import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		n: 'design1GridHoverSelectedBackgroundColor',
		cp: 'background-color',
		dn: 'Design 1 Grid Hover or Selected Background Color',
		de: 'Design 1 Grid Hover or Selected Background Color',
		dv: '#EEEEEE',
		np: true,
		sel: '.comp.compTable._design1 ._eachTableGrid._dataGrid:hover, .comp.compTable._design1 ._eachTableGrid._dataGrid._selected',
	},
	{
		n: 'design2GridHoverSelectedBackgroundColor',
		cp: 'background-color',
		dn: 'Design 2 Grid Hover or Selected Background Color',
		de: 'Design 2 Grid Hover or Selected Background Color',
		dv: '#EEEEEE',
		np: true,
		sel: '.comp.compTable._design2 ._eachTableGrid._dataGrid:hover, .comp.compTable._design2 ._eachTableGrid._dataGrid._selected',
	},
	{
		n: 'design3GridHoverSelectedBackgroundColor',
		cp: 'background-color',
		dn: 'Design 3 Grid Hover or Selected Background Color',
		de: 'Design 3 Grid Hover or Selected Background Color',
		dv: '#EEEEEE',
		np: true,
		sel: '.comp.compTable._design3 ._eachTableGrid._dataGrid:hover, .comp.compTable._design3 ._eachTableGrid._dataGrid._selected',
	},
	{
		n: 'design4GridHoverSelectedBackgroundColor',
		cp: 'background-color',
		dn: 'Design 4 Grid Hover or Selected Background Color',
		de: 'Design 4 Grid Hover or Selected Background Color',
		dv: '#EEEEEE',
		np: true,
		sel: '.comp.compTable._design4 ._eachTableGrid._dataGrid:hover, .comp.compTable._design4 ._eachTableGrid._dataGrid._selected',
	},
	{
		n: 'design5GridHoverSelectedBackgroundColor',
		cp: 'background-color',
		dn: 'Design 5 Grid Hover or Selected Background Color',
		de: 'Design 5 Grid Hover or Selected Background Color',
		dv: '#EEEEEE',
		np: true,
		sel: '.comp.compTable._design5 ._eachTableGrid._dataGrid:hover, .comp.compTable._design5 ._eachTableGrid._dataGrid._selected',
	},
	{
		n: 'design6GridHoverSelectedBackgroundColor',
		cp: 'background-color',
		dn: 'Design 6 Grid Hover or Selected Background Color',
		de: 'Design 6 Grid Hover or Selected Background Color',
		dv: '#EEEEEE',
		np: true,
		sel: '.comp.compTable._design6 ._eachTableGrid._dataGrid:hover, .comp.compTable._design6 ._eachTableGrid._dataGrid._selected',
	},
	{
		n: 'design7GridHoverSelectedBackgroundColor',
		cp: 'background-color',
		dn: 'Design 7 Grid Hover or Selected Background Color',
		de: 'Design 7 Grid Hover or Selected Background Color',
		dv: '#EEEEEE',
		np: true,
		sel: '.comp.compTable._design7 ._eachTableGrid._dataGrid:hover, .comp.compTable._design7 ._eachTableGrid._dataGrid._selected',
	},
	{
		n: 'design8GridHoverSelectedBackgroundColor',
		cp: 'background-color',
		dn: 'Design 8 Grid Hover or Selected Background Color',
		de: 'Design 8 Grid Hover or Selected Background Color',
		dv: '#EEEEEE',
		np: true,
		sel: '.comp.compTable._design8 ._eachTableGrid._dataGrid:hover, .comp.compTable._design8 ._eachTableGrid._dataGrid._selected',
	},
	{
		n: 'design9GridHoverSelectedBackgroundColor',
		cp: 'background-color',
		dn: 'Design 9 Grid Hover or Selected Background Color',
		de: 'Design 9 Grid Hover or Selected Background Color',
		dv: '#EEEEEE',
		np: true,
		sel: '.comp.compTable._design9 ._eachTableGrid._dataGrid:hover, .comp.compTable._design9 ._eachTableGrid._dataGrid._selected',
	},
	{
		n: 'design10GridHoverSelectedBackgroundColor',
		cp: 'background-color',
		dn: 'Design 10 Grid Hover or Selected Background Color',
		de: 'Design 10 Grid Hover or Selected Background Color',
		dv: '#EEEEEE',
		np: true,
		sel: '.comp.compTable._design10 ._eachTableGrid._dataGrid:hover, .comp.compTable._design10 ._eachTableGrid._dataGrid._selected',
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.dv)
		.map(({ n: name, dv: defaultValue }) => [name, defaultValue!]),
);
