import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'MD Navigator Gap',
		displayName: 'MD Navigator Gap Default Design',
		name: 'mDNavigatorGapDefaultDesign',
		defaultValue: '0',
		cssProperty: 'gap',
		selector: '.comp.compMarkdownNav._markdown',
		noPrefix: true,
	},
	{
		groupName: 'MD Navigator Padding',
		displayName: 'MD Navigator Padding Default Design',
		name: 'mDNavigatorPaddingDefaultDesign',
		defaultValue: '0',
		cssProperty: 'padding',
		selector: '.comp.compMarkdownNav._markdown',
		noPrefix: true,
	},
	{
		groupName: 'MD Navigator Margin',
		displayName: 'MD Navigator Margin Default Design',
		name: 'mDNavigatorMarginDefaultDesign',
		defaultValue: '0',
		cssProperty: 'margin',
		selector: '.comp.compMarkdownNav._markdown',
		noPrefix: true,
	},

	{
		groupName: 'MD H1 Link Padding',
		displayName: 'MD H1 Link Padding Default Design',
		name: 'mDH1LinkPaddingDefaultDesign',
		defaultValue: '0',
		cssProperty: 'padding',
		selector: '.comp.compMarkdownNav._markdown a.h1',
		noPrefix: true,
	},
	{
		groupName: 'MD H1 Link Margin',
		displayName: 'MD H1 Link Margin Default Design',
		name: 'mDH1LinkMarginDefaultDesign',
		defaultValue: '0',
		cssProperty: 'margin',
		selector: '.comp.compMarkdownNav._markdown a.h1',
		noPrefix: true,
	},
	{
		groupName: 'MD H1 Link Color',
		displayName: 'MD H1 Link Color Default Design',
		name: 'mDLinkColorDefaultDesign',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compMarkdownNav._markdown a.h1',
		noPrefix: true,
	},
	{
		groupName: 'MD H1 Link Text Decoration',
		displayName: 'MD H1 Link Text Decoration Default Design',
		name: 'mDH1LinkTextDecorationDefaultDesign',
		defaultValue: 'none',
		cssProperty: 'text-decoration',
		selector: '.comp.compMarkdownNav._markdown a.h1',
		noPrefix: true,
	},
	{
		groupName: 'MD H1 Link Font',
		displayName: 'MD H1 Link Font Default Design',
		name: 'mDH1LinkFontDefaultDesign',
		defaultValue: '<linkFont>',
		cssProperty: 'font',
		selector: '.comp.compMarkdownNav._markdown a.h1',
		noPrefix: true,
	},

	{
		groupName: 'MD H2 Link Padding',
		displayName: 'MD H2 Link Padding Default Design',
		name: 'mDH2LinkPaddingDefaultDesign',
		defaultValue: '0',
		cssProperty: 'padding',
		selector: '.comp.compMarkdownNav._markdown a.h2',
		noPrefix: true,
	},
	{
		groupName: 'MD H2 Link Margin',
		displayName: 'MD H2 Link Margin Default Design',
		name: 'mDH2LinkMarginDefaultDesign',
		defaultValue: '0',
		cssProperty: 'margin',
		selector: '.comp.compMarkdownNav._markdown a.h2',
		noPrefix: true,
	},
	{
		groupName: 'MD H2 Link Color',
		displayName: 'MD H2 Link Color Default Design',
		name: 'mDH2LinkColorDefaultDesign',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compMarkdownNav._markdown a.h2',
		noPrefix: true,
	},
	{
		groupName: 'MD H1 Link Text Decoration',
		displayName: 'MD H2 Link Text Decoration Default Design',
		name: 'mDH2LinkTextDecorationDefaultDesign',
		defaultValue: 'none',
		cssProperty: 'text-decoration',
		selector: '.comp.compMarkdownNav._markdown a.h2',
		noPrefix: true,
	},
	{
		groupName: 'MD H2 Link Font',
		displayName: 'MD H2 Link Font Default Design',
		name: 'mDH2LinkFontDefaultDesign',
		defaultValue: '<linkFont>',
		cssProperty: 'font',
		selector: '.comp.compMarkdownNav._markdown a.h2',
		noPrefix: true,
	},

	{
		groupName: 'MD H1 Link Color On Hover',
		displayName: 'MD H1 Link Color Default Design On Hover',
		name: 'mDLinkColorOnHoverDefaultDesign',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compMarkdownNav._markdown a.h1:hover',
		noPrefix: true,
	},
	{
		groupName: 'MD H1 Link Text Decoration On Hover',
		displayName: 'MD H1 Link Text Decoration Default Design On Hover',
		name: 'mDH1LinkTextDecorationOnHoverDefaultDesign',
		defaultValue: 'none',
		cssProperty: 'text-decoration',
		selector: '.comp.compMarkdownNav._markdown a.h1:hover',
		noPrefix: true,
	},
	{
		groupName: 'MD H1 Link Font On Hover',
		displayName: 'MD H1 Link Font Default Design On Hover',
		name: 'mDH1LinkFontOnHoverDefaultDesign',
		defaultValue: '<linkFont>',
		cssProperty: 'font',
		selector: '.comp.compMarkdownNav._markdown a.h1:hover',
		noPrefix: true,
	},

	{
		groupName: 'MD H1 Link Color On Visited',
		displayName: 'MD H1 Link Color Default Design On Visited',
		name: 'mDLinkColorOnVisitedDefaultDesign',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compMarkdownNav._markdown a.h1:visited',
		noPrefix: true,
	},
	{
		groupName: 'MD H1 Link Text Decoration On Visited',
		displayName: 'MD H1 Link Text Decoration Default Design On Visited',
		name: 'mDH1LinkTextDecorationOnVisitedDefaultDesign',
		defaultValue: 'none',
		cssProperty: 'text-decoration',
		selector: '.comp.compMarkdownNav._markdown a.h1:visited',
		noPrefix: true,
	},
	{
		groupName: 'MD H1 Link Font On Visited',
		displayName: 'MD H1 Link Font Default Design On Visited',
		name: 'mDH1LinkFontOnVisitedDefaultDesign',
		defaultValue: '<linkFont>',
		cssProperty: 'font',
		selector: '.comp.compMarkdownNav._markdown a.h1:visited',
		noPrefix: true,
	},

	{
		groupName: 'MD H2 Link Color On Hover',
		displayName: 'MD H2 Link Color Default Design On Hover',
		name: 'mDLinkColorOnHoverDefaultDesign',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compMarkdownNav._markdown a.h2:hover',
		noPrefix: true,
	},
	{
		groupName: 'MD H2 Link Text Decoration On Hover',
		displayName: 'MD H2 Link Text Decoration Default Design On Hover',
		name: 'mDH2LinkTextDecorationOnHoverDefaultDesign',
		defaultValue: 'none',
		cssProperty: 'text-decoration',
		selector: '.comp.compMarkdownNav._markdown a.h2:hover',
		noPrefix: true,
	},
	{
		groupName: 'MD H2 Link Font On Hover',
		displayName: 'MD H2 Link Font Default Design On Hover',
		name: 'mDH2LinkFontOnHoverDefaultDesign',
		defaultValue: '<linkFont>',
		cssProperty: 'font',
		selector: '.comp.compMarkdownNav._markdown a.h2:hover',
		noPrefix: true,
	},

	{
		groupName: 'MD H2 Link Color On Visited',
		displayName: 'MD H2 Link Color Default Design On Visited',
		name: 'mDLinkColorOnVisitedDefaultDesign',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compMarkdownNav._markdown a.h2:visited',
		noPrefix: true,
	},
	{
		groupName: 'MD H2 Link Text Decoration On Visited',
		displayName: 'MD H2 Link Text Decoration Default Design On Visited',
		name: 'mDH2LinkTextDecorationOnVisitedDefaultDesign',
		defaultValue: 'none',
		cssProperty: 'text-decoration',
		selector: '.comp.compMarkdownNav._markdown a.h2:visited',
		noPrefix: true,
	},
	{
		groupName: 'MD H2 Link Font On Visited',
		displayName: 'MD H2 Link Font Default Design On Visited',
		name: 'mDH2LinkFontOnVisitedDefaultDesign',
		defaultValue: '<linkFont>',
		cssProperty: 'font',
		selector: '.comp.compMarkdownNav._markdown a.h2:visited',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
