import {
	SCHEMA_ANY_COMP_PROP,
	SCHEMA_BOOL_COMP_PROP,
	SCHEMA_NUM_COMP_PROP,
	SCHEMA_STRING_COMP_PROP,
} from '../../constants';
import {
	ComponentPropertyDefinition,
	ComponentPropertyGroup,
	ComponentStylePropertyDefinition,
} from '../../types/common';
import { COMMON_COMPONENT_PROPERTIES, COMPONENT_STYLE_GROUP_PROPERTIES } from '../util/properties';

const propertiesDefinition: Array<ComponentPropertyDefinition> = [
	{
		name: 'hideGrid',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Hide Grid',
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		...COMMON_COMPONENT_PROPERTIES.colorScheme,
		enumValues: [
			{
				name: '_primary',
				displayName: 'Primary Color Scheme',
				description: 'Default Color Scheme',
			},
		],
	},
	{
		name: 'chartType',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Chart Type',
		group: ComponentPropertyGroup.BASIC,
		defaultValue: 'ordinary',
		enumValues: [
			{ name: 'ordinary', displayName: 'Regular (Line or Bar)' },
			{ name: 'radial', displayName: 'Radial (Pie or Doughnut or Polar Area)' },
			{ name: 'radar', displayName: 'Radar' },
			{ name: 'dot', displayName: 'Dot (Bubble or Scatter)' },
			{ name: 'gannt', displayName: 'Gannt' },
			{ name: 'waffle', displayName: 'Waffle' },
			{ name: 'gauge', displayName: 'Gauge Chart' },
		],
	},

	{
		name: 'data',
		schema: SCHEMA_ANY_COMP_PROP,
		defaultValue: [10, 20, 30, 40, 50],
		displayName: 'Data',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'dataColors',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Data Colors',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'xAxisType',
		schema: SCHEMA_STRING_COMP_PROP,
		defaultValue: 'oridnal',
		displayName: 'X Axis Type',
		group: ComponentPropertyGroup.DATA,
		enumValues: [
			{ name: 'oridnal', displayName: 'Oridnal' },
			{ name: 'value', displayName: 'Value' },
			{ name: 'time', displayName: 'Time' },
			{ name: 'log', displayName: 'Logirthamic' },
		],
	},
	{
		name: 'xAxisStartPosition',
		schema: SCHEMA_STRING_COMP_PROP,
		defaultValue: 'bottom',
		displayName: 'X Axis Start Position',
		group: ComponentPropertyGroup.DATA,
		enumValues: [
			{ name: 'bottom', displayName: 'Bottom' },
			{ name: 'top', displayName: 'Top' },
			{ name: 'center', displayName: 'Center' },
		],
	},
	{
		name: 'xAxisLabels',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'X Axis Labels for Ordinal Axis',
		group: ComponentPropertyGroup.DATA,
		multiValued: true,
	},
	{
		name: 'xAxisLabelsSort',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Sort X Axis Labels for Ordinal Axis',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'xAxisMin',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'X Axis Min',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'xAxisSuggestedMin',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'X Axis Suggested Min',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'xAxisMax',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'X Axis Max',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'xAxisSuggestedMax',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'X Axis Suggested Max',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'xAxisReverse',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'X Axis Reverse',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'xAxisHideTicks',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Hide X Axis Ticks',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'xAxisHideLabels',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Hide X Axis Labels',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'xAxisDataPath',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'X Axis Data Path in Object',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'hideXAxis',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Hide X Axis',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'xAxisTitle',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'X Axis Title',
		group: ComponentPropertyGroup.DATA,
	},

	{
		name: 'yAxisType',
		schema: SCHEMA_STRING_COMP_PROP,
		defaultValue: 'oridnal',
		displayName: 'Y Axis Type',
		group: ComponentPropertyGroup.DATA,
		enumValues: [
			{ name: 'oridnal', displayName: 'Oridnal' },
			{ name: 'value', displayName: 'Value' },
			{ name: 'time', displayName: 'Time' },
			{ name: 'log', displayName: 'Logirthamic' },
			{ name: 'derivied', displayName: 'Derivied' },
		],
	},
	{
		name: 'yAxisStartPosition',
		schema: SCHEMA_STRING_COMP_PROP,
		defaultValue: 'left',
		displayName: 'Y Axis Start Position',
		group: ComponentPropertyGroup.DATA,
		enumValues: [
			{ name: 'left', displayName: 'Left' },
			{ name: 'right', displayName: 'Right' },
			{ name: 'center', displayName: 'Center' },
		],
	},
	{
		name: 'yAxisLabels',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Y Axis Labels for Ordinal Axis',
		group: ComponentPropertyGroup.DATA,
		multiValued: true,
	},
	{
		name: 'yAxisLabelsSort',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Sort Y Axis Labels for Ordinal Axis',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'yAxisMin',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'Y Axis Min',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'yAxisSuggestedMin',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'Y Axis Suggested Min',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'yAxisMax',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'Y Axis Max',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'yAxisSuggestedMax',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'Y Axis Suggested Max',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'yAxisReverse',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Y Axis Reverse',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'yAxisHideTicks',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Hide Y Axis Ticks',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'yAxisHideLabels',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Hide Y Axis Labels',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'yAxisDataPath',
		schema: SCHEMA_STRING_COMP_PROP,
		multiValued: true,
		displayName: 'Y Axis Data Path in Object',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'yAxisDataStyle',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Y Axis Data Style',
		group: ComponentPropertyGroup.DATA,
		multiValued: true,
		enumValues: [
			{ name: 'line', displayName: 'Line (Line Graph)' },
			{ name: 'steppedLine', displayName: 'Stepped Line (Line Graph)' },
			{ name: 'dashedLine', displayName: 'Dashed Line (Line Graph)' },
			{ name: 'dottedLine', displayName: 'Dotted Line (Line Graph)' },
			{ name: 'filledLine', displayName: 'Filled Line (Line Graph)' },
			{ name: 'filledSteppedLine', displayName: 'Filled Stepped Line (Line Graph)' },
			{ name: 'filledDashedLine', displayName: 'Filled Dashed Line (Line Graph)' },
			{ name: 'filledDottedLine', displayName: 'Filled Dotted Line (Line Graph)' },
			{ name: 'bar', displayName: 'Bar (Bar Graph)' },
			{ name: 'filledBar', displayName: 'Filled Bar (Bar Graph)' },
			{ name: 'filledDashedBar', displayName: 'Filled Dashed Bar (Bar Graph)' },
			{ name: 'filledDottedBar', displayName: 'Filled Dotted Bar (Bar Graph)' },
			{ name: 'filledSteppedBar', displayName: 'Filled Stepped Bar (Bar Graph)' },
			{ name: 'filledLine', displayName: 'Filled Line (Line Graph)' },
			{ name: 'filledSteppedLine', displayName: 'Filled Stepped Line (Line Graph)' },
			{ name: 'filledDashedLine', displayName: 'Filled Dashed Line (Line Graph)' },
			{ name: 'filledDottedLine', displayName: 'Filled Dotted Line (Line Graph)' },
			{ name: 'filledPolarArea', displayName: 'Filled Polar Area (Polar Area Graph)' },
			{ name: 'filledBubble', displayName: 'Filled Bubble (Bubble Graph)' },
			{ name: 'filledScatter', displayName: 'Filled Scatter (Scatter Graph)' },
		],
	},
	{
		name: 'hideYAxis',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Hide Y Axis',
		group: ComponentPropertyGroup.DATA,
	},
	{
		name: 'xAxisTitle',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'X Axis Title',
		group: ComponentPropertyGroup.DATA,
	},

	{
		name: 'stackedAxis',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Stacked Axis',
		group: ComponentPropertyGroup.DATA,
		defaultValue: 'none',
		enumValues: [
			{ name: 'none', displayName: 'None' },
			{ name: 'x', displayName: 'X Axis' },
			{ name: 'y', displayName: 'Y Axis' },
			{ name: 'z', displayName: 'Z Axis' },
		],
	},

	{
		name: 'legendPosition',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Legend Position',
		group: ComponentPropertyGroup.BASIC,
		defaultValue: 'top',
		enumValues: [
			{ name: 'top', displayName: 'Top' },
			{ name: 'bottom', displayName: 'Bottom' },
			{ name: 'left', displayName: 'Left' },
			{ name: 'right', displayName: 'Right' },
			{ name: 'none', displayName: 'None' },
		],
	},

	{
		name: 'pointType',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Point Type',
		group: ComponentPropertyGroup.BASIC,
		multiValued: true,
		defaultValue: 'circle',
		enumValues: [
			{ name: 'circle', displayName: 'Circle' },
			{ name: 'filledCircle', displayName: 'Filled Circle' },
			{ name: 'cross', displayName: 'Cross' },
			{ name: 'x', displayName: 'X' },
			{ name: 'dash', displayName: 'Dash' },
			{ name: 'line', displayName: 'Line' },
			{ name: 'verticalLine', displayName: 'Vertical Line' },
			{ name: 'rect', displayName: 'Rectangle' },
			{ name: 'filledRect', displayName: 'Filled Rectangle' },
			{ name: 'rectRounded', displayName: 'Rectangle Rounded' },
			{ name: 'filledRectRounded', displayName: 'Filled Rectangle Rounded' },
			{ name: 'rectRot', displayName: 'Rectangle Rotated' },
			{ name: 'filledRectRot', displayName: 'Filled Rectangle Rotated' },
			{ name: 'star', displayName: 'Star' },
			{ name: 'filledStar', displayName: 'Filled Star' },
			{ name: 'triangle', displayName: 'Triangle' },
			{ name: 'filledTriangle', displayName: 'Filled Triangle' },
			{ name: 'triangleRot', displayName: 'Triangle Rotated' },
			{ name: 'filledTriangleRot', displayName: 'Filled Triangle Rotated' },
			{ name: 'none', displayName: 'None' },
		],
	},

	{
		name: 'invertAxis',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Invert Axis',
		group: ComponentPropertyGroup.ADVANCED,
	},

	COMMON_COMPONENT_PROPERTIES.visibility,
];

const stylePropertiesDefinition: ComponentStylePropertyDefinition = {
	'': [
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.typography.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.effects.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.background.type,
	],
};

export { propertiesDefinition, stylePropertiesDefinition };
