import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'Default',
		displayName: 'Default Toggle Button Height',
		name: 'defaultToggleButtonHeight',
		defaultValue: '24px',
		cssProperty: 'height',
		selector: '.comp.compToggleButton._default',
		noPrefix: true,
	},
	{
		groupName: 'Outlined',
		displayName: 'Outlined Toggle Button Height',
		name: 'outlinedToggleButtonHeight',
		defaultValue: '24px',
		cssProperty: 'height',
		selector: '.comp.compToggleButton._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Squared',
		displayName: 'Squared Toggle Button Height',
		name: 'squaredToggleButtonHeight',
		defaultValue: '24px',
		cssProperty: 'height',
		selector: '.comp.compToggleButton._squared',
		noPrefix: true,
	},
	{
		groupName: 'BigKnob',
		displayName: 'Big Knob Toggle Button Height',
		name: 'bigKnobToggleButtonHeight',
		defaultValue: '18px',
		cssProperty: 'height',
		selector: '.comp.compToggleButton._bigknob',
		noPrefix: true,
	},
	{
		groupName: 'Small',
		displayName: 'Small Toggle Button Height',
		name: 'smallToggleButtonHeight',
		defaultValue: '24px',
		cssProperty: 'height',
		selector: '.comp.compToggleButton._small',
		noPrefix: true,
	},

	{
		groupName: 'Background',
		displayName: 'Primary Track Background Color',
		name: 'primaryToggleCompBGColor',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector:
			'.comp.compToggleButton._default._primary._on, .comp.compToggleButton._outlined._primary._on, .comp.compToggleButton._squared._primary._on, .comp.compToggleButton._bigknob._primary._on, .comp.compToggleButton._small._primary._on, .comp.compToggleButton._outlined._primary ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Background',
		displayName: 'Secondary Track Background Color',
		name: 'secondaryToggleCompBGColor',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector:
			'.comp.compToggleButton._default._secondary._on, .comp.compToggleButton._outlined._secondary._on, .comp.compToggleButton._squared._secondary._on, .comp.compToggleButton._bigknob._secondary._on, .comp.compToggleButton._small._secondary._on, .comp.compToggleButton._outlined._secondary ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Background',
		displayName: 'Tertiary Track Background Color',
		name: 'tertiaryToggleCompBGColor',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector:
			'.comp.compToggleButton._default._tertiary._on, .comp.compToggleButton._outlined._tertiary._on, .comp.compToggleButton._squared._tertiary._on, .comp.compToggleButton._bigknob._tertiary._on, .comp.compToggleButton._small._tertiary._on, .comp.compToggleButton._outlined._tertiary ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Background',
		displayName: 'Quaternary Track Background Color',
		name: 'quaternaryToggleCompBGColor',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector:
			'.comp.compToggleButton._default._quaternary._on, .comp.compToggleButton._outlined._quaternary._on, .comp.compToggleButton._squared._quaternary._on, .comp.compToggleButton._bigknob._quaternary._on, .comp.compToggleButton._small._quaternary._on, .comp.compToggleButton._outlined._quaternary ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Background',
		displayName: 'Quinary Track Background Color',
		name: 'quinaryToggleCompBGColor',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector:
			'.comp.compToggleButton._default._quinary._on, .comp.compToggleButton._outlined._quinary._on, .comp.compToggleButton._squared._quinary._on, .comp.compToggleButton._bigknob._quinary._on, .comp.compToggleButton._small._quinary._on, .comp.compToggleButton._outlined._quinary ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Background',
		displayName: 'Gradient One Track Background Color',
		name: 'gradientOneToggleCompBGColor',
		defaultValue: '<gradientColorOne>',
		cssProperty: 'background',
		selector:
			'.comp.compToggleButton._default._gradient1._on, .comp.compToggleButton._outlined._gradient1._on, .comp.compToggleButton._squared._gradient1._on, .comp.compToggleButton._bigknob._gradient1._on, .comp.compToggleButton._small._gradient1._on, .comp.compToggleButton._outlined._gradient1 ._knob',
		noPrefix: true,
	},

	{
		groupName: 'Background',
		displayName: 'Grey Background',
		name: 'greyToggleCompBgColor',
		defaultValue: '<backgroundColorNine>',
		cssProperty: 'background',
		selector:
			'.comp.compToggleButton._default, .comp.compToggleButton._squared, .comp.compToggleButton._bigknob, .comp.compToggleButton._small',
		noPrefix: true,
	},
	{
		groupName: 'Background',
		displayName: 'Light Background',
		name: 'lightToggleCompBgColor',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector:
			'.comp.compToggleButton._outlined, .comp.compToggleButton._outlined._on ._knob, .comp.compToggleButton._default ._knob, .comp.compToggleButton._squared ._knob, .comp.compToggleButton._bigknob ._knob, .comp.compToggleButton._small ._knob',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Toggle Knob Height',
		name: 'defaultToggleKnobHeight',
		defaultValue: '18px',
		cssProperty: 'height',
		selector: '.comp.compToggleButton._default ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Outlined',
		displayName: 'Outlined Toggle Knob Height',
		name: 'outlinedToggleKnobHeight',
		defaultValue: '18px',
		cssProperty: 'height',
		selector: '.comp.compToggleButton._outlined ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Squared',
		displayName: 'Squared Toggle Knob Height',
		name: 'squaredToggleKnobHeight',
		defaultValue: '18px',
		cssProperty: 'height',
		selector: '.comp.compToggleButton._squared ._knob',
		noPrefix: true,
	},
	{
		groupName: 'BigKnob',
		displayName: 'Big Knob Toggle Knob Height',
		name: 'bigKnobToggleKnobHeight',
		defaultValue: '24px',
		cssProperty: 'height',
		selector: '.comp.compToggleButton._bigknob ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Small',
		displayName: 'Small Toggle Knob Height',
		name: 'smallToggleKnobHeight',
		defaultValue: '12px',
		cssProperty: 'height',
		selector: '.comp.compToggleButton._small ._knob',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Toggle Knob Width',
		name: 'defaultToggleKnobWidth',
		defaultValue: '<defaultToggleKnobHeight>',
		cssProperty: 'width',
		selector: '.comp.compToggleButton._default ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Outlined',
		displayName: 'Outlined Toggle Knob Width',
		name: 'outlinedToggleKnobWidth',
		defaultValue: '<outlinedToggleKnobHeight>',
		cssProperty: 'width',
		selector: '.comp.compToggleButton._outlined ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Squared',
		displayName: 'Squared Toggle Knob Width',
		name: 'squaredToggleKnobWidth',
		defaultValue: '<squaredToggleKnobHeight>',
		cssProperty: 'width',
		selector: '.comp.compToggleButton._squared ._knob',
		noPrefix: true,
	},
	{
		groupName: 'BigKnob',
		displayName: 'Big Knob Toggle Knob Width',
		name: 'bigKnobToggleKnobWidth',
		defaultValue: '<bigKnobToggleKnobHeight>',
		cssProperty: 'width',
		selector: '.comp.compToggleButton._bigknob ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Small',
		displayName: 'Small Toggle Knob Width',
		name: 'smallToggleKnobWidth',
		defaultValue: '<smallToggleKnobHeight>',
		cssProperty: 'width',
		selector: '.comp.compToggleButton._small ._knob',
		noPrefix: true,
	},

	{
		groupName: 'Padding',
		displayName: 'Knob Padding',
		name: 'toggleKnobPadding',
		defaultValue: '5px',
		cssProperty: 'padding',
		selector:
			'.comp.compToggleButton._default ._knob._withText, .comp.compToggleButton._outlined ._knob._withText, .comp.compToggleButton._squared ._knob._withText, .comp.compToggleButton._bigknob ._knob._withText, .comp.compToggleButton._small ._knob._withText',
		noPrefix: true,
	},

	{
		groupName: 'Color',
		displayName: 'Grey Color',
		name: 'greyToggleCompTextColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector:
			'.comp.compToggleButton._default ._toggleButtonLabel, .comp.compToggleButton._outlined ._toggleButtonLabel, .comp.compToggleButton._squared ._toggleButtonLabel, .comp.compToggleButton._bigknob ._toggleButtonLabel, .comp.compToggleButton._small ._toggleButtonLabel, .comp.compToggleButton._default._on ._knob._withText ._toggleButtonLabel, .comp.compToggleButton._outlined._on ._knob._withText ._toggleButtonLabel, .comp.compToggleButton._squared._on ._knob._withText ._toggleButtonLabel, .comp.compToggleButton._bigknob._on ._knob._withText ._toggleButtonLabel, .comp.compToggleButton._small._on ._knob._withText ._toggleButtonLabel',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Light Color',
		name: 'lightToggleCompTextColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compToggleButton._default._on ._toggleButtonLabel, .comp.compToggleButton._outlined._on ._toggleButtonLabel, .comp.compToggleButton._squared._on ._toggleButtonLabel, .comp.compToggleButton._bigknob._on ._toggleButtonLabel, .comp.compToggleButton._small._on ._toggleButtonLabel, .comp.compToggleButton._outlined ._knob._withText ._toggleButtonLabel',
		noPrefix: true,
	},

	{
		groupName: 'Border',
		displayName: 'Default Toggle Button Border',
		name: 'defaultToggleButtonBorder',
		cssProperty: 'border',
		selector: '.comp.compToggleButton._default',
		noPrefix: true,
	},
	{
		groupName: 'Border',
		displayName: 'Outlined Toggle Button Border',
		name: 'outlinedToggleButtonBorder',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compToggleButton._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Border',
		displayName: 'Squared Toggle Button Border',
		name: 'squaredToggleButtonBorder',
		cssProperty: 'border',
		selector: '.comp.compToggleButton._squared',
		noPrefix: true,
	},
	{
		groupName: 'Border',
		displayName: 'Big Knob Toggle Button Border',
		name: 'bigKnobToggleButtonBorder',
		cssProperty: 'border',
		selector: '.comp.compToggleButton._bigknob',
		noPrefix: true,
	},
	{
		groupName: 'Border',
		displayName: 'Small Toggle Button Border',
		name: 'smallToggleButtonBorder',
		cssProperty: 'border',
		selector: '.comp.compToggleButton._small',
		noPrefix: true,
	},

	{
		groupName: 'Border Color',
		displayName: 'Primary Track Border Color',
		name: 'primaryToggleCompBorderColor',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-color',
		selector: '.comp.compToggleButton._outlined._primary',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Secondary Track Border Color',
		name: 'secondaryToggleCompBorderColor',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compToggleButton._outlined._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Tertiary Track Border Color',
		name: 'tertiaryToggleCompBorderColor',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compToggleButton._outlined._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Quaternary Track Border Color',
		name: 'quaternaryToggleCompBorderColor',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compToggleButton._outlined._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Quinary Track Border Color',
		name: 'quinaryToggleCompBorderColor',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compToggleButton._outlined._quinary',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Gradient One Track Border Color',
		name: 'gradientOneToggleCompBorderColor',
		defaultValue: '<gradientColorOne>',
		cssProperty: 'border-color',
		selector: '.comp.compToggleButton._outlined._gradient1',
		noPrefix: true,
	},

	{
		groupName: 'Border Color',
		displayName: 'Grey Border Color',
		name: 'greyToggleCompBorderColor',
		defaultValue: '<backgroundColorNine>',
		cssProperty: 'border-color',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Light Border Color',
		name: 'lightToggleCompBorderColor',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'border-color',
		noPrefix: true,
	},

	{
		groupName: 'Border Radius',
		displayName: 'Round Border',
		name: 'toggleCompRoundBorder',
		defaultValue: '50%',
		cssProperty: 'border-radius',
		selector:
			'.comp.compToggleButton._default ._knob, .comp.compToggleButton._outlined ._knob, .comp.compToggleButton._small ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Border Radius',
		displayName: 'Rounded Border With Width',
		name: 'toggleCompRoundBorderWithWidth',
		defaultValue: '100px',
		cssProperty: 'border-radius',
		selector:
			'.comp.compToggleButton._default, .comp.compToggleButton._outlined, .comp.compToggleButton._bigknob, .comp.compToggleButton._bigknob ._knob, .comp.compToggleButton._default ._knob._withText, .comp.compToggleButton._outlined ._knob._withText, .comp.compToggleButton._bigknob ._knob._withText, .comp.compToggleButton._small ._knob._withText',
		noPrefix: true,
	},
	{
		groupName: 'Border Radius',
		displayName: 'Squared Border',
		name: 'toggleCompSquaredBorder',
		defaultValue: '2px',
		cssProperty: 'border-radius',
		selector:
			'.comp.compToggleButton._squared, .comp.compToggleButton._squared ._knob, .comp.compToggleButton._squared ._knob._withText',
		noPrefix: true,
	},
	{
		groupName: 'Border Radius',
		displayName: 'Small Round Border',
		name: 'toggleCompSmallRoundBorder',
		defaultValue: '50px',
		cssProperty: 'border-radius',
		selector: '.comp.compToggleButton._small',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Toggle Knob Width',
		name: 'defaultToggleKnobWithTextWidth',
		defaultValue: 'auto',
		cssProperty: 'width',
		selector: '.comp.compToggleButton._default ._knob._withText',
		noPrefix: true,
	},
	{
		groupName: 'Outlined',
		displayName: 'Outlined Toggle Knob Width',
		name: 'outlinedToggleKnobWithTextWidth',
		defaultValue: 'auto',
		cssProperty: 'width',
		selector: '.comp.compToggleButton._outlined ._knob._withText',
		noPrefix: true,
	},
	{
		groupName: 'Squared',
		displayName: 'Squared Toggle Knob Width',
		name: 'squaredToggleKnobWithTextWidth',
		defaultValue: 'auto',
		cssProperty: 'width',
		selector: '.comp.compToggleButton._squared ._knob._withText',
		noPrefix: true,
	},
	{
		groupName: 'BigKnob',
		displayName: 'Big Knob Toggle Knob Width',
		name: 'bigKnobToggleKnobWithTextWidth',
		defaultValue: 'auto',
		cssProperty: 'width',
		selector: '.comp.compToggleButton._bigknob ._knob._withText',
		noPrefix: true,
	},
	{
		groupName: 'Small',
		displayName: 'Small Toggle Knob Width',
		name: 'smallToggleKnobWithTextWidth',
		defaultValue: 'auto',
		cssProperty: 'width',
		selector: '.comp.compToggleButton._small ._knob._withText',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Toggle Knob Margin in ON State',
		name: 'defaultToggleKnobMarginOnState',
		defaultValue: '0px 0px 0px -3px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._default._on ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Outlined',
		displayName: 'Outlined Toggle Knob Margin in ON State',
		name: 'outlinedToggleKnobMarginOnState',
		defaultValue: '0px 0px 0px -3px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._outlined._on ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Squared',
		displayName: 'Squared Toggle Knob Margin in ON State',
		name: 'squaredToggleKnobMarginOnState',
		defaultValue: '0px 0px 0px -3px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._squared._on ._knob',
		noPrefix: true,
	},
	{
		groupName: 'BigKnob',
		displayName: 'BigKnob Toggle Knob Margin in ON State',
		name: 'bigKnobToggleKnobMarginOnState',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._bigknob._on ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Small',
		displayName: 'Small Toggle Knob Margin',
		name: 'smallToggleKnobMarginOnState',
		defaultValue: '0px 0px 0px -6px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._small._on ._knob',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Toggle Knob Margin in OFF State',
		name: 'defaultToggleKnobMarginOffState',
		defaultValue: '0px 0px 0px 3px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._default._off ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Outlined',
		displayName: 'Outlined Toggle Knob Margin in OFF State',
		name: 'outlinedToggleKnobMarginOffState',
		defaultValue: '0px 0px 0px 3px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._outlined._off ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Squared',
		displayName: 'Squared Toggle Knob Margin in OFF State',
		name: 'squaredToggleKnobMarginOffState',
		defaultValue: '0px 0px 0px 3px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._squared._off ._knob',
		noPrefix: true,
	},
	{
		groupName: 'BigKnob',
		displayName: 'BigKnob Toggle Knob Margin in OFF State',
		name: 'bigKnobToggleKnobMarginOffState',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._bigknob._off ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Small',
		displayName: 'Small Toggle Knob Margin in OFF State',
		name: 'smallToggleKnobMarginOffState',
		defaultValue: '0px 0px 0px 6px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._small._off ._knob',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Toggle Label Margin in ON State',
		name: 'defaultToggleLabelMarginOnState',
		defaultValue: '0px 0px 0px -3px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._default._off ._toggleButtonLabel._ontrack',
		noPrefix: true,
	},
	{
		groupName: 'Outlined',
		displayName: 'Outlined Toggle Label Margin in ON State',
		name: 'outlinedToggleLabelMarginOnState',
		defaultValue: '0px 0px 0px -3px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._outlined._off ._toggleButtonLabel._ontrack',
		noPrefix: true,
	},
	{
		groupName: 'Squared',
		displayName: 'Squared Toggle Label Margin in ON State',
		name: 'squaredToggleLabelMarginOnState',
		defaultValue: '0px 0px 0px -3px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._squared._off ._toggleButtonLabel._ontrack',
		noPrefix: true,
	},
	{
		groupName: 'BigKnob',
		displayName: 'BigKnob Toggle Label Margin in ON State',
		name: 'bigKnobToggleLabelMarginOnState',
		defaultValue: '0px 0px 0px -5px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._bigknob._off ._toggleButtonLabel._ontrack',
		noPrefix: true,
	},
	{
		groupName: 'Small',
		displayName: 'Small Toggle Label Margin',
		name: 'smallToggleLabelMarginOnState',
		defaultValue: '0px 0px 0px -3px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._small._off ._toggleButtonLabel._ontrack',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Toggle Label Margin in OFF State',
		name: 'defaultToggleLabelMarginOffState',
		defaultValue: '0px 0px 0px 3px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._default._on ._toggleButtonLabel._ontrack',
		noPrefix: true,
	},
	{
		groupName: 'Outlined',
		displayName: 'Outlined Toggle Label Margin in OFF State',
		name: 'outlinedToggleLabelMarginOffState',
		defaultValue: '0px 0px 0px 3px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._outlined._on ._toggleButtonLabel._ontrack',
		noPrefix: true,
	},
	{
		groupName: 'Squared',
		displayName: 'Squared Toggle Label Margin in OFF State',
		name: 'squaredToggleLabelMarginOffState',
		defaultValue: '0px 0px 0px 3px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._squared._on ._toggleButtonLabel._ontrack',
		noPrefix: true,
	},
	{
		groupName: 'BigKnob',
		displayName: 'BigKnob Toggle Label Margin in OFF State',
		name: 'bigKnobToggleLabelMarginOffState',
		defaultValue: '0px 0px 0px 5px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._bigknob._on ._toggleButtonLabel._ontrack',
		noPrefix: true,
	},
	{
		groupName: 'Small',
		displayName: 'Small Toggle Label Margin in OFF State',
		name: 'smallToggleLabelMarginOffState',
		defaultValue: '0px 0px 0px 3px',
		cssProperty: 'margin',
		selector: '.comp.compToggleButton._small._on ._toggleButtonLabel._ontrack',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Toggle Knob BoxShadow in ON State',
		name: 'defaultToggleKnobBoxShadowOnState',
		cssProperty: 'box-shadow',
		selector: '.comp.compToggleButton._default._on ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Outlined',
		displayName: 'Outlined Toggle Knob BoxShadow in ON State',
		name: 'outlinedToggleKnobBoxShadowOnState',
		cssProperty: 'box-shadow',
		selector: '.comp.compToggleButton._outlined._on ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Squared',
		displayName: 'Squared Toggle Knob BoxShadow in ON State',
		name: 'squaredToggleKnobBoxShadowOnState',
		cssProperty: 'box-shadow',
		selector: '.comp.compToggleButton._squared._on ._knob',
		noPrefix: true,
	},
	{
		groupName: 'BigKnob',
		displayName: 'BigKnob Toggle Knob BoxShadow in ON State',
		name: 'bigKnobToggleKnobBoxShadowOnState',
		defaultValue: '0px 0px 5px #aaa',
		cssProperty: 'box-shadow',
		selector: '.comp.compToggleButton._bigknob._on ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Small',
		displayName: 'Small Toggle Knob BoxShadow',
		name: 'smallToggleKnobBoxShadowOnState',
		cssProperty: 'box-shadow',
		selector: '.comp.compToggleButton._small._on ._knob',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Toggle Knob BoxShadow in OFF State',
		name: 'defaultToggleKnobBoxShadowOffState',
		defaultValue: '0px 0px 5px #aaa',
		cssProperty: 'box-shadow',
		selector: '.comp.compToggleButton._default._off ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Outlined',
		displayName: 'Outlined Toggle Knob BoxShadow in OFF State',
		name: 'outlinedToggleKnobBoxShadowOffState',
		defaultValue: '0px 0px 5px #aaa',
		cssProperty: 'box-shadow',
		selector: '.comp.compToggleButton._outlined._off ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Squared',
		displayName: 'Squared Toggle Knob BoxShadow in OFF State',
		name: 'squaredToggleKnobBoxShadowOffState',
		defaultValue: '0px 0px 5px #aaa',
		cssProperty: 'box-shadow',
		selector: '.comp.compToggleButton._squared._off ._knob',
		noPrefix: true,
	},
	{
		groupName: 'BigKnob',
		displayName: 'BigKnob Toggle Knob BoxShadow in OFF State',
		name: 'bigKnobToggleKnobBoxShadowOffState',
		defaultValue: '0px 0px 5px #aaa',
		cssProperty: 'box-shadow',
		selector: '.comp.compToggleButton._bigknob._off ._knob',
		noPrefix: true,
	},
	{
		groupName: 'Small',
		displayName: 'Small Toggle Knob BoxShadow in OFF State',
		name: 'smallToggleKnobBoxShadowOffState',
		defaultValue: '0px 0px 5px #aaa',
		cssProperty: 'box-shadow',
		selector: '.comp.compToggleButton._small._off ._knob',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
