export const COUNTRY_LIST = [
	{ N: 'Afghanistan', D: '+93', C: 'AF' },
	{ N: 'Albania', D: '+355', C: 'AL' },
	{ N: 'Algeria', D: '+213', C: 'DZ' },
	{ N: 'AmericanSamoa', D: '+1684', C: 'AS' },
	{ N: 'Andorra', D: '+376', C: 'AD' },
	{ N: 'Angola', D: '+244', C: 'AO' },
	{ N: 'Anguilla', D: '+1264', C: 'AI' },
	{ N: 'Antarctica', D: '+672', C: 'AQ' },
	{ N: 'Antigua and Barbuda', D: '+1268', C: 'AG' },
	{ N: 'Argentina', D: '+54', C: 'AR' },
	{ N: 'Armenia', D: '+374', C: 'AM' },
	{ N: 'Aruba', D: '+297', C: 'AW' },
	{ N: 'Australia', D: '+61', C: 'AU' },
	{ N: 'Austria', D: '+43', C: 'AT' },
	{ N: 'Azerbaijan', D: '+994', C: 'AZ' },
	{ N: 'Bahamas', D: '+1242', C: 'BS' },
	{ N: 'Bahrain', D: '+973', C: 'BH' },
	{ N: 'Bangladesh', D: '+880', C: 'BD' },
	{ N: 'Barbados', D: '+1246', C: 'BB' },
	{ N: 'Belarus', D: '+375', C: 'BY' },
	{ N: 'Belgium', D: '+32', C: 'BE' },
	{ N: 'Belize', D: '+501', C: 'BZ' },
	{ N: 'Benin', D: '+229', C: 'BJ' },
	{ N: 'Bermuda', D: '+1441', C: 'BM' },
	{ N: 'Bhutan', D: '+975', C: 'BT' },
	{ N: 'Bolivia', D: '+591', C: 'BO' },
	{ N: 'Bosnia and Herzegovina', D: '+387', C: 'BA' },
	{ N: 'Botswana', D: '+267', C: 'BW' },
	{ N: 'Brazil', D: '+55', C: 'BR' },
	{ N: 'British Indian Ocean Territory', D: '+246', C: 'IO' },
	{ N: 'Brunei Darussalam', D: '+673', C: 'BN' },
	{ N: 'Bulgaria', D: '+359', C: 'BG' },
	{ N: 'Burkina Faso', D: '+226', C: 'BF' },
	{ N: 'Burundi', D: '+257', C: 'BI' },
	{ N: 'Cambodia', D: '+855', C: 'KH' },
	{ N: 'Cameroon', D: '+237', C: 'CM' },
	{ N: 'Canada', D: '+1', C: 'CA' },
	{ N: 'Cape Verde', D: '+238', C: 'CV' },
	{ N: 'Cayman Islands', D: '+ 345', C: 'KY' },
	{ N: 'Central African Republic', D: '+236', C: 'CF' },
	{ N: 'Chad', D: '+235', C: 'TD' },
	{ N: 'Chile', D: '+56', C: 'CL' },
	{ N: 'China', D: '+86', C: 'CN' },
	{ N: 'Christmas Island', D: '+61', C: 'CX' },
	{ N: 'Cocos (Keeling) Islands', D: '+61', C: 'CC' },
	{ N: 'Colombia', D: '+57', C: 'CO' },
	{ N: 'Comoros', D: '+269', C: 'KM' },
	{ N: 'Congo', D: '+242', C: 'CG' },
	{ N: 'Congo, The Democratic Republic of the', D: '+243', C: 'CD' },
	{ N: 'Cook Islands', D: '+682', C: 'CK' },
	{ N: 'Costa Rica', D: '+506', C: 'CR' },
	{ N: "Cote d'Ivoire", D: '+225', C: 'CI' },
	{ N: 'Croatia', D: '+385', C: 'HR' },
	{ N: 'Cuba', D: '+53', C: 'CU' },
	{ N: 'Cyprus', D: '+537', C: 'CY' },
	{ N: 'Czech Republic', D: '+420', C: 'CZ' },
	{ N: 'Denmark', D: '+45', C: 'DK' },
	{ N: 'Djibouti', D: '+253', C: 'DJ' },
	{ N: 'Dominica', D: '+1767', C: 'DM' },
	{ N: 'Dominican Republic', D: '+1849', C: 'DO' },
	{ N: 'Ecuador', D: '+593', C: 'EC' },
	{ N: 'Egypt', D: '+20', C: 'EG' },
	{ N: 'El Salvador', D: '+503', C: 'SV' },
	{ N: 'Equatorial Guinea', D: '+240', C: 'GQ' },
	{ N: 'Eritrea', D: '+291', C: 'ER' },
	{ N: 'Estonia', D: '+372', C: 'EE' },
	{ N: 'Ethiopia', D: '+251', C: 'ET' },
	{ N: 'Falkland Islands (Malvinas)', D: '+500', C: 'FK' },
	{ N: 'Faroe Islands', D: '+298', C: 'FO' },
	{ N: 'Fiji', D: '+679', C: 'FJ' },
	{ N: 'Finland', D: '+358', C: 'FI' },
	{ N: 'France', D: '+33', C: 'FR' },
	{ N: 'French Guiana', D: '+594', C: 'GF' },
	{ N: 'French Polynesia', D: '+689', C: 'PF' },
	{ N: 'Gabon', D: '+241', C: 'GA' },
	{ N: 'Gambia', D: '+220', C: 'GM' },
	{ N: 'Georgia', D: '+995', C: 'GE' },
	{ N: 'Germany', D: '+49', C: 'DE' },
	{ N: 'Ghana', D: '+233', C: 'GH' },
	{ N: 'Gibraltar', D: '+350', C: 'GI' },
	{ N: 'Greece', D: '+30', C: 'GR' },
	{ N: 'Greenland', D: '+299', C: 'GL' },
	{ N: 'Grenada', D: '+1473', C: 'GD' },
	{ N: 'Guadeloupe', D: '+590', C: 'GP' },
	{ N: 'Guam', D: '+1671', C: 'GU' },
	{ N: 'Guatemala', D: '+502', C: 'GT' },
	{ N: 'Guernsey', D: '+44', C: 'GG' },
	{ N: 'Guinea', D: '+224', C: 'GN' },
	{ N: 'Guinea-Bissau', D: '+245', C: 'GW' },
	{ N: 'Guyana', D: '+595', C: 'GY' },
	{ N: 'Haiti', D: '+509', C: 'HT' },
	{ N: 'Holy See (Vatican City State)', D: '+379', C: 'VA' },
	{ N: 'Honduras', D: '+504', C: 'HN' },
	{ N: 'Hong Kong', D: '+852', C: 'HK' },
	{ N: 'Hungary', D: '+36', C: 'HU' },
	{ N: 'Iceland', D: '+354', C: 'IS' },
	{ N: 'India', D: '+91', C: 'IN' },
	{ N: 'Indonesia', D: '+62', C: 'ID' },
	{ N: 'Iran, Islamic Republic of', D: '+98', C: 'IR' },
	{ N: 'Iraq', D: '+964', C: 'IQ' },
	{ N: 'Ireland', D: '+353', C: 'IE' },
	{ N: 'Isle of Man', D: '+44', C: 'IM' },
	{ N: 'Israel', D: '+972', C: 'IL' },
	{ N: 'Italy', D: '+39', C: 'IT' },
	{ N: 'Jamaica', D: '+1876', C: 'JM' },
	{ N: 'Japan', D: '+81', C: 'JP' },
	{ N: 'Jersey', D: '+44', C: 'JE' },
	{ N: 'Jordan', D: '+962', C: 'JO' },
	{ N: 'Kazakhstan', D: '+7 7', C: 'KZ' },
	{ N: 'Kenya', D: '+254', C: 'KE' },
	{ N: 'Kiribati', D: '+686', C: 'KI' },
	{ N: "Korea, Democratic People's Republic of", D: '+850', C: 'KP' },
	{ N: 'Korea, Republic of', D: '+82', C: 'KR' },
	{ N: 'Kuwait', D: '+965', C: 'KW' },
	{ N: 'Kyrgyzstan', D: '+996', C: 'KG' },
	{ N: "Lao People's Democratic Republic", D: '+856', C: 'LA' },
	{ N: 'Latvia', D: '+371', C: 'LV' },
	{ N: 'Lebanon', D: '+961', C: 'LB' },
	{ N: 'Lesotho', D: '+266', C: 'LS' },
	{ N: 'Liberia', D: '+231', C: 'LR' },
	{ N: 'Libyan Arab Jamahiriya', D: '+218', C: 'LY' },
	{ N: 'Liechtenstein', D: '+423', C: 'LI' },
	{ N: 'Lithuania', D: '+370', C: 'LT' },
	{ N: 'Luxembourg', D: '+352', C: 'LU' },
	{ N: 'Macao', D: '+853', C: 'MO' },
	{ N: 'Macedonia, The Former Yugoslav Republic of', D: '+389', C: 'MK' },
	{ N: 'Madagascar', D: '+261', C: 'MG' },
	{ N: 'Malawi', D: '+265', C: 'MW' },
	{ N: 'Malaysia', D: '+60', C: 'MY' },
	{ N: 'Maldives', D: '+960', C: 'MV' },
	{ N: 'Mali', D: '+223', C: 'ML' },
	{ N: 'Malta', D: '+356', C: 'MT' },
	{ N: 'Marshall Islands', D: '+692', C: 'MH' },
	{ N: 'Martinique', D: '+596', C: 'MQ' },
	{ N: 'Mauritania', D: '+222', C: 'MR' },
	{ N: 'Mauritius', D: '+230', C: 'MU' },
	{ N: 'Mayotte', D: '+262', C: 'YT' },
	{ N: 'Mexico', D: '+52', C: 'MX' },
	{ N: 'Micronesia, Federated States of', D: '+691', C: 'FM' },
	{ N: 'Moldova, Republic of', D: '+373', C: 'MD' },
	{ N: 'Monaco', D: '+377', C: 'MC' },
	{ N: 'Mongolia', D: '+976', C: 'MN' },
	{ N: 'Montenegro', D: '+382', C: 'ME' },
	{ N: 'Montserrat', D: '+1664', C: 'MS' },
	{ N: 'Morocco', D: '+212', C: 'MA' },
	{ N: 'Mozambique', D: '+258', C: 'MZ' },
	{ N: 'Myanmar', D: '+95', C: 'MM' },
	{ N: 'Namibia', D: '+264', C: 'NA' },
	{ N: 'Nauru', D: '+674', C: 'NR' },
	{ N: 'Nepal', D: '+977', C: 'NP' },
	{ N: 'Netherlands', D: '+31', C: 'NL' },
	{ N: 'Netherlands Antilles', D: '+599', C: 'AN' },
	{ N: 'New Caledonia', D: '+687', C: 'NC' },
	{ N: 'New Zealand', D: '+64', C: 'NZ' },
	{ N: 'Nicaragua', D: '+505', C: 'NI' },
	{ N: 'Niger', D: '+227', C: 'NE' },
	{ N: 'Nigeria', D: '+234', C: 'NG' },
	{ N: 'Niue', D: '+683', C: 'NU' },
	{ N: 'Norfolk Island', D: '+672', C: 'NF' },
	{ N: 'Northern Mariana Islands', D: '+1670', C: 'MP' },
	{ N: 'Norway', D: '+47', C: 'NO' },
	{ N: 'Oman', D: '+968', C: 'OM' },
	{ N: 'Pakistan', D: '+92', C: 'PK' },
	{ N: 'Palau', D: '+680', C: 'PW' },
	{ N: 'Palestinian Territory, Occupied', D: '+970', C: 'PS' },
	{ N: 'Panama', D: '+507', C: 'PA' },
	{ N: 'Papua New Guinea', D: '+675', C: 'PG' },
	{ N: 'Paraguay', D: '+595', C: 'PY' },
	{ N: 'Peru', D: '+51', C: 'PE' },
	{ N: 'Philippines', D: '+63', C: 'PH' },
	{ N: 'Pitcairn', D: '+872', C: 'PN' },
	{ N: 'Poland', D: '+48', C: 'PL' },
	{ N: 'Portugal', D: '+351', C: 'PT' },
	{ N: 'Puerto Rico', D: '+1939', C: 'PR' },
	{ N: 'Qatar', D: '+974', C: 'QA' },
	{ N: 'Romania', D: '+40', C: 'RO' },
	{ N: 'Russia', D: '+7', C: 'RU' },
	{ N: 'Rwanda', D: '+250', C: 'RW' },
	{ N: 'Reunion', D: '+262', C: 'RE' },
	{ N: 'Saint Barthelemy', D: '+590', C: 'BL' },
	{ N: 'Saint Helena, Ascension and Tristan Da Cunha', D: '+290', C: 'SH' },
	{ N: 'Saint Kitts and Nevis', D: '+1869', C: 'KN' },
	{ N: 'Saint Lucia', D: '+1758', C: 'LC' },
	{ N: 'Saint Martin', D: '+590', C: 'MF' },
	{ N: 'Saint Pierre and Miquelon', D: '+508', C: 'PM' },
	{ N: 'Saint Vincent and the Grenadines', D: '+1784', C: 'VC' },
	{ N: 'Samoa', D: '+685', C: 'WS' },
	{ N: 'San Marino', D: '+378', C: 'SM' },
	{ N: 'Sao Tome and Principe', D: '+239', C: 'ST' },
	{ N: 'Saudi Arabia', D: '+966', C: 'SA' },
	{ N: 'Senegal', D: '+221', C: 'SN' },
	{ N: 'Serbia', D: '+381', C: 'RS' },
	{ N: 'Seychelles', D: '+248', C: 'SC' },
	{ N: 'Sierra Leone', D: '+232', C: 'SL' },
	{ N: 'Singapore', D: '+65', C: 'SG' },
	{ N: 'Slovakia', D: '+421', C: 'SK' },
	{ N: 'Slovenia', D: '+386', C: 'SI' },
	{ N: 'Solomon Islands', D: '+677', C: 'SB' },
	{ N: 'Somalia', D: '+252', C: 'SO' },
	{ N: 'South Africa', D: '+27', C: 'ZA' },
	{ N: 'South Sudan', D: '+211', C: 'SS' },
	{ N: 'South Georgia and the South Sandwich Islands', D: '+500', C: 'GS' },
	{ N: 'Spain', D: '+34', C: 'ES' },
	{ N: 'Sri Lanka', D: '+94', C: 'LK' },
	{ N: 'Sudan', D: '+249', C: 'SD' },
	{ N: 'SuriN', D: '+597', C: 'SR' },
	{ N: 'Svalbard and Jan Mayen', D: '+47', C: 'SJ' },
	{ N: 'Swaziland', D: '+268', C: 'SZ' },
	{ N: 'Sweden', D: '+46', C: 'SE' },
	{ N: 'Switzerland', D: '+41', C: 'CH' },
	{ N: 'Syrian Arab Republic', D: '+963', C: 'SY' },
	{ N: 'Taiwan', D: '+886', C: 'TW' },
	{ N: 'Tajikistan', D: '+992', C: 'TJ' },
	{ N: 'Tanzania, United Republic of', D: '+255', C: 'TZ' },
	{ N: 'Thailand', D: '+66', C: 'TH' },
	{ N: 'Timor-Leste', D: '+670', C: 'TL' },
	{ N: 'Togo', D: '+228', C: 'TG' },
	{ N: 'Tokelau', D: '+690', C: 'TK' },
	{ N: 'Tonga', D: '+676', C: 'TO' },
	{ N: 'Trinidad and Tobago', D: '+1868', C: 'TT' },
	{ N: 'Tunisia', D: '+216', C: 'TN' },
	{ N: 'Turkey', D: '+90', C: 'TR' },
	{ N: 'Turkmenistan', D: '+993', C: 'TM' },
	{ N: 'Turks and Caicos Islands', D: '+1649', C: 'TC' },
	{ N: 'Tuvalu', D: '+688', C: 'TV' },
	{ N: 'Uganda', D: '+256', C: 'UG' },
	{ N: 'Ukraine', D: '+380', C: 'UA' },
	{ N: 'United Arab Emirates', D: '+971', C: 'AE' },
	{ N: 'United Kingdom', D: '+44', C: 'GB' },
	{ N: 'United States', D: '+1', C: 'US' },
	{ N: 'Uruguay', D: '+598', C: 'UY' },
	{ N: 'Uzbekistan', D: '+998', C: 'UZ' },
	{ N: 'Vanuatu', D: '+678', C: 'VU' },
	{ N: 'Venezuela, Bolivarian Republic of', D: '+58', C: 'VE' },
	{ N: 'Viet Nam', D: '+84', C: 'VN' },
	{ N: 'Virgin Islands, British', D: '+1284', C: 'VG' },
	{ N: 'Virgin Islands, U.S.', D: '+1340', C: 'VI' },
	{ N: 'Wallis and Futuna', D: '+681', C: 'WF' },
	{ N: 'Yemen', D: '+967', C: 'YE' },
	{ N: 'Zambia', D: '+260', C: 'ZM' },
	{ N: 'Zimbabwe', D: '+263', C: 'ZW' },
];
