import { StylePropertyDefinition } from '../../types/common';
export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'Design 1',
		displayName: 'Design 1 Border',
		name: 'design1ButtonBarBorder',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design 1',
		displayName: 'Design 1 Button Border',
		name: 'design1ButtonBarButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 1',
		displayName: 'Design 1 Button BorderTop',
		name: 'design1ButtonBarButtonTopBorder',
		cssProperty: 'border-top',
		noPrefix: true,
	},
	{
		groupName: 'Design 1',
		displayName: 'Design 1 Button BorderRight',
		name: 'design1ButtonBarButtonRightBorder',
		cssProperty: 'border-right',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button:not(:last-child)',
		noPrefix: true,
	},
	{
		groupName: 'Design 1',
		displayName: 'Design 1 Button BorderBottom',
		name: 'design1ButtonBarButtonBottomBorder',
		cssProperty: 'border-bottom',
		noPrefix: true,
	},
	{
		groupName: 'Design 1',
		displayName: 'Design 1 Button BorderLeft',
		name: 'design1ButtonBarButtonLeftBorder',
		cssProperty: 'border-left',
		noPrefix: true,
	},
	{
		groupName: 'Design 1',
		displayName: 'Design 1 Button height',
		name: 'design1ButtonBarButtonHeight',
		defaultValue: '32px',
		cssProperty: 'height',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: ' Button Background',
		name: 'ButtonBarBackgroundOne',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._primary ._button,.comp.compButtonBar._buttonBarDesign2._primary ._button,.comp.compButtonBar._buttonBarDesign3._primary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Background',
		name: 'ButtonBarBackgroundTwo',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._secondary ._button,.comp.compButtonBar._buttonBarDesign2._secondary ._button,.comp.compButtonBar._buttonBarDesign3._secondary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Background',
		name: 'ButtonBarBackgroundThree',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._tertiary ._button,.comp.compButtonBar._buttonBarDesign2._tertiary ._button,.comp.compButtonBar._buttonBarDesign3._tertiary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Background',
		name: 'ButtonBarBackgroundFour',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._quaternary ._button, .comp.compButtonBar._buttonBarDesign2._quaternary ._button, .comp.compButtonBar._buttonBarDesign3._quaternary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Background',
		name: 'ButtonBarBackgroundFive',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._quinary ._button,.comp.compButtonBar._buttonBarDesign2._quinary ._button,.comp.compButtonBar._buttonBarDesign3._quinary ._button',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: ' Button Hover Background',
		name: 'ButtonBarHoverBackgroundOne',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._primary ._button:hover, .comp.compButtonBar._buttonBarDesign2._primary ._button:hover, .comp.compButtonBar._buttonBarDesign3._primary ._button:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Hover Background',
		name: 'ButtonBarHoverBackgroundTwo',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._secondary ._button:hover,.comp.compButtonBar._buttonBarDesign2._secondary ._button:hover,.comp.compButtonBar._buttonBarDesign3._secondary ._button:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Hover Background',
		name: 'ButtonBarHoverBackgroundThree',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._tertiary ._button:hover, .comp.compButtonBar._buttonBarDesign2._tertiary ._button:hover, .comp.compButtonBar._buttonBarDesign3._tertiary ._button:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Hover Background',
		name: 'ButtonBarHoverBackgroundFour',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._quaternary ._button:hover, .comp.compButtonBar._buttonBarDesign2._quaternary ._button:hover,.comp.compButtonBar._buttonBarDesign3._quaternary ._button:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Hover Background',
		name: 'ButtonBarHoverBackgroundFive',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._quinary ._button:hover, .comp.compButtonBar._buttonBarDesign2._quinary ._button:hover, .comp.compButtonBar._buttonBarDesign3._quinary ._button:hover',
		noPrefix: true,
	},

	{
		groupName: 'Color',
		displayName: ' ButtonBar  Hover Text Color',
		name: 'ButtonBArHoverTextColorOne',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button:hover, .comp.compButtonBar._buttonBarDesign2 ._button:hover, .comp.compButtonBar._buttonBarDesign3 ._button:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: ' ButtonBar  Hover Text Color',
		name: 'ButtonBArHoverTextColorTwo',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button:hover',
		noPrefix: true,
	},

	{
		groupName: 'Color',
		displayName: ' Button Text Color',
		name: 'ButtonBArTextColorOne',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button,.comp.compButtonBar._buttonBarDesign2 ._button,.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},

	{
		groupName: 'Design 2',
		displayName: 'Design 2 Border',
		name: 'design2ButtonBarBorder',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2 Button Border',
		name: 'design2ButtonBarButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2 Button BorderTop',
		name: 'design2ButtonBarButtonTopBorder',
		cssProperty: 'border-top',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2 Button BorderRight',
		name: 'design2ButtonBarButtonRightBorder',
		cssProperty: 'border-right',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button:not(:last-child)',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2 Button BorderBottom',
		name: 'design2ButtonBarButtonBottomBorder',
		cssProperty: 'border-bottom',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2 Button BorderLeft',
		name: 'design2ButtonBarButtonLeftBorder',
		cssProperty: 'border-left',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2 Button height',
		name: 'design2ButtonBarButtonHeight',
		defaultValue: '32px',
		cssProperty: 'height',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2 border radius',
		name: 'design2ButtonBarBorderRadius',
		defaultValue: '30px',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2  button border top left  radius',
		name: 'design2buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-top-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button:first-child',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2  button border bottom left radius',
		name: 'design2buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-bottom-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button:first-child',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2  button border bottom right radius',
		name: 'design2buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-bottom-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button:last-child',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2  button border top right radius',
		name: 'design2buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-top-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button:last-child',
		noPrefix: true,
	},

	{
		groupName: 'Design 3',
		displayName: 'Design 3 Border',
		name: 'design3ButtonBarBorder',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3 Button Border',
		name: 'design3ButtonBarButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3 Button BorderTop',
		name: 'design3ButtonBarButtonTopBorder',
		cssProperty: 'border-top',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3 Button BorderRight',
		name: 'design3ButtonBarButtonRightBorder',
		cssProperty: 'border-right',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3 Button BorderBottom',
		name: 'design3ButtonBarButtonBottomBorder',
		cssProperty: 'border-bottom',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3 Button BorderLeft',
		name: 'design3ButtonBarButtonLeftBorder',
		cssProperty: 'border-left',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3 Button height',
		name: 'design3ButtonBarButtonHeight',
		defaultValue: '32px',
		cssProperty: 'height',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3 border radius',
		name: 'design3ButtonBarBorderRadius',
		defaultValue: '30px',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3  button border top left  radius',
		name: 'design3buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-top-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3  button border bottom left radius',
		name: 'design3buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-bottom-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3  button border bottom right radius',
		name: 'design3buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-bottom-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3  button border top right radius',
		name: 'design3buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-top-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3 Button border radius',
		name: 'design3buttonBarBorderRadius',
		defaultValue: '30px',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design3 Design 3 flex',
		name: 'design3design3Flex',
		defaultValue: 'flex',
		cssProperty: 'display',
		selector: '.comp.compButtonBar._buttonBarDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design3',
		displayName: 'Design3Gap',
		name: 'design3Gap',
		defaultValue: '2px',
		cssProperty: 'gap',
		selector: '.comp.compButtonBar._buttonBarDesign3',
		noPrefix: true,
	},

	{
		groupName: 'Design 4',
		displayName: 'Design 4 Border',
		name: 'design4ButtonBarBorder',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4 Button Border',
		name: 'design4ButtonBarButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4 Button BorderTop',
		name: 'design4ButtonBarButtonTopBorder',
		cssProperty: 'border-top',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4 Button BorderRight',
		name: 'design4ButtonBarButtonRightBorder',
		cssProperty: 'border-right',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4 Button BorderBottom',
		name: 'design4ButtonBarButtonBottomBorder',
		cssProperty: 'border-bottom',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4 Button BorderLeft',
		name: 'design4ButtonBarButtonLeftBorder',
		cssProperty: 'border-left',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4 Button height',
		name: 'design4ButtonBarButtonHeight',
		defaultValue: '32px',
		cssProperty: 'height',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4 border radius',
		name: 'design4ButtonBarBorderRadius',
		defaultValue: '40px',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4  button border top left  radius',
		name: 'design4buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-top-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4  button border bottom left radius',
		name: 'design4buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-bottom-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4  button border bottom right radius',
		name: 'design4buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-bottom-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4  button border top right radius',
		name: 'design4buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-top-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4 Button border radius',
		name: 'design4buttonBarBorderRadius',
		defaultValue: '40px',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design4 Design 4 flex',
		name: 'design4design4Flex',
		defaultValue: 'flex',
		cssProperty: 'display',
		selector: '.comp.compButtonBar._buttonBarDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Design4',
		displayName: 'Design4Gap',
		name: 'design4Gap',
		defaultValue: '2px',
		cssProperty: 'gap',
		selector: '.comp.compButtonBar._buttonBarDesign4',
		noPrefix: true,
	},

	{
		groupName: 'Text Color',
		displayName: ' ButtonBar Text Color',
		name: 'ButtonBarTextColorOne',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4._primary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Text Color',
		displayName: ' ButtonBar Text Color',
		name: 'ButtonBarTextColorTwo',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4._secondary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Text Color',
		displayName: ' ButtonBar Text Color',
		name: 'ButtonBarTextColorThree',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4._tertiary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Text Color',
		displayName: ' ButtonBar Text Color',
		name: 'ButtonBarTextColorFour',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4._quaternary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Text Color',
		displayName: ' ButtonBar Text Color',
		name: 'ButtonBarTextColorFive',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4._quinary ._button',
		noPrefix: true,
	},

	{
		groupName: 'Text Color Hover',
		displayName: 'ButtonBar Text hover',
		name: 'ButtonBarTextHover',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector:
			'.comp.compButtonBar._buttonBarDesign4._primary ._button:hover,.comp.compButtonBar._buttonBarDesign4._secondary ._button:hover,.comp.compButtonBar._buttonBarDesign4._tertiary ._button:hover,.comp.compButtonBar._buttonBarDesign4._quaternary ._button:hover,.comp.compButtonBar._buttonBarDesign4._quinary ._button:hover',
		noPrefix: true,
	},

	{
		groupName: 'ButtonBarCursor',
		displayName: 'buttonBarCursor',
		name: 'buttonBarCursor',
		defaultValue: 'pointer',
		cssProperty: 'cursor',
		selector: '.comp.compButtonBar ._button',
		noPrefix: true,
	},

	{
		groupName: 'Text Color Hover',
		displayName: 'ButtonBar Text hoverSelected',
		name: 'ButtonBarTextHover',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector:
			'.comp.compButtonBar._buttonBarDesign4._primary ._button._selected,.comp.compButtonBar._buttonBarDesign4._secondary ._button._selected,.comp.compButtonBar._buttonBarDesign4._tertiary ._button._selected,.comp.compButtonBar._buttonBarDesign4._quaternary ._button._selected,.comp.compButtonBar._buttonBarDesign4._quinary ._button._selected',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: ' Button Hover BackgroundSelected',
		name: 'ButtonBarHoverBackgroundOneSelect',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._primary ._button._selected, .comp.compButtonBar._buttonBarDesign2._primary ._button._selected, .comp.compButtonBar._buttonBarDesign3._primary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Hover BackgroundSelected',
		name: 'ButtonBarHoverBackgroundTwoSelect',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._secondary ._button._selected,.comp.compButtonBar._buttonBarDesign2._secondary ._button._selected,.comp.compButtonBar._buttonBarDesign3._secondary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Hover BackgroundSelected',
		name: 'ButtonBarHoverBackgroundThreeSelect',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._tertiary ._button._selected, .comp.compButtonBar._buttonBarDesign2._tertiary ._button._selected, .comp.compButtonBar._buttonBarDesign3._tertiary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Hover BackgroundSelected',
		name: 'ButtonBarHoverBackgroundFourSelect',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._quaternary ._button._selected, .comp.compButtonBar._buttonBarDesign2._quaternary ._button._selected,.comp.compButtonBar._buttonBarDesign3._quaternary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Hover BackgroundSelected',
		name: 'ButtonBarHoverBackgroundFiveSelect',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._quinary ._button._selected, .comp.compButtonBar._buttonBarDesign2._quinary ._button._selected, .comp.compButtonBar._buttonBarDesign3._quinary ._button._selected',
		noPrefix: true,
	},

	{
		groupName: 'Color',
		displayName: ' ButtonBar  Hover Text ColorSelect',
		name: 'ButtonBArHoverTextColorOneSelect',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button._selected, .comp.compButtonBar._buttonBarDesign2 ._button._selected, .comp.compButtonBar._buttonBarDesign3 ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: ' ButtonBar  Hover Text ColorSelect',
		name: 'ButtonBArHoverTextColorTwoSelect',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button._selected',
		noPrefix: true,
	},
];
export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
