import { StylePropertyDefinition } from '../../types/common';
export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'Button Bar Border',
		displayName: 'Button Bar Border Border',
		name: 'buttonbarborderButtonBarBorder',
		cssProperty: 'border',
		selector:
			'.comp.compButtonBar._buttonBarDesign1, .comp.compButtonBar._buttonBarDesign2, .comp.compButtonBar._buttonBarDesign3, .comp.compButtonBar._buttonBarDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Button Border',
		displayName: 'Button Bar Button Border Button Border',
		name: 'buttonbarbuttonborderButtonBarButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button, .comp.compButtonBar._buttonBarDesign2 ._button, .comp.compButtonBar._buttonBarDesign3 ._button, .comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Button Border',
		displayName: 'Button Bar Button Border Button BorderTop',
		name: 'buttonbarbuttonborderButtonBarButtonTopBorder',
		cssProperty: 'border-top',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button, .comp.compButtonBar._buttonBarDesign2 ._button, .comp.compButtonBar._buttonBarDesign3 ._button, .comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Button Border',
		displayName: 'Button Bar Button Border Button BorderRight',
		name: 'buttonbarbuttonborderButtonBarButtonRightBorder',
		cssProperty: 'border-right',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button, .comp.compButtonBar._buttonBarDesign2 ._button, .comp.compButtonBar._buttonBarDesign3 ._button, .comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Button Border',
		displayName: 'Button Bar Button Border Button BorderBottom',
		name: 'buttonbarbuttonborderButtonBarButtonBottomBorder',
		cssProperty: 'border-bottom',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button, .comp.compButtonBar._buttonBarDesign2 ._button, .comp.compButtonBar._buttonBarDesign3 ._button, .comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Button Border',
		displayName: 'Button Bar Button Border Button BorderLeft',
		name: 'buttonbarbuttonborderButtonBarButtonLeftBorder',
		cssProperty: 'border-left',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button, .comp.compButtonBar._buttonBarDesign2 ._button, .comp.compButtonBar._buttonBarDesign3 ._button, .comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Height',
		displayName: 'Design 1 Button height',
		name: 'design1ButtonBarButtonHeight',
		defaultValue: '32px',
		cssProperty: 'height',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button, .comp.compButtonBar._buttonBarDesign2 ._button, .comp.compButtonBar._buttonBarDesign3 ._button, .comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Background',
		name: 'ButtonBarBackgroundOne',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._primary ._button,.comp.compButtonBar._buttonBarDesign2._primary ._button,.comp.compButtonBar._buttonBarDesign3._primary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Background',
		name: 'ButtonBarBackgroundTwo',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._secondary ._button,.comp.compButtonBar._buttonBarDesign2._secondary ._button,.comp.compButtonBar._buttonBarDesign3._secondary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Background',
		name: 'ButtonBarBackgroundThree',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._tertiary ._button,.comp.compButtonBar._buttonBarDesign2._tertiary ._button,.comp.compButtonBar._buttonBarDesign3._tertiary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Background',
		name: 'ButtonBarBackgroundFour',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._quaternary ._button, .comp.compButtonBar._buttonBarDesign2._quaternary ._button, .comp.compButtonBar._buttonBarDesign3._quaternary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Background',
		name: 'ButtonBarBackgroundFive',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._quinary ._button,.comp.compButtonBar._buttonBarDesign2._quinary ._button,.comp.compButtonBar._buttonBarDesign3._quinary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Hover Background',
		name: 'ButtonBarHoverBackgroundOne',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._primary ._button:hover, .comp.compButtonBar._buttonBarDesign2._primary ._button:hover, .comp.compButtonBar._buttonBarDesign3._primary ._button:hover, .comp.compButtonBar._buttonBarDesign1._primary ._button._selected, .comp.compButtonBar._buttonBarDesign2._primary ._button._selected, .comp.compButtonBar._buttonBarDesign3._primary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Hover Background',
		name: 'ButtonBarHoverBackgroundTwo',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._secondary ._button:hover, .comp.compButtonBar._buttonBarDesign2._secondary ._button:hover, .comp.compButtonBar._buttonBarDesign3._secondary ._button:hover, .comp.compButtonBar._buttonBarDesign1._secondary ._button._selected, .comp.compButtonBar._buttonBarDesign2._secondary ._button._selected, .comp.compButtonBar._buttonBarDesign3._secondary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Hover Background',
		name: 'ButtonBarHoverBackgroundThree',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._tertiary ._button:hover, .comp.compButtonBar._buttonBarDesign2._tertiary ._button:hover, .comp.compButtonBar._buttonBarDesign3._tertiary ._button:hover, .comp.compButtonBar._buttonBarDesign1._tertiary ._button._selected, .comp.compButtonBar._buttonBarDesign2._tertiary ._button._selected, .comp.compButtonBar._buttonBarDesign3._tertiary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Hover Background',
		name: 'ButtonBarHoverBackgroundFour',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._quaternary ._button:hover, .comp.compButtonBar._buttonBarDesign2._quaternary ._button:hover, .comp.compButtonBar._buttonBarDesign3._quaternary ._button:hover, .comp.compButtonBar._buttonBarDesign1._quaternary ._button._selected, .comp.compButtonBar._buttonBarDesign2._quaternary ._button._selected, .comp.compButtonBar._buttonBarDesign3._quaternary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: ' Button Hover Background',
		name: 'ButtonBarHoverBackgroundFive',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._quinary ._button:hover, .comp.compButtonBar._buttonBarDesign2._quinary ._button:hover, .comp.compButtonBar._buttonBarDesign3._quinary ._button:hover, .comp.compButtonBar._buttonBarDesign1._quinary ._button._selected, .comp.compButtonBar._buttonBarDesign2._quinary ._button._selected, .comp.compButtonBar._buttonBarDesign3._quinary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: ' ButtonBar  Hover Text Color',
		name: 'ButtonBArHoverTextColorOne',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button:hover, .comp.compButtonBar._buttonBarDesign2 ._button:hover, .comp.compButtonBar._buttonBarDesign3 ._button:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: ' ButtonBar  Hover Text Color',
		name: 'ButtonBArHoverTextColorTwo',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: ' Button Text Color',
		name: 'ButtonBArTextColorOne',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button,.comp.compButtonBar._buttonBarDesign2 ._button,.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design3',
		displayName: 'Design3Gap',
		name: 'design3Gap',
		defaultValue: '2px',
		cssProperty: 'gap',
		selector: '.comp.compButtonBar._buttonBarDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design4',
		displayName: 'Design4Gap',
		name: 'design4Gap',
		defaultValue: '2px',
		cssProperty: 'gap',
		selector: '.comp.compButtonBar._buttonBarDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Text Color',
		displayName: ' ButtonBar Text Color',
		name: 'ButtonBarTextColorOne',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4._primary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Text Color',
		displayName: ' ButtonBar Text Color',
		name: 'ButtonBarTextColorTwo',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4._secondary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Text Color',
		displayName: ' ButtonBar Text Color',
		name: 'ButtonBarTextColorThree',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4._tertiary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Text Color',
		displayName: ' ButtonBar Text Color',
		name: 'ButtonBarTextColorFour',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4._quaternary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Text Color',
		displayName: ' ButtonBar Text Color',
		name: 'ButtonBarTextColorFive',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4._quinary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Text Color Hover',
		displayName: 'ButtonBar Text hover',
		name: 'ButtonBarTextHover',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector:
			'.comp.compButtonBar._buttonBarDesign4._primary ._button:hover,.comp.compButtonBar._buttonBarDesign4._secondary ._button:hover,.comp.compButtonBar._buttonBarDesign4._tertiary ._button:hover,.comp.compButtonBar._buttonBarDesign4._quaternary ._button:hover,.comp.compButtonBar._buttonBarDesign4._quinary ._button:hover',
		noPrefix: true,
	},
	{
		groupName: 'ButtonBarCursor',
		displayName: 'buttonBarCursor',
		name: 'buttonBarCursor',
		defaultValue: 'pointer',
		cssProperty: 'cursor',
		selector: '.comp.compButtonBar ._button',
		noPrefix: true,
	},
	{
		groupName: 'Text Color Hover',
		displayName: 'ButtonBar Text hoverSelected',
		name: 'ButtonBarTextHover',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector:
			'.comp.compButtonBar._buttonBarDesign4._primary ._button._selected,.comp.compButtonBar._buttonBarDesign4._secondary ._button._selected,.comp.compButtonBar._buttonBarDesign4._tertiary ._button._selected,.comp.compButtonBar._buttonBarDesign4._quaternary ._button._selected,.comp.compButtonBar._buttonBarDesign4._quinary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: ' ButtonBar  Hover Text ColorSelect',
		name: 'ButtonBArHoverTextColorOneSelect',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button._selected, .comp.compButtonBar._buttonBarDesign2 ._button._selected, .comp.compButtonBar._buttonBarDesign3 ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: ' ButtonBar  Hover Text ColorSelect',
		name: 'ButtonBArHoverTextColorTwoSelect',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design One',
		displayName: 'Button Bar Border Design One Border',
		name: 'buttonbarborderdesignoneButtonBarBorder',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design One',
		displayName: 'Button Bar Border Design One Button Border',
		name: 'buttonbarborderdesignoneButtonBarButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design One',
		displayName: 'Button Bar Border Design One Button BorderTop',
		name: 'buttonbarborderdesignoneButtonBarButtonTopBorder',
		cssProperty: 'border-top',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design One',
		displayName: 'Button Bar Border Design One Button BorderRight',
		name: 'buttonbarborderdesignoneButtonBarButtonRightBorder',
		cssProperty: 'border-right',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design One',
		displayName: 'Button Bar Border Design One Button BorderBottom',
		name: 'buttonbarborderdesignoneButtonBarButtonBottomBorder',
		cssProperty: 'border-bottom',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design One',
		displayName: 'Button Bar Border Design One Button BorderLeft',
		name: 'buttonbarborderdesignoneButtonBarButtonLeftBorder',
		cssProperty: 'border-left',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Two',
		displayName: 'Button Bar Border Design Two Border',
		name: 'buttonbarborderdesigntwoButtonBarBorder',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Two',
		displayName: 'Button Bar Border Design Two Button Border',
		name: 'buttonbarborderdesigntwoButtonBarButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Two',
		displayName: 'Button Bar Border Design Two Button BorderTop',
		name: 'buttonbarborderdesigntwoButtonBarButtonTopBorder',
		cssProperty: 'border-top',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Two',
		displayName: 'Button Bar Border Design Two Button BorderRight',
		name: 'buttonbarborderdesigntwoButtonBarButtonRightBorder',
		cssProperty: 'border-right',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Two',
		displayName: 'Button Bar Border Design Two Button BorderBottom',
		name: 'buttonbarborderdesigntwoButtonBarButtonBottomBorder',
		cssProperty: 'border-bottom',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Two',
		displayName: 'Button Bar Border Design Two Button BorderLeft',
		name: 'buttonbarborderdesigntwoButtonBarButtonLeftBorder',
		cssProperty: 'border-left',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Three',
		displayName: 'Button Bar Border Design Three Border',
		name: 'buttonbarborderdesignthreeButtonBarBorder',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Three',
		displayName: 'Button Bar Border Design Three Button Border',
		name: 'buttonbarborderdesignthreeButtonBarButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Three',
		displayName: 'Button Bar Border Design Three Button BorderTop',
		name: 'buttonbarborderdesignthreeButtonBarButtonTopBorder',
		cssProperty: 'border-top',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Three',
		displayName: 'Button Bar Border Design Three Button BorderRight',
		name: 'buttonbarborderdesignthreeButtonBarButtonRightBorder',
		cssProperty: 'border-right',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Three',
		displayName: 'Button Bar Border Design Three Button BorderBottom',
		name: 'buttonbarborderdesignthreeButtonBarButtonBottomBorder',
		cssProperty: 'border-bottom',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Three',
		displayName: 'Button Bar Border Design Three Button BorderLeft',
		name: 'buttonbarborderdesignthreeButtonBarButtonLeftBorder',
		cssProperty: 'border-left',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Four',
		displayName: 'Button Bar Border Design Four Border',
		name: 'buttonbarborderdesignfourButtonBarBorder',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Four',
		displayName: 'Button Bar Border Design Four Button Border',
		name: 'buttonbarborderdesignfourButtonBarButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Four',
		displayName: 'Button Bar Border Design Four Button BorderTop',
		name: 'buttonbarborderdesignfourButtonBarButtonTopBorder',
		cssProperty: 'border-top',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Four',
		displayName: 'Button Bar Border Design Four Button BorderRight',
		name: 'buttonbarborderdesignfourButtonBarButtonRightBorder',
		cssProperty: 'border-right',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Four',
		displayName: 'Button Bar Border Design Four Button BorderBottom',
		name: 'buttonbarborderdesignfourButtonBarButtonBottomBorder',
		cssProperty: 'border-bottom',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Design Four',
		displayName: 'Button Bar Border Design Four Button BorderLeft',
		name: 'buttonbarborderdesignfourButtonBarButtonLeftBorder',
		cssProperty: 'border-left',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 1',
		displayName: 'Design 1 border radius',
		name: 'design1ButtonBarBorderRadius',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design 1',
		displayName: 'Design 1  button border top left  radius',
		name: 'design1buttonBorderRadius',
		cssProperty: 'border-top-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button:first-child',
		noPrefix: true,
	},
	{
		groupName: 'Design 1',
		displayName: 'Design 1  button border bottom left radius',
		name: 'design1buttonBorderRadius',
		cssProperty: 'border-bottom-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button:first-child',
		noPrefix: true,
	},
	{
		groupName: 'Design 1',
		displayName: 'Design 1  button border bottom right radius',
		name: 'design1buttonBorderRadius',
		cssProperty: 'border-bottom-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button:last-child',
		noPrefix: true,
	},
	{
		groupName: 'Design 1',
		displayName: 'Design 1  button border top right radius',
		name: 'design1buttonBorderRadius',
		cssProperty: 'border-top-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button:last-child',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2 border radius',
		name: 'design2ButtonBarBorderRadius',
		defaultValue: '30px',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2  button border top left  radius',
		name: 'design2buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-top-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button:first-child',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2  button border bottom left radius',
		name: 'design2buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-bottom-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button:first-child',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2  button border bottom right radius',
		name: 'design2buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-bottom-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button:last-child',
		noPrefix: true,
	},
	{
		groupName: 'Design 2',
		displayName: 'Design 2  button border top right radius',
		name: 'design2buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-top-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button:last-child',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3 border radius',
		name: 'design3ButtonBarBorderRadius',
		defaultValue: '30px',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3  button border top left  radius',
		name: 'design3buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-top-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3  button border bottom left radius',
		name: 'design3buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-bottom-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3  button border bottom right radius',
		name: 'design3buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-bottom-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3  button border top right radius',
		name: 'design3buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-top-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 3',
		displayName: 'Design 3 Button border radius',
		name: 'design3buttonBarBorderRadius',
		defaultValue: '30px',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4 border radius',
		name: 'design4ButtonBarBorderRadius',
		defaultValue: '40px',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4  button border top left  radius',
		name: 'design4buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-top-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4  button border bottom left radius',
		name: 'design4buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-bottom-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4  button border bottom right radius',
		name: 'design4buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-bottom-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4  button border top right radius',
		name: 'design4buttonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-top-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design 4',
		displayName: 'Design 4 Button border radius',
		name: 'design4buttonBarBorderRadius',
		defaultValue: '40px',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
];
export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
