import { StylePropertyDefinition } from '../../types/common';
export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'Button Bar Height',
		displayName: 'Button Bar Height Buttons Height',
		name: 'buttonBarHeightButtonsHeight',
		defaultValue: '32px',
		cssProperty: 'height',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button, .comp.compButtonBar._buttonBarDesign2 ._button, .comp.compButtonBar._buttonBarDesign3 ._button, .comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Background Color',
		displayName: 'Button Bar Background Color Primary  Button Background',
		name: 'buttonBarBackgroundColorPrimaryButtonBackground',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._primary ._button,.comp.compButtonBar._buttonBarDesign2._primary ._button,.comp.compButtonBar._buttonBarDesign3._primary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Background Color',
		displayName: 'Button Bar Background Color Secondary  Button Background',
		name: 'buttonBarBackgroundColorSecondaryButtonBackground',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._secondary ._button,.comp.compButtonBar._buttonBarDesign2._secondary ._button,.comp.compButtonBar._buttonBarDesign3._secondary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Background Color',
		displayName: 'Button Bar Background Color Tertiary  Button Background',
		name: 'buttonBarBackgroundColorTertiaryButtonBackground',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._tertiary ._button,.comp.compButtonBar._buttonBarDesign2._tertiary ._button,.comp.compButtonBar._buttonBarDesign3._tertiary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Background Color',
		displayName: 'Button Bar Background Color Quatranary  Button Background',
		name: 'buttonBarBackgroundColorQuatranaryButtonBackground',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._quaternary ._button, .comp.compButtonBar._buttonBarDesign2._quaternary ._button, .comp.compButtonBar._buttonBarDesign3._quaternary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Background Color',
		displayName: 'Button Bar Background Color Quinary  Button Background',
		name: 'buttonBarBackgroundColorQuinaryButtonBackground',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._quinary ._button,.comp.compButtonBar._buttonBarDesign2._quinary ._button,.comp.compButtonBar._buttonBarDesign3._quinary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Hover Background Color',
		displayName: 'Button Bar Hover Background Color Primary Background',
		name: 'buttonBarHoverBackgroundColorPrimaryBackground',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._primary ._button:hover, .comp.compButtonBar._buttonBarDesign2._primary ._button:hover, .comp.compButtonBar._buttonBarDesign3._primary ._button:hover, .comp.compButtonBar._buttonBarDesign1._primary ._button._selected, .comp.compButtonBar._buttonBarDesign2._primary ._button._selected, .comp.compButtonBar._buttonBarDesign3._primary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Hover Background Color',
		displayName: 'Button Bar Hover Background Color Secondary Background',
		name: 'buttonBarHoverBackgroundColorSecondaryBackground',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._secondary ._button:hover, .comp.compButtonBar._buttonBarDesign2._secondary ._button:hover, .comp.compButtonBar._buttonBarDesign3._secondary ._button:hover, .comp.compButtonBar._buttonBarDesign1._secondary ._button._selected, .comp.compButtonBar._buttonBarDesign2._secondary ._button._selected, .comp.compButtonBar._buttonBarDesign3._secondary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Hover Background Color',
		displayName: 'Button Bar Hover Background Color Tertiary Background',
		name: 'buttonBarHoverBackgroundColorTertiaryBackground',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._tertiary ._button:hover, .comp.compButtonBar._buttonBarDesign2._tertiary ._button:hover, .comp.compButtonBar._buttonBarDesign3._tertiary ._button:hover, .comp.compButtonBar._buttonBarDesign1._tertiary ._button._selected, .comp.compButtonBar._buttonBarDesign2._tertiary ._button._selected, .comp.compButtonBar._buttonBarDesign3._tertiary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Hover Background Color',
		displayName: 'Button Bar Hover Background Color Quatranary Background',
		name: 'buttonBarHoverBackgroundColorQuatranaryBackground',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._quaternary ._button:hover, .comp.compButtonBar._buttonBarDesign2._quaternary ._button:hover, .comp.compButtonBar._buttonBarDesign3._quaternary ._button:hover, .comp.compButtonBar._buttonBarDesign1._quaternary ._button._selected, .comp.compButtonBar._buttonBarDesign2._quaternary ._button._selected, .comp.compButtonBar._buttonBarDesign3._quaternary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Hover Background Color',
		displayName: 'Button Bar Hover Background Color Quinary Background',
		name: 'buttonBarHoverBackgroundColorQuinaryBackground',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'background',
		selector:
			'.comp.compButtonBar._buttonBarDesign1._quinary ._button:hover, .comp.compButtonBar._buttonBarDesign2._quinary ._button:hover, .comp.compButtonBar._buttonBarDesign3._quinary ._button:hover, .comp.compButtonBar._buttonBarDesign1._quinary ._button._selected, .comp.compButtonBar._buttonBarDesign2._quinary ._button._selected, .comp.compButtonBar._buttonBarDesign3._quinary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Text Color',
		displayName: 'Button Bar Text Color Hover Text Color',
		name: 'buttonBarTextColorHoverTextColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button:hover, .comp.compButtonBar._buttonBarDesign2 ._button:hover, .comp.compButtonBar._buttonBarDesign3 ._button:hover',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Text Color',
		displayName: 'Button Bar Text Color Design 4 Hover Text Color',
		name: 'buttonBarTextColorDesign4HoverTextColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button:hover',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Text Color',
		displayName: 'Button Bar Text Color Normal Text Color',
		name: 'buttonBarTextColorNormalTextColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button, .comp.compButtonBar._buttonBarDesign2 ._button, .comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Gap',
		displayName: 'Button Bar Gap Design 3 Gap',
		name: 'buttonBarGapDesign3Gap',
		defaultValue: '2px',
		cssProperty: 'gap',
		selector: '.comp.compButtonBar._buttonBarDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Gap',
		displayName: 'Button Bar Gap Design 4 Gap',
		name: 'buttonBarGapDesign4Gap',
		defaultValue: '2px',
		cssProperty: 'gap',
		selector: '.comp.compButtonBar._buttonBarDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Text Color',
		displayName: 'Primary Button Bar Text Color',
		name: 'primaryButtonBarTextColor',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4._primary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Text Color',
		displayName: 'Secondary Button Bar Text Color',
		name: 'secondaryButtonBarTextColor',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4._secondary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Text Color',
		displayName: 'Tertiary Button Bar Text Color',
		name: 'tertiaryButtonBarTextColor',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4._tertiary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Text Color',
		displayName: 'Quatranary Button Bar Text Color',
		name: 'quatranaryButtonBarTextColor',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4._quaternary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Text Color',
		displayName: 'Quinary Button Bar Text Color',
		name: 'quinaryButtonBarTextColor',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4._quinary ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Text Hover Color',
		displayName: 'Button Bar Text Hover Color Design 4',
		name: 'buttonBarTextHoverColorDesign4',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector:
			'.comp.compButtonBar._buttonBarDesign4._primary ._button:hover,.comp.compButtonBar._buttonBarDesign4._secondary ._button:hover,.comp.compButtonBar._buttonBarDesign4._tertiary ._button:hover,.comp.compButtonBar._buttonBarDesign4._quaternary ._button:hover,.comp.compButtonBar._buttonBarDesign4._quinary ._button:hover',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Cursor',
		displayName: 'Button Bar Cursor All Designs',
		name: 'buttonBarCursorAllDesigns',
		defaultValue: 'pointer',
		cssProperty: 'cursor',
		selector: '.comp.compButtonBar ._button',
		noPrefix: true,
	},
	{
		groupName: 'Text Color Hover',
		displayName: 'ButtonBar Text hoverSelected',
		name: 'buttonBarTexthoverSelected',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector:
			'.comp.compButtonBar._buttonBarDesign4._primary ._button._selected,.comp.compButtonBar._buttonBarDesign4._secondary ._button._selected,.comp.compButtonBar._buttonBarDesign4._tertiary ._button._selected,.comp.compButtonBar._buttonBarDesign4._quaternary ._button._selected,.comp.compButtonBar._buttonBarDesign4._quinary ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Text Color Selected',
		displayName: 'Text Color SelectedDesigns 1 2 3',
		name: 'textColorSelectedDesigns123',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector:
			'.comp.compButtonBar._buttonBarDesign1 ._button._selected, .comp.compButtonBar._buttonBarDesign2 ._button._selected, .comp.compButtonBar._buttonBarDesign3 ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Text Color Selected',
		displayName: 'Text Color SelectedDesigns 4',
		name: 'textColorSelectedDesigns4',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button._selected',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design One Border',
		displayName: 'Button Bar Design One Border Bar Border',
		name: 'buttonBarDesignOneBorderBarBorder',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design One Border',
		displayName: 'Button Bar Design One Border Button Border',
		name: 'buttonBarDesignOneBorderButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design One Border',
		displayName: 'Button Bar Design One Border Button Border Top',
		name: 'buttonBarDesignOneBorderButtonBorderTop',
		cssProperty: 'border-top',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design One Border',
		displayName: 'Button Bar Design One Border Button Border Right',
		name: 'buttonBarDesignOneBorderButtonBorderRight',
		cssProperty: 'border-right',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design One Border',
		displayName: 'Button Bar Design One Border Button Border Bottom',
		name: 'buttonBarDesignOneBorderButtonBorderBottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design One Border',
		displayName: 'Button Bar Design One Border Button Border Left',
		name: 'buttonBarDesignOneBorderButtonBorderLeft',
		cssProperty: 'border-left',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Two Border',
		displayName: 'Button Bar Design Two Border Bar Border',
		name: 'buttonBarDesignTwoBorderBarBorder',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Two Border',
		displayName: 'Button Bar Design Two Border Button Border',
		name: 'buttonBarDesignTwoBorderButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Two Border',
		displayName: 'Button Bar Design Two Border Button Border Top',
		name: 'buttonBarDesignTwoBorderButtonBorderTop',
		cssProperty: 'border-top',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Two Border',
		displayName: 'Button Bar Design Two Border Button Border Right',
		name: 'buttonBarDesignTwoBorderButtonBorderRight',
		cssProperty: 'border-right',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Two Border',
		displayName: 'Button Bar Design Two Border Button Border Bottom',
		name: 'buttonBarDesignTwoBorderButtonBorderBottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Two Border',
		displayName: 'Button Bar Design Two Border Button Border Left',
		name: 'buttonBarDesignTwoBorderButtonBorderLeft',
		cssProperty: 'border-left',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Three Border',
		displayName: 'Button Bar Design Three Border Bar Border',
		name: 'buttonBarDesignThreeBorderBarBorder',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Three Border',
		displayName: 'Button Bar Design Three Border Button Border',
		name: 'buttonBarDesignThreeBorderButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Three Border',
		displayName: 'Button Bar Design Three Border Button Border Top',
		name: 'buttonBarDesignThreeBorderButtonBorderTop',
		cssProperty: 'border-top',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Three Border',
		displayName: 'Button Bar Design Three Border Button Border Right',
		name: 'buttonBarDesignThreeBorderButtonBorderRight',
		cssProperty: 'border-right',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Three Border',
		displayName: 'Button Bar Design Three Border Button Border Bottom',
		name: 'buttonBarDesignThreeBorderButtonBorderBottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Three Border',
		displayName: 'Button Bar Design Three Border Button Border Left',
		name: 'buttonBarDesignThreeBorderButtonBorderLeft',
		cssProperty: 'border-left',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Four Border',
		displayName: 'Button Bar Design Four Border Bar Border',
		name: 'buttonBarDesignFourBorderBarBorder',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Four Border',
		displayName: 'Button Bar Design Four Border Button Border',
		name: 'buttonBarDesignFourBorderButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Four Border',
		displayName: 'Button Bar Design Four Border Button Border Top',
		name: 'buttonBarDesignFourBorderButtonBorderTop',
		cssProperty: 'border-top',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Four Border',
		displayName: 'Button Bar Design Four Border Button Border Right',
		name: 'buttonBarDesignFourBorderButtonBorderRight',
		cssProperty: 'border-right',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Four Border',
		displayName: 'Button Bar Design Four Border Button Border Bottom',
		name: 'buttonBarDesignFourBorderButtonBorderBottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Design Four Border',
		displayName: 'Button Bar Design Four Border Button Border Left',
		name: 'buttonBarDesignFourBorderButtonBorderLeft',
		cssProperty: 'border-left',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border RadiusDesign 1 Shorthand',
		name: 'buttonBarBorderRadiusDesign1Shorthand',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design OneTop Left',
		name: 'buttonBarBorderRadiusDesignOneTopLeft',
		cssProperty: 'border-top-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button._firstChild',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design OneBottom Left',
		name: 'buttonBarBorderRadiusDesignOneBottomLeft',
		cssProperty: 'border-bottom-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button._first-child',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design OneBottom Right',
		name: 'buttonBarBorderRadiusDesignOneBottomRight',
		cssProperty: 'border-bottom-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button._lastChild',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design OneTop Right',
		name: 'buttonBarBorderRadiusDesignOneTopRight',
		cssProperty: 'border-top-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign1 ._button._lastChild',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border RadiusDesign Two Shorthand',
		name: 'buttonBarBorderRadiusDesignTwoShorthand',
		defaultValue: '30px',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design Two Top Left',
		name: 'buttonBarBorderRadiusDesignTwoTopLeft',
		defaultValue: '16px',
		cssProperty: 'border-top-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button._firstChild',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design Two Bottom Left',
		name: 'buttonBarBorderRadiusDesignTwoBottomLeft',
		defaultValue: '16px',
		cssProperty: 'border-bottom-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button._firstChild',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design Two Bottom Right',
		name: 'buttonBarBorderRadiusDesignTwoBottomRight',
		defaultValue: '16px',
		cssProperty: 'border-bottom-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button._lastChild',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design Two Top Right',
		name: 'buttonBarBorderRadiusDesignTwoTopRight',
		defaultValue: '16px',
		cssProperty: 'border-top-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign2 ._button._lastChild',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border RadiusDesign Three Shorthand',
		name: 'buttonBarBorderRadiusDesignThreeShorthand',
		defaultValue: '30px',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design Three Top Left',
		name: 'buttonBarBorderRadiusDesignThreeTopLeft',
		cssProperty: 'border-top-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design Three Bottom Left',
		name: 'buttonBarBorderRadiusDesignThreeBottomLeft',
		cssProperty: 'border-bottom-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design Three Bottom Right',
		name: 'buttonBarBorderRadiusDesignThreeBottomRight',
		cssProperty: 'border-bottom-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design Three Top Right',
		name: 'buttonBarBorderRadiusDesignThreeTopRight',
		cssProperty: 'border-top-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design Three Button',
		name: 'buttonBarBorderRadiusDesignThreeButton',
		defaultValue: '30px',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign3 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border RadiusDesign Four Shorthand',
		name: 'buttonBarBorderRadiusDesignFourShorthand',
		defaultValue: '40px',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design Four Top Left',
		name: 'buttonBarBorderRadiusDesignFourTopLeft',
		cssProperty: 'border-top-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design Four Bottom Left',
		name: 'buttonBarBorderRadiusDesignFourBottomLeft',
		cssProperty: 'border-bottom-left-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design Four Bottom Right',
		name: 'buttonBarBorderRadiusDesignFourBottomRight',
		cssProperty: 'border-bottom-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Button Bar Border Radius Design Four Top Right',
		name: 'buttonBarBorderRadiusDesignFourTopRight',
		cssProperty: 'border-top-right-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Button Bar Border Radius',
		displayName: 'Design 4 Button border radius',
		name: 'design4Buttonborderradius',
		defaultValue: '40px',
		cssProperty: 'border-radius',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
	{
		groupName: 'Design4',
		displayName: 'Design4 Background color ',
		name: 'ButtonBarDesign4backgroundColor',
		defaultValue: '<backgroundColorTen>',
		cssProperty: 'background-color',
		selector: '.comp.compButtonBar._buttonBarDesign4 ._button',
		noPrefix: true,
	},
];
export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
