import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{ displayName: 'Link Font', name: 'linkFont', defaultValue: '<primaryFont>', noPrefix: true },

	{
		groupName: 'Default',
		displayName: 'Default Link Font',
		name: 'defaultLinkFont',
		defaultValue: '<linkFont>',
		cssProperty: 'font',
		selector: '.comp.compLink._default',
		noPrefix: true,
	},
	{
		groupName: 'Under Line',
		displayName: 'Under Line Link Font',
		name: 'underLineLinkFont',
		defaultValue: '<linkFont>',
		cssProperty: 'font',
		selector: '.comp.compLink._underLine',
		noPrefix: true,
	},
	{
		groupName: 'Under Above Line',
		displayName: 'Under n Above Link Font',
		name: 'undernAboveLinkFont',
		defaultValue: '<linkFont>',
		cssProperty: 'font',
		selector: '.comp.compLink._underAboveLine',
		noPrefix: true,
	},
	{
		groupName: 'Side Line',
		displayName: 'SideLines Link Font',
		name: 'sideLinesLinkFont',
		defaultValue: '<linkFont>',
		cssProperty: 'font',
		selector: '.comp.compLink._sideLines',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Link Padding',
		name: 'defaultLinkPadding',
		cssProperty: 'padding',
		selector: '.comp.compLink._default',
		noPrefix: true,
	},
	{
		groupName: 'Under Line',
		displayName: 'Under Line Link Padding',
		name: 'underLineLinkPadding',
		cssProperty: 'padding',
		selector: '.comp.compLink._underLine',
		noPrefix: true,
	},
	{
		groupName: 'Under Above Line',
		displayName: 'Under Above Line Link Padding',
		name: 'underAboveLineLinkPadding',
		cssProperty: 'padding',
		selector: '.comp.compLink._underAboveLine',
		noPrefix: true,
	},
	{
		groupName: 'Side Line',
		displayName: 'Side Line Link Padding',
		name: 'sideLineLinkPadding',
		defaultValue: '0px 5px',
		cssProperty: 'padding',
		selector: '.comp.compLink._sideLines',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Link Margin',
		name: 'defaultLinkMargin',
		cssProperty: 'margin',
		selector: '.comp.compLink._default',
		noPrefix: true,
	},
	{
		groupName: 'Under Line',
		displayName: 'Under Line Link Margin',
		name: 'underLineLinkMargin',
		cssProperty: 'margin',
		selector: '.comp.compLink._underLine',
		noPrefix: true,
	},
	{
		groupName: 'Under Above Line',
		displayName: 'Under Above Line Link Margin',
		name: 'underAboveLineLinkMargin',
		cssProperty: 'margin',
		selector: '.comp.compLink._underAboveLine',
		noPrefix: true,
	},
	{
		groupName: 'Side Line',
		displayName: 'Side Line Link Margin',
		name: 'sideLineLinkMargin',
		cssProperty: 'margin',
		selector: '.comp.compLink._sideLines',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Link Text Decoration',
		name: 'defaultLinkTextDecoration',
		defaultValue: 'none',
		cssProperty: 'text-decoration',
		selector: '.comp.compLink._default',
		noPrefix: true,
	},
	{
		groupName: 'Under Line',
		displayName: 'Under Line Link Text Decoration',
		name: 'underLineLinkTextDecoration',
		defaultValue: 'none',
		cssProperty: 'text-decoration',
		selector: '.comp.compLink._underLine',
		noPrefix: true,
	},
	{
		groupName: 'Under Above Line',
		displayName: 'Under Above Line Link Text Decoration',
		name: 'underAboveLineLinkTextDecoration',
		defaultValue: 'none',
		cssProperty: 'text-decoration',
		selector: '.comp.compLink._underAboveLine',
		noPrefix: true,
	},
	{
		groupName: 'Side Line',
		displayName: 'Side Line Link Text Decoration',
		name: 'sideLineLinkTextDecoration',
		defaultValue: 'none',
		cssProperty: 'text-decoration',
		selector: '.comp.compLink._sideLines',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Hover Link Text Decoration',
		name: 'defaultHoverLinkTextDecoration',
		defaultValue: 'none',
		cssProperty: 'text-decoration',
		selector: '.comp.compLink._default:hover, .comp.compLink._default._showLines',
		noPrefix: true,
	},
	{
		groupName: 'Under Line',
		displayName: 'Under Line Hover Link Text Decoration',
		name: 'underLineHoverLinkTextDecoration',
		defaultValue: 'underline',
		cssProperty: 'text-decoration',
		selector: '.comp.compLink._underLine:hover, .comp.compLink._underLine._showLines',
		noPrefix: true,
	},
	{
		groupName: 'Under Above Line',
		displayName: 'Under Above Line Hover Link Text Decoration',
		name: 'underAboveLineHoverLinkTextDecoration',
		defaultValue: 'underline overline',
		cssProperty: 'text-decoration',
		selector: '.comp.compLink._underAboveLine:hover, .comp.compLink._underAboveLine._showLines',
		noPrefix: true,
	},
	{
		groupName: 'Side Line',
		displayName: 'Side Line Hover Link Text Decoration',
		name: 'sideLineHoverLinkTextDecoration',
		defaultValue: 'none',
		cssProperty: 'text-decoration',
		selector: '.comp.compLink._sideLines:hover, .comp.compLink._sideLines._showLines',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Link Border',
		name: 'defaultLinkBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compLink._default',
		noPrefix: true,
	},
	{
		groupName: 'Under Line',
		displayName: 'Under Line Link Border',
		name: 'underLineLinkBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compLink._underLine',
		noPrefix: true,
	},
	{
		groupName: 'Under Above Line',
		displayName: 'Under Above Line Link Border',
		name: 'underAboveLineLinkBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compLink._underAboveLine',
		noPrefix: true,
	},
	{
		groupName: 'Side Line',
		displayName: 'Side Line Link Border',
		name: 'sideLineLinkBorder',
		defaultValue: 'none, 1px solid transparent, none, 1px solid transparent',
		cssProperty: 'border',
		selector: '.comp.compLink._sideLines',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Link Hover Border',
		name: 'defaultLinkHoverBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compLink._default:hover, .comp.compLink._default._showLines',
		noPrefix: true,
	},
	{
		groupName: 'Under Line',
		displayName: 'Under Line Link Hover Border',
		name: 'underLineLinkHoverBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compLink._underLine:hover, .comp.compLink._underLine._showLines',
		noPrefix: true,
	},
	{
		groupName: 'Under Above Line',
		displayName: 'Under Above Line Link Hover Border',
		name: 'underAboveLineLinkHoverBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compLink._underAboveLine:hover, .comp.compLink._underAboveLine._showLines',
		noPrefix: true,
	},
	{
		groupName: 'Side Line',
		displayName: 'Side Line Link Hover Border',
		name: 'sideLineLinkHoverBorder',
		defaultValue: 'none, 1px solid, none, 1px solid',
		cssProperty: 'border',
		selector: '.comp.compLink._sideLines:hover, .comp.compLink._sideLines._showLines',
		noPrefix: true,
	},

	{
		groupName: 'Line Color',
		displayName: 'Primary Link Border Color',
		name: 'primaryLinkBorderColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'border-color',
		selector:
			'.comp.compLink._default._primary, .comp.compLink._underLine._primary, .comp.compLink._underAboveLine._primary, .comp.compLink._sideLines._primary:hover, .comp.compLink._sideLines._primary._showLines',
		noPrefix: true,
	},
	{
		groupName: 'Line Color',
		displayName: 'Secondary Link Border Color',
		name: 'secondaryLinkBorderColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'border-color',
		selector:
			'.comp.compLink._default._secondary, .comp.compLink._underLine._secondary, .comp.compLink._underAboveLine._secondary, .comp.compLink._sideLines._secondary:hover, .comp.compLink._sideLines._secondary._showLines',
		noPrefix: true,
	},
	{
		groupName: 'Line Color',
		displayName: 'Tertiary Link Border Color',
		name: 'tertiaryLinkBorderColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'border-color',
		selector:
			'.comp.compLink._default._tertiary, .comp.compLink._underLine._tertiary, .comp.compLink._underAboveLine._tertiary, .comp.compLink._sideLines._tertiary:hover, .comp.compLink._sideLines._tertiary._showLines',
		noPrefix: true,
	},
	{
		groupName: 'Line Color',
		displayName: 'Quaternary Link Border Color',
		name: 'quaternaryLinkBorderColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'border-color',
		selector:
			'.comp.compLink._default._quaternary, .comp.compLink._underLine._quaternary, .comp.compLink._underAboveLine._quaternary, .comp.compLink._sideLines._quaternary:hover, .comp.compLink._sideLines._quaternary._showLines',
		noPrefix: true,
	},
	{
		groupName: 'Line Color',
		displayName: 'Quinary Link Border Color',
		name: 'quinaryLinkBorderColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'border-color',
		selector:
			'.comp.compLink._default._quinary, .comp.compLink._underLine._quinary, .comp.compLink._underAboveLine._quinary, .comp.compLink._sideLines._quinary:hover, .comp.compLink._sideLines._quinary._showLines',
		noPrefix: true,
	},

	{
		groupName: 'Color',
		displayName: 'Primary Link Font Color',
		name: 'primaryLinkFontColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector:
			'.comp.compLink._default._primary, .comp.compLink._underLine._primary, .comp.compLink._underAboveLine._primary, .comp.compLink._sideLines._primary',
		noPrefix: true,
	},
	{
		groupName: 'Line Color',
		displayName: 'Secondary Link Font Color',
		name: 'secondaryLinkFontColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector:
			'.comp.compLink._default._secondary, .comp.compLink._underLine._secondary, .comp.compLink._underAboveLine._secondary, .comp.compLink._sideLines._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Line Color',
		displayName: 'Tertiary Link Font Color',
		name: 'tertiaryLinkFontColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector:
			'.comp.compLink._default._tertiary, .comp.compLink._underLine._tertiary, .comp.compLink._underAboveLine._tertiary, .comp.compLink._sideLines._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Line Color',
		displayName: 'Quaternary Link Font Color',
		name: 'quaternaryLinkFontColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector:
			'.comp.compLink._default._quaternary, .comp.compLink._underLine._quaternary, .comp.compLink._underAboveLine._quaternary, .comp.compLink._sideLines._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Line Color',
		displayName: 'Quinary Link Font Color',
		name: 'quinaryLinkFontColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector:
			'.comp.compLink._default._quinary, .comp.compLink._underLine._quinary, .comp.compLink._underAboveLine._quinary, .comp.compLink._sideLines._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Line Color',
		displayName: 'Primary Text Decoration Color',
		name: 'primaryTextDecorationColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'text-decoration-color',
		selector:
			'.comp.compLink._default._primary, .comp.compLink._underLine._primary, .comp.compLink._underAboveLine._primary, .comp.compLink._sideLines._primary',
		noPrefix: true,
	},
	{
		groupName: 'Line Color',
		displayName: 'Secondary Text Decoration Color',
		name: 'secondaryTextDecorationColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'text-decoration-color',
		selector:
			'.comp.compLink._default._secondary, .comp.compLink._underLine._secondary, .comp.compLink._underAboveLine._secondary, .comp.compLink._sideLines._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Line Color',
		displayName: 'Tertiary Text Decoration Color',
		name: 'tertiaryTextDecorationColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'text-decoration-color',
		selector:
			'.comp.compLink._default._tertiary, .comp.compLink._underLine._tertiary, .comp.compLink._underAboveLine._tertiary, .comp.compLink._sideLines._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Line Color',
		displayName: 'Quaternary Text Decoration Color',
		name: 'quaternaryTextDecorationColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'text-decoration-color',
		selector:
			'.comp.compLink._default._quaternary, .comp.compLink._underLine._quaternary, .comp.compLink._underAboveLine._quaternary, .comp.compLink._sideLines._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Line Color',
		displayName: 'Quinary Text Decoration Color',
		name: 'quinaryTextDecorationColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'text-decoration-color',
		selector:
			'.comp.compLink._default._quinary, .comp.compLink._underLine._quinary, .comp.compLink._underAboveLine._quinary, .comp.compLink._sideLines._quinary',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
