import { StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		name: 'tagBorderRadius',
		cssProperty: 'border-radius',
		displayName: 'border radius of the Tag',
		description: "The Tag's border radius.",
		defaultValue: '2px',
		selector: '.container',
	},
	{
		name: 'tagBorder',
		cssProperty: 'border',
		displayName: 'Tag border',
		description: "The Tag's border.",
		defaultValue: '1px solid #c7c8d6',
		selector: '.container',
	},
	{
		name: 'tagBorderOnHover',
		cssProperty: 'border',
		displayName: 'Tag border - Hover',
		description: "The Tag's border color on hover.",
		selector: '.container:hover',
	},
	{
		name: 'tagHeight',
		cssProperty: 'height',
		displayName: 'height style of the Tag',
		description: "The Tag's height.",
		defaultValue: '32px',
		selector: '.container',
	},
	{
		name: 'tagMaxWidth',
		cssProperty: 'max-width',
		displayName: 'max width style of the Tag',
		description: 'The Max width of the tag.',
		defaultValue: '100px',
		selector: '.container',
	},
	{
		name: 'tagBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'background color of the Tag',
		description: "The Tag's background color.",
		selector: '.container',
	},
	{
		name: 'tagBackgroundColorHover',
		cssProperty: 'background-color',
		displayName: 'Tag background color - Hover',
		description: "The Tag's background color on hover.",
		selector: '.container:hover',
	},
	{
		name: 'tagFontSize',
		cssProperty: 'font-size',
		displayName: 'Tag font size',
		description: "The Tag's label font size.",
		selector: '.iconCss',
	},
	{
		name: 'tagIconColor',
		cssProperty: 'color',
		displayName: 'icon color of the Tag',
		description: "The Tag's icon color.",
		selector: '.iconCss',
	},
	{
		name: 'tagIconColorHover',
		cssProperty: 'color',
		displayName: 'Tag icon color - hover',
		description: "The Tag's icon color on hover.",
		selector: '.iconCss:hover',
	},
	{
		name: 'closeIconColor',
		cssProperty: 'color',
		displayName: 'close icon color of the Tag',
		description: "The Tag's close icon color.",
		selector: '.closeButton',
	},
	{
		name: 'closeIconColorHover',
		cssProperty: 'color',
		displayName: 'Tag close icon - hover',
		description: "The Tag's close icon color on hover.",
		selector: '.closeButton:hover',
	},
	{
		name: 'closeIconSize',
		cssProperty: 'font-size',
		displayName: 'Close icon size',
		description: "The Tag's size of close icon.",
		selector: '.closeButton',
	},
	{
		name: 'labelFontSize',
		cssProperty: 'font-size',
		displayName: 'Label font size',
		description: 'Label font size.',
		selector: '.text',
	},
	{
		name: 'iconSize',
		cssProperty: 'font-size',
		displayName: "Icon's size",
		description: 'The size of icon.',
		selector: '.iconCss',
	},
	{
		name: 'labelColor',
		cssProperty: 'color',
		displayName: 'Label color',
		description: "The Tag's label label color.",
		selector: '.text',
	},
	{
		name: 'labelColorHover',
		cssProperty: 'color',
		displayName: 'Label color - Hover',
		description: "The Tag's label label color on hover.",
		selector: '.text:hover',
	},
	{
		name: 'Outerlabel',
		cssProperty: 'color',
		displayName: 'Outer Label color ',
		description: "The Tag's outer label color.",
		selector: '.label',
		defaultValue: '#393A3C',
	},
	{
		name: 'inputHeight',
		cssProperty: 'height',
		displayName: 'Height of input box ',
		description: 'The input box height.',
		selector: '.input',
		defaultValue: '30px',
	},
	{
		name: 'inputPadding',
		cssProperty: 'padding-left',
		displayName: 'Left padding of input box ',
		description: 'The input box left padding.',
		selector: '.input',
		defaultValue: '7px',
	},
	{
		name: 'inputBorder',
		cssProperty: 'border',
		displayName: 'border of input box ',
		description: 'The input box border.',
		selector: '.input',
		defaultValue: 'none',
	},
	{
		name: 'inputBorderRadius',
		cssProperty: 'border-radius',
		displayName: 'border radius of input box ',
		description: 'The input box border radius.',
		selector: '.input',
		defaultValue: '4px',
	},
	{
		name: 'tagContainerWithInputFlexDirection',
		cssProperty: 'flex-direction',
		displayName: 'Flex direction of container with input',
		description: 'Flex direction of container with input.',
		selector: '.tagcontainerWithInput',
		defaultValue: 'row',
	},
	{
		name: 'tagContainerWithInputMaxHeight',
		cssProperty: 'max-height',
		displayName: 'Max height of tag container with input',
		description: 'The max height of tag container with input.',
		selector: '.tagcontainerWithInput',
		defaultValue: '200px',
	},
	{
		name: 'containerWithInputPadding',
		cssProperty: 'padding',
		displayName: 'padding of container with input',
		description: 'The padding of container with input.',
		selector: '.tagcontainerWithInput',
		defaultValue: '4px',
	},
	{
		name: 'outerContainerBorderWithInput',
		cssProperty: 'border',
		displayName: 'border of outer container with input',
		description: 'The border of outer container with input.',
		selector: '.containerWithInput',
		defaultValue: '1px solid #393A3C',
	},
	{
		name: 'outerContainerBorderRadiusWithInput',
		cssProperty: 'border-radius',
		displayName: 'border radius of outer container with input',
		description: 'The border radius of outer container with input.',
		selector: '.containerWithInput',
		defaultValue: '4px',
	},
	{
		name: 'outerContainerBackgroundColorWithInput',
		cssProperty: 'background-color',
		displayName: 'background color of outer container with input',
		description: 'The background color of outer container with input.',
		selector: '.containerWithInput',
		defaultValue: '',
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
