import {
	SCHEMA_BOOL_COMP_PROP,
	SCHEMA_NUM_COMP_PROP,
	SCHEMA_STRING_COMP_PROP,
} from '../../constants';
import {
	ComponentPropertyDefinition,
	ComponentPropertyEditor,
	ComponentPropertyGroup,
	ComponentStylePropertyDefinition,
} from '../../types/common';
import {
	COMMON_COMPONENT_PROPERTIES,
	COMPONENT_STYLE_GROUP_PROPERTIES,
} from '../util/properties';

const propertiesDefinition: Array<ComponentPropertyDefinition> = [
	{
		name: 'agentEndpoint',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Agent Endpoint',
		description: 'SSE endpoint URL for the AI agent.',
		group: ComponentPropertyGroup.BASIC,
	},
	{
		name: 'placeholder',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Placeholder',
		description: 'Placeholder text for the input field.',
		defaultValue: 'Ask the AI to build something...',
		group: ComponentPropertyGroup.BASIC,
		translatable: true,
	},
	{
		name: 'welcomeMessage',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Welcome Message',
		description: 'Heading shown when chat is empty.',
		defaultValue: 'What can I help with?',
		group: ComponentPropertyGroup.BASIC,
		translatable: true,
	},
	{
		name: 'showSessions',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Show Sessions',
		description: 'Show the session history sidebar.',
		defaultValue: true,
		group: ComponentPropertyGroup.BASIC,
	},
	{
		name: 'newChatLabel',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'New Chat Label',
		description: 'Label for the new chat button.',
		defaultValue: 'New chat',
		group: ComponentPropertyGroup.BASIC,
		translatable: true,
	},
	{
		name: 'yourChatsLabel',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Your Chats Label',
		description: 'Label for the session group heading.',
		defaultValue: 'Your chats',
		group: ComponentPropertyGroup.BASIC,
		translatable: true,
	},
	{
		name: 'deleteConfirmMessage',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Delete Confirm Message',
		description: 'Confirmation message shown when deleting a chat.',
		defaultValue: 'Delete this chat? This action cannot be undone.',
		group: ComponentPropertyGroup.BASIC,
		translatable: true,
	},
	{
		name: 'enableVoiceInput',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Enable Voice Input',
		description: 'Show microphone button for speech-to-text input.',
		defaultValue: true,
		group: ComponentPropertyGroup.BASIC,
	},
	{
		name: 'showToolCalls',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Show Tool Calls',
		description: 'Show tool call cards in the chat (default true).',
		defaultValue: true,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'enablePersonalization',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Enable Personalization',
		description: 'Remember sidebar width per user via personalization service.',
		defaultValue: true,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'sidebarToggleIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Sidebar Toggle Icon',
		description: 'Icon class for sidebar toggle button.',
		defaultValue: 'fa fa-bars',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'newChatTopIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'New Chat Top Icon',
		description: 'Icon class for the new chat button in top bar.',
		defaultValue: 'fa fa-pen-to-square',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'newChatSidebarIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'New Chat Sidebar Icon',
		description: 'Icon class for the new chat button in sidebar.',
		defaultValue: 'fa fa-plus',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'sendIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Send Icon',
		description: 'Icon class for the send button.',
		defaultValue: 'fa fa-arrow-up',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'stopIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Stop Icon',
		description: 'Icon class for the stop button.',
		defaultValue: 'fa fa-stop',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'addAttachmentIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Add Attachment Icon',
		description: 'Icon class for the add attachment button.',
		defaultValue: 'fa fa-plus',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'removeAttachmentIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Remove Attachment Icon',
		description: 'Icon class for removing attachments.',
		defaultValue: 'fa fa-xmark',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'fileIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'File Icon',
		description: 'Icon class for file attachments.',
		defaultValue: 'fa fa-file',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'copyIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Copy Icon',
		description: 'Icon class for the copy button.',
		defaultValue: 'fa fa-clone',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'copySuccessIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Copy Success Icon',
		description: 'Icon class shown after successful copy.',
		defaultValue: 'fa fa-check',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'renameIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Rename Icon',
		description: 'Icon class for the rename session button.',
		defaultValue: 'fa fa-pen',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'deleteIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Delete Icon',
		description: 'Icon class for the delete session button.',
		defaultValue: 'fa fa-trash',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'toolRunningIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Tool Running Icon',
		description: 'Icon class for running tool calls.',
		defaultValue: 'fa fa-circle-notch fa-spin',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'toolSuccessIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Tool Success Icon',
		description: 'Icon class for successful tool calls.',
		defaultValue: 'fa fa-check',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'toolErrorIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Tool Error Icon',
		description: 'Icon class for failed tool calls.',
		defaultValue: 'fa fa-xmark',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'expandIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Expand Icon',
		description: 'Icon class for expand/chevron down.',
		defaultValue: 'fa fa-chevron-down',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'collapseIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Collapse Icon',
		description: 'Icon class for collapse/chevron up.',
		defaultValue: 'fa fa-chevron-up',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'microphoneIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Microphone Icon',
		description: 'Icon class for the microphone button.',
		defaultValue: 'fa fa-microphone',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'microphoneActiveIcon',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Microphone Active Icon',
		description: 'Icon shown while recording voice.',
		defaultValue: 'fa fa-stop',
		editor: ComponentPropertyEditor.ICON,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'sessionsPerPage',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'Sessions Per Page',
		description: 'Number of sessions to load per page.',
		defaultValue: 20,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'messagesPerPage',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'Messages Per Page',
		description: 'Number of message turns to load per page.',
		defaultValue: 20,
		group: ComponentPropertyGroup.ADVANCED,
	},
	COMMON_COMPONENT_PROPERTIES.readOnly,
	COMMON_COMPONENT_PROPERTIES.visibility,
	{
		name: 'onMessage',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'On Message',
		description: 'Event fired when assistant message received.',
		editor: ComponentPropertyEditor.EVENT_SELECTOR,
		group: ComponentPropertyGroup.EVENTS,
	},
	{
		name: 'onError',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'On Error',
		description: 'Event fired on error.',
		editor: ComponentPropertyEditor.EVENT_SELECTOR,
		group: ComponentPropertyGroup.EVENTS,
	},
];

const stylePropertiesDefinition: ComponentStylePropertyDefinition = {
	'': [
		COMPONENT_STYLE_GROUP_PROPERTIES.layout.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.position.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.typography.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.effects.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.background.type,
	],
	messagesContainer: [
		COMPONENT_STYLE_GROUP_PROPERTIES.layout.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.position.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.background.type,
	],
	userMessage: [
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.typography.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.background.type,
	],
	assistantMessage: [
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.typography.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.background.type,
	],
	thinkingBlock: [
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.typography.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.background.type,
	],
	inputBar: [
		COMPONENT_STYLE_GROUP_PROPERTIES.layout.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.background.type,
	],
	inputTextArea: [
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.typography.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.background.type,
	],
	sendButton: [
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.typography.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.background.type,
	],
	sessionSidebar: [
		COMPONENT_STYLE_GROUP_PROPERTIES.layout.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.typography.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.background.type,
	],
	sidebarHeader: [
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.background.type,
	],
	newChatButton: [
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.typography.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.background.type,
	],
	sessionItem: [
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.typography.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.background.type,
	],
};

export { propertiesDefinition, stylePropertiesDefinition };
