import { StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{ displayName: 'Otp Font', name: 'OtpFont', defaultValue: '<primaryFont>' },

	{
		groupName: 'Otp Font',
		displayName: 'Otp Font Design Default',
		name: 'otpFontDesignDefault',
		defaultValue: '<OtpFont>',
		cssProperty: 'font',
		selector: '.comp.compOtp._default ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Font',
		displayName: 'Otp Font Design Dashed',
		name: 'otpFontDesignDashed',
		defaultValue: '<OtpFont>',
		cssProperty: 'font',
		selector: '.comp.compOtp._dashed ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Font',
		displayName: 'Otp Font Design Filled',
		name: 'otpFontDesignFilled',
		defaultValue: '<OtpFont>',
		cssProperty: 'font',
		selector: '.comp.compOtp._filled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Font',
		displayName: 'Otp Font Design Round',
		name: 'otpFontDesignRound',
		defaultValue: '<OtpFont>',
		cssProperty: 'font',
		selector: '.comp.compOtp._round ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Color ',
		displayName: 'Primary Otp Color  Design Default',
		name: 'primaryOtpColorDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Secondary Otp Color  Design Default',
		name: 'secondaryOtpColorDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default_secondary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Tertiary Otp Color Active Design Default',
		name: 'tertiaryOtpColorActiveDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._tertiary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Quaternary Otp Color Design Default',
		name: 'quaternaryOtpColorDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Quinary Otp Color Design Default',
		name: 'quinaryOtpColorDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Color ',
		displayName: 'Primary Otp Color Design Dashed',
		name: 'primaryOtpColorDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Secondary Otp Color Design Dashed',
		name: 'secondaryOtpColorDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._secondary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Tertiary Otp Color Design Dashed',
		name: 'tertiaryOtpColorDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._tertiary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Quaternary Otp Color Design Dashed',
		name: 'quaternaryOtpColorDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Quinary Otp Color Design Dashed',
		name: 'quinaryOtpColorDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Color ',
		displayName: 'Primary Otp Color Design Filled',
		name: 'primaryOtpColorDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Secondary Otp Color Design Filled',
		name: 'secondaryOtpColorDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._secondary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Tertiary Otp Color Design Filled',
		name: 'tertiaryOtpColorDesignFilled',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._tertiary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Quaternary Otp Color Design Filled',
		name: 'quaternaryOtpColorDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Quinary Otp Color Design Filled',
		name: 'quinaryOtpColorDesignFilled',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Color ',
		displayName: 'Primary Otp Color Design Round',
		name: 'primaryOtpColorDesignRound',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Secondary Otp Color Design Round',
		name: 'secondaryOtpColorDesignRound',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._secondary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Tertiary Otp Color Design Round',
		name: 'tertiaryOtpColorDesignRound',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._tertiary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Quaternary Otp Color Design Round',
		name: 'quaternaryOtpColorDesignRound',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color ',
		displayName: 'Quinary Otp Color Design Round',
		name: 'quinaryOtpColorDesignRound',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Color Active',
		displayName: 'Primary Otp Color Active Design Default',
		name: 'primaryOtpColorActiveDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Secondary Otp Color Active Design Default',
		name: 'secondaryOtpColorActiveDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default_secondary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Tertiary Otp Color Active Design Default',
		name: 'tertiaryOtpColorActiveDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._tertiary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Quaternary Otp Color Active Design Default',
		name: 'quaternaryOtpColorActiveDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Quinary Otp Color Active Design Default',
		name: 'quinaryOtpColorActiveDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Color Active',
		displayName: 'Primary Otp Color Active Design Dashed',
		name: 'primaryOtpColorActiveDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Secondary Otp Color Active Design Dashed',
		name: 'secondaryOtpColorActiveDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._secondary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Tertiary Otp Color Active Design Dashed',
		name: 'tertiaryOtpColorActiveDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._tertiary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Quaternary Otp Color Active Design Dashed',
		name: 'quaternaryOtpColorActiveDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Quinary Otp Color Active Design Dashed',
		name: 'quinaryOtpColorActiveDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Color Active',
		displayName: 'Primary Otp Color Active Design Filled',
		name: 'primaryOtpColorActiveDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Secondary Otp Color Active Design Filled',
		name: 'secondaryOtpColorActiveDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._secondary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Tertiary Otp Color Active Design Filled',
		name: 'tertiaryOtpColorActiveDesignFilled',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._tertiary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Quaternary Otp Color Active Design Filled',
		name: 'quaternaryOtpColorActiveDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Quinary Otp Color Active Design Filled',
		name: 'quinaryOtpColorActiveDesignFilled',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Color Active',
		displayName: 'Primary Otp Color Active Design Round',
		name: 'primaryOtpColorActiveDesignRound',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Secondary Otp Color Active Design Round',
		name: 'secondaryOtpColorActiveDesignRound',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._secondary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Tertiary Otp Color Active Design Round',
		name: 'tertiaryOtpColorActiveDesignRound',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._tertiary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Quaternary Otp Color Active Design Round',
		name: 'quaternaryOtpColorActiveDesignRound',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Active',
		displayName: 'Quinary Otp Color Active Design Round',
		name: 'quinaryOtpColorActiveDesignRound',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Color Has Value',
		displayName: 'Primary Otp Color Has Value Design Default',
		name: 'primaryOtpColorHasValueDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._primary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: 'Secondary Otp Color Has Value Design Default',
		name: 'secondaryOtpColorHasValueDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._secondary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: 'Tertiary Otp Color Has Value Design Default',
		name: 'tertiaryOtpColorHasValueDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._tertiary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: 'Quaternary Otp Color Has Value Design Default',
		name: 'quaternaryOtpColorHasValueDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._quaternary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: 'Quinary Otp Color Has Value Design Default',
		name: 'quinaryOtpColorHasValueDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._quinary ._inputBox._hasValue',
		noPrefix: true,
	},

	{
		groupName: 'Otp Color Has Value',
		displayName: 'Primary Otp Color Has Value Design Dashed',
		name: 'primaryOtpColorHasValueDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._primary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: 'Secondary Otp Color Has Value Design Dashed',
		name: 'secondaryOtpColorHasValueDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._secondary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: 'Tertiary Otp Color Has Value Design Dashed',
		name: 'tertiaryOtpColorHasValueDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._tertiary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: 'Quaternary Otp Color Has Value Design Dashed',
		name: 'quaternaryOtpColorHasValueDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._quaternary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: 'Quinary Otp Color Has Value Design Dashed',
		name: 'quinaryOtpColorHasValueDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._quinary ._inputBox._hasValue',
		noPrefix: true,
	},

	{
		groupName: 'Otp Color Has Value',
		displayName: ' Otp Color Has Value Design Filled Primary',
		name: ' OtpColorHasValueDesignFilledPrimary',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._primary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: ' Otp Color Has Value Design FilledSecondary',
		name: ' OtpColorHasValueDesignFilledSecondary',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._secondary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: ' Otp Color Has Value Design FilledTertiary',
		name: ' OtpColorHasValueDesignFilledTertiary',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._tertiary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: ' Otp Color Has Value Design FilledQuaternary',
		name: ' OtpColorHasValueDesignFilledQuaternary',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._quaternary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: ' Otp Color Has Value Design FilledQuinary',
		name: ' OtpColorHasValueDesignFilledQuinary',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._quinary ._inputBox._hasValue',
		noPrefix: true,
	},

	{
		groupName: 'Otp Color Has Value',
		displayName: ' Otp Color Has Value Design Round Primary',
		name: ' OtpColorHasValueDesignRoundPrimary',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._primary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: ' Otp Color Has Value Design RoundSecondary',
		name: ' OtpColorHasValueDesignRoundSecondary',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._secondary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: ' Otp Color Has Value Design RoundTertiary',
		name: ' OtpColorHasValueDesignRoundTertiary',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._tertiary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: ' Otp Color Has Value Design RoundQuaternary',
		name: ' OtpColorHasValueDesignRoundQuaternary',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._quaternary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Color Has Value',
		displayName: ' Otp Color Has Value Design RoundQuinary',
		name: ' OtpColorHasValueDesignRoundQuinary',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._quinary ._inputBox._hasValue',
		noPrefix: true,
	},

	{
		groupName: 'Otp Disabled  Color Default',
		displayName: 'Primary Otp Disabled text Color Default Design Filled',
		name: 'primaryOtpDisabledtextColorDefaultDesignFilled',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._primary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled  Color Default',
		displayName: 'Secondary Otp Disabled text Color Default Design Filled',
		name: 'secondaryOtpDisabledtextColorDefaultDesignFilled',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._secondary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled  Color Default',
		displayName: 'Tertiary Otp Disabled text Color Default Design Filled',
		name: 'tertiaryOtpDisabledtextColorDefaultDesignFilled',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._tertiary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled  Color Default',
		displayName: 'Quaternary Otp Disabled text Color Default Design Filled',
		name: 'quaternaryOtpDisabledtextColorDefaultDesignFilled',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._quaternary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled  Color Default',
		displayName: 'Quinary Otp Disabled text Color Default Design Filled',
		name: 'quinaryOtpDisabledtextColorDefaultDesignFilled',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._quinary._disabled ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Input Width',
		displayName: 'Otp Input Width Design Default',
		name: 'otpInputWidthDesignDefault',
		defaultValue: '30px',
		cssProperty: 'width',
		selector: '.comp.compOtp._default ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Input Width',
		displayName: 'Otp Input Width Design Dashed',
		name: 'otpInputWidthDesignDashed',
		defaultValue: '30px',
		cssProperty: 'width',
		selector: '.comp.compOtp._dashed ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Input Width',
		displayName: 'Otp Input Width Design Filled',
		name: 'otpInputWidthDesignFilled',
		defaultValue: '30px',
		cssProperty: 'width',
		selector: '.comp.compOtp._filled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Input Width',
		displayName: 'Otp Input Width Design Round',
		name: 'otpInputWidthDesignRound',
		defaultValue: '30px',
		cssProperty: 'width',
		selector: '.comp.compOtp._round ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Input Height',
		displayName: 'Otp Input Height Design Default',
		name: 'otpInputHeightDesignDefault',
		defaultValue: '30px',
		cssProperty: 'height',
		selector: '.comp.compOtp._default ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Input Height',
		displayName: 'Otp Input Height Design Dashed',
		name: 'otpInputHeightDesignDashed',
		defaultValue: '30px',
		cssProperty: 'height',
		selector: '.comp.compOtp._dashed ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Input Height',
		displayName: 'Otp Input Height Design Filled',
		name: 'otpInputHeightDesignFilled',
		defaultValue: '30px',
		cssProperty: 'height',
		selector: '.comp.compOtp._filled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Input Height',
		displayName: 'Otp Input Height Design Round',
		name: 'otpInputHeightDesignRound',
		defaultValue: '30px',
		cssProperty: 'height',
		selector: '.comp.compOtp._round ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Input Margin',
		displayName: 'Otp Input Margin Design Default',
		name: 'otpInputMarginDesignDefault',
		defaultValue: '8px',
		cssProperty: 'margin',
		selector: '.comp.compOtp._default ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Input Margin',
		displayName: 'Otp Input Margin Design Dashed',
		name: 'otpInputMarginDesignDashed',
		defaultValue: '8px',
		cssProperty: 'margin',
		selector: '.comp.compOtp._dashed ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Input Margin',
		displayName: 'Otp Input Margin Design Filled',
		name: 'otpInputMarginDesignFilled',
		defaultValue: '8px',
		cssProperty: 'margin',
		selector: '.comp.compOtp._filled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Input Margin',
		displayName: 'Otp Input Margin Design Round',
		name: 'otpInputMarginDesignRound',
		defaultValue: '8px',
		cssProperty: 'margin',
		selector: '.comp.compOtp._round ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Input Border Style',
		displayName: 'Otp Input Border Style Design Default',
		name: 'otpInputBorderStyleDesignDefault',
		defaultValue: 'solid',
		cssProperty: 'border-style',
		selector: '.comp.compOtp._default ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Input Border Style',
		displayName: 'Otp Input Border Style Design Dashed',
		name: 'otpInputBorderStyleDesignDashed',
		defaultValue: 'solid',
		cssProperty: 'border-style',
		selector: '.comp.compOtp._dashed ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Input Border Style',
		displayName: 'Otp Input Border Style Design Filled',
		name: 'otpInputBorderStyleDesignFilled',
		defaultValue: 'solid',
		cssProperty: 'border-style',
		selector: '.comp.compOtp._filled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Input Border Style',
		displayName: 'Otp Input Border Style Design Round',
		name: 'otpInputBorderStyleDesignRound',
		defaultValue: 'solid',
		cssProperty: 'border-style',
		selector: '.comp.compOtp._round ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border ',
		displayName: 'Otp Border  Design Default',
		name: 'otpBorderDesignDefault',
		defaultValue: '1 px solid',
		cssProperty: 'border',
		selector: '.comp.compOtp._default ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border ',
		displayName: 'Otp Border  Design Dashed',
		name: 'otpBorderDesignDashed',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compOtp._dashed ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border ',
		displayName: 'Otp Border  Design Filled',
		name: 'otpBorderDesignFilled',
		defaultValue: '1 px solid',
		cssProperty: 'border',
		selector: '.comp.compOtp._filled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border ',
		displayName: 'Otp Border  Design Round',
		name: 'otpBorderDesignRound',
		defaultValue: '1 px solid',
		cssProperty: 'border',
		selector: '.comp.compOtp._round ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Active',
		displayName: 'Otp Border Active Design Default',
		name: 'otpBorderActiveDesignDefault',
		defaultValue: '2 px solid',
		cssProperty: 'border',
		selector: '.comp.compOtp._default ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Active',
		displayName: 'Otp Border Active Design Dashed',
		name: 'otpBorderActiveDesignDashed',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compOtp._dashed ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Active',
		displayName: 'Otp Border Active Design Filled',
		name: 'otpBorderActiveDesignFilled',
		defaultValue: '2 px solid',
		cssProperty: 'border',
		selector: '.comp.compOtp._filled ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Active',
		displayName: 'Otp Border Active Design Round',
		name: 'otpBorderActiveDesignRound',
		defaultValue: '2 px solid',
		cssProperty: 'border',
		selector: '.comp.compOtp._round ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Bottom',
		displayName: 'Otp Border Bottom Design Default',
		name: 'otpBorderBottomDesignDefault',
		cssProperty: 'border-bottom',
		selector: '.comp.compOtp._default ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Bottom',
		displayName: 'Otp Border Bottom Design Dashed',
		name: 'otpBorderBottomDesignDashed',
		defaultValue: '2px solid',
		cssProperty: 'border-bottom',
		selector: '.comp.compOtp._dashed ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Bottom',
		displayName: 'Otp Border Bottom Design Filled',
		name: 'otpBorderBottomDesignFilled',
		cssProperty: 'border-bottom',
		selector: '.comp.compOtp._filled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Bottom',
		displayName: 'Otp Border Bottom Design Round',
		name: 'otpBorderBottomDesignRound',
		cssProperty: 'border-bottom',
		selector: '.comp.compOtp._round ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Bottom Active',
		displayName: 'Otp Border Bottom Active Design Default',
		name: 'otpBorderBottomActiveDesignDefault',
		cssProperty: 'border-bottom',
		selector: '.comp.compOtp._default ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Bottom Active',
		displayName: 'Otp Border Bottom Active Design Dashed',
		name: 'otpBorderBottomActiveDesignDashed',
		defaultValue: '2px solid',
		cssProperty: 'border-bottom',
		selector: '.comp.compOtp._dashed ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Bottom Active',
		displayName: 'Otp Border Bottom Active Design Filled',
		name: 'otpBorderBottomActiveDesignFilled',
		cssProperty: 'border-bottom',
		selector: '.comp.compOtp._filled ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Bottom Active',
		displayName: 'Otp Border Bottom Active Design Round',
		name: 'otpBorderBottomActiveDesignRound',
		cssProperty: 'border-bottom',
		selector: '.comp.compOtp._round ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Radius',
		displayName: 'Otp Border Radius Design Default',
		name: 'otpBorderRadiusDesignDefault',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compOtp._default ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Radius',
		displayName: 'Otp Border Radius Design Dashed',
		name: 'otpBorderRadiusDesignDashed',
		defaultValue: '0px',
		cssProperty: 'border-radius',
		selector: '.comp.compOtp._dashed ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Radius',
		displayName: 'Otp Border Radius Design Filled',
		name: 'otpBorderRadiusDesignFilled',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compOtp._filled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Radius',
		displayName: 'Otp Border Radius Design Round',
		name: 'otpBorderRadiusDesignRound',
		defaultValue: '50px',
		cssProperty: 'border-radius',
		selector: '.comp.compOtp._round ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Bottom Color Default',
		displayName: 'Primary Otp Border Color Default Design Dashed',
		name: 'primaryOtpBorderColorDefaultDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._primary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Bottom Color Default',
		displayName: 'Secondary Otp Border Color Default Design Dashed',
		name: 'secondaryOtpBorderColorDefaultDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._secondary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Bottom Color Default',
		displayName: 'Tertiary Otp Border Color Default Design Dashed',
		name: 'tertiaryOtpBorderColorDefaultDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._tertiary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Bottom Color Default',
		displayName: 'Quaternary Otp Border Color Default Design Dashed',
		name: 'quaternaryOtpBorderColorDefaultDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._quaternary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Bottom Color Default',
		displayName: 'Quinary Otp Border Color Default Design Dashed',
		name: 'quinaryOtpBorderColorDefaultDesignDashed',
		defaultValue: '<fontColorOne>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._quinary ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Bottom Color Active',
		displayName: 'Primary Otp Border Bottom Color Active Design Dashed',
		name: 'primaryOtpBorderBottomColorActiveDesignDashed',
		defaultValue: '<fontColorThree>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Bottom Color Active',
		displayName: 'Secondary Otp Border Bottom Color Active Design Dashed',
		name: 'secondaryOtpBorderBottomColorActiveDesignDashed',
		defaultValue: '<fontColorFour>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._secondary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Bottom Color Active',
		displayName: 'Tertiary Otp Border Bottom Color Active Design Dashed',
		name: 'tertiaryOtpBorderBottomColorActiveDesignDashed',
		defaultValue: '<fontColorFive>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._tertiary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Bottom Color Active',
		displayName: 'Quaternary Otp Border Bottom Color Active Design Dashed',
		name: 'quaternaryOtpBorderBottomColorActiveDesignDashed',
		defaultValue: '<fontColorNine>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Bottom Color Active',
		displayName: 'Quinary Otp Border Bottom Color Active Design Dashed',
		name: 'quinaryOtpBorderBottomColorActiveDesignDashed',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Color Default',
		displayName: 'Primary Otp Border Color Default Design Default',
		name: 'primaryOtpBorderColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._primary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Default',
		displayName: 'Secondary Otp Border Color Default Design Default',
		name: 'secondaryOtpBorderColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._secondary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Default',
		displayName: 'Tertiary Otp Border Color Default Design Default',
		name: 'tertiaryOtpBorderColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._tertiary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Default',
		displayName: 'Quaternary Otp Border Color Default Design Default',
		name: 'quaternaryOtpBorderColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._quaternary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Default',
		displayName: 'Quinary Otp Border Color Default Design Default',
		name: 'quinaryOtpBorderColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._quinary ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Color Default',
		displayName: 'Primary Otp Border Color Default Design Filled',
		name: 'primaryOtpBorderColorDefaultDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._primary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Default',
		displayName: 'Secondary Otp Border Color Default Design Filled',
		name: 'secondaryOtpBorderColorDefaultDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._secondary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Default',
		displayName: 'Tertiary Otp Border Color Default Design Filled',
		name: 'tertiaryOtpBorderColorDefaultDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._tertiary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Default',
		displayName: 'Quaternary Otp Border Color Default Design Filled',
		name: 'quaternaryOtpBorderColorDefaultDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._quaternary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Default',
		displayName: 'Quinary Otp Border Color Default Design Filled',
		name: 'quinaryOtpBorderColorDefaultDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._quinary ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Color Default',
		displayName: 'Primary Otp Border Color Default Design Round',
		name: 'primaryOtpBorderColorDefaultDesignRound',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._primary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Default',
		displayName: 'Secondary Otp Border Color Default Design Round',
		name: 'secondaryOtpBorderColorDefaultDesignRound',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._secondary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Default',
		displayName: 'Tertiary Otp Border Color Default Design Round',
		name: 'tertiaryOtpBorderColorDefaultDesignRound',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._tertiary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Default',
		displayName: 'Quaternary Otp Border Color Default Design Round',
		name: 'quaternaryOtpBorderColorDefaultDesignRound',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._quaternary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Default',
		displayName: 'Quinary Otp Border Color Default Design Round',
		name: 'quinaryOtpBorderColorDefaultDesignRound',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._quinary ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Color Active',
		displayName: 'Primary Otp Border Color Active Design Default',
		name: 'primaryOtpBorderColorActiveDesignDefault',
		defaultValue: '<fontColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Active',
		displayName: 'Secondary Otp Border Color Active Design Default',
		name: 'secondaryOtpBorderColorActiveDesignDefault',
		defaultValue: '<fontColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._secondary  ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Active',
		displayName: 'Tertiary Otp Border Color Active Design Default',
		name: 'tertiaryOtpBorderColorActiveDesignDefault',
		defaultValue: '<fontColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._tertiary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Active',
		displayName: 'Quaternary Otp Border Color Active Design Default',
		name: 'quaternaryOtpBorderColorActiveDesignDefault',
		defaultValue: '<fontColorNine>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Active',
		displayName: 'Quinary Otp Border Color Active Design Default',
		name: 'quinaryOtpBorderColorActiveDesignDefault',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Color Active',
		displayName: 'Primary Otp Border Color Active Design Filled',
		name: 'primaryOtpBorderColorActiveDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Active',
		displayName: 'Secondary Otp Border Color Active Design Filled',
		name: 'secondaryOtpBorderColorActiveDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._secondary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Active',
		displayName: 'Tertiary Otp Border Color Active Design Filled',
		name: 'tertiaryOtpBorderColorActiveDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._tertiary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Active',
		displayName: 'Quaternary Otp Border Color Active Design Filled',
		name: 'quaternaryOtpBorderColorActiveDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Active',
		displayName: 'Quinary Otp Border Color Active Design Filled',
		name: 'quinaryOtpBorderColorActiveDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Color Active',
		displayName: 'Primary Otp Border Color Active Design Round',
		name: 'primaryOtpBorderColorActiveDesignRound',
		defaultValue: '<fontColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Active',
		displayName: 'Secondary Otp Border Color Active Design Round',
		name: 'secondaryOtpBorderColorActiveDesignRound',
		defaultValue: '<fontColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._secondary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Active',
		displayName: 'Tertiary Otp Border Color Active Design Round',
		name: 'tertiaryOtpBorderColorActiveDesignRound',
		defaultValue: '<fontColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._tertiary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Active',
		displayName: 'Quaternary Otp Border Color Active Design Round',
		name: 'quaternaryOtpBorderColorActiveDesignRound',
		defaultValue: '<fontColorNine>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Active',
		displayName: 'Quinary Otp Border Color Active Design Round',
		name: 'quinaryOtpBorderColorActiveDesignRound',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Primary Otp Border Bottom Color Has Value Design Default',
		name: 'primaryOtpBorderColorHasValueDefault',
		defaultValue: '<fontColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._primary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Secondary Otp Border Bottom Color Has Value Design Default',
		name: 'secondaryOtpBorderColorHasValueDefault',
		defaultValue: '<fontColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._secondary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Tertiary Otp Border Bottom Color Has Value Design Default',
		name: 'tertiaryOtpBorderColorHasValueDefault',
		defaultValue: '<fontColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._tertiary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Quaternary Otp Border Bottom Color Has Value Design Default',
		name: 'quaternaryOtpBorderColorHasValueDefault',
		defaultValue: '<fontColorNine>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._quaternary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Quinary Otp Border Bottom Color Has Value Design Dashed',
		name: 'quinaryOtpBorderColorHasValueDefault',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._quinary ._inputBox._hasValue',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Primary Otp Border Bottom Color Has Value Design Dashed',
		name: 'primaryOtpBorderBottomColorHasValueDesignDashed',
		defaultValue: '<fontColorThree>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._primary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Secondary Otp Border Bottom Color Has Value Design Dashed',
		name: 'secondaryOtpBorderBottomColorHasValueDesignDashed',
		defaultValue: '<fontColorFour>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._secondary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Tertiary Otp Border Bottom Color Has Value Design Dashed',
		name: 'tertiaryOtpBorderBottomColorHasValueDesignDashed',
		defaultValue: '<fontColorFive>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._tertiary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Quaternary Otp Border Bottom Color Has Value Design Dashed',
		name: 'quaternaryOtpBorderBottomColorHasValueDesignDashed',
		defaultValue: '<fontColorNine>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._quaternary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Quinary Otp Border Bottom Color Has Value Design Dashed',
		name: 'quinaryOtpBorderBottomColorHasValueDesignDashed',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._quinary ._inputBox._hasValue',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Primary Otp Border Bottom Color Has Value Design Filled',
		name: 'primaryOtpBorderColorHasValueDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._primary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Secondary Otp Border Bottom Color Has Value Design Filled',
		name: 'secondaryOtpBorderColorHasValueDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._secondary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Tertiary Otp Border Bottom Color Has Value Design Filled',
		name: 'tertiaryOtpBorderColorHasValueDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._tertiary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Quaternary Otp Border Bottom Color Has Value Design Filled',
		name: 'quaternaryOtpBorderColorHasValueDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._quaternary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Quinary Otp Border Bottom Color Has Value Design Filled',
		name: 'quinaryOtpBorderColorHasValueDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._quinary ._inputBox._hasValue',
		noPrefix: true,
	},

	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Primary Otp Border Bottom Color Has Value Design Round',
		name: 'primaryOtpBorderColorHasValueDesignRound',
		defaultValue: '<fontColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._primary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Secondary Otp Border Bottom Color Has Value Design Round',
		name: 'secondaryOtpBorderColorHasValueDesignRound',
		defaultValue: '<fontColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._secondary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Tertiary Otp Border Bottom Color Has Value Design Round',
		name: 'tertiaryOtpBorderColorHasValueDesignRound',
		defaultValue: '<fontColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._tertiary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Quaternary Otp Border Bottom Color Has Value Design Round',
		name: 'quaternaryOtpBorderColorHasValueDesignRound',
		defaultValue: '<fontColorNine>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._quaternary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Border Color Has Value',
		displayName: 'Quinary Otp Border Bottom Color Has Value Design Round',
		name: 'quinaryOtpBorderColorHasValueDesignRound',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._quinary ._inputBox._hasValue',
		noPrefix: true,
	},

	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Primary Otp Disabled Color Default Design Default',
		name: 'primaryOtpDisabledColorDefaultDesignDefault',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._primary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Secondary Otp DisabledColor Default Design Default',
		name: 'secondaryOtpDisabledColorDefaultDesignDefault',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._secondary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Tertiary Otp Disabled Color Default Design Default',
		name: 'tertiaryOtpDisabledColorDefaultDesignDefault',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._tertiary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Quaternary Otp Disabled Color Default Design Default',
		name: 'quaternaryOtpDisabledColorDefaultDesignDefault',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._quaternary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Quinary Otp Disabled Color Default Design Default',
		name: 'quinaryOtpDisabledColorDefaultDesignDefault',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._default._quinary._disabled ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Primary Otp Disabled Color Default Design Dashed',
		name: 'primaryOtpDisabledColorDefaultDesignDashed',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._primary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Secondary Otp Disabled Color Default Design Dashed',
		name: 'secondaryOtpDisabledColorDefaultDesignDashed',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._secondary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Tertiary Otp Disabled Color Default Design Dashed',
		name: 'tertiaryOtpDisabledColorDefaultDesignDashed',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._tertiary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Quaternary Otp Disabled Color Default Design Dashed',
		name: 'quaternaryOtpDisabledColorDefaultDesignDashed',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._quaternary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Quinary Otp Disabled Color Default Design Dashed',
		name: 'quinaryOtpDisabledColorDefaultDesignDashed',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-bottom-color',
		selector: '.comp.compOtp._dashed._quinary._disabled ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Primary Otp Disabled Color Default Design Filled',
		name: 'primaryOtpDisabledColorDefaultDesignFilled',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._primary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Secondary Otp Disabled Color Default Design Filled',
		name: 'secondaryOtpDisabledColorDefaultDesignFilled',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._secondary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Tertiary Otp Disabled Color Default Design Filled',
		name: 'tertiaryOtpDisabledColorDefaultDesignFilled',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._tertiary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Quaternary Otp Disabled Color Default Design Filled',
		name: 'quaternaryOtpDisabledColorDefaultDesignFilled',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._quaternary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Quinary Otp Disabled Color Default Design Filled',
		name: 'quinaryOtpDisabledColorDefaultDesignFilled',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._filled._quinary._disabled ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Primary Otp Disabled Color Default Design Round',
		name: 'primaryOtpDisabledColorDefaultDesignRound',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._primary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Secondary Otp Disabled Color Default Design Round',
		name: 'secondaryOtpDisabledColorDefaultDesignRound',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._secondary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Tertiary Otp Disabled Color Default Design Round',
		name: 'tertiaryOtpDisabledColorDefaultDesignRound',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._tertiary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Quaternary Otp Disabled Color Default Design Round',
		name: 'quaternaryOtpDisabledColorDefaultDesignRound',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._quaternary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Color Default',
		displayName: 'Quinary Otp Disabled Color Default Design Round',
		name: 'quinaryOtpDisabledColorDefaultDesignRound',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compOtp._round._quinary._disabled ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Background Default',
		displayName: 'Primary Otp Background Default Design Default',
		name: 'primaryOtpBackgroundDefaultDesignDefault',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._default._primary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Secondary Otp Background Default Design Default',
		name: 'secondaryOtpBackgroundDefaultDesignDefault',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._default._secondary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Tertiary Otp Background Default Design Default',
		name: 'tertiaryOtpBackgroundDefaultDesignDefault',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._default._tertiary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Quaternary Otp Background Default Design Default',
		name: 'quaternaryOtpBackgroundDefaultDesignDefault',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._default._quaternary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Quinary Otp Background Default Design Default',
		name: 'quinaryOtpBackgroundDefaultDesignDefault',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._default._quinary ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Background Default',
		displayName: 'Primary Otp Background Default Design Dashed',
		name: 'primaryOtpBackgroundDefaultDesignDashed',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._primary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Secondary Otp Background Default Design Dashed',
		name: 'secondaryOtpBackgroundDefaultDesignDashed',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._secondary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Tertiary Otp Background Default Design Dashed',
		name: 'tertiaryOtpBackgroundDefaultDesignDashed',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._tertiary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Quaternary Otp Background Default Design Dashed',
		name: 'quaternaryOtpBackgroundDefaultDesignDashed',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._quaternary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Quinary Otp Background Default Design Dashed',
		name: 'quinaryOtpBackgroundDefaultDesignDashed',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._quinary ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Background Default',
		displayName: 'Primary Otp Background Default Design Filled',
		name: 'primaryOtpBackgroundDefaultDesignFilled',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._primary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Secondary Otp Background Default Design Filled',
		name: 'secondaryOtpBackgroundDefaultDesignFilled',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._secondary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Tertiary Otp Background Default Design Filled',
		name: 'tertiaryOtpBackgroundDefaultDesignFilled',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._tertiary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Quaternary Otp Background Default Design Filled',
		name: 'quaternaryOtpBackgroundDefaultDesignFilled',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._quaternary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Quinary Otp Background Default Design Filled',
		name: 'quinaryOtpBackgroundDefaultDesignFilled',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._quinary ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Background Default',
		displayName: 'Primary Otp Background Default Design Round',
		name: 'primaryOtpBackgroundDefaultDesignRound',
		defaultValue: 'linear-gradient(90deg, #96A1B41A 0%, #33333300 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compOtp._round._primary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Secondary Otp Background Default Design Round',
		name: 'secondaryOtpBackgroundDefaultDesignRound',
		defaultValue: 'linear-gradient(90deg, #96A1B41A 0%, #33333300 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compOtp._round._secondary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Tertiary Otp Background Default Design Round',
		name: 'tertiaryOtpBackgroundDefaultDesignRound',
		defaultValue: 'linear-gradient(90deg, #96A1B41A 0%, #33333300 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compOtp._round._tertiary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Quaternary Otp Background Default Design Round',
		name: 'quaternaryOtpBackgroundDefaultDesignRound',
		defaultValue: 'linear-gradient(90deg, #96A1B41A 0%, #33333300 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compOtp._round._quaternary ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Default',
		displayName: 'Quinary Otp Background Default Design Round',
		name: 'quinaryOtpBackgroundDefaultDesignRound',
		defaultValue: 'linear-gradient(90deg, #96A1B41A 0%, #33333300 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compOtp._round._quinary ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Background Active',
		displayName: 'Primary Otp Background Active Design Default',
		name: 'primaryOtpBackgroundActiveDesignDefault',
		cssProperty: 'background',
		selector: '.comp.compOtp._default._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Secondary Otp Background Active Design Default',
		name: 'secondaryOtpBackgroundActiveDesignDefault',
		cssProperty: 'background',
		selector: '.comp.compOtp._default._secondary  ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Tertiary Otp Background Active Design Default',
		name: 'tertiaryOtpBackgroundActiveDesignDefault',
		cssProperty: 'background',
		selector: '.comp.compOtp._default._tertiary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Quaternary Otp Background Active Design Default',
		name: 'quaternaryOtpBackgroundActiveDesignDefault',
		cssProperty: 'background',
		selector: '.comp.compOtp._default._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Quinary Otp Background Active Design Default',
		name: 'quinaryOtpBackgroundActiveDesignDefault',
		cssProperty: 'background',
		selector: '.comp.compOtp._default._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Background Active',
		displayName: 'Primary Otp Background Active Design Dashed',
		name: 'primaryOtpBackgroundActiveDesignDashed',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Secondary Otp Background Active Design Dashed',
		name: 'secondaryOtpBackgroundActiveDesignDashed',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._secondary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Tertiary Otp Background Active Design Dashed',
		name: 'tertiaryOtpBackgroundActiveDesignDashed',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._tertiary._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Quaternary Otp Background Active Design Dashed',
		name: 'quaternaryOtpBackgroundActiveDesignDashed',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Quinary Otp Background Active Design Dashed',
		name: 'quinaryOtpBackgroundActiveDesignDashed',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Background Active',
		displayName: 'Primary Otp Background Active Design Filled',
		name: 'primaryOtpBackgroundActiveDesignFilled',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Secondary Otp Background Active Design Filled',
		name: 'secondaryOtpBackgroundActiveDesignFilled',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._secondary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Tertiary Otp Background Active Design Filled',
		name: 'tertiaryOtpBackgroundActiveDesignFilled',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._tertiary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Quaternary Otp Background Active Design Filled',
		name: 'quaternaryOtpBackgroundActiveDesignFilled',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Quinary Otp Background Active Design Filled',
		name: 'quinaryOtpBackgroundActiveDesignFilled',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Background Active',
		displayName: 'Primary Otp Background Active Design Round',
		name: 'primaryOtpBackgroundActiveDesignRound',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorOne>19 0%, <backgroundColorSix>00 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compOtp._round._primary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Secondary Otp Background Active Design Round',
		name: 'secondaryOtpBackgroundActiveDesignRound',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorTwo>19 0%, <backgroundColorSix>00 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compOtp._round._secondary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Tertiary Otp Background Active Design Round',
		name: 'tertiaryOtpBackgroundActiveDesignRound',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorThree>19 0%, <backgroundColorSix>00 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compOtp._round._tertiary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Quaternary Otp Background Active Design Round',
		name: 'quaternaryOtpBackgroundActiveDesignRound',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorFour>19 0%, <backgroundColorSix>00 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compOtp._round._quaternary ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Active',
		displayName: 'Quinary Otp Background Active Design Round',
		name: 'quinaryOtpBackgroundActiveDesignRound',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorFive>19 0%, <backgroundColorSix>00 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compOtp._round._quinary ._inputBox._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design DefaultPrimary',
		name: 'primaryOtpBackgroundHasValueDefault',
		cssProperty: 'background',
		selector: '.comp.compOtp._default._primary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design DefaultSecondary',
		name: 'secondaryOtpBackgroundHasValueDefault',
		cssProperty: 'background',
		selector: '.comp.compOtp._default._secondary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design DefaultTertiary',
		name: 'tertiaryOtpBackgroundHasValueDefault',
		cssProperty: 'background',
		selector: '.comp.compOtp._default._tertiary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design DefaultQuaternary',
		name: 'quaternaryOtpBackgroundHasValueDefault',
		cssProperty: 'background',
		selector: '.comp.compOtp._default._quaternary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design DefaultQuinary',
		name: 'quinaryOtpBackgroundHasValueDefault',
		cssProperty: 'background',
		selector: '.comp.compOtp._default._quinary ._inputBox._hasValue',
		noPrefix: true,
	},

	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design DashedPrimary',
		name: 'primaryOtpBackgroundHasValueDashed',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._primary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design DashedSecondary',
		name: 'secondaryOtpBackgroundHasValueDashed',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._secondary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design DashedTertiary',
		name: 'tertiaryOtpBackgroundHasValueDashed',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._tertiary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design DashedQuaternary',
		name: 'quaternaryOtpBackgroundHasValueDashed',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._quaternary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design DashedQuinary',
		name: 'quinaryOtpBackgroundHasValueDashed',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._quinary ._inputBox._hasValue',
		noPrefix: true,
	},

	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design FilledPrimary',
		name: 'primaryOtpBackgroundHasValueFilled',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._primary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design FilledSecondary',
		name: 'secondaryOtpBackgroundHasValueFilled',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._secondary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design FilledTertiary',
		name: 'tertiaryOtpBackgroundHasValueFilled',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._tertiary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design FilledQuaternary',
		name: 'quaternaryOtpBackgroundHasValueFilled',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._quaternary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design FilledQuinary',
		name: 'quinaryOtpBackgroundHasValueFilled',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._quinary ._inputBox._hasValue',
		noPrefix: true,
	},

	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design RoundPrimary',
		name: 'primaryOtpBackgroundHasValueRound',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorOne>19 0%, <backgroundColorSix>00 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compOtp._round._primary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design RoundSecondary',
		name: 'secondaryOtpBackgroundHasValueRound',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorTwo>19 0%, <backgroundColorSix>00 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compOtp._round._secondary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design RoundTertiary',
		name: 'tertiaryOtpBackgroundHasValueRound',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorThree>19 0%, <backgroundColorSix>00 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compOtp._round._tertiary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design RoundQuaternary',
		name: 'quaternaryOtpBackgroundHasValueRound',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorFour>19 0%, <backgroundColorSix>00 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compOtp._round._quaternary ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Background Has Value',
		displayName: ' Otp Background Has Value Design RoundQuinary',
		name: 'quinaryOtpBackgroundHasValueRound',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorFive>19 0%, <backgroundColorSix>00 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compOtp._round._quinary ._inputBox._hasValue',
		noPrefix: true,
	},

	{
		groupName: 'Otp Disabled Background Color Default',
		displayName: 'Primary Otp Disabled Background Color Default Design Dashed',
		name: 'primaryOtpDisabledBackgroundColorDefaultDesignDashed',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._primary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Background Color Default',
		displayName: 'Secondary Otp Disabled Background Color Default Design Dashed',
		name: 'secondaryOtpDisabledBackgroundColorDefaultDesignDashed',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._secondary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Background Color Default',
		displayName: 'Tertiary Otp Disabled Background Color Default Design Dashed',
		name: 'tertiaryOtpDisabledBackgroundColorDefaultDesignDashed',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._tertiary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Background Color Default',
		displayName: 'Quaternary Otp Disabled Background Color Default Design Dashed',
		name: 'quaternaryOtpDisabledBackgroundColorDefaultDesignDashed',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._quaternary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Background Color Default',
		displayName: 'Quinary Otp Disabled Background Color Default Design Dashed',
		name: 'quinaryOtpDisabledBackgroundColorDefaultDesignDashed',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._dashed._quinary._disabled ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Disabled Background Color Default',
		displayName: 'Primary Otp Disabled Background Color Default Design Filled',
		name: 'primaryOtpDisabledBackgroundColorDefaultDesignFilled',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._primary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Background Color Default',
		displayName: 'Secondary Otp Disabled Background Color Default Design Filled',
		name: 'secondaryOtpDisabledBackgroundColorDefaultDesignFilled',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._secondary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Background Color Default',
		displayName: 'Tertiary Otp Disabled Background Color Default Design Filled',
		name: 'tertiaryOtpDisabledBackgroundColorDefaultDesignFilled',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._tertiary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Background Color Default',
		displayName: 'Quaternary Otp Disabled Background Color Default Design Filled',
		name: 'quaternaryOtpDisabledBackgroundColorDefaultDesignFilled',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._quaternary._disabled ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Disabled Background Color Default',
		displayName: 'Quinary Otp Disabled Background Color Default Design Filled',
		name: 'quinaryOtpDisabledBackgroundColorDefaultDesignFilled',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compOtp._filled._quinary._disabled ._inputBox',
		noPrefix: true,
	},

	{
		groupName: 'Otp Support Text Font',
		displayName: 'Otp Support Text Font Design Default',
		name: 'otpSupportTextFontDesignDefault',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compOtp._default ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Font',
		displayName: 'Otp Support Text Font Design Dashed',
		name: 'otpSupportTextFontDesignDashed',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compOtp._dashed ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Font',
		displayName: 'Otp Support Text Font Design Filled',
		name: 'otpSupportTextFontDesignFilled',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compOtp._filled ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Font',
		displayName: 'Otp Support Text Font Design Round',
		name: 'otpSupportTextFontDesignRound',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compOtp._round ._supportText',
		noPrefix: true,
	},

	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Primary Otp Support Text Color Default Design Default',
		name: 'primaryOtpSupportTextColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._primary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Secondary Otp Support Text Color Default Design Default',
		name: 'secondaryOtpSupportTextColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._secondary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Tertiary Otp Support Text Color Default Design Default',
		name: 'tertiaryOtpSupportTextColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._tertiary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Quaternary Otp Support Text Color Default Design Default',
		name: 'quaternaryOtpSupportTextColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._quaternary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Quinary Otp Support Text Color Default Design Default',
		name: 'quinaryOtpSupportTextColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._quinary ._supportText',
		noPrefix: true,
	},

	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Primary Otp Support Text Color Default Design Dashed',
		name: 'primaryOtpSupportTextColorDefaultDesignDashed',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._primary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Secondary Otp Support Text Color Default Design Dashed',
		name: 'secondaryOtpSupportTextColorDefaultDesignDashed',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._secondary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Tertiary Otp Support Text Color Default Design Dashed',
		name: 'tertiaryOtpSupportTextColorDefaultDesignDashed',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._tertiary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Quaternary Otp Support Text Color Default Design Dashed',
		name: 'quaternaryOtpSupportTextColorDefaultDesignDashed',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._quaternary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Quinary Otp Support Text Color Default Design Dashed',
		name: 'quinaryOtpSupportTextColorDefaultDesignDashed',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._quinary ._supportText',
		noPrefix: true,
	},

	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Primary Otp Support Text Color Default Design Filled',
		name: 'primaryOtpSupportTextColorDefaultDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._primary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Secondary Otp Support Text Color Default Design Filled',
		name: 'secondaryOtpSupportTextColorDefaultDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._secondary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Tertiary Otp Support Text Color Default Design Filled',
		name: 'tertiaryOtpSupportTextColorDefaultDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._tertiary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Quaternary Otp Support Text Color Default Design Filled',
		name: 'quaternaryOtpSupportTextColorDefaultDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._quaternary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Quinary Otp Support Text Color Default Design Filled',
		name: 'quinaryOtpSupportTextColorDefaultDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._quinary ._supportText',
		noPrefix: true,
	},

	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Primary Otp Support Text Color Default Design Round',
		name: 'primaryOtpSupportTextColorDefaultDesignRound',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._primary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Secondary Otp Support Text Color Default Design Round',
		name: 'secondaryOtpSupportTextColorDefaultDesignRound',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._secondary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Tertiary Otp Support Text Color Default Design Round',
		name: 'tertiaryOtpSupportTextColorDefaultDesignRound',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._tertiary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Quaternary Otp Support Text Color Default Design Round',
		name: 'quaternaryOtpSupportTextColorDefaultDesignRound',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._quaternary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Default',
		displayName: 'Quinary Otp Support Text Color Default Design Round',
		name: 'quinaryOtpSupportTextColorDefaultDesignRound',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._quinary ._supportText',
		noPrefix: true,
	},

	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Primary Otp Support Text Color Active Design Default',
		name: 'primaryOtpSupportTextColorActiveDesignDefault',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._primary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Secondary Otp Support Text Color Active Design Default',
		name: 'secondaryOtpSupportTextColorActiveDesignDefault',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._secondary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Tertiary Otp Support Text Color Active Design Default',
		name: 'tertiaryOtpSupportTextColorActiveDesignDefault',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._tertiary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Quaternary Otp Support Text Color Active Design Default',
		name: 'quaternaryOtpSupportTextColorActiveDesignDefault',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._quaternary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Quinary Otp Support Text Color Active Design Default',
		name: 'quinaryOtpSupportTextColorActiveDesignDefault',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector: '.comp.compOtp._default._quinary ._supportText._supportTextActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Primary Otp Support Text Color Active Design Dashed',
		name: 'primaryOtpSupportTextColorActiveDesignDashed',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._primary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Secondary Otp Support Text Color Active Design Dashed',
		name: 'secondaryOtpSupportTextColorActiveDesignDashed',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._secondary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Tertiary Otp Support Text Color Active Design Dashed',
		name: 'tertiaryOtpSupportTextColorActiveDesignDashed',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._tertiary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Quaternary Otp Support Text Color Active Design Dashed',
		name: 'quaternaryOtpSupportTextColorActiveDesignDashed',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._quaternary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Quinary Otp Support Text Color Active Design Dashed',
		name: 'quinaryOtpSupportTextColorActiveDesignDashed',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector: '.comp.compOtp._dashed._quinary ._supportText._supportTextActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Primary Otp Support Text Color Active Design Filled',
		name: 'primaryOtpSupportTextColorActiveDesignFilled',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._primary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Secondary Otp Support Text Color Active Design Filled',
		name: 'secondaryOtpSupportTextColorActiveDesignFilled',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._secondary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Tertiary Otp Support Text Color Active Design Filled',
		name: 'tertiaryOtpSupportTextColorActiveDesignFilled',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._tertiary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Quaternary Otp Support Text Color Active Design Filled',
		name: 'quaternaryOtpSupportTextColorActiveDesignFilled',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._quaternary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Quinary Otp Support Text Color Active Design Filled',
		name: 'quinaryOtpSupportTextColorActiveDesignFilled',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._quinary ._supportText._supportTextActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Primary Otp Support Text Color Active Design Round',
		name: 'primaryOtpSupportTextColorActiveDesignRound',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._primary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Secondary Otp Support Text Color Active Design Round',
		name: 'secondaryOtpSupportTextColorActiveDesignRound',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._secondary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Tertiary Otp Support Text Color Active Design Round',
		name: 'tertiaryOtpSupportTextColorActiveDesignRound',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._tertiary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Quaternary Otp Support Text Color Active Design Round',
		name: 'quaternaryOtpSupportTextColorActiveDesignRound',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._quaternary ._supportText._supportTextActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Support Text Color Active',
		displayName: 'Quinary Otp Support Text Color Active Design Round',
		name: 'quinaryOtpSupportTextColorActiveDesignRound',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector: '.comp.compOtp._round._quinary ._supportText._supportTextActive',
		noPrefix: true,
	},

	{
		groupName: 'Otp Error Border Color',
		displayName: 'Otp Error Border Color Design Default',
		name: 'otpErrorBorderColorDesignDefault',
		defaultValue: '<errorColor>',
		cssProperty: 'border-color',
		selector:
			'.comp.compOtp._default._hasError ._inputBox,.comp.compOtp._default._hasError ._inputBox._isActive, .comp.compOtp._default._hasError ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Error Border Color',
		displayName: 'Otp Error Border Color Design Dashed',
		name: 'otpErrorBorderColorDesignDashed',
		defaultValue: '<errorColor>',
		cssProperty: 'border-color',
		selector:
			'.comp.compOtp._dashed._hasError ._inputBox,.comp.compOtp._dashed._hasError ._inputBox._isActive, .comp.compOtp._dashed._hasError ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Error Border Color',
		displayName: 'Otp Error Border Color Design Filled',
		name: 'otpErrorBorderColorDesignFilled',
		cssProperty: 'border-color',
		selector:
			'.comp.compOtp._filled._hasError ._inputBox,.comp.compOtp._filled._hasError ._inputBox._isActive, .comp.compOtp._filled._hasError ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Error Border Color',
		displayName: 'Otp Error Border Color Design Round',
		name: 'otpErrorBorderColorDesignRound',
		defaultValue: '<errorColor>',
		cssProperty: 'border-color',
		selector:
			'.comp.compOtp._round._hasError ._inputBox,.comp.compOtp._round._hasError ._inputBox._isActive, .comp.compOtp._round._hasError ._inputBox._hasValue',
		noPrefix: true,
	},

	{
		groupName: 'Otp Error Background',
		displayName: 'Otp Error Background Design Default',
		name: 'otpErrorBackgroundDesignDefault',
		cssProperty: 'background',
		selector:
			'.comp.compOtp._default._hasError ._inputBox,.comp.compOtp._default._hasError ._inputBox._isActive, .comp.compOtp._default._hasError ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Error Background',
		displayName: 'Otp Error Background Design Dashed',
		name: 'otpErrorBackgroundDesignDashed',
		cssProperty: 'background',
		selector:
			'.comp.compOtp._dashed._hasError ._inputBox,.comp.compOtp._dashed._hasError ._inputBox._isActive, .comp.compOtp._dashed._hasError ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Error Background',
		displayName: 'Otp Error Background Design Filled',
		name: 'otpErrorBackgroundDesignFilled',
		defaultValue: '<errorColor>',
		cssProperty: 'background',
		selector:
			'.comp.compOtp._filled._hasError ._inputBox,.comp.compOtp._filled._hasError ._inputBox._isActive, .comp.compOtp._filled._hasError ._inputBox._hasValue',
		noPrefix: true,
	},
	{
		groupName: 'Otp Error Background',
		displayName: 'Otp Error Background Design Round',
		name: 'otpErrorBackgroundDesignRound',
		defaultValue: 'linear-gradient(90deg, <errorColor>19 0%, <backgroundColorSix>00 64.33%)',
		cssProperty: 'background',
		selector:
			'.comp.compOtp._round._hasError ._inputBox,.comp.compOtp._round._hasError ._inputBox._isActive, .comp.compOtp._round._hasError ._inputBox._hasValue',
		noPrefix: true,
	},

	{
		groupName: 'Otp Error Color',
		displayName: 'Otp Error Color Design Filled',
		name: 'otpErrorColorDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compTextBox._filled._hasError ._inputBox',
		noPrefix: true,
	},
	{
		groupName: 'Otp Error Color Active',
		displayName: 'Otp Error Color Active Design Filled',
		name: 'otpErrorColorActiveDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._hasError ._inputBox._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Otp Error Color Has Value',
		displayName: 'Otp Error Color Has Value Design Filled',
		name: 'otpErrorColorHasValueDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compOtp._filled._hasError ._inputBox._hasValue',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
