import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
    {
        name: 'calendarDivWidth',
        cssProperty: 'width',
        displayName: 'date and time input box width',
        description: "This is used to indicate the width of the calendar input box",
        defaultValue: '100%',
        selector: '.calendarDiv',
    },
    {
        name: 'calendarDivBorderColor',
        cssProperty: 'border',
        displayName: "Calendar Input's border color",
        description: "This color is used for Calendar input's border color.",
        defaultValue: '1px solid <form-input-border-color>',
        selector: '.calendarDiv',
    },
    {
        name: 'calendarDivHeight',
        cssProperty: 'height',
        displayName: "Calendar Div's height",
        description: "This is for Calendar Div's height",
        defaultValue: '56px',
        selector: '.calendarDiv',
    },
    {
        name: 'calendarDivBorderRadius',
        cssProperty: 'border-radius',
        displayName: "Calendar Div's border radius",
        description: "This is for Calendar Div's border radius",
        defaultValue: '4px',
        selector: '.calendarDiv',
    },
    {
        name: 'textBox left icon self align',
        cssProperty: 'justify-self',
        displayName: "textbox's left icon self align",
        description: "This is for textbox's left icon self align",
        defaultValue: 'center',
        selector: '.calendarDiv .calendarIcon',
    },
    {
        name: 'calendarDiv Calendar icon padding',
        cssProperty: 'padding',
        displayName: "CalendarDiv Calendar icon padding",
        description: "This is for Calendar icons's padding",
        defaultValue: '0',
        selector: '.calendarDiv .calendarIcon',
    },
    {
        name: 'calendarInputBoxContainerContentAlign',
        cssProperty: 'align-items',
        displayName: "calendar input Container Content Align in the grid",
        description: "This align items is used for Calendar InoutBox's conatiner content align.",
        defaultValue: 'center',
        selector: '.calendarDiv',
    },
    {
        name: 'calendarPopupContainerPositionRight',
        cssProperty: 'right',
        displayName: "calendar popup Container position right in the grid",
        description: "This position right is used for Calendar popup conatiner positon right.",
        defaultValue: '0',
        selector: '.calendarDiv .calendarPopOver',
    },
    {
        name: 'calendarPopupContainerPositionLeft',
        cssProperty: 'left',
        displayName: "calendar popup Container position Left in the grid",
        description: "This position left is used for Calendar popup conatiner positon Left.",
        defaultValue: '',
        selector: '.calendarDiv .calendarPopOver',
    },
    {
        name: 'calendarPopupContainerPositionBottom',
        cssProperty: 'bottom',
        displayName: "calendar popup Container position Left in the grid",
        description: "This position bottom is used for Calendar popup conatiner positon bottom.",
        selector: '.calendarDiv .calendarPopOver',
    },
    {
        name: 'calendarPopupContainerPositionTop',
        cssProperty: 'top',
        displayName: "calendar popup Container position Top in the grid",
        description: "This position top is used for Calendar popup conatiner positon Top.",
        defaultValue: '0',
        selector: '.calendarDiv .calendarPopOver',
    },
    {
        name: 'calendarPopupContainerMarginRight',
        cssProperty: 'margin-right',
        displayName: "calendar popup Container margin right in the grid",
        description: "This margin right is used for Calendar popup conatiner margin right.",
        selector: '.calendarDiv .calendarPopOver',
        defaultValue: '-400px'
    },
    {
        name: 'calendarPopupContainerMarginLeft',
        cssProperty: 'margin-left',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        selector: '.calendarDiv .calendarPopOver',
    },
    {
        name: 'calendarPopupContainerMarginTop',
        cssProperty: 'margin-top',
        displayName: "calendar popup Container margin top in the grid",
        description: "This margin top is used for Calendar popup conatiner margin top.",
        defaultValue: "20px",
        selector: '.calendarDiv .calendarPopOver',
    },
    {
        name: 'calendarPopupContainerMarginBottom',
        cssProperty: 'margin-bottom',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin bottom is used for Calendar popup conatiner margin bottom.",
        selector: '.calendarDiv .calendarPopOver',
    },
    {
        name: 'calendarPopupContainerBoxShadow',
        cssProperty: 'box-shadow',
        displayName: "calendar popup Container box shadow in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "1px 2px 8px hsl(0deg 0% 0% / 0.5)",
        selector: '.calendarDiv .calendarPopOver',
    },
    {
        name: 'calendarPopupContainerBorderColor',
        cssProperty: 'border',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        selector: '.calendarDiv .calendarPopOver',
    },
    {
        name: 'calendarPopupContainerBorderRadius',
        cssProperty: 'border-radius',
        displayName: "calendar popup Container border radius in the grid",
        description: "This border radius is used for Calendar popup conatiner border radius.",
        defaultValue: '2px',
        selector: '.calendarDiv .calendarPopOver',
    },
    {
        name: 'calendarPopupContainerwidth',
        cssProperty: 'width',
        displayName: "calendar popup Container border radius in the grid",
        description: "This border radius is used for Calendar popup conatiner border radius.",
        selector: '.calendarDiv .calendarPopOver',
    },
    {
        name: 'calendarCurrentDateDisplayModuleJustifyzItems',
        cssProperty: 'justify-items',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: 'center',
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv',
    },
    {
        name: 'calendarCurrentDateDisplayModuleBackgroundColor',
        cssProperty: 'background-color',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv',
    },
    {
        name: 'calendarCurrentDateDisplayModuleHeaderBackgroundColor',
        cssProperty: 'background-color',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarHeader',
    },
    {
        name: 'calendarCurrentDateDisplayModuleHeaderWidth',
        cssProperty: 'width',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "100%",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarHeader',
    },
    {
        name: 'calendarCurrentDateDisplayModuleHeaderDisplay',
        cssProperty: 'display',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "flex",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarHeader',
    },
    {
        name: 'calendarCurrentDateDisplayModuleHeaderJustfiyCenter',
        cssProperty: 'justify-content',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "space-between",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarHeader',
    },
    {
        name: 'calendarCurrentDateDisplayModuleHeaderPaddingTop',
        cssProperty: 'padding-top',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "10px",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarHeader',
    },
    {
        name: 'calendarCurrentDateDisplayModuleHeaderPaddingBottom',
        cssProperty: 'padding-bottom',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "10px",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarHeader',
    },
    {
        name: 'calendarCurrentDateDisplayModuleHeaderPaddingLeft',
        cssProperty: 'padding-left',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "4px",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarHeader',
    },
    {
        name: 'calendarCurrentDateDisplayModuleHeaderPaddingRight',
        cssProperty: 'padding-right',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "4px",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarHeader',
    },
    {
        name: 'calendarCurrentDateDisplayModuleHeaderIconBackgroundColorOnHover',
        cssProperty: 'background-color',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "#f5f5f5",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarMainCard .calendarHeader .iconLeft:hover, .calendarDiv .calendarPopOver .calendarPopupDiv .calendarMainCard .calendarHeader .rightIcon:hover',
    },
    {
        name: 'calendarCurrentDateDisplayModuleHeaderAlignContent',
        cssProperty: 'align-items',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "center",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarHeader',
    },
    {
        name: 'calendarPopupCalendarSelectedDateWidth',
        cssProperty: 'width',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "100%",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarSelectedDate',
    },
    {
        name: 'calendarPopupCalendarSelectedHeight',
        cssProperty: 'height',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarSelectedDate',
    },
    {
        name: 'calendarPopupCalendarSelectedDateBackgroundColor',
        cssProperty: 'background-color',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "<main-font-color>",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarSelectedDate',
    },
    {
        name: 'calendarPopupCalendarSelectedDateFontColor',
        cssProperty: 'color',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "<light-font-color>",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarSelectedDate',
    },
    {
        name: 'calendarPopupCalendarSelectedDatepaddingTop',
        cssProperty: 'padding-top',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "25px",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarSelectedDate',
    },
    {
        name: 'calendarPopupCalendarSelectedDatepaddingBottom',
        cssProperty: 'padding-bottom',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "25px",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarSelectedDate',
    },
    {
        name: 'calendarPopupContainerAlignItems',
        cssProperty: 'font-size',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "20px",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarSelectedDate',
    },
    {
        name: 'calendarPopupContainerCalendarSelectedDate',
        cssProperty: 'text-align',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "center",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarSelectedDate',
    },
    {
        name: 'calendarPopupMainCardPadding',
        cssProperty: 'padding',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarMainCard',
    },
    {
        name: 'calendarPopupMainCardPaddingLeft',
        cssProperty: 'padding-left',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: "20px",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarMainCard',
    },
    {
        name: 'calendarPopupMainCardPadddingRight',
        cssProperty: 'padding-right',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: '20px',
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarMainCard',
    },
    {
        name: 'calendarPopupMainCardPadddingTop',
        cssProperty: 'padding-top',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarMainCard',
    },
    {
        name: 'calendarPopupMainCardPadddingBottom',
        cssProperty: 'padding-bottom',
        displayName: "calendar popup Container margin left in the grid",
        description: "This margin left is used for Calendar popup conatiner margin left.",
        defaultValue: '20px',
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarMainCard',
    },
    {
        name: 'calendarPopupContainerMainCalendarPadding',
        cssProperty: 'padding',
        displayName: "calendar popup Container border radius in the grid",
        description: "This border radius is used for Calendar popup conatiner border radius.",
        defaultValue: '8px 8px 8px 8px',
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarMainCard .calendarRow',
    },
    {
        name: 'calendarPopupContainerMainCalendarFontSize',
        cssProperty: 'font-size',
        displayName: "calendar popup Container border radius in the grid",
        description: "This border radius is used for Calendar popup conatiner border radius.",
        defaultValue: '13px',
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarMainCard .calendarRow',
    },
    {
        name: 'calendarPopupContainerMainCalendarSelectedDayBackgroundColor',
        cssProperty: 'background-color',
        displayName: "calendar popup Container border radius in the grid",
        description: "This border radius is used for Calendar popup conatiner border radius.",
        defaultValue: '<main-font-color>',
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarMainCard .calendarRow.selectedDay',
    },
    {
        name: 'calendarPopupContainerMainCalendarSelectedDayFontColor',
        cssProperty: 'color',
        displayName: "calendar popup Container border radius in the grid",
        description: "This border radius is used for Calendar popup conatiner border radius.",
        defaultValue: '<light-font-color>',
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarMainCard .calendarRow.selectedDay',
    },
    {
        name: 'calendarPopupContainerMainCalendarSelectedDayBackgroundColorOnHover',
        cssProperty: 'background-color',
        displayName: "calendar popup Container border radius in the grid",
        description: "This border radius is used for Calendar popup conatiner border radius.",
        defaultValue: '#f5f5f5',
        selector: '.calendarDiv .calendarPopOver .calendarPopupDiv .calendarMainCard .calendarCol td:hover:not(.selectedDay)',
    },
];

export const styleDefaults = new Map<string, string>(
    styleProperties.filter(e => !!e.defaultValue).map(({ name, defaultValue }) => [name, defaultValue!]),
);