import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/style';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		name: 'fabButtonColor',
		cssProperty: 'background-color',
		displayName: "Fab Button's Color",
		description: 'The color of the Fab Button.',
		defaultValue: '<primary-color>',
		selector: '.fabButton',
	},
	{
		name: 'fabButtonIconColor',
		cssProperty: 'color',
		displayName: "Fab Button's Icon Color",
		description: 'The color of the Fab Button Icon.',
		defaultValue: '<white>',
		selector: '.fabButton',
	},
	{
		name: 'fabButtonMiniColor',
		cssProperty: 'background-color',
		displayName: "Mini Fab Button's Color",
		description: 'The color of the Mini Fab Button.',
		defaultValue: '<primary-color>',
		selector: '.fabButtonMini',
	},
	{
		name: 'fabButtonIconColor',
		cssProperty: 'color',
		displayName: "Mini Fab Button's Icon Color",
		description: 'The color of the Mini Fab Button Icon.',
		defaultValue: '<white>',
		selector: '.fabButtonMini',
	},
	{
		name: 'buttonColor',
		cssProperty: 'background-color',
		displayName: "Button's  Color",
		description: 'The color of the Primary Button.',
		defaultValue: '<primary-color>',
		selector: '.button',
	},
	{
		name: 'buttonTextColor',
		cssProperty: 'color',
		displayName: "Button's text Color",
		description: "The color of the Primary Button's text.",
		defaultValue: '<secondary-white>',
		selector: '.button',
	},
	{
		name: 'buttonColorDisabled',
		cssProperty: 'background-color',
		displayName: "Disabled Button's Color",
		description: 'The color of the disabled Primary Button.',
		defaultValue: '<app-disabled-color>',
		selector: '.button:disabled',
	},
	{
		name: 'buttonTextColorDisabled',
		cssProperty: 'color',
		displayName: "Disabled Button's text Color",
		description: "The color of the Primary Button's text when disabled.",
		defaultValue: '<primary-color>',
		selector: '.button:disabled',
	},
	{
		name: 'buttonOutlinedColorBorder',
		cssProperty: 'border',
		displayName: "Oultined Button's Border color",
		description: "The color of the Outline Button's border.",
		defaultValue: '1px solid <primary-color>',
		selector: '.button.outlined',
	},
	{
		name: 'buttonOutlinedTextColor',
		cssProperty: 'color',
		displayName: "Outlined Button's text Color",
		description: "The color of the Oultined Button's text.",
		defaultValue: '<primary-color>',
		selector: '.button.outlined',
	},
	{
		name: 'buttonOutlinedColorBorderDisabled',
		cssProperty: 'border-color',
		displayName: "Oultined Button's Border color when disabled",
		description: "The color of the Outline Button's border when disabled.",
		defaultValue: '<secondary-disabled-border>',
		selector: '.button.outlined:disabled',
	},
	{
		name: 'buttonOutlinedTextColorDisabled',
		cssProperty: 'color',
		displayName: "Outlined Button's text Color when disabled",
		description: "The color of the Oultined Button's text when disabled.",
		defaultValue: '<app-disabled-text>',
		selector: '.button.outlined:disabled',
	},
	{
		name: 'buttonOutlinedColorHover',
		cssProperty: 'background-color',
		displayName: "Outlined Button's Color when hover",
		description: 'The color of the Oultined Button on hover.',
		defaultValue: 'rgba(31, 60, 61, 0.109)',
		selector: '.button.outlined:hover',
	},
	{
		name: 'buttonOutlinedColorBorderHover',
		cssProperty: 'border-color',
		displayName: "Oultined Button's Border color on hover",
		description: "The color of the Outline Button's border on hover.",
		defaultValue: '<primary-color>',
		selector: '.button.outlined:hover',
	},
	{
		name: 'buttonOutlinedTextColorHover',
		cssProperty: 'color',
		displayName: "Outlined Button's text Color on hover",
		description: "The color of the Oultined Button's text on hover.",
		defaultValue: '<app-disabled-text>',
		selector: '.button.outlined:hover',
	},
	{
		name: 'buttonOutlinedColorFocus',
		cssProperty: 'background-color',
		displayName: "Outlined Button's Color on focus",
		description: 'The color of the Oultined Button on focus.',
		defaultValue: 'rgba(31, 60, 61, 0.109)',
		selector: '.button.outlined:focus',
	},
	{
		name: 'buttonOutlinedColorBorderFocus',
		cssProperty: 'border-color',
		displayName: "Oultined Button's Border color on focus",
		description: "The color of the Outline Button's border on focus.",
		defaultValue: '<primary-color>',
		selector: '.button.outlined:focus',
	},
	{
		name: 'buttonOutlinedTextColorFocus',
		cssProperty: 'color',
		displayName: "Outlined Button's text Color on focus",
		description: "The color of the Oultined Button's text on focus.",
		defaultValue: '<app-disabled-text>',
		selector: '.button.outlined:focus',
	},
	{
		name: 'textButtonTextColor',
		cssProperty: 'color',
		displayName: "Text Button's text Color",
		description: "The color of the Text Button's text.",
		defaultValue: '<primary-color>',
		selector: '.button.text',
	},
	{
		name: 'textButtonTextColorDisabled',
		cssProperty: 'color',
		displayName: "Text Button's text Color on hover",
		description: "The color of the Text Button's text on hover.",
		defaultValue: '<app-text-disabled-color>',
		selector: '.button.text:disabled',
	},
	{
		name: 'textButtonTextColorHover',
		cssProperty: 'color',
		displayName: "Text Button's text Color on hover",
		description: "The color of the Text Button's text on hover.",
		defaultValue: 'rgba(31, 60, 61, 0.078)',
		selector: '.button.text:hover',
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
