import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{ displayName: 'Button Font', name: 'buttonFont', defaultValue: '<primaryFont>' },

	{
		groupName: 'Default',
		displayName: 'Default Button Font',
		name: 'defaultButtonFont',
		defaultValue: '<buttonFont>',
		cssProperty: 'font',
		selector: '.comp.compButton._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Button Font',
		name: 'outlineButtonFont',
		defaultValue: '<textBoxFont>',
		cssProperty: 'font',
		selector: '.comp.compButton._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Text',
		displayName: 'Text Button Font',
		name: 'textButtonFont',
		defaultValue: '<textBoxFont>',
		cssProperty: 'font',
		selector: '.comp.compButton._text',
		noPrefix: true,
	},
	{
		groupName: 'Icon',
		displayName: 'Icon Button Font',
		name: 'iconButtonFont',
		defaultValue: '<textBoxFont>',
		cssProperty: 'font',
		selector: '.comp.compButton._iconButton',
		noPrefix: true,
	},
	{
		groupName: 'FAB',
		displayName: 'FAB Button Font',
		name: 'fabButtonFont',
		defaultValue: '<textBoxFont>',
		cssProperty: 'font',
		selector: '.comp.compButton._fabButton',
		noPrefix: true,
	},
	{
		groupName: 'FAB Mini',
		displayName: 'FAB Mini Button Font',
		name: 'fabminiButtonFont',
		defaultValue: '<textBoxFont>',
		cssProperty: 'font',
		selector: '.comp.compButton._fabButtonMini',
		noPrefix: true,
	},
	{
		groupName: 'Decortive',
		displayName: 'Decortive Button Font',
		name: 'decortiveButtonFont',
		defaultValue: '<textBoxFont>',
		cssProperty: 'font',
		selector: '.comp.compButton._decorative',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Button Font',
		name: 'bigdesign1ButtonFont',
		defaultValue: '<tertiaryFont>',
		cssProperty: 'font',
		selector: '.comp.compButton._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Button Height',
		name: 'defaultButtonHeight',
		defaultValue: '32px',
		cssProperty: 'height',
		selector: '.comp.compButton._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Button Height',
		name: 'outlineButtonHeight',
		defaultValue: '32px',
		cssProperty: 'height',
		selector: '.comp.compButton._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Text',
		displayName: 'Text Button Height',
		name: 'textButtonHeight',
		defaultValue: '32px',
		cssProperty: 'height',
		selector: '.comp.compButton._text',
		noPrefix: true,
	},
	{
		groupName: 'Icon',
		displayName: 'Icon Button Height',
		name: 'iconButtonHeight',
		cssProperty: 'height',
		selector: '.comp.compButton._iconButton',
		noPrefix: true,
	},
	{
		groupName: 'FAB',
		displayName: 'FAB Button Height',
		name: 'fabButtonHeight',
		defaultValue: '48px',
		cssProperty: 'height',
		selector: '.comp.compButton._fabButton',
		noPrefix: true,
	},
	{
		groupName: 'FAB Mini',
		displayName: 'FAB Mini Button Height',
		name: 'fabminiButtonHeight',
		defaultValue: '32px',
		cssProperty: 'height',
		selector: '.comp.compButton._fabButtonMini',
		noPrefix: true,
	},
	{
		groupName: 'Decortive',
		displayName: 'Decortive Button Height',
		name: 'decortiveButtonHeight',
		defaultValue: '32px',
		cssProperty: 'height',
		selector: '.comp.compButton._decorative',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Button Height',
		name: 'bigdesign1ButtonHeight',
		defaultValue: '60px',
		cssProperty: 'height',
		selector: '.comp.compButton._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Button Width',
		name: 'defaultButtonWidth',
		cssProperty: 'width',
		selector: '.comp.compButton._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Button Width',
		name: 'outlineButtonWidth',
		cssProperty: 'width',
		selector: '.comp.compButton._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Text',
		displayName: 'Text Button Width',
		name: 'textButtonWidth',
		cssProperty: 'width',
		selector: '.comp.compButton._text',
		noPrefix: true,
	},
	{
		groupName: 'Icon',
		displayName: 'Icon Button Width',
		name: 'iconButtonWidth',
		cssProperty: 'width',
		selector: '.comp.compButton._iconButton',
		noPrefix: true,
	},
	{
		groupName: 'FAB',
		displayName: 'FAB Button Width',
		name: 'fabButtonWidth',
		defaultValue: '48px',
		cssProperty: 'width',
		selector: '.comp.compButton._fabButton',
		noPrefix: true,
	},
	{
		groupName: 'FAB Mini',
		displayName: 'FAB Mini Button Width',
		name: 'fabminiButtonWidth',
		defaultValue: '32px',
		cssProperty: 'width',
		selector: '.comp.compButton._fabButtonMini',
		noPrefix: true,
	},
	{
		groupName: 'Decortive',
		displayName: 'Decortive Button Width',
		name: 'decortiveButtonWidth',
		cssProperty: 'width',
		selector: '.comp.compButton._decorative',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Button Width',
		name: 'bigdesign1ButtonWidth',
		cssProperty: 'width',
		selector: '.comp.compButton._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Button Padding',
		name: 'defaultButtonPadding',
		defaultValue: '5px 5px',
		cssProperty: 'padding',
		selector: '.comp.compButton._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Button Padding',
		name: 'outlineButtonPadding',
		defaultValue: '5px 5px',
		cssProperty: 'padding',
		selector: '.comp.compButton._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Text',
		displayName: 'Text Button Padding',
		name: 'textButtonPadding',
		defaultValue: '5px 5px',
		cssProperty: 'padding',
		selector: '.comp.compButton._text',
		noPrefix: true,
	},
	{
		groupName: 'Icon',
		displayName: 'Icon Button Padding',
		name: 'iconButtonPadding',
		cssProperty: 'padding',
		selector: '.comp.compButton._iconButton',
		noPrefix: true,
	},
	{
		groupName: 'FAB',
		displayName: 'FAB Button Padding',
		name: 'fabButtonPadding',
		defaultValue: '0px',
		cssProperty: 'padding',
		selector: '.comp.compButton._fabButton',
		noPrefix: true,
	},
	{
		groupName: 'FAB Mini',
		displayName: 'FAB Mini Button Padding',
		name: 'fabminiButtonPadding',
		defaultValue: '0px',
		cssProperty: 'padding',
		selector: '.comp.compButton._fabButtonMini',
		noPrefix: true,
	},
	{
		groupName: 'Decortive',
		displayName: 'Decortive Button Padding',
		name: 'decortiveButtonPadding',
		defaultValue: '5px 5px',
		cssProperty: 'padding',
		selector: '.comp.compButton._decorative',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Button Padding',
		name: 'bigdesign1ButtonPadding',
		defaultValue: '5px 5px',
		cssProperty: 'padding',
		selector: '.comp.compButton._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Button Border Radius',
		name: 'defaultButtonBorderRadius',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compButton._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Button Border Radius',
		name: 'outlineButtonBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-radius',
		selector: '.comp.compButton._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Text',
		displayName: 'Text Button Border Radius',
		name: 'textButtonBorderRadius',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compButton._text',
		noPrefix: true,
	},
	{
		groupName: 'Icon',
		displayName: 'Icon Button Border Radius',
		name: 'iconButtonBorderRadius',
		defaultValue: '2px',
		cssProperty: 'border-radius',
		selector: '.comp.compButton._iconButton',
		noPrefix: true,
	},
	{
		groupName: 'FAB',
		displayName: 'FAB Button Border Radius',
		name: 'fabButtonBorderRadius',
		defaultValue: '50%',
		cssProperty: 'border-radius',
		selector: '.comp.compButton._fabButton',
		noPrefix: true,
	},
	{
		groupName: 'FAB Mini',
		displayName: 'FAB Mini Button Border Radius',
		name: 'fabminiButtonBorderRadius',
		defaultValue: '50%',
		cssProperty: 'border-radius',
		selector: '.comp.compButton._fabButtonMini',
		noPrefix: true,
	},
	{
		groupName: 'Decortive',
		displayName: 'Decortive Button Border Radius',
		name: 'decortiveButtonBorderRadius',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compButton._decorative',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Button Border Radius',
		name: 'bigdesign1ButtonBorderRadius',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compButton._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Button Border',
		name: 'defaultButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButton._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Button Border',
		name: 'outlineButtonBorder',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compButton._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Text',
		displayName: 'Text Button Border',
		name: 'textButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButton._text',
		noPrefix: true,
	},
	{
		groupName: 'Icon',
		displayName: 'Icon Button Border',
		name: 'iconButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButton._iconButton',
		noPrefix: true,
	},
	{
		groupName: 'FAB',
		displayName: 'FAB Button Border',
		name: 'fabButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButton._fabButton',
		noPrefix: true,
	},
	{
		groupName: 'FAB Mini',
		displayName: 'FAB Mini Button Border',
		name: 'fabminiButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButton._fabButtonMini',
		noPrefix: true,
	},
	{
		groupName: 'Decortive',
		displayName: 'Decortive Button Border',
		name: 'decortiveButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButton._decorative',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Button Border',
		name: 'bigdesign1ButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compButton._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Button Cursor',
		name: 'defaultButtonCursor',
		defaultValue: 'pointer',
		cssProperty: 'cursor',
		selector: '.comp.compButton._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Button Cursor',
		name: 'outlineButtonCursor',
		defaultValue: 'pointer',
		cssProperty: 'cursor',
		selector: '.comp.compButton._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Text',
		displayName: 'Text Button Cursor',
		name: 'textButtonCursor',
		defaultValue: 'pointer',
		cssProperty: 'cursor',
		selector: '.comp.compButton._text',
		noPrefix: true,
	},
	{
		groupName: 'Icon',
		displayName: 'Icon Button Cursor',
		name: 'iconButtonCursor',
		defaultValue: 'pointer',
		cssProperty: 'cursor',
		selector: '.comp.compButton._iconButton',
		noPrefix: true,
	},
	{
		groupName: 'FAB',
		displayName: 'FAB Button Cursor',
		name: 'fabButtonCursor',
		defaultValue: 'pointer',
		cssProperty: 'cursor',
		selector: '.comp.compButton._fabButton',
		noPrefix: true,
	},
	{
		groupName: 'FAB Mini',
		displayName: 'FAB Mini Button Cursor',
		name: 'fabminiButtonCursor',
		defaultValue: 'pointer',
		cssProperty: 'cursor',
		selector: '.comp.compButton._fabButtonMini',
		noPrefix: true,
	},
	{
		groupName: 'Decortive',
		displayName: 'Decortive Button Cursor',
		name: 'decortiveButtonCursor',
		defaultValue: 'pointer',
		cssProperty: 'cursor',
		selector: '.comp.compButton._decorative',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Button Cursor',
		name: 'bigdesign1ButtonCursor',
		defaultValue: 'pointer',
		cssProperty: 'cursor',
		selector: '.comp.compButton._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Primary Button Background',
		name: 'primaryButtonBackground',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector:
			'.comp.compButton._default._primary, .comp.compButton._iconButton._primary:hover, .comp.compButton._fabButton._primary, .comp.compButton._fabButtonMini._primary, .comp.compButton._outlined._primary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Secondary Button Background',
		name: 'secondaryButtonBackground',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector:
			'.comp.compButton._default._secondary, .comp.compButton._iconButton._secondary:hover, .comp.compButton._fabButton._secondary, .comp.compButton._fabButtonMini._secondary, .comp.compButton._outlined._secondary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Tertiary Button Background',
		name: 'tertiaryButtonBackground',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector:
			'.comp.compButton._default._tertiary, .comp.compButton._iconButton._tertiary:hover, .comp.compButton._fabButton._tertiary, .comp.compButton._fabButtonMini._tertiary, .comp.compButton._outlined._tertiary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quaternary Button Background',
		name: 'quaternaryButtonBackground',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector:
			'.comp.compButton._default._quaternary, .comp.compButton._iconButton._quaternary:hover, .comp.compButton._fabButton._quaternary, .comp.compButton._fabButtonMini._quaternary, .comp.compButton._outlined._quaternary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quinary Button Background',
		name: 'quinaryButtonBackground',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector:
			'.comp.compButton._default._quinary, .comp.compButton._iconButton._quinary:hover, .comp.compButton._fabButton._quinary, .comp.compButton._fabButtonMini._quinary, .comp.compButton._outlined._quinary:hover',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Primary Button Hover Background',
		name: 'primaryButtonHoverBackground',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'background',
		selector:
			'.comp.compButton._default._primary:hover, .comp.compButton._fabButton._primary:hover, .comp.compButton._fabButtonMini._primary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Secondary Button Hover Background',
		name: 'secondaryButtonHoverBackground',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'background',
		selector:
			'.comp.compButton._default._secondary:hover, .comp.compButton._fabButton._secondary:hover, .comp.compButton._fabButtonMini._secondary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Tertiary Button Hover Background',
		name: 'tertiaryButtonHoverBackground',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'background',
		selector:
			'.comp.compButton._default._tertiary:hover, .comp.compButton._fabButton._tertiary:hover, .comp.compButton._fabButtonMini._tertiary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quaternary Button Hover Background',
		name: 'quaternaryButtonHoverBackground',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'background',
		selector:
			'.comp.compButton._default._quaternary:hover, .comp.compButton._fabButton._quaternary:hover, .comp.compButton._fabButtonMini._quaternary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quinary Button Hover Background',
		name: 'quinaryButtonHoverBackground',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'background',
		selector:
			'.comp.compButton._default._quinary:hover, .comp.compButton._fabButton._quinary:hover, .comp.compButton._fabButtonMini._quinary:hover',
		noPrefix: true,
	},

	{
		groupName: 'Color',
		displayName: 'Primary Button Text Color',
		name: 'primaryButtonTextColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._default._primary, .comp.compButton._iconButton._primary, .comp.compButton._fabButton._primary, .comp.compButton._fabButtonMini._primary, .comp.compButton._decorative._primary, .comp.compButton._bigDesign1._primary',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Secondary Button Text Color',
		name: 'secondaryButtonTextColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._default._secondary, .comp.compButton._iconButton._secondary, .comp.compButton._fabButton._secondary, .comp.compButton._fabButtonMini._secondary, .comp.compButton._decorative._secondary, .comp.compButton._bigDesign1._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Tertiary Button Text Color',
		name: 'tertiaryButtonTextColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._default._tertiary, .comp.compButton._iconButton._tertiary, .comp.compButton._fabButton._tertiary, .comp.compButton._fabButtonMini._tertiary, .comp.compButton._decorative._tertiary, .comp.compButton._bigDesign1._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quaternary Button Text Color',
		name: 'quaternaryButtonTextColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._default._quaternary, .comp.compButton._iconButton._quaternary, .comp.compButton._fabButton._quaternary, .comp.compButton._fabButtonMini._quaternary, .comp.compButton._decorative._quaternary, .comp.compButton._bigDesign1._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quinary Button Text Color',
		name: 'quinaryButtonTextColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._default._quinary, .comp.compButton._iconButton._quinary, .comp.compButton._fabButton._quinary, .comp.compButton._fabButtonMini._quinary, .comp.compButton._decorative._quinary, .comp.compButton._bigDesign1._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Color',
		displayName: 'Primary Button Hover Text Color',
		name: 'primaryButtonHoverTextColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._default._primary:hover, .comp.compButton._iconButton._primary:hover, .comp.compButton._fabButton._primary:hover, .comp.compButton._fabButtonMini._primary:hover, .comp.compButton._decorative._primary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Secondary Button Hover Text Color',
		name: 'secondaryButtonHoverTextColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._default._secondary:hover, .comp.compButton._iconButton._secondary:hover, .comp.compButton._fabButton._secondary:hover, .comp.compButton._fabButtonMini._secondary:hover, .comp.compButton._decorative._secondary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Tertiary Button Hover Text Color',
		name: 'tertiaryButtonHoverTextColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._default._tertiary:hover, .comp.compButton._iconButton._tertiary:hover, .comp.compButton._fabButton._tertiary:hover, .comp.compButton._fabButtonMini._tertiary:hover, .comp.compButton._decorative._tertiary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quaternary Button Hover Text Color',
		name: 'quaternaryButtonHoverTextColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._default._quaternary:hover, .comp.compButton._iconButton._quaternary:hover, .comp.compButton._fabButton._quaternary:hover, .comp.compButton._fabButtonMini._quaternary:hover, .comp.compButton._decorative._quaternary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quinary Button Hover Text Color',
		name: 'quinaryButtonHoverTextColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._default._quinary:hover, .comp.compButton._iconButton._quinary:hover, .comp.compButton._fabButton._quinary:hover, .comp.compButton._fabButtonMini._quinary:hover, .comp.compButton._decorative._quinary:hover',
		noPrefix: true,
	},

	{
		groupName: 'Border Color',
		displayName: 'Primary Button Border Color',
		name: 'primaryButtonBorderColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'border-color',
		selector:
			'.comp.compButton._default._primary, .comp.compButton._iconButton._primary, .comp.compButton._fabButton._primary, .comp.compButton._fabButtonMini._primary, .comp.compButton._outlined._primary',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Secondary Button Border Color',
		name: 'secondaryButtonBorderColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'border-color',
		selector:
			'.comp.compButton._default._secondary, .comp.compButton._iconButton._secondary, .comp.compButton._fabButton._secondary, .comp.compButton._fabButtonMini._secondary, .comp.compButton._outlined._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Tertiary Button Border Color',
		name: 'tertiaryButtonBorderColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'border-color',
		selector:
			'.comp.compButton._default._tertiary, .comp.compButton._iconButton._tertiary, .comp.compButton._fabButton._tertiary, .comp.compButton._fabButtonMini._tertiary, .comp.compButton._outlined._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Quaternary Button Border Color',
		name: 'quaternaryButtonBorderColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'border-color',
		selector:
			'.comp.compButton._default._quaternary, .comp.compButton._iconButton._quaternary, .comp.compButton._fabButton._quaternary, .comp.compButton._fabButtonMini._quaternary, .comp.compButton._outlined._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Quinary Button Border Color',
		name: 'quinaryButtonBorderColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'border-color',
		selector:
			'.comp.compButton._default._quinary, .comp.compButton._iconButton._quinary, .comp.compButton._fabButton._quinary, .comp.compButton._fabButtonMini._quinary, .comp.compButton._outlined._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Border Color',
		displayName: 'Primary Button Hover Border Color',
		name: 'primaryButtonHoverBorderColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'border-color',
		selector:
			'.comp.compButton._default._primary:hover, .comp.compButton._iconButton._primary:hover, .comp.compButton._fabButton._primary:hover, .comp.compButton._fabButtonMini._primary:hover, .comp.compButton._outlined._primary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Secondary Button Hover Border Color',
		name: 'secondaryButtonHoverBorderColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'border-color',
		selector:
			'.comp.compButton._default._secondary:hover, .comp.compButton._iconButton._secondary:hover, .comp.compButton._fabButton._secondary:hover, .comp.compButton._fabButtonMini._secondary:hover, .comp.compButton._outlined._secondary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Tertiary Button Hover Border Color',
		name: 'tertiaryButtonHoverBorderColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'border-color',
		selector:
			'.comp.compButton._default._tertiary:hover, .comp.compButton._iconButton._tertiary:hover, .comp.compButton._fabButton._tertiary:hover, .comp.compButton._fabButtonMini._tertiary:hover, .comp.compButton._outlined._tertiary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Quaternary Button Hover Border Color',
		name: 'quaternaryButtonHoverBorderColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'border-color',
		selector:
			'.comp.compButton._default._quaternary:hover, .comp.compButton._iconButton._quaternary:hover, .comp.compButton._fabButton._quaternary:hover, .comp.compButton._fabButtonMini._quaternary:hover, .comp.compButton._outlined._quaternary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Quinary Button Hover Border Color',
		name: 'quinaryButtonHoverBorderColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'border-color',
		selector:
			'.comp.compButton._default._quinary:hover, .comp.compButton._iconButton._quinary:hover, .comp.compButton._fabButton._quinary:hover, .comp.compButton._fabButtonMini._quinary:hover, .comp.compButton._outlined._quinary:hover',
		noPrefix: true,
	},

	{
		groupName: 'Color',
		displayName: 'Primary Outlined Button Text Color',
		name: 'primaryOutlinedButtonTextColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector: '.comp.compButton._outlined._primary, .comp.compButton._iconButton._primary',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Secondary Outlined Button Text Color',
		name: 'secondaryOutlinedButtonTextColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector: '.comp.compButton._outlined._secondary, .comp.compButton._iconButton._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Tertiary Outlined Button Text Color',
		name: 'tertiaryOutlinedButtonTextColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector: '.comp.compButton._outlined._tertiary, .comp.compButton._iconButton._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quaternary Outlined Button Text Color',
		name: 'quaternaryOutlinedButtonTextColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._outlined._quaternary, .comp.compButton._iconButton._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quinary Outlined Button Text Color',
		name: 'quinaryOutlinedButtonTextColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector: '.comp.compButton._outlined._quinary, .comp.compButton._iconButton._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Color',
		displayName: 'Primary Outlined Button Hover Text Color',
		name: 'primaryOutlinedButtonHoverTextColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._outlined._primary:hover, .comp.compButton._iconButton._primary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Secondary Outlined Button Hover Text Color',
		name: 'secondaryOutlinedButtonHoverTextColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._outlined._secondary:hover, .comp.compButton._iconButton._secondary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Tertiary Outlined Button Hover Text Color',
		name: 'tertiaryOutlinedButtonHoverTextColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._outlined._tertiary:hover, .comp.compButton._iconButton._tertiary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quaternary Outlined Button Hover Text Color',
		name: 'quaternaryOutlinedButtonHoverTextColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._outlined._quaternary:hover, .comp.compButton._iconButton._quaternary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quinary Outlined Button Hover Text Color',
		name: 'quinaryOutlinedButtonHoverTextColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._outlined._quinary:hover, .comp.compButton._iconButton._quinary:hover',
		noPrefix: true,
	},

	{
		groupName: 'Color',
		displayName: 'Primary Text Button Text Color',
		name: 'primaryTextButtonTextColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector: '.comp.compButton._text._primary',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Secondary Text Button Text Color',
		name: 'secondaryTextButtonTextColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector: '.comp.compButton._text._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Tertiary Text Button Text Color',
		name: 'tertiaryTextButtonTextColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector: '.comp.compButton._text._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quaternary Text Button Text Color',
		name: 'quaternaryTextButtonTextColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector: '.comp.compButton._text._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quinary Text Button Text Color',
		name: 'quinaryTextButtonTextColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector: '.comp.compButton._text._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Color',
		displayName: 'Primary Text Hover Button Text Color',
		name: 'primaryTextHoverButtonTextColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compButton._text._primary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Secondary Text Hover Button Text Color',
		name: 'secondaryTextHoverButtonTextColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compButton._text._secondary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Tertiary Text Hover Button Text Color',
		name: 'tertiaryTextHoverButtonTextColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compButton._text._tertiary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quaternary Text Hover Button Text Color',
		name: 'quaternaryTextHoverButtonTextColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compButton._text._quaternary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quinary Text Hover Button Text Color',
		name: 'quinaryTextHoverButtonTextColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compButton._text._quinary:hover',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Button Disabled Background',
		name: 'buttonDisabledBackground',
		defaultValue: '<backgroundColorNine>',
		cssProperty: 'background',
		selector:
			'.comp.compButton._default._primary:disabled,.comp.compButton._iconButton._primary:disabled,.comp.compButton._fabButton._primary:disabled,.comp.compButton._fabButtonMini._primary:disabled,.comp.compButton._outlined._primary:disabled,.comp.compButton._bigDesign1._primary:disabled,.comp.compButton._bigDesign1._primary:disabled:hover,.comp.compButton._default._secondary:disabled,.comp.compButton._iconButton._secondary:disabled,.comp.compButton._fabButton._secondary:disabled,.comp.compButton._fabButtonMini._secondary:disabled,.comp.compButton._outlined._secondary:disabled,.comp.compButton._bigDesign1._secondary:disabled,.comp.compButton._bigDesign1._secondary:disabled:hover,.comp.compButton._default._tertiary:disabled,.comp.compButton._iconButton._tertiary:disabled,.comp.compButton._fabButton._tertiary:disabled,.comp.compButton._fabButtonMini._tertiary:disabled,.comp.compButton._outlined._tertiary:disabled,.comp.compButton._bigDesign1._tertiary:disabled,.comp.compButton._bigDesign1._tertiary:disabled:hover,.comp.compButton._default._quaternary:disabled,.comp.compButton._iconButton._quaternary:disabled,.comp.compButton._fabButton._quaternary:disabled,.comp.compButton._fabButtonMini._quaternary:disabled,.comp.compButton._outlined._quaternary:disabled,.comp.compButton._bigDesign1._quaternary:disabled,.comp.compButton._bigDesign1._quaternary:disabled:hover,.comp.compButton._default._quinary:disabled,.comp.compButton._iconButton._quinary:disabled,.comp.compButton._fabButton._quinary:disabled,.comp.compButton._fabButtonMini._quinary:disabled,.comp.compButton._outlined._quinary:disabled,.comp.compButton._bigDesign1._quinary:disabled,.comp.compButton._bigDesign1._quinary:disabled:hover',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Button Dsiabled Font Color',
		name: 'buttonDsiabledFontColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector:
			'.comp.compButton._default._primary:disabled,.comp.compButton._iconButton._primary:disabled,.comp.compButton._fabButton._primary:disabled,.comp.compButton._fabButtonMini._primary:disabled,.comp.compButton._outlined._primary:disabled,.comp.compButton._text._primary:disabled,.comp.compButton._bigDesign1._primary:disabled,.comp.compButton._default._secondary:disabled,.comp.compButton._iconButton._secondary:disabled,.comp.compButton._fabButton._secondary:disabled,.comp.compButton._fabButtonMini._secondary:disabled,.comp.compButton._outlined._secondary:disabled,.comp.compButton._text._secondary:disabled,.comp.compButton._bigDesign1._secondary:disabled,.comp.compButton._default._tertiary:disabled,.comp.compButton._iconButton._tertiary:disabled,.comp.compButton._fabButton._tertiary:disabled,.comp.compButton._fabButtonMini._tertiary:disabled,.comp.compButton._outlined._tertiary:disabled,.comp.compButton._text._tertiary:disabled,.comp.compButton._bigDesign1._tertiary:disabled,.comp.compButton._default._quaternary:disabled,.comp.compButton._iconButton._quaternary:disabled,.comp.compButton._fabButton._quaternary:disabled,.comp.compButton._fabButtonMini._quaternary:disabled,.comp.compButton._outlined._quaternary:disabled,.comp.compButton._text._quaternary:disabled,.comp.compButton._bigDesign1._quaternary:disabled,.comp.compButton._default._quinary:disabled,.comp.compButton._iconButton._quinary:disabled,.comp.compButton._fabButton._quinary:disabled,.comp.compButton._fabButtonMini._quinary:disabled,.comp.compButton._outlined._quinary:disabled,.comp.compButton._text._quinary:disabled,.comp.compButton._bigDesign1._quinary:disabled',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Button Disabled Border Color',
		name: 'buttonDisabledBorderColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector:
			'.comp.compButton._default._primary:disabled,.comp.compButton._iconButton._primary:disabled,.comp.compButton._fabButton._primary:disabled,.comp.compButton._fabButtonMini._primary:disabled,.comp.compButton._outlined._primary:disabled,.comp.compButton._bigDesign1._primary:disabled,.comp.compButton._default._secondary:disabled,.comp.compButton._iconButton._secondary:disabled,.comp.compButton._fabButton._secondary:disabled,.comp.compButton._fabButtonMini._secondary:disabled,.comp.compButton._outlined._secondary:disabled,.comp.compButton._bigDesign1._secondary:disabled,.comp.compButton._default._tertiary:disabled,.comp.compButton._iconButton._tertiary:disabled,.comp.compButton._fabButton._tertiary:disabled,.comp.compButton._fabButtonMini._tertiary:disabled,.comp.compButton._outlined._tertiary:disabled,.comp.compButton._bigDesign1._tertiary:disabled,.comp.compButton._default._quaternary:disabled,.comp.compButton._iconButton._quaternary:disabled,.comp.compButton._fabButton._quaternary:disabled,.comp.compButton._fabButtonMini._quaternary:disabled,.comp.compButton._outlined._quaternary:disabled,.comp.compButton._bigDesign1._quaternary:disabled,.comp.compButton._default._quinary:disabled,.comp.compButton._iconButton._quinary:disabled,.comp.compButton._fabButton._quinary:disabled,.comp.compButton._fabButtonMini._quinary:disabled,.comp.compButton._outlined._quinary:disabled,.comp.compButton._bigDesign1._quinary:disabled',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Primary Outline Text Icon Button Background',
		name: 'primaryOutlineTextIconButtonBackground',
		defaultValue: 'transparent',
		cssProperty: 'background',
		selector:
			'.comp.compButton._outlined._primary, .comp.compButton._iconButton._primary, .comp.compButton._text._primary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Secondary Outline Text Icon Button Background',
		name: 'secondaryOutlineTextIconButtonBackground',
		defaultValue: 'transparent',
		cssProperty: 'background',
		selector:
			'.comp.compButton._outlined._secondary, .comp.compButton._iconButton._secondary, .comp.compButton._text._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Tertiary Outline Text Icon Button Background',
		name: 'tertiaryOutlineTextIconButtonBackground',
		defaultValue: 'transparent',
		cssProperty: 'background',
		selector:
			'.comp.compButton._outlined._tertiary, .comp.compButton._iconButton._tertiary, .comp.compButton._text._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quaternary Outline Text Icon Button Background',
		name: 'quaternaryOutlineTextIconButtonBackground',
		defaultValue: 'transparent',
		cssProperty: 'background',
		selector:
			'.comp.compButton._outlined._quaternary, .comp.compButton._iconButton._quaternary, .comp.compButton._text._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quinary Outline Text Icon Button Background',
		name: 'quinaryOutlineTextIconButtonBackground',
		defaultValue: 'transparent',
		cssProperty: 'background',
		selector:
			'.comp.compButton._outlined._quinary, .comp.compButton._iconButton._quinary, .comp.compButton._text._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Primary Decorative Button Hover Background',
		name: 'primaryDecorativeButtonHoverBackground',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._primary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Secondary Decorative Button Hover Background',
		name: 'secondaryDecorativeButtonHoverBackground',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._secondary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Tertiary Decorative Button Hover Background',
		name: 'tertiaryDecorativeButtonHoverBackground',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._tertiary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quaternary Decorative Button Hover Background',
		name: 'quaternaryDecorativeButtonHoverBackground',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._quaternary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quinary Decorative Button Hover Background',
		name: 'quinaryDecorativeButtonHoverBackground',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._quinary:hover',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Primary Decorative Button Background',
		name: 'primaryDecorativeButtonBackground',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._primary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Secondary Decorative Button Background',
		name: 'secondaryDecorativeButtonBackground',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Tertiary Decorative Button Background',
		name: 'tertiaryDecorativeButtonBackground',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quaternary Decorative Button Background',
		name: 'quaternaryDecorativeButtonBackground',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quinary Decorative Button Background',
		name: 'quinaryDecorativeButtonBackground',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Margin',
		displayName: 'Left Icon Button Margin',
		name: 'leftIconButtonMargin',
		defaultValue: '0px 5px 0px 0px',
		cssProperty: 'margin',
		selector:
			'.comp.compButton._default ._leftButtonIcon, .comp.compButton._outlined ._leftButtonIcon, .comp.compButton._text ._leftButtonIcon',
		noPrefix: true,
	},
	{
		groupName: 'Margin',
		displayName: 'Right Icon Button Margin',
		name: 'rightIconButtonMargin',
		defaultValue: '0px 0px 0px 5px',
		cssProperty: 'margin',
		selector:
			'.comp.compButton._default ._rightButtonIcon, .comp.compButton._outlined ._rightButtonIcon, .comp.compButton._text ._rightButtonIcon',
		noPrefix: true,
	},
	{
		groupName: 'Padding',
		displayName: 'Left Icon Button Padding',
		name: 'leftIconButtonPadding',
		defaultValue: '0px',
		cssProperty: 'padding',
		selector: '.comp.compButton ._leftButtonIcon',
		noPrefix: true,
	},
	{
		groupName: 'Padding',
		displayName: 'Right Icon Button Padding',
		name: 'rightIconButtonPadding',
		defaultValue: '0px',
		cssProperty: 'padding',
		selector: '.comp.compButton ._rightButtonIcon',
		noPrefix: true,
	},
	{
		groupName: 'Padding',
		displayName: 'Decorative Button Padding With Left Icon',
		name: 'decorativeButtonPaddingWithLeftIcon',
		defaultValue: '37px',
		cssProperty: 'padding-left',
		selector: '.comp.compButton._decorative._withLeftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Padding',
		displayName: 'Decorative Button Padding With Right Icon',
		name: 'decorativeButtonPaddingWithRightIcon',
		defaultValue: '37px',
		cssProperty: 'padding-right',
		selector: '.comp.compButton._decorative._withRightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Border',
		displayName: 'Decorative Button Left Icon Border Radius',
		name: 'decorativeButtonLeftIconBorderRadius',
		defaultValue: '4px 0px 0px 4px',
		cssProperty: 'border-radius',
		selector: '.comp.compButton._decorative ._leftButtonIcon',
		noPrefix: true,
	},
	{
		groupName: 'Border',
		displayName: 'Decorative Button Right Icon Border Radius',
		name: 'decorativeButtonRightIconBorderRadius',
		defaultValue: '0px 4px 4px 0px',
		cssProperty: 'border-radius',
		selector: '.comp.compButton._decorative ._rightButtonIcon',
		noPrefix: true,
	},

	{
		groupName: 'Icon Width',
		displayName: 'Decorative Button Left Icon',
		name: 'decorativeButtonLeftIcon',
		defaultValue: '32px',
		cssProperty: 'width',
		selector: '.comp.compButton._decorative ._leftButtonIcon',
		noPrefix: true,
	},
	{
		groupName: 'Icon Width',
		displayName: 'Decorative Button Right Icon',
		name: 'decorativeButtonRightIcon',
		defaultValue: '32px',
		cssProperty: 'width',
		selector: '.comp.compButton._decorative ._rightButtonIcon',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Primary Decorative Button Icon Background',
		name: 'primaryDecorativeButtonIconBackground',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._primary:hover ._icon',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Secondary Decorative Button Icon Background',
		name: 'secondaryDecorativeButtonIconBackground',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._secondary:hover ._icon',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Tertiary Decorative Button Icon Background',
		name: 'tertiaryDecorativeButtonIconBackground',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._tertiary:hover ._icon',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quaternary Decorative Button Icon Background',
		name: 'quaternaryDecorativeButtonIconBackground',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._quaternary:hover ._icon',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quinary Decorative Button Icon Background',
		name: 'quinaryDecorativeButtonIconBackground',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._quinary:hover ._icon',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Primary Decorative Button Icon Hover Background',
		name: 'primaryDecorativeButtonIconHoverBackground',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._primary ._icon',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Secondary Decorative Button Icon Hover Background',
		name: 'secondaryDecorativeButtonIconHoverBackground',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._secondary ._icon',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Tertiary Decorative Button Icon Hover Background',
		name: 'tertiaryDecorativeButtonIconHoverBackground',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._tertiary ._icon',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quaternary Decorative Button Icon Hover Background',
		name: 'quaternaryDecorativeButtonIconHoverBackground',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._quaternary ._icon',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quinary Decorative Button Icon Hover Background',
		name: 'quinaryDecorativeButtonIconHoverBackground',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compButton._decorative._quinary ._icon',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Primary Big Design1 Button Hover Background',
		name: 'primaryBigDesign1ButtonHoverBackground',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compButton._bigDesign1._primary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Secondary Big Design1 Button Hover Background',
		name: 'secondaryBigDesign1ButtonHoverBackground',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compButton._bigDesign1._secondary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Tertiary Big Design1 Button Hover Background',
		name: 'tertiaryBigDesign1ButtonHoverBackground',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compButton._bigDesign1._tertiary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quaternary Big Design1 Button Hover Background',
		name: 'quaternaryBigDesign1ButtonHoverBackground',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compButton._bigDesign1._quaternary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quinary Big Design1 Button Hover Background',
		name: 'quinaryBigDesign1ButtonHoverBackground',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compButton._bigDesign1._quinary:hover',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Primary Big Design1 Button Background',
		name: 'primaryBigDesign1ButtonBackground',
		defaultValue:
			'linear-gradient(90deg, <backgroundDarkerColorOne> 0%, <backgroundColorOne> 100%)',
		cssProperty: 'background',
		selector: '.comp.compButton._bigDesign1._primary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Secondary Big Design1 Button Background',
		name: 'secondaryBigDesign1ButtonBackground',
		defaultValue:
			'linear-gradient(90deg, <backgroundDarkerColorTwo> 0%, <backgroundColorTwo> 100%)',
		cssProperty: 'background',
		selector: '.comp.compButton._bigDesign1._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Tertiary Big Design1 Button Background',
		name: 'tertiaryBigDesign1ButtonBackground',
		defaultValue:
			'linear-gradient(90deg, <backgroundDarkerColorThree> 0%, <backgroundColorThree> 100%)',
		cssProperty: 'background',
		selector: '.comp.compButton._bigDesign1._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quaternary Big Design1 Button Background',
		name: 'quaternaryBigDesign1ButtonBackground',
		defaultValue:
			'linear-gradient(90deg, <backgroundDarkerColorFour> 0%, <backgroundColorFour> 100%)',
		cssProperty: 'background',
		selector: '.comp.compButton._bigDesign1._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quinary Big Design1 Button Background',
		name: 'quinaryBigDesign1ButtonBackground',
		defaultValue:
			'linear-gradient(90deg, <backgroundDarkerColorFive> 0%, <backgroundColorFive> 100%)',
		cssProperty: 'background',
		selector: '.comp.compButton._bigDesign1._quinary',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
