import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		name: 'fabButtonColor',
		cssProperty: 'background-color',
		displayName: "Fab Button's Color",
		description: 'The color of the Fab Button.',
		defaultValue: '<mainFontColor>',
		noPrefix: true,
		selector: '.compButton.button.fabButton',
	},
	{
		name: 'fabButtonIconColor',
		cssProperty: 'color',
		displayName: "Fab Button's Icon Color",
		description: 'The color of the Fab Button Icon.',
		defaultValue: '<lightFontColor>',
		noPrefix: true,
		selector: '.compButton.fabButton',
	},
	{
		name: 'fabButtonWidth',
		cssProperty: 'width',
		displayName: "Fab Button's Width",
		description: 'The width of the Fab Button.',
		defaultValue: '56px',
		noPrefix: true,
		selector: '.compButton.fabButton',
	},
	{
		name: 'fabButtonMiniColor',
		cssProperty: 'background-color',
		displayName: "Mini Fab Button's Color",
		description: 'The color of the Mini Fab Button.',
		defaultValue: '<mainFontColor>',
		noPrefix: true,
		selector: '.compButton.fabButtonMini',
	},
	{
		name: 'fabButtonMiniIconColor',
		cssProperty: 'color',
		displayName: "Mini Fab Button's Icon Color",
		description: 'The color of the Mini Fab Button Icon.',
		defaultValue: '<lightFontColor>',
		noPrefix: true,
		selector: '.compButton.fabButtonMini',
	},
	{
		name: 'fabButtonMiniWidth',
		cssProperty: 'width',
		displayName: "Fab Button Mini's Width",
		description: 'The width of the Fab mini Button.',
		defaultValue: '40px',
		noPrefix: true,
		selector: '.compButton.fabButtonMini',
	},
	{
		name: 'buttonColor',
		cssProperty: 'background-color',
		displayName: "Button's  Color",
		description: 'The color of the Primary Button.',
		defaultValue: '<mainFontColor>',
		noPrefix: true,
		selector: '.compButton',
	},
	{
		name: 'buttonFontFamily',
		cssProperty: 'font-family',
		displayName: "Button's Font Family",
		description: 'The font of the Primary Button.',
		defaultValue: '<mainFontFamily>',
		noPrefix: true,
		selector: '.compButton',
	},
	{
		name: 'buttonColorHover',
		cssProperty: 'background-color',
		displayName: "Button's background color on hover",
		description: 'The color of the Button on hover.',
		defaultValue: '#647879',
		noPrefix: true,
		selector: '.compButton:hover',
	},
	{
		name: 'buttonTextColor',
		cssProperty: 'color',
		displayName: "Button's text Color",
		description: "The color of the Primary Button's text.",
		defaultValue: '<lightFontColor>',
		noPrefix: true,
		selector: '.compButton',
	},
	{
		name: 'buttonColorDisabled',
		cssProperty: 'background-color',
		displayName: "Disabled Button's Color",
		description: 'The color of the disabled Primary Button.',
		defaultValue: '<mainDisabledColor>',
		noPrefix: true,
		selector: '.compButton:disabled',
	},
	{
		name: 'buttonTextColorDisabled',
		cssProperty: 'color',
		displayName: "Disabled Button's text Color",
		description: "The color of the Primary Button's text when disabled.",
		defaultValue: '<mainFontColor>',
		noPrefix: true,
		selector: '.compButton:disabled',
	},
	{
		name: 'buttonOutlinedColorBorder',
		cssProperty: 'border',
		displayName: "Oultined Button's Border color",
		description: "The color of the Outline Button's border.",
		defaultValue: '1px solid <mainFontColor>',
		noPrefix: true,
		selector: '.compButton.outlined',
	},
	{
		name: 'buttonOutlinedTextColor',
		cssProperty: 'color',
		displayName: "Outlined Button's text Color",
		description: "The color of the Oultined Button's text.",
		defaultValue: '<mainFontColor>',
		noPrefix: true,
		selector: '.compButton.outlined',
	},
	{
		name: 'buttonOutlinedColorBorderDisabled',
		cssProperty: 'border-color',
		displayName: "Oultined Button's Border color when disabled",
		description: "The color of the Outline Button's border when disabled.",
		defaultValue: '<secondaryDisabledBorder>',
		noPrefix: true,
		selector: '.compButton.outlined:disabled',
	},
	{
		name: 'buttonOutlinedTextColorDisabled',
		cssProperty: 'color',
		displayName: "Outlined Button's text Color when disabled",
		description: "The color of the Oultined Button's text when disabled.",
		defaultValue: '<mainDisabledText>',
		noPrefix: true,
		selector: '.compButton.outlined:disabled',
	},
	{
		name: 'buttonOutlinedColorHover',
		cssProperty: 'background-color',
		displayName: "Outlined Button's Color when hover",
		description: 'The color of the Oultined Button on hover.',
		defaultValue: 'rgba(31, 60, 61, 0.109)',
		noPrefix: true,
		selector: '.compButton.outlined:hover',
	},
	{
		name: 'buttonOutlinedColorBorderHover',
		cssProperty: 'border-color',
		displayName: "Oultined Button's Border color on hover",
		description: "The color of the Outline Button's border on hover.",
		defaultValue: '<mainFontColor>',
		noPrefix: true,
		selector: '.compButton.outlined:hover',
	},
	{
		name: 'buttonOutlinedTextColorHover',
		cssProperty: 'color',
		displayName: "Outlined Button's text Color on hover",
		description: "The color of the Oultined Button's text on hover.",
		defaultValue: '<mainDisabledText>',
		noPrefix: true,
		selector: '.compButton.outlined:hover',
	},
	{
		name: 'buttonOutlinedColorFocus',
		cssProperty: 'background-color',
		displayName: "Outlined Button's Color on focus",
		description: 'The color of the Oultined Button on focus.',
		defaultValue: 'rgba(31, 60, 61, 0.109)',
		noPrefix: true,
		selector: '.compButton.outlined:focus',
	},
	{
		name: 'buttonOutlinedColorBorderFocus',
		cssProperty: 'border-color',
		displayName: "Oultined Button's Border color on focus",
		description: "The color of the Outline Button's border on focus.",
		defaultValue: '<mainFontColor>',
		noPrefix: true,
		selector: '.compButton.outlined:focus',
	},
	{
		name: 'buttonOutlinedTextColorFocus',
		cssProperty: 'color',
		displayName: "Outlined Button's text Color on focus",
		description: "The color of the Oultined Button's text on focus.",
		defaultValue: '<mainDisabledText>',
		noPrefix: true,
		selector: '.compButton.outlined:focus',
	},
	{
		name: 'textButtonTextColor',
		cssProperty: 'color',
		displayName: "Text Button's text Color",
		description: "The color of the Text Button's text.",
		defaultValue: '<mainFontColor>',
		noPrefix: true,
		selector: '.compButton.text',
	},
	{
		name: 'textButtonTextColorDisabled',
		cssProperty: 'color',
		displayName: "Text Button's text Color on disabled",
		description: "The color of the Text Button's text on disabed.",
		defaultValue: '<secondaryDisabledBorder>',
		noPrefix: true,
		selector: '.compButton.text:disabled',
	},
	{
		name: 'textButtonTextBackgroundColorHover',
		cssProperty: 'background-color',
		displayName: "Text Button's background color on hover",
		description: "The color of the Text Button's text on hover.",
		defaultValue: '#EDEFEF',
		noPrefix: true,
		selector: '.compButton.text:hover',
	},
	{
		name: 'buttonIconMargin',
		displayName: "Icon's margin",
		description: 'Margin for left and right icons',
		defaultValue: '8px',
	},
	{
		name: 'buttonPadding',
		displayName: 'Button Padding',
		description: 'Padding for button',
		defaultValue: '0 32px',
	},
	{
		name: 'buttonHeight',
		displayName: 'Button Height',
		description: 'Height of a button',
		defaultValue: '41px',
	},
	{
		name: 'buttonBorderRadius',
		displayName: 'Button Height',
		description: 'Height of the button',
		defaultValue: '5px',
	},
	{
		name: 'buttonBorder',
		displayName: 'Button Border',
		description: 'Border of the button',
		defaultValue: 'none',
	},
	{
		name: 'buttonCursor',
		cssProperty: 'cursor',
		displayName: "Button's cursor",
		description: 'Cursor to be used on hover',
		defaultValue: 'pointer',
		noPrefix: true,
		selector: '.compButton',
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
