import { StyleGroupDefinition, StylePropertyDefinition } from '../types/style';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		name: 'main-font-family',
		cssProperty: 'font-family',
		selector: 'body',
		displayName: 'Application/Site Font Family',
		description: 'This font is used throughout application.',
		defaultValue: "'Open Sans', 'Microsoft Sans Serif', sans-serif",
		noPrefix: true,
	},
	{
		name: 'main-font-weight',
		displayName: 'Application/Site Font Weight',
		description: 'This font is used throughout application.',
		selector: 'body',
		noPrefix: true,
	},
	{
		name: 'main-font-color',
		cssProperty: 'color',
		selector: 'body',
		displayName: 'Application/Site Color',
		description: 'This color is used throughout application.',
		defaultValue: '#1f3c3d',
		noPrefix: true,
	},
	{
		name: 'main-disabled-color',
		displayName: 'Application/Site Disabled font color',
		description: 'This color is used throughout application.',
		defaultValue: '#d5d5d5',
		noPrefix: true,
	},
	{
		name: 'main-error-color',
		displayName: 'Application/Site Error color',
		description: 'This color is used throughout application.',
		defaultValue: '#ed6a5e',
		noPrefix: true,
	},
	{
		name: 'primary-color',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '#1f3c3d',
		noPrefix: true,
	},
	{
		name: 'white',
		displayName: 'Application/Site white color',
		description: 'This color is used throughout application.',
		defaultValue: '#ffffff',
		noPrefix: true,
	},
	{
		name: 'black',
		displayName: 'Application/Site black color',
		description: 'This color is used throughout application.',
		defaultValue: '#000000',
		noPrefix: true,
	},
	{
		name: 'app-yellow',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '#e5b122',
		noPrefix: true,
	},
	{
		name: 'secondary-white',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '#f9f9fb',
		noPrefix: true,
	},
	{
		name: 'app-disabled-color',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '#e0e1e3',
		noPrefix: true,
	},
	{
		name: 'app-disabled-text',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '#6e6e6e',
		noPrefix: true,
	},
	{
		name: 'secondary-disabled-border',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '#bcbcbc',
		noPrefix: true,
	},
	{
		name: 'app-text-disabled-color',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '#888585',
		noPrefix: true,
	},
	{
		name: 'app-grey-color',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '#dddddd',
		noPrefix: true,
	},
	{
		name: 'app-secondary-grey-color',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '#e3e3e3',
		noPrefix: true,
	},
	{
		name: 'app-black-rgb-color',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '0, 0, 0',
		noPrefix: true,
	},
	{
		name: 'app-yellow-rgb-color',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '229, 177, 34',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
