import { StylePropertyDefinition } from '../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		name: 'mainFontFamily',
		cssProperty: 'font-family',
		selector: 'body',
		displayName: 'Application/Site Font Family',
		description: 'This font is used throughout application.',
		defaultValue: "'Open Sans', 'Microsoft Sans Serif', sans-serif",
		noPrefix: true,
	},
	{
		name: 'mainBodyMargin',
		cssProperty: 'margin',
		selector: 'body',
		displayName: 'Application/Site Body margin',
		description: 'This margin is applied to the body.',
		defaultValue: '0px',
		noPrefix: true,
	},
	{
		name: 'boxBoxShadow',
		displayName: 'Box shadow for container',
		description: 'Box shadow for container.',
		defaultValue: '#E6E6E6',
		noPrefix: true,
	},
	{
		name: 'mainFontWeight',
		displayName: 'Application/Site Font Weight',
		description: 'This font is used throughout application.',
		selector: 'body',
		noPrefix: true,
	},
	{
		name: 'mainFocusColor',
		displayName: 'Application/Site text box Focus Color',
		description: 'This color is used for focus on text box',
		defaultValue: '#397ef5',
		noPrefix: true,
	},
	{
		name: 'mainErrorIconColor',
		displayName: 'Application/Site text box error icon color',
		description: 'This color is used for error icon when error occurs during validation',
		defaultValue: '#EC6A5F',
		noPrefix: true,
	},
	{
		name: 'mainFontColor',
		cssProperty: 'color',
		selector: 'body',
		displayName: 'Application/Site Color',
		description: 'This color is used throughout application for all fonts.',
		defaultValue: '#1f3c3d',
		noPrefix: true,
	},
	{
		name: 'blackFontColor',
		cssProperty: 'color',
		displayName: 'Application/Site Color',
		description: 'This color is used throughout application for all fonts.',
		defaultValue: '#000000',
		noPrefix: true,
	},
	{
		name: 'lightBlackFontColor',
		displayName: 'Application/Site Color',
		description: 'This color is used throughout application for all fonts.',
		defaultValue: '#0000001F',
		noPrefix: true,
	},
	{
		name: 'formInputBorderColor',
		displayName: 'Form input border color',
		description: 'This border color is used throughout form input controls.',
		defaultValue: '#C7C8D6',
		noPrefix: true,
	},
	{
		name: 'formInputBorderColorFocussed',
		displayName: 'Form input border color when focussed',
		description: 'This border color is used throughout form input controls when focussed.',
		defaultValue: '#393A3C',
		noPrefix: true,
	},
	{
		name: 'formInputBorderColorHover',
		displayName: 'Form input border color when hover',
		description: 'This border color is used throughout form input controls when hover.',
		defaultValue: '#2680EB',
		noPrefix: true,
	},
	{
		name: 'optionHoverBackground',
		displayName: 'Hover background color',
		description: 'Background color on hover.',
		defaultValue: '#F4F6F6',
		noPrefix: true,
	},
	{
		name: 'formInputBorderColorWithText',
		displayName: 'Form input border color when has text',
		description: 'This border color is used throughout form input controls when has text.',
		defaultValue: '#393A3C',
		noPrefix: true,
	},
	{
		name: 'formInputTextColor',
		displayName: 'Form input text color',
		description: 'This text color is used throughout form input controls.',
		defaultValue: '#393A3C',
		noPrefix: true,
	},
	{
		name: 'formInputBorderColorWhenDisabled',
		displayName: 'Form input border color when disabled',
		description: 'This border color is used throughout form input controls when disabled.',
		defaultValue: '#C7C8D6',
		noPrefix: true,
	},
	{
		name: 'formInputBorderColorWhenError',
		displayName: 'Form input border color when error',
		description: 'This border color is used throughout form input controls when error.',
		defaultValue: '#EC6A5F',
		noPrefix: true,
	},
	{
		name: 'formInputTextColorWhenDisabled',
		displayName: 'Form input text color when disabled',
		description: 'This text color is used throughout form input controls when disabled.',
		defaultValue: '#C7C8D6',
		noPrefix: true,
	},
	{
		name: 'formInputMouseEventWhenDisabled',
		displayName: 'Form input mouse event when disabled',
		description: 'This mouse event is used throughout form input controls when disbaled',
		defaultValue: 'not-allowed',
		noPrefix: true,
	},
	{
		name: 'formInputTextColorWhenError',
		displayName: 'Form input text color when error',
		description: 'This text color is used throughout form input controls when error.',
		defaultValue: '#ED6A5E',
		noPrefix: true,
	},
	{
		name: 'formInputIconDisabledColor',
		displayName: 'Application/Site Disabled font color',
		description: 'This disabled color is used throughout application.',
		defaultValue: '#d5d5d5',
		noPrefix: true,
	},
	{
		name: 'formInputBorderErrorColor',
		displayName: 'Application/Site Error color',
		description: 'This error color is used throughout application.',
		defaultValue: '#ed6a5e',
		noPrefix: true,
	},
	{
		name: 'fromInputErrorIconHastextColor',
		displayName: 'Form Input Text Box Error Icon Color When Text',
		description: 'This error icon color is used when we input in textbox after any error',
		defaultValue: '#393A3C',
		noPrefix: true,
	},
	{
		name: 'mainDisabledColor',
		displayName: 'Application/Site Disabled font color',
		description: 'This disabled color is used throughout application.',
		defaultValue: '#d5d5d5',
		noPrefix: true,
	},
	{
		name: 'mainErrorColor',
		displayName: 'Application/Site Error color',
		description: 'This error color is used throughout application.',
		defaultValue: '#ed6a5e',
		noPrefix: true,
	},
	{
		name: 'mainFontSize',
		displayName: 'Application/Site font size',
		description: 'This error color is used throughout application.',
		defaultValue: '12px',
		noPrefix: true,
	},
	{
		name: 'lightFontColor',
		displayName: 'Application/Site Light font color',
		description: 'This font color is used throughout application where light color is needed.',
		defaultValue: '#ffffff',
		noPrefix: true,
	},
	{
		name: 'contrastBrightColor',
		displayName: 'Application/Site Bright color',
		description: 'This color is used throughout application where bright color is needed',
		defaultValue: '#e5b122',
		noPrefix: true,
	},
	{
		name: 'lightContrastBrightColor',
		displayName: 'Application/Site Bright color',
		description: 'This color is used throughout application where bright color is needed',
		defaultValue: '#e5b12221',
		noPrefix: true,
	},
	{
		name: 'mainDisabledText',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '#6e6e6e',
		noPrefix: true,
	},
	{
		name: 'secondaryDisabledBorder',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '#bcbcbc',
		noPrefix: true,
	},
	{
		name: 'appTextDisabledColor',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '#888585',
		noPrefix: true,
	},
	{
		name: 'appGreyColor',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '#dddddd',
		noPrefix: true,
	},
	{
		name: 'appSecondaryGreyColor',
		displayName: 'Application/Site Primary color',
		description: 'This color is used throughout application.',
		defaultValue: '#e3e3e3',
		noPrefix: true,
	},
	{
		name: 'bodyBackground',
		displayName: 'Application/Site Background',
		description: 'This is the application level background',
		noPrefix: true,
		cssProperty: 'background',
		selector: 'body',
	},
	{
		name: 'primaryBackground',
		displayName: 'Primary background',
		description: 'Primary background image/color',
		noPrefix: true,
		cssProperty: 'background',
		selector: '._PRIMARYBG',
		defaultValue: '<mainFontColor>',
	},
	{
		name: 'secondaryBackground',
		displayName: 'Secondary background',
		description: 'Secondary background image/color',
		noPrefix: true,
		cssProperty: 'background',
		selector: '._SECONDARYBG',
		defaultValue: '#FFFFFFF8',
	},
	{
		name: 'tertiaryBackground',
		displayName: 'Tertiary background',
		description: 'Tertiary background image/color',
		noPrefix: true,
		cssProperty: 'background',
		selector: '._TERTIARYBG',
		defaultValue: '#E6A435',
	},
	{
		name: 'quaternaryBackground',
		displayName: 'Quaternary background',
		description: 'Quaternary background image/color',
		noPrefix: true,
		cssProperty: 'background',
		selector: '._QUATERNARYBG',
		defaultValue: '#DAAC53',
	},
	{
		name: 'quinaryBackground',
		displayName: 'Quinary background',
		description: 'Quinary background image/color',
		noPrefix: true,
		cssProperty: 'background',
		selector: '._QUINARYBG',
		defaultValue: 'radial-gradient(farthest-corner at 10% 55%, #F7E7D1, #F9CDC7 120%)',
	},
	{
		name: 'senaryBackground',
		displayName: 'Senary background',
		description: 'Senary background image/color',
		noPrefix: true,
		cssProperty: 'background',
		selector: '._SENARYBG',
		defaultValue: 'radial-gradient(farthest-corner at 10% 85%, #555D6D, #9EE2D0 120%)',
	},
	{
		name: 'septenaryBackground',
		displayName: 'Septenary background',
		description: 'Septenary background image/color',
		noPrefix: true,
		cssProperty: 'background',
		selector: '._SEPTENARYBG',
		defaultValue: '#F5E2C6',
	},
	{
		name: 'scrollBarWidth',
		displayName: 'Scroll bar width',
		description: 'Scroll bar width',
		noPrefix: true,
		cssProperty: 'width',
		selector: '::-webkit-scrollbar',
		defaultValue: '7px',
	},
	{
		name: 'scrollBarHeight',
		displayName: 'Scroll bar height',
		description: 'Scroll bar height',
		noPrefix: true,
		cssProperty: 'height',
		selector: '::-webkit-scrollbar',
		defaultValue: '7px',
	},
	{
		name: 'scrollBarThumbBg',
		displayName: 'Scroll bar thumb background',
		description: 'Scroll bar thumb background',
		noPrefix: true,
		cssProperty: 'background',
		selector: '::-webkit-scrollbar-thumb',
		defaultValue: '#a3b2c0',
	},
	{
		name: 'scrollBarThumbBorderRadius',
		displayName: 'Scroll bar thumb border radius',
		description: 'Scroll bar thumb border radius',
		noPrefix: true,
		cssProperty: 'border-radius',
		selector: '::-webkit-scrollbar-thumb, ::-webkit-scrollbar-corner',
		defaultValue: '3px',
	},
	{
		name: 'scrollBarHoverWidth',
		displayName: 'Scroll bar hover width',
		description: 'Scroll bar hover width',
		noPrefix: true,
		cssProperty: 'width',
		selector: '*:hover::-webkit-scrollbar',
		defaultValue: '7px',
	},
	{
		name: 'scrollBarThumbHoverBg',
		displayName: 'Scroll bar hover thumb background',
		description: 'Scroll bar hover thumb background',
		noPrefix: true,
		cssProperty: 'background',
		selector: '*:hover::-webkit-scrollbar-thumb',
		defaultValue: '#6d8499',
	},
	{
		name: 'validationMsgFontSize',
		displayName: 'Validation Messages Font Size',
		description: 'Validation Messages Font Size',
		noPrefix: true,
		cssProperty: 'font-size',
		selector: '._validationMessages',
		defaultValue: 'calc(<mainFontSize> - 2px)',
	},
	{
		name: 'validationMsgFontColor',
		displayName: 'Validation Messages Font Color',
		description: 'Validation Messages Font Color',
		noPrefix: true,
		cssProperty: 'color',
		selector: '._validationMessages',
		defaultValue: '<mainErrorColor>',
	},
	{
		name: 'validationMsgFixedHeight',
		displayName: 'minHeight for Validation Messages with fixed display type',
		description: 'minHeight for Validation Messages with fixed display type',
		noPrefix: true,
		cssProperty: 'min-height',
		selector: '._validationMessages._fixedMessages',
		defaultValue: '20px',
	},

	// New Global Theme
	{
		groupName: 'Primary Font',
		displayName: 'Primary Font Family',
		name: 'primaryFontFamily',
		defaultValue: 'Asap',
		description: 'Primary Font Family used in application.',
		cssProperty: '',
		selector: '._primaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Secodary Font',
		displayName: 'Secondary Font Family',
		name: 'secondaryFontFamily',
		defaultValue: 'Roboto',
		description: 'Secondary Font Family used in application.',
		cssProperty: '',
		selector: '._secondaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Font',
		displayName: 'Tertiary Font Family',
		name: 'tertiaryFontFamily',
		defaultValue: 'Open Sans',
		description: 'Tertiary Font Family used in application.',
		cssProperty: '',
		selector: '._tertiaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Font',
		displayName: 'Quaternary Font Family',
		name: 'quaternaryFontFamily',
		defaultValue: 'Roboto',
		description: 'Quaternary Font Family used in application.',
		cssProperty: '',
		selector: '._quaternaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Font',
		displayName: 'Quinary Font Family',
		name: 'quinaryFontFamily',
		defaultValue: 'Roboto',
		description: 'Quinary Font Family used in application.',
		cssProperty: '',
		selector: '._quinaryFont',
		noPrefix: true,
	},

	{
		groupName: 'Primary Font',
		displayName: 'Primary Font Size',
		name: 'primaryFontSize',
		defaultValue: '18px',
		description: 'Primary Font Size used in application.',
		cssProperty: '',
		selector: '._primaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Secodary Font',
		displayName: 'Secodary Font Size',
		name: 'secondaryFontSize',
		defaultValue: '16px',
		description: 'Secondary Font Size used in application.',
		cssProperty: '',
		selector: '._secondaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Font',
		displayName: 'Tertiary Font Size',
		name: 'tertiaryFontSize',
		defaultValue: '14px',
		description: 'Tertiary Font Size used in application.',
		cssProperty: '',
		selector: '._tertiaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Font',
		displayName: 'Quaternary Font Size',
		name: 'quaternaryFontSize',
		defaultValue: '12px',
		description: 'Quaternary Font Size used in application.',
		cssProperty: '',
		selector: '._quaternaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Font',
		displayName: 'Quinary Font Size',
		name: 'quinaryFontSize',
		defaultValue: '10px',
		description: 'Quinary Font Size used in application.',
		cssProperty: '',
		selector: '._quinaryFont',
		noPrefix: true,
	},

	{
		groupName: 'Primary Font',
		displayName: 'Primary Font Line Height',
		name: 'primaryFontLineHeight',
		defaultValue: '26px',
		description: 'Primary Line Height used in application.',
		cssProperty: '',
		selector: '._primaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Secodary Font',
		displayName: 'Secodary Font Line Height',
		name: 'secodaryFontLineHeight',
		defaultValue: '24px',
		description: 'Secondary Line Height used in application.',
		cssProperty: '',
		selector: '._secondaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Font',
		displayName: 'Tertiary Font Line Height',
		name: 'tertiaryFontLineHeight',
		defaultValue: '22px',
		description: 'Tertiary Line Height used in application.',
		cssProperty: '',
		selector: '._tertiaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Font',
		displayName: 'Quaternary Font Line Height',
		name: 'quaternaryFontLineHeight',
		defaultValue: '20px',
		description: 'Quaternary Line Height used in application.',
		cssProperty: '',
		selector: '._quaternaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Font',
		displayName: 'Quinary Font Line Height',
		name: 'quinaryFontLineHeight',
		defaultValue: '18px',
		description: 'Quinary Line Height used in application.',
		cssProperty: '',
		selector: '._quinaryFont',
		noPrefix: true,
	},

	{
		groupName: 'Primary Font',
		displayName: 'Primary Font Weight',
		name: 'primaryFontWeight',
		defaultValue: 'normal',
		description: 'Primary Font Weight used in application.',
		cssProperty: '',
		selector: '._primaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Secodary Font',
		displayName: 'Secodary Font Font Weight',
		name: 'secodaryFontFontWeight',
		defaultValue: 'normal',
		description: 'Secondary Font Weight used in application.',
		cssProperty: '',
		selector: '._secondaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Font',
		displayName: 'Tertiary Font Font Weight',
		name: 'tertiaryFontFontWeight',
		defaultValue: 'normal',
		description: 'Tertiary Font Weight used in application.',
		cssProperty: '',
		selector: '._tertiaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Font',
		displayName: 'Quaternary Font Font Weight',
		name: 'quaternaryFontFontWeight',
		defaultValue: 'normal',
		description: 'Quaternary Font Weight used in application.',
		cssProperty: '',
		selector: '._quaternaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Font',
		displayName: 'Quinary Font Font Weight',
		name: 'quinaryFontFontWeight',
		defaultValue: 'normal',
		description: 'Quinary Font Weight used in application.',
		cssProperty: '',
		selector: '._quinaryFont',
		noPrefix: true,
	},

	{
		groupName: 'Font Weight',
		displayName: 'Bold Font Weight',
		name: 'boldFontWeight',
		defaultValue: 'bold',
		description: 'Bold Font Weight',
		cssProperty: '',
		selector: '._boldFontWeight',
		noPrefix: true,
	},
	{
		groupName: 'Font Weight',
		displayName: 'Normal Font Weight',
		name: 'normalFontWeight',
		defaultValue: 'normal',
		description: 'Normal Font Weight',
		cssProperty: '',
		selector: '._normalFontWeight',
		noPrefix: true,
	},
	{
		groupName: 'Font Weight',
		displayName: 'Extra Bold Font Weight',
		name: 'extraBoldFontWeight',
		defaultValue: '900',
		description: 'Extra Bold Font Weight',
		cssProperty: '',
		selector: '._extraBoldFontWeight',
		noPrefix: true,
	},
	{
		groupName: 'Font Weight',
		displayName: 'Thin Font Weight',
		name: 'thinFontWeight',
		defaultValue: '200',
		description: 'Thin Font Weight',
		cssProperty: '',
		selector: '._thinFontWeight',
		noPrefix: true,
	},

	{
		groupName: 'Primary Font',
		displayName: 'Primary Font Style',
		name: 'primaryFontStyle',
		defaultValue: 'normal',
		description: 'Primary Font Style used in application.',
		cssProperty: '',
		selector: '._primaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Secodary Font',
		displayName: 'Secodary Font Font Style',
		name: 'secodaryFontFontStyle',
		defaultValue: 'normal',
		description: 'Secondary Font Style used in application.',
		cssProperty: '',
		selector: '._secondaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Font',
		displayName: 'Tertiary Font Font Style',
		name: 'tertiaryFontFontStyle',
		defaultValue: 'normal',
		description: 'Tertiary Font Style used in application.',
		cssProperty: '',
		selector: '._tertiaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Font',
		displayName: 'Quaternary Font Font Style',
		name: 'quaternaryFontFontStyle',
		defaultValue: 'normal',
		description: 'Quaternary Font Style used in application.',
		cssProperty: '',
		selector: '._quaternaryFont',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Font',
		displayName: 'Quinary Font Font Style',
		name: 'quinaryFontFontStyle',
		defaultValue: 'normal',
		description: 'Quinary Font Style used in application.',
		cssProperty: '',
		selector: '._quinaryFont',
		noPrefix: true,
	},

	{
		groupName: 'Font Style',
		displayName: 'Normal Font Style',
		name: 'normalFontStyle',
		defaultValue: 'normal',
		description: 'Normal Font Style used in application.',
		cssProperty: '',
		selector: '._normalFontStyle',
		noPrefix: true,
	},
	{
		groupName: 'Font Style',
		displayName: 'Italic Font Style',
		name: 'italicFontStyle',
		defaultValue: 'italic',
		description: 'Italic Font Style used in application.',
		cssProperty: '',
		selector: '._italicFontStyle',
		noPrefix: true,
	},
	{
		groupName: 'Font Style',
		displayName: 'Oblique Font Style',
		name: 'obliqueFontStyle',
		defaultValue: 'oblique',
		description: 'oblique Font Style used in application.',
		cssProperty: '',
		selector: '._obliqueFontStyle',
		noPrefix: true,
	},

	{
		groupName: 'Font Color',
		displayName: 'Font Color One',
		name: 'fontColorOne',
		defaultValue: '#08705C',
		description: 'Font Color One used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Two',
		name: 'fontColorTwo',
		defaultValue: '#333333',
		description: 'Font Color Two used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Three',
		name: 'fontColorThree',
		defaultValue: '#4C7FEE',
		description: 'Font Color Three used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Four',
		name: 'fontColorFour',
		defaultValue: '#96A1B4',
		description: 'Font Color Four used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Five',
		name: 'fontColorFive',
		defaultValue: '#E8E9ED',
		description: 'Font Color Five used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Six',
		name: 'fontColorSix',
		defaultValue: '#4D7FEE',
		description: 'Font Color Six used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Seven',
		name: 'fontColorSeven',
		defaultValue: '#FFC728',
		description: 'Font Color Seven used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Eight',
		name: 'fontColorEight',
		defaultValue: '#F5F5F5',
		description: 'Font Color Eight used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Nine',
		name: 'fontColorNine',
		defaultValue: '#FAFAFA',
		description: 'Font Color Nine used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Ten',
		name: 'fontColorTen',
		defaultValue: '#F8FAFB',
		description: 'Font Color Ten used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Eleven',
		name: 'fontColorEleven',
		defaultValue: '#D9D9D9',
		description: 'Font Color Eleven used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Twelve',
		name: 'fontColorTwelve',
		defaultValue: '#000000',
		description: 'Font Color Twelve used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Thirteen',
		name: 'fontColorThirteen',
		defaultValue: '#52BD94',
		description: 'Font Color Thirteen used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Fourteen',
		name: 'fontColorFourteen',
		defaultValue: '#EC6B5F',
		description: 'Font Color Fourteen used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Fifteen',
		name: 'fontColorFifteen',
		defaultValue: '#FFFFFF',
		description: 'Font Color Fifteen used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Sixteen',
		name: 'fontColorSixteen',
		defaultValue: '#61C554',
		description: 'Font Color Sixteen used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Seventeen',
		name: 'fontColorSeventeen',
		defaultValue: '#8E90A4',
		description: 'Font Color Seventeen used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Eighteen',
		name: 'fontColorEighteen',
		defaultValue: '#F4CA70',
		description: 'Font Color Eighteen used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Font Color Nineteen',
		name: 'fontColorNineteen',
		defaultValue: '#12BA9A',
		description: 'Font Color Nineteen used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Background Color One',
		name: 'backgroundColorOne',
		defaultValue: '<fontColorOne>',
		description: 'Background Color One used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Two',
		name: 'backgroundColorTwo',
		defaultValue: '<fontColorTwo>',
		description: 'Background Color Two used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Three',
		name: 'backgroundColorThree',
		defaultValue: '<fontColorThree>',
		description: 'Background Color Three used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Four',
		name: 'backgroundColorFour',
		defaultValue: '<fontColorFour>',
		description: 'Background Color Four used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Five',
		name: 'backgroundColorFive',
		defaultValue: '<fontColorFive>',
		description: 'Background Color Five used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Six',
		name: 'backgroundColorSix',
		defaultValue: '<fontColorSix>',
		description: 'Background Color Six used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Seven',
		name: 'backgroundColorSeven',
		defaultValue: '<fontColorSeven>',
		description: 'Background Color Seven used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Eight',
		name: 'backgroundColorEight',
		defaultValue: '<fontColorEight>',
		description: 'Background Color Eight used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Nine',
		name: 'backgroundColorNine',
		defaultValue: '<fontColorNine>',
		description: 'Background Color Nine used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Ten',
		name: 'backgroundColorTen',
		defaultValue: '<fontColorTen>',
		description: 'Background Color Ten used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Eleven',
		name: 'backgroundColorEleven',
		defaultValue: '<fontColorEleven>',
		description: 'Background Color Eleven used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Twelve',
		name: 'backgroundColorTwelve',
		defaultValue: '<fontColorTwelve>',
		description: 'Background Color Twelve used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Thirteen',
		name: 'backgroundColorThirteen',
		defaultValue: '<fontColorThirteen>',
		description: 'Background Color Thirteen used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Fourteen',
		name: 'backgroundColorFourteen',
		defaultValue: '<fontColorFourteen>',
		description: 'Background Color Fourteen used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Fifteen',
		name: 'backgroundColorFifteen',
		defaultValue: '<fontColorFifteen>',
		description: 'Background Color Fifteen used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Sixteen',
		name: 'backgroundColorSixteen',
		defaultValue: '<fontColorSixteen>',
		description: 'Background Color Sixteen used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Seventeen',
		name: 'backgroundColorSeventeen',
		defaultValue: '<fontColorSeventeen>',
		description: 'Font Color Seventeen used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Background Color Eighteen',
		name: 'backgroundColorEighteen',
		defaultValue: '<fontColorEighteen>',
		description: 'Font Color Eighteen used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},

	{
		groupName: 'Color Gradient',
		displayName: 'Background Color Gradient One',
		name: 'backgroundColorGradientOne',
		defaultValue: 'linear-gradient(180deg, #464646 -32.5%, <backgroundColorTwelve> 100%)',
		description: 'Background Color Gradient One used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Color Gradient',
		displayName: 'Background Color Gradient Two',
		name: 'backgroundColorGradientTwo',
		defaultValue:
			'linear-gradient(180deg, <fontColorThirteen>e3 -37.5%, <backgroundColorTwo> 100%)',
		description: 'Background Color Gradient Two used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Color Gradient',
		displayName: 'Background Color Gradient Three',
		name: 'backgroundColorGradientThree',
		defaultValue:
			'linear-gradient(180deg, <backgroundColorSeven> -17.5%, <fontColorSeven> 100%)',
		description: 'Background Color Gradient Three used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Color Gradient',
		displayName: 'Background Color Gradient Four',
		name: 'backgroundColorGradientFour',
		defaultValue: 'linear-gradient(180deg, #42B1FF -16.25%, #5E7EBF 100%)',
		description: 'Background Color Gradient Four used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Color Gradient',
		displayName: 'Background Color Gradient Five',
		name: 'backgroundColorGradientFive',
		defaultValue: 'linear-gradient(360deg, #8E90A4 0%, #C4C6D0 155%)',
		description: 'Background Color Gradient Five used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Color Gradient',
		displayName: 'Background Color Gradient Six',
		name: 'backgroundColorGradientSix',
		defaultValue:
			'linear-gradient(87.94deg, <backgroundColorSeven> -85.49%, <backgroundColorEleven> 87.31%)',
		description: 'Background Color Gradient Six used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Color Gradient',
		displayName: 'Background Color Gradient Seven',
		name: 'backgroundColorGradientSeven',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorOne>33 0%, <backgroundColorTen> 93.35%)',
		description: 'Background Color Gradient Seven used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Color Gradient',
		displayName: 'Background Color Gradient Eight',
		name: 'backgroundColorGradientEight',
		defaultValue: 'linear-gradient(90deg, <fontColorThirteen> 0%, <fontColorNineteen> 100%)',
		description: 'Background Color Gradient Seven used in application',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},

	{
		groupName: 'Padding',
		displayName: 'Padding One',
		name: 'paddingOne',
		defaultValue: '0px',
		description: 'Padding One used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Padding',
		displayName: 'Padding Two',
		name: 'paddingTwo',
		defaultValue: '5px',
		description: 'Padding Two used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Padding',
		displayName: 'Padding Three',
		name: 'paddingThree',
		defaultValue: '10px',
		description: 'Padding Three used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Padding',
		displayName: 'Padding Four',
		name: 'paddingFour',
		defaultValue: '15px',
		description: 'Padding Four used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Padding',
		displayName: 'Padding Five',
		name: 'paddingFive',
		defaultValue: '20px',
		description: 'Padding Five used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},

	{
		groupName: 'Margin',
		displayName: 'Margin One',
		name: 'marginOne',
		defaultValue: '0px',
		description: 'Margin One used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Margin',
		displayName: 'Margin Two',
		name: 'marginTwo',
		defaultValue: '5px',
		description: 'Margin Two used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Margin',
		displayName: 'Margin Three',
		name: 'marginThree',
		defaultValue: '10px',
		description: 'Margin Three used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Margin',
		displayName: 'Margin Four',
		name: 'marginFour',
		defaultValue: '15px',
		description: 'Margin Four used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Margin',
		displayName: 'Margin Five',
		name: 'marginFive',
		defaultValue: '20px',
		description: 'Margin Five used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},

	{
		groupName: 'Border Style',
		displayName: 'Border Style One ',
		name: 'borderStyleOne',
		defaultValue: 'none',
		description: 'Border Style One used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Style',
		displayName: 'Border Style Two ',
		name: 'borderStyleTwo',
		defaultValue: 'hidden',
		description: 'Border Style Two used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Style',
		displayName: 'Border Style Three',
		name: 'borderStyleThree',
		defaultValue: 'dotted',
		description: 'Border Style Three used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Style',
		displayName: 'Border Style Four ',
		name: 'borderStyleFour',
		defaultValue: 'dashed',
		description: 'Border Style Four used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Style',
		displayName: 'Border Style Five ',
		name: 'borderStyleFive',
		defaultValue: 'solid',
		description: 'Border Style Five used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Style',
		displayName: 'Border Style Six',
		name: 'borderStyleSix',
		defaultValue: 'double',
		description: 'Border Style Six used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Style',
		displayName: 'Border Style Seven',
		name: 'borderStyleSeven',
		defaultValue: 'groove',
		description: 'Border Style Seven used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Style',
		displayName: 'Border Style Eight',
		name: 'borderStyleEight',
		defaultValue: 'ridge',
		description: 'Border Style Eight used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Style',
		displayName: 'Border Style Nine ',
		name: 'borderStyleNine',
		defaultValue: 'inset',
		description: 'Border Style Nine used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Style',
		displayName: 'Border Style Ten',
		name: 'borderStyleTen',
		defaultValue: 'outset',
		description: 'Border Style Ten used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},

	{
		groupName: 'Border Width',
		displayName: 'Border Width One ',
		name: 'borderWidthOne ',
		defaultValue: '0px',
		description: 'Border Width One used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Width',
		displayName: 'Border Width Two ',
		name: 'borderWidthTwo ',
		defaultValue: '1px',
		description: 'Border Width Two used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Width',
		displayName: 'Border Width Three',
		name: 'borderWidthThree',
		defaultValue: '2px',
		description: 'Border Width Three used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Width',
		displayName: 'Border Width Four ',
		name: 'borderWidthFour ',
		defaultValue: '3px',
		description: 'Border Width Four used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Width',
		displayName: 'Border Width Five ',
		name: 'borderWidthFive ',
		defaultValue: '4px',
		description: 'Border Width Five used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Width',
		displayName: 'Border Width Six',
		name: 'borderWidthSix',
		defaultValue: '0.5px',
		description: 'Border Width Six used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},

	{
		groupName: 'Border Radius',
		displayName: 'Border Radius One',
		name: 'borderRadiusOne',
		defaultValue: '4px',
		description: 'Border Radius One used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Radius',
		displayName: 'Border Radius Two',
		name: 'borderRadiusTwo',
		defaultValue: '0px',
		description: 'Border Radius Two used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Radius',
		displayName: 'Border Radius Three',
		name: 'borderRadiusThree',
		defaultValue: '45px',
		description: 'Border Radius Three used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Radius',
		displayName: 'Border Radius Four',
		name: 'borderRadiusFour',
		defaultValue: '50px',
		description: 'Border Radius Four used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},

	{
		groupName: 'Border Color',
		displayName: 'Border Color One',
		name: 'borderColorOne',
		defaultValue: '<fontColorFourteen>',
		description: 'Border Color One used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Border Color Two',
		name: 'borderColorTwo',
		defaultValue: '<fontColorOne>',
		description: 'Border Color Two used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Border Color Three',
		name: 'borderColorThree',
		defaultValue: '<fontColorEighteen>',
		description: 'Border Color Three used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Border Color Four',
		name: 'borderColorFour',
		defaultValue: '<fontColorTwo>',
		description: 'Border Color Four used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Border Color Five',
		name: 'borderColorFive',
		defaultValue: '<fontColorSeventeen>',
		description: 'Border Color Five used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Border Color Six',
		name: 'borderColorSix',
		defaultValue: '<fontColorSix>',
		description: 'Border Color Six used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Border Color Seven',
		name: 'borderColorSeven',
		defaultValue: '<fontColorSixteen>',
		description: 'Border Color Seven used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Border Color Eight',
		name: 'borderColorEight',
		defaultValue: '<fontColorOne>73',
		description: 'Border Color Eight used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Border Color Nine',
		name: 'borderColorNine',
		defaultValue: '<fontColorFourteen>1a',
		description: 'Border Color Nine used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},

	{
		groupName: 'Letter Spacing',
		displayName: 'Letter Spacing One',
		name: 'letterSpacingOne',
		defaultValue: 'normal',
		description: 'Letter Spacing One used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
	{
		groupName: 'Letter Spacing',
		displayName: 'Letter Spacing Two',
		name: 'letterSpacingTwo',
		defaultValue: '0.16px',
		description: 'Letter Spacing Two used in application.',
		cssProperty: '',
		selector: '',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
