import {
	SCHEMA_ANY_COMP_PROP,
	SCHEMA_BOOL_COMP_PROP,
	SCHEMA_NUM_COMP_PROP,
	SCHEMA_STRING_COMP_PROP,
} from '../../constants';
import {
	ComponentPropertyDefinition,
	ComponentPropertyEditor,
	ComponentPropertyGroup,
} from '../../types/common';
import { COMMON_COMPONENT_PROPERTIES, COMPONENT_STYLE_GROUP_PROPERTIES } from '../util/properties';

const propertiesDefinition: Array<ComponentPropertyDefinition> = [
	{
		name: 'showArrowButtons',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Left and right Buttons',
		description: 'Left and right arrow buttons to control carousel',
		group: ComponentPropertyGroup.BASIC,
		defaultValue: true,
	},
	{
		name: 'slideSpeed',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'Carousel slide speed',
		description: `Adjust the slide speed by giving the time in milliseconds.`,
		group: ComponentPropertyGroup.BASIC,
		defaultValue: 2000,
	},
	{
		name: 'animationDuration',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'Animation Duration',
		description: 'How long the animation should last.',
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: 2000,
	},
	{
		name: 'easing',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Easing',
		description: 'Easing',
		editor: ComponentPropertyEditor.ENUM,
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: 'ease',
		enumValues: [
			{ name: 'linear', displayName: 'Linear', description: 'Linear' },
			{ name: 'ease', displayName: 'Ease', description: 'Ease' },
			{ name: 'ease-in', displayName: 'Ease In', description: 'Ease In' },
			{ name: 'ease-out', displayName: 'Ease Out', description: 'Ease Out' },
			{ name: 'ease-in-out', displayName: 'Ease In Out', description: 'Ease In Out' },
		],
	},
	{
		name: 'autoPlay',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Auto Play',
		description: 'Play automatically without interaction',
		group: ComponentPropertyGroup.BASIC,
		defaultValue: true,
	},
	{
		name: 'dotsButtonType',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Dots Button Type',
		description: 'Types of Dot buttons',
		editor: ComponentPropertyEditor.ENUM,
		defaultValue: 'circle',
		group: ComponentPropertyGroup.BASIC,
		enumValues: [
			{ name: 'circle', displayName: 'dots', description: 'dots' },
			{ name: 'square', displayName: 'square', description: 'square buttons' },
			{ name: 'minus', displayName: 'dash', description: 'dash icon' },
			{ name: 'none', displayName: 'none', description: 'none' },
		],
	},
	{
		name: 'dotsButtonIconType',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Dots Button Type',
		description: 'Position of Dot buttons',
		editor: ComponentPropertyEditor.ENUM,
		group: ComponentPropertyGroup.BASIC,
		defaultValue: 'regular',
		enumValues: [
			{ name: 'regular', displayName: 'regular', description: 'hallow icon' },
			{ name: 'solid', displayName: 'solid', description: 'solid icon' },
		],
	},
	{
		name: 'show Slide Numbers In Dots',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Show Slide Numbers In Dots',
		description: 'Show Slide number in the dots',
		group: ComponentPropertyGroup.BASIC,
		defaultValue: false,
	},
	{
		name: 'slideNavButtonPlacement',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'slide Nav Button Placement',
		description: 'Slide Nav Dot buttons Placement',
		editor: ComponentPropertyEditor.ENUM,
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: 'Inside',
		enumValues: [
			{
				name: 'Inside',
				displayName: 'Inside',
				description: 'slide navigations button inside placement',
			},
			{
				name: 'Outside',
				displayName: 'Outside',
				description: 'slide navigations button outside placement',
			},
		],
	},
	{
		name: 'slideNavButtonVerticalAlignment',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Slide Nav Button Vertical Alignment',
		description: 'Slide Nav Button Vertical Alignment',
		editor: ComponentPropertyEditor.ENUM,
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: 'Bottom',
		enumValues: [
			{
				name: 'Top',
				displayName: 'Top',
				description: 'slide navigations button positioned on top',
			},
			{
				name: 'Bottom',
				displayName: 'Bottom',
				description: 'slide navigations button positioned on bottom',
			},
		],
	},
	{
		name: 'slideNavButtonHorizontalAlignment',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Slide Nav Button Horizontal Alignment',
		description: 'Slide Nav Button Horizontal Alignment',
		editor: ComponentPropertyEditor.ENUM,
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: 'Middle',
		enumValues: [
			{
				name: 'Right',
				displayName: 'Right',
				description: 'slide navigations button positioned right',
			},
			{
				name: 'Left',
				displayName: 'Left',
				description: 'slide navigations button positioned Left',
			},
			{
				name: 'Middle',
				displayName: 'Middle',
				description: 'slide navigations button positioned Middle',
			},
		],
	},
	{
		name: 'arrowButtonsPlacement',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Arrow Buttons Placement',
		description: 'Arrow buttons Placement outside or inside',
		editor: ComponentPropertyEditor.ENUM,
		defaultValue: 'Inside',
		group: ComponentPropertyGroup.ADVANCED,
		enumValues: [
			{
				name: 'Inside',
				displayName: 'Inside',
				description: 'Arrow navigations button positioned inside',
			},
			{
				name: 'Outside',
				displayName: 'Outside',
				description: 'Arrow navigations button positioned outside',
			},
		],
	},
	{
		name: 'arrowButtonsVerticalPlacement',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Arrow Buttons Vertical Placement',
		description: 'Arrow buttons Placement Vertical',
		editor: ComponentPropertyEditor.ENUM,
		defaultValue: 'Bottom',
		group: ComponentPropertyGroup.ADVANCED,
		enumValues: [
			{
				name: 'Bottom',
				displayName: 'Bottom',
				description: 'Arrow navigations button positioned bottom',
			},
			{
				name: 'Top',
				displayName: 'Top',
				description: 'Arrow navigations button positioned on top',
			},
			{
				name: 'Center',
				displayName: 'Center',
				description: 'Arrow navigations button positioned center',
			},
		],
	},
	{
		name: 'arrowButtonsHorizontalPlacement',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Arrow Buttons Horizontal Placement',
		description: 'Arrow buttons Placement Horizontal',
		editor: ComponentPropertyEditor.ENUM,
		defaultValue: 'Middle',
		group: ComponentPropertyGroup.ADVANCED,
		enumValues: [
			{
				name: 'Left',
				displayName: 'Left',
				description: 'Arrow navigations button positioned Left',
			},
			{
				name: 'Right',
				displayName: 'Right',
				description: 'Arrow navigations button positioned Right',
			},
			{
				name: 'Middle',
				displayName: 'Middle',
				description: 'Arrow navigations button positioned Middle',
			},
		],
	},
	{
		name: 'showNavigationControlsOnHover',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Show navigation controls on hover',
		description:
			'This property display navigation controls, i.e; navigation and buttons, when the carousel is hovered upon.',
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: false,
	},
	{
		name: 'showArrowButtonsOnHover',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Show Arrow Buttons on hover',
		description:
			'This property display arrow buttons, i.e; arrows buttons, when the carousel is hovered upon.',
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: false,
	},
	{
		name: 'designType',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Deisgn Type',
		description: 'Design Type',
		editor: ComponentPropertyEditor.ENUM,
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: '_primary',
		enumValues: [
			{ name: '_primary', displayName: 'Simple Mode', description: 'Simple Mode Slider' },
			{ name: '_secondary', displayName: 'Center Mode', description: 'Center Mode Slider' },
			{ name: '_tertiary', displayName: 'Vertical Slider', description: 'Vertical Mode Slider' },
			{ name: '_quaternary', displayName: 'Vertical Center Mode', description: 'Vertical Center Mode' },
		],
	},
	{
		name: 'slidesToScroll',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'Number of slides to scroll',
		description: 'Add the number of slides you want to scroll at once',
		group: ComponentPropertyGroup.BASIC,
		defaultValue: 1,
	},
	{
		name: 'pauseOnHover',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Pause on hover over the slide',
		description: 'You can enable pause on hover on current slide',
		group: ComponentPropertyGroup.BASIC,
		defaultValue: false,
	},
	{
		name: 'fixedChild',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Toggle To Show Fixed no of Childs',
		description: 'This Shows the fixed number of slides given by user',
		group: ComponentPropertyGroup.BASIC,
		defaultValue: false,
	},
	{
		name: 'noOfChilds',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'Number of slides to show',
		description: 'This is the number of slides to show when fixed child is selected',
		group: ComponentPropertyGroup.BASIC,
		defaultValue: 3,
	},
	COMMON_COMPONENT_PROPERTIES.visibility,
	COMMON_COMPONENT_PROPERTIES.readOnly,
	{
		name: 'data',
		schema: SCHEMA_ANY_COMP_PROP,
		displayName: 'Default Data',
		description: 'Default data for repeater',
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		...COMMON_COMPONENT_PROPERTIES.datatype,
		enumValues: [
			{
				name: 'LIST_OF_STRINGS',
				displayName: 'List of strings',
				description: 'data has an array of strings',
			},
			{
				name: 'LIST_OF_OBJECTS',
				displayName: 'List of objects',
				description: 'data has an array of objects',
			},
		],
	},
	COMMON_COMPONENT_PROPERTIES.selectionKey,
	COMMON_COMPONENT_PROPERTIES.uniqueKey,
	COMMON_COMPONENT_PROPERTIES.selectionType,
	COMMON_COMPONENT_PROPERTIES.uniqueKeyType
];

const stylePropertiesDefinition = {
	'': [
		COMPONENT_STYLE_GROUP_PROPERTIES.layout.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.position.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.typography.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.effects.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.background.type,
	],
	arrowButtonsContainer: [
		COMPONENT_STYLE_GROUP_PROPERTIES.layout.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.position.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.typography.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
	],
	arrowButtons: [
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.typography.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
	],
	slideButtonsContainer: [
		COMPONENT_STYLE_GROUP_PROPERTIES.layout.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.position.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.typography.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.effects.type,
	],
	dotButtons: [
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.typography.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.effects.type,
	],
	innerDivSlideNav: [
		COMPONENT_STYLE_GROUP_PROPERTIES.layout.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.position.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.effects.type,
	],
	containerInnerDiv: [
		COMPONENT_STYLE_GROUP_PROPERTIES.layout.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.effects.type,
	],
	childElement: [
		COMPONENT_STYLE_GROUP_PROPERTIES.layout.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.effects.type,
	],
};

export { propertiesDefinition, stylePropertiesDefinition };
