import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'Font',
		displayName: 'Slider Font',
		name: 'sliderFont',
		defaultValue: '<primaryFont>',
		cssProperty: 'font',
		selector: '.comp.compSmallCarousel',
		noPrefix: true,
	},
	{
		groupName: 'Text Color',
		displayName: 'Slider Font Color',
		name: 'sliderFontColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Container Background Color Primay Design1',
		name: 'sliderContainerBackgroundColorPrimayDesign1',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._primary',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Container Background Color Secondary Design1',
		name: 'sliderContainerBackgroundColorSecondaryDesign1',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Container Background Color Tertiary Design1',
		name: 'sliderContainerBackgroundColorTertiaryDesign1',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Container Background Color Quaternary Design1',
		name: 'sliderContainerBackgroundColorQuaternaryDesign1',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Container Background Color Quinary Design1',
		name: 'sliderContainerBackgroundColorQuinaryDesign1',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Container Background Color Primay Design2',
		name: 'sliderContainerBackgroundColorPrimayDesign2',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._primary',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Container Background Color Secondary Design2',
		name: 'sliderContainerBackgroundColorSecondaryDesign2',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Container Background Color Tertiary Design2',
		name: 'sliderContainerBackgroundColorTertiaryDesign2',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Container Background Color Quaternary Design2',
		name: 'sliderContainerBackgroundColorQuaternaryDesign2',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Container Background Color Quinary Design2',
		name: 'sliderContainerBackgroundColorQuinaryDesign2',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Container Background Color Primay Design3',
		name: 'sliderContainerBackgroundColorPrimayDesign3',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._primary',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Container Background Color Secondary Design3',
		name: 'sliderContainerBackgroundColorSecondaryDesign3',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Container Background Color Tertiary Design3',
		name: 'sliderContainerBackgroundColorTertiaryDesign3',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Container Background Color Quaternary Design3',
		name: 'sliderContainerBackgroundColorQuaternaryDesign3',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Container Background Color Quinary Design3',
		name: 'sliderContainerBackgroundColorQuinaryDesign3',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Container Background Color Primay Design4',
		name: 'sliderContainerBackgroundColorPrimayDesign4',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._primary',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Container Background Color Secondary Design4',
		name: 'sliderContainerBackgroundColorSecondaryDesign4',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Container Background Color Tertiary Design4',
		name: 'sliderContainerBackgroundColorTertiaryDesign4',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Container Background Color Quaternary Design4',
		name: 'sliderContainerBackgroundColorQuaternaryDesign4',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Container Background Color Quinary Design4',
		name: 'sliderContainerBackgroundColorQuinaryDesign4',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Container Padding Primay Design1',
		name: 'sliderContainerPaddingPrimayDesign1',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._primary',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Container Padding Secondary Design1',
		name: 'sliderContainerPaddingSecondaryDesign1',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Container Padding Tertiary Design1',
		name: 'sliderContainerPaddingTertiaryDesign1',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Container Padding Quaternary Design1',
		name: 'sliderContainerPaddingQuaternaryDesign1',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Container Padding Quinary Design1',
		name: 'sliderContainerPaddingQuinaryDesign1',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Container Padding Primay Design2',
		name: 'sliderContainerPaddingPrimayDesign2',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._primary',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Container Padding Secondary Design2',
		name: 'sliderContainerPaddingSecondaryDesign2',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Container Padding Tertiary Design2',
		name: 'sliderContainerPaddingTertiaryDesign2',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Container Padding Quaternary Design2',
		name: 'sliderContainerPaddingQuaternaryDesign2',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Container Padding Quinary Design2',
		name: 'sliderContainerPaddingQuinaryDesign2',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Container Padding Primay Design3',
		name: 'sliderContainerPaddingPrimayDesign3',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._primary',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Container Padding Secondary Design3',
		name: 'sliderContainerPaddingSecondaryDesign3',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Container Padding Tertiary Design3',
		name: 'sliderContainerPaddingTertiaryDesign3',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Container Padding Quaternary Design3',
		name: 'sliderContainerPaddingQuaternaryDesign3',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Container Padding Quinary Design3',
		name: 'sliderContainerPaddingQuinaryDesign3',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Container Padding Primay Design4',
		name: 'sliderContainerPaddingPrimayDesign4',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._primary',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Container Padding Secondary Design4',
		name: 'sliderContainerPaddingSecondaryDesign4',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Container Padding Tertiary Design4',
		name: 'sliderContainerPaddingTertiaryDesign4',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Container Padding Quaternary Design4',
		name: 'sliderContainerPaddingQuaternaryDesign4',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Container Padding Quinary Design4',
		name: 'sliderContainerPaddingQuinaryDesign4',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Arrow Button Color Primay Design1',
		name: 'sliderArrowButtonColorPrimayDesign1',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Arrow Button Color Secondary Design1',
		name: 'sliderArrowButtonColorSecondaryDesign1',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Arrow Button Color Tertiary Design1',
		name: 'sliderArrowButtonColorTertiaryDesign1',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Arrow Button Color Quaternary Design1',
		name: 'sliderArrowButtonColorQuaternaryDesign1',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Arrow Button Color Quinary Design1',
		name: 'sliderArrowButtonColorQuinaryDesign1',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Arrow Button Color Primay Design2',
		name: 'sliderArrowButtonColorPrimayDesign2',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Arrow Button Color Secondary Design2',
		name: 'sliderArrowButtonColorSecondaryDesign2',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Arrow Button Color Tertiary Design2',
		name: 'sliderArrowButtonColorTertiaryDesign2',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Arrow Button Color Quaternary Design2',
		name: 'sliderArrowButtonColorQuaternaryDesign2',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Arrow Button Color Quinary Design2',
		name: 'sliderArrowButtonColorQuinaryDesign2',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Arrow Button Color Primay Design3',
		name: 'sliderArrowButtonColorPrimayDesign3',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Arrow Button Color Secondary Design3',
		name: 'sliderArrowButtonColorSecondaryDesign3',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Arrow Button Color Tertiary Design3',
		name: 'sliderArrowButtonColorTertiaryDesign3',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Arrow Button Color Quaternary Design3',
		name: 'sliderArrowButtonColorQuaternaryDesign3',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Arrow Button Color Quinary Design3',
		name: 'sliderArrowButtonColorQuinaryDesign3',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Arrow Button Color Primay Design4',
		name: 'sliderArrowButtonColorPrimayDesign4',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Arrow Button Color Secondary Design4',
		name: 'sliderArrowButtonColorSecondaryDesign4',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Arrow Button Color Tertiary Design4',
		name: 'sliderArrowButtonColorTertiaryDesign4',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Arrow Button Color Quaternary Design4',
		name: 'sliderArrowButtonColorQuaternaryDesign4',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Arrow Button Color Quinary Design4',
		name: 'sliderArrowButtonColorQuinaryDesign4',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Arrow Button BackgroundColor Primay Design1',
		name: 'sliderArrowButtonBackgroundColorPrimayDesign1',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Arrow Button BackgroundColor Secondary Design1',
		name: 'sliderArrowButtonBackgroundColorSecondaryDesign1',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Arrow Button BackgroundColor Tertiary Design1',
		name: 'sliderArrowButtonBackgroundColorTertiaryDesign1',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Arrow Button BackgroundColor Quaternary Design1',
		name: 'sliderArrowButtonBackgroundColorQuaternaryDesign1',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Arrow Button BackgroundColor Quinary Design1',
		name: 'sliderArrowButtonBackgroundColorQuinaryDesign1',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Arrow Button BackgroundColor Primay Design2',
		name: 'sliderArrowButtonBackgroundColorPrimayDesign2',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Arrow Button BackgroundColor Secondary Design2',
		name: 'sliderArrowButtonBackgroundColorSecondaryDesign2',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Arrow Button BackgroundColor Tertiary Design2',
		name: 'sliderArrowButtonBackgroundColorTertiaryDesign2',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Arrow Button BackgroundColor Quaternary Design2',
		name: 'sliderArrowButtonBackgroundColorQuaternaryDesign2',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Arrow Button BackgroundColor Quinary Design2',
		name: 'sliderArrowButtonBackgroundColorQuinaryDesign2',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Arrow Button BackgroundColor Primay Design3',
		name: 'sliderArrowButtonBackgroundColorPrimayDesign3',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Arrow Button BackgroundColor Secondary Design3',
		name: 'sliderArrowButtonBackgroundColorSecondaryDesign3',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Arrow Button BackgroundColor Tertiary Design3',
		name: 'sliderArrowButtonBackgroundColorTertiaryDesign3',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Arrow Button BackgroundColor Quaternary Design3',
		name: 'sliderArrowButtonBackgroundColorQuaternaryDesign3',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Arrow Button BackgroundColor Quinary Design3',
		name: 'sliderArrowButtonBackgroundColorQuinaryDesign3',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Arrow Button BackgroundColor Primay Design4',
		name: 'sliderArrowButtonBackgroundColorPrimayDesign4',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Arrow Button BackgroundColor Secondary Design4',
		name: 'sliderArrowButtonBackgroundColorSecondaryDesign4',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Arrow Button BackgroundColor Tertiary Design4',
		name: 'sliderArrowButtonBackgroundColorTertiaryDesign4',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Arrow Button BackgroundColor Quaternary Design4',
		name: 'sliderArrowButtonBackgroundColorQuaternaryDesign4',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Arrow Button BackgroundColor Quinary Design4',
		name: 'sliderArrowButtonBackgroundColorQuinaryDesign4',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Arrow Button Border Primay Design1',
		name: 'sliderArrowButtonBorderPrimayDesign1',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Arrow Button Border Secondary Design1',
		name: 'sliderArrowButtonBorderSecondaryDesign1',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Arrow Button Border Tertiary Design1',
		name: 'sliderArrowButtonBorderTertiaryDesign1',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Arrow Button Border Quaternary Design1',
		name: 'sliderArrowButtonBorderQuaternaryDesign1',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Arrow Button Border Quinary Design1',
		name: 'sliderArrowButtonBorderQuinaryDesign1',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Arrow Button Border Primay Design2',
		name: 'sliderArrowButtonBorderPrimayDesign2',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Arrow Button Border Secondary Design2',
		name: 'sliderArrowButtonBorderSecondaryDesign2',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Arrow Button Border Tertiary Design2',
		name: 'sliderArrowButtonBorderTertiaryDesign2',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Arrow Button Border Quaternary Design2',
		name: 'sliderArrowButtonBorderQuaternaryDesign2',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Arrow Button Border Quinary Design2',
		name: 'sliderArrowButtonBorderQuinaryDesign2',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Arrow Button Border Primay Design3',
		name: 'sliderArrowButtonBorderPrimayDesign3',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Arrow Button Border Secondary Design3',
		name: 'sliderArrowButtonBorderSecondaryDesign3',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Arrow Button Border Tertiary Design3',
		name: 'sliderArrowButtonBorderTertiaryDesign3',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Arrow Button Border Quaternary Design3',
		name: 'sliderArrowButtonBorderQuaternaryDesign3',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Arrow Button Border Quinary Design3',
		name: 'sliderArrowButtonBorderQuinaryDesign3',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Arrow Button Border Primay Design4',
		name: 'sliderArrowButtonBorderPrimayDesign4',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Arrow Button Border Secondary Design4',
		name: 'sliderArrowButtonBorderSecondaryDesign4',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Arrow Button Border Tertiary Design4',
		name: 'sliderArrowButtonBorderTertiaryDesign4',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Arrow Button Border Quaternary Design4',
		name: 'sliderArrowButtonBorderQuaternaryDesign4',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Arrow Button Border Quinary Design4',
		name: 'sliderArrowButtonBorderQuinaryDesign4',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Arrow Button Border Color Primay Design1',
		name: 'sliderArrowButtonBorderColorPrimayDesign1',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Arrow Button Border Color Secondary Design1',
		name: 'sliderArrowButtonBorderColorSecondaryDesign1',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Arrow Button Border Color Tertiary Design1',
		name: 'sliderArrowButtonBorderColorTertiaryDesign1',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Arrow Button Border Color Quaternary Design1',
		name: 'sliderArrowButtonBorderColorQuaternaryDesign1',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Arrow Button Border Color Quinary Design1',
		name: 'sliderArrowButtonBorderColorQuinaryDesign1',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Arrow Button Border Color Primay Design2',
		name: 'sliderArrowButtonBorderColorPrimayDesign2',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Arrow Button Border Color Secondary Design2',
		name: 'sliderArrowButtonBorderColorSecondaryDesign2',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Arrow Button Border Color Tertiary Design2',
		name: 'sliderArrowButtonBorderColorTertiaryDesign2',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Arrow Button Border Color Quaternary Design2',
		name: 'sliderArrowButtonBorderColorQuaternaryDesign2',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Arrow Button Border Color Quinary Design2',
		name: 'sliderArrowButtonBorderColorQuinaryDesign2',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Arrow Button Border Color Primay Design3',
		name: 'sliderArrowButtonBorderColorPrimayDesign3',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Arrow Button Border Color Secondary Design3',
		name: 'sliderArrowButtonBorderColorSecondaryDesign3',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Arrow Button Border Color Tertiary Design3',
		name: 'sliderArrowButtonBorderColorTertiaryDesign3',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Arrow Button Border Color Quaternary Design3',
		name: 'sliderArrowButtonBorderColorQuaternaryDesign3',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Arrow Button Border Color Quinary Design3',
		name: 'sliderArrowButtonBorderColorQuinaryDesign3',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Arrow Button Border Color Primay Design4',
		name: 'sliderArrowButtonBorderColorPrimayDesign4',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Arrow Button Border Color Secondary Design4',
		name: 'sliderArrowButtonBorderColorSecondaryDesign4',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Arrow Button Border Color Tertiary Design4',
		name: 'sliderArrowButtonBorderColorTertiaryDesign4',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Arrow Button Border Color Quaternary Design4',
		name: 'sliderArrowButtonBorderColorQuaternaryDesign4',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Arrow Button Border Color Quinary Design4',
		name: 'sliderArrowButtonBorderColorQuinaryDesign4',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Arrow Button Padding Primay Design1',
		name: 'sliderArrowButtonPaddingPrimayDesign1',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Arrow Button Padding Secondary Design1',
		name: 'sliderArrowButtonPaddingSecondaryDesign1',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Arrow Button Padding Tertiary Design1',
		name: 'sliderArrowButtonPaddingTertiaryDesign1',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Arrow Button Padding Quaternary Design1',
		name: 'sliderArrowButtonPaddingQuaternaryDesign1',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Arrow Button Padding Quinary Design1',
		name: 'sliderArrowButtonPaddingQuinaryDesign1',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Arrow Button Padding Primay Design2',
		name: 'sliderArrowButtonPaddingPrimayDesign2',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Arrow Button Padding Secondary Design2',
		name: 'sliderArrowButtonPaddingSecondaryDesign2',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Arrow Button Padding Tertiary Design2',
		name: 'sliderArrowButtonPaddingTertiaryDesign2',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Arrow Button Padding Quaternary Design2',
		name: 'sliderArrowButtonPaddingQuaternaryDesign2',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Arrow Button Padding Quinary Design2',
		name: 'sliderArrowButtonPaddingQuinaryDesign2',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Arrow Button Padding Primay Design3',
		name: 'sliderArrowButtonPaddingPrimayDesign3',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Arrow Button Padding Secondary Design3',
		name: 'sliderArrowButtonPaddingSecondaryDesign3',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Arrow Button Padding Tertiary Design3',
		name: 'sliderArrowButtonPaddingTertiaryDesign3',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Arrow Button Padding Quaternary Design3',
		name: 'sliderArrowButtonPaddingQuaternaryDesign3',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Arrow Button Padding Quinary Design3',
		name: 'sliderArrowButtonPaddingQuinaryDesign3',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Arrow Button Padding Primay Design4',
		name: 'sliderArrowButtonPaddingPrimayDesign4',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Arrow Button Padding Secondary Design4',
		name: 'sliderArrowButtonPaddingSecondaryDesign4',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Arrow Button Padding Tertiary Design4',
		name: 'sliderArrowButtonPaddingTertiaryDesign4',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Arrow Button Padding Quaternary Design4',
		name: 'sliderArrowButtonPaddingQuaternaryDesign4',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Arrow Button Padding Quinary Design4',
		name: 'sliderArrowButtonPaddingQuinaryDesign4',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Arrow Button Border Radius Primay Design1',
		name: 'sliderArrowButtonBorderRadiusPrimayDesign1',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Arrow Button Border Radius Secondary Design1',
		name: 'sliderArrowButtonBorderRadiusSecondaryDesign1',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Arrow Button Border Radius Tertiary Design1',
		name: 'sliderArrowButtonBorderRadiusTertiaryDesign1',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Arrow Button Border Radius Quaternary Design1',
		name: 'sliderArrowButtonBorderRadiusQuaternaryDesign1',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Arrow Button Border Radius Quinary Design1',
		name: 'sliderArrowButtonBorderRadiusQuinaryDesign1',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Arrow Button Border Radius Primay Design2',
		name: 'sliderArrowButtonBorderRadiusPrimayDesign2',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Arrow Button Border Radius Secondary Design2',
		name: 'sliderArrowButtonBorderRadiusSecondaryDesign2',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Arrow Button Border Radius Tertiary Design2',
		name: 'sliderArrowButtonBorderRadiusTertiaryDesign2',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Arrow Button Border Radius Quaternary Design2',
		name: 'sliderArrowButtonBorderRadiusQuaternaryDesign2',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Arrow Button Border Radius Quinary Design2',
		name: 'sliderArrowButtonBorderRadiusQuinaryDesign2',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Arrow Button Border Radius Primay Design3',
		name: 'sliderArrowButtonBorderRadiusPrimayDesign3',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Arrow Button Border Radius Secondary Design3',
		name: 'sliderArrowButtonBorderRadiusSecondaryDesign3',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Arrow Button Border Radius Tertiary Design3',
		name: 'sliderArrowButtonBorderRadiusTertiaryDesign3',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Arrow Button Border Radius Quaternary Design3',
		name: 'sliderArrowButtonBorderRadiusQuaternaryDesign3',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Arrow Button Border Radius Quinary Design3',
		name: 'sliderArrowButtonBorderRadiusQuinaryDesign3',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Arrow Button Border Radius Primay Design4',
		name: 'sliderArrowButtonBorderRadiusPrimayDesign4',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Arrow Button Border Radius Secondary Design4',
		name: 'sliderArrowButtonBorderRadiusSecondaryDesign4',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Arrow Button Border Radius Tertiary Design4',
		name: 'sliderArrowButtonBorderRadiusTertiaryDesign4',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Arrow Button Border Radius Quaternary Design4',
		name: 'sliderArrowButtonBorderRadiusQuaternaryDesign4',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Arrow Button Border Radius Quinary Design4',
		name: 'sliderArrowButtonBorderRadiusQuinaryDesign4',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Arrow Button Font Size Primay Design1',
		name: 'sliderArrowButtonFontSizePrimayDesign1',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Arrow Button Font Size Secondary Design1',
		name: 'sliderArrowButtonFontSizeSecondaryDesign1',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Arrow Button Font Size Tertiary Design1',
		name: 'sliderArrowButtonFontSizeTertiaryDesign1',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Arrow Button Font Size Quaternary Design1',
		name: 'sliderArrowButtonFontSizeQuaternaryDesign1',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Arrow Button Font Size Quinary Design1',
		name: 'sliderArrowButtonFontSizeQuinaryDesign1',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Arrow Button Font Size Primay Design2',
		name: 'sliderArrowButtonFontSizePrimayDesign2',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Arrow Button Font Size Secondary Design2',
		name: 'sliderArrowButtonFontSizeSecondaryDesign2',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Arrow Button Font Size Tertiary Design2',
		name: 'sliderArrowButtonFontSizeTertiaryDesign2',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Arrow Button Font Size Quaternary Design2',
		name: 'sliderArrowButtonFontSizeQuaternaryDesign2',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Arrow Button Font Size Quinary Design2',
		name: 'sliderArrowButtonFontSizeQuinaryDesign2',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Arrow Button Font Size Primay Design3',
		name: 'sliderArrowButtonFontSizePrimayDesign3',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Arrow Button Font Size Secondary Design3',
		name: 'sliderArrowButtonFontSizeSecondaryDesign3',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Arrow Button Font Size Tertiary Design3',
		name: 'sliderArrowButtonFontSizeTertiaryDesign3',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Arrow Button Font Size Quaternary Design3',
		name: 'sliderArrowButtonFontSizeQuaternaryDesign3',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Arrow Button Font Size Quinary Design3',
		name: 'sliderArrowButtonFontSizeQuinaryDesign3',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Arrow Button Font Size Primay Design4',
		name: 'sliderArrowButtonFontSizePrimayDesign4',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Arrow Button Font Size Secondary Design4',
		name: 'sliderArrowButtonFontSizeSecondaryDesign4',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Arrow Button Font Size Tertiary Design4',
		name: 'sliderArrowButtonFontSizeTertiaryDesign4',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Arrow Button Font Size Quaternary Design4',
		name: 'sliderArrowButtonFontSizeQuaternaryDesign4',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Arrow Button Font Size Quinary Design4',
		name: 'sliderArrowButtonFontSizeQuinaryDesign4',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Arrow Button Border Primay Design1',
		name: 'sliderArrowButtonBorderPrimayDesign1',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Arrow Button Border Secondary Design1',
		name: 'sliderArrowButtonBorderSecondaryDesign1',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Arrow Button Border Tertiary Design1',
		name: 'sliderArrowButtonBorderTertiaryDesign1',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Arrow Button Border Quaternary Design1',
		name: 'sliderArrowButtonBorderQuaternaryDesign1',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Arrow Button Border Quinary Design1',
		name: 'sliderArrowButtonBorderQuinaryDesign1',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Arrow Button Border Primay Design2',
		name: 'sliderArrowButtonBorderPrimayDesign2',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Arrow Button Border Secondary Design2',
		name: 'sliderArrowButtonBorderSecondaryDesign2',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Arrow Button Border Tertiary Design2',
		name: 'sliderArrowButtonBorderTertiaryDesign2',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Arrow Button Border Quaternary Design2',
		name: 'sliderArrowButtonBorderQuaternaryDesign2',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Arrow Button Border Quinary Design2',
		name: 'sliderArrowButtonBorderQuinaryDesign2',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Arrow Button Border Primay Design3',
		name: 'sliderArrowButtonBorderPrimayDesign3',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Arrow Button Border Secondary Design3',
		name: 'sliderArrowButtonBorderSecondaryDesign3',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Arrow Button Border Tertiary Design3',
		name: 'sliderArrowButtonBorderTertiaryDesign3',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Arrow Button Border Quaternary Design3',
		name: 'sliderArrowButtonBorderQuaternaryDesign3',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Arrow Button Border Quinary Design3',
		name: 'sliderArrowButtonBorderQuinaryDesign3',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Arrow Button Border Primay Design4',
		name: 'sliderArrowButtonBorderPrimayDesign4',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Arrow Button Border Secondary Design4',
		name: 'sliderArrowButtonBorderSecondaryDesign4',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Arrow Button Border Tertiary Design4',
		name: 'sliderArrowButtonBorderTertiaryDesign4',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Arrow Button Border Quaternary Design4',
		name: 'sliderArrowButtonBorderQuaternaryDesign4',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Arrow Button Border Quinary Design4',
		name: 'sliderArrowButtonBorderQuinaryDesign4',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Arrow Button Border Color Primay Design1',
		name: 'sliderArrowButtonBorderColorPrimayDesign1',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Arrow Button Border Color Secondary Design1',
		name: 'sliderArrowButtonBorderColorSecondaryDesign1',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Arrow Button Border Color Tertiary Design1',
		name: 'sliderArrowButtonBorderColorTertiaryDesign1',
		defaultValue: '<borderColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Arrow Button Border Color Quaternary Design1',
		name: 'sliderArrowButtonBorderColorQuaternaryDesign1',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Arrow Button Border Color Quinary Design1',
		name: 'sliderArrowButtonBorderColorQuinaryDesign1',
		defaultValue: '<borderColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Arrow Button Border Color Primay Design2',
		name: 'sliderArrowButtonBorderColorPrimayDesign2',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Arrow Button Border Color Secondary Design2',
		name: 'sliderArrowButtonBorderColorSecondaryDesign2',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Arrow Button Border Color Tertiary Design2',
		name: 'sliderArrowButtonBorderColorTertiaryDesign2',
		defaultValue: '<borderColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Arrow Button Border Color Quaternary Design2',
		name: 'sliderArrowButtonBorderColorQuaternaryDesign2',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Arrow Button Border Color Quinary Design2',
		name: 'sliderArrowButtonBorderColorQuinaryDesign2',
		defaultValue: '<borderColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Arrow Button Border Color Primay Design3',
		name: 'sliderArrowButtonBorderColorPrimayDesign3',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Arrow Button Border Color Secondary Design3',
		name: 'sliderArrowButtonBorderColorSecondaryDesign3',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Arrow Button Border Color Tertiary Design3',
		name: 'sliderArrowButtonBorderColorTertiaryDesign3',
		defaultValue: '<borderColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Arrow Button Border Color Quaternary Design3',
		name: 'sliderArrowButtonBorderColorQuaternaryDesign3',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Arrow Button Border Color Quinary Design3',
		name: 'sliderArrowButtonBorderColorQuinaryDesign3',
		defaultValue: '<borderColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Arrow Button Border Color Primay Design4',
		name: 'sliderArrowButtonBorderColorPrimayDesign4',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Arrow Button Border Color Secondary Design4',
		name: 'sliderArrowButtonBorderColorSecondaryDesign4',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Arrow Button Border Color Tertiary Design4',
		name: 'sliderArrowButtonBorderColorTertiaryDesign4',
		defaultValue: '<borderColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Arrow Button Border Color Quaternary Design4',
		name: 'sliderArrowButtonBorderColorQuaternaryDesign4',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Arrow Button Border Color Quinary Design4',
		name: 'sliderArrowButtonBorderColorQuinaryDesign4',
		defaultValue: '<borderColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Arrow Button Border Radius Primay Design1',
		name: 'sliderArrowButtonBorderRadiusPrimayDesign1',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Arrow Button Border Radius Secondary Design1',
		name: 'sliderArrowButtonBorderRadiusSecondaryDesign1',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Arrow Button Border Radius Tertiary Design1',
		name: 'sliderArrowButtonBorderRadiusTertiaryDesign1',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Arrow Button Border Radius Quaternary Design1',
		name: 'sliderArrowButtonBorderRadiusQuaternaryDesign1',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Arrow Button Border Radius Quinary Design1',
		name: 'sliderArrowButtonBorderRadiusQuinaryDesign1',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Arrow Button Border Radius Primay Design2',
		name: 'sliderArrowButtonBorderRadiusPrimayDesign2',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Arrow Button Border Radius Secondary Design2',
		name: 'sliderArrowButtonBorderRadiusSecondaryDesign2',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Arrow Button Border Radius Tertiary Design2',
		name: 'sliderArrowButtonBorderRadiusTertiaryDesign2',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Arrow Button Border Radius Quaternary Design2',
		name: 'sliderArrowButtonBorderRadiusQuaternaryDesign2',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Arrow Button Border Radius Quinary Design2',
		name: 'sliderArrowButtonBorderRadiusQuinaryDesign2',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Arrow Button Border Radius Primay Design3',
		name: 'sliderArrowButtonBorderRadiusPrimayDesign3',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Arrow Button Border Radius Secondary Design3',
		name: 'sliderArrowButtonBorderRadiusSecondaryDesign3',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Arrow Button Border Radius Tertiary Design3',
		name: 'sliderArrowButtonBorderRadiusTertiaryDesign3',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Arrow Button Border Radius Quaternary Design3',
		name: 'sliderArrowButtonBorderRadiusQuaternaryDesign3',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Arrow Button Border Radius Quinary Design3',
		name: 'sliderArrowButtonBorderRadiusQuinaryDesign3',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Arrow Button Border Radius Primay Design4',
		name: 'sliderArrowButtonBorderRadiusPrimayDesign4',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Arrow Button Border Radius Secondary Design4',
		name: 'sliderArrowButtonBorderRadiusSecondaryDesign4',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Arrow Button Border Radius Tertiary Design4',
		name: 'sliderArrowButtonBorderRadiusTertiaryDesign4',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Arrow Button Border Radius Quaternary Design4',
		name: 'sliderArrowButtonBorderRadiusQuaternaryDesign4',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Arrow Button Border Radius Quinary Design4',
		name: 'sliderArrowButtonBorderRadiusQuinaryDesign4',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Arrow Button Padding Primay Design1',
		name: 'sliderArrowButtonPaddingPrimayDesign1',
		defaultValue: '0px 20px 0px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Arrow Button Padding Secondary Design1',
		name: 'sliderArrowButtonPaddingSecondaryDesign1',
		defaultValue: '20px 20px 20px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Arrow Button Padding Tertiary Design1',
		name: 'sliderArrowButtonPaddingTertiaryDesign1',
		defaultValue: '0px 20px 0px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Arrow Button Padding Quaternary Design1',
		name: 'sliderArrowButtonPaddingQuaternaryDesign1',
		defaultValue: '20px 20px 20px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Arrow Button Padding Quinary Design1',
		name: 'sliderArrowButtonPaddingQuinaryDesign1',
		defaultValue: '0px 20px 0px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Arrow Button Padding Primay Design2',
		name: 'sliderArrowButtonPaddingPrimayDesign2',
		defaultValue: '0px 20px 0px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Arrow Button Padding Secondary Design2',
		name: 'sliderArrowButtonPaddingSecondaryDesign2',
		defaultValue: '20px 20px 20px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Arrow Button Padding Tertiary Design2',
		name: 'sliderArrowButtonPaddingTertiaryDesign2',
		defaultValue: '0px 20px 0px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Arrow Button Padding Quaternary Design2',
		name: 'sliderArrowButtonPaddingQuaternaryDesign2',
		defaultValue: '20px 20px 20px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Arrow Button Padding Quinary Design2',
		name: 'sliderArrowButtonPaddingQuinaryDesign2',
		defaultValue: '0px 20px 0px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Arrow Button Padding Primay Design3',
		name: 'sliderArrowButtonPaddingPrimayDesign3',
		defaultValue: '0px 20px 0px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Arrow Button Padding Secondary Design3',
		name: 'sliderArrowButtonPaddingSecondaryDesign3',
		defaultValue: '20px 20px 20px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Arrow Button Padding Tertiary Design3',
		name: 'sliderArrowButtonPaddingTertiaryDesign3',
		defaultValue: '0px 20px 0px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Arrow Button Padding Quaternary Design3',
		name: 'sliderArrowButtonPaddingQuaternaryDesign3',
		defaultValue: '20px 20px 20px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Arrow Button Padding Quinary Design3',
		name: 'sliderArrowButtonPaddingQuinaryDesign3',
		defaultValue: '0px 20px 0px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Arrow Button Padding Primay Design4',
		name: 'sliderArrowButtonPaddingPrimayDesign4',
		defaultValue: '0px 20px 0px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Arrow Button Padding Secondary Design4',
		name: 'sliderArrowButtonPaddingSecondaryDesign4',
		defaultValue: '20px 20px 20px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Arrow Button Padding Tertiary Design4',
		name: 'sliderArrowButtonPaddingTertiaryDesign4',
		defaultValue: '0px 20px 0px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Arrow Button Padding Quaternary Design4',
		name: 'sliderArrowButtonPaddingQuaternaryDesign4',
		defaultValue: '20px 20px 20px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Arrow Button Padding Quinary Design4',
		name: 'sliderArrowButtonPaddingQuinaryDesign4',
		defaultValue: '0px 20px 0px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Arrow Button Box Shadow Primay Design1',
		name: 'sliderArrowButtonBoxShadowPrimayDesign1',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Arrow Button Box Shadow Secondary Design1',
		name: 'sliderArrowButtonBoxShadowSecondaryDesign1',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Arrow Button Box Shadow Tertiary Design1',
		name: 'sliderArrowButtonBoxShadowTertiaryDesign1',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Arrow Button Box Shadow Quaternary Design1',
		name: 'sliderArrowButtonBoxShadowQuaternaryDesign1',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Arrow Button Box Shadow Quinary Design1',
		name: 'sliderArrowButtonBoxShadowQuinaryDesign1',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Arrow Button Box Shadow Primay Design2',
		name: 'sliderArrowButtonBoxShadowPrimayDesign2',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Arrow Button Box Shadow Secondary Design2',
		name: 'sliderArrowButtonBoxShadowSecondaryDesign2',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Arrow Button Box Shadow Tertiary Design2',
		name: 'sliderArrowButtonBoxShadowTertiaryDesign2',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Arrow Button Box Shadow Quaternary Design2',
		name: 'sliderArrowButtonBoxShadowQuaternaryDesign2',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Arrow Button Box Shadow Quinary Design2',
		name: 'sliderArrowButtonBoxShadowQuinaryDesign2',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Arrow Button Box Shadow Primay Design3',
		name: 'sliderArrowButtonBoxShadowPrimayDesign3',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Arrow Button Box Shadow Secondary Design3',
		name: 'sliderArrowButtonBoxShadowSecondaryDesign3',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Arrow Button Box Shadow Tertiary Design3',
		name: 'sliderArrowButtonBoxShadowTertiaryDesign3',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Arrow Button Box Shadow Quaternary Design3',
		name: 'sliderArrowButtonBoxShadowQuaternaryDesign3',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Arrow Button Box Shadow Quinary Design3',
		name: 'sliderArrowButtonBoxShadowQuinaryDesign3',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Arrow Button Box Shadow Primay Design4',
		name: 'sliderArrowButtonBoxShadowPrimayDesign4',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Arrow Button Box Shadow Secondary Design4',
		name: 'sliderArrowButtonBoxShadowSecondaryDesign4',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Arrow Button Box Shadow Tertiary Design4',
		name: 'sliderArrowButtonBoxShadowTertiaryDesign4',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Arrow Button Box Shadow Quaternary Design4',
		name: 'sliderArrowButtonBoxShadowQuaternaryDesign4',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Arrow Button Box Shadow Quinary Design4',
		name: 'sliderArrowButtonBoxShadowQuinaryDesign4',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Arrow Button Background Primay Design1',
		name: 'sliderArrowButtonBackgroundPrimayDesign1',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Arrow Button Background Secondary Design1',
		name: 'sliderArrowButtonBackgroundSecondaryDesign1',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Arrow Button Background Tertiary Design1',
		name: 'sliderArrowButtonBackgroundTertiaryDesign1',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Arrow Button Background Quaternary Design1',
		name: 'sliderArrowButtonBackgroundQuaternaryDesign1',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Arrow Button Background Quinary Design1',
		name: 'sliderArrowButtonBackgroundQuinaryDesign1',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Arrow Button Background Primay Design2',
		name: 'sliderArrowButtonBackgroundPrimayDesign2',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Arrow Button Background Secondary Design2',
		name: 'sliderArrowButtonBackgroundSecondaryDesign2',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Arrow Button Background Tertiary Design2',
		name: 'sliderArrowButtonBackgroundTertiaryDesign2',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Arrow Button Background Quaternary Design2',
		name: 'sliderArrowButtonBackgroundQuaternaryDesign2',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Arrow Button Background Quinary Design2',
		name: 'sliderArrowButtonBackgroundQuinaryDesign2',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Arrow Button Background Primay Design3',
		name: 'sliderArrowButtonBackgroundPrimayDesign3',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Arrow Button Background Secondary Design3',
		name: 'sliderArrowButtonBackgroundSecondaryDesign3',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Arrow Button Background Tertiary Design3',
		name: 'sliderArrowButtonBackgroundTertiaryDesign3',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Arrow Button Background Quaternary Design3',
		name: 'sliderArrowButtonBackgroundQuaternaryDesign3',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Arrow Button Background Quinary Design3',
		name: 'sliderArrowButtonBackgroundQuinaryDesign3',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Arrow Button Background Primay Design4',
		name: 'sliderArrowButtonBackgroundPrimayDesign4',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Arrow Button Background Secondary Design4',
		name: 'sliderArrowButtonBackgroundSecondaryDesign4',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Arrow Button Background Tertiary Design4',
		name: 'sliderArrowButtonBackgroundTertiaryDesign4',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Arrow Button Background Quaternary Design4',
		name: 'sliderArrowButtonBackgroundQuaternaryDesign4',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Arrow Button Background Quinary Design4',
		name: 'sliderArrowButtonBackgroundQuinaryDesign4',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design1',
		displayName: 'Slider Arrow Button Scale Center Primay Design1',
		name: 'sliderArrowButtonScaleCenterPrimayDesign1',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design1 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design1',
		displayName: 'Slider Arrow Button Scale Center Secondary Design1',
		name: 'sliderArrowButtonScaleCenterSecondaryDesign1',
		defaultValue: 'scale(1.1) translateX(20px)',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design2 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design1',
		displayName: 'Slider Arrow Button Scale Center Tertiary Design1',
		name: 'sliderArrowButtonScaleCenterTertiaryDesign1',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design3 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design1',
		displayName: 'Slider Arrow Button Scale Center Quaternary Design1',
		name: 'sliderArrowButtonScaleCenterQuaternaryDesign1',
		defaultValue: 'scale(1.1) translateX(20px)',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design4 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design1',
		displayName: 'Slider Arrow Button Scale Center Quinary Design1',
		name: 'sliderArrowButtonScaleCenterQuinaryDesign1',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design5 .childElement.center',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design2',
		displayName: 'Slider Arrow Button Scale Center Primay Design2',
		name: 'sliderArrowButtonScaleCenterPrimayDesign2',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design1 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design2',
		displayName: 'Slider Arrow Button Scale Center Secondary Design2',
		name: 'sliderArrowButtonScaleCenterSecondaryDesign2',
		defaultValue: 'scale(1.1) translateX(20px)',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design2 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design2',
		displayName: 'Slider Arrow Button Scale Center Tertiary Design2',
		name: 'sliderArrowButtonScaleCenterTertiaryDesign2',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design3 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design2',
		displayName: 'Slider Arrow Button Scale Center Quaternary Design2',
		name: 'sliderArrowButtonScaleCenterQuaternaryDesign2',
		defaultValue: 'scale(1.1) translateX(20px)',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design4 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design2',
		displayName: 'Slider Arrow Button Scale Center Quinary Design2',
		name: 'sliderArrowButtonScaleCenterQuinaryDesign2',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design5 .childElement.center',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design3',
		displayName: 'Slider Arrow Button Scale Center Primay Design3',
		name: 'sliderArrowButtonScaleCenterPrimayDesign3',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design1 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design3',
		displayName: 'Slider Arrow Button Scale Center Secondary Design3',
		name: 'sliderArrowButtonScaleCenterSecondaryDesign3',
		defaultValue: 'scale(1.1) translateX(20px)',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design2 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design3',
		displayName: 'Slider Arrow Button Scale Center Tertiary Design3',
		name: 'sliderArrowButtonScaleCenterTertiaryDesign3',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design3 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design3',
		displayName: 'Slider Arrow Button Scale Center Quaternary Design3',
		name: 'sliderArrowButtonScaleCenterQuaternaryDesign3',
		defaultValue: 'scale(1.1) translateX(20px)',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design4 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design3',
		displayName: 'Slider Arrow Button Scale Center Quinary Design3',
		name: 'sliderArrowButtonScaleCenterQuinaryDesign3',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design5 .childElement.center',
		noPrefix: true,
	},

	{
		groupName: 'Primay Design4',
		displayName: 'Slider Arrow Button Scale Center Primay Design4',
		name: 'sliderArrowButtonScaleCenterPrimayDesign4',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design1 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Secondary Design4',
		displayName: 'Slider Arrow Button Scale Center Secondary Design4',
		name: 'sliderArrowButtonScaleCenterSecondaryDesign4',
		defaultValue: 'scale(1.1) translateX(20px)',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design2 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary Design4',
		displayName: 'Slider Arrow Button Scale Center Tertiary Design4',
		name: 'sliderArrowButtonScaleCenterTertiaryDesign4',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design3 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary Design4',
		displayName: 'Slider Arrow Button Scale Center Quaternary Design4',
		name: 'sliderArrowButtonScaleCenterQuaternaryDesign4',
		defaultValue: 'scale(1.1) translateX(20px)',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design4 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Quinary Design4',
		displayName: 'Slider Arrow Button Scale Center Quinary Design4',
		name: 'sliderArrowButtonScaleCenterQuinaryDesign4',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design5 .childElement.center',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
