import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'Font',
		displayName: 'Slider Font',
		name: 'sliderFont',
		defaultValue: '<primaryFont>',
		cssProperty: 'font',
		selector: '.comp.compSmallCarousel',
		noPrefix: true,
	},
	{
		groupName: 'Text Color',
		displayName: 'Slider Font Color',
		name: 'sliderFontColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Container Background Color Primay',
		name: 'sliderContainerBackgroundColorPrimay',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._primary',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Container Background Color Secondary',
		name: 'sliderContainerBackgroundColorSecondary',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Container Background Color Tertiary',
		name: 'sliderContainerBackgroundColorTertiary',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Container Background Color Quaternary',
		name: 'sliderContainerBackgroundColorQuaternary',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Container Background Color Quinary',
		name: 'sliderContainerBackgroundColorQuinary',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Container Padding Primay',
		name: 'sliderContainerPaddingPrimay',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._primary',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Container Padding Secondary',
		name: 'sliderContainerPaddingSecondary',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Container Padding Tertiary',
		name: 'sliderContainerPaddingTertiary',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Container Padding Quaternary',
		name: 'sliderContainerPaddingQuaternary',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Container Padding Quinary',
		name: 'sliderContainerPaddingQuinary',
		defaultValue: '20px 0px 20px 0px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Arrow Button Color Primay',
		name: 'sliderArrowButtonColorPrimay',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Arrow Button Color Secondary',
		name: 'sliderArrowButtonColorSecondary',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Arrow Button Color Tertiary',
		name: 'sliderArrowButtonColorTertiary',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Arrow Button Color Quaternary',
		name: 'sliderArrowButtonColorQuaternary',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Arrow Button Color Quinary',
		name: 'sliderArrowButtonColorQuinary',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Arrow Button BackgroundColor Primay',
		name: 'sliderArrowButtonBackgroundColorPrimay',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Arrow Button BackgroundColor Secondary',
		name: 'sliderArrowButtonBackgroundColorSecondary',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Arrow Button BackgroundColor Tertiary',
		name: 'sliderArrowButtonBackgroundColorTertiary',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Arrow Button BackgroundColor Quaternary',
		name: 'sliderArrowButtonBackgroundColorQuaternary',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Arrow Button BackgroundColor Quinary',
		name: 'sliderArrowButtonBackgroundColorQuinary',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Arrow Button Border Primay',
		name: 'sliderArrowButtonBorderPrimay',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Arrow Button Border Secondary',
		name: 'sliderArrowButtonBorderSecondary',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Arrow Button Border Tertiary',
		name: 'sliderArrowButtonBorderTertiary',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Arrow Button Border Quaternary',
		name: 'sliderArrowButtonBorderQuaternary',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Arrow Button Border Quinary',
		name: 'sliderArrowButtonBorderQuinary',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Arrow Button Border Color Primay',
		name: 'sliderArrowButtonBorderColorPrimay',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Arrow Button Border Color Secondary',
		name: 'sliderArrowButtonBorderColorSecondary',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Arrow Button Border Color Tertiary',
		name: 'sliderArrowButtonBorderColorTertiary',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Arrow Button Border Color Quaternary',
		name: 'sliderArrowButtonBorderColorQuaternary',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Arrow Button Border Color Quinary',
		name: 'sliderArrowButtonBorderColorQuinary',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Arrow Button Padding Primay',
		name: 'sliderArrowButtonPaddingPrimay',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Arrow Button Padding Secondary',
		name: 'sliderArrowButtonPaddingSecondary',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Arrow Button Padding Tertiary',
		name: 'sliderArrowButtonPaddingTertiary',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Arrow Button Padding Quaternary',
		name: 'sliderArrowButtonPaddingQuaternary',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Arrow Button Padding Quinary',
		name: 'sliderArrowButtonPaddingQuinary',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Arrow Button Border Radius Primay',
		name: 'sliderArrowButtonBorderRadiusPrimay',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Arrow Button Border Radius Secondary',
		name: 'sliderArrowButtonBorderRadiusSecondary',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Arrow Button Border Radius Tertiary',
		name: 'sliderArrowButtonBorderRadiusTertiary',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Arrow Button Border Radius Quaternary',
		name: 'sliderArrowButtonBorderRadiusQuaternary',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Arrow Button Border Radius Quinary',
		name: 'sliderArrowButtonBorderRadiusQuinary',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Arrow Button Font Size Primay',
		name: 'sliderArrowButtonFontSizePrimay',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design1 .button',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Arrow Button Font Size Secondary',
		name: 'sliderArrowButtonFontSizeSecondary',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design2 .button',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Arrow Button Font Size Tertiary',
		name: 'sliderArrowButtonFontSizeTertiary',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design3 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Arrow Button Font Size Quaternary',
		name: 'sliderArrowButtonFontSizeQuaternary',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design4 .button',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Arrow Button Font Size Quinary',
		name: 'sliderArrowButtonFontSizeQuinary',
		cssProperty: 'font-size',
		selector: '.comp.compSmallCarousel._design5 .button',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Arrow Button Border Primay',
		name: 'sliderArrowButtonBorderPrimay',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Arrow Button Border Secondary',
		name: 'sliderArrowButtonBorderSecondary',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Arrow Button Border Tertiary',
		name: 'sliderArrowButtonBorderTertiary',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Arrow Button Border Quaternary',
		name: 'sliderArrowButtonBorderQuaternary',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Arrow Button Border Quinary',
		name: 'sliderArrowButtonBorderQuinary',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Arrow Button Border Color Primay',
		name: 'sliderArrowButtonBorderColorPrimay',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Arrow Button Border Color Secondary',
		name: 'sliderArrowButtonBorderColorSecondary',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Arrow Button Border Color Tertiary',
		name: 'sliderArrowButtonBorderColorTertiary',
		defaultValue: '<borderColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Arrow Button Border Color Quaternary',
		name: 'sliderArrowButtonBorderColorQuaternary',
		defaultValue: 'transparent ',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Arrow Button Border Color Quinary',
		name: 'sliderArrowButtonBorderColorQuinary',
		defaultValue: '<borderColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Arrow Button Border Radius Primay',
		name: 'sliderArrowButtonBorderRadiusPrimay',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Arrow Button Border Radius Secondary',
		name: 'sliderArrowButtonBorderRadiusSecondary',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Arrow Button Border Radius Tertiary',
		name: 'sliderArrowButtonBorderRadiusTertiary',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Arrow Button Border Radius Quaternary',
		name: 'sliderArrowButtonBorderRadiusQuaternary',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Arrow Button Border Radius Quinary',
		name: 'sliderArrowButtonBorderRadiusQuinary',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Arrow Button Padding Primay',
		name: 'sliderArrowButtonPaddingPrimay',
		defaultValue: '0px 20px 0px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Arrow Button Padding Secondary',
		name: 'sliderArrowButtonPaddingSecondary',
		defaultValue: '20px 20px 20px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Arrow Button Padding Tertiary',
		name: 'sliderArrowButtonPaddingTertiary',
		defaultValue: '0px 20px 0px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Arrow Button Padding Quaternary',
		name: 'sliderArrowButtonPaddingQuaternary',
		defaultValue: '20px 20px 20px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Arrow Button Padding Quinary',
		name: 'sliderArrowButtonPaddingQuinary',
		defaultValue: '0px 20px 0px 20px ',
		cssProperty: 'padding',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Arrow Button Box Shadow Primay',
		name: 'sliderArrowButtonBoxShadowPrimay',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Arrow Button Box Shadow Secondary',
		name: 'sliderArrowButtonBoxShadowSecondary',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Arrow Button Box Shadow Tertiary',
		name: 'sliderArrowButtonBoxShadowTertiary',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Arrow Button Box Shadow Quaternary',
		name: 'sliderArrowButtonBoxShadowQuaternary',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Arrow Button Box Shadow Quinary',
		name: 'sliderArrowButtonBoxShadowQuinary',
		cssProperty: 'box-shadow',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Arrow Button Background Primay',
		name: 'sliderArrowButtonBackgroundPrimay',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design1 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Arrow Button Background Secondary',
		name: 'sliderArrowButtonBackgroundSecondary',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design2 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Arrow Button Background Tertiary',
		name: 'sliderArrowButtonBackgroundTertiary',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design3 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Arrow Button Background Quaternary',
		name: 'sliderArrowButtonBackgroundQuaternary',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design4 .childElement',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Arrow Button Background Quinary',
		name: 'sliderArrowButtonBackgroundQuinary',
		cssProperty: 'background',
		selector: '.comp.compSmallCarousel._design5 .childElement',
		noPrefix: true,
	},

	{
		groupName: 'Primay',
		displayName: 'Slider Arrow Button Scale Center Primay',
		name: 'sliderArrowButtonScaleCenterPrimay',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design1 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Secondary',
		displayName: 'Slider Arrow Button Scale Center Secondary',
		name: 'sliderArrowButtonScaleCenterSecondary',
		defaultValue: 'scale(1.1) translateX(20px)',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design2 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Tertiary',
		displayName: 'Slider Arrow Button Scale Center Tertiary',
		name: 'sliderArrowButtonScaleCenterTertiary',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design3 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Quaternary',
		displayName: 'Slider Arrow Button Scale Center Quaternary',
		name: 'sliderArrowButtonScaleCenterQuaternary',
		defaultValue: 'scale(1.1) translateX(20px)',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design4 .childElement.center',
		noPrefix: true,
	},
	{
		groupName: 'Quinary',
		displayName: 'Slider Arrow Button Scale Center Quinary',
		name: 'sliderArrowButtonScaleCenterQuinary',
		cssProperty: 'transform',
		selector: '.comp.compSmallCarousel._design5 .childElement.center',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
