import {
	SCHEMA_BOOL_COMP_PROP,
	SCHEMA_STRING_COMP_PROP,
	SCHEMA_NUM_COMP_PROP,
} from '../../constants';
import {
	ComponentPropertyDefinition,
	ComponentPropertyEditor,
	ComponentPropertyGroup,
	ComponentStylePropertyDefinition,
} from '../../types/common';
import { COMMON_COMPONENT_PROPERTIES, COMPONENT_STYLE_GROUP_PROPERTIES } from '../util/properties';

const propertiesDefinition: Array<ComponentPropertyDefinition> = [
	COMMON_COMPONENT_PROPERTIES.onClick,
	{
		name: 'src',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Default image source.',
		description: 'Default image source.',
		editor: ComponentPropertyEditor.IMAGE,
		group: ComponentPropertyGroup.BASIC,
	},
	{
		name: 'src2',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Image source for Tablet landscape screen',
		description: 'source of the image for Tablet landscape screen.',
		editor: ComponentPropertyEditor.IMAGE,
		group: ComponentPropertyGroup.BASIC,
	},
	{
		name: 'src3',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Image source for Tablet portrait screen',
		description: 'source of the image for Tablet portrait screen.',
		editor: ComponentPropertyEditor.IMAGE,
		group: ComponentPropertyGroup.BASIC,
	},
	{
		name: 'src4',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Image source for Mobile landscape screen',
		description: 'source of the image for Mobile landscape screen.',
		editor: ComponentPropertyEditor.IMAGE,
		group: ComponentPropertyGroup.BASIC,
	},
	{
		name: 'src5',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Image source for Mobile portrait screen',
		description: 'source of the image for Mobile portrait screen.',
		editor: ComponentPropertyEditor.IMAGE,
		group: ComponentPropertyGroup.BASIC,
	},
	{
		name: 'alt',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Alt Text',
		description: 'Text describing the image.',
		defaultValue: '',
		group: ComponentPropertyGroup.BASIC,
	},
	{
		name: 'enhancementType',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Enhancement Type',
		description: 'Type of image enhancement to apply',
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: 'none',
		enumValues: [
			{ name: 'none', displayName: 'None' },
			{ name: 'zoomPreview', displayName: 'Zoom Preview' },
			{ name: 'magnification', displayName: 'Magnification' },
		],
	},
	{
		name: 'zoomPreviewVisible',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Always Show Zoom Preview',
		description: 'Whether to always show zoom preview or only on hover',
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: false,
	},
	{
		name: 'zoomFactor',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'Zoom Factor',
		description: 'Magnification level for zoom preview',
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: 2,
	},
	{
		name: 'magnifierSize',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'Magnifier Size',
		description: 'Size of the magnifier in pixels',
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: 150,
	},
	{
		name: 'magnificationFactor',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'Magnification Factor',
		description: 'Magnification level for the magnifier',
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: 2,
	},
	{
		name: 'fallBackImg',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Fallback image',
		description: 'FallBack image will be dispalyed when main image is broken.',
		group: ComponentPropertyGroup.ADVANCED,
		editor: ComponentPropertyEditor.IMAGE,
	},
	{
		name: 'imgLazyLoading',
		schema: SCHEMA_BOOL_COMP_PROP,
		displayName: 'Image lazy loading',
		description: 'Image lazy loading',
		defaultValue: false,
		group: ComponentPropertyGroup.ADVANCED,
	},
	{
		name: 'stopPropagation',
		schema: SCHEMA_BOOL_COMP_PROP,
		group: ComponentPropertyGroup.ADVANCED,
		displayName: 'Stop propagation of click event',
		description:
			'Stop propagation of click event which will not trigger the container click event.',
		defaultValue: false,
	},
	{
		name: 'preventDefault',
		schema: SCHEMA_BOOL_COMP_PROP,
		group: ComponentPropertyGroup.ADVANCED,
		displayName: 'Prevent default of click event',
		description: 'Prevent default of click event.',
		defaultValue: false,
	},
	{
		name: 'previewPlacement',
		schema: SCHEMA_STRING_COMP_PROP,
		displayName: 'Preview Placement',
		description: 'Position of the zoom preview window',
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: 'right',
		enumValues: [
			{ name: 'right', displayName: 'Right' },
			{ name: 'left', displayName: 'Left' },
			{ name: 'top', displayName: 'Top' },
			{ name: 'bottom', displayName: 'Bottom' },
		],
	},
	{
		name: 'previewWidth',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'Preview Width',
		description: 'Width of the zoom preview window in pixels',
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: 300,
	},
	{
		name: 'previewHeight',
		schema: SCHEMA_NUM_COMP_PROP,
		displayName: 'Preview Height',
		description: 'Height of the zoom preview window in pixels',
		group: ComponentPropertyGroup.ADVANCED,
		defaultValue: 300,
	},
	COMMON_COMPONENT_PROPERTIES.visibility,
	{
		name: 'useObjectToRender',
		schema: SCHEMA_BOOL_COMP_PROP,
		group: ComponentPropertyGroup.ADVANCED,
		displayName: 'Use Object to render (SVG only)',
		defaultValue: false,
	},
];

const stylePropertiesDefinition: ComponentStylePropertyDefinition = {
	'': [
		COMPONENT_STYLE_GROUP_PROPERTIES.layout.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.position.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.effects.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.image.type,
	],
	image: [
		COMPONENT_STYLE_GROUP_PROPERTIES.image.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.layout.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.position.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.effects.type,
	],
	zoomPreview: [
		COMPONENT_STYLE_GROUP_PROPERTIES.layout.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.position.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.spacing.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.size.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.effects.type,
	],
	magnifier: [
		COMPONENT_STYLE_GROUP_PROPERTIES.border.type,
		COMPONENT_STYLE_GROUP_PROPERTIES.effects.type,
	],
};

export { propertiesDefinition, stylePropertiesDefinition };
