import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		name: 'design1Padding',
		cssProperty: 'padding',
		displayName: 'Design 1 Padding',
		description: 'Design 1 Padding',
		defaultValue: '5px',
		noPrefix: true,
		selector: '.comp.compTable._design1',
	},
	{
		name: 'design3Padding',
		cssProperty: 'padding',
		displayName: 'Design 3 Padding',
		description: 'Design 3 Padding',
		defaultValue: '5px',
		noPrefix: true,
		selector: '.comp.compTable._design3',
	},
	{
		name: 'design5Padding',
		cssProperty: 'padding',
		displayName: 'Design 5 Padding',
		description: 'Design 5 Padding',
		defaultValue: '5px',
		noPrefix: true,
		selector: '.comp.compTable._design5',
	},
	{
		name: 'design7Padding',
		cssProperty: 'padding',
		displayName: 'Design 7 Padding',
		description: 'Design 7 Padding',
		defaultValue: '5px',
		noPrefix: true,
		selector: '.comp.compTable._design7',
	},
	{
		name: 'design9Padding',
		cssProperty: 'padding',
		displayName: 'Design 9 Padding',
		description: 'Design 9 Padding',
		defaultValue: '5px',
		noPrefix: true,
		selector: '.comp.compTable._design9',
	},

	{
		name: 'design2Padding',
		cssProperty: 'padding',
		displayName: 'Design 2 Padding',
		description: 'Design 2 Padding',
		defaultValue: '10px',
		noPrefix: true,
		selector: '.comp.compTable._design2',
	},
	{
		name: 'design4Padding',
		cssProperty: 'padding',
		displayName: 'Design 4 Padding',
		description: 'Design 4 Padding',
		defaultValue: '0px',
		noPrefix: true,
		selector: '.comp.compTable._design4',
	},
	{
		name: 'design6Padding',
		cssProperty: 'padding',
		displayName: 'Design 6 Padding',
		description: 'Design 6 Padding',
		defaultValue: '0px',
		noPrefix: true,
		selector: '.comp.compTable._design6',
	},
	{
		name: 'design8Padding',
		cssProperty: 'padding',
		displayName: 'Design 8 Padding',
		description: 'Design 8 Padding',
		defaultValue: '0px',
		noPrefix: true,
		selector: '.comp.compTable._design8',
	},
	{
		name: 'design10Padding',
		cssProperty: 'padding',
		displayName: 'Design 10 Padding',
		description: 'Design 10 Padding',
		defaultValue: '0px',
		noPrefix: true,
		selector: '.comp.compTable._design10',
	},

	{
		name: 'design1BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 1 Background Color',
		description: 'Design 1 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design1',
	},
	{
		name: 'design3BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 3 Background Color',
		description: 'Design 3 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design3',
	},
	{
		name: 'design5BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 5 Background Color',
		description: 'Design 5 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design5',
	},
	{
		name: 'design7BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 7 Background Color',
		description: 'Design 7 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design7',
	},
	{
		name: 'design9BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 9 Background Color',
		description: 'Design 9 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design9',
	},

	{
		name: 'design2BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 2 Background Color',
		description: 'Design 2 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design2',
	},
	{
		name: 'design4BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 4 Background Color',
		description: 'Design 4 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design4',
	},
	{
		name: 'design6BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 6 Background Color',
		description: 'Design 6 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design6',
	},
	{
		name: 'design8BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 8 Background Color',
		description: 'Design 8 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design8',
	},
	{
		name: 'design10BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 10 Background Color',
		description: 'Design 10 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design10',
	},

	{
		name: 'design1BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 1 Border Radius',
		description: 'Design 1 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design1',
	},
	{
		name: 'design3BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 3 Border Radius',
		description: 'Design 3 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design3',
	},
	{
		name: 'design5BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 5 Border Radius',
		description: 'Design 5 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design5',
	},
	{
		name: 'design7BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 7 Border Radius',
		description: 'Design 7 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design7',
	},
	{
		name: 'design9BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 9 Border Radius',
		description: 'Design 9 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design9',
	},

	{
		name: 'design2BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 2 Border Radius',
		description: 'Design 2 Border Radius',
		defaultValue: '10px',
		noPrefix: true,
		selector: '.comp.compTable._design2',
	},
	{
		name: 'design4BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 4 Border Radius',
		description: 'Design 4 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design4',
	},
	{
		name: 'design6BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 6 Border Radius',
		description: 'Design 6 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design6',
	},
	{
		name: 'design8BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 8 Border Radius',
		description: 'Design 8 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design8',
	},
	{
		name: 'design10BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 10 Border Radius',
		description: 'Design 10 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design10',
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
