import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		name: 'design1Padding',
		cssProperty: 'padding',
		displayName: 'Design 1 Padding',
		description: 'Design 1 Padding',
		defaultValue: '5px',
		noPrefix: true,
		selector: '.comp.compTable._design1',
	},
	{
		name: 'design3Padding',
		cssProperty: 'padding',
		displayName: 'Design 3 Padding',
		description: 'Design 3 Padding',
		defaultValue: '5px',
		noPrefix: true,
		selector: '.comp.compTable._design3',
	},
	{
		name: 'design5Padding',
		cssProperty: 'padding',
		displayName: 'Design 5 Padding',
		description: 'Design 5 Padding',
		defaultValue: '5px',
		noPrefix: true,
		selector: '.comp.compTable._design5',
	},
	{
		name: 'design7Padding',
		cssProperty: 'padding',
		displayName: 'Design 7 Padding',
		description: 'Design 7 Padding',
		defaultValue: '5px',
		noPrefix: true,
		selector: '.comp.compTable._design7',
	},
	{
		name: 'design9Padding',
		cssProperty: 'padding',
		displayName: 'Design 9 Padding',
		description: 'Design 9 Padding',
		defaultValue: '5px',
		noPrefix: true,
		selector: '.comp.compTable._design9',
	},

	{
		name: 'design2Padding',
		cssProperty: 'padding',
		displayName: 'Design 2 Padding',
		description: 'Design 2 Padding',
		defaultValue: '10px',
		noPrefix: true,
		selector: '.comp.compTable._design2',
	},
	{
		name: 'design4Padding',
		cssProperty: 'padding',
		displayName: 'Design 4 Padding',
		description: 'Design 4 Padding',
		defaultValue: '0px',
		noPrefix: true,
		selector: '.comp.compTable._design4',
	},
	{
		name: 'design6Padding',
		cssProperty: 'padding',
		displayName: 'Design 6 Padding',
		description: 'Design 6 Padding',
		defaultValue: '0px',
		noPrefix: true,
		selector: '.comp.compTable._design6',
	},
	{
		name: 'design8Padding',
		cssProperty: 'padding',
		displayName: 'Design 8 Padding',
		description: 'Design 8 Padding',
		defaultValue: '0px',
		noPrefix: true,
		selector: '.comp.compTable._design8',
	},
	{
		name: 'design10Padding',
		cssProperty: 'padding',
		displayName: 'Design 10 Padding',
		description: 'Design 10 Padding',
		defaultValue: '0px',
		noPrefix: true,
		selector: '.comp.compTable._design10',
	},

	{
		name: 'design1BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 1 Background Color',
		description: 'Design 1 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design1',
	},
	{
		name: 'design3BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 3 Background Color',
		description: 'Design 3 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design3',
	},
	{
		name: 'design5BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 5 Background Color',
		description: 'Design 5 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design5',
	},
	{
		name: 'design7BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 7 Background Color',
		description: 'Design 7 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design7',
	},
	{
		name: 'design9BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 9 Background Color',
		description: 'Design 9 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design9',
	},

	{
		name: 'design2BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 2 Background Color',
		description: 'Design 2 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design2',
	},
	{
		name: 'design4BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 4 Background Color',
		description: 'Design 4 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design4',
	},
	{
		name: 'design6BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 6 Background Color',
		description: 'Design 6 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design6',
	},
	{
		name: 'design8BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 8 Background Color',
		description: 'Design 8 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design8',
	},
	{
		name: 'design10BackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 10 Background Color',
		description: 'Design 10 Background Color',
		defaultValue: '#FFFFFF',
		noPrefix: true,
		selector: '.comp.compTable._design10',
	},

	{
		name: 'design1BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 1 Border Radius',
		description: 'Design 1 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design1',
	},
	{
		name: 'design3BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 3 Border Radius',
		description: 'Design 3 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design3',
	},
	{
		name: 'design5BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 5 Border Radius',
		description: 'Design 5 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design5',
	},
	{
		name: 'design7BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 7 Border Radius',
		description: 'Design 7 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design7',
	},
	{
		name: 'design9BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 9 Border Radius',
		description: 'Design 9 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design9',
	},

	{
		name: 'design2BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 2 Border Radius',
		description: 'Design 2 Border Radius',
		defaultValue: '10px',
		noPrefix: true,
		selector: '.comp.compTable._design2',
	},
	{
		name: 'design4BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 4 Border Radius',
		description: 'Design 4 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design4',
	},
	{
		name: 'design6BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 6 Border Radius',
		description: 'Design 6 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design6',
	},
	{
		name: 'design8BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 8 Border Radius',
		description: 'Design 8 Border Radius',

		noPrefix: true,
		selector: '.comp.compTable._design8',
	},
	{
		name: 'design10BorderRadius',
		cssProperty: 'border-radius',
		displayName: 'Design 10 Border Radius',
		description: 'Design 10 Border Radius',
		noPrefix: true,
		selector: '.comp.compTable._design10',
	},
	{
		name: 'paginationSelectedBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Pagination Selected BG Color',
		description: 'Pagination Selected BG Color',
		defaultValue: '<mainFontColor>',
		selector: '._tablePagination ._selected',
	},
	{
		name: 'paginationSelectedColor',
		cssProperty: 'color',
		displayName: 'Pagination Selected Color',
		description: 'Pagination Selected Color',
		defaultValue: '<lightFontColor>',
		selector: '._tablePagination ._selected',
	},
	{
		name: 'paginationSeperatorColor',
		cssProperty: 'color',
		displayName: 'Pagination Seperator Color',
		description: 'Pagination Seperator Color',
		defaultValue: '<lightFontColor>',
	},
	{
		name: 'paginationMargin',
		cssProperty: 'margin',
		displayName: 'Pagination Margin',
		description: 'Pagination Margin',
		defaultValue: '10px 0px 0px 0px',
		selector: '._tablePagination',
	},
	{
		groupName: 'Pagination Border ',
		displayName: 'Pagination Border Default Design1 Primary',
		name: 'paginationBorderDefaultDesign1Primary',
		defaultValue: '1px solid #DFE3E8',
		description: 'Pagination Border Default Design1 Primary',
		cssProperty: 'border',
		selector: '._tablePagination._design1._primary ._pageNumber',
	},
	{
		groupName: 'Pagination Border ',
		displayName: 'Pagination Border Default Design1 Secondary',
		name: 'paginationBorderDefaultDesign1Secondary',
		defaultValue: '1px solid #DFE3E8',
		description: 'Pagination Border Default Design1 Secondary',
		cssProperty: 'border',
		selector: '._tablePagination._design1._secondary ._pageNumber',
	},
	{
		groupName: 'Pagination Border ',
		displayName: 'Pagination Border Default Design1 Tertiary',
		name: 'paginationBorderDefaultDesign1Tertiary',
		defaultValue: '1px solid #DFE3E8',
		description: 'Pagination Border Default Design1 Tertiary',
		cssProperty: 'border',
		selector: '._tablePagination._design1._tertiary ._pageNumber',
	},
	{
		groupName: 'Pagination Border ',
		displayName: 'Pagination Border Default Design1 Quaternary',
		name: 'paginationBorderDefaultDesign1Quaternary',
		defaultValue: '1px solid #DFE3E8',
		description: 'Pagination Border Default Design1 Quaternary',
		cssProperty: 'border',
		selector: '._tablePagination._design1._quaternary ._pageNumber',
	},
	{
		groupName: 'Pagination Border ',
		displayName: 'Pagination Border Default Design1 Quinary',
		name: 'paginationBorderDefaultDesign1Quinary',
		defaultValue: '1px solid #DFE3E8',
		description: 'Pagination Border Default Design1 Quinary',
		cssProperty: 'border',
		selector: '._tablePagination._design1._quinary ._pageNumber',
	},

	{
		groupName: 'Pagination Border Radius',
		displayName: 'Pagination Border Radius Default Design1 Primary',
		name: 'paginationBorderRadiusDefaultDesign1Primary',
		defaultValue: '4px',
		description: 'Pagination Border Radius Default Design1 Primary',
		cssProperty: 'border-radius',
		selector: '._tablePagination._design1._primary ._pageNumber',
	},
	{
		groupName: 'Pagination Border Radius',
		displayName: 'Pagination Border Radius Default Design1 Secondary',
		name: 'paginationBorderRadiusDefaultDesign1Secondary',
		defaultValue: '4px',
		description: 'Pagination Border Radius Default Design1 Secondary',
		cssProperty: 'border-radius',
		selector: '._tablePagination._design1._secondary ._pageNumber',
	},
	{
		groupName: 'Pagination Border Radius',
		displayName: 'Pagination Border Radius Default Design1 Tertiary',
		name: 'paginationBorderRadiusDefaultDesign1Tertiary',
		defaultValue: '4px',
		description: 'Pagination Border Radius Default Design1 Tertiary',
		cssProperty: 'border-radius',
		selector: '._tablePagination._design1._tertiary ._pageNumber',
	},
	{
		groupName: 'Pagination Border Radius',
		displayName: 'Pagination Border Radius Default Design1 Quaternary',
		name: 'paginationBorderRadiusDefaultDesign1Quaternary',
		defaultValue: '4px',
		description: 'Pagination Border Radius Default Design1 Quaternary',
		cssProperty: 'border-radius',
		selector: '._tablePagination._design1._quaternary ._pageNumber',
	},
	{
		groupName: 'Pagination Border Radius',
		displayName: 'Pagination Border Radius Default Design1 Quinary',
		name: 'paginationBorderRadiusDefaultDesign1Quinary',
		defaultValue: '4px',
		description: 'Pagination Border Radius Default Design1 Quinary',
		cssProperty: 'border-radius',
		selector: '._tablePagination._design1._quinary ._pageNumber',
	},
	{
		groupName: 'Pagination Selected Border ',
		displayName: 'Pagination Selected Border Default Design1 Primary',
		name: 'paginationSelectedBorderDefaultDesign1Primary',
		defaultValue: '1px solid <fontColorThree>',
		description: 'Pagination Border Default Design1 Primary',
		cssProperty: 'border',
		selector: '._tablePagination._design1._primary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Border ',
		displayName: 'Pagination Selected Border Default Design1 Secondary',
		name: 'paginationSelectedBorderDefaultDesign1Secondary',
		defaultValue: '1px solid <fontColorFour>',
		description: 'Pagination Border Default Design1 Secondary',
		cssProperty: 'border',
		selector: '._tablePagination._design1._secondary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Border ',
		displayName: 'Pagination Selected Border Default Design1 Tertiary',
		name: 'paginationSelectedBorderDefaultDesign1Tertiary',
		defaultValue: '1px solid <fontColorFive>',
		description: 'Pagination Border Default Design1 Tertiary',
		cssProperty: 'border',
		selector: '._tablePagination._design1._tertiary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Border ',
		displayName: 'Pagination Selected Border Default Design1 Quaternary',
		name: 'paginationSelectedBorderDefaultDesign1Quaternary',
		defaultValue: '1px solid <fontColorNine>',
		description: 'Pagination Border Default Design1 Quaternary',
		cssProperty: 'border',
		selector: '._tablePagination._design1._quaternary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Border ',
		displayName: 'Pagination Selected Border Default Design1 Quinary',
		name: 'paginationSelectedBorderDefaultDesign1Quinary',
		defaultValue: '1px solid <fontColorSeven>',
		description: 'Pagination Border Default Design1 Quinary',
		cssProperty: 'border',
		selector: '._tablePagination._design1._quinary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color ',
		displayName: 'Pagination Selected Color Default Design1 Primary',
		name: 'paginationSelectedColorDefaultDesign1Primary',
		defaultValue: '<fontColorThree>',
		description: 'Pagination Color Default Design1 Primary',
		cssProperty: 'color',
		selector: '._tablePagination._design1._primary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color ',
		displayName: 'Pagination Selected Color Default Design1 Secondary',
		name: 'paginationSelectedColorDefaultDesign1Secondary',
		defaultValue: '<fontColorFour>',
		description: 'Pagination Color Default Design1 Secondary',
		cssProperty: 'color',
		selector: '._tablePagination._design1._secondary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color ',
		displayName: 'Pagination Selected Color Default Design1 Tertiary',
		name: 'paginationSelectedColorDefaultDesign1Tertiary',
		defaultValue: '<fontColorFive>',
		description: 'Pagination Color Default Design1 Tertiary',
		cssProperty: 'color',
		selector: '._tablePagination._design1._tertiary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color ',
		displayName: 'Pagination Selected Color Default Design1 Quaternary',
		name: 'paginationSelectedColorDefaultDesign1Quaternary',
		defaultValue: '<fontColorNine>',
		description: 'Pagination Color Default Design1 Quaternary',
		cssProperty: 'color',
		selector: '._tablePagination._design1._quaternary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color ',
		displayName: 'Pagination Selected Color Default Design1 Quinary',
		name: 'paginationSelectedColorDefaultDesign1Quinary',
		defaultValue: '<fontColorSeven>',
		description: 'Pagination Color Default Design1 Quinary',
		cssProperty: 'color',
		selector: '._tablePagination._design1._quinary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Border ',
		displayName: 'Pagination Border Default Design2 Primary',
		name: 'paginationBorderDefaultDesign2Primary',
		defaultValue: '1px solid #DFE3E8',
		description: 'Pagination Border Default Design2 Primary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._primary ._pageNumber',
	},
	{
		groupName: 'Pagination Border ',
		displayName: 'Pagination Border Default Design2 Secondary',
		name: 'paginationBorderDefaultDesign2Secondary',
		defaultValue: '1px solid #DFE3E8',
		description: 'Pagination Border Default Design2 Secondary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._secondary ._pageNumber',
	},
	{
		groupName: 'Pagination Border ',
		displayName: 'Pagination Border Default Design2 Tertiary',
		name: 'paginationBorderDefaultDesign2Tertiary',
		defaultValue: '1px solid #DFE3E8',
		description: 'Pagination Border Default Design2 Tertiary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._tertiary ._pageNumber',
	},
	{
		groupName: 'Pagination Border ',
		displayName: 'Pagination Border Default Design2 Quaternary',
		name: 'paginationBorderDefaultDesign2Quaternary',
		defaultValue: '1px solid #DFE3E8',
		description: 'Pagination Border Default Design2 Quaternary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._quaternary ._pageNumber',
	},
	{
		groupName: 'Pagination Border ',
		displayName: 'Pagination Border Default Design2 Quinary',
		name: 'paginationBorderDefaultDesign2Quinary',
		defaultValue: '1px solid #DFE3E8',
		description: 'Pagination Border Default Design2 Quinary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._quinary ._pageNumber',
	},

	{
		groupName: 'Pagination Border Radius',
		displayName: 'Pagination Border Radius Default Design2 Primary',
		name: 'paginationBorderRadiusDefaultDesign2Primary',
		defaultValue: '100px',
		description: 'Pagination Border Radius Default Design2 Primary',
		cssProperty: 'border-radius',
		selector: '._tablePagination._design2._primary ._pageNumber',
	},
	{
		groupName: 'Pagination Border Radius',
		displayName: 'Pagination Border Radius Default Design2 Secondary',
		name: 'paginationBorderRadiusDefaultDesign2Secondary',
		defaultValue: '100px',
		description: 'Pagination Border Radius Default Design2 Secondary',
		cssProperty: 'border-radius',
		selector: '._tablePagination._design2._secondary ._pageNumber',
	},
	{
		groupName: 'Pagination Border Radius',
		displayName: 'Pagination Border Radius Default Design2 Tertiary',
		name: 'paginationBorderRadiusDefaultDesign2Tertiary',
		defaultValue: '100px',
		description: 'Pagination Border Radius Default Design2 Tertiary',
		cssProperty: 'border-radius',
		selector: '._tablePagination._design2._tertiary ._pageNumber',
	},
	{
		groupName: 'Pagination Border Radius',
		displayName: 'Pagination Border Radius Default Design2 Quaternary',
		name: 'paginationBorderRadiusDefaultDesign2Quaternary',
		defaultValue: '100px',
		description: 'Pagination Border Radius Default Design2 Quaternary',
		cssProperty: 'border-radius',
		selector: '._tablePagination._design2._quaternary ._pageNumber',
	},
	{
		groupName: 'Pagination Border Radius',
		displayName: 'Pagination Border Radius Default Design2 Quinary',
		name: 'paginationBorderRadiusDefaultDesign2Quinary',
		defaultValue: '100px',
		description: 'Pagination Border Radius Default Design2 Quinary',
		cssProperty: 'border-radius',
		selector: '._tablePagination._design2._quinary ._pageNumber',
	},
	{
		groupName: 'Pagination Selected Border',
		displayName: 'Pagination Selected Border Default Design2 Primary',
		name: 'paginationSelectedBorderDefaultDesign2Primary',
		defaultValue: '1px solid <fontColorThree>',
		description: 'Pagination Border Default Design2 Primary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._primary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Border',
		displayName: 'Pagination Selected Border Default Design2 Secondary',
		name: 'paginationSelectedBorderDefaultDesign2Secondary',
		defaultValue: '1px solid <fontColorFour>',
		description: 'Pagination Border Default Design2 Secondary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._secondary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Border',
		displayName: 'Pagination Selected Border Default Design2 Tertiary',
		name: 'paginationSelectedBorderDefaultDesign2Tertiary',
		defaultValue: '1px solid <fontColorFive>',
		description: 'Pagination Border Default Design2 Tertiary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._tertiary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Border',
		displayName: 'Pagination Selected Border Default Design2 Quaternary',
		name: 'paginationSelectedBorderDefaultDesign2Quaternary',
		defaultValue: '1px solid <fontColorNine>',
		description: 'Pagination Border Default Design2 Quaternary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._quaternary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Border',
		displayName: 'Pagination Selected Border Default Design2 Quinary',
		name: 'paginationSelectedBorderDefaultDesign2Quinary',
		defaultValue: '1px solid <fontColorSeven>',
		description: 'Pagination Border Default Design2 Quinary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._quinary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Color Default Design2 Primary',
		name: 'paginationSelectedColorDefaultDesign2Primary',
		defaultValue: '<fontColorThree>',
		description: 'Pagination Color Default Design2 Primary',
		cssProperty: 'color',
		selector: '._tablePagination._design2._primary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Color Default Design2 Secondary',
		name: 'paginationSelectedColorDefaultDesign2Secondary',
		defaultValue: '<fontColorFour>',
		description: 'Pagination Color Default Design2 Secondary',
		cssProperty: 'color',
		selector: '._tablePagination._design2._secondary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Color Default Design2 Tertiary',
		name: 'paginationSelectedColorDefaultDesign2Tertiary',
		defaultValue: '<fontColorFive>',
		description: 'Pagination Color Default Design2 Tertiary',
		cssProperty: 'color',
		selector: '._tablePagination._design2._tertiary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Color Default Design2 Quaternary',
		name: 'paginationSelectedColorDefaultDesign2Quaternary',
		defaultValue: '<fontColorNine>',
		description: 'Pagination Color Default Design2 Quaternary',
		cssProperty: 'color',
		selector: '._tablePagination._design2._quaternary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Color Default Design2 Quinary',
		name: 'paginationSelectedColorDefaultDesign2Quinary',
		defaultValue: '<fontColorSeven>',
		description: 'Pagination Color Default Design2 Quinary',
		cssProperty: 'color',
		selector: '._tablePagination._design2._quinary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Border ',
		displayName: 'Pagination Border Default Design2 Primary',
		name: 'paginationBorderDefaultDesign2Primary',
		defaultValue: '1px solid #DFE3E8',
		description: 'Pagination Border Default Design2 Primary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._primary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Border ',
		displayName: 'Pagination Border Default Design2 Secondary',
		name: 'paginationBorderDefaultDesign2Secondary',
		defaultValue: '1px solid #DFE3E8',
		description: 'Pagination Border Default Design2 Secondary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._secondary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Border ',
		displayName: 'Pagination Border Default Design2 Tertiary',
		name: 'paginationBorderDefaultDesign2Tertiary',
		defaultValue: '1px solid #DFE3E8',
		description: 'Pagination Border Default Design2 Tertiary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._tertiary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Border ',
		displayName: 'Pagination Border Default Design2 Quaternary',
		name: 'paginationBorderDefaultDesign2Quaternary',
		defaultValue: '1px solid #DFE3E8',
		description: 'Pagination Border Default Design2 Quaternary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._quaternary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Border ',
		displayName: 'Pagination Border Default Design2 Quinary',
		name: 'paginationBorderDefaultDesign2Quinary',
		defaultValue: '1px solid #DFE3E8',
		description: 'Pagination Border Default Design2 Quinary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._quinary ._pageNumber ._selected',
	},

	{
		groupName: 'Pagination Border Radius',
		displayName: 'Pagination Border Radius Default Design2 Primary',
		name: 'paginationBorderRadiusDefaultDesign2Primary',
		defaultValue: '100px',
		description: 'Pagination Border Radius Default Design2 Primary',
		cssProperty: 'border-radius',
		selector: '._tablePagination._design2._primary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Border Radius',
		displayName: 'Pagination Border Radius Default Design2 Secondary',
		name: 'paginationBorderRadiusDefaultDesign2Secondary',
		defaultValue: '100px',
		description: 'Pagination Border Radius Default Design2 Secondary',
		cssProperty: 'border-radius',
		selector: '._tablePagination._design2._secondary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Border Radius',
		displayName: 'Pagination Border Radius Default Design2 Tertiary',
		name: 'paginationBorderRadiusDefaultDesign2Tertiary',
		defaultValue: '100px',
		description: 'Pagination Border Radius Default Design3 Tertiary',
		cssProperty: 'border-radius',
		selector: '._tablePagination._design2._tertiary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Border Radius',
		displayName: 'Pagination Border Radius Default Design2 Quaternary',
		name: 'paginationBorderRadiusDefaultDesign2Quaternary',
		defaultValue: '100px',
		description: 'Pagination Border Radius Default Design4 Quaternary',
		cssProperty: 'border-radius',
		selector: '._tablePagination._design2._quaternary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Border Radius',
		displayName: 'Pagination Border Radius Default Design2 Quinary',
		name: 'paginationBorderRadiusDefaultDesign2Quinary',
		defaultValue: '100px',
		description: 'Pagination Border Radius Default Design5 Quinary',
		cssProperty: 'border-radius',
		selector: '._tablePagination._design2._quinary ._pageNumber ._selected',
	},

	{
		groupName: 'Pagination Selected Border ',
		displayName: 'Pagination Selected Border Default Design2 Primary',
		name: 'paginationSelectedBorderDefaultDesign2Primary',
		defaultValue: '1px solid <fontColorThree>',
		description: 'Pagination Border Default Design2 Primary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._primary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Selected Border ',
		displayName: 'Pagination Selected Border Default Design2 Secondary',
		name: 'paginationSelectedBorderDefaultDesign2Secondary',
		defaultValue: '1px solid <fontColorFour>',
		description: 'Pagination Border Default Design2 Secondary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._secondary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Selected Border ',
		displayName: 'Pagination Selected Border Default Design2 Tertiary',
		name: 'paginationSelectedBorderDefaultDesign2Tertiary',
		defaultValue: '1px solid <fontColorFive>',
		description: 'Pagination Border Default Design2 Tertiary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._tertiary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Selected Border ',
		displayName: 'Pagination Selected Border Default Design2 Quaternary',
		name: 'paginationSelectedBorderDefaultDesign2Quaternary',
		defaultValue: '1px solid <fontColorNine>',
		description: 'Pagination Border Default Design2 Quaternary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._quaternary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Selected Border ',
		displayName: 'Pagination Selected Border Default Design2 Quinary',
		name: 'paginationSelectedBorderDefaultDesign2Quinary',
		defaultValue: '1px solid <fontColorSeven>',
		description: 'Pagination Border Default Design2 Quinary',
		cssProperty: 'border',
		selector: '._tablePagination._design2._quinary ._pageNumber ._selected',
	},

	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Color Design2 Primary',
		name: 'paginationSelectedColorDesign2Primary',
		defaultValue: '<fontColorThree>',
		description: 'Pagination Selected Color Design2 Primary',
		cssProperty: 'color ',
		selector: '._tablePagination._design2._primary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Color Design2 Secondary',
		name: 'paginationSelectedColorDesign2Secondary',
		defaultValue: '<fontColorFour>',
		description: 'Pagination Selected Color Design2 Secondary',
		cssProperty: 'color ',
		selector: '._tablePagination._design2._secondary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Color Design2 Tertiary',
		name: 'paginationSelectedColorDesign2Tertiary',
		defaultValue: '<fontColorFive>',
		description: 'Pagination Selected Color Design2 Tertiary',
		cssProperty: 'color ',
		selector: '._tablePagination._design2._tertiary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Color Design2 Quaternary',
		name: 'paginationSelectedColorDesign2Quaternary',
		defaultValue: '<fontColorNine>',
		description: 'Pagination Selected Color Design2 Quaternary',
		cssProperty: 'color ',
		selector: '._tablePagination._design2._quaternary ._pageNumber ._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Color Design2 Quinary',
		name: 'paginationSelectedColorDesign2Quinary',
		defaultValue: '<fontColorSeven>',
		description: 'Pagination Selected Color Design2 Quinary',
		cssProperty: 'color ',
		selector: '._tablePagination._design2._quinary ._pageNumber ._selected',
	},

	{
		groupName: 'Pagination Border',
		displayName: 'Pagination  Filled Border Design3 Primary',
		name: 'paginationFilledBorderDesign3Primary',
		defaultValue: '1px solid  #BDBDBD',
		description: 'Pagination  Filled Border Design3 Primary',
		cssProperty: 'border',
		selector: '._tablePagination._design3._primary ._pageNumber',
	},
	{
		groupName: 'Pagination Border',
		displayName: 'Pagination  Filled Border Design3 Secondary',
		name: 'paginationFilledBorderDesign3Secondary',
		defaultValue: '1px solid  #BDBDBD',
		description: 'Pagination  Filled Border Design3 Secondary',
		cssProperty: 'border',
		selector: '._tablePagination._design3._secondary ._pageNumber',
	},
	{
		groupName: 'Pagination Border',
		displayName: 'Pagination  Filled Border Design3 Tertiary',
		name: 'paginationFilledBorderDesign3Tertiary',
		defaultValue: '1px solid  #BDBDBD',
		description: 'Pagination  Filled Border Design3 Tertiary',
		cssProperty: 'border',
		selector: '._tablePagination._design3._tertiary ._pageNumber',
	},
	{
		groupName: 'Pagination Border',
		displayName: 'Pagination  Filled Border Design3 Quaternary',
		name: 'paginationFilledBorderDesign3Quaternary',
		defaultValue: '1px solid  #BDBDBD',
		description: 'Pagination  Filled Border Design3 Quaternary',
		cssProperty: 'border',
		selector: '._tablePagination._design3._quaternary ._pageNumber',
	},
	{
		groupName: 'Pagination Border',
		displayName: 'Pagination  Filled Border Design3 Quinary',
		name: 'paginationFilledBorderDesign3Quinary',
		defaultValue: '1px solid  #BDBDBD',
		description: 'Pagination  Filled Border Design3 Quinary',
		cssProperty: 'border',
		selector: '._tablePagination._design3._quinary ._pageNumber',
	},

	{
		groupName: 'Pagination Color',
		displayName: 'Pagination  Filled Color Design3 Primary',
		name: 'paginationFilledColorDesign3Primary',
		defaultValue: '#BDBDBD',
		description: 'Pagination  Filled Color Design3 Primary',
		cssProperty: 'color ',
		selector: '._tablePagination._design3._primary ._pageNumber',
	},
	{
		groupName: 'Pagination Color',
		displayName: 'Pagination  Filled Color Design3 Secondary',
		name: 'paginationFilledColorDesign3Secondary',
		defaultValue: '#BDBDBD',
		description: 'Pagination  Filled Color Design3 Secondary',
		cssProperty: 'color ',
		selector: '._tablePagination._design3._secondary ._pageNumber',
	},
	{
		groupName: 'Pagination Color',
		displayName: 'Pagination  Filled Color Design3 Tertiary',
		name: 'paginationFilledColorDesign3Tertiary',
		defaultValue: '#BDBDBD',
		description: 'Pagination  Filled Color Design3 Tertiary',
		cssProperty: 'color ',
		selector: '._tablePagination._design3._tertiary ._pageNumber',
	},
	{
		groupName: 'Pagination Color',
		displayName: 'Pagination  Filled Color Design3 Quaternary',
		name: 'paginationFilledColorDesign3Quaternary',
		defaultValue: '#BDBDBD',
		description: 'Pagination  Filled Color Design3 Quaternary',
		cssProperty: 'color ',
		selector: '._tablePagination._design3._quaternary ._pageNumber',
	},
	{
		groupName: 'Pagination Color',
		displayName: 'Pagination  Filled Color Design3 Quinary',
		name: 'paginationFilledColorDesign3Quinary',
		defaultValue: '#BDBDBD',
		description: 'Pagination  Filled Color Design3 Quinary',
		cssProperty: 'color ',
		selector: '._tablePagination._design3._quinary ._pageNumber',
	},

	{
		groupName: 'Pagination Border-radius',
		displayName: 'Pagination  Filled Border-radius Design3 Primary',
		name: 'paginationFilledBorder-radiusDesign3Primary',
		defaultValue: '4px',
		description: 'Pagination  Filled Border-radius Design3 Primary',
		cssProperty: 'border-radius ',
		selector: '._tablePagination._design3._primary ._pageNumber',
	},
	{
		groupName: 'Pagination Border-radius',
		displayName: 'Pagination  Filled Border-radius Design3 Secondary',
		name: 'paginationFilledBorder-radiusDesign3Secondary',
		defaultValue: '4px',
		description: 'Pagination  Filled Border-radius Design3 Secondary',
		cssProperty: 'border-radius ',
		selector: '._tablePagination._design3._secondary ._pageNumber',
	},
	{
		groupName: 'Pagination Border-radius',
		displayName: 'Pagination  Filled Border-radius Design3 Tertiary',
		name: 'paginationFilledBorder-radiusDesign3Tertiary',
		defaultValue: '4px',
		description: 'Pagination  Filled Border-radius Design3 Tertiary',
		cssProperty: 'border-radius ',
		selector: '._tablePagination._design3._tertiary ._pageNumber',
	},
	{
		groupName: 'Pagination Border-radius',
		displayName: 'Pagination  Filled Border-radius Design3 Quaternary',
		name: 'paginationFilledBorder-radiusDesign3Quaternary',
		defaultValue: '4px',
		description: 'Pagination  Filled Border-radius Design3 Quaternary',
		cssProperty: 'border-radius ',
		selector: '._tablePagination._design3._quaternary ._pageNumber',
	},
	{
		groupName: 'Pagination Border-radius',
		displayName: 'Pagination  Filled Border-radius Design3 Quinary',
		name: 'paginationFilledBorder-radiusDesign3Quinary',
		defaultValue: '4px',
		description: 'Pagination  Filled Border-radius Design3 Quinary',
		cssProperty: 'border-radius ',
		selector: '._tablePagination._design3._quinary ._pageNumber',
	},

	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Filled Color Design3 Primary',
		name: 'paginationSelectedFilledColorDesign3Primary',
		defaultValue: '#FFFFFF',
		description: 'Pagination Selected Filled Color Design3 Primary',
		cssProperty: 'color ',
		selector: '._tablePagination._design3._primary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Filled Color Design3 Secondary',
		name: 'paginationSelectedFilledColorDesign3Secondary',
		defaultValue: '#FFFFFF',
		description: 'Pagination Selected Filled Color Design3 Secondary',
		cssProperty: 'color ',
		selector: '._tablePagination._design3._secondary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Filled Color Design3 Tertiary',
		name: 'paginationSelectedFilledColorDesign3Tertiary',
		defaultValue: '#FFFFFF',
		description: 'Pagination Selected Filled Color Design3 Tertiary',
		cssProperty: 'color ',
		selector: '._tablePagination._design3._tertiary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Filled Color Design3 Quaternary',
		name: 'paginationSelectedFilledColorDesign3Quaternary',
		defaultValue: '#FFFFFF',
		description: 'Pagination Selected Filled Color Design3 Quaternary',
		cssProperty: 'color ',
		selector: '._tablePagination._design3._quaternary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Filled Color Design3 Quinary',
		name: 'paginationSelectedFilledColorDesign3Quinary',
		defaultValue: '#FFFFFF',
		description: 'Pagination Selected Filled Color Design3 Quinary',
		cssProperty: 'color ',
		selector: '._tablePagination._design3._quinary ._pageNumber._selected',
	},

	{
		groupName: 'Pagination Selected Background',
		displayName: 'Pagination Selected Filled Background Design3 Primary',
		name: 'paginationSelectedFilledBackgroundDesign3Primary',
		defaultValue: '<fontColorThree>',
		description: 'Pagination Selected Filled Background Design3 Primary',
		cssProperty: 'background',
		selector: '._tablePagination._design3._primary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Background',
		displayName: 'Pagination Selected Filled Background Design3 Secondary',
		name: 'paginationSelectedFilledBackgroundDesign3Secondary',
		defaultValue: '<fontColorFour>',
		description: 'Pagination Selected Filled Background Design3 Secondary',
		cssProperty: 'background',
		selector: '._tablePagination._design3._secondary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Background',
		displayName: 'Pagination Selected Filled Background Design3 Tertiary',
		name: 'paginationSelectedFilledBackgroundDesign3Tertiary',
		defaultValue: '<fontColorFive>',
		description: 'Pagination Selected Filled Background Design3 Tertiary',
		cssProperty: 'background',
		selector: '._tablePagination._design3._tertiary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Background',
		displayName: 'Pagination Selected Filled Background Design3 Quaternary',
		name: 'paginationSelectedFilledBackgroundDesign3Quaternary',
		defaultValue: '<fontColorNine>',
		description: 'Pagination Selected Filled Background Design3 Quaternary',
		cssProperty: 'background',
		selector: '._tablePagination._design3._quaternary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Background',
		displayName: 'Pagination Selected Filled Background Design3 Quinary',
		name: 'paginationSelectedFilledBackgroundDesign3Quinary',
		defaultValue: '<fontColorSeven>',
		description: 'Pagination Selected Filled Background Design3 Quinary',
		cssProperty: 'background',
		selector: '._tablePagination._design3._quinary ._pageNumber._selected',
	},

	{
		groupName: 'Pagination Border',
		displayName: 'Pagination  Filled Border Design4 Primary',
		name: 'paginationFilledBorderDesign4Primary',
		defaultValue: '1px solid  #BDBDBD',
		description: 'Pagination  Filled Border Design4 Primary',
		cssProperty: 'border',
		selector: '._tablePagination._design4._primary ._pageNumber',
	},
	{
		groupName: 'Pagination Border',
		displayName: 'Pagination  Filled Border Design4 Secondary',
		name: 'paginationFilledBorderDesign4Secondary',
		defaultValue: '1px solid  #BDBDBD',
		description: 'Pagination  Filled Border Design4 Secondary',
		cssProperty: 'border',
		selector: '._tablePagination._design4._secondary ._pageNumber',
	},
	{
		groupName: 'Pagination Border',
		displayName: 'Pagination  Filled Border Design4 Tertiary',
		name: 'paginationFilledBorderDesign4Tertiary',
		defaultValue: '1px solid  #BDBDBD',
		description: 'Pagination  Filled Border Design4 Tertiary',
		cssProperty: 'border',
		selector: '._tablePagination._design4._tertiary ._pageNumber',
	},
	{
		groupName: 'Pagination Border',
		displayName: 'Pagination  Filled Border Design4 Quaternary',
		name: 'paginationFilledBorderDesign4Quaternary',
		defaultValue: '1px solid  #BDBDBD',
		description: 'Pagination  Filled Border Design4 Quaternary',
		cssProperty: 'border',
		selector: '._tablePagination._design4._quaternary ._pageNumber',
	},
	{
		groupName: 'Pagination Border',
		displayName: 'Pagination  Filled Border Design4 Quinary',
		name: 'paginationFilledBorderDesign4Quinary',
		defaultValue: '1px solid  #BDBDBD',
		description: 'Pagination  Filled Border Design4 Quinary',
		cssProperty: 'border',
		selector: '._tablePagination._design4._quinary ._pageNumber',
	},

	{
		groupName: 'Pagination Color',
		displayName: 'Pagination  Filled Color Design4 Primary',
		name: 'paginationFilledColorDesign4Primary',
		defaultValue: '#BDBDBD',
		description: 'Pagination  Filled Color Design4 Primary',
		cssProperty: 'color ',
		selector: '._tablePagination._design4._primary ._pageNumber',
	},
	{
		groupName: 'Pagination Color',
		displayName: 'Pagination  Filled Color Design4 Secondary',
		name: 'paginationFilledColorDesign4Secondary',
		defaultValue: '#BDBDBD',
		description: 'Pagination  Filled Color Design4 Secondary',
		cssProperty: 'color ',
		selector: '._tablePagination._design4._secondary ._pageNumber',
	},
	{
		groupName: 'Pagination Color',
		displayName: 'Pagination  Filled Color Design4 Tertiary',
		name: 'paginationFilledColorDesign4Tertiary',
		defaultValue: '#BDBDBD',
		description: 'Pagination  Filled Color Design4 Tertiary',
		cssProperty: 'color ',
		selector: '._tablePagination._design4._tertiary ._pageNumber',
	},
	{
		groupName: 'Pagination Color',
		displayName: 'Pagination  Filled Color Design4 Quaternary',
		name: 'paginationFilledColorDesign4Quaternary',
		defaultValue: '#BDBDBD',
		description: 'Pagination  Filled Color Design4 Quaternary',
		cssProperty: 'color ',
		selector: '._tablePagination._design4._quaternary ._pageNumber',
	},
	{
		groupName: 'Pagination Color',
		displayName: 'Pagination  Filled Color Design4 Quinary',
		name: 'paginationFilledColorDesign4Quinary',
		defaultValue: '#BDBDBD',
		description: 'Pagination  Filled Color Design4 Quinary',
		cssProperty: 'color ',
		selector: '._tablePagination._design4._quinary ._pageNumber',
	},

	{
		groupName: 'Pagination Border-radius',
		displayName: 'Pagination  Filled Border-radius Design4 Primary',
		name: 'paginationFilledBorder-radiusDesign4Primary',
		defaultValue: '100px',
		description: 'Pagination  Filled Border-radius Design4 Primary',
		cssProperty: 'border-radius ',
		selector: '._tablePagination._design4._primary ._pageNumber',
	},
	{
		groupName: 'Pagination Border-radius',
		displayName: 'Pagination  Filled Border-radius Design4 Secondary',
		name: 'paginationFilledBorder-radiusDesign4Secondary',
		defaultValue: '100px',
		description: 'Pagination  Filled Border-radius Design4 Secondary',
		cssProperty: 'border-radius ',
		selector: '._tablePagination._design4._secondary ._pageNumber',
	},
	{
		groupName: 'Pagination Border-radius',
		displayName: 'Pagination  Filled Border-radius Design4 Tertiary',
		name: 'paginationFilledBorder-radiusDesign4Tertiary',
		defaultValue: '100px',
		description: 'Pagination  Filled Border-radius Design4 Tertiary',
		cssProperty: 'border-radius ',
		selector: '._tablePagination._design4._tertiary ._pageNumber',
	},
	{
		groupName: 'Pagination Border-radius',
		displayName: 'Pagination  Filled Border-radius Design4 Quaternary',
		name: 'paginationFilledBorder-radiusDesign4Quaternary',
		defaultValue: '100px',
		description: 'Pagination  Filled Border-radius Design4 Quaternary',
		cssProperty: 'border-radius ',
		selector: '._tablePagination._design4._quaternary ._pageNumber',
	},
	{
		groupName: 'Pagination Border-radius',
		displayName: 'Pagination  Filled Border-radius Design4 Quinary',
		name: 'paginationFilledBorder-radiusDesign4Quinary',
		defaultValue: '100px',
		description: 'Pagination  Filled Border-radius Design4 Quinary',
		cssProperty: 'border-radius ',
		selector: '._tablePagination._design4._quinary ._pageNumber',
	},

	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Filled Color Design4 Primary',
		name: 'paginationSelectedFilledColorDesign4Primary',
		defaultValue: '#FFFFFF',
		description: 'Pagination Selected Filled Color Design4 Primary',
		cssProperty: 'color ',
		selector: '._tablePagination._design4._primary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Filled Color Design4 Secondary',
		name: 'paginationSelectedFilledColorDesign4Secondary',
		defaultValue: '#FFFFFF',
		description: 'Pagination Selected Filled Color Design4 Secondary',
		cssProperty: 'color ',
		selector: '._tablePagination._design4._secondary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Filled Color Design4 Tertiary',
		name: 'paginationSelectedFilledColorDesign4Tertiary',
		defaultValue: '#FFFFFF',
		description: 'Pagination Selected Filled Color Design4 Tertiary',
		cssProperty: 'color ',
		selector: '._tablePagination._design4._tertiary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Filled Color Design4 Quaternary',
		name: 'paginationSelectedFilledColorDesign4Quaternary',
		defaultValue: '#FFFFFF',
		description: 'Pagination Selected Filled Color Design4 Quaternary',
		cssProperty: 'color ',
		selector: '._tablePagination._design4._quaternary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Color',
		displayName: 'Pagination Selected Filled Color Design4 Quinary',
		name: 'paginationSelectedFilledColorDesign4Quinary',
		defaultValue: '#FFFFFF',
		description: 'Pagination Selected Filled Color Design4 Quinary',
		cssProperty: 'color ',
		selector: '._tablePagination._design4._quinary ._pageNumber._selected',
	},

	{
		groupName: 'Pagination Selected Background',
		displayName: 'Pagination Selected Filled Background Design4 Primary',
		name: 'paginationSelectedFilledBackgroundDesign4Primary',
		defaultValue: '<fontColorThree>',
		description: 'Pagination Selected Filled Background Design4 Primary',
		cssProperty: 'background',
		selector: '._tablePagination._design4._primary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Background',
		displayName: 'Pagination Selected Filled Background Design4 Secondary',
		name: 'paginationSelectedFilledBackgroundDesign4Secondary',
		defaultValue: '<fontColorFour>',
		description: 'Pagination Selected Filled Background Design4 Secondary',
		cssProperty: 'background',
		selector: '._tablePagination._design4._secondary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Background',
		displayName: 'Pagination Selected Filled Background Design4 Tertiary',
		name: 'paginationSelectedFilledBackgroundDesign4Tertiary',
		defaultValue: '<fontColorFive>',
		description: 'Pagination Selected Filled Background Design4 Tertiary',
		cssProperty: 'background',
		selector: '._tablePagination._design4._tertiary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Background',
		displayName: 'Pagination Selected Filled Background Design4 Quaternary',
		name: 'paginationSelectedFilledBackgroundDesign4Quaternary',
		defaultValue: '<fontColorNine>',
		description: 'Pagination Selected Filled Background Design4 Quaternary',
		cssProperty: 'background',
		selector: '._tablePagination._design4._quaternary ._pageNumber._selected',
	},
	{
		groupName: 'Pagination Selected Background',
		displayName: 'Pagination Selected Filled Background Design4 Quinary',
		name: 'paginationSelectedFilledBackgroundDesign4Quinary',
		defaultValue: '<fontColorSeven>',
		description: 'Pagination Selected Filled Background Design4 Quinary',
		cssProperty: 'background',
		selector: '._tablePagination._design4._quinary ._pageNumber._selected',
	},
	{
		groupName: 'Icon Border',
		displayName: 'Columns Icon Border',
		name: 'columnsIconBorder',
		defaultValue: '1px solid  #DFE3E8',
		description: 'Columns Icon Border',
		cssProperty: 'border',
		selector: '.fa-solid.fa-table',
	},
	{
		groupName: 'Icon Border',
		displayName: 'Table Icon Border',
		name: 'tableIconBorder',
		defaultValue: '1px solid  #DFE3E8',
		description: 'Table Icon Border',
		cssProperty: 'border',
		selector: '.fa-solid.fa-table-columns',
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
