import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'General',
		displayName: 'Stepper Font',
		name: 'stepperFont',
		defaultValue: '<primaryFont>',
	},

	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Primary Stepper Step Line Color  Horizontal Design Default',
		name: 'primaryStepperStepLineColorHorizontalDesignDefault',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compStepper._default._primary ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Secondary Stepper Step Line Color  Horizontal Design Default',
		name: 'secondaryStepperStepLineColorHorizontalDesignDefault',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compStepper._default._secondary ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Tertiary Stepper Step Line Color  Horizontal Design Default',
		name: 'tertiaryStepperStepLineColorHorizontalDesignDefault',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compStepper._default._tertiary ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quaternary Stepper Step Line Color  Horizontal Design Default',
		name: 'quaternaryStepperStepLineColorHorizontalDesignDefault',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compStepper._default._quaternary ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quinary Stepper Step Line Color  Horizontal Design Default',
		name: 'quinaryStepperStepLineColorHorizontalDesignDefault',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compStepper._default._quinary ._listItem ._line',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Primary Stepper Step Line Color  Horizontal Design Big Circle',
		name: 'primaryStepperStepLineColorHorizontalDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compStepper._big_circle._primary ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Secondary Stepper Step Line Color  Horizontal Design Big Circle',
		name: 'secondaryStepperStepLineColorHorizontalDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compStepper._big_circle._secondary ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Tertiary Stepper Step Line Color  Horizontal Design Big Circle',
		name: 'tertiaryStepperStepLineColorHorizontalDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compStepper._big_circle._tertiary ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quaternary Stepper Step Line Color  Horizontal Design Big Circle',
		name: 'quaternaryStepperStepLineColorHorizontalDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compStepper._big_circle._quaternary ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quinary Stepper Step Line Color  Horizontal Design Big Circle',
		name: 'quinaryStepperStepLineColorHorizontalDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compStepper._big_circle._quinary ._listItem ._line',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Circle Height',
		displayName: 'Stepper Step Circle Height Design Default',
		name: 'stepperStepCircleHeightDesignDefault',
		defaultValue: '32px',
		cssProperty: 'height',
		selector: '.comp.compStepper._default ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Circle Height',
		displayName: 'Stepper Step Circle Height Design Big Circle',
		name: 'stepperStepCircleHeightDesignBigCircle',
		defaultValue: '50px',
		cssProperty: 'height',
		selector: '.comp.compStepper._big_circle ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Circle Width',
		displayName: 'Stepper Step Circle Width Design Default',
		name: 'stepperStepCircleWidthDesignDefault',
		defaultValue: '32px',
		cssProperty: 'width',
		selector: '.comp.compStepper._default ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Circle Width',
		displayName: 'Stepper Step Circle Width Design Big Circle',
		name: 'stepperStepCircleWidthDesignBigCircle',
		defaultValue: '50px',
		cssProperty: 'width',
		selector: '.comp.compStepper._big_circle ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Min Width',
		displayName: 'Stepper Step Line Min Width Design Default',
		name: 'stepperStepLineMinWidthDesignDefault',
		defaultValue: '30px',
		cssProperty: 'min-width',
		selector: '.comp.compStepper._default._horizontal ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Min Width',
		displayName: 'Stepper Step Line Min Width Design Big Circle',
		name: 'stepperStepLineMinWidthDesignBigCircle',
		defaultValue: '30px',
		cssProperty: 'min-width',
		selector: '.comp.compStepper._big_circle._horizontal ._listItem ._line',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Min Height',
		displayName: 'Stepper Step Line Min Height Design Default',
		name: 'stepperStepLineMinHeightDesignDefault',
		defaultValue: '30px',
		cssProperty: 'min-height',
		selector: '.comp.compStepper._default._vertical ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Min Height',
		displayName: 'Stepper Step Line Min Height Design Big Circle',
		name: 'stepperStepLineMinHeightDesignBigCircle',
		defaultValue: '30px',
		cssProperty: 'min-height',
		selector: '.comp.compStepper._big_circle._vertical ._listItem ._line',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Height',
		displayName: 'Stepper Step Line Height Design Default',
		name: 'stepperStepLineHeightDesignDefault',
		defaultValue: '2px',
		cssProperty: 'height',
		selector: '.comp.compStepper._default._horizontal ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Height',
		displayName: 'Stepper Step Line Height Design Big Circle',
		name: 'stepperStepLineHeightDesignBigCircle',
		defaultValue: '2px',
		cssProperty: 'height',
		selector: '.comp.compStepper._big_circle._horizontal ._listItem ._line',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Width',
		displayName: 'Stepper Step Line Width Design Default',
		name: 'stepperStepLineWidthDesignDefault',
		defaultValue: '2px',
		cssProperty: 'width',
		selector:
			'.comp.compStepper._default._vertical._textRight ._listItem ._line,.comp.compStepper._default._vertical._textLeft ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Width',
		displayName: 'Stepper Step Line Width Design Big Circle',
		name: 'stepperStepLineWidthDesignBigCircle',
		defaultValue: '2px',
		cssProperty: 'width',
		selector:
			'.comp.compStepper._big_circle._vertical._textRight ._listItem ._line,.comp.compStepper._big_circle._vertical._textLeft ._listItem ._line',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Horizontal Line Margin Top',
		displayName: 'Stepper Step Horizontal Line Margin Top Design Default',
		name: 'stepperStepHorizontalLineMarginTopDesignDefault',
		defaultValue: '15px',
		cssProperty: 'margin-top',
		selector: '.comp.compStepper._default._horizontal ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Horizontal Line Margin Top',
		displayName: 'Stepper Step Horizontal Line Margin Top Design Big Circle',
		name: 'stepperStepHorizontalLineMarginTopDesignBigCircle',
		defaultValue: '25px',
		cssProperty: 'margin-top',
		selector: '.comp.compStepper._big_circle._horizontal ._listItem ._line',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Horizontal Line Margin Bottom',
		displayName: 'Stepper Step Horizontal Line Margin Bottom Design Default',
		name: 'stepperStepHorizontalLineMarginBottomDesignDefault',
		defaultValue: '15px',
		cssProperty: 'margin-bottom',
		selector: '.comp.compStepper._default._horizontal ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Horizontal Line Margin Bottom',
		displayName: 'Stepper Step Horizontal Line Margin Bottom Design Big Circle',
		name: 'stepperStepHorizontalLineMarginBottomDesignBigCircle',
		defaultValue: '25px',
		cssProperty: 'margin-bottom',
		selector: '.comp.compStepper._big_circle._horizontal ._listItem ._line',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Vertical Line Margin Left',
		displayName: 'Stepper Step Vertical Line Margin Left Design Default',
		name: 'stepperStepVerticalLineMarginLeftDesignDefault',
		defaultValue: '15px',
		cssProperty: 'margin-left',
		selector:
			'.comp.compStepper._default._vertical._textRight ._listItem ._line,.comp.compStepper._default._vertical._textLeft ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Vertical Line Margin Left',
		displayName: 'Stepper Step Vertical Line Margin Left Design Big Circle',
		name: 'stepperStepVerticalLineMarginLeftDesignBigCircle',
		defaultValue: '25px',
		cssProperty: 'margin-left',
		selector:
			'.comp.compStepper._big_circle._vertical._textRight ._listItem ._line,.comp.compStepper._big_circle._vertical._textLeft ._listItem ._line',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Vertical Line Margin Right',
		displayName: 'Stepper Step Vertical Line Margin Right Design Default',
		name: 'stepperStepVerticalLineMarginRightDesignDefault',
		defaultValue: '15px',
		cssProperty: 'margin-right',
		selector:
			'.comp.compStepper._default._vertical._textRight ._listItem ._line,.comp.compStepper._default._vertical._textLeft ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Vertical Line Margin Right',
		displayName: 'Stepper Step Vertical Line Margin Right Design Big Circle',
		name: 'stepperStepVerticalLineMarginRightDesignBigCircle',
		defaultValue: '25px',
		cssProperty: 'margin-right',
		selector:
			'.comp.compStepper._big_circle._vertical._textRight ._listItem ._line,.comp.compStepper._big_circle._vertical._textLeft ._listItem ._line',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Pill Width',
		displayName: 'Stepper Step Pill Width Design Pills',
		name: 'stepperStepPillWidthDesignPills',
		defaultValue: '48px',
		cssProperty: 'width',
		selector: '.comp.compStepper._pills ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Pill Height',
		displayName: 'Stepper Step Pill Height Design Pills',
		name: 'stepperStepPillHeightDesignPills',
		defaultValue: '24px',
		cssProperty: 'height',
		selector: '.comp.compStepper._pills ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Default State',
		displayName: 'Stepper Step Border Default State Design Default',
		name: 'stepperStepBorderDefaultStateDesignDefault',
		defaultValue: '2px solid',
		cssProperty: 'border',
		selector: '.comp.compStepper._default ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Default State',
		displayName: 'Stepper Step Border Default State Design Big Circle',
		name: 'stepperStepBorderDefaultStateDesignBigCircle',
		defaultValue: '2px solid',
		cssProperty: 'border',
		selector: '.comp.compStepper._big_circle ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Default State',
		displayName: 'Stepper Step Border Default State Design Pills',
		name: 'stepperStepBorderDefaultStateDesignPills',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._pills ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Default State',
		displayName: 'Stepper Step Border Default State Design Rectangle Arrow',
		name: 'stepperStepBorderDefaultStateDesignRectangleArrow',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._rectangle_arrow ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Active State',
		displayName: 'Stepper Step Border Active State Design Default',
		name: 'stepperStepBorderActiveStateDesignDefault',
		defaultValue: '2px solid',
		cssProperty: 'border',
		selector: '.comp.compStepper._default ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Active State',
		displayName: 'Stepper Step Border Active State Design Big Circle',
		name: 'stepperStepBorderActiveStateDesignBigCircle',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._big_circle ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Active State',
		displayName: 'Stepper Step Border Active State Design Pills',
		name: 'stepperStepBorderActiveStateDesignPills',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._pills ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Active State',
		displayName: 'Stepper Step Border Active State Design Rectangle Arrow',
		name: 'stepperStepBorderActiveStateDesignRectangleArrow',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._rectangle_arrow ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Done State',
		displayName: 'Stepper Step Border Done State Design Default',
		name: 'stepperStepBorderDoneStateDesignDefault',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._default ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Done State',
		displayName: 'Stepper Step Border Done State Design Big Circle',
		name: 'stepperStepBorderDoneStateDesignBigCircle',
		defaultValue: '2px solid',
		cssProperty: 'border',
		selector: '.comp.compStepper._big_circle ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Done State',
		displayName: 'Stepper Step Border Done State Design Pills',
		name: 'stepperStepBorderDoneStateDesignPills',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._pills ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Done State',
		displayName: 'Stepper Step Border Done State Design Rectangle Arrow',
		name: 'stepperStepBorderDoneStateDesignRectangleArrow',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._rectangle_arrow ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Radius',
		displayName: 'Stepper Step Border Radius Design Default',
		name: 'stepperStepBorderRadiusDesignDefault',
		defaultValue: '50%',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._default ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Radius',
		displayName: 'Stepper Step Border Radius Design Big Circle',
		name: 'stepperStepBorderRadiusDesignBigCircle',
		defaultValue: '50%',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._big_circle ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Radius',
		displayName: 'Stepper Step Border Radius Design Pills',
		name: 'stepperStepBorderRadiusDesignPills',
		defaultValue: '12px',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._pills ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Primary Stepper Step Border Color Default State Design Default',
		name: 'primaryStepperStepBorderColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._primary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Secondary Stepper Step Border Color Default State Design Default',
		name: 'secondaryStepperStepBorderColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._secondary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Tertiary Stepper Step Border Color Default State Design Default',
		name: 'tertiaryStepperStepBorderColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._tertiary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Quaternary Stepper Step Border Color Default State Design Default',
		name: 'quaternaryStepperStepBorderColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._quaternary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Quinary Stepper Step Border Color Default State Design Default',
		name: 'quinaryStepperStepBorderColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._quinary ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Primary Stepper Step Border Color Default State Design Big Circle',
		name: 'primaryStepperStepBorderColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._primary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Secondary Stepper Step Border Color Default State Design Big Circle',
		name: 'secondaryStepperStepBorderColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._secondary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Tertiary Stepper Step Border Color Default State Design Big Circle',
		name: 'tertiaryStepperStepBorderColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._tertiary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Quaternary Stepper Step Border Color Default State Design Big Circle',
		name: 'quaternaryStepperStepBorderColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._quaternary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Quinary Stepper Step Border Color Default State Design Big Circle',
		name: 'quinaryStepperStepBorderColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._quinary ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Color Active State',
		displayName: 'Primary Stepper Step Border Color Active State Design Default',
		name: 'primaryStepperStepBorderColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._primary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Active State',
		displayName: 'Secondary Stepper Step Border Color Active State Design Default',
		name: 'secondaryStepperStepBorderColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._secondary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Active State',
		displayName: 'Tertiary Stepper Step Border Color Active State Design Default',
		name: 'tertiaryStepperStepBorderColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._tertiary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Active State',
		displayName: 'Quaternary Stepper Step Border Color Active State Design Default',
		name: 'quaternaryStepperStepBorderColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._quaternary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Active State',
		displayName: 'Quinary Stepper Step Border Color Active State Design Default',
		name: 'quinaryStepperStepBorderColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._quinary ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Color Done State',
		displayName: 'Primary Stepper Step Border Color Done State Design Big Circle',
		name: 'primaryStepperStepBorderColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._primary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Done State',
		displayName: 'Secondary Stepper Step Border Color Done State Design Big Circle',
		name: 'secondaryStepperStepBorderColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._secondary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Done State',
		displayName: 'Tertiary Stepper Step Border Color Done State Design Big Circle',
		name: 'tertiaryStepperStepBorderColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._tertiary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Done State',
		displayName: 'Quaternary Stepper Step Border Color Done State Design Big Circle',
		name: 'quaternaryStepperStepBorderColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._quaternary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Done State',
		displayName: 'Quinary Stepper Step Border Color Done State Design Big Circle',
		name: 'quinaryStepperStepBorderColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._quinary ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Primary Stepper Step Background Color Done State Design Default',
		name: 'primaryStepperStepBackgroundColorDoneStateDesignDefault',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._primary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Secondary Stepper Step Background Color Done State Design Default',
		name: 'secondaryStepperStepBackgroundColorDoneStateDesignDefault',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._secondary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Tertiary Stepper Step Background Color Done State Design Default',
		name: 'tertiaryStepperStepBackgroundColorDoneStateDesignDefault',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._tertiary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Quaternary Stepper Step Background Color Done State Design Default',
		name: 'quaternaryStepperStepBackgroundColorDoneStateDesignDefault',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._quaternary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Quinary Stepper Step Background Color Done State Design Default',
		name: 'quinaryStepperStepBackgroundColorDoneStateDesignDefault',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._quinary ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Primary Stepper Step Background Color Active State Design Big Circle',
		name: 'primaryStepperStepBackgroundColorActiveStateDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._primary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Secondary Stepper Step Background Color Active State Design Big Circle',
		name: 'secondaryStepperStepBackgroundColorActiveStateDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._secondary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Tertiary Stepper Step Background Color Active State Design Big Circle',
		name: 'tertiaryStepperStepBackgroundColorActiveStateDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._tertiary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Quaternary Stepper Step Background Color Active State Design Big Circle',
		name: 'quaternaryStepperStepBackgroundColorActiveStateDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._quaternary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Quinary Stepper Step Background Color Active State Design Big Circle',
		name: 'quinaryStepperStepBackgroundColorActiveStateDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._quinary ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Primary Stepper Step Color Default State Design Default',
		name: 'primaryStepperStepColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._primary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Secondary Stepper Step Color Default State Design Default',
		name: 'secondaryStepperStepColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._secondary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Tertiary Stepper Step Color Default State Design Default',
		name: 'tertiaryStepperStepColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._tertiary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Quaternary Stepper Step Color Default State Design Default',
		name: 'quaternaryStepperStepColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quaternary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Quinary Stepper Step Color Default State Design Default',
		name: 'quinaryStepperStepColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quinary ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Primary Stepper Step Color Default State Design Big Circle',
		name: 'primaryStepperStepColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._primary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Secondary Stepper Step Color Default State Design Big Circle',
		name: 'secondaryStepperStepColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._secondary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Tertiary Stepper Step Color Default State Design Big Circle',
		name: 'tertiaryStepperStepColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._tertiary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Quaternary Stepper Step Color Default State Design Big Circle',
		name: 'quaternaryStepperStepColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quaternary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Quinary Stepper Step Color Default State Design Big Circle',
		name: 'quinaryStepperStepColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quinary ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Primary Stepper Step Color Active State Design Default',
		name: 'primaryStepperStepColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._primary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Secondary Stepper Step Color Active State Design Default',
		name: 'secondaryStepperStepColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._secondary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Tertiary Stepper Step Color Active State Design Default',
		name: 'tertiaryStepperStepColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._tertiary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Quaternary Stepper Step Color Active State Design Default',
		name: 'quaternaryStepperStepColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quaternary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Quinary Stepper Step Color Active State Design Default',
		name: 'quinaryStepperStepColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quinary ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Primary Stepper Step Color Active State Design Big Circle',
		name: 'primaryStepperStepColorActiveStateDesignBigCircle',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._primary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Secondary Stepper Step Color Active State Design Big Circle',
		name: 'secondaryStepperStepColorActiveStateDesignBigCircle',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._secondary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Tertiary Stepper Step Color Active State Design Big Circle',
		name: 'tertiaryStepperStepColorActiveStateDesignBigCircle',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._tertiary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Quaternary Stepper Step Color Active State Design Big Circle',
		name: 'quaternaryStepperStepColorActiveStateDesignBigCircle',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quaternary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Quinary Stepper Step Color Active State Design Big Circle',
		name: 'quinaryStepperStepColorActiveStateDesignBigCircle',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quinary ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Primary Stepper Step Color Done State Design Default',
		name: 'primaryStepperStepColorDoneStateDesignDefault',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._primary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Secondary Stepper Step Color Done State Design Default',
		name: 'secondaryStepperStepColorDoneStateDesignDefault',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._secondary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Tertiary Stepper Step Color Done State Design Default',
		name: 'tertiaryStepperStepColorDoneStateDesignDefault',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._tertiary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Quaternary Stepper Step Color Done State Design Default',
		name: 'quaternaryStepperStepColorDoneStateDesignDefault',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quaternary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Quinary Stepper Step Color Done State Design Default',
		name: 'quinaryStepperStepColorDoneStateDesignDefault',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quinary ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Primary Stepper Step Color Done State Design Big Circle',
		name: 'primaryStepperStepColorDoneStateDesignBigCircle',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._primary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Secondary Stepper Step Color Done State Design Big Circle',
		name: 'secondaryStepperStepColorDoneStateDesignBigCircle',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._secondary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Tertiary Stepper Step Color Done State Design Big Circle',
		name: 'tertiaryStepperStepColorDoneStateDesignBigCircle',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._tertiary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Quaternary Stepper Step Color Done State Design Big Circle',
		name: 'quaternaryStepperStepColorDoneStateDesignBigCircle',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quaternary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Quinary Stepper Step Color Done State Design Big Circle',
		name: 'quinaryStepperStepColorDoneStateDesignBigCircle',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quinary ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Primary Stepper Step Title Color Design Default',
		name: 'primaryStepperStepTitleColorDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._primary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Secondary Stepper Step Title Color Design Default',
		name: 'secondaryStepperStepTitleColorDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._secondary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Tertiary Stepper Step Title Color Design Default',
		name: 'tertiaryStepperStepTitleColorDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._tertiary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Quaternary Stepper Step Title Color Design Default',
		name: 'quaternaryStepperStepTitleColorDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quaternary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Quinary Stepper Step Title Color Design Default',
		name: 'quinaryStepperStepTitleColorDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quinary ._title',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Primary Stepper Step Title Color Design Big Circle',
		name: 'primaryStepperStepTitleColorDesignBigCircle',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._primary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Secondary Stepper Step Title Color Design Big Circle',
		name: 'secondaryStepperStepTitleColorDesignBigCircle',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._secondary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Tertiary Stepper Step Title Color Design Big Circle',
		name: 'tertiaryStepperStepTitleColorDesignBigCircle',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._tertiary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Quaternary Stepper Step Title Color Design Big Circle',
		name: 'quaternaryStepperStepTitleColorDesignBigCircle',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quaternary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Quinary Stepper Step Title Color Design Big Circle',
		name: 'quinaryStepperStepTitleColorDesignBigCircle',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quinary ._title',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Padding',
		displayName: 'Stepper Step Title Padding Design Default',
		name: 'stepperStepTitlePaddingDesignDefault',
		defaultValue: '5px',
		cssProperty: 'padding',
		selector: '.comp.compStepper._default ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Padding',
		displayName: 'Stepper Step Title Padding Design Big Circle',
		name: 'stepperStepTitlePaddingDesignBigCircle',
		defaultValue: '8px',
		cssProperty: 'padding',
		selector: '.comp.compStepper._big_circle ._title',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Primary Stepper Step Background Color Default State Design Pills',
		name: 'primaryStepperStepBackgroundColorDefaultStateDesignPills',
		defaultValue: '<backgroundHoverColorSeven>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._primary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Secondary Stepper Step Background Color Default State Design Pills',
		name: 'secondaryStepperStepBackgroundColorDefaultStateDesignPills',
		defaultValue: '<backgroundHoverColorSeven>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._secondary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Tertiary Stepper Step Background Color Default State Design Pills',
		name: 'tertiaryStepperStepBackgroundColorDefaultStateDesignPills',
		defaultValue: '<backgroundHoverColorSeven>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._tertiary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Quaternary Stepper Step Background Color Default State Design Pills',
		name: 'quaternaryStepperStepBackgroundColorDefaultStateDesignPills',
		defaultValue: '<backgroundHoverColorSeven>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._quaternary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Quinary Stepper Step Background Color Default State Design Pills',
		name: 'quinaryStepperStepBackgroundColorDefaultStateDesignPills',
		defaultValue: '<backgroundHoverColorSeven>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._quinary ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Primary Stepper Step Background Color Active State Design Pills',
		name: 'primaryStepperStepBackgroundColorActiveStateDesignPills',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._primary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Secondary Stepper Step Background Color Active State Design Pills',
		name: 'secondaryStepperStepBackgroundColorActiveStateDesignPills',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._secondary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Tertiary Stepper Step Background Color Active State Design Pills',
		name: 'tertiaryStepperStepBackgroundColorActiveStateDesignPills',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._tertiary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Quaternary Stepper Step Background Color Active State Design Pills',
		name: 'quaternaryStepperStepBackgroundColorActiveStateDesignPills',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._quaternary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Quinary Stepper Step Background Color Active State Design Pills',
		name: 'quinaryStepperStepBackgroundColorActiveStateDesignPills',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._quinary ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Primary Stepper Step Background Color Done State Design Pills',
		name: 'primaryStepperStepBackgroundColorDoneStateDesignPills',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._primary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Secondary Stepper Step Background Color Done State Design Pills',
		name: 'secondaryStepperStepBackgroundColorDoneStateDesignPills',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._secondary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Tertiary Stepper Step Background Color Done State Design Pills',
		name: 'tertiaryStepperStepBackgroundColorDoneStateDesignPills',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._tertiary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Quaternary Stepper Step Background Color Done State Design Pills',
		name: 'quaternaryStepperStepBackgroundColorDoneStateDesignPills',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._quaternary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Quinary Stepper Step Background Color Done State Design Pills',
		name: 'quinaryStepperStepBackgroundColorDoneStateDesignPills',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._quinary ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Primary Stepper Step Color Default State Design Pills',
		name: 'primaryStepperStepColorDefaultStateDesignPills',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._primary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Secondary Stepper Step Color Default State Design Pills',
		name: 'secondaryStepperStepColorDefaultStateDesignPills',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._secondary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Tertiary Stepper Step Color Default State Design Pills',
		name: 'tertiaryStepperStepColorDefaultStateDesignPills',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._tertiary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Quaternary Stepper Step Color Default State Design Pills',
		name: 'quaternaryStepperStepColorDefaultStateDesignPills',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._quaternary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Quinary Stepper Step Color Default State Design Pills',
		name: 'quinaryStepperStepColorDefaultStateDesignPills',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._quinary ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Primary Stepper Step Color Active State Design Pills',
		name: 'primaryStepperStepColorActiveStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._primary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Secondary Stepper Step Color Active State Design Pills',
		name: 'secondaryStepperStepColorActiveStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._secondary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Tertiary Stepper Step Color Active State Design Pills',
		name: 'tertiaryStepperStepColorActiveStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._tertiary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Quaternary Stepper Step Color Active State Design Pills',
		name: 'quaternaryStepperStepColorActiveStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._quaternary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Quinary Stepper Step Color Active State Design Pills',
		name: 'quinaryStepperStepColorActiveStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._quinary ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Primary Stepper Step Color Done State Design Pills',
		name: 'primaryStepperStepColorDoneStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._primary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Secondary Stepper Step Color Done State Design Pills',
		name: 'secondaryStepperStepColorDoneStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._secondary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Tertiary Stepper Step Color Done State Design Pills',
		name: 'tertiaryStepperStepColorDoneStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._tertiary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Quaternary Stepper Step Color Done State Design Pills',
		name: 'quaternaryStepperStepColorDoneStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._quaternary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Quinary Stepper Step Color Done State Design Pills',
		name: 'quinaryStepperStepColorDoneStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._quinary ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Gap',
		displayName: 'Stepper Gap Design Pills',
		name: 'stepperGapDesignPills',
		defaultValue: '8px',
		cssProperty: 'gap',
		selector: 'ul.comp.compStepper._pills',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Border Radius',
		displayName: 'Stepper Border Radius Design Rectangle Arrow',
		name: 'stepperBorderRadiusDesignRectangleArrow',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: 'ul.comp.compStepper._rectangle_arrow',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Box Shadow',
		displayName: 'Stepper Box Shadow Design Rectangle Arrow',
		name: 'stepperBoxShadowDesignRectangleArrow',
		defaultValue: '0px 1px 4px 0px rgba(0, 0, 0, 0.10)',
		cssProperty: 'box-shadow',
		selector: 'ul.comp.compStepper._rectangle_arrow',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Rectangle Arrow Design Item Container Gap',
		displayName: 'Stepper Rectangle Arrow Design Item Container Gap Design Rectangle Arrow',
		name: 'stepperRectangleArrowDesignItemContainerGapDesignRectangleArrow',
		defaultValue: '10px',
		cssProperty: 'gap',
		selector: 'ul.comp.compStepper._rectangle_arrow ._itemContainer',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Background Color',
		displayName: 'Primary Stepper Background Color Design Rectangle Arrow',
		name: 'primaryStepperBackgroundColorDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'background-color',
		selector: 'ul.comp.compStepper._rectangle_arrow._primary',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Background Color',
		displayName: 'Secondary Stepper Background Color Design Rectangle Arrow',
		name: 'secondaryStepperBackgroundColorDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'background-color',
		selector: 'ul.comp.compStepper._rectangle_arrow._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Background Color',
		displayName: 'Tertiary Stepper Background Color Design Rectangle Arrow',
		name: 'tertiaryStepperBackgroundColorDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'background-color',
		selector: 'ul.comp.compStepper._rectangle_arrow._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Background Color',
		displayName: 'Quaternary Stepper Background Color Design Rectangle Arrow',
		name: 'quaternaryStepperBackgroundColorDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'background-color',
		selector: 'ul.comp.compStepper._rectangle_arrow._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Background Color',
		displayName: 'Quinary Stepper Background Color Design Rectangle Arrow',
		name: 'quinaryStepperBackgroundColorDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'background-color',
		selector: 'ul.comp.compStepper._rectangle_arrow._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Height',
		displayName: 'Stepper Step Height Design Rectangle Arrow',
		name: 'stepperStepHeightDesignRectangleArrow',
		defaultValue: '48px',
		cssProperty: 'height',
		selector: '.comp.compStepper._rectangle_arrow ._listItem',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Primary Stepper Step Background Color Default State Design Rectangle Arrow',
		name: 'primaryStepperStepBackgroundColorDefaultStateDesignRectangleArrow',
		defaultValue: 'transparent',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._primary ._listItem',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Secondary Stepper Step Background Color Default State Design Rectangle Arrow',
		name: 'secondaryStepperStepBackgroundColorDefaultStateDesignRectangleArrow',
		defaultValue: 'transparent',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._secondary ._listItem',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Tertiary Stepper Step Background Color Default State Design Rectangle Arrow',
		name: 'tertiaryStepperStepBackgroundColorDefaultStateDesignRectangleArrow',
		defaultValue: 'transparent',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._tertiary ._listItem',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName:
			'Quaternary Stepper Step Background Color Default State Design Rectangle Arrow',
		name: 'quaternaryStepperStepBackgroundColorDefaultStateDesignRectangleArrow',
		defaultValue: 'transparent',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._quaternary ._listItem',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Quinary Stepper Step Background Color Default State Design Rectangle Arrow',
		name: 'quinaryStepperStepBackgroundColorDefaultStateDesignRectangleArrow',
		defaultValue: 'transparent',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._quinary ._listItem',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Primary Stepper Step Background Color Active State Design Rectangle Arrow',
		name: 'primaryStepperStepBackgroundColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._primary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Secondary Stepper Step Background Color Active State Design Rectangle Arrow',
		name: 'secondaryStepperStepBackgroundColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._secondary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Tertiary Stepper Step Background Color Active State Design Rectangle Arrow',
		name: 'tertiaryStepperStepBackgroundColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._tertiary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Quaternary Stepper Step Background Color Active State Design Rectangle Arrow',
		name: 'quaternaryStepperStepBackgroundColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._quaternary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Quinary Stepper Step Background Color Active State Design Rectangle Arrow',
		name: 'quinaryStepperStepBackgroundColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._quinary ._listItem._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Primary Stepper Step Background Color Done State Design Rectangle Arrow',
		name: 'primaryStepperStepBackgroundColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._primary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Secondary Stepper Step Background Color Done State Design Rectangle Arrow',
		name: 'secondaryStepperStepBackgroundColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._secondary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Tertiary Stepper Step Background Color Done State Design Rectangle Arrow',
		name: 'tertiaryStepperStepBackgroundColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._tertiary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Quaternary Stepper Step Background Color Done State Design Rectangle Arrow',
		name: 'quaternaryStepperStepBackgroundColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._quaternary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Quinary Stepper Step Background Color Done State Design Rectangle Arrow',
		name: 'quinaryStepperStepBackgroundColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._quinary ._listItem._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Arrow Border Width',
		displayName: 'Stepper Step Arrow Border Width Design Rectangle Arrow',
		name: 'stepperStepArrowBorderWidthDesignRectangleArrow',
		defaultValue: '20px',
		cssProperty: 'width',
		selector: '.comp.compStepper._rectangle_arrow ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Height',
		displayName: 'Stepper Step Arrow Border Height Design Rectangle Arrow',
		name: 'stepperStepArrowBorderHeightDesignRectangleArrow',
		defaultValue: '100%',
		cssProperty: 'height',
		selector: '.comp.compStepper._rectangle_arrow ._listItem ._line',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Arrow Border Left Color Active State',
		displayName:
			'Primary Stepper Step Arrow Border Left Color Active State Design Rectangle Arrow',
		name: 'primaryStepperStepArrowBorderLeftColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._primary ._listItem._active ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Active State',
		displayName:
			'Secondary Stepper Step Arrow Border Left Color Active State Design Rectangle Arrow',
		name: 'secondaryStepperStepArrowBorderLeftColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._secondary ._listItem._active ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Active State',
		displayName:
			'Tertiary Stepper Step Arrow Border Left Color Active State Design Rectangle Arrow',
		name: 'tertiaryStepperStepArrowBorderLeftColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._tertiary ._listItem._active ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Active State',
		displayName:
			'Quaternary Stepper Step Arrow Border Left Color Active State Design Rectangle Arrow',
		name: 'quaternaryStepperStepArrowBorderLeftColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._quaternary ._listItem._active ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Active State',
		displayName:
			'Quinary Stepper Step Arrow Border Left Color Active State Design Rectangle Arrow',
		name: 'quinaryStepperStepArrowBorderLeftColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._quinary ._listItem._active ._line',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Arrow Border Left Color Done State',
		displayName:
			'Primary Stepper Step Arrow Border Left Color Done State Design Rectangle Arrow',
		name: 'primaryStepperStepArrowBorderLeftColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._primary ._listItem._done ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Done State',
		displayName:
			'Secondary Stepper Step Arrow Border Left Color Done State Design Rectangle Arrow',
		name: 'secondaryStepperStepArrowBorderLeftColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._secondary ._listItem._done ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Done State',
		displayName:
			'Tertiary Stepper Step Arrow Border Left Color Done State Design Rectangle Arrow',
		name: 'tertiaryStepperStepArrowBorderLeftColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._tertiary ._listItem._done ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Done State',
		displayName:
			'Quaternary Stepper Step Arrow Border Left Color Done State Design Rectangle Arrow',
		name: 'quaternaryStepperStepArrowBorderLeftColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._quaternary ._listItem._done ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Done State',
		displayName:
			'Quinary Stepper Step Arrow Border Left Color Done State Design Rectangle Arrow',
		name: 'quinaryStepperStepArrowBorderLeftColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compStepper._rectangle_arrow._quinary ._listItem._done ._line',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Color Default State',
		displayName: 'Primary Stepper Step Title Color Default State Design Rectangle Arrow',
		name: 'primaryStepperStepTitleColorDefaultStateDesignRectangleArrow',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._primary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Default State',
		displayName: 'Secondary Stepper Step Title Color Default State Design Rectangle Arrow',
		name: 'secondaryStepperStepTitleColorDefaultStateDesignRectangleArrow',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._secondary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Default State',
		displayName: 'Tertiary Stepper Step Title Color Default State Design Rectangle Arrow',
		name: 'tertiaryStepperStepTitleColorDefaultStateDesignRectangleArrow',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._tertiary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Default State',
		displayName: 'Quaternary Stepper Step Title Color Default State Design Rectangle Arrow',
		name: 'quaternaryStepperStepTitleColorDefaultStateDesignRectangleArrow',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._quaternary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Default State',
		displayName: 'Quinary Stepper Step Title Color Default State Design Rectangle Arrow',
		name: 'quinaryStepperStepTitleColorDefaultStateDesignRectangleArrow',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._quinary ._title',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Color Active State',
		displayName: 'Primary Stepper Step Title Color Active State Design Rectangle Arrow',
		name: 'primaryStepperStepTitleColorActiveStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._primary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active State',
		displayName: 'Secondary Stepper Step Title Color Active State Design Rectangle Arrow',
		name: 'secondaryStepperStepTitleColorActiveStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._secondary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active State',
		displayName: 'Tertiary Stepper Step Title Color Active State Design Rectangle Arrow',
		name: 'tertiaryStepperStepTitleColorActiveStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._tertiary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active State',
		displayName: 'Quaternary Stepper Step Title Color Active State Design Rectangle Arrow',
		name: 'quaternaryStepperStepTitleColorActiveStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._quaternary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active State',
		displayName: 'Quinary Stepper Step Title Color Active State Design Rectangle Arrow',
		name: 'quinaryStepperStepTitleColorActiveStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._quinary ._title._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Primary Stepper Step Title Color Done State Design Rectangle Arrow',
		name: 'primaryStepperStepTitleColorDoneStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._primary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Secondary Stepper Step Title Color Done State Design Rectangle Arrow',
		name: 'secondaryStepperStepTitleColorDoneStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._secondary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Tertiary Stepper Step Title Color Done State Design Rectangle Arrow',
		name: 'tertiaryStepperStepTitleColorDoneStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._tertiary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Quaternary Stepper Step Title Color Done State Design Rectangle Arrow',
		name: 'quaternaryStepperStepTitleColorDoneStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._quaternary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Quinary Stepper Step Title Color Done State Design Rectangle Arrow',
		name: 'quinaryStepperStepTitleColorDoneStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._quinary ._title._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color',
		displayName: 'Primary Stepper Step Background Color Design Default Active State',
		name: 'primaryStepperStepBackgroundColorDesignDefaultActiveState',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._primary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color',
		displayName: 'Secondary Stepper Step Background Color Design Default Active State',
		name: 'secondaryStepperStepBackgroundColorDesignDefaultActiveState',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._secondary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color',
		displayName: 'Tertiary Stepper Step Background Color Design Default Active State',
		name: 'tertiaryStepperStepBackgroundColorDesignDefaultActiveState',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._tertiary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color',
		displayName: 'Quaternary Stepper Step Background Color Design Default Active State',
		name: 'quaternaryStepperStepBackgroundColorDesignDefaultActiveState',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._quaternary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color',
		displayName: 'Quinary Stepper Step Background Color Design Default Active State',
		name: 'quinaryStepperStepBackgroundColorDesignDefaultActiveState',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._quinary ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color',
		displayName: 'Primary Stepper Step Background Color Design Default Future State',
		name: 'primaryStepperStepBackgroundColorDesignDefaultFutureState',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._primary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color',
		displayName: 'Secondary Stepper Step Background Color Design Default Future State',
		name: 'secondaryStepperStepBackgroundColorDesignDefaultFutureState',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._secondary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color',
		displayName: 'Tertiary Stepper Step Background Color Design Default Future State',
		name: 'tertiaryStepperStepBackgroundColorDesignDefaultFutureState',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._tertiary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color',
		displayName: 'Quaternary Stepper Step Background Color Design Default Future State',
		name: 'quaternaryStepperStepBackgroundColorDesignDefaultFutureState',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._quaternary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color',
		displayName: 'Quinary Stepper Step Background Color Design Default Future State',
		name: 'quinaryStepperStepBackgroundColorDesignDefaultFutureState',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._quinary ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Primary Stepper Step Background Color Done State Design Big Circle',
		name: 'primaryStepperStepBackgroundColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._primary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Secondary Stepper Step Background Color Done State Design Big Circle',
		name: 'secondaryStepperStepBackgroundColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._secondary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Tertiary Stepper Step Background Color Done State Design Big Circle',
		name: 'tertiaryStepperStepBackgroundColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._tertiary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Quaternary Stepper Step Background Color Done State Design Big Circle',
		name: 'quaternaryStepperStepBackgroundColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._quaternary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Quinary Stepper Step Background Color Done State Design Big Circle',
		name: 'quinaryStepperStepBackgroundColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._quinary ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Future State',
		displayName: 'Primary Stepper Step Background Color Future State Design Big Circle',
		name: 'primaryStepperStepBackgroundColorFutureStateDesignBigCircle',
		defaultValue: 'transparent',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._primary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Future State',
		displayName: 'Secondary Stepper Step Background Color Future State Design Big Circle',
		name: 'secondaryStepperStepBackgroundColorFutureStateDesignBigCircle',
		defaultValue: 'transparent',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._secondary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Future State',
		displayName: 'Tertiary Stepper Step Background Color Future State Design Big Circle',
		name: 'tertiaryStepperStepBackgroundColorFutureStateDesignBigCircle',
		defaultValue: 'transparent',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._tertiary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Future State',
		displayName: 'Quaternary Stepper Step Background Color Future State Design Big Circle',
		name: 'quaternaryStepperStepBackgroundColorFutureStateDesignBigCircle',
		defaultValue: 'transparent',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._quaternary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Future State',
		displayName: 'Quinary Stepper Step Background Color Future State Design Big Circle',
		name: 'quinaryStepperStepBackgroundColorFutureStateDesignBigCircle',
		defaultValue: 'transparent',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._quinary ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Color Active',
		displayName: 'Primary Stepper Step Title Color Active Design Default',
		name: 'primaryStepperStepTitleColorActiveDesignDefault',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._primary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active',
		displayName: 'Secondary Stepper Step Title Color Active Design Default',
		name: 'secondaryStepperStepTitleColorActiveDesignDefault',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._secondary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active',
		displayName: 'Tertiary Stepper Step Title Color Active Design Default',
		name: 'tertiaryStepperStepTitleColorActiveDesignDefault',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._tertiary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active',
		displayName: 'Quaternary Stepper Step Title Color Active Design Default',
		name: 'quaternaryStepperStepTitleColorActiveDesignDefault',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quaternary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active',
		displayName: 'Quinary Stepper Step Title Color Active Design Default',
		name: 'quinaryStepperStepTitleColorActiveDesignDefault',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quinary ._title._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Color Active',
		displayName: 'Primary Stepper Step Title Color Active Design Big Circle',
		name: 'primaryStepperStepTitleColorActiveDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._primary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active',
		displayName: 'Secondary Stepper Step Title Color Active Design Big Circle',
		name: 'secondaryStepperStepTitleColorActiveDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._secondary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active',
		displayName: 'Tertiary Stepper Step Title Color Active Design Big Circle',
		name: 'tertiaryStepperStepTitleColorActiveDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._tertiary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active',
		displayName: 'Quaternary Stepper Step Title Color Active Design Big Circle',
		name: 'quaternaryStepperStepTitleColorActiveDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quaternary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active',
		displayName: 'Quinary Stepper Step Title Color Active Design Big Circle',
		name: 'quinaryStepperStepTitleColorActiveDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quinary ._title._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Primary Stepper Step Title Color Done State Design Default',
		name: 'primaryStepperStepTitleColorDoneStateDesignDefault',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._primary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Secondary Stepper Step Title Color Done State Design Default',
		name: 'secondaryStepperStepTitleColorDoneStateDesignDefault',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._secondary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Tertiary Stepper Step Title Color Done State Design Default',
		name: 'tertiaryStepperStepTitleColorDoneStateDesignDefault',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._tertiary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Quaternary Stepper Step Title Color Done State Design Default',
		name: 'quaternaryStepperStepTitleColorDoneStateDesignDefault',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quaternary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Quinary Stepper Step Title Color Done State Design Default',
		name: 'quinaryStepperStepTitleColorDoneStateDesignDefault',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quinary ._title._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Primary Stepper Step Title Color Done State Design Big Circle',
		name: 'primaryStepperStepTitleColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._primary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Secondary Stepper Step Title Color Done State Design Big Circle',
		name: 'secondaryStepperStepTitleColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._secondary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Tertiary Stepper Step Title Color Done State Design Big Circle',
		name: 'tertiaryStepperStepTitleColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._tertiary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Quaternary Stepper Step Title Color Done State Design Big Circle',
		name: 'quaternaryStepperStepTitleColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quaternary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Quinary Stepper Step Title Color Done State Design Big Circle',
		name: 'quinaryStepperStepTitleColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quinary ._title._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Title Font',
		displayName: 'Stepper Title Font Default Design',
		name: 'stepperTitleFontDefaultDesign',
		defaultValue: '<stepperFont>',
		cssProperty: 'font',
		selector: '.comp.compStepper._default ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Title Font',
		displayName: 'Stepper Title Font Big Circle',
		name: 'stepperTitleFontBigCircle',
		defaultValue: '<stepperFont>',
		cssProperty: 'font',
		selector: '.comp.compStepper._big_circle ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Title Font',
		displayName: 'Stepper Title Font Rectangle',
		name: 'stepperTitleFontRectangle',
		defaultValue: '<stepperFont>',
		cssProperty: 'font',
		selector: '.comp.compStepper._rectangle_arrow ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Title Font',
		displayName: 'Stepper Title Font Pills',
		name: 'stepperTitleFontPills',
		cssProperty: 'font',
		selector: '.comp.compStepper._pills ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Title Font Active',
		displayName: 'Stepper Title Font Active Default Design',
		name: 'stepperTitleFontActiveDefaultDesign',
		defaultValue: '<stepperFont>',
		cssProperty: 'font',
		selector: '.comp.compStepper._default ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Title Font Active',
		displayName: 'Stepper Title Font Active Big Circle',
		name: 'stepperTitleFontActiveBigCircle',
		defaultValue: '<stepperFont>',
		cssProperty: 'font',
		selector: '.comp.compStepper._big_circle ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Title Font Active',
		displayName: 'Stepper Title Font Active Rectangle',
		name: 'stepperTitleFontActiveRectangle',
		defaultValue: '<stepperFont>',
		cssProperty: 'font',
		selector: '.comp.compStepper._rectangle_arrow ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Title Font Active',
		displayName: 'Stepper Title Font Active Pills',
		name: 'stepperTitleFontActivePills',
		cssProperty: 'font',
		selector: '.comp.compStepper._pills ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Title Font Done',
		displayName: 'Stepper Title Font Done Default Design',
		name: 'stepperTitleFontDoneDefaultDesign',
		defaultValue: '<stepperFont>',
		cssProperty: 'font',
		selector: '.comp.compStepper._default ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Title Font Done',
		displayName: 'Stepper Title Font Done Big Circle',
		name: 'stepperTitleFontDoneBigCircle',
		defaultValue: '<stepperFont>',
		cssProperty: 'font',
		selector: '.comp.compStepper._big_circle ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Title Font Done',
		displayName: 'Stepper Title Font Done Rectangle',
		name: 'stepperTitleFontDoneRectangle',
		defaultValue: '<stepperFont>',
		cssProperty: 'font',
		selector: '.comp.compStepper._rectangle_arrow ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Title Font Done',
		displayName: 'Stepper Title Font Done Pills',
		name: 'stepperTitleFontDonePills',
		cssProperty: 'font',
		selector: '.comp.compStepper._pills ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Font',
		displayName: 'Stepper Step Font Default Design',
		name: 'stepperStepFontDefaultDesign',
		cssProperty: 'font',
		selector: '.comp.compStepper._default ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Font',
		displayName: 'Stepper Step Font Big Circle',
		name: 'stepperStepFontBigCircle',
		cssProperty: 'font',
		selector: '.comp.compStepper._big_circle ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Font',
		displayName: 'Stepper Step Font Rectangle',
		name: 'stepperStepFontRectangle',
		cssProperty: 'font',
		selector: '.comp.compStepper._rectangle_arrow ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Font Active',
		displayName: 'Stepper Step Font Active Default Design',
		name: 'stepperStepFontActiveDefaultDesign',
		cssProperty: 'font',
		selector: '.comp.compStepper._default ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Font Active',
		displayName: 'Stepper Step Font Active Big Circle',
		name: 'stepperStepFontActiveBigCircle',
		cssProperty: 'font',
		selector: '.comp.compStepper._big_circle ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Font Active',
		displayName: 'Stepper Step Font Active Rectangle',
		name: 'stepperStepFontActiveRectangle',
		cssProperty: 'font',
		selector: '.comp.compStepper._rectangle_arrow ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Font Done',
		displayName: 'Stepper Step Font Done Default Design',
		name: 'stepperStepFontDoneDefaultDesign',
		cssProperty: 'font',
		selector: '.comp.compStepper._default ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Font Done',
		displayName: 'Stepper Step Font Done Big Circle',
		name: 'stepperStepFontDoneBigCircle',
		cssProperty: 'font',
		selector: '.comp.compStepper._big_circle ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Font Done',
		displayName: 'Stepper Step Font Done Rectangle',
		name: 'stepperStepFontDoneRectangle',
		cssProperty: 'font',
		selector: '.comp.compStepper._rectangle_arrow ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Background Color Active',
		displayName: 'Stepper Step Title Background Color Active Design DefaultPrimary',
		name: 'stepperStepTitleBackgroundColorActiveDesignDefaultPrimary',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._primary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Background Color Active',
		displayName: 'Stepper Step Title Background Color Active Design DefaultSecondary',
		name: 'stepperStepTitleBackgroundColorActiveDesignDefaultSecondary',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._secondary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Background Color Active',
		displayName: 'Stepper Step Title Background Color Active Design DefaultTertiary',
		name: 'stepperStepTitleBackgroundColorActiveDesignDefaultTertiary',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._tertiary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Background Color Active',
		displayName: 'Stepper Step Title Background Color Active Design DefaultQuaternary',
		name: 'stepperStepTitleBackgroundColorActiveDesignDefaultQuaternary',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._quaternary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Background Color Active',
		displayName: 'Stepper Step Title Background Color Active Design DefaultQuinary',
		name: 'stepperStepTitleBackgroundColorActiveDesignDefaultQuinary',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._quinary ._listItem._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Background Color Done',
		displayName: 'Stepper Step Title Background Color Done Design DefaultPrimary',
		name: 'stepperStepTitleBackgroundColorDoneDesignDefaultPrimary',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._primary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Background Color Done',
		displayName: 'Stepper Step Title Background Color Done Design DefaultSecondary',
		name: 'stepperStepTitleBackgroundColorDoneDesignDefaultSecondary',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._secondary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Background Color Done',
		displayName: 'Stepper Step Title Background Color Done Design DefaultTertiary',
		name: 'stepperStepTitleBackgroundColorDoneDesignDefaultTertiary',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._tertiary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Background Color Done',
		displayName: 'Stepper Step Title Background Color Done Design DefaultQuaternary',
		name: 'stepperStepTitleBackgroundColorDoneDesignDefaultQuaternary',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._quaternary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Background Color Done',
		displayName: 'Stepper Step Title Background Color Done Design DefaultQuinary',
		name: 'stepperStepTitleBackgroundColorDoneDesignDefaultQuinary',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._quinary ._listItem._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Border Radius  Active',
		displayName: 'Stepper Step Title Border Radius  Active Design DefaultPrimary',
		name: 'stepperStepTitleBorderRadiusActiveDesignDefaultPrimary',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._default._primary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Border Radius  Active',
		displayName: 'Stepper Step Title Border Radius  Active Design DefaultSecondary',
		name: 'stepperStepTitleBorderRadiusActiveDesignDefaultSecondary',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._default._secondary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Border Radius  Active',
		displayName: 'Stepper Step Title Border Radius  Active Design DefaultTertiary',
		name: 'stepperStepTitleBorderRadiusActiveDesignDefaultTertiary',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._default._tertiary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Border Radius  Active',
		displayName: 'Stepper Step Title Border Radius  Active Design DefaultQuaternary',
		name: 'stepperStepTitleBorderRadiusActiveDesignDefaultQuaternary',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._default._quaternary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Border Radius  Active',
		displayName: 'Stepper Step Title Border Radius  Active Design DefaultQuinary',
		name: 'stepperStepTitleBorderRadiusActiveDesignDefaultQuinary',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._default._quinary ._listItem._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Border Radius  Done',
		displayName: 'Stepper Step Title Border Radius  Done Design DefaultPrimary',
		name: 'stepperStepTitleBorderRadiusDoneDesignDefaultPrimary',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._default._primary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Border Radius  Done',
		displayName: 'Stepper Step Title Border Radius  Done Design DefaultSecondary',
		name: 'stepperStepTitleBorderRadiusDoneDesignDefaultSecondary',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._default._secondary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Border Radius  Done',
		displayName: 'Stepper Step Title Border Radius  Done Design DefaultTertiary',
		name: 'stepperStepTitleBorderRadiusDoneDesignDefaultTertiary',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._default._tertiary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Border Radius  Done',
		displayName: 'Stepper Step Title Border Radius  Done Design DefaultQuaternary',
		name: 'stepperStepTitleBorderRadiusDoneDesignDefaultQuaternary',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._default._quaternary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Border Radius  Done',
		displayName: 'Stepper Step Title Border Radius  Done Design DefaultQuinary',
		name: 'stepperStepTitleBorderRadiusDoneDesignDefaultQuinary',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._default._quinary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Text Top Bottom Line Width',
		displayName: 'Stepper Step Text Top Bottom Line Width Design Default',
		name: 'stepperStepTextTopBottomLineWidthDesignDefault',
		defaultValue: '2px',
		cssProperty: 'width',
		selector: '.comp.compStepper._default._vertical ._listItem ._line',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Text Top Bottom Line Width',
		displayName: 'Stepper Step Text Top Bottom Line Width Design Big Circle',
		name: 'stepperStepTextTopBottomLineWidthDesignBigCircle',
		defaultValue: '2px',
		cssProperty: 'width',
		selector: '.comp.compStepper._big_circle._vertical ._listItem ._line',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
