import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Primary Stepper Step Line Color  Horizontal Design Default',
		name: 'primaryStepperStepLineColorHorizontalDesignDefault',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-bottom-color',
		selector:
			'.comp.compStepper._default._primary ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Secondary Stepper Step Line Color  Horizontal Design Default',
		name: 'secondaryStepperStepLineColorHorizontalDesignDefault',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-bottom-color',
		selector:
			'.comp.compStepper._default._secondary ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Tertiary Stepper Step Line Color  Horizontal Design Default',
		name: 'tertiaryStepperStepLineColorHorizontalDesignDefault',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-bottom-color',
		selector:
			'.comp.compStepper._default._tertiary ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quaternary Stepper Step Line Color  Horizontal Design Default',
		name: 'quaternaryStepperStepLineColorHorizontalDesignDefault',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-bottom-color',
		selector:
			'.comp.compStepper._default._quaternary ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quinary Stepper Step Line Color  Horizontal Design Default',
		name: 'quinaryStepperStepLineColorHorizontalDesignDefault',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-bottom-color',
		selector:
			'.comp.compStepper._default._quinary ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Primary Stepper Step Line Color  Horizontal Design Big Circle',
		name: 'primaryStepperStepLineColorHorizontalDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-bottom-color',
		selector:
			'.comp.compStepper._big_circle._primary ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Secondary Stepper Step Line Color  Horizontal Design Big Circle',
		name: 'secondaryStepperStepLineColorHorizontalDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-bottom-color',
		selector:
			'.comp.compStepper._big_circle._secondary ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Tertiary Stepper Step Line Color  Horizontal Design Big Circle',
		name: 'tertiaryStepperStepLineColorHorizontalDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-bottom-color',
		selector:
			'.comp.compStepper._big_circle._tertiary ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quaternary Stepper Step Line Color  Horizontal Design Big Circle',
		name: 'quaternaryStepperStepLineColorHorizontalDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-bottom-color',
		selector:
			'.comp.compStepper._big_circle._quaternary ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quinary Stepper Step Line Color  Horizontal Design Big Circle',
		name: 'quinaryStepperStepLineColorHorizontalDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-bottom-color',
		selector:
			'.comp.compStepper._big_circle._quinary ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Primary Stepper Step Line Color  Horizontal Text Top Design Default',
		name: 'primaryStepperStepLineColorHorizontalTextTopDesignDefault',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-top-color',
		selector:
			'.comp.compStepper._default._primary ul._horizontal._textTop ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Secondary Stepper Step Line Color  Horizontal Text Top Design Default',
		name: 'secondaryStepperStepLineColorHorizontalTextTopDesignDefault',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-top-color',
		selector:
			'.comp.compStepper._default._secondary ul._horizontal._textTop ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Tertiary Stepper Step Line Color  Horizontal Text Top Design Default',
		name: 'tertiaryStepperStepLineColorHorizontalTextTopDesignDefault',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-top-color',
		selector:
			'.comp.compStepper._default._tertiary ul._horizontal._textTop ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quaternary Stepper Step Line Color  Horizontal Text Top Design Default',
		name: 'quaternaryStepperStepLineColorHorizontalTextTopDesignDefault',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-top-color',
		selector:
			'.comp.compStepper._default._quaternary ul._horizontal._textTop ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quinary Stepper Step Line Color  Horizontal Text Top Design Default',
		name: 'quinaryStepperStepLineColorHorizontalTextTopDesignDefault',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-top-color',
		selector:
			'.comp.compStepper._default._quinary ul._horizontal._textTop ._listItem:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Primary Stepper Step Line Color  Horizontal Text Top Design Big Circle',
		name: 'primaryStepperStepLineColorHorizontalTextTopDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-top-color',
		selector:
			'.comp.compStepper._big_circle._primary ul._horizontal._textTop ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Secondary Stepper Step Line Color  Horizontal Text Top Design Big Circle',
		name: 'secondaryStepperStepLineColorHorizontalTextTopDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-top-color',
		selector:
			'.comp.compStepper._big_circle._secondary ul._horizontal._textTop ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Tertiary Stepper Step Line Color  Horizontal Text Top Design Big Circle',
		name: 'tertiaryStepperStepLineColorHorizontalTextTopDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-top-color',
		selector:
			'.comp.compStepper._big_circle._tertiary ul._horizontal._textTop ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quaternary Stepper Step Line Color  Horizontal Text Top Design Big Circle',
		name: 'quaternaryStepperStepLineColorHorizontalTextTopDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-top-color',
		selector:
			'.comp.compStepper._big_circle._quaternary ul._horizontal._textTop ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quinary Stepper Step Line Color  Horizontal Text Top Design Big Circle',
		name: 'quinaryStepperStepLineColorHorizontalTextTopDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-top-color',
		selector:
			'.comp.compStepper._big_circle._quinary ul._horizontal._textTop ._listItem:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Primary Stepper Step Line Color Vertical Design Default',
		name: 'primaryStepperStepLineColorVerticalDesignDefault',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._default._primary ul._vertical ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Secondary Stepper Step Line Color Vertical Design Default',
		name: 'secondaryStepperStepLineColorVerticalDesignDefault',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._default._secondary ul._vertical ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Tertiary Stepper Step Line Color Vertical Design Default',
		name: 'tertiaryStepperStepLineColorVerticalDesignDefault',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._default._tertiary ul._vertical ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quaternary Stepper Step Line Color Vertical Design Default',
		name: 'quaternaryStepperStepLineColorVerticalDesignDefault',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._default._quaternary ul._vertical ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quinary Stepper Step Line Color Vertical Design Default',
		name: 'quinaryStepperStepLineColorVerticalDesignDefault',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._default._quinary ul._vertical ._listItem:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Primary Stepper Step Line Color Vertical Design Big Circle',
		name: 'primaryStepperStepLineColorVerticalDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._big_circle._primary ul._vertical ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Secondary Stepper Step Line Color Vertical Design Big Circle',
		name: 'secondaryStepperStepLineColorVerticalDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._big_circle._secondary ul._vertical ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Tertiary Stepper Step Line Color Vertical Design Big Circle',
		name: 'tertiaryStepperStepLineColorVerticalDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._big_circle._tertiary ul._vertical ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quaternary Stepper Step Line Color Vertical Design Big Circle',
		name: 'quaternaryStepperStepLineColorVerticalDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._big_circle._quaternary ul._vertical ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quinary Stepper Step Line Color Vertical Design Big Circle',
		name: 'quinaryStepperStepLineColorVerticalDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._big_circle._quinary ul._vertical ._listItem:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Primary Stepper Step Line Color Vertical Text Right Design Default',
		name: 'primaryStepperStepLineColorVerticalTextRightDesignDefault',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-right-color',
		selector:
			'.comp.compStepper._default._primary ul._vertical._textRight ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Secondary Stepper Step Line Color Vertical Text Right Design Default',
		name: 'secondaryStepperStepLineColorVerticalTextRightDesignDefault',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-right-color',
		selector:
			'.comp.compStepper._default._secondary ul._vertical._textRight ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Tertiary Stepper Step Line Color Vertical Text Right Design Default',
		name: 'tertiaryStepperStepLineColorVerticalTextRightDesignDefault',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-right-color',
		selector:
			'.comp.compStepper._default._tertiary ul._vertical._textRight ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quaternary Stepper Step Line Color Vertical Text Right Design Default',
		name: 'quaternaryStepperStepLineColorVerticalTextRightDesignDefault',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-right-color',
		selector:
			'.comp.compStepper._default._quaternary ul._vertical._textRight ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quinary Stepper Step Line Color Vertical Text Right Design Default',
		name: 'quinaryStepperStepLineColorVerticalTextRightDesignDefault',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-right-color',
		selector:
			'.comp.compStepper._default._quinary ul._vertical._textRight ._listItem:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Primary Stepper Step Line Color Vertical Text Right Design Big Circle',
		name: 'primaryStepperStepLineColorVerticalTextRightDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-right-color',
		selector:
			'.comp.compStepper._big_circle._primary ul._vertical._textRight ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Secondary Stepper Step Line Color Vertical Text Right Design Big Circle',
		name: 'secondaryStepperStepLineColorVerticalTextRightDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-right-color',
		selector:
			'.comp.compStepper._big_circle._secondary ul._vertical._textRight ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Tertiary Stepper Step Line Color Vertical Text Right Design Big Circle',
		name: 'tertiaryStepperStepLineColorVerticalTextRightDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-right-color',
		selector:
			'.comp.compStepper._big_circle._tertiary ul._vertical._textRight ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quaternary Stepper Step Line Color Vertical Text Right Design Big Circle',
		name: 'quaternaryStepperStepLineColorVerticalTextRightDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-right-color',
		selector:
			'.comp.compStepper._big_circle._quaternary ul._vertical._textRight ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Color',
		displayName: 'Quinary Stepper Step Line Color Vertical Text Right Design Big Circle',
		name: 'quinaryStepperStepLineColorVerticalTextRightDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-right-color',
		selector:
			'.comp.compStepper._big_circle._quinary ul._vertical._textRight ._listItem:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Border',
		displayName: 'Primary Stepper Step Line Border  Horizontal Design Default',
		name: 'primaryStepperStepLineBorderHorizontalDesignDefault',
		defaultValue: '2px solid',
		cssProperty: 'border-bottom',
		selector: '.comp.compStepper._default ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Border',
		displayName: 'Primary Stepper Step Line Border  Horizontal Design Big Circle',
		name: 'primaryStepperStepLineBorderHorizontalDesignBigCircle',
		defaultValue: '2px solid',
		cssProperty: 'border-bottom',
		selector: '.comp.compStepper._big_circle ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Border',
		displayName: 'Primary Stepper Step Line Border  Horizontal Text Top Design Default',
		name: 'primaryStepperStepLineBorderHorizontalTextTopDesignDefault',
		defaultValue: '2px solid',
		cssProperty: 'border-top',
		selector:
			'.comp.compStepper._default ul._horizontal._textTop ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Border',
		displayName: 'Primary Stepper Step Line Border  Horizontal Text Top Design Big Circle',
		name: 'primaryStepperStepLineBorderHorizontalTextTopDesignBigCircle',
		defaultValue: '2px solid',
		cssProperty: 'border-top',
		selector:
			'.comp.compStepper._big_circle ul._horizontal._textTop ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Border',
		displayName: 'Primary Stepper Step Line Border Vertical Design Default',
		name: 'primaryStepperStepLineBorderVerticalDesignDefault',
		defaultValue: '2px solid',
		cssProperty: 'border-left',
		selector: '.comp.compStepper._default ul._vertical ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Border',
		displayName: 'Primary Stepper Step Line Border Vertical Design Big Circle',
		name: 'primaryStepperStepLineBorderVerticalDesignBigCircle',
		defaultValue: '2px solid',
		cssProperty: 'border-left',
		selector: '.comp.compStepper._big_circle ul._vertical ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Border',
		displayName: 'Primary Stepper Step Line Border Vertical Text Right Design Default',
		name: 'primaryStepperStepLineBorderVerticalTextRightDesignDefault',
		defaultValue: '2px solid',
		cssProperty: 'border-right',
		selector:
			'.comp.compStepper._default ul._vertical._textRight ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Border',
		displayName: 'Primary Stepper Step Line Border Vertical Text Right Design Big Circle',
		name: 'primaryStepperStepLineBorderVerticalTextRightDesignBigCircle',
		defaultValue: '2px solid',
		cssProperty: 'border-right',
		selector:
			'.comp.compStepper._big_circle ul._vertical._textRight ._listItem:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Circle Height',
		displayName: 'Stepper Step Circle Height Design Default',
		name: 'stepperStepCircleHeightDesignDefault',
		defaultValue: '32px',
		cssProperty: 'height',
		selector: '.comp.compStepper._default ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Circle Height',
		displayName: 'Stepper Step Circle Height Design Big Circle',
		name: 'stepperStepCircleHeightDesignBigCircle',
		defaultValue: '50px',
		cssProperty: 'height',
		selector: '.comp.compStepper._big_circle ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Circle Width',
		displayName: 'Stepper Step Circle Width Design Default',
		name: 'stepperStepCircleWidthDesignDefault',
		defaultValue: '32px',
		cssProperty: 'width',
		selector: '.comp.compStepper._default ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Circle Width',
		displayName: 'Stepper Step Circle Width Design Big Circle',
		name: 'stepperStepCircleWidthDesignBigCircle',
		defaultValue: '50px',
		cssProperty: 'width',
		selector: '.comp.compStepper._big_circle ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Min Width',
		displayName: 'Stepper Step Line Min Width Design Default',
		name: 'stepperStepLineMinWidthDesignDefault',
		defaultValue: '30px',
		cssProperty: 'min-width',
		selector: '.comp.compStepper._default ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Min Width',
		displayName: 'Stepper Step Line Min Width Design Big Circle',
		name: 'stepperStepLineMinWidthDesignBigCircle',
		defaultValue: '30px',
		cssProperty: 'min-width',
		selector: '.comp.compStepper._big_circle ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Min Height',
		displayName: 'Stepper Step Line Min Height Design Default',
		name: 'stepperStepLineMinHeightDesignDefault',
		defaultValue: '30px',
		cssProperty: 'min-height',
		selector: '.comp.compStepper._default ul._vertical ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Min Height',
		displayName: 'Stepper Step Line Min Height Design Big Circle',
		name: 'stepperStepLineMinHeightDesignBigCircle',
		defaultValue: '30px',
		cssProperty: 'min-height',
		selector: '.comp.compStepper._big_circle ul._vertical ._listItem:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Height',
		displayName: 'Stepper Step Line Height Design Default',
		name: 'stepperStepLineHeightDesignDefault',
		defaultValue: '16px',
		cssProperty: 'height',
		selector: '.comp.compStepper._default ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Height',
		displayName: 'Stepper Step Line Height Design Big Circle',
		name: 'stepperStepLineHeightDesignBigCircle',
		defaultValue: '25px',
		cssProperty: 'height',
		selector: '.comp.compStepper._big_circle ul._horizontal ._listItem:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Line Width',
		displayName: 'Stepper Step Line Width Design Default',
		name: 'stepperStepLineWidthDesignDefault',
		defaultValue: '16px',
		cssProperty: 'width',
		selector:
			'.comp.compStepper._default ul._vertical._textRight ._listItem:not(:last-child)::after,.comp.compStepper._default ul._vertical._textLeft ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Line Width',
		displayName: 'Stepper Step Line Width Design Big Circle',
		name: 'stepperStepLineWidthDesignBigCircle',
		defaultValue: '25px',
		cssProperty: 'width',
		selector:
			'.comp.compStepper._big_circle ul._vertical._textRight ._listItem:not(:last-child)::after,.comp.compStepper._big_circle ul._vertical._textLeft ._listItem:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Pill Width',
		displayName: 'Stepper Step Pill Width Design Pills',
		name: 'stepperStepPillWidthDesignPills',
		defaultValue: '48px',
		cssProperty: 'width',
		selector: '.comp.compStepper._pills ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Pill Height',
		displayName: 'Stepper Step Pill Height Design Pills',
		name: 'stepperStepPillHeightDesignPills',
		defaultValue: '16px',
		cssProperty: 'height',
		selector: '.comp.compStepper._pills ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Default State',
		displayName: 'Stepper Step Border Default State Design Default',
		name: 'stepperStepBorderDefaultStateDesignDefault',
		defaultValue: '2px solid',
		cssProperty: 'border',
		selector: '.comp.compStepper._default ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Default State',
		displayName: 'Stepper Step Border Default State Design Big Circle',
		name: 'stepperStepBorderDefaultStateDesignBigCircle',
		defaultValue: '2px solid',
		cssProperty: 'border',
		selector: '.comp.compStepper._big_circle ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Default State',
		displayName: 'Stepper Step Border Default State Design Pills',
		name: 'stepperStepBorderDefaultStateDesignPills',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._pills ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Default State',
		displayName: 'Stepper Step Border Default State Design Rectangle Arrow',
		name: 'stepperStepBorderDefaultStateDesignRectangleArrow',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._rectangle_arrow ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Active State',
		displayName: 'Stepper Step Border Active State Design Default',
		name: 'stepperStepBorderActiveStateDesignDefault',
		defaultValue: '2px solid',
		cssProperty: 'border',
		selector: '.comp.compStepper._default ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Active State',
		displayName: 'Stepper Step Border Active State Design Big Circle',
		name: 'stepperStepBorderActiveStateDesignBigCircle',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._big_circle ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Active State',
		displayName: 'Stepper Step Border Active State Design Pills',
		name: 'stepperStepBorderActiveStateDesignPills',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._pills ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Active State',
		displayName: 'Stepper Step Border Active State Design Rectangle Arrow',
		name: 'stepperStepBorderActiveStateDesignRectangleArrow',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._rectangle_arrow ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Done State',
		displayName: 'Stepper Step Border Done State Design Default',
		name: 'stepperStepBorderDoneStateDesignDefault',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._default ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Done State',
		displayName: 'Stepper Step Border Done State Design Big Circle',
		name: 'stepperStepBorderDoneStateDesignBigCircle',
		defaultValue: '2px solid',
		cssProperty: 'border',
		selector: '.comp.compStepper._big_circle ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Done State',
		displayName: 'Stepper Step Border Done State Design Pills',
		name: 'stepperStepBorderDoneStateDesignPills',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._pills ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Done State',
		displayName: 'Stepper Step Border Done State Design Rectangle Arrow',
		name: 'stepperStepBorderDoneStateDesignRectangleArrow',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compStepper._rectangle_arrow ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Radius',
		displayName: 'Stepper Step Border Radius Design Default',
		name: 'stepperStepBorderRadiusDesignDefault',
		defaultValue: '50%',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._default ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Radius',
		displayName: 'Stepper Step Border Radius Design Big Circle',
		name: 'stepperStepBorderRadiusDesignBigCircle',
		defaultValue: '50%',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._big_circle ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Radius',
		displayName: 'Stepper Step Border Radius Design Pills',
		name: 'stepperStepBorderRadiusDesignPills',
		defaultValue: '8px',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._pills ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Primary Stepper Step Border Color Default State Design Default',
		name: 'primaryStepperStepBorderColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._primary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Secondary Stepper Step Border Color Default State Design Default',
		name: 'secondaryStepperStepBorderColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._secondary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Tertiary Stepper Step Border Color Default State Design Default',
		name: 'tertiaryStepperStepBorderColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._tertiary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Quaternary Stepper Step Border Color Default State Design Default',
		name: 'quaternaryStepperStepBorderColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._quaternary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Quinary Stepper Step Border Color Default State Design Default',
		name: 'quinaryStepperStepBorderColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._quinary ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Primary Stepper Step Border Color Default State Design Big Circle',
		name: 'primaryStepperStepBorderColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._primary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Secondary Stepper Step Border Color Default State Design Big Circle',
		name: 'secondaryStepperStepBorderColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._secondary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Tertiary Stepper Step Border Color Default State Design Big Circle',
		name: 'tertiaryStepperStepBorderColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._tertiary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Quaternary Stepper Step Border Color Default State Design Big Circle',
		name: 'quaternaryStepperStepBorderColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._quaternary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Default State',
		displayName: 'Quinary Stepper Step Border Color Default State Design Big Circle',
		name: 'quinaryStepperStepBorderColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._quinary ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Color Active State',
		displayName: 'Primary Stepper Step Border Color Active State Design Default',
		name: 'primaryStepperStepBorderColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._primary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Active State',
		displayName: 'Secondary Stepper Step Border Color Active State Design Default',
		name: 'secondaryStepperStepBorderColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._secondary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Active State',
		displayName: 'Tertiary Stepper Step Border Color Active State Design Default',
		name: 'tertiaryStepperStepBorderColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._tertiary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Active State',
		displayName: 'Quaternary Stepper Step Border Color Active State Design Default',
		name: 'quaternaryStepperStepBorderColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._quaternary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Active State',
		displayName: 'Quinary Stepper Step Border Color Active State Design Default',
		name: 'quinaryStepperStepBorderColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._default._quinary ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Border Color Done State',
		displayName: 'Primary Stepper Step Border Color Done State Design Big Circle',
		name: 'primaryStepperStepBorderColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._primary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Done State',
		displayName: 'Secondary Stepper Step Border Color Done State Design Big Circle',
		name: 'secondaryStepperStepBorderColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._secondary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Done State',
		displayName: 'Tertiary Stepper Step Border Color Done State Design Big Circle',
		name: 'tertiaryStepperStepBorderColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._tertiary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Done State',
		displayName: 'Quaternary Stepper Step Border Color Done State Design Big Circle',
		name: 'quaternaryStepperStepBorderColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._quaternary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Border Color Done State',
		displayName: 'Quinary Stepper Step Border Color Done State Design Big Circle',
		name: 'quinaryStepperStepBorderColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compStepper._big_circle._quinary ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Primary Stepper Step Background Color Done State Design Default',
		name: 'primaryStepperStepBackgroundColorDoneStateDesignDefault',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._primary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Secondary Stepper Step Background Color Done State Design Default',
		name: 'secondaryStepperStepBackgroundColorDoneStateDesignDefault',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._secondary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Tertiary Stepper Step Background Color Done State Design Default',
		name: 'tertiaryStepperStepBackgroundColorDoneStateDesignDefault',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._tertiary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Quaternary Stepper Step Background Color Done State Design Default',
		name: 'quaternaryStepperStepBackgroundColorDoneStateDesignDefault',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._quaternary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Quinary Stepper Step Background Color Done State Design Default',
		name: 'quinaryStepperStepBackgroundColorDoneStateDesignDefault',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._default._quinary ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Primary Stepper Step Background Color Active State Design Big Circle',
		name: 'primaryStepperStepBackgroundColorActiveStateDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._primary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Secondary Stepper Step Background Color Active State Design Big Circle',
		name: 'secondaryStepperStepBackgroundColorActiveStateDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._secondary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Tertiary Stepper Step Background Color Active State Design Big Circle',
		name: 'tertiaryStepperStepBackgroundColorActiveStateDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._tertiary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Quaternary Stepper Step Background Color Active State Design Big Circle',
		name: 'quaternaryStepperStepBackgroundColorActiveStateDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._quaternary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Quinary Stepper Step Background Color Active State Design Big Circle',
		name: 'quinaryStepperStepBackgroundColorActiveStateDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._big_circle._quinary ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Primary Stepper Step Color Default State Design Default',
		name: 'primaryStepperStepColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._primary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Secondary Stepper Step Color Default State Design Default',
		name: 'secondaryStepperStepColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._secondary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Tertiary Stepper Step Color Default State Design Default',
		name: 'tertiaryStepperStepColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._tertiary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Quaternary Stepper Step Color Default State Design Default',
		name: 'quaternaryStepperStepColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quaternary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Quinary Stepper Step Color Default State Design Default',
		name: 'quinaryStepperStepColorDefaultStateDesignDefault',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quinary ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Primary Stepper Step Color Default State Design Big Circle',
		name: 'primaryStepperStepColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._primary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Secondary Stepper Step Color Default State Design Big Circle',
		name: 'secondaryStepperStepColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._secondary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Tertiary Stepper Step Color Default State Design Big Circle',
		name: 'tertiaryStepperStepColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._tertiary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Quaternary Stepper Step Color Default State Design Big Circle',
		name: 'quaternaryStepperStepColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quaternary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Quinary Stepper Step Color Default State Design Big Circle',
		name: 'quinaryStepperStepColorDefaultStateDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quinary ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Primary Stepper Step Color Active State Design Default',
		name: 'primaryStepperStepColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._primary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Secondary Stepper Step Color Active State Design Default',
		name: 'secondaryStepperStepColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._secondary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Tertiary Stepper Step Color Active State Design Default',
		name: 'tertiaryStepperStepColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._tertiary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Quaternary Stepper Step Color Active State Design Default',
		name: 'quaternaryStepperStepColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quaternary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Quinary Stepper Step Color Active State Design Default',
		name: 'quinaryStepperStepColorActiveStateDesignDefault',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quinary ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Primary Stepper Step Color Active State Design Big Circle',
		name: 'primaryStepperStepColorActiveStateDesignBigCircle',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._primary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Secondary Stepper Step Color Active State Design Big Circle',
		name: 'secondaryStepperStepColorActiveStateDesignBigCircle',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._secondary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Tertiary Stepper Step Color Active State Design Big Circle',
		name: 'tertiaryStepperStepColorActiveStateDesignBigCircle',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._tertiary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Quaternary Stepper Step Color Active State Design Big Circle',
		name: 'quaternaryStepperStepColorActiveStateDesignBigCircle',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quaternary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Quinary Stepper Step Color Active State Design Big Circle',
		name: 'quinaryStepperStepColorActiveStateDesignBigCircle',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quinary ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Primary Stepper Step Color Done State Design Default',
		name: 'primaryStepperStepColorDoneStateDesignDefault',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._primary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Secondary Stepper Step Color Done State Design Default',
		name: 'secondaryStepperStepColorDoneStateDesignDefault',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._secondary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Tertiary Stepper Step Color Done State Design Default',
		name: 'tertiaryStepperStepColorDoneStateDesignDefault',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._tertiary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Quaternary Stepper Step Color Done State Design Default',
		name: 'quaternaryStepperStepColorDoneStateDesignDefault',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quaternary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Quinary Stepper Step Color Done State Design Default',
		name: 'quinaryStepperStepColorDoneStateDesignDefault',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quinary ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Primary Stepper Step Color Done State Design Big Circle',
		name: 'primaryStepperStepColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._primary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Secondary Stepper Step Color Done State Design Big Circle',
		name: 'secondaryStepperStepColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._secondary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Tertiary Stepper Step Color Done State Design Big Circle',
		name: 'tertiaryStepperStepColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._tertiary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Quaternary Stepper Step Color Done State Design Big Circle',
		name: 'quaternaryStepperStepColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quaternary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Quinary Stepper Step Color Done State Design Big Circle',
		name: 'quinaryStepperStepColorDoneStateDesignBigCircle',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quinary ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Primary Stepper Step Title Color Design Default',
		name: 'primaryStepperStepTitleColorDesignDefault',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._primary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Secondary Stepper Step Title Color Design Default',
		name: 'secondaryStepperStepTitleColorDesignDefault',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._secondary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Tertiary Stepper Step Title Color Design Default',
		name: 'tertiaryStepperStepTitleColorDesignDefault',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._tertiary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Quaternary Stepper Step Title Color Design Default',
		name: 'quaternaryStepperStepTitleColorDesignDefault',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quaternary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Quinary Stepper Step Title Color Design Default',
		name: 'quinaryStepperStepTitleColorDesignDefault',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._default._quinary ._title',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Primary Stepper Step Title Color Design Big Circle',
		name: 'primaryStepperStepTitleColorDesignBigCircle',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._primary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Secondary Stepper Step Title Color Design Big Circle',
		name: 'secondaryStepperStepTitleColorDesignBigCircle',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._secondary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Tertiary Stepper Step Title Color Design Big Circle',
		name: 'tertiaryStepperStepTitleColorDesignBigCircle',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._tertiary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Quaternary Stepper Step Title Color Design Big Circle',
		name: 'quaternaryStepperStepTitleColorDesignBigCircle',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quaternary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color',
		displayName: 'Quinary Stepper Step Title Color Design Big Circle',
		name: 'quinaryStepperStepTitleColorDesignBigCircle',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._big_circle._quinary ._title',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Padding',
		displayName: 'Stepper Step Title Padding Design Default',
		name: 'stepperStepTitlePaddingDesignDefault',
		defaultValue: '5px',
		cssProperty: 'padding',
		selector: '.comp.compStepper._default ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Padding',
		displayName: 'Stepper Step Title Padding Design Big Circle',
		name: 'stepperStepTitlePaddingDesignBigCircle',
		defaultValue: '8px',
		cssProperty: 'padding',
		selector: '.comp.compStepper._big_circle ._title',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Primary Stepper Step Background Color Default State Design Pills',
		name: 'primaryStepperStepBackgroundColorDefaultStateDesignPills',
		defaultValue: '<backgroundHoverColorSeven>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._primary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Secondary Stepper Step Background Color Default State Design Pills',
		name: 'secondaryStepperStepBackgroundColorDefaultStateDesignPills',
		defaultValue: '<backgroundHoverColorSeven>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._secondary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Tertiary Stepper Step Background Color Default State Design Pills',
		name: 'tertiaryStepperStepBackgroundColorDefaultStateDesignPills',
		defaultValue: '<backgroundHoverColorSeven>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._tertiary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Quaternary Stepper Step Background Color Default State Design Pills',
		name: 'quaternaryStepperStepBackgroundColorDefaultStateDesignPills',
		defaultValue: '<backgroundHoverColorSeven>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._quaternary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Quinary Stepper Step Background Color Default State Design Pills',
		name: 'quinaryStepperStepBackgroundColorDefaultStateDesignPills',
		defaultValue: '<backgroundHoverColorSeven>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._quinary ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Primary Stepper Step Background Color Active State Design Pills',
		name: 'primaryStepperStepBackgroundColorActiveStateDesignPills',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._primary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Secondary Stepper Step Background Color Active State Design Pills',
		name: 'secondaryStepperStepBackgroundColorActiveStateDesignPills',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._secondary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Tertiary Stepper Step Background Color Active State Design Pills',
		name: 'tertiaryStepperStepBackgroundColorActiveStateDesignPills',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._tertiary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Quaternary Stepper Step Background Color Active State Design Pills',
		name: 'quaternaryStepperStepBackgroundColorActiveStateDesignPills',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._quaternary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Quinary Stepper Step Background Color Active State Design Pills',
		name: 'quinaryStepperStepBackgroundColorActiveStateDesignPills',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._quinary ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Primary Stepper Step Background Color Done State Design Pills',
		name: 'primaryStepperStepBackgroundColorDoneStateDesignPills',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._primary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Secondary Stepper Step Background Color Done State Design Pills',
		name: 'secondaryStepperStepBackgroundColorDoneStateDesignPills',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._secondary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Tertiary Stepper Step Background Color Done State Design Pills',
		name: 'tertiaryStepperStepBackgroundColorDoneStateDesignPills',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._tertiary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Quaternary Stepper Step Background Color Done State Design Pills',
		name: 'quaternaryStepperStepBackgroundColorDoneStateDesignPills',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._quaternary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Quinary Stepper Step Background Color Done State Design Pills',
		name: 'quinaryStepperStepBackgroundColorDoneStateDesignPills',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._pills._quinary ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Primary Stepper Step Color Default State Design Pills',
		name: 'primaryStepperStepColorDefaultStateDesignPills',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._primary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Secondary Stepper Step Color Default State Design Pills',
		name: 'secondaryStepperStepColorDefaultStateDesignPills',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._secondary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Tertiary Stepper Step Color Default State Design Pills',
		name: 'tertiaryStepperStepColorDefaultStateDesignPills',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._tertiary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Quaternary Stepper Step Color Default State Design Pills',
		name: 'quaternaryStepperStepColorDefaultStateDesignPills',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._quaternary ._step',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Default State',
		displayName: 'Quinary Stepper Step Color Default State Design Pills',
		name: 'quinaryStepperStepColorDefaultStateDesignPills',
		defaultValue: '<colorThirteen>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._quinary ._step',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Primary Stepper Step Color Active State Design Pills',
		name: 'primaryStepperStepColorActiveStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._primary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Secondary Stepper Step Color Active State Design Pills',
		name: 'secondaryStepperStepColorActiveStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._secondary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Tertiary Stepper Step Color Active State Design Pills',
		name: 'tertiaryStepperStepColorActiveStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._tertiary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Quaternary Stepper Step Color Active State Design Pills',
		name: 'quaternaryStepperStepColorActiveStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._quaternary ._step._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Active State',
		displayName: 'Quinary Stepper Step Color Active State Design Pills',
		name: 'quinaryStepperStepColorActiveStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._quinary ._step._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Primary Stepper Step Color Done State Design Pills',
		name: 'primaryStepperStepColorDoneStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._primary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Secondary Stepper Step Color Done State Design Pills',
		name: 'secondaryStepperStepColorDoneStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._secondary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Tertiary Stepper Step Color Done State Design Pills',
		name: 'tertiaryStepperStepColorDoneStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._tertiary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Quaternary Stepper Step Color Done State Design Pills',
		name: 'quaternaryStepperStepColorDoneStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._quaternary ._step._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Color Done State',
		displayName: 'Quinary Stepper Step Color Done State Design Pills',
		name: 'quinaryStepperStepColorDoneStateDesignPills',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._pills._quinary ._step._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Gap',
		displayName: 'Stepper Gap Design Pills',
		name: 'stepperGapDesignPills',
		defaultValue: '8px',
		cssProperty: 'gap',
		selector: '.comp.compStepper._pills ul',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Border Radius',
		displayName: 'Stepper Border Radius Design Rectangle Arrow',
		name: 'stepperBorderRadiusDesignRectangleArrow',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compStepper._rectangle_arrow ul',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Box Shadow',
		displayName: 'Stepper Box Shadow Design Rectangle Arrow',
		name: 'stepperBoxShadowDesignRectangleArrow',
		defaultValue: '0px 1px 4px 0px rgba(0, 0, 0, 0.10)',
		cssProperty: 'box-shadow',
		selector: '.comp.compStepper._rectangle_arrow ul',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Background Color',
		displayName: 'Primary Stepper Background Color Design Rectangle Arrow',
		name: 'primaryStepperBackgroundColorDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._primary ul',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Background Color',
		displayName: 'Secondary Stepper Background Color Design Rectangle Arrow',
		name: 'secondaryStepperBackgroundColorDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._secondary ul',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Background Color',
		displayName: 'Tertiary Stepper Background Color Design Rectangle Arrow',
		name: 'tertiaryStepperBackgroundColorDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._tertiary ul',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Background Color',
		displayName: 'Quaternary Stepper Background Color Design Rectangle Arrow',
		name: 'quaternaryStepperBackgroundColorDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._quaternary ul',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Background Color',
		displayName: 'Quinary Stepper Background Color Design Rectangle Arrow',
		name: 'quinaryStepperBackgroundColorDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._quinary ul',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Padding',
		displayName: 'Stepper Step Padding Design Rectangle Arrow',
		name: 'stepperStepPaddingDesignRectangleArrow',
		defaultValue: '30px',
		cssProperty: 'padding-left',
		selector: '.comp.compStepper._rectangle_arrow ._listItem',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Height',
		displayName: 'Stepper Step Height Design Rectangle Arrow',
		name: 'stepperStepHeightDesignRectangleArrow',
		defaultValue: '48px',
		cssProperty: 'height',
		selector: '.comp.compStepper._rectangle_arrow ._listItem',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Primary Stepper Step Background Color Default State Design Rectangle Arrow',
		name: 'primaryStepperStepBackgroundColorDefaultStateDesignRectangleArrow',
		defaultValue: 'transparent',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._primary ._listItem',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Secondary Stepper Step Background Color Default State Design Rectangle Arrow',
		name: 'secondaryStepperStepBackgroundColorDefaultStateDesignRectangleArrow',
		defaultValue: 'transparent',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._secondary ._listItem',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Tertiary Stepper Step Background Color Default State Design Rectangle Arrow',
		name: 'tertiaryStepperStepBackgroundColorDefaultStateDesignRectangleArrow',
		defaultValue: 'transparent',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._tertiary ._listItem',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName:
			'Quaternary Stepper Step Background Color Default State Design Rectangle Arrow',
		name: 'quaternaryStepperStepBackgroundColorDefaultStateDesignRectangleArrow',
		defaultValue: 'transparent',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._quaternary ._listItem',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Default State',
		displayName: 'Quinary Stepper Step Background Color Default State Design Rectangle Arrow',
		name: 'quinaryStepperStepBackgroundColorDefaultStateDesignRectangleArrow',
		defaultValue: 'transparent',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._quinary ._listItem',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Primary Stepper Step Background Color Active State Design Rectangle Arrow',
		name: 'primaryStepperStepBackgroundColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._primary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Secondary Stepper Step Background Color Active State Design Rectangle Arrow',
		name: 'secondaryStepperStepBackgroundColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._secondary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Tertiary Stepper Step Background Color Active State Design Rectangle Arrow',
		name: 'tertiaryStepperStepBackgroundColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._tertiary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Quaternary Stepper Step Background Color Active State Design Rectangle Arrow',
		name: 'quaternaryStepperStepBackgroundColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._quaternary ._listItem._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Active State',
		displayName: 'Quinary Stepper Step Background Color Active State Design Rectangle Arrow',
		name: 'quinaryStepperStepBackgroundColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._quinary ._listItem._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Primary Stepper Step Background Color Done State Design Rectangle Arrow',
		name: 'primaryStepperStepBackgroundColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._primary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Secondary Stepper Step Background Color Done State Design Rectangle Arrow',
		name: 'secondaryStepperStepBackgroundColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._secondary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Tertiary Stepper Step Background Color Done State Design Rectangle Arrow',
		name: 'tertiaryStepperStepBackgroundColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._tertiary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Quaternary Stepper Step Background Color Done State Design Rectangle Arrow',
		name: 'quaternaryStepperStepBackgroundColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._quaternary ._listItem._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Background Color Done State',
		displayName: 'Quinary Stepper Step Background Color Done State Design Rectangle Arrow',
		name: 'quinaryStepperStepBackgroundColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compStepper._rectangle_arrow._quinary ._listItem._done',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Arrow Border Top',
		displayName: 'Stepper Step Arrow Border Top Design Rectangle Arrow',
		name: 'stepperStepArrowBorderTopDesignRectangleArrow',
		defaultValue: '24px solid transparent',
		cssProperty: 'border-top',
		selector: '.comp.compStepper._rectangle_arrow ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left',
		displayName: 'Stepper Step Arrow Border Left Design Rectangle Arrow',
		name: 'stepperStepArrowBorderLeftDesignRectangleArrow',
		defaultValue: '20px solid transparent',
		cssProperty: 'border-left',
		selector: '.comp.compStepper._rectangle_arrow ._listItem:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Bottom',
		displayName: 'Stepper Step Arrow Border Bottom Design Rectangle Arrow',
		name: 'stepperStepArrowBorderBottomDesignRectangleArrow',
		defaultValue: '24px solid transparent',
		cssProperty: 'border-bottom',
		selector: '.comp.compStepper._rectangle_arrow ._listItem:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Arrow Border Left Color Active State',
		displayName:
			'Primary Stepper Step Arrow Border Left Color Active State Design Rectangle Arrow',
		name: 'primaryStepperStepArrowBorderLeftColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._rectangle_arrow._primary ._listItem._active:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Active State',
		displayName:
			'Secondary Stepper Step Arrow Border Left Color Active State Design Rectangle Arrow',
		name: 'secondaryStepperStepArrowBorderLeftColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._rectangle_arrow._secondary ._listItem._active:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Active State',
		displayName:
			'Tertiary Stepper Step Arrow Border Left Color Active State Design Rectangle Arrow',
		name: 'tertiaryStepperStepArrowBorderLeftColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._rectangle_arrow._tertiary ._listItem._active:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Active State',
		displayName:
			'Quaternary Stepper Step Arrow Border Left Color Active State Design Rectangle Arrow',
		name: 'quaternaryStepperStepArrowBorderLeftColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._rectangle_arrow._quaternary ._listItem._active:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Active State',
		displayName:
			'Quinary Stepper Step Arrow Border Left Color Active State Design Rectangle Arrow',
		name: 'quinaryStepperStepArrowBorderLeftColorActiveStateDesignRectangleArrow',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._rectangle_arrow._quinary ._listItem._active:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Arrow Border Left Color Done State',
		displayName:
			'Primary Stepper Step Arrow Border Left Color Done State Design Rectangle Arrow',
		name: 'primaryStepperStepArrowBorderLeftColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._rectangle_arrow._primary ._listItem._done:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Done State',
		displayName:
			'Secondary Stepper Step Arrow Border Left Color Done State Design Rectangle Arrow',
		name: 'secondaryStepperStepArrowBorderLeftColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._rectangle_arrow._secondary ._listItem._done:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Done State',
		displayName:
			'Tertiary Stepper Step Arrow Border Left Color Done State Design Rectangle Arrow',
		name: 'tertiaryStepperStepArrowBorderLeftColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._rectangle_arrow._tertiary ._listItem._done:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Done State',
		displayName:
			'Quaternary Stepper Step Arrow Border Left Color Done State Design Rectangle Arrow',
		name: 'quaternaryStepperStepArrowBorderLeftColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._rectangle_arrow._quaternary ._listItem._done:not(:last-child)::after',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Arrow Border Left Color Done State',
		displayName:
			'Quinary Stepper Step Arrow Border Left Color Done State Design Rectangle Arrow',
		name: 'quinaryStepperStepArrowBorderLeftColorDoneStateDesignRectangleArrow',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-left-color',
		selector:
			'.comp.compStepper._rectangle_arrow._quinary ._listItem._done:not(:last-child)::after',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Color Default State',
		displayName: 'Primary Stepper Step Title Color Default State Design Rectangle Arrow',
		name: 'primaryStepperStepTitleColorDefaultStateDesignRectangleArrow',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._primary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Default State',
		displayName: 'Secondary Stepper Step Title Color Default State Design Rectangle Arrow',
		name: 'secondaryStepperStepTitleColorDefaultStateDesignRectangleArrow',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._secondary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Default State',
		displayName: 'Tertiary Stepper Step Title Color Default State Design Rectangle Arrow',
		name: 'tertiaryStepperStepTitleColorDefaultStateDesignRectangleArrow',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._tertiary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Default State',
		displayName: 'Quaternary Stepper Step Title Color Default State Design Rectangle Arrow',
		name: 'quaternaryStepperStepTitleColorDefaultStateDesignRectangleArrow',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._quaternary ._title',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Default State',
		displayName: 'Quinary Stepper Step Title Color Default State Design Rectangle Arrow',
		name: 'quinaryStepperStepTitleColorDefaultStateDesignRectangleArrow',
		defaultValue: '<colorSix>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._quinary ._title',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Color Active State',
		displayName: 'Primary Stepper Step Title Color Active State Design Rectangle Arrow',
		name: 'primaryStepperStepTitleColorActiveStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._primary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active State',
		displayName: 'Secondary Stepper Step Title Color Active State Design Rectangle Arrow',
		name: 'secondaryStepperStepTitleColorActiveStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._secondary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active State',
		displayName: 'Tertiary Stepper Step Title Color Active State Design Rectangle Arrow',
		name: 'tertiaryStepperStepTitleColorActiveStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._tertiary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active State',
		displayName: 'Quaternary Stepper Step Title Color Active State Design Rectangle Arrow',
		name: 'quaternaryStepperStepTitleColorActiveStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._quaternary ._title._active',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Active State',
		displayName: 'Quinary Stepper Step Title Color Active State Design Rectangle Arrow',
		name: 'quinaryStepperStepTitleColorActiveStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._quinary ._title._active',
		noPrefix: true,
	},

	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Primary Stepper Step Title Color Done State Design Rectangle Arrow',
		name: 'primaryStepperStepTitleColorDoneStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._primary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Secondary Stepper Step Title Color Done State Design Rectangle Arrow',
		name: 'secondaryStepperStepTitleColorDoneStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._secondary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Tertiary Stepper Step Title Color Done State Design Rectangle Arrow',
		name: 'tertiaryStepperStepTitleColorDoneStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._tertiary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Quaternary Stepper Step Title Color Done State Design Rectangle Arrow',
		name: 'quaternaryStepperStepTitleColorDoneStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._quaternary ._title._done',
		noPrefix: true,
	},
	{
		groupName: 'Stepper Step Title Color Done State',
		displayName: 'Quinary Stepper Step Title Color Done State Design Rectangle Arrow',
		name: 'quinaryStepperStepTitleColorDoneStateDesignRectangleArrow',
		defaultValue: '<colorSeven>',
		cssProperty: 'color',
		selector: '.comp.compStepper._rectangle_arrow._quinary ._title._done',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
