import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'Video Range Slider Accent Color',
		displayName: 'Primary Video Range Slider Accent Color',
		name: 'primaryVideoRangeSliderAccentColor',
		defaultValue: '<backgroundColorOne>',
		description: 'rangeSlider design one primary  color',
		cssProperty: 'accent-color',
		selector:
			'.comp.compVideo._videoDesign1._primary input[type="range"], .comp.compVideo._videoDesign2._primary input[type="range"], .comp.compVideo._videoDesign3._primary input[type="range"], .comp.compVideo._videoDesign4._primary input[type="range"]',
		noPrefix: true,
	},
	{
		groupName: 'Video Range Slider Accent Color',
		displayName: 'Secondary Video Range Slider Accent Color',
		name: 'secondaryVideoRangeSliderAccentColor',
		defaultValue: '<backgroundColorTwo>',
		description: 'rangeSlider design one secondary  color',
		cssProperty: 'accent-color',
		selector:
			'.comp.compVideo._videoDesign1._secondary input[type="range"], .comp.compVideo._videoDesign2._secondary input[type="range"], .comp.compVideo._videoDesign3._secondary input[type="range"], .comp.compVideo._videoDesign4._secondary input[type="range"]',
		noPrefix: true,
	},
	{
		groupName: 'Video Range Slider Accent Color',
		displayName: 'Tertiary Video Range Slider Accent Color',
		name: 'tertiaryVideoRangeSliderAccentColor',
		defaultValue: '<backgroundColorThree>',
		description: 'rangeSlider design one tertiary  color',
		cssProperty: 'accent-color',
		selector:
			'.comp.compVideo._videoDesign1._tertiary input[type="range"], .comp.compVideo._videoDesign2._tertiary input[type="range"], .comp.compVideo._videoDesign3._tertiary input[type="range"], .comp.compVideo._videoDesign4._tertiary input[type="range"]',
		noPrefix: true,
	},
	{
		groupName: 'Video Range Slider Accent Color',
		displayName: 'Quaternary Video Range Slider Accent Color',
		name: 'quaternaryVideoRangeSliderAccentColor',
		defaultValue: '<backgroundColorFour>',
		description: 'rangeSlider design one quaternary  color ',
		cssProperty: 'accent-color',
		selector:
			'.comp.compVideo._videoDesign1._quaternary input[type="range"], .comp.compVideo._videoDesign2._quaternary input[type="range"], .comp.compVideo._videoDesign3._quaternary input[type="range"], .comp.compVideo._videoDesign4._quaternary input[type="range"]',
		noPrefix: true,
	},
	{
		groupName: 'Video Range Slider Accent Color',
		displayName: 'Quinary Video Range Slider Accent Color',
		name: 'quinaryVideoRangeSliderAccentColor',
		defaultValue: '<backgroundColorFive>',
		description: 'rangeSlider design one quinary  color',
		cssProperty: 'accent-color',
		selector:
			'.comp.compVideo._videoDesign1._quinary input[type="range"], .comp.compVideo._videoDesign2._quinary input[type="range"], .comp.compVideo._videoDesign3._quinary input[type="range"], .comp.compVideo._videoDesign4._quinary input[type="range"]',
		noPrefix: true,
	},

	{
		groupName: 'Video Range Slider Height',
		displayName: 'Video Range Slider Height Design One',
		name: 'videoRangeSliderHeightDesignOne',
		defaultValue: '3px',
		description: 'rangeSlider Height for Design One',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign1 input[type="range"]',
		noPrefix: true,
	},
	{
		groupName: 'Video Range Slider Height',
		displayName: 'Video Range Slider Height Design Two',
		name: 'videoRangeSliderHeightDesignTwo',
		defaultValue: '3px',
		description: 'rangeSlider Height for Design Two',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign2 input[type="range"]',
		noPrefix: true,
	},
	{
		groupName: 'Video Range Slider Height',
		displayName: 'Video Range Slider Height Design Three',
		name: 'videoRangeSliderHeightDesignThree',
		defaultValue: '3px',
		description: 'rangeSlider Height for Design Three',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign3 input[type="range"]',
		noPrefix: true,
	},
	{
		groupName: 'Video Range Slider Height',
		displayName: 'Video Range Slider Height Design Four',
		name: 'videoRangeSliderHeightDesignFour',
		defaultValue: '3px',
		description: 'rangeSlider Height for Design Four',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign4 input[type="range"]',
		noPrefix: true,
	},

	{
		groupName: 'VideoProgressBarWidthDesignOne',
		displayName: 'ProgressBar Width DesignOne',
		name: 'progressBarWidthDesignOne',
		defaultValue: '0.99',
		description: 'Progress bar width for design one',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign1 ._progressBar',
		noPrefix: true,
	},

	{
		groupName: 'Video progress Bar container Padding',
		displayName: 'Video progress Bar container PaddingDesign One',
		name: 'videoprogressBarcontainerPaddingDesignOne',
		defaultValue: '0px 8px 0px 4px',
		description: 'Progress bar container padding',
		cssProperty: 'padding',
		selector: '.comp.compVideo ._progressBarContainer',
		noPrefix: true,
	},

	{
		groupName: 'VideoProgressBarCursorAll',
		displayName: 'ProgressBar Cursor All',
		name: 'ProgressBarCursorAll',
		defaultValue: 'pointer',
		description: 'progress bar cursor for all',
		cssProperty: 'cursor',
		selector: '.comp.compVideo ._progressBar',
		noPrefix: true,
	},

	{
		groupName: 'Video Progress Bar ToolTip Color',
		displayName: 'Video Progress Bar ToolTip Color All Designs',
		name: 'videoProgressBarToolTipColorAllDesigns',
		defaultValue: '<fontColorTwo>',
		description: 'progress bar tooltip color All designs.',
		cssProperty: 'color',
		selector: '.comp.compVideo ._toolTip',
		noPrefix: true,
	},

	{
		groupName: 'Video Time Color',
		displayName: 'Video Time Color Design One',
		name: 'videoTimeColorDesignOne',
		defaultValue: '<fontColorTwo>',
		description: 'Video time color for Design One',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign1 ._time',
		noPrefix: true,
	},
	{
		groupName: 'Video Time Color',
		displayName: 'Video Time Color Design Two',
		name: 'videoTimeColorDesignTwo',
		defaultValue: '<fontColorTwo>',
		description: 'Video time color for Design Two',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign2 ._time',
		noPrefix: true,
	},
	{
		groupName: 'Video Time Color',
		displayName: 'Video Time Color Design Three',
		name: 'videoTimeColorDesignThree',
		defaultValue: '<fontColorTwo>',
		description: 'Video time color for Design Three',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign3 ._time',
		noPrefix: true,
	},
	{
		groupName: 'Video Time Color',
		displayName: 'Video Time Color Design Four',
		name: 'videoTimeColorDesignFour',
		defaultValue: '<fontColorTwo>',
		description: 'Video time color for Design Four',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign4 ._time',
		noPrefix: true,
	},

	{
		groupName: 'Video Volume Icon Color',
		displayName: 'Video Volume Icon Color Design One',
		name: 'videoVolumeIconColorDesignOne',
		defaultValue: '<fontColorTwo>',
		description: 'Video time color for Design One',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign1 ._volumeButton',
		noPrefix: true,
	},
	{
		groupName: 'Video Volume Icon Color',
		displayName: 'Video Volume Icon Color Design Two',
		name: 'videoVolumeIconColorDesignTwo',
		defaultValue: '<fontColorTwo>',
		description: 'Video time color for Design Two',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign2 ._volumeButton',
		noPrefix: true,
	},
	{
		groupName: 'Video Volume Icon Color',
		displayName: 'Video Volume Icon Color Design Three',
		name: 'videoVolumeIconColorDesignThree',
		defaultValue: '<fontColorTwo>',
		description: 'Video time color for Design Three',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign3 ._volumeButton',
		noPrefix: true,
	},
	{
		groupName: 'Video Volume Icon Color',
		displayName: 'Video Volume Icon Color Design Four',
		name: 'videoVolumeIconColorDesignFour',
		defaultValue: '<fontColorTwo>',
		description: 'Video time color for Design Four',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign4 ._volumeButton',
		noPrefix: true,
	},

	{
		groupName: 'Video Full Screen Icon Color',
		displayName: 'Video Full Screen Icon Color Design One',
		name: 'videoFullScreenIconColorDesignOne',
		defaultValue: '<fontColorTwo>',
		description: 'Video full screen iconDesign One',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign1 ._fullScreen',
		noPrefix: true,
	},
	{
		groupName: 'Video Full Screen Icon Color',
		displayName: 'Video Full Screen Icon Color Design Two',
		name: 'videoFullScreenIconColorDesignTwo',
		defaultValue: '<fontColorTwo>',
		description: 'Video full screen iconDesign Two',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign2 ._fullScreen',
		noPrefix: true,
	},
	{
		groupName: 'Video Full Screen Icon Color',
		displayName: 'Video Full Screen Icon Color Design Three',
		name: 'videoFullScreenIconColorDesignThree',
		defaultValue: '<fontColorTwo>',
		description: 'Video full screen iconDesign Three',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign3 ._fullScreen',
		noPrefix: true,
	},
	{
		groupName: 'Video Full Screen Icon Color',
		displayName: 'Video Full Screen Icon Color Design Four',
		name: 'videoFullScreenIconColorDesignFour',
		defaultValue: '<fontColorTwo>',
		description: 'Video full screen iconDesign Four',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign4 ._fullScreen',
		noPrefix: true,
	},

	{
		groupName: 'Video PIP Icon',
		displayName: 'Video PIP Icon Design One',
		name: 'videoPIPIconDesignOne',
		defaultValue: '<fontColorTwo>',
		description: 'Video PIP iconDesign One',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign1 ._pip',
		noPrefix: true,
	},
	{
		groupName: 'Video PIP Icon',
		displayName: 'Video PIP Icon Design Two',
		name: 'videoPIPIconDesignTwo',
		defaultValue: '<fontColorTwo>',
		description: 'Video PIP iconDesign Two',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign2 ._pip',
		noPrefix: true,
	},
	{
		groupName: 'Video PIP Icon',
		displayName: 'Video PIP Icon Design Three',
		name: 'videoPIPIconDesignThree',
		defaultValue: '<fontColorTwo>',
		description: 'Video PIP iconDesign Three',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign3 ._pip',
		noPrefix: true,
	},
	{
		groupName: 'Video PIP Icon',
		displayName: 'Video PIP Icon Design Four',
		name: 'videoPIPIconDesignFour',
		defaultValue: '<fontColorTwo>',
		description: 'Video PIP iconDesign Four',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign4 ._pip',
		noPrefix: true,
	},

	{
		groupName: 'Video Play And Volume Grid',
		displayName: 'Video Play And Volume Grid Design One',
		name: 'videoPlayAndVolumeGridDesignOne',
		defaultValue: 'flex',
		description: 'Video Play and Volume GridDesign One',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign1 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid',
		displayName: 'Video Play And Volume Grid Design Two',
		name: 'videoPlayAndVolumeGridDesignTwo',
		defaultValue: 'flex',
		description: 'Video Play and Volume GridDesign Two',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign2 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid',
		displayName: 'Video Play And Volume Grid Design Three',
		name: 'videoPlayAndVolumeGridDesignThree',
		defaultValue: 'flex',
		description: 'Video Play and Volume GridDesign Three',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign3 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid',
		displayName: 'Video Play And Volume Grid Design Four',
		name: 'videoPlayAndVolumeGridDesignFour',
		description: 'Video Play and Volume GridDesign Four',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign4 ._playAndVolumeGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play And Volume Grid Gap',
		displayName: 'Video Play And Volume Grid Gap Design One',
		name: 'videoPlayAndVolumeGridGapDesignOne',
		defaultValue: '10px',
		description: 'Video Play and Volume Grid GapDesign One',
		cssProperty: 'gap',
		selector: '.comp.compVideo._videoDesign1 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Gap',
		displayName: 'Video Play And Volume Grid Gap Design Two',
		name: 'videoPlayAndVolumeGridGapDesignTwo',
		defaultValue: '10px',
		description: 'Video Play and Volume Grid GapDesign Two',
		cssProperty: 'gap',
		selector: '.comp.compVideo._videoDesign2 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Gap',
		displayName: 'Video Play And Volume Grid Gap Design Three',
		name: 'videoPlayAndVolumeGridGapDesignThree',
		defaultValue: '10px',
		description: 'Video Play and Volume Grid GapDesign Three',
		cssProperty: 'gap',
		selector: '.comp.compVideo._videoDesign3 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Gap',
		displayName: 'Video Play And Volume Grid Gap Design Four',
		name: 'videoPlayAndVolumeGridGapDesignFour',
		description: 'Video Play and Volume Grid GapDesign Four',
		cssProperty: 'gap',
		selector: '.comp.compVideo._videoDesign4 ._playAndVolumeGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play And Volume Grid Align Items',
		displayName: 'Video Play And Volume Grid Align Items Design One',
		name: 'Video Play And Volume Grid Flex direction one',
		defaultValue: 'center',
		description: 'videoPlayAndVolumeGridAlignItemsDesign One',
		cssProperty: 'align-items',
		selector: '.comp.compVideo._videoDesign1 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Align Items',
		displayName: 'Video Play And Volume Grid Align Items Design Two',
		name: 'Video Play And Volume Grid Flex direction two',
		defaultValue: 'center',
		description: 'videoPlayAndVolumeGridAlignItemsDesign Two',
		cssProperty: 'align-items',
		selector: '.comp.compVideo._videoDesign2 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Align Items',
		displayName: 'Video Play And Volume Grid Align Items Design Three',
		name: 'Video Play And Volume Grid Flex direction three',
		defaultValue: 'center',
		description: 'videoPlayAndVolumeGridAlignItemsDesign Three',
		cssProperty: 'align-items',
		selector: '.comp.compVideo._videoDesign3 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Align Items',
		displayName: 'Video Play And Volume Grid Align Items Design Four',
		name: 'Video Play And Volume Grid Flex direction four',
		description: 'videoPlayAndVolumeGridAlignItemsDesign Four',
		cssProperty: 'align-items',
		selector: '.comp.compVideo._videoDesign4 ._playAndVolumeGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play And Volume Grid Height',
		displayName: 'Video Play And Volume Grid Height Design One',
		name: 'videoPlayAndVolumeGridHeightDesignOne',
		defaultValue: '20px',
		description: 'videoPlayAndVolumeGridHeight',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign1 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Height',
		displayName: 'Video Play And Volume Grid Height Design Two',
		name: 'videoPlayAndVolumeGridHeightDesignTwo',
		defaultValue: '20px',
		description: 'videoPlayAndVolumeGridHeight',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign2 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Height',
		displayName: 'Video Play And Volume Grid Height Design Three',
		name: 'videoPlayAndVolumeGridHeightDesignThree',
		defaultValue: '20px',
		description: 'videoPlayAndVolumeGridHeight',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign3 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Height',
		displayName: 'Video Play And Volume Grid Height Design Four',
		name: 'videoPlayAndVolumeGridHeightDesignFour',
		description: 'videoPlayAndVolumeGridHeight',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign4 ._playAndVolumeGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play And Volume Grid Height',
		displayName: 'Video Play And Volume Grid Height ',
		name: 'videoPlayAndVolumeGridHeight',
		defaultValue: '20px',
		description: 'videoPlayAndVolumeGridHeight',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign1 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Height',
		displayName: 'Video Play And Volume Grid Height ',
		name: 'videoPlayAndVolumeGridHeight',
		defaultValue: '20px',
		description: 'videoPlayAndVolumeGridHeight',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign2 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Height',
		displayName: 'Video Play And Volume Grid Height ',
		name: 'videoPlayAndVolumeGridHeight',
		defaultValue: '20px',
		description: 'videoPlayAndVolumeGridHeight',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign3 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Height',
		displayName: 'Video Play And Volume Grid Height ',
		name: 'videoPlayAndVolumeGridHeight',
		defaultValue: '20px',
		description: 'videoPlayAndVolumeGridHeight',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign4 ._playAndVolumeGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play Back Icon Color',
		displayName: 'Video Play Back Icon Color Design One',
		name: 'videoPlayBackIconColorDesignOne',
		defaultValue: '<fontColorTwo>',
		description: 'video playbackiconDesign One',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign1 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon Color',
		displayName: 'Video Play Back Icon Color Design Two',
		name: 'videoPlayBackIconColorDesignTwo',
		defaultValue: '<fontColorTwo>',
		description: 'video playbackiconDesign Two',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign2 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon Color',
		displayName: 'Video Play Back Icon Color Design Three',
		name: 'videoPlayBackIconColorDesignThree',
		defaultValue: '<fontColorTwo>',
		description: 'video playbackiconDesign Three',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign3 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon Color',
		displayName: 'Video Play Back Icon Color Design Four',
		name: 'videoPlayBackIconColorDesignFour',
		defaultValue: '<fontColorTwo>',
		description: 'video playbackiconDesign Four',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign4 ._playIcon',
		noPrefix: true,
	},

	{
		groupName: 'Video PauseIcon Color',
		displayName: 'Video PauseIcon Color Design One',
		name: 'videoPauseIconColorDesignOne',
		defaultValue: '<fontColorTwo>',
		description: 'video pauseicon',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign1 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video PauseIcon Color',
		displayName: 'Video PauseIcon Color Design Two',
		name: 'videoPauseIconColorDesignTwo',
		defaultValue: '<fontColorTwo>',
		description: 'video pauseicon',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign2 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video PauseIcon Color',
		displayName: 'Video PauseIcon Color Design Three',
		name: 'videoPauseIconColorDesignThree',
		defaultValue: '<fontColorTwo>',
		description: 'video pauseicon',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign3 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video PauseIcon Color',
		displayName: 'Video PauseIcon Color Design Four',
		name: 'videoPauseIconColorDesignFour',
		defaultValue: '<fontColorTwo>',
		description: 'video pauseicon',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign4 ._pauseIcon',
		noPrefix: true,
	},

	{
		groupName: 'Video Play and Fullscreen grid',
		displayName: 'Video Play and Fullscreen grid Design One',
		name: 'videoPlayandFullscreengridDesignOne',
		defaultValue: 'flex',
		description: 'video Play and fullscreen gridDesign One',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign1 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid',
		displayName: 'Video Play and Fullscreen grid Design Two',
		name: 'videoPlayandFullscreengridDesignTwo',
		defaultValue: 'flex',
		description: 'video Play and fullscreen gridDesign Two',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign2 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid',
		displayName: 'Video Play and Fullscreen grid Design Three',
		name: 'videoPlayandFullscreengridDesignThree',
		defaultValue: 'flex',
		description: 'video Play and fullscreen gridDesign Three',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign3 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid',
		displayName: 'Video Play and Fullscreen grid Design Four',
		name: 'videoPlayandFullscreengridDesignFour',
		description: 'video Play and fullscreen gridDesign Four',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign4 ._playAndFullscreenGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play and Fullscreen grid Padding top',
		displayName: 'Video Play and Fullscreen grid Padding top Design One',
		name: 'videoPlayandFullscreengridPaddingtopDesignOne',
		defaultValue: '10px',
		description: 'video Play and  grid Padding topDesign One',
		cssProperty: 'padding-top',
		selector: '.comp.compVideo._videoDesign1 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding top',
		displayName: 'Video Play and Fullscreen grid Padding top Design Two',
		name: 'videoPlayandFullscreengridPaddingtopDesignTwo',
		defaultValue: '10px',
		description: 'video Play and  grid Padding topDesign Two',
		cssProperty: 'padding-top',
		selector: '.comp.compVideo._videoDesign2 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding top',
		displayName: 'Video Play and Fullscreen grid Padding top Design Three',
		name: 'videoPlayandFullscreengridPaddingtopDesignThree',
		defaultValue: '10px',
		description: 'video Play and  grid Padding topDesign Three',
		cssProperty: 'padding-top',
		selector: '.comp.compVideo._videoDesign3 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding top',
		displayName: 'Video Play and Fullscreen grid Padding top Design Four',
		name: 'videoPlayandFullscreengridPaddingtopDesignFour',
		description: 'video Play and  grid Padding topDesign Four',
		cssProperty: 'padding-top',
		selector: '.comp.compVideo._videoDesign4 ._playAndFullscreenGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play and Fullscreen grid Padding Left',
		displayName: 'Video Play and Fullscreen grid Padding Left Design One',
		name: 'videoPlayandFullscreengridPaddingLeftDesignOne',
		defaultValue: '10px',
		description: 'video Play and  grid Padding LeftDesign One',
		cssProperty: 'padding-Left',
		selector: '.comp.compVideo._videoDesign1 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding Left',
		displayName: 'Video Play and Fullscreen grid Padding Left Design Two',
		name: 'videoPlayandFullscreengridPaddingLeftDesignTwo',
		defaultValue: '10px',
		description: 'video Play and  grid Padding LeftDesign Two',
		cssProperty: 'padding-Left',
		selector: '.comp.compVideo._videoDesign2 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding Left',
		displayName: 'Video Play and Fullscreen grid Padding Left Design Three',
		name: 'videoPlayandFullscreengridPaddingLeftDesignThree',
		defaultValue: '10px',
		description: 'video Play and  grid Padding LeftDesign Three',
		cssProperty: 'padding-Left',
		selector: '.comp.compVideo._videoDesign3 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding Left',
		displayName: 'Video Play and Fullscreen grid Padding Left Design Four',
		name: 'videoPlayandFullscreengridPaddingLeftDesignFour',
		description: 'video Play and  grid Padding LeftDesign Four',
		cssProperty: 'padding-Left',
		selector: '.comp.compVideo._videoDesign4 ._playAndFullscreenGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play and Fullscreen grid content',
		displayName: 'Video Play and Fullscreen grid content Design One',
		name: 'videoPlayandFullscreengridcontentDesignOne',
		defaultValue: 'space-between',
		description: 'video Play and fullscreen grid contentDesign One',
		cssProperty: 'justify-content',
		selector: '.comp.compVideo._videoDesign1 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid content',
		displayName: 'Video Play and Fullscreen grid content Design Two',
		name: 'videoPlayandFullscreengridcontentDesignTwo',
		defaultValue: 'space-between',
		description: 'video Play and fullscreen grid contentDesign Two',
		cssProperty: 'justify-content',
		selector: '.comp.compVideo._videoDesign2 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid content',
		displayName: 'Video Play and Fullscreen grid content Design Three',
		name: 'videoPlayandFullscreengridcontentDesignThree',
		defaultValue: 'space-between',
		description: 'video Play and fullscreen grid contentDesign Three',
		cssProperty: 'justify-content',
		selector: '.comp.compVideo._videoDesign3 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid content',
		displayName: 'Video Play and Fullscreen grid content Design Four',
		name: 'videoPlayandFullscreengridcontentDesignFour',
		description: 'video Play and fullscreen grid contentDesign Four',
		cssProperty: 'justify-content',
		selector: '.comp.compVideo._videoDesign4 ._playAndFullscreenGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play and Fullscreen grid Padding right',
		displayName: 'Video Play and Fullscreen grid Padding right Design One',
		name: 'videoPlayandFullscreengridPaddingrightDesignOne',
		defaultValue: '10px',
		description: 'video Play and  grid Padding RightDesign One',
		cssProperty: 'padding-right',
		selector: '.comp.compVideo._videoDesign1 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding right',
		displayName: 'Video Play and Fullscreen grid Padding right Design Two',
		name: 'videoPlayandFullscreengridPaddingrightDesignTwo',
		defaultValue: '10px',
		description: 'video Play and  grid Padding RightDesign Two',
		cssProperty: 'padding-right',
		selector: '.comp.compVideo._videoDesign2 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding right',
		displayName: 'Video Play and Fullscreen grid Padding right Design Three',
		name: 'videoPlayandFullscreengridPaddingrightDesignThree',
		defaultValue: '10px',
		description: 'video Play and  grid Padding RightDesign Three',
		cssProperty: 'padding-right',
		selector: '.comp.compVideo._videoDesign3 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding right',
		displayName: 'Video Play and Fullscreen grid Padding right Design Four',
		name: 'videoPlayandFullscreengridPaddingrightDesignFour',
		description: 'video Play and  grid Padding RightDesign Four',
		cssProperty: 'padding-right',
		selector: '.comp.compVideo._videoDesign4 ._playAndFullscreenGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play and Fullscreen grid Padding bottom',
		displayName: 'Video Play and Fullscreen grid Padding bottom Design One',
		name: 'videoPlayandFullscreengridPaddingbottomDesignOne',
		defaultValue: '3px',
		description: 'video Play and  grid Padding bottomDesign One',
		cssProperty: 'padding-bottom',
		selector: '.comp.compVideo._videoDesign1 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding bottom',
		displayName: 'Video Play and Fullscreen grid Padding bottom Design Two',
		name: 'videoPlayandFullscreengridPaddingbottomDesignTwo',
		defaultValue: '3px',
		description: 'video Play and  grid Padding bottomDesign Two',
		cssProperty: 'padding-bottom',
		selector: '.comp.compVideo._videoDesign2 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding bottom',
		displayName: 'Video Play and Fullscreen grid Padding bottom Design Three',
		name: 'videoPlayandFullscreengridPaddingbottomDesignThree',
		defaultValue: '3px',
		description: 'video Play and  grid Padding bottomDesign Three',
		cssProperty: 'padding-bottom',
		selector: '.comp.compVideo._videoDesign3 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding bottom',
		displayName: 'Video Play and Fullscreen grid Padding bottom Design Four',
		name: 'videoPlayandFullscreengridPaddingbottomDesignFour',
		description: 'video Play and  grid Padding bottomDesign Four',
		cssProperty: 'padding-bottom',
		selector: '.comp.compVideo._videoDesign4 ._playAndFullscreenGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Pip and Fullscreen Grid Display',
		displayName: 'Video Pip and Fullscreen Grid Display Design One',
		name: 'videoPipandFullscreenGridDisplayDesignOne',
		defaultValue: 'flex',
		description: 'video pip and fullscreen GridDesign One',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign1 ._pipAndFullScreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Pip and Fullscreen Grid Display',
		displayName: 'Video Pip and Fullscreen Grid Display Design Two',
		name: 'videoPipandFullscreenGridDisplayDesignTwo',
		defaultValue: 'flex',
		description: 'video pip and fullscreen GridDesign Two',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign2 ._pipAndFullScreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Pip and Fullscreen Grid Display',
		displayName: 'Video Pip and Fullscreen Grid Display Design Three',
		name: 'videoPipandFullscreenGridDisplayDesignThree',
		defaultValue: 'flex',
		description: 'video pip and fullscreen GridDesign Three',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign3 ._pipAndFullScreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Pip and Fullscreen Grid Display',
		displayName: 'Video Pip and Fullscreen Grid Display Design Four',
		name: 'videoPipandFullscreenGridDisplayDesignFour',
		description: 'video pip and fullscreen GridDesign Four',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign4 ._pipAndFullScreenGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Pip and Fullscreen Grid Gap',
		displayName: 'Video Pip and Fullscreen Grid Gap Design One',
		name: 'videoPipandFullscreenGridGapDesignOne',
		defaultValue: '10px',
		description: 'video pip and fullscreen GridDesign One',
		cssProperty: 'gap',
		selector: '.comp.compVideo._videoDesign1 ._pipAndFullScreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Pip and Fullscreen Grid Gap',
		displayName: 'Video Pip and Fullscreen Grid Gap Design Two',
		name: 'videoPipandFullscreenGridGapDesignTwo',
		defaultValue: '10px',
		description: 'video pip and fullscreen GridDesign Two',
		cssProperty: 'gap',
		selector: '.comp.compVideo._videoDesign2 ._pipAndFullScreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Pip and Fullscreen Grid Gap',
		displayName: 'Video Pip and Fullscreen Grid Gap Design Three',
		name: 'videoPipandFullscreenGridGapDesignThree',
		defaultValue: '10px',
		description: 'video pip and fullscreen GridDesign Three',
		cssProperty: 'gap',
		selector: '.comp.compVideo._videoDesign3 ._pipAndFullScreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Pip and Fullscreen Grid Gap',
		displayName: 'Video Pip and Fullscreen Grid Gap Design Four',
		name: 'videoPipandFullscreenGridGapDesignFour',
		description: 'video pip and fullscreen GridDesign Four',
		cssProperty: 'gap',
		selector: '.comp.compVideo._videoDesign4 ._pipAndFullScreenGrid',
		noPrefix: true,
	},

	{
		groupName: 'Volume Button Width',
		displayName: 'Volume Button Width Design One',
		name: 'volumeButtonWidthDesignOne',
		defaultValue: '20px',
		description: 'volume button Width Design One',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign1 ._volumeButton',
		noPrefix: true,
	},
	{
		groupName: 'Volume Button Width',
		displayName: 'Volume Button Width Design Two',
		name: 'volumeButtonWidthDesignTwo',
		defaultValue: '20px',
		description: 'volume button Width Design Two',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign2 ._volumeButton',
		noPrefix: true,
	},
	{
		groupName: 'Volume Button Width',
		displayName: 'Volume Button Width Design Three',
		name: 'volumeButtonWidthDesignThree',
		defaultValue: '20px',
		description: 'volume button Width Design Three',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign3 ._volumeButton',
		noPrefix: true,
	},
	{
		groupName: 'Volume Button Width',
		displayName: 'Volume Button Width Design Four',
		name: 'volumeButtonWidthDesignFour',
		description: 'volume button Width Design Four',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign4 ._volumeButton',
		noPrefix: true,
	},

	{
		groupName: 'fullScreen icon Width',
		displayName: 'fullScreen icon Width Design One',
		name: 'fullScreeniconWidthDesignOne',
		defaultValue: '15px',
		description: 'fullScreen icon WidthDesign One',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign1 ._fullScreen ',
		noPrefix: true,
	},
	{
		groupName: 'fullScreen icon Width',
		displayName: 'fullScreen icon Width Design Two',
		name: 'fullScreeniconWidthDesignTwo',
		defaultValue: '18px',
		description: 'fullScreen icon WidthDesign Two',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign2 ._fullScreen ',
		noPrefix: true,
	},
	{
		groupName: 'fullScreen icon Width',
		displayName: 'fullScreen icon Width Design Three',
		name: 'fullScreeniconWidthDesignThree',
		defaultValue: '18px',
		description: 'fullScreen icon WidthDesign Three',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign3 ._fullScreen ',
		noPrefix: true,
	},
	{
		groupName: 'fullScreen icon Width',
		displayName: 'fullScreen icon Width Design Four',
		name: 'fullScreeniconWidthDesignFour',
		description: 'fullScreen icon WidthDesign Four',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign4 ._fullScreen ',
		noPrefix: true,
	},

	{
		groupName: 'Video PIP Icon Width',
		displayName: 'Video PIP Icon Width Design One',
		name: 'videoPIPIconWidthDesignOne',
		defaultValue: '15px',
		description: 'Video PIP iconDesign One',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign1 ._pip',
		noPrefix: true,
	},
	{
		groupName: 'Video PIP Icon Width',
		displayName: 'Video PIP Icon Width Design Two',
		name: 'videoPIPIconWidthDesignTwo',
		defaultValue: '18px',
		description: 'Video PIP iconDesign Two',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign2 ._pip',
		noPrefix: true,
	},
	{
		groupName: 'Video PIP Icon Width',
		displayName: 'Video PIP Icon Width Design Three',
		name: 'videoPIPIconWidthDesignThree',
		defaultValue: '18px',
		description: 'Video PIP iconDesign Three',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign3 ._pip',
		noPrefix: true,
	},
	{
		groupName: 'Video PIP Icon Width',
		displayName: 'Video PIP Icon Width Design Four',
		name: 'videoPIPIconWidthDesignFour',
		description: 'Video PIP iconDesign Four',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign4 ._pip',
		noPrefix: true,
	},

	{
		groupName: 'Video Play Back Icon Width',
		displayName: 'Video Play Back Icon Width Design One',
		name: 'videoPlayBackIconWidthDesignOne',
		defaultValue: '15px',
		description: 'video playbackiconDesign One',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign1 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon Width',
		displayName: 'Video Play Back Icon Width Design Two',
		name: 'videoPlayBackIconWidthDesignTwo',
		defaultValue: '20px',
		description: 'video playbackiconDesign Two',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign2 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon Width',
		displayName: 'Video Play Back Icon Width Design Three',
		name: 'videoPlayBackIconWidthDesignThree',
		defaultValue: '30px',
		description: 'video playbackiconDesign Three',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign3 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon Width',
		displayName: 'Video Play Back Icon Width Design Four',
		name: 'videoPlayBackIconWidthDesignFour',
		description: 'video playbackiconDesign Four',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign4 ._playIcon',
		noPrefix: true,
	},

	{
		groupName: 'Video Pause  Icon Width',
		displayName: 'Video Pause  Icon Width Design One',
		name: 'videoPauseIconWidthDesignOne',
		defaultValue: '15px',
		description: 'video Pause IconDesign One',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign1 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Pause  Icon Width',
		displayName: 'Video Pause  Icon Width Design Two',
		name: 'videoPauseIconWidthDesignTwo',
		defaultValue: '20px',
		description: 'video Pause IconDesign Two',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign2 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Pause  Icon Width',
		displayName: 'Video Pause  Icon Width Design Three',
		name: 'videoPauseIconWidthDesignThree',
		defaultValue: '30px',
		description: 'video Pause IconDesign Three',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign3 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Pause  Icon Width',
		displayName: 'Video Pause  Icon Width Design Four',
		name: 'videoPauseIconWidthDesignFour',
		description: 'video Pause IconDesign Four',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign4 ._pauseIcon',
		noPrefix: true,
	},

	{
		groupName: 'Video Play Back Icon position',
		displayName: 'Video Play Back Icon position Design One',
		name: 'videoPlayBackIconpositionDesignOne',
		description: 'video playbackicon',
		selector: '.comp.compVideo._videoDesign1 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon position',
		displayName: 'Video Play Back Icon position Design Two',
		name: 'videoPlayBackIconpositionDesignTwo',
		description: 'video playbackicon',
		selector: '.comp.compVideo._videoDesign2 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon position',
		displayName: 'Video Play Back Icon position Design Three',
		name: 'videoPlayBackIconpositionDesignThree',
		defaultValue: 'absolute',
		description: 'video playbackicon',
		cssProperty: 'position',
		selector: '.comp.compVideo._videoDesign3 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon position',
		displayName: 'Video Play Back Icon position Design Four',
		name: 'videoPlayBackIconpositionDesignFour',
		description: 'video playbackicon',
		selector: '.comp.compVideo._videoDesign4 ._playIcon',
		noPrefix: true,
	},

	{
		groupName: 'Video Play Back Icon top',
		displayName: 'Video Play Back Icon top Design One',
		name: 'videoPlayBackIcontopDesignOne',
		description: 'video playbackicon',
		selector: '.comp.compVideo._videoDesign1 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon top',
		displayName: 'Video Play Back Icon top Design Two',
		name: 'videoPlayBackIcontopDesignTwo',
		description: 'video playbackicon',
		selector: '.comp.compVideo._videoDesign2 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon top',
		displayName: 'Video Play Back Icon top Design Three',
		name: 'videoPlayBackIcontopDesignThree',
		defaultValue: '50%',
		description: 'video playbackicon',
		cssProperty: 'top',
		selector: '.comp.compVideo._videoDesign3 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon top',
		displayName: 'Video Play Back Icon top Design Four',
		name: 'videoPlayBackIcontopDesignFour',
		description: 'video playbackicon',
		selector: '.comp.compVideo._videoDesign4 ._playIcon',
		noPrefix: true,
	},

	{
		groupName: 'Video Play Back Icon left',
		displayName: 'Video Play Back Icon left Design One',
		name: 'videoPlayBackIconleftDesignOne',
		description: 'video playbackicon',
		selector: '.comp.compVideo._videoDesign1 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon left',
		displayName: 'Video Play Back Icon left Design Two',
		name: 'videoPlayBackIconleftDesignTwo',
		description: 'video playbackicon',
		selector: '.comp.compVideo._videoDesign2 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon left',
		displayName: 'Video Play Back Icon left Design Three',
		name: 'videoPlayBackIconleftDesignThree',
		defaultValue: '50%',
		description: 'video playbackicon',
		cssProperty: 'left',
		selector: '.comp.compVideo._videoDesign3 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon left',
		displayName: 'Video Play Back Icon left Design Four',
		name: 'videoPlayBackIconleftDesignFour',
		description: 'video playbackicon',
		selector: '.comp.compVideo._videoDesign4 ._playIcon',
		noPrefix: true,
	},

	{
		groupName: 'Video pause Icon top',
		displayName: 'Video pause Icon top Design One',
		name: 'videopauseIcontopDesignOne',
		description: 'video Pause IconDesign One',
		selector: '.comp.compVideo._videoDesign1 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video pause Icon top',
		displayName: 'Video pause Icon top Design Two',
		name: 'videopauseIcontopDesignTwo',
		description: 'video Pause IconDesign Two',
		selector: '.comp.compVideo._videoDesign2 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video pause Icon top',
		displayName: 'Video pause Icon top Design Three',
		name: 'videopauseIcontopDesignThree',
		defaultValue: 'absolute',
		description: 'video Pause IconDesign Three',
		cssProperty: 'position',
		selector: '.comp.compVideo._videoDesign3 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video pause Icon top',
		displayName: 'Video pause Icon top Design Four',
		name: 'videopauseIcontopDesignFour',
		description: 'video Pause IconDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._pauseIcon',
		noPrefix: true,
	},

	{
		groupName: 'Video Pause Icon left',
		displayName: 'Video Pause Icon left Design One',
		name: 'videoPauseIconleftDesignOne',
		description: 'video playbackiconDesign One',
		selector: '.comp.compVideo._videoDesign1 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Pause Icon left',
		displayName: 'Video Pause Icon left Design Two',
		name: 'videoPauseIconleftDesignTwo',
		description: 'video playbackiconDesign Two',
		selector: '.comp.compVideo._videoDesign2 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Pause Icon left',
		displayName: 'Video Pause Icon left Design Three',
		name: 'videoPauseIconleftDesignThree',
		defaultValue: '50%',
		description: 'video playbackiconDesign Three',
		cssProperty: 'top',
		selector: '.comp.compVideo._videoDesign3 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Pause Icon left',
		displayName: 'Video Pause Icon left Design Four',
		name: 'videoPauseIconleftDesignFour',
		description: 'video playbackiconDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._pauseIcon',
		noPrefix: true,
	},

	{
		groupName: 'Video Pause Icon position',
		displayName: 'Video Pause Icon position Design One',
		name: 'videoPauseIconpositionDesignOne',
		description: 'video pause icon positionDesign One',
		selector: '.comp.compVideo._videoDesign1 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Pause Icon position',
		displayName: 'Video Pause Icon position Design Two',
		name: 'videoPauseIconpositionDesignTwo',
		description: 'video pause icon positionDesign Two',
		selector: '.comp.compVideo._videoDesign2 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Pause Icon position',
		displayName: 'Video Pause Icon position Design Three',
		name: 'videoPauseIconpositionDesignThree',
		defaultValue: '50%',
		description: 'video pause icon positionDesign Three',
		cssProperty: 'left',
		selector: '.comp.compVideo._videoDesign3 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Pause Icon position',
		displayName: 'Video Pause Icon position Design Four',
		name: 'videoPauseIconpositionDesignFour',
		description: 'video pause icon positionDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._pauseIcon',
		noPrefix: true,
	},

	{
		groupName: 'video volume control position',
		displayName: 'video volume control position Design One',
		name: 'videovolumecontrolpositionDesignOne',
		description: 'volume control positionDesign One',
		selector: '.comp.compVideo._videoDesign1 ._volumeControls',
		noPrefix: true,
	},
	{
		groupName: 'video volume control position',
		displayName: 'video volume control position Design Two',
		name: 'videovolumecontrolpositionDesignTwo',
		description: 'volume control positionDesign Two',
		selector: '.comp.compVideo._videoDesign2 ._volumeControls',
		noPrefix: true,
	},
	{
		groupName: 'video volume control position',
		displayName: 'video volume control position Design Three',
		name: 'videovolumecontrolpositionDesignThree',
		description: 'volume control positionDesign Three',
		selector: '.comp.compVideo._videoDesign3 ._volumeControls',
		noPrefix: true,
	},
	{
		groupName: 'video volume control position',
		displayName: 'video volume control position Design Four',
		name: 'videovolumecontrolpositionDesignFour',
		description: 'volume control positionDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._volumeControls',
		noPrefix: true,
	},

	{
		groupName: 'video volume control top',
		displayName: 'video volume control top Design One',
		name: 'videovolumecontroltopDesignOne',
		description: 'volume control topDesign One',
		selector: '.comp.compVideo._videoDesign1 ._volumeControls',
		noPrefix: true,
	},
	{
		groupName: 'video volume control top',
		displayName: 'video volume control top Design Two',
		name: 'videovolumecontroltopDesignTwo',
		description: 'volume control topDesign Two',
		selector: '.comp.compVideo._videoDesign2 ._volumeControls',
		noPrefix: true,
	},
	{
		groupName: 'video volume control top',
		displayName: 'video volume control top Design Three',
		name: 'videovolumecontroltopDesignThree',
		defaultValue: '10%',
		description: 'volume control topDesign Three',
		cssProperty: 'top',
		selector: '.comp.compVideo._videoDesign3 ._volumeControls',
		noPrefix: true,
	},
	{
		groupName: 'video volume control top',
		displayName: 'video volume control top Design Four',
		name: 'videovolumecontroltopDesignFour',
		description: 'volume control topDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._volumeControls',
		noPrefix: true,
	},

	{
		groupName: 'video volume control left',
		displayName: 'video volume control left Design One',
		name: 'videovolumecontrolleftDesignOne',
		description: 'volume control leftDesign One',
		selector: '.comp.compVideo._videoDesign1 ._volumeControls',
		noPrefix: true,
	},
	{
		groupName: 'video volume control left',
		displayName: 'video volume control left Design Two',
		name: 'videovolumecontrolleftDesignTwo',
		description: 'volume control leftDesign Two',
		selector: '.comp.compVideo._videoDesign2 ._volumeControls',
		noPrefix: true,
	},
	{
		groupName: 'video volume control left',
		displayName: 'video volume control left Design Three',
		name: 'videovolumecontrolleftDesignThree',
		defaultValue: '2%',
		description: 'volume control leftDesign Three',
		cssProperty: 'left',
		selector: '.comp.compVideo._videoDesign3 ._volumeControls',
		noPrefix: true,
	},
	{
		groupName: 'video volume control left',
		displayName: 'video volume control left Design Four',
		name: 'videovolumecontrolleftDesignFour',
		description: 'volume control leftDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._volumeControls',
		noPrefix: true,
	},

	{
		groupName: 'video volume control rotate',
		displayName: 'video volume control rotate Design One',
		name: 'videovolumecontrolrotateDesignOne',
		description: 'video volume control rotateDesign One',
		selector: '.comp.compVideo._videoDesign1 ._volumeControls',
		noPrefix: true,
	},
	{
		groupName: 'video volume control rotate',
		displayName: 'video volume control rotate Design Two',
		name: 'videovolumecontrolrotateDesignTwo',
		description: 'video volume control rotateDesign Two',
		selector: '.comp.compVideo._videoDesign2 ._volumeControls',
		noPrefix: true,
	},
	{
		groupName: 'video volume control rotate',
		displayName: 'video volume control rotate Design Three',
		name: 'videovolumecontrolrotateDesignThree',
		defaultValue: 'absolute',
		description: 'video volume control rotateDesign Three',
		cssProperty: 'position',
		selector: '.comp.compVideo._videoDesign3 ._volumeControls',
		noPrefix: true,
	},
	{
		groupName: 'video volume control rotate',
		displayName: 'video volume control rotate Design Four',
		name: 'videovolumecontrolrotateDesignFour',
		description: 'video volume control rotateDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._volumeControls',
		noPrefix: true,
	},

	{
		groupName: 'video controls container position',
		displayName: 'video controls container position',
		name: 'videocontrolscontainerposition',
		defaultValue: '0%',
		description: 'video volume control rotateDesign Three',
		cssProperty: 'bottom',
		selector: '.comp.compVideo ._videoControlsContainer',
		noPrefix: true,
	},

	{
		groupName: 'video volume control position',
		displayName: 'video volume control position Design One',
		name: 'videovolumecontrolpositionDesignOne',
		description: 'volume control position',
		selector: '.comp.compVideo._videoDesign1 ._volumeControls',
		noPrefix: true,
	},
	{
		groupName: 'video volume control position',
		displayName: 'video volume control position Design Two',
		name: 'videovolumecontrolpositionDesignTwo',
		description: 'volume control position',
		selector: '.comp.compVideo._videoDesign2 ._volumeControls',
		noPrefix: true,
	},
	{
		groupName: 'video volume control position',
		displayName: 'video volume control position Design Three',
		name: 'videovolumecontrolpositionDesignThree',
		defaultValue: '1',
		description: 'volume control position',
		cssProperty: 'z-index',
		selector: '.comp.compVideo._videoDesign3 ._volumeControls',
		noPrefix: true,
	},
	{
		groupName: 'video volume control position',
		displayName: 'video volume control position Design Four',
		name: 'videovolumecontrolpositionDesignFour',
		description: 'volume control position',
		selector: '.comp.compVideo._videoDesign4 ._volumeControls',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
