import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'Video Range Slider Accent Color',
		displayName: 'Primary Video Range Slider Accent Color',
		name: 'primaryVideoRangeSliderAccentColor',
		defaultValue: '<backgroundColorOne>',
		description: 'rangeSlider design one primary  color',
		cssProperty: 'accent-color',
		selector:
			'.comp.compVideo._videoDesign1._primary input[type="range"], .comp.compVideo._videoDesign2._primary input[type="range"], .comp.compVideo._videoDesign3._primary input[type="range"], .comp.compVideo._videoDesign4._primary input[type="range"]',
		noPrefix: true,
	},
	{
		groupName: 'Video Range Slider Accent Color',
		displayName: 'Secondary Video Range Slider Accent Color',
		name: 'secondaryVideoRangeSliderAccentColor',
		defaultValue: '<backgroundColorTwo>',
		description: 'rangeSlider design one secondary  color',
		cssProperty: 'accent-color',
		selector:
			'.comp.compVideo._videoDesign1._secondary input[type="range"], .comp.compVideo._videoDesign2._secondary input[type="range"], .comp.compVideo._videoDesign3._secondary input[type="range"], .comp.compVideo._videoDesign4._secondary input[type="range"]',
		noPrefix: true,
	},
	{
		groupName: 'Video Range Slider Accent Color',
		displayName: 'Tertiary Video Range Slider Accent Color',
		name: 'tertiaryVideoRangeSliderAccentColor',
		defaultValue: '<backgroundColorThree>',
		description: 'rangeSlider design one tertiary  color',
		cssProperty: 'accent-color',
		selector:
			'.comp.compVideo._videoDesign1._tertiary input[type="range"], .comp.compVideo._videoDesign2._tertiary input[type="range"], .comp.compVideo._videoDesign3._tertiary input[type="range"], .comp.compVideo._videoDesign4._tertiary input[type="range"]',
		noPrefix: true,
	},
	{
		groupName: 'Video Range Slider Accent Color',
		displayName: 'Quaternary Video Range Slider Accent Color',
		name: 'quaternaryVideoRangeSliderAccentColor',
		defaultValue: '<backgroundColorFour>',
		description: 'rangeSlider design one quaternary  color ',
		cssProperty: 'accent-color',
		selector:
			'.comp.compVideo._videoDesign1._quaternary input[type="range"], .comp.compVideo._videoDesign2._quaternary input[type="range"], .comp.compVideo._videoDesign3._quaternary input[type="range"], .comp.compVideo._videoDesign4._quaternary input[type="range"]',
		noPrefix: true,
	},
	{
		groupName: 'Video Range Slider Accent Color',
		displayName: 'Quinary Video Range Slider Accent Color',
		name: 'quinaryVideoRangeSliderAccentColor',
		defaultValue: '<backgroundColorFive>',
		description: 'rangeSlider design one quinary  color',
		cssProperty: 'accent-color',
		selector:
			'.comp.compVideo._videoDesign1._quinary input[type="range"], .comp.compVideo._videoDesign2._quinary input[type="range"], .comp.compVideo._videoDesign3._quinary input[type="range"], .comp.compVideo._videoDesign4._quinary input[type="range"]',
		noPrefix: true,
	},

	{
		groupName: 'Video Range Slider Height',
		displayName: 'Video Range Slider Height Design One',
		name: 'videoRangeSliderHeightDesignOne',
		defaultValue: '3px',
		description: 'rangeSlider Height for Design One',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign1 input[type="range"]',
		noPrefix: true,
	},
	{
		groupName: 'Video Range Slider Height',
		displayName: 'Video Range Slider Height Design Two',
		name: 'videoRangeSliderHeightDesignTwo',
		description: 'rangeSlider Height for Design Two',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign2 input[type="range"]',
		noPrefix: true,
	},
	{
		groupName: 'Video Range Slider Height',
		displayName: 'Video Range Slider Height Design Three',
		name: 'videoRangeSliderHeightDesignThree',
		description: 'rangeSlider Height for Design Three',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign3 input[type="range"]',
		noPrefix: true,
	},
	{
		groupName: 'Video Range Slider Height',
		displayName: 'Video Range Slider Height Design Four',
		name: 'videoRangeSliderHeightDesignFour',
		description: 'rangeSlider Height for Design Four',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign4 input[type="range"]',
		noPrefix: true,
	},

	{
		groupName: 'VideoProgressBarWidthDesignOne',
		displayName: 'ProgressBar Width DesignOne',
		name: 'progressBarWidthDesignOne',
		defaultValue: '0.99',
		description: 'Progress bar width for design one',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign1 ._progressBar',
		noPrefix: true,
	},

	{
		groupName: 'Video progress Bar container Padding',
		displayName: 'Video progress Bar container PaddingDesign One',
		name: 'videoprogressBarcontainerPaddingDesignOne',
		defaultValue: '0px 8px 0px 4px',
		description: 'Progress bar container padding',
		cssProperty: 'padding',
		selector: '.comp.compVideo ._progressBarContainer',
		noPrefix: true,
	},

	{
		groupName: 'VideoProgressBarCursorAll',
		displayName: 'ProgressBar Cursor All',
		name: 'ProgressBarCursorAll',
		defaultValue: 'pointer',
		description: 'progress bar cursor for all',
		cssProperty: 'cursor',
		selector: '.comp.compVideo ._progressBar',
		noPrefix: true,
	},

	{
		groupName: 'Video Progress Bar ToolTip Color',
		displayName: 'Video Progress Bar ToolTip Color All Designs',
		name: 'videoProgressBarToolTipColorAllDesigns',
		defaultValue: '<fontColorTwo>',
		description: 'progress bar tooltip color All designs.',
		cssProperty: 'color',
		selector: '.comp.compVideo ._toolTip',
		noPrefix: true,
	},

	{
		groupName: 'Video Time Color',
		displayName: 'Video Time Color Design One',
		name: 'videoTimeColorDesignOne',
		defaultValue: '<fontColorTwo>',
		description: 'Video time color for Design One',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign1 ._time',
		noPrefix: true,
	},
	{
		groupName: 'Video Time Color',
		displayName: 'Video Time Color Design Two',
		name: 'videoTimeColorDesignTwo',
		defaultValue: '<fontColorTwo>',
		description: 'Video time color for Design Two',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign2 ._time',
		noPrefix: true,
	},
	{
		groupName: 'Video Time Color',
		displayName: 'Video Time Color Design Three',
		name: 'videoTimeColorDesignThree',
		description: 'Video time color for Design Three',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign3 ._time',
		noPrefix: true,
	},
	{
		groupName: 'Video Time Color',
		displayName: 'Video Time Color Design Four',
		name: 'videoTimeColorDesignFour',
		description: 'Video time color for Design Four',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign4 ._time',
		noPrefix: true,
	},

	{
		groupName: 'Video Volume Icon Color',
		displayName: 'Video Volume Icon Color Design One',
		name: 'videoVolumeIconColorDesignOne',
		defaultValue: '<fontColorTwo>',
		description: 'Video time color for Design One',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign1 ._volumeButton',
		noPrefix: true,
	},
	{
		groupName: 'Video Volume Icon Color',
		displayName: 'Video Volume Icon Color Design Two',
		name: 'videoVolumeIconColorDesignTwo',
		defaultValue: '<fontColorTwo>',
		description: 'Video time color for Design Two',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign2 ._volumeButton',
		noPrefix: true,
	},
	{
		groupName: 'Video Volume Icon Color',
		displayName: 'Video Volume Icon Color Design Three',
		name: 'videoVolumeIconColorDesignThree',
		description: 'Video time color for Design Three',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign3 ._volumeButton',
		noPrefix: true,
	},
	{
		groupName: 'Video Volume Icon Color',
		displayName: 'Video Volume Icon Color Design Four',
		name: 'videoVolumeIconColorDesignFour',
		description: 'Video time color for Design Four',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign4 ._volumeButton',
		noPrefix: true,
	},

	{
		groupName: 'Video Full Screen Icon Color',
		displayName: 'Video Full Screen Icon Color Design One',
		name: 'videoFullScreenIconColorDesignOne',
		defaultValue: '<fontColorTwo>',
		description: 'Video full screen iconDesign One',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign1 ._fullScreen',
		noPrefix: true,
	},
	{
		groupName: 'Video Full Screen Icon Color',
		displayName: 'Video Full Screen Icon Color Design Two',
		name: 'videoFullScreenIconColorDesignTwo',
		defaultValue: '<fontColorTwo>',
		description: 'Video full screen iconDesign Two',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign2 ._fullScreen',
		noPrefix: true,
	},
	{
		groupName: 'Video Full Screen Icon Color',
		displayName: 'Video Full Screen Icon Color Design Three',
		name: 'videoFullScreenIconColorDesignThree',
		description: 'Video full screen iconDesign Three',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign3 ._fullScreen',
		noPrefix: true,
	},
	{
		groupName: 'Video Full Screen Icon Color',
		displayName: 'Video Full Screen Icon Color Design Four',
		name: 'videoFullScreenIconColorDesignFour',
		description: 'Video full screen iconDesign Four',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign4 ._fullScreen',
		noPrefix: true,
	},

	{
		groupName: 'Video PIP Icon',
		displayName: 'Video PIP Icon Design One',
		name: 'videoPIPIconDesignOne',
		defaultValue: '<fontColorTwo>',
		description: 'Video PIP iconDesign One',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign1 ._pip',
		noPrefix: true,
	},
	{
		groupName: 'Video PIP Icon',
		displayName: 'Video PIP Icon Design Two',
		name: 'videoPIPIconDesignTwo',
		defaultValue: '<fontColorTwo>',
		description: 'Video PIP iconDesign Two',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign2 ._pip',
		noPrefix: true,
	},
	{
		groupName: 'Video PIP Icon',
		displayName: 'Video PIP Icon Design Three',
		name: 'videoPIPIconDesignThree',
		description: 'Video PIP iconDesign Three',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign3 ._pip',
		noPrefix: true,
	},
	{
		groupName: 'Video PIP Icon',
		displayName: 'Video PIP Icon Design Four',
		name: 'videoPIPIconDesignFour',
		description: 'Video PIP iconDesign Four',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign4 ._pip',
		noPrefix: true,
	},

	{
		groupName: 'Video Play And Volume Grid',
		displayName: 'Video Play And Volume GridDesign One',
		name: 'videoPlayAndVolumeGridDesignOne',
		defaultValue: 'flex',
		description: 'Video Play and Volume GridDesign One',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign1 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid',
		displayName: 'Video Play And Volume GridDesign Two',
		name: 'videoPlayAndVolumeGridDesignTwo',
		defaultValue: 'flex',
		description: 'Video Play and Volume GridDesign Two',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign2 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid',
		displayName: 'Video Play And Volume GridDesign Three',
		name: 'videoPlayAndVolumeGridDesignThree',
		description: 'Video Play and Volume GridDesign Three',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign3 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid',
		displayName: 'Video Play And Volume GridDesign Four',
		name: 'videoPlayAndVolumeGridDesignFour',
		description: 'Video Play and Volume GridDesign Four',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign4 ._playAndVolumeGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play And Volume Grid Gap',
		displayName: 'Video Play And Volume Grid Gap',
		name: 'videoPlayAndVolumeGridGap',
		defaultValue: '10px',
		description: 'Video Play and Volume Grid GapDesign One',
		cssProperty: 'gap',
		selector: '.comp.compVideo._videoDesign1 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Gap',
		displayName: 'Video Play And Volume Grid Gap',
		name: 'videoPlayAndVolumeGridGap',
		defaultValue: '10px',
		description: 'Video Play and Volume Grid GapDesign Two',
		cssProperty: 'gap',
		selector: '.comp.compVideo._videoDesign2 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Gap',
		displayName: 'Video Play And Volume Grid Gap',
		name: 'videoPlayAndVolumeGridGap',
		description: 'Video Play and Volume Grid GapDesign Three',
		cssProperty: 'gap',
		selector: '.comp.compVideo._videoDesign3 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Gap',
		displayName: 'Video Play And Volume Grid Gap',
		name: 'videoPlayAndVolumeGridGap',
		description: 'Video Play and Volume Grid GapDesign Four',
		cssProperty: 'gap',
		selector: '.comp.compVideo._videoDesign4 ._playAndVolumeGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play And Volume Grid Align Items',
		displayName: 'Video Play And Volume Grid Align Items Design One',
		name: 'videoPlayAndVolumeGridAlignItemsDesignOne',
		defaultValue: 'center',
		description: 'videoPlayAndVolumeGridAlignItemsDesign One',
		cssProperty: 'align-items',
		selector: '.comp.compVideo._videoDesign1 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Align Items',
		displayName: 'Video Play And Volume Grid Align Items Design Two',
		name: 'videoPlayAndVolumeGridAlignItemsDesignTwo',
		defaultValue: 'center',
		description: 'videoPlayAndVolumeGridAlignItemsDesign Two',
		cssProperty: 'align-items',
		selector: '.comp.compVideo._videoDesign2 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Align Items',
		displayName: 'Video Play And Volume Grid Align Items Design Three',
		name: 'videoPlayAndVolumeGridAlignItemsDesignThree',
		description: 'videoPlayAndVolumeGridAlignItemsDesign Three',
		selector: '.comp.compVideo._videoDesign3 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Align Items',
		displayName: 'Video Play And Volume Grid Align Items Design Four',
		name: 'videoPlayAndVolumeGridAlignItemsDesignFour',
		description: 'videoPlayAndVolumeGridAlignItemsDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._playAndVolumeGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play And Volume Grid Height',
		displayName: 'Video Play And Volume Grid Height ',
		name: 'videoPlayAndVolumeGridHeight',
		defaultValue: '20px',
		description: 'videoPlayAndVolumeGridHeight',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign1 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Height',
		displayName: 'Video Play And Volume Grid Height ',
		name: 'videoPlayAndVolumeGridHeight',
		defaultValue: '20px',
		description: 'videoPlayAndVolumeGridHeight',
		cssProperty: 'height',
		selector: '.comp.compVideo._videoDesign2 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Height',
		displayName: 'Video Play And Volume Grid Height ',
		name: 'videoPlayAndVolumeGridHeight',
		description: 'videoPlayAndVolumeGridHeight',
		selector: '.comp.compVideo._videoDesign3 ._playAndVolumeGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play And Volume Grid Height',
		displayName: 'Video Play And Volume Grid Height ',
		name: 'videoPlayAndVolumeGridHeight',
		description: 'videoPlayAndVolumeGridHeight',
		selector: '.comp.compVideo._videoDesign4 ._playAndVolumeGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play Back Icon Color',
		displayName: 'Video Play Back Icon ColorDesign One',
		name: 'videoPlayBackIconColorDesignOne',
		defaultValue: '<fontColorTwo>',
		description: 'video playbackiconDesign One',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign1 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon Color',
		displayName: 'Video Play Back Icon ColorDesign Two',
		name: 'videoPlayBackIconColorDesignTwo',
		defaultValue: '<fontColorTwo>',
		description: 'video playbackiconDesign Two',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign2 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon Color',
		displayName: 'Video Play Back Icon ColorDesign Three',
		name: 'videoPlayBackIconColorDesignThree',
		description: 'video playbackiconDesign Three',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign3 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon Color',
		displayName: 'Video Play Back Icon ColorDesign Four',
		name: 'videoPlayBackIconColorDesignFour',
		description: 'video playbackiconDesign Four',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign4 ._playIcon',
		noPrefix: true,
	},

	{
		groupName: 'Video PauseIcon Color',
		displayName: 'Video PauseIcon Color',
		name: 'videoPauseIconColor',
		defaultValue: '<fontColorTwo>',
		description: 'video pauseicon',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign1 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video PauseIcon Color',
		displayName: 'Video PauseIcon Color',
		name: 'videoPauseIconColor',
		defaultValue: '<fontColorTwo>',
		description: 'video pauseicon',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign2 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video PauseIcon Color',
		displayName: 'Video PauseIcon Color',
		name: 'videoPauseIconColor',
		description: 'video pauseicon',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign3 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video PauseIcon Color',
		displayName: 'Video PauseIcon Color',
		name: 'videoPauseIconColor',
		description: 'video pauseicon',
		cssProperty: 'color',
		selector: '.comp.compVideo._videoDesign4 ._pauseIcon',
		noPrefix: true,
	},

	{
		groupName: 'Video Play Back Icon Font size',
		displayName: 'Video Play Back Icon Font sizeDesign One',
		name: 'videoPlayBackIconFontsizeDesignOne',
		defaultValue: '20px',
		description: 'video playbackiconDesign One',
		cssProperty: 'font-size',
		selector: '.comp.compVideo._videoDesign1 ._playBackIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon Font size',
		displayName: 'Video Play Back Icon Font sizeDesign Two',
		name: 'videoPlayBackIconFontsizeDesignTwo',
		defaultValue: '20px',
		description: 'video playbackiconDesign Two',
		cssProperty: 'font-size',
		selector: '.comp.compVideo._videoDesign2 ._playBackIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon Font size',
		displayName: 'Video Play Back Icon Font sizeDesign Three',
		name: 'videoPlayBackIconFontsizeDesignThree',
		description: 'video playbackiconDesign Three',
		selector: '.comp.compVideo._videoDesign3 ._playBackIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon Font size',
		displayName: 'Video Play Back Icon Font sizeDesign Four',
		name: 'videoPlayBackIconFontsizeDesignFour',
		description: 'video playbackiconDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._playBackIcon',
		noPrefix: true,
	},

	{
		groupName: 'Video Play and Fullscreen grid',
		displayName: 'Video Play and Fullscreen gridDesign One',
		name: 'videoPlayandFullscreengridDesignOne',
		defaultValue: 'flex',
		description: 'video Play and fullscreen gridDesign One',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign1 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid',
		displayName: 'Video Play and Fullscreen gridDesign Two',
		name: 'videoPlayandFullscreengridDesignTwo',
		defaultValue: 'flex',
		description: 'video Play and fullscreen gridDesign Two',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign2 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid',
		displayName: 'Video Play and Fullscreen gridDesign Three',
		name: 'videoPlayandFullscreengridDesignThree',
		description: 'video Play and fullscreen gridDesign Three',
		selector: '.comp.compVideo._videoDesign3 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid',
		displayName: 'Video Play and Fullscreen gridDesign Four',
		name: 'videoPlayandFullscreengridDesignFour',
		description: 'video Play and fullscreen gridDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._playAndFullscreenGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play and Fullscreen grid Padding top',
		displayName: 'Video Play and Fullscreen grid Padding topDesign One',
		name: 'videoPlayandFullscreengridPaddingtopDesignOne',
		defaultValue: '10px',
		description: 'video Play and  grid Padding topDesign One',
		cssProperty: 'padding-top',
		selector: '.comp.compVideo._videoDesign1 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding top',
		displayName: 'Video Play and Fullscreen grid Padding topDesign Two',
		name: 'videoPlayandFullscreengridPaddingtopDesignTwo',
		defaultValue: '10px',
		description: 'video Play and  grid Padding topDesign Two',
		cssProperty: 'padding-top',
		selector: '.comp.compVideo._videoDesign2 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding top',
		displayName: 'Video Play and Fullscreen grid Padding topDesign Three',
		name: 'videoPlayandFullscreengridPaddingtopDesignThree',
		defaultValue: '10px',
		description: 'video Play and  grid Padding topDesign Three',
		cssProperty: 'padding-top',
		selector: '.comp.compVideo._videoDesign3 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding top',
		displayName: 'Video Play and Fullscreen grid Padding topDesign Four',
		name: 'videoPlayandFullscreengridPaddingtopDesignFour',
		description: 'video Play and  grid Padding topDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._playAndFullscreenGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play and Fullscreen grid Padding Left',
		displayName: 'Video Play and Fullscreen grid Padding LeftDesign One',
		name: 'videoPlayandFullscreengridPaddingLeftDesignOne',
		defaultValue: '10px',
		description: 'video Play and  grid Padding LeftDesign One',
		cssProperty: 'padding-Left',
		selector: '.comp.compVideo._videoDesign1 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding Left',
		displayName: 'Video Play and Fullscreen grid Padding LeftDesign Two',
		name: 'videoPlayandFullscreengridPaddingLeftDesignTwo',
		defaultValue: '10px',
		description: 'video Play and  grid Padding LeftDesign Two',
		cssProperty: 'padding-Left',
		selector: '.comp.compVideo._videoDesign2 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding Left',
		displayName: 'Video Play and Fullscreen grid Padding LeftDesign Three',
		name: 'videoPlayandFullscreengridPaddingLeftDesignThree',
		description: 'video Play and  grid Padding LeftDesign Three',
		cssProperty: 'padding-Left',
		selector: '.comp.compVideo._videoDesign3 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding Left',
		displayName: 'Video Play and Fullscreen grid Padding LeftDesign Four',
		name: 'videoPlayandFullscreengridPaddingLeftDesignFour',
		description: 'video Play and  grid Padding LeftDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._playAndFullscreenGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play and Fullscreen grid content',
		displayName: 'Video Play and Fullscreen grid contentDesign One',
		name: 'videoPlayandFullscreengridcontentDesignOne',
		defaultValue: 'space-between',
		description: 'video Play and fullscreen grid contentDesign One',
		cssProperty: 'justify-content',
		selector: '.comp.compVideo._videoDesign1 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid content',
		displayName: 'Video Play and Fullscreen grid contentDesign Two',
		name: 'videoPlayandFullscreengridcontentDesignTwo',
		defaultValue: 'space-between',
		description: 'video Play and fullscreen grid contentDesign Two',
		cssProperty: 'justify-content',
		selector: '.comp.compVideo._videoDesign2 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid content',
		displayName: 'Video Play and Fullscreen grid contentDesign Three',
		name: 'videoPlayandFullscreengridcontentDesignThree',
		description: 'video Play and fullscreen grid contentDesign Three',
		selector: '.comp.compVideo._videoDesign3 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid content',
		displayName: 'Video Play and Fullscreen grid contentDesign Four',
		name: 'videoPlayandFullscreengridcontentDesignFour',
		description: 'video Play and fullscreen grid contentDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._playAndFullscreenGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play and Fullscreen grid Padding right',
		displayName: 'Video Play and Fullscreen grid Padding rightDesign One',
		name: 'videoPlayandFullscreengridPaddingrightDesignOne',
		defaultValue: '10px',
		description: 'video Play and  grid Padding RightDesign One',
		cssProperty: 'padding-right',
		selector: '.comp.compVideo._videoDesign1 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding right',
		displayName: 'Video Play and Fullscreen grid Padding rightDesign Two',
		name: 'videoPlayandFullscreengridPaddingrightDesignTwo',
		defaultValue: '10px',
		description: 'video Play and  grid Padding RightDesign Two',
		cssProperty: 'padding-right',
		selector: '.comp.compVideo._videoDesign2 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding right',
		displayName: 'Video Play and Fullscreen grid Padding rightDesign Three',
		name: 'videoPlayandFullscreengridPaddingrightDesignThree',
		description: 'video Play and  grid Padding RightDesign Three',
		selector: '.comp.compVideo._videoDesign3 ._playAndFullscreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Play and Fullscreen grid Padding right',
		displayName: 'Video Play and Fullscreen grid Padding rightDesign Four',
		name: 'videoPlayandFullscreengridPaddingrightDesignFour',
		description: 'video Play and  grid Padding RightDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._playAndFullscreenGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Pip and Fullscreen Grid Display',
		displayName: 'Video Pip and Fullscreen Grid Display Design One',
		name: 'videoPipandFullscreenGridDisplayDesignOne',
		defaultValue: 'flex',
		description: 'video pip and fullscreen GridDesign One',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign1 ._pipAndFullScreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Pip and Fullscreen Grid Display',
		displayName: 'Video Pip and Fullscreen Grid Display Design Two',
		name: 'videoPipandFullscreenGridDisplayDesignTwo',
		defaultValue: 'flex',
		description: 'video pip and fullscreen GridDesign Two',
		cssProperty: 'display',
		selector: '.comp.compVideo._videoDesign2 ._pipAndFullScreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Pip and Fullscreen Grid Display',
		displayName: 'Video Pip and Fullscreen Grid Display Design Three',
		name: 'videoPipandFullscreenGridDisplayDesignThree',
		description: 'video pip and fullscreen GridDesign Three',
		selector: '.comp.compVideo._videoDesign3 ._pipAndFullScreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Pip and Fullscreen Grid Display',
		displayName: 'Video Pip and Fullscreen Grid Display Design Four',
		name: 'videoPipandFullscreenGridDisplayDesignFour',
		description: 'video pip and fullscreen GridDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._pipAndFullScreenGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Pip and Fullscreen Grid Gap',
		displayName: 'Video Pip and Fullscreen Grid Gap ',
		name: 'videoPipandFullscreenGridGap',
		defaultValue: '10px',
		description: 'video pip and fullscreen GridDesign One',
		cssProperty: 'gap',
		selector: '.comp.compVideo._videoDesign1 ._pipAndFullScreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Pip and Fullscreen Grid Gap',
		displayName: 'Video Pip and Fullscreen Grid Gap ',
		name: 'videoPipandFullscreenGridGap',
		defaultValue: '10px',
		description: 'video pip and fullscreen GridDesign Two',
		cssProperty: 'gap',
		selector: '.comp.compVideo._videoDesign2 ._pipAndFullScreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Pip and Fullscreen Grid Gap',
		displayName: 'Video Pip and Fullscreen Grid Gap ',
		name: 'videoPipandFullscreenGridGap',
		description: 'video pip and fullscreen GridDesign Three',
		selector: '.comp.compVideo._videoDesign3 ._pipAndFullScreenGrid',
		noPrefix: true,
	},
	{
		groupName: 'Video Pip and Fullscreen Grid Gap',
		displayName: 'Video Pip and Fullscreen Grid Gap ',
		name: 'videoPipandFullscreenGridGap',
		description: 'video pip and fullscreen GridDesign Four',
		selector: '.comp.compVideo._videoDesign4 ._pipAndFullScreenGrid',
		noPrefix: true,
	},

	{
		groupName: 'Video Play Back Button Width',
		displayName: 'Video Play Back Button WidthDesign One',
		name: 'videoPlayBackButtonWidthDesignOne',
		defaultValue: '20px',
		description: 'video playback button Width Design One',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign1 ._playBackIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Button Width',
		displayName: 'Video Play Back Button WidthDesign Two',
		name: 'videoPlayBackButtonWidthDesignTwo',
		defaultValue: '20px',
		description: 'video playback button Width Design Two',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign2 ._playBackIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Button Width',
		displayName: 'Video Play Back Button WidthDesign Three',
		name: 'videoPlayBackButtonWidthDesignThree',
		description: 'video playback button Width Design Three',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign3 ._playBackIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Button Width',
		displayName: 'Video Play Back Button WidthDesign Four',
		name: 'videoPlayBackButtonWidthDesignFour',
		description: 'video playback button Width Design Four',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign4 ._playBackIcon',
		noPrefix: true,
	},

	{
		groupName: 'Volume Button Width',
		displayName: 'Volume Button Width Design One',
		name: 'volumeButtonWidthDesignOne',
		defaultValue: '20px',
		description: 'volume button Width Design One',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign1 ._volumeButton',
		noPrefix: true,
	},
	{
		groupName: 'Volume Button Width',
		displayName: 'Volume Button Width Design Two',
		name: 'volumeButtonWidthDesignTwo',
		defaultValue: '20px',
		description: 'volume button Width Design Two',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign2 ._volumeButton',
		noPrefix: true,
	},
	{
		groupName: 'Volume Button Width',
		displayName: 'Volume Button Width Design Three',
		name: 'volumeButtonWidthDesignThree',
		description: 'volume button Width Design Three',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign3 ._volumeButton',
		noPrefix: true,
	},
	{
		groupName: 'Volume Button Width',
		displayName: 'Volume Button Width Design Four',
		name: 'volumeButtonWidthDesignFour',
		description: 'volume button Width Design Four',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign4 ._volumeButton',
		noPrefix: true,
	},

	{
		groupName: 'fullScreen icon Width',
		displayName: 'fullScreen icon Width Design One',
		name: 'fullScreeniconWidthDesignOne',
		defaultValue: '15px',
		description: 'fullScreen icon WidthDesign One',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign1 ._fullScreen ',
		noPrefix: true,
	},
	{
		groupName: 'fullScreen icon Width',
		displayName: 'fullScreen icon Width Design Two',
		name: 'fullScreeniconWidthDesignTwo',
		defaultValue: '15px',
		description: 'fullScreen icon WidthDesign Two',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign2 ._fullScreen ',
		noPrefix: true,
	},
	{
		groupName: 'fullScreen icon Width',
		displayName: 'fullScreen icon Width Design Three',
		name: 'fullScreeniconWidthDesignThree',
		description: 'fullScreen icon WidthDesign Three',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign3 ._fullScreen ',
		noPrefix: true,
	},
	{
		groupName: 'fullScreen icon Width',
		displayName: 'fullScreen icon Width Design Four',
		name: 'fullScreeniconWidthDesignFour',
		description: 'fullScreen icon WidthDesign Four',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign4 ._fullScreen ',
		noPrefix: true,
	},

	{
		groupName: 'Video PIP Icon Width',
		displayName: 'Video PIP Icon Width ',
		name: 'videoPIPIconWidth',
		defaultValue: '15px',
		description: 'Video PIP iconDesign One',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign1 ._pip',
		noPrefix: true,
	},
	{
		groupName: 'Video PIP Icon Width',
		displayName: 'Video PIP Icon Width ',
		name: 'videoPIPIconWidth',
		defaultValue: '18px',
		description: 'Video PIP iconDesign Two',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign2 ._pip',
		noPrefix: true,
	},
	{
		groupName: 'Video PIP Icon Width',
		displayName: 'Video PIP Icon Width ',
		name: 'videoPIPIconWidth',
		description: 'Video PIP iconDesign Three',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign3 ._pip',
		noPrefix: true,
	},
	{
		groupName: 'Video PIP Icon Width',
		displayName: 'Video PIP Icon Width ',
		name: 'videoPIPIconWidth',
		description: 'Video PIP iconDesign Four',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign4 ._pip',
		noPrefix: true,
	},

	{
		groupName: 'Video Play Back Icon Width',
		displayName: 'Video Play Back Icon Width',
		name: 'videoPlayBackIconWidth',
		defaultValue: '15px',
		description: 'video playbackiconDesign One',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign1 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon Width',
		displayName: 'Video Play Back Icon Width',
		name: 'videoPlayBackIconWidth',
		defaultValue: '20px',
		description: 'video playbackiconDesign Two',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign2 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon Width',
		displayName: 'Video Play Back Icon Width',
		name: 'videoPlayBackIconWidth',
		description: 'video playbackiconDesign Three',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign3 ._playIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Play Back Icon Width',
		displayName: 'Video Play Back Icon Width',
		name: 'videoPlayBackIconWidth',
		description: 'video playbackiconDesign Four',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign4 ._playIcon',
		noPrefix: true,
	},

	{
		groupName: 'Video Pause  Icon Width',
		displayName: 'Video Pause  Icon Width',
		name: 'videoPauseIconWidth',
		defaultValue: '15px',
		description: 'video Pause IconDesign One',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign1 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Pause  Icon Width',
		displayName: 'Video Pause  Icon Width',
		name: 'videoPauseIconWidth',
		defaultValue: '20px',
		description: 'video Pause IconDesign Two',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign2 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Pause  Icon Width',
		displayName: 'Video Pause  Icon Width',
		name: 'videoPauseIconWidth',
		description: 'video Pause IconDesign Three',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign3 ._pauseIcon',
		noPrefix: true,
	},
	{
		groupName: 'Video Pause  Icon Width',
		displayName: 'Video Pause  Icon Width',
		name: 'videoPauseIconWidth',
		description: 'video Pause IconDesign Four',
		cssProperty: 'width',
		selector: '.comp.compVideo._videoDesign4 ._pauseIcon',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
