import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'Icon Color',
		displayName: 'Default Icon Color',
		name: 'defaultIconColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compIcon._defaultIcon._default, .comp.compIcon._defaultIcon._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Light Icon Color',
		name: 'lightIconColor',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compIcon._lightIcon._default, .comp.compIcon._lightIcon._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Primary Icon Color',
		name: 'primaryIconColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector: '.comp.compIcon._primary._default, .comp.compIcon._primary._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Secondary Icon Color',
		name: 'secondaryIconColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector: '.comp.compIcon._secondary._default , .comp.compIcon._secondary._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Tertiary Icon Color',
		name: 'tertiaryIconColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector: '.comp.compIcon._tertiary._default, .comp.compIcon._tertiary._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Quaternary Icon Color',
		name: 'quaternaryIconColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector: '.comp.compIcon._quaternary._default, .comp.compIcon._quaternary._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Quinary Icon Color',
		name: 'quinaryIconColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector: '.comp.compIcon._quinary._default, .comp.compIcon._quinary._outlined',
		noPrefix: true,
	},

	{
		groupName: 'Icon Border Color',
		displayName: 'Default Icon Border Color',
		name: 'defaultIconBorderColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'border-color',
		selector: '.comp.compIcon._defaultIcon',
		noPrefix: true,
	},
	{
		groupName: 'Icon Border Color',
		displayName: 'Light Icon Border Color',
		name: 'lightIconBorderColor',
		defaultValue: '<fontColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compIcon._lightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Icon Border Color',
		displayName: 'Primary Menu Border Color',
		name: 'primaryMenuBorderColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compIcon._primary',
		noPrefix: true,
	},
	{
		groupName: 'Icon Border Color',
		displayName: 'Secondary Menu Border Color',
		name: 'secondaryMenuBorderColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compIcon._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Icon Border Color',
		displayName: 'Tertiary Menu Border Color',
		name: 'tertiaryMenuBorderColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compIcon._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Icon Border Color',
		displayName: 'Quaternary Menu Border Color',
		name: 'quaternaryMenuBorderColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'border-color',
		selector: '.comp.compIcon._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Icon Border Color',
		displayName: 'Quinary Menu Border Color',
		name: 'quinaryMenuBorderColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'border-color',
		selector: '.comp.compIcon._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Icon Border',
		name: 'defaultIconBorder',
		cssProperty: 'border',
		selector: '.comp.compIcon._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Icon Border',
		name: 'outlineIconBorder',
		defaultValue: '2px solid',
		cssProperty: 'border',
		selector: '.comp.compIcon._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Icon Border',
		name: 'filledIconBorder',
		cssProperty: 'border',
		selector: '.comp.compIcon._filled',
		noPrefix: true,
	},
	{
		groupName: 'Rounded',
		displayName: 'Rounded Icon Border',
		name: 'roundedIconBorder',
		cssProperty: 'border',
		selector: '.comp.compIcon._rounded',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Icon Border Radius',
		name: 'defaultIconBorderRadius',
		cssProperty: 'border-radius',
		selector: '.comp.compIcon._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Icon Border Radius',
		name: 'outlineIconBorderRadius',
		defaultValue: '3px',
		cssProperty: 'border-radius',
		selector: '.comp.compIcon._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Icon Border Radius',
		name: 'filledIconBorderRadius',
		defaultValue: '3px',
		cssProperty: 'border-radius',
		selector: '.comp.compIcon._filled',
		noPrefix: true,
	},
	{
		groupName: 'Rounded',
		displayName: 'Rounded Icon Border Radius',
		name: 'roundedIconBorderRadius',
		defaultValue: '50%',
		cssProperty: 'border-radius',
		selector: '.comp.compIcon._rounded',
		noPrefix: true,
	},

	{
		groupName: 'Icon Filled Background Color',
		displayName: 'Default Icon Background Color',
		name: 'defaultIconBackgroundColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'background',
		selector: '.comp.compIcon._defaultIcon._filled, .comp.compIcon._defaultIcon._rounded',
		noPrefix: true,
	},
	{
		groupName: 'Icon Filled Background Color',
		displayName: 'Light Icon Background Color',
		name: 'lightIconBackgroundColor',
		defaultValue: '<backgroundColorNine>',
		cssProperty: 'background',
		selector: '.comp.compIcon._lightIcon._filled, .comp.compIcon._lightIcon._rounded',
		noPrefix: true,
	},
	{
		groupName: 'Icon Filled Background Color',
		displayName: 'Primary Icon Background Color',
		name: 'primaryIconBackgroundColor',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compIcon._primary._filled, .comp.compIcon._primary._rounded',
		noPrefix: true,
	},
	{
		groupName: 'Icon Filled Background Color',
		displayName: 'Secondary Icon Background Color',
		name: 'secondaryIconBackgroundColor',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compIcon._secondary._filled , .comp.compIcon._secondary._rounded',
		noPrefix: true,
	},
	{
		groupName: 'Icon Filled Background Color',
		displayName: 'Tertiary Icon Background Color',
		name: 'tertiaryIconBackgroundColor',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compIcon._tertiary._filled, .comp.compIcon._tertiary._rounded',
		noPrefix: true,
	},
	{
		groupName: 'Icon Filled Background Color',
		displayName: 'Quaternary Icon Background Color',
		name: 'quaternaryIconBackgroundColor',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compIcon._quaternary._filled, .comp.compIcon._quaternary._rounded',
		noPrefix: true,
	},
	{
		groupName: 'Icon Filled Background Color',
		displayName: 'Quinary Icon Background Color',
		name: 'quinaryIconBackgroundColor',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compIcon._quinary._filled, .comp.compIcon._quinary._rounded',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Icon Font Size',
		name: 'defaultIconFontSize',
		defaultValue: '16px',
		cssProperty: 'font-size',
		selector: '.comp.compIcon._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Icon Font Size',
		name: 'outlineIconFontSize',
		defaultValue: '16px',
		cssProperty: 'font-size',
		selector: '.comp.compIcon._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Icon Font Size',
		name: 'filledIconFontSize',
		defaultValue: '16px',
		cssProperty: 'font-size',
		selector: '.comp.compIcon._filled',
		noPrefix: true,
	},
	{
		groupName: 'Rounded',
		displayName: 'Rounded Icon Font Size',
		name: 'roundedIconFontSize',
		defaultValue: '16px',
		cssProperty: 'font-size',
		selector: '.comp.compIcon._rounded',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Icon Padding Size',
		name: 'defaultIconPaddingSize',
		defaultValue: '6px',
		cssProperty: 'padding',
		selector: '.comp.compIcon._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Icon Padding Size',
		name: 'outlineIconPaddingSize',
		defaultValue: '6px',
		cssProperty: 'padding',
		selector: '.comp.compIcon._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Icon Padding Size',
		name: 'filledIconPaddingSize',
		defaultValue: '6px',
		cssProperty: 'padding',
		selector: '.comp.compIcon._filled',
		noPrefix: true,
	},
	{
		groupName: 'Rounded',
		displayName: 'Rounded Icon Padding Size',
		name: 'roundedIconPaddingSize',
		defaultValue: '6px',
		cssProperty: 'padding',
		selector: '.comp.compIcon._rounded',
		noPrefix: true,
	},

	{
		groupName: 'Icon Color',
		displayName: 'Default Icon Filled and Rounded Color',
		name: 'defaultIconFilledRoundedColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compIcon._defaultIcon._filled, .comp.compIcon._defaultIcon._rounded',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Light Icon Filled and Rounded Color',
		name: 'lightIconFilledRoundedColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compIcon._lightIcon._filled, .comp.compIcon._lightIcon._rounded',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Primary Icon Filled and Rounded Color',
		name: 'primaryIconFilledRoundedColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compIcon._primary._filled, .comp.compIcon._primary._rounded',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Secondary Icon Filled and Rounded Color',
		name: 'secondaryIconFilledRoundedColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compIcon._secondary._filled , .comp.compIcon._secondary._rounded',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Tertiary Icon Filled and Rounded Color',
		name: 'tertiaryIconFilledRoundedColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compIcon._tertiary._filled, .comp.compIcon._tertiary._rounded',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Quaternary Icon Filled and Rounded Color',
		name: 'quaternaryIconFilledRoundedColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compIcon._quaternary._filled, .comp.compIcon._quaternary._rounded',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Quinary Icon Filled and Rounded Color',
		name: 'quinaryIconFilledRoundedColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compIcon._quinary._filled, .comp.compIcon._quinary._rounded',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
