import { StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'File Upload Border Inline Design1',
		displayName: 'File Upload Border Inline Design1 Border',
		name: 'fileuploadborderinlinedesign1Border',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design1 ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Inline Design2',
		displayName: 'File Upload Border Inline Design2 Border',
		name: 'fileuploadborderinlinedesign2Border',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design2  ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Inline Design3',
		displayName: 'File Upload Border Inline Design3 Border',
		name: 'fileuploadborderinlinedesign3Border',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design3  ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Inline Design4',
		displayName: 'File Upload Border Inline Design4 Border',
		name: 'fileuploadborderinlinedesign4Border',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design4',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Icon Design1',
		displayName: 'File Upload Border Icon Design1 Border',
		name: 'fileuploadbordericondesign1Border',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_icon_design1  ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border DropArea Design1',
		displayName: 'File Upload Border DropArea Design1 Border',
		name: 'fileuploadborderdropareadesign1Border',
		defaultValue: '1px dashed',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._droparea_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border DropArea Design2',
		displayName: 'File Upload Border DropArea Design2 Border',
		name: 'fileuploadborderdropareadesign2Border',
		defaultValue: '1px dashed',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._droparea_design2',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border DropArea Design3',
		displayName: 'File Upload Border DropArea Design3 Border',
		name: 'fileuploadborderdropareadesign3Border',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._droparea_design3',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border DropArea Design3',
		displayName: 'File Upload Border DropArea Design3 Border Bottom',
		name: 'fileUploadBorderDropAreaDesign3BorderBottom',
		defaultValue: '1px solid',
		cssProperty: 'border-bottom',
		selector: '.comp.compFileUpload._droparea_design3 ._mainText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Inline Design1',
		displayName: 'File Upload Border Inline Design1 Top Border',
		name: 'fileUploadBorderInlineDesign1TopBorder',
		defaultValue: '1px solid',
		cssProperty: 'border-top',
		selector: '.comp.compFileUpload._inline_design1 ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Inline Design1',
		displayName: 'File Upload Border Inline Design1 Right Border',
		name: 'fileUploadBorderInlineDesign1RightBorder',
		cssProperty: 'border-right',
		selector: '.comp.compFileUpload._inline_design1 ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Inline Design1',
		displayName: 'File Upload Border Inline Design1 Bottom Border',
		name: 'fileUploadBorderInlineDesign1BottomBorder',
		defaultValue: '1px solid',
		cssProperty: 'border-bottom',
		selector: '.comp.compFileUpload._inline_design1 ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Inline Design1',
		displayName: 'File Upload Border Inline Design1 Left Border',
		name: 'fileUploadBorderInlineDesign1LeftBorder',
		defaultValue: '1px solid',
		cssProperty: 'border-left',
		selector: '.comp.compFileUpload._inline_design1 ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Icon Design1',
		displayName: 'File Upload Border Icon Design1 Top Border',
		name: 'fileUploadBorderIconDesign1TopBorder',
		defaultValue: '1px solid',
		cssProperty: 'border-top',
		selector: '.comp.compFileUpload._inline_icon_design1 ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Icon Design2',
		displayName: 'File Upload Border Icon Design1 Right Border',
		name: 'fileUploadBorderIconDesign1RightBorder',
		cssProperty: 'border-right',
		selector: '.comp.compFileUpload._inline_icon_design1 ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Icon Design3',
		displayName: 'File Upload Border Icon Design1 Bottom Border',
		name: 'fileUploadBorderIconDesign1BottomBorder',
		defaultValue: '1px solid',
		cssProperty: 'border-bottom',
		selector: '.comp.compFileUpload._inline_icon_design1 ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Icon Design4',
		displayName: 'File Upload Border Icon Design1 Left Border',
		name: 'fileUploadBorderIconDesign1LeftBorder',
		defaultValue: '1px solid',
		cssProperty: 'border-left',
		selector: '.comp.compFileUpload._inline_icon_design1 ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color Inline Design1',
		displayName: 'File Upload Border Color Inline Design1 Border',
		name: 'fileuploadbordercolorinlinedesign1Border',
		defaultValue: '<borderColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._inline_design1 ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color Inline Design2',
		displayName: 'File Upload Border Color Inline Design2 Border',
		name: 'fileuploadbordercolorinlinedesign2Border',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._inline_design2',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color Inline Design3',
		displayName: 'File Upload Border Color Inline Design3 Border',
		name: 'fileuploadbordercolorinlinedesign3Border',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._inline_design3',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color Inline Design4',
		displayName: 'File Upload Border Color Inline Design4 Border',
		name: 'fileuploadbordercolorinlinedesign4Border',
		defaultValue: '<borderColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._inline_design4',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color Icon Design1',
		displayName: 'File Upload Border Color Icon Design1 Border',
		name: 'fileuploadbordercoloricondesign1Border',
		defaultValue: '<borderColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._inline_icon_design1 ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color DropArea Design1',
		displayName: 'File Upload Border Color DropArea Design1 Border Color',
		name: 'fileuploadbordercolordropareadesign1Border',
		defaultValue: '<borderColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color DropArea Design2',
		displayName: 'File Upload Border Color DropArea Design2 Border Color',
		name: 'fileuploadbordercolordropareadesign2Border',
		defaultValue: '<borderColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design2',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color DropArea Design3',
		displayName: 'File Upload Border Color DropArea Design3 Border Color',
		name: 'fileuploadbordercolordropareadesign3Border',
		defaultValue: '<borderColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design3',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color DropArea Design3',
		displayName: 'File Upload Border Color DropArea Design3 Border Bottom Color',
		name: 'fileUploadBorderColorDropAreaDesign3BorderBottomColor',
		defaultValue: '<borderColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design3 ._mainText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Radius Inline Design1',
		displayName: 'File Upload Border Radius Inline Design1 Border',
		name: 'fileuploadborderradiusinlinedesign1Border',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Radius Inline Design2',
		displayName: 'File Upload Border Radius Inline Design2 Border',
		name: 'fileuploadborderradiusinlinedesign2Border',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design2',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Radius Inline Design3',
		displayName: 'File Upload Border Radius Inline Design3 Border',
		name: 'fileuploadborderradiusinlinedesign3Border',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design3',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Radius Inline Design4',
		displayName: 'File Upload Border Radius Inline Design4 Border',
		name: 'fileuploadborderradiusinlinedesign4Border',
		defaultValue: '100px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design4',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Radius Icon Design1',
		displayName: 'File Upload Border Radius Icon Design1 Border',
		name: 'fileuploadborderradiusicondesign1Border',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_icon_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Radius Droparea Design1',
		displayName: 'File Upload Border Radius Droparea Design1 Border',
		name: 'fileuploadborderradiusdropareadesign1Border',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._droparea_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Radius Droparea Design2',
		displayName: 'File Upload Border Radius Droparea Design2 Border',
		name: 'fileuploadborderradiusdropareadesign2Border',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._droparea_design2',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Radius Droparea Design3',
		displayName: 'File Upload Border Radius Droparea Design3 Border',
		name: 'fileuploadborderradiusdropareadesign3Border',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._droparea_design3',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Background Color',
		displayName: 'Primary File Upload Background Color for Button Background',
		name: 'primaryFileUploadBackgroundColorforButtonBackground',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._primary ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Background Color',
		displayName: 'Secondary File Upload Background Color for Button Background',
		name: 'secondaryFileUploadBackgroundColorforButtonBackground',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._secondary ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Background Color',
		displayName: 'Tertiary File Upload Background Color for Button Background',
		name: 'tertiaryFileUploadBackgroundColorforButtonBackground',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._tertiary ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Background Color',
		displayName: 'Quaternary File Upload Background Color for Button Background',
		name: 'quaternaryFileUploadBackgroundColorforButtonBackground',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._quaternary ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Background Color',
		displayName: 'Quinary File Upload Background Color for Button Background',
		name: 'quinaryFileUploadBackgroundColorforButtonBackground',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._quinary ._fileUploadButton',
		noPrefix: true,
	},

	{
		groupName: 'Color',
		displayName: 'Primary File Upload Main Text Color',
		name: 'primaryFileUploadMainTextColor',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector: '.comp.compFileUpload._inline_design3._primary ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Secondary File Upload Main Text Color',
		name: 'secondaryFileUploadMainTextColor',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compFileUpload._inline_design3._secondary ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Tertiary File Upload Main Text Color',
		name: 'tertiaryFileUploadMainTextColor',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector: '.comp.compFileUpload._inline_design3._tertiary ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quaternary File Upload Main Text Color',
		name: 'quaternaryFileUploadMainTextColor',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector: '.comp.compFileUpload._inline_design3._quaternary ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quinary File Upload Main Text Color',
		name: 'quinaryFileUploadMainTextColor',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector: '.comp.compFileUpload._inline_design3._quinary ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Dark File Upload Text Color',
		name: 'darkFileUploadTextColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compFileUpload ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Light File Upload Text Color',
		name: 'lightFileUploadTextColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compFileUpload ._fileUploadButton',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Button Padding',
		displayName: 'File Upload Button Padding Inline Design One',
		name: 'fileUploadButtonPaddingInlineDesignOne',
		defaultValue: '8px 12px',
		cssProperty: 'padding',
		selector: '.comp.compFileUpload ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Button Padding',
		displayName: 'File Upload Button Padding Inline Design Two',
		name: 'fileUploadButtonPaddingInlineDesignTwo',
		defaultValue: '8px 12px',
		cssProperty: 'padding',
		selector: '.comp.compFileUpload ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Button Padding',
		displayName: 'File Upload Button Padding Inline Design Three',
		name: 'fileUploadButtonPaddingInlineDesignThree',
		defaultValue: '8px 12px',
		cssProperty: 'padding',
		selector: '.comp.compFileUpload ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Button Padding',
		displayName: 'File Upload Button Padding Inline Design Four',
		name: 'fileUploadButtonPaddingInlineDesignFour',
		defaultValue: '8px 12px',
		cssProperty: 'padding',
		selector: '.comp.compFileUpload ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Padding',
		displayName: 'File Upload Padding DropArea Design3',
		name: 'fileUploadPaddingDropAreaDesign3',
		defaultValue: '10px',
		cssProperty: 'padding',
		selector: '.comp.compFileUpload._droparea_design3',
		noPrefix: true,
	},

	{
		groupName: 'Border Radius',
		displayName: 'Border Radius File Upload Button Inline Design One',
		name: 'borderRadiusFileUploadButtonInlineDesignOne',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design1 ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Border Radius',
		displayName: 'Border Radius File Upload Button Inline Design Two',
		name: 'borderRadiusFileUploadButtonInlineDesignTwo',
		defaultValue: '0px 2px 2px 0px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design2  ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Border Radius',
		displayName: 'Border Radius File Upload Button Inline Design Three',
		name: 'borderRadiusFileUploadButtonInlineDesignThree',
		defaultValue: '5px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design3  ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Border Radius',
		displayName: 'Border Radius File Upload Button Inline Design Four',
		name: 'borderRadiusFileUploadButtonInlineDesignFour',
		defaultValue: '100px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design4  ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Border Radius',
		displayName: 'Border Radius File Upload Button Icon Design One',
		name: 'borderRadiusFileUploadButtonIconDesignOne',
		defaultValue: '0px 4px 4px 0px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_icon_design1  ._fileUploadButton',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Button Border Inline Design1',
		displayName: 'File Upload Button Border Inline Design1 Border',
		name: 'fileuploadbuttonborderinlinedesign1Border',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design1 ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Button Border Inline Design2',
		displayName: 'File Upload Button Border Inline Design2 Border',
		name: 'fileuploadbuttonborderinlinedesign2Border',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design2  ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Button Border Inline Design3',
		displayName: 'File Upload Button Border Inline Design3 Border',
		name: 'fileuploadbuttonborderinlinedesign3Border',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design3  ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Button Border Inline Design4',
		displayName: 'File Upload Button Border Inline Design4 Border',
		name: 'fileuploadbuttonborderinlinedesign4Border',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design4  ._fileUploadButton',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Background Color Hover',
		displayName: 'File Upload Background Color Hover Upload Button Background Primary',
		name: 'fileUploadBackgroundColorHoverUploadButtonBackgroundPrimary',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._primary ._fileUploadButton:hover',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Background Color Hover',
		displayName: 'File Upload Background Color Hover Upload Button Background Secondary',
		name: 'fileUploadBackgroundColorHoverUploadButtonBackgroundSecondary',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._secondary ._fileUploadButton:hover',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Background Color Hover',
		displayName: 'File Upload Background Color Hover Upload Button Background Tertiary',
		name: 'fileUploadBackgroundColorHoverUploadButtonBackgroundTertiary',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._tertiary ._fileUploadButton:hover',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Background Color Hover',
		displayName: 'File Upload Background Color Hover Upload Button Background Quaternary',
		name: 'fileUploadBackgroundColorHoverUploadButtonBackgroundQuaternary',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._quaternary ._fileUploadButton:hover',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Background Color Hover',
		displayName: 'File Upload Background Color Hover Upload Button Background Quinary',
		name: 'fileUploadBackgroundColorHoverUploadButtonBackgroundQuinary',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._quinary ._fileUploadButton:hover',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Width',
		displayName: 'File Upload Width Inline Design One Button Width',
		name: 'fileUploadWidthInlineDesignOneButtonWidth',
		defaultValue: '50%',
		cssProperty: 'width',
		selector: '.comp.compFileUpload ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Width',
		displayName: 'File Upload Width Inline Design One Text Width',
		name: 'fileUploadWidthInlineDesignOneTextWidth',
		defaultValue: '50%',
		cssProperty: 'width',
		selector: '.comp.compFileUpload ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Width',
		displayName: 'File Upload Width Icon Only Design One Button Width',
		name: 'fileUploadWidthIconOnlyDesignOneButtonWidth',
		defaultValue: '30px',
		cssProperty: 'width',
		selector: '.comp.compFileUpload._inline_icon_design1 ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Width',
		displayName: 'File Upload Width Icon Only Design One Text Width',
		name: 'fileUploadWidthIconOnlyDesignOneTextWidth',
		defaultValue: '1',
		cssProperty: 'flex',
		selector: '.comp.compFileUpload._inline_icon_design1 ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Width',
		displayName: 'File Upload Width Full Icon Design One Text Width',
		name: 'fileUploadWidthFullIconDesignOneTextWidth',
		defaultValue: '100%',
		cssProperty: 'width',
		selector: '.comp.compFileUpload._only_icon_design1 ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Width',
		displayName: 'File Upload Width Full Icon Design Two Text Width',
		name: 'fileUploadWidthFullIconDesignTwoTextWidth',
		defaultValue: '100%',
		cssProperty: 'width',
		selector: '.comp.compFileUpload._only_icon_design2 ._fileUploadText',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Text Background',
		displayName: 'File Upload Text Background Inline Design One Text Background',
		name: 'fileUploadTextBackgroundInlineDesignOneTextBackground',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._inline_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Text Background',
		displayName: 'File Upload Text Background Inline Design Two Text Background',
		name: 'fileUploadTextBackgroundInlineDesignTwoTextBackground',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._inline_design2',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Text Background',
		displayName: 'File Upload Text Background Inline Design Three Text Background',
		name: 'fileUploadTextBackgroundInlineDesignThreeTextBackground',
		defaultValue: '<backgroundColorNine>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._inline_design3',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Text Background',
		displayName: 'File Upload Text Background Inline Design Four Text Background',
		name: 'fileUploadTextBackgroundInlineDesignFourTextBackground',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._inline_design4',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Text Background',
		displayName: 'File Upload Text Background Icon Design One Text Background',
		name: 'fileUploadTextBackgroundIconDesignOneTextBackground',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._inline_icon_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Text Background',
		displayName: 'File Upload Text Background DropArea Design One Text Background',
		name: 'fileUploadTextBackgroundDropAreaDesignOneTextBackground',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._droparea_design1',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Text Background',
		displayName: 'File Upload Text Background DropArea Design Three Text Background',
		name: 'fileUploadTextBackgroundDropAreaDesignThreeTextBackground',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._droparea_design3',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Flex Direction',
		displayName: 'File Upload Flex Direction Droparea Design 1 Flex Direction',
		name: 'fileUploadFlexDirectionDropareaDesign1FlexDirection',
		defaultValue: 'column',
		cssProperty: 'flex-direction',
		selector: '.comp.compFileUpload._droparea_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Flex Direction',
		displayName: 'File Upload Flex Direction Droparea Design 2 Flex Direction',
		name: 'fileUploadFlexDirectionDropareaDesign2FlexDirection',
		defaultValue: 'column',
		cssProperty: 'flex-direction',
		selector: '.comp.compFileUpload._droparea_design2',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Flex Direction',
		displayName: 'File Upload Flex Direction Droparea Design 3 Flex Direction',
		name: 'fileUploadFlexDirectionDropareaDesign3FlexDirection',
		cssProperty: 'flex-direction',
		selector: '.comp.compFileUpload._droparea_design3',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Flex Alignment',
		displayName: 'File Upload Flex Alignment Droparea Design 1 Flex Alignment',
		name: 'fileUploadFlexAlignmentDropareaDesign1FlexAlignment',
		defaultValue: 'space-around',
		cssProperty: 'justify-content',
		selector: '.comp.compFileUpload._droparea_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Flex Alignment',
		displayName: 'File Upload Flex Alignment Droparea Design 2 Flex Alignment',
		name: 'fileUploadFlexAlignmentDropareaDesign2FlexAlignment',
		defaultValue: 'space-around',
		cssProperty: 'justify-content',
		selector: '.comp.compFileUpload._droparea_design2',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Flex Alignment',
		displayName: 'File Upload Flex Alignment Droparea Design 3 Flex Alignment',
		name: 'fileUploadFlexAlignmentDropareaDesign3FlexAlignment',
		defaultValue: 'space-around',
		cssProperty: 'justify-content',
		selector: '.comp.compFileUpload._droparea_design3',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Height',
		displayName: 'File Upload Height Droparea Design One Height',
		name: 'fileUploadHeightDropareaDesignOneHeight',
		defaultValue: '150px',
		cssProperty: 'height',
		selector: '.comp.compFileUpload._droparea_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Height',
		displayName: 'File Upload Height Droparea Design Two Height',
		name: 'fileUploadHeightDropareaDesignTwoHeight',
		defaultValue: '150px',
		cssProperty: 'height',
		selector: '.comp.compFileUpload._droparea_design2',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Height',
		displayName: 'File Upload Height Droparea Design Three Height',
		name: 'fileUploadHeightDropareaDesignThreeHeight',
		defaultValue: '80px',
		cssProperty: 'height',
		selector: '.comp.compFileUpload._droparea_design3',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Height',
		displayName: 'File Upload Height Inline Design One Text Height',
		name: 'fileUploadHeightInlineDesignOneTextHeight',
		defaultValue: '100%',
		cssProperty: 'height',
		selector: '.comp.compFileUpload._inline_design1 ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Height',
		displayName: 'File Upload Height Inline Design Two Text Height',
		name: 'fileUploadHeightInlineDesignTwoTextHeight',
		defaultValue: '100%',
		cssProperty: 'height',
		selector: '.comp.compFileUpload._inline_design2  ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Height',
		displayName: 'File Upload Height Inline Design Three Text Height',
		name: 'fileUploadHeightInlineDesignThreeTextHeight',
		defaultValue: '100%',
		cssProperty: 'height',
		selector: '.comp.compFileUpload._inline_design3  ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Height',
		displayName: 'File Upload Height Inline Design Four Text Height',
		name: 'fileUploadHeightInlineDesignFourTextHeight',
		defaultValue: '100%',
		cssProperty: 'height',
		selector: '.comp.compFileUpload._inline_design4  ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Height',
		displayName: 'File Upload Height Inline Design Icon Text Height',
		name: 'fileUploadHeightInlineDesignIconTextHeight',
		defaultValue: '100%',
		cssProperty: 'height',
		selector: '.comp.compFileUpload._inline_icon_design1  ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Icon Height',
		displayName: 'File Upload Icon Height Icon Only Design One Height',
		name: 'fileUploadIconHeightIconOnlyDesignOneHeight',
		defaultValue: '50px',
		cssProperty: 'height',
		selector: '.comp.compFileUpload._only_icon_design1 ._uploadIcon._upload_icon_1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Icon Height',
		displayName: 'File Upload Icon Height Icon Only Design Two Height',
		name: 'fileUploadIconHeightIconOnlyDesignTwoHeight',
		defaultValue: '84px',
		cssProperty: 'height',
		selector: '.comp.compFileUpload._only_icon_design2 ._uploadIcon._upload_icon_2',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Border Color',
		displayName: 'Primary File Upload Border Color Droparea design2 border Color',
		name: 'primaryFileUploadBorderColorDropareadesign2borderColor',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design2._primary',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color',
		displayName: 'Secondary File Upload Border Color Droparea design2 border Color',
		name: 'secondaryFileUploadBorderColorDropareadesign2borderColor',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design2._secondary',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color',
		displayName: 'Tertiary File Upload Border Color Droparea design2 border Color',
		name: 'tertiaryFileUploadBorderColorDropareadesign2borderColor',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design2._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color',
		displayName: 'Quaternary File Upload Border Color Droparea design2 border Color',
		name: 'quaternaryFileUploadBorderColorDropareadesign2borderColor',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design2._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color',
		displayName: 'Quinary File Upload Border Color Droparea design2 border Color',
		name: 'quinaryFileUploadBorderColorDropareadesign2borderColor',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design2._quinary',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Background Color Droparea Design2',
		displayName:
			'Primary File Upload Background Color Droparea Design2 Droparea design2 Background Color',
		name: 'primaryFileUploadBackgroundColorDropareaDesign2Dropareadesign2BackgroundColor',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._droparea_design2._primary',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Background Color Droparea Design3',
		displayName:
			'Secondary File Upload Background Color Droparea Design3 Droparea design2 Background Color',
		name: 'secondaryFileUploadBackgroundColorDropareaDesign3Dropareadesign2BackgroundColor',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._droparea_design2._secondary',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Background Color Droparea Design4',
		displayName:
			'Tertiary File Upload Background Color Droparea Design4 Droparea design2 Background Color',
		name: 'tertiaryFileUploadBackgroundColorDropareaDesign4Dropareadesign2BackgroundColor',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._droparea_design2._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Background Color Droparea Design5',
		displayName:
			'Quaternary File Upload Background Color Droparea Design5 Droparea design2 Background Color',
		name: 'quaternaryFileUploadBackgroundColorDropareaDesign5Dropareadesign2BackgroundColor',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._droparea_design2._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Background Color Droparea Design6',
		displayName:
			'Quinary File Upload Background Color Droparea Design6 Droparea design2 Background Color',
		name: 'quinaryFileUploadBackgroundColorDropareaDesign6Dropareadesign2BackgroundColor',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._droparea_design2._quinary',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Icon Color',
		displayName: 'Primary File Upload Icon Color Droparea design Icon Color',
		name: 'primaryFileUploadIconColorDropareadesignIconColor',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector:
			'.comp.compFileUpload._droparea_design1._primary ._uploadIcon, .comp.compFileUpload._droparea_design2._primary ._uploadIcon, .comp.compFileUpload._droparea_design3._primary ._uploadIcon, .comp.compFileUpload._only_icon_design1._primary ._uploadIcon, .comp.compFileUpload._only_icon_design2._primary ._uploadIcon',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Icon Color',
		displayName: 'Secondary File Upload Icon Color Droparea design Icon Color',
		name: 'secondaryFileUploadIconColorDropareadesignIconColor',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compFileUpload._droparea_design1._secondary ._uploadIcon, .comp.compFileUpload._droparea_design2._secondary ._uploadIcon, .comp.compFileUpload._droparea_design3._secondary ._uploadIcon, .comp.compFileUpload._only_icon_design1._secondary ._uploadIcon, .comp.compFileUpload._only_icon_design2._secondary ._uploadIcon',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Icon Color',
		displayName: 'Tertiary File Upload Icon Color Droparea design Icon Color',
		name: 'tertiaryFileUploadIconColorDropareadesignIconColor',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector:
			'.comp.compFileUpload._droparea_design1._tertiary ._uploadIcon, .comp.compFileUpload._droparea_design2._tertiary ._uploadIcon, .comp.compFileUpload._droparea_design3._tertiary ._uploadIcon, .comp.compFileUpload._only_icon_design1._tertiary ._uploadIcon, .comp.compFileUpload._only_icon_design2._tertiary ._uploadIcon',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Icon Color',
		displayName: 'Quaternary File Upload Icon Color Droparea design Icon Color',
		name: 'quaternaryFileUploadIconColorDropareadesignIconColor',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector:
			'.comp.compFileUpload._droparea_design1._quaternary ._uploadIcon, .comp.compFileUpload._droparea_design2._quaternary ._uploadIcon, .comp.compFileUpload._droparea_design3._quaternary ._uploadIcon, .comp.compFileUpload._only_icon_design1._quaternary ._uploadIcon, .comp.compFileUpload._only_icon_design2._quaternary ._uploadIcon',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Icon Color',
		displayName: 'Quinary File Upload Icon Color Droparea design Icon Color',
		name: 'quinaryFileUploadIconColorDropareadesignIconColor',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector:
			'.comp.compFileUpload._droparea_design1._quinary ._uploadIcon, .comp.compFileUpload._droparea_design2._quinary ._uploadIcon, .comp.compFileUpload._droparea_design3._quinary ._uploadIcon, .comp.compFileUpload._only_icon_design1._quinary ._uploadIcon, .comp.compFileUpload._only_icon_design2._quinary ._uploadIcon',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Color',
		displayName: ' File Upload ColorSupport Text Color One File Upload',
		name: ' FileUploadColorSupportTextColorOneFileUpload',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compFileUpload ._subtext',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Support Text Font Size',
		displayName: 'File Upload Support Text Font Size',
		name: 'fileUploadSupportTextFontSize',
		defaultValue: '12px',
		cssProperty: 'font-size',
		selector: '.comp.compFileUpload ._subtext',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Padding',
		displayName: 'File Upload Padding Top DropArea Design 3',
		name: 'fileUploadPaddingTopDropAreaDesign3',
		defaultValue: '16px',
		cssProperty: 'padding-top',
		selector: '.comp.compFileUpload._droparea_design3  ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Margin',
		displayName: 'File Upload Margin DropArea Design 3 Margin Right',
		name: 'fileUploadMarginDropAreaDesign3MarginRight',
		defaultValue: '5px',
		cssProperty: 'margin-right',
		selector: '.comp.compFileUpload._droparea_design3  ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Bottom',
		displayName: 'File Upload Bottom DropArea Design 3',
		name: 'fileUploadBottomDropAreaDesign3',
		defaultValue: '4px',
		cssProperty: 'bottom',
		selector: '.comp.compFileUpload._droparea_design3  ._subtext',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Icon Font Size',
		displayName: 'File Upload Icon Font Size Big Icon Design One',
		name: 'fileUploadIconFontSizeBigIconDesignOne',
		defaultValue: '64px',
		cssProperty: 'font-size',
		selector: '.comp.compFileUpload._only_icon_design1 ._uploadIcon',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Icon Font Size',
		displayName: 'File Upload Icon Font Size Big Icon Design Two',
		name: 'fileUploadIconFontSizeBigIconDesignTwo',
		defaultValue: '84px',
		cssProperty: 'font-size',
		selector: '.comp.compFileUpload._only_icon_design2 ._uploadIcon',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
