import { StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'File Upload Border Inline Design1',
		displayName: 'File Upload Border Inline Design1 Border',
		name: 'fileuploadborderinlinedesign1Border',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Inline Design2',
		displayName: 'File Upload Border Inline Design2 Border',
		name: 'fileuploadborderinlinedesign2Border',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design2',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Inline Design3',
		displayName: 'File Upload Border Inline Design3 Border',
		name: 'fileuploadborderinlinedesign3Border',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design3',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Inline Design4',
		displayName: 'File Upload Border Inline Design4 Border',
		name: 'fileuploadborderinlinedesign4Border',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design4',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Icon Design1',
		displayName: 'File Upload Border Icon Design1 Border',
		name: 'fileuploadbordericondesign1Border',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_icon_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border DropArea Design1',
		displayName: 'File Upload Border DropArea Design1 Border',
		name: 'fileuploadborderdropareadesign1Border',
		defaultValue: '1px dashed',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._droparea_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border DropArea Design2',
		displayName: 'File Upload Border DropArea Design2 Border',
		name: 'fileuploadborderdropareadesign2Border',
		defaultValue: '1px dashed',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._droparea_design2',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border DropArea Design3',
		displayName: 'File Upload Border DropArea Design3 Border',
		name: 'fileuploadborderdropareadesign3Border',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._droparea_design3',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Border Color Inline Design1',
		displayName: 'File Upload Border Color Inline Design1 Border',
		name: 'fileuploadbordercolorinlinedesign1Border',
		defaultValue: '<borderColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._inline_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color Inline Design2',
		displayName: 'File Upload Border Color Inline Design2 Border',
		name: 'fileuploadbordercolorinlinedesign2Border',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._inline_design2',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color Inline Design3',
		displayName: 'File Upload Border Color Inline Design3 Border',
		name: 'fileuploadbordercolorinlinedesign3Border',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._inline_design3',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color Inline Design4',
		displayName: 'File Upload Border Color Inline Design4 Border',
		name: 'fileuploadbordercolorinlinedesign4Border',
		defaultValue: '<borderColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._inline_design4',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color Icon Design1',
		displayName: 'File Upload Border Color Icon Design1 Border',
		name: 'fileuploadbordercoloricondesign1Border',
		defaultValue: '<borderColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._inline_icon_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color DropArea Design1',
		displayName: 'File Upload Border Color DropArea Design1 Border Color',
		name: 'fileuploadbordercolordropareadesign1Border',
		defaultValue: '<borderColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color DropArea Design2',
		displayName: 'File Upload Border Color DropArea Design2 Border Color',
		name: 'fileuploadbordercolordropareadesign2Border',
		defaultValue: '<borderColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design2',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Color DropArea Design3',
		displayName: 'File Upload Border Color DropArea Design3 Border Color',
		name: 'fileuploadbordercolordropareadesign3Border',
		defaultValue: '<borderColorSix>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design3',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Border Radius Inline Design1',
		displayName: 'File Upload Border Radius Inline Design1 Border',
		name: 'fileuploadborderradiusinlinedesign1Border',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Radius Inline Design2',
		displayName: 'File Upload Border Radius Inline Design2 Border',
		name: 'fileuploadborderradiusinlinedesign2Border',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design2',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Radius Inline Design3',
		displayName: 'File Upload Border Radius Inline Design3 Border',
		name: 'fileuploadborderradiusinlinedesign3Border',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design3',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Radius Inline Design4',
		displayName: 'File Upload Border Radius Inline Design4 Border',
		name: 'fileuploadborderradiusinlinedesign4Border',
		defaultValue: '100px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design4',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Radius Icon Design1',
		displayName: 'File Upload Border Radius Icon Design1 Border',
		name: 'fileuploadborderradiusicondesign1Border',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_icon_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Radius Droparea Design1',
		displayName: 'File Upload Border Radius Droparea Design1 Border',
		name: 'fileuploadborderradiusdropareadesign1Border',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._droparea_design1',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Radius Droparea Design2',
		displayName: 'File Upload Border Radius Droparea Design2 Border',
		name: 'fileuploadborderradiusdropareadesign2Border',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._droparea_design2',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Border Radius Droparea Design3',
		displayName: 'File Upload Border Radius Droparea Design3 Border',
		name: 'fileuploadborderradiusdropareadesign3Border',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._droparea_design3',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Primary Upload Button Background',
		name: 'primaryUploadButtonBackground',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._primary ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Secondary Upload Button Background',
		name: 'secondaryUploadButtonBackground',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._secondary ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Tertiary Upload Button Background',
		name: 'tertiaryUploadButtonBackground',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._tertiary ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quaternary Upload Button Background',
		name: 'quaternaryUploadButtonBackground',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._quaternary ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quinary Upload Button Background',
		name: 'quinaryUploadButtonBackground',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._quinary ._fileUploadButton',
		noPrefix: true,
	},

	{
		groupName: 'Color',
		displayName: 'Primary Upload Text Color',
		name: 'primaryUploadTextColor',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector: '.comp.compFileUpload._inline_design3._primary ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Secondary Upload Text Color',
		name: 'secondaryUploadTextColor',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compFileUpload._inline_design3._secondary ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Tertiary Upload Text Color',
		name: 'tertiaryUploadTextColor',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector: '.comp.compFileUpload._inline_design3._tertiary ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quaternary Upload Text Color',
		name: 'quaternaryUploadTextColor',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector: '.comp.compFileUpload._inline_design3._quaternary ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Quinary Upload Text Color',
		name: 'quinaryUploadTextColor',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector: '.comp.compFileUpload._inline_design3._quinary ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Dark Upload Text Color',
		name: 'darkUploadTextColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compFileUpload ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'Color',
		displayName: 'Light Upload Text Color',
		name: 'lightUploadTextColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compFileUpload ._fileUploadButton',
		noPrefix: true,
	},

	{
		groupName: 'Padding',
		displayName: 'Padding Inline Design One',
		name: 'paddingInlineDesignOne',
		defaultValue: '8px 12px',
		cssProperty: 'padding',
		selector: '.comp.compFileUpload ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Padding',
		displayName: 'Padding Inline Design Two',
		name: 'paddingInlineDesignTwo',
		defaultValue: '8px 12px',
		cssProperty: 'padding',
		selector: '.comp.compFileUpload ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Padding',
		displayName: 'Padding Inline Design Three',
		name: 'paddingInlineDesignThree',
		defaultValue: '8px 12px',
		cssProperty: 'padding',
		selector: '.comp.compFileUpload ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Padding',
		displayName: 'Padding Inline Design Four',
		name: 'paddingInlineDesignFour',
		defaultValue: '8px 12px',
		cssProperty: 'padding',
		selector: '.comp.compFileUpload ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Padding',
		displayName: 'Padding DropArea Design3',
		name: 'paddingDropAreaDesignThree',
		defaultValue: '10px',
		cssProperty: 'padding',
		selector: '.comp.compFileUpload._droparea_design3',
		noPrefix: true,
	},

	{
		groupName: 'Border Radius',
		displayName: 'Border Radius File Upload Button Inline Design One',
		name: 'borderRadiusFileUploadButtonInlineDesignOne',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design1 ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Border Radius',
		displayName: 'Border Radius File Upload Button Inline Design Two',
		name: 'borderRadiusFileUploadButtonInlineDesignTwo',
		defaultValue: '0px 2px 2px 0px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design2  ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Border Radius',
		displayName: 'Border Radius File Upload Button Inline Design Three',
		name: 'borderRadiusFileUploadButtonInlineDesignThree',
		defaultValue: '5px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design3  ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Border Radius',
		displayName: 'Border Radius File Upload Button Inline Design Four',
		name: 'borderRadiusFileUploadButtonInlineDesignFour',
		defaultValue: '100px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_design4  ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Border Radius',
		displayName: 'Border Radius File Upload Button Icon Design One',
		name: 'borderRadiusFileUploadButtonIconDesignOne',
		defaultValue: '0px 4px 4px 0px',
		cssProperty: 'border-radius',
		selector: '.comp.compFileUpload._inline_icon_design1  ._fileUploadButton',
		noPrefix: true,
	},

	{
		groupName: 'File Upload Button Border Inline Design1',
		displayName: 'File Upload Button Border Inline Design1 Border',
		name: 'fileuploadbuttonborderinlinedesign1Border',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design1 ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Button Border Inline Design2',
		displayName: 'File Upload Button Border Inline Design2 Border',
		name: 'fileuploadbuttonborderinlinedesign2Border',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design2  ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Button Border Inline Design3',
		displayName: 'File Upload Button Border Inline Design3 Border',
		name: 'fileuploadbuttonborderinlinedesign3Border',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design3  ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'File Upload Button Border Inline Design4',
		displayName: 'File Upload Button Border Inline Design4 Border',
		name: 'fileuploadbuttonborderinlinedesign4Border',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compFileUpload._inline_design4  ._fileUploadButton',
		noPrefix: true,
	},

	{
		groupName: 'Background Color Hover',
		displayName: 'Background Color Hover Upload Button Background Primary',
		name: 'backgroundColorHoverUploadButtonBackgroundPrimary',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._primary ._fileUploadButton:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color Hover',
		displayName: 'Background Color Hover Upload Button Background Secondary',
		name: 'backgroundColorHoverUploadButtonBackgroundSecondary',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._secondary ._fileUploadButton:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color Hover',
		displayName: 'Background Color Hover Upload Button Background Tertiary',
		name: 'backgroundColorHoverUploadButtonBackgroundTertiary',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._tertiary ._fileUploadButton:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color Hover',
		displayName: 'Background Color Hover Upload Button Background Quaternary',
		name: 'backgroundColorHoverUploadButtonBackgroundQuaternary',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._quaternary ._fileUploadButton:hover',
		noPrefix: true,
	},
	{
		groupName: 'Background Color Hover',
		displayName: 'Background Color Hover Upload Button Background Quinary',
		name: 'backgroundColorHoverUploadButtonBackgroundQuinary',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._quinary ._fileUploadButton:hover',
		noPrefix: true,
	},

	{
		groupName: 'Width',
		displayName: 'Width Inline Design One Button Width',
		name: 'widthInlineDesignOneButtonWidth',
		defaultValue: '50%',
		cssProperty: 'width',
		selector: '.comp.compFileUpload ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Width',
		displayName: 'Width Inline Design One Text Width',
		name: 'widthInlineDesignOneTextWidth',
		defaultValue: '50%',
		cssProperty: 'width',
		selector: '.comp.compFileUpload ._fileUploadText',
		noPrefix: true,
	},
	{
		groupName: 'Width',
		displayName: 'Width Icon Only Design One Button Width',
		name: 'widthIconOnlyDesignOneButtonWidth',
		defaultValue: '30px',
		cssProperty: 'width',
		selector: '.comp.compFileUpload._inline_icon_design1 ._fileUploadButton',
		noPrefix: true,
	},
	{
		groupName: 'Width',
		displayName: 'Width Icon Only Design One Text Width',
		name: 'widthIconOnlyDesignOneTextWidth',
		defaultValue: '1',
		cssProperty: 'flex',
		selector: '.comp.compFileUpload._inline_icon_design1 ._fileUploadText',
		noPrefix: true,
	},

	{
		groupName: 'Text Background',
		displayName: 'Text Background Inline Design One Text Background',
		name: 'textBackgroundInlineDesignOneTextBackground',
		defaultValue: 'transparent',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._inline_design1',
		noPrefix: true,
	},
	{
		groupName: 'Text Background',
		displayName: 'Text Background Inline Design Two Text Background',
		name: 'textBackgroundInlineDesignTwoTextBackground',
		defaultValue: 'transparent',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._inline_design2',
		noPrefix: true,
	},
	{
		groupName: 'Text Background',
		displayName: 'Text Background Inline Design Three Text Background',
		name: 'textBackgroundInlineDesignThreeTextBackground',
		defaultValue: '<backgroundColorNine>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._inline_design3',
		noPrefix: true,
	},
	{
		groupName: 'Text Background',
		displayName: 'Text Background Inline Design Four Text Background',
		name: 'textBackgroundInlineDesignFourTextBackground',
		defaultValue: 'transparent',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._inline_design4',
		noPrefix: true,
	},

	{
		groupName: 'Flex Direction',
		displayName: 'Flex Direction Droparea Design 1 Flex Direction',
		name: 'flexDirectionDropareaDesign1FlexDirection',
		defaultValue: 'column',
		cssProperty: 'flex-direction',
		selector: '.comp.compFileUpload._droparea_design1',
		noPrefix: true,
	},
	{
		groupName: 'Flex Direction',
		displayName: 'Flex Direction Droparea Design 2 Flex Direction',
		name: 'flexDirectionDropareaDesign2FlexDirection',
		defaultValue: 'column',
		cssProperty: 'flex-direction',
		selector: '.comp.compFileUpload._droparea_design2',
		noPrefix: true,
	},
	{
		groupName: 'Flex Direction',
		displayName: 'Flex Direction Droparea Design 3 Flex Direction',
		name: 'flexDirectionDropareaDesign3FlexDirection',
		cssProperty: 'flex-direction',
		selector: '.comp.compFileUpload._droparea_design3',
		noPrefix: true,
	},

	{
		groupName: 'Flex Alignment',
		displayName: 'Flex Alignment Droparea Design 1 Flex Alignment',
		name: 'flexAlignmentDropareaDesign1FlexAlignment',
		defaultValue: 'space-around',
		cssProperty: 'justify-content',
		selector: '.comp.compFileUpload._droparea_design1',
		noPrefix: true,
	},
	{
		groupName: 'Flex Alignment',
		displayName: 'Flex Alignment Droparea Design 2 Flex Alignment',
		name: 'flexAlignmentDropareaDesign2FlexAlignment',
		defaultValue: 'space-around',
		cssProperty: 'justify-content',
		selector: '.comp.compFileUpload._droparea_design2',
		noPrefix: true,
	},
	{
		groupName: 'Flex Alignment',
		displayName: 'Flex Alignment Droparea Design 3 Flex Alignment',
		name: 'flexAlignmentDropareaDesign3FlexAlignment',
		defaultValue: 'space-around',
		cssProperty: 'justify-content',
		selector: '.comp.compFileUpload._droparea_design3',
		noPrefix: true,
	},

	{
		groupName: 'Height',
		displayName: 'Height Droparea Design One Height',
		name: 'heightDropareaDesignOneHeight',
		defaultValue: '150px',
		cssProperty: 'height',
		selector: '.comp.compFileUpload._droparea_design1',
		noPrefix: true,
	},
	{
		groupName: 'Height',
		displayName: 'Height Droparea Design Two Height',
		name: 'heightDropareaDesignTwoHeight',
		defaultValue: '150px',
		cssProperty: 'height',
		selector: '.comp.compFileUpload._droparea_design2',
		noPrefix: true,
	},
	{
		groupName: 'Height',
		displayName: 'Height Droparea Design Three Height',
		name: 'heightDropareaDesignThreeHeight',
		defaultValue: '80px',
		cssProperty: 'height',
		selector: '.comp.compFileUpload._droparea_design3',
		noPrefix: true,
	},

	{
		groupName: 'Border Color',
		displayName: 'Primary Droparea design2 border Color',
		name: 'primaryDropareadesign2borderColor',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design2._primary',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Secondary Droparea design2 border Color',
		name: 'secondaryDropareadesign2borderColor',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design2._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Tertiary Droparea design2 border Color',
		name: 'tertiaryDropareadesign2borderColor',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design2._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Quaternary Droparea design2 border Color',
		name: 'quaternaryDropareadesign2borderColor',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design2._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Quinary Droparea design2 border Color',
		name: 'quinaryDropareadesign2borderColor',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compFileUpload._droparea_design2._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Background Color Droparea Design2',
		displayName: 'Primary Droparea design2 Background Color',
		name: 'primaryDropareadesign2BackgroundColor',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._droparea_design2._primary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color Droparea Design2',
		displayName: 'Secondary Droparea design2 Background Color',
		name: 'secondaryDropareadesign2BackgroundColor',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._droparea_design2._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color Droparea Design2',
		displayName: 'Tertiary Droparea design2 Background Color',
		name: 'tertiaryDropareadesign2BackgroundColor',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._droparea_design2._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color Droparea Design2',
		displayName: 'Quaternary Droparea design2 Background Color',
		name: 'quaternaryDropareadesign2BackgroundColor',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._droparea_design2._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Background Color Droparea Design2',
		displayName: 'Quinary Droparea design2 Background Color',
		name: 'quinaryDropareadesign2BackgroundColor',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'background',
		selector: '.comp.compFileUpload._droparea_design2._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Icon Color',
		displayName: 'Primary Droparea design Icon Color',
		name: 'primaryDropareadesignIconColor',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'color',
		selector:
			'.comp.compFileUpload._droparea_design1._primary ._uploadIcon, .comp.compFileUpload._droparea_design2._primary ._uploadIcon, .comp.compFileUpload._droparea_design3._primary ._uploadIcon',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Secondary Droparea design Icon Color',
		name: 'secondaryDropareadesignIconColor',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compFileUpload._droparea_design1._secondary ._uploadIcon, .comp.compFileUpload._droparea_design2._secondary ._uploadIcon, .comp.compFileUpload._droparea_design3._secondary ._uploadIcon',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Tertiary Droparea design Icon Color',
		name: 'tertiaryDropareadesignIconColor',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'color',
		selector:
			'.comp.compFileUpload._droparea_design1._tertiary ._uploadIcon, .comp.compFileUpload._droparea_design2._tertiary ._uploadIcon, .comp.compFileUpload._droparea_design3._tertiary ._uploadIcon',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Quaternary Droparea design Icon Color',
		name: 'quaternaryDropareadesignIconColor',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'color',
		selector:
			'.comp.compFileUpload._droparea_design1._quaternary ._uploadIcon, .comp.compFileUpload._droparea_design2._quaternary ._uploadIcon, .comp.compFileUpload._droparea_design3._quaternary ._uploadIcon',
		noPrefix: true,
	},
	{
		groupName: 'Icon Color',
		displayName: 'Quinary Droparea design Icon Color',
		name: 'quinaryDropareadesignIconColor',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'color',
		selector:
			'.comp.compFileUpload._droparea_design1._quinary ._uploadIcon, .comp.compFileUpload._droparea_design2._quinary ._uploadIcon, .comp.compFileUpload._droparea_design3._quinary ._uploadIcon',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
