import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'Column Padding',
		displayName: 'Design 1 Column Padding',
		name: 'design1ColumnPadding',
		defaultValue: '5px',
		description: 'Design 1 Column Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Column Padding',
		displayName: 'Design 2 Column Padding',
		name: 'design2ColumnPadding',
		defaultValue: '5px',
		description: 'Design 2 Column Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Column Padding',
		displayName: 'Design 3 Column Padding',
		name: 'design3ColumnPadding',
		defaultValue: '5px',
		description: 'Design 3 Column Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Column Padding',
		displayName: 'Design 4 Column Padding',
		name: 'design4ColumnPadding',
		defaultValue: '5px',
		description: 'Design 4 Column Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Column Padding',
		displayName: 'Design 5 Column Padding',
		name: 'design5ColumnPadding',
		defaultValue: '5px',
		description: 'Design 5 Column Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Column Padding',
		displayName: 'Design 6 Column Padding',
		name: 'design6ColumnPadding',
		defaultValue: '0px',
		description: 'Design 6 Column Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Column Padding',
		displayName: 'Design 7 Column Padding',
		name: 'design7ColumnPadding',
		defaultValue: '5px',
		description: 'Design 7 Column Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Column Padding',
		displayName: 'Design 8 Column Padding',
		name: 'design8ColumnPadding',
		defaultValue: '0px',
		description: 'Design 8 Column Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Column Padding',
		displayName: 'Design 9 Column Padding',
		name: 'design9ColumnPadding',
		defaultValue: '5px',
		description: 'Design 9 Column Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Column Padding',
		displayName: 'Design 10 Column Padding',
		name: 'design10ColumnPadding',
		defaultValue: '0px',
		description: 'Design 10 Column Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},

	{
		groupName: 'Column Border Bottom',
		displayName: 'Design 1 Column Border Bottom',
		name: 'design1ColumnBorderBottom',
		description: 'Design 1 Column Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design1 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom',
		displayName: 'Design 2 Column Border Bottom',
		name: 'design2ColumnBorderBottom',
		description: 'Design 2 Column Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design2 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom',
		displayName: 'Design 3 Column Border Bottom',
		name: 'design3ColumnBorderBottom',
		defaultValue: '1px solid #E5E7EB',
		description: 'Design 3 Column Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design3 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom',
		displayName: 'Design 4 Column Border Bottom',
		name: 'design4ColumnBorderBottom',
		defaultValue: '1px solid #3333330D',
		description: 'Design 4 Column Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design4 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom',
		displayName: 'Design 5 Column Border Bottom',
		name: 'design5ColumnBorderBottom',
		description: 'Design 5 Column Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design5 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom',
		displayName: 'Design 6 Column Border Bottom',
		name: 'design6ColumnBorderBottom',
		defaultValue: '1px solid #3333330D',
		description: 'Design 6 Column Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design6 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom',
		displayName: 'Design 7 Column Border Bottom',
		name: 'design7ColumnBorderBottom',
		defaultValue: '1px solid #DBDBDB',
		description: 'Design 7 Column Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design7 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom',
		displayName: 'Design 8 Column Border Bottom',
		name: 'design8ColumnBorderBottom',
		defaultValue: '1px solid #DBDBDB',
		description: 'Design 8 Column Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design8 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom',
		displayName: 'Design 9 Column Border Bottom',
		name: 'design9ColumnBorderBottom',
		description: 'Design 9 Column Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design9 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom',
		displayName: 'Design 10 Column Border Bottom',
		name: 'design10ColumnBorderBottom',
		description: 'Design 10 Column Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design10 .comp.compTableColumn',
		noPrefix: true,
	},

	{
		groupName: 'Column Border Top',
		displayName: 'Design 1 Column Border Top',
		name: 'design1ColumnBorderTop',
		description: 'Design 1 Column Border Top',
		cssProperty: 'border-top',
		selector: '.comp.compTable._design1 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 2 Column Border Top',
		name: 'design2ColumnBorderTop',
		description: 'Design 2 Column Border Top',
		cssProperty: 'border-top',
		selector: '.comp.compTable._design2 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 3 Column Border Top',
		name: 'design3ColumnBorderTop',
		description: 'Design 3 Column Border Top',
		cssProperty: 'border-top',
		selector: '.comp.compTable._design3 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 4 Column Border Top',
		name: 'design4ColumnBorderTop',
		description: 'Design 4 Column Border Top',
		cssProperty: 'border-top',
		selector: '.comp.compTable._design4 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 5 Column Border Top',
		name: 'design5ColumnBorderTop',
		description: 'Design 5 Column Border Top',
		cssProperty: 'border-top',
		selector: '.comp.compTable._design5 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 6 Column Border Top',
		name: 'design6ColumnBorderTop',
		description: 'Design 6 Column Border Top',
		cssProperty: 'border-top',
		selector: '.comp.compTable._design6 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 7 Column Border Top',
		name: 'design7ColumnBorderTop',
		description: 'Design 7 Column Border Top',
		cssProperty: 'border-top',
		selector: '.comp.compTable._design7 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 8 Column Border Top',
		name: 'design8ColumnBorderTop',
		description: 'Design 8 Column Border Top',
		cssProperty: 'border-top',
		selector: '.comp.compTable._design8 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 9 Column Border Top',
		name: 'design9ColumnBorderTop',
		description: 'Design 9 Column Border Top',
		cssProperty: 'border-top',
		selector: '.comp.compTable._design9 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 10 Column Border Top',
		name: 'design10ColumnBorderTop',
		description: 'Design 10 Column Border Top',
		cssProperty: 'border-top',
		selector: '.comp.compTable._design10 .comp.compTableColumn',
		noPrefix: true,
	},

	{
		groupName: 'Column Border Right',
		displayName: 'Design 1 Column Border Right',
		name: 'design1ColumnBorderRight',
		description: 'Design 1 Column Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design1 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Right',
		displayName: 'Design 2 Column Border Right',
		name: 'design2ColumnBorderRight',
		description: 'Design 2 Column Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design2 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Right',
		displayName: 'Design 3 Column Border Right',
		name: 'design3ColumnBorderRight',
		description: 'Design 3 Column Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design3 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Right',
		displayName: 'Design 4 Column Border Right',
		name: 'design4ColumnBorderRight',
		description: 'Design 4 Column Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design4 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Right',
		displayName: 'Design 5 Column Border Right',
		name: 'design5ColumnBorderRight',
		description: 'Design 5 Column Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design5 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Right',
		displayName: 'Design 6 Column Border Right',
		name: 'design6ColumnBorderRight',
		description: 'Design 6 Column Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design6 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Right',
		displayName: 'Design 7 Column Border Right',
		name: 'design7ColumnBorderRight',
		defaultValue:'1px solid #DBDBDB',
		description: 'Design 7 Column Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design7 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Right',
		displayName: 'Design 8 Column Border Right',
		name: 'design8ColumnBorderRight',
		defaultValue:'1px solid #DBDBDB',
		description: 'Design 8 Column Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design8 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Right',
		displayName: 'Design 9 Column Border Right',
		name: 'design9ColumnBorderRight',
		description: 'Design 9 Column Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design9 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Right',
		displayName: 'Design 10 Column Border Right',
		name: 'design10ColumnBorderRight',
		description: 'Design 10 Column Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design10 .comp.compTableColumn',
		noPrefix: true,
	},

	{
		groupName: 'Column Border Top',
		displayName: 'Design 1 Column Border Left',
		name: 'design1ColumnBorderLeft',
		description: 'Design 1 Column Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design1 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 2 Column Border Left',
		name: 'design2ColumnBorderLeft',
		description: 'Design 2 Column Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design2 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 3 Column Border Left',
		name: 'design3ColumnBorderLeft',
		description: 'Design 3 Column Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design3 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 4 Column Border Left',
		name: 'design4ColumnBorderLeft',
		description: 'Design 4 Column Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design4 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 5 Column Border Left',
		name: 'design5ColumnBorderLeft',
		description: 'Design 5 Column Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design5 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 6 Column Border Left',
		name: 'design6ColumnBorderLeft',
		description: 'Design 6 Column Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design6 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 7 Column Border Left',
		name: 'design7ColumnBorderLeft',
		description: 'Design 7 Column Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design7 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 8 Column Border Left',
		name: 'design8ColumnBorderLeft',
		description: 'Design 8 Column Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design8 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 9 Column Border Left',
		name: 'design9ColumnBorderLeft',
		description: 'Design 9 Column Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design9 .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Top',
		displayName: 'Design 10 Column Border Left',
		name: 'design10ColumnBorderLeft',
		description: 'Design 10 Column Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design10 .comp.compTableColumn',
		noPrefix: true,
	},
	

];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
