import { StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{ displayName: 'Text Area Font', name: 'textAreaFont', defaultValue: '<primaryFont>' },

	{
		groupName: 'Text Area Font',
		displayName: 'Text Area Font Design Default',
		name: 'textAreaFontDesignDefault',
		defaultValue: '<textAreaFont>',
		cssProperty: 'font',
		selector: '.comp.compTextArea._default',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Font',
		displayName: 'Text Area Font Design Filled',
		name: 'textAreaFontDesignFilled',
		defaultValue: '<textAreaFont>',
		cssProperty: 'font',
		selector: '.comp.compTextArea._filled',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Placeholder Color',
		displayName: 'Primary Text Area Placeholder Color Design Default',
		name: 'primaryTextAreaPlaceholderColorDesignDefault',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._primary input::placeholder',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Placeholder Color',
		displayName: 'Secondary Text Area Placeholder Color Design Default',
		name: 'secondaryTextAreaPlaceholderColorDesignDefault',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._secondary input::placeholder',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Placeholder Color',
		displayName: 'Tertiary Text Area Placeholder Color Design Default',
		name: 'tertiaryTextAreaPlaceholderColorDesignDefault',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._tertiary input::placeholder',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Placeholder Color',
		displayName: 'Quaternary Text Area Placeholder Color Design Default',
		name: 'quaternaryTextAreaPlaceholderColorDesignDefault',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._quaternary input::placeholder',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Placeholder Color',
		displayName: 'Quinary Text Area Placeholder Color Design Default',
		name: 'quinaryTextAreaPlaceholderColorDesignDefault',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._quinary input::placeholder',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Placeholder Color',
		displayName: 'Primary Text Area Placeholder Color Design Filled',
		name: 'primaryTextAreaPlaceholderColorDesignFilled',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._primary input::placeholder',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Placeholder Color',
		displayName: 'Secondary Text Area Placeholder Color Design Filled',
		name: 'secondaryTextAreaPlaceholderColorDesignFilled',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._secondary input::placeholder',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Placeholder Color',
		displayName: 'Tertiary Text Area Placeholder Color Design Filled',
		name: 'tertiaryTextAreaPlaceholderColorDesignFilled',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._tertiary input::placeholder',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Placeholder Color',
		displayName: 'Quaternary Text Area Placeholder Color Design Filled',
		name: 'quaternaryTextAreaPlaceholderColorDesignFilled',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._quaternary input::placeholder',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Placeholder Color',
		displayName: 'Quinary Text Area Placeholder Color Design Filled',
		name: 'quinaryTextAreaPlaceholderColorDesignFilled',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._quinary input::placeholder',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Color',
		displayName: 'Primary Text Area Color Design Default',
		name: 'primaryTextAreaColorDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._primary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Color',
		displayName: 'Secondary Text Area Color Design Default',
		name: 'secondaryTextAreaColorDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Color',
		displayName: 'Tertiary Text Area Color Design Default',
		name: 'tertiaryTextAreaColorDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Color',
		displayName: 'Quaternary Text Area Color Design Default',
		name: 'quaternaryTextAreaColorDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Color',
		displayName: 'Quinary Text Area Color Design Default',
		name: 'quinaryTextAreaColorDesignDefault',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Color',
		displayName: 'Primary Text Area Color Design Filled',
		name: 'primaryTextAreaColorDesignFilled',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._primary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Color',
		displayName: 'Secondary Text Area Color Design Filled',
		name: 'secondaryTextAreaColorDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Color',
		displayName: 'Tertiary Text Area Color Design Filled',
		name: 'tertiaryTextAreaColorDesignFilled',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Color',
		displayName: 'Quaternary Text Area Color Design Filled',
		name: 'quaternaryTextAreaColorDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Color',
		displayName: 'Quinary Text Area Color Design Filled',
		name: 'quinaryTextAreaColorDesignFilled',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Height',
		displayName: 'Text Area Height Design Default',
		name: 'textAreaHeightDesignDefault',
		cssProperty: 'height',
		selector: '.comp.compTextArea._default',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Height',
		displayName: 'Text Area Height Design Filled',
		name: 'textAreaHeightDesignFilled',
		cssProperty: 'height',
		selector: '.comp.compTextArea._filled',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Padding',
		displayName: 'Text Area Padding Design Default',
		name: 'textAreaPaddingDesignDefault',
		defaultValue: '0px 5px',
		cssProperty: 'padding',
		selector: '.comp.compTextArea._default',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Padding',
		displayName: 'Text Area Padding Design Filled',
		name: 'textAreaPaddingDesignFilled',
		defaultValue: '0px 5px',
		cssProperty: 'padding',
		selector: '.comp.compTextArea._filled',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Border Radius',
		displayName: 'Text Area Border Radius Design Default',
		name: 'textAreaBorderRadiusDesignDefault',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compTextArea._default',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Radius',
		displayName: 'Text Area Border Radius Design Filled',
		name: 'textAreaBorderRadiusDesignFilled',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compTextArea._filled',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Border Default',
		displayName: 'Text Area Border Default Design Default',
		name: 'textAreaBorderDefaultDesignDefault',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compTextArea._default',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Default',
		displayName: 'Text Area Border Default Design Filled',
		name: 'textAreaBorderDefaultDesignFilled',
		cssProperty: 'border',
		selector: '.comp.compTextArea._filled',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Border Active',
		displayName: 'Text Area Border Active Design Default',
		name: 'textAreaBorderActiveDesignDefault',
		defaultValue: '2px solid',
		cssProperty: 'border',
		selector: '.comp.compTextArea._default._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Active',
		displayName: 'Text Area Border Active Design Filled',
		name: 'textAreaBorderActiveDesignFilled',
		cssProperty: 'border',
		selector: '.comp.compTextArea._filled._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Border Color Default',
		displayName: 'Primary Text Area Border Color Default Design Default',
		name: 'primaryTextAreaBorderColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._default._primary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Default',
		displayName: 'Secondary Text Area Border Color Default Design Default',
		name: 'secondaryTextAreaBorderColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._default._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Default',
		displayName: 'Tertiary Text Area Border Color Default Design Default',
		name: 'tertiaryTextAreaBorderColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._default._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Default',
		displayName: 'Quaternary Text Area Border Color Default Design Default',
		name: 'quaternaryTextAreaBorderColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._default._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Default',
		displayName: 'Quinary Text Area Border Color Default Design Default',
		name: 'quinaryTextAreaBorderColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._default._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Border Color Default',
		displayName: 'Primary Text Area Border Color Default Design Filled',
		name: 'primaryTextAreaBorderColorDefaultDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._filled._primary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Default',
		displayName: 'Secondary Text Area Border Color Default Design Filled',
		name: 'secondaryTextAreaBorderColorDefaultDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._filled._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Default',
		displayName: 'Tertiary Text Area Border Color Default Design Filled',
		name: 'tertiaryTextAreaBorderColorDefaultDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._filled._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Default',
		displayName: 'Quaternary Text Area Border Color Default Design Filled',
		name: 'quaternaryTextAreaBorderColorDefaultDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._filled._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Default',
		displayName: 'Quinary Text Area Border Color Default Design Filled',
		name: 'quinaryTextAreaBorderColorDefaultDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._filled._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Border Color Active',
		displayName: 'Primary Text Area Border Color Active Design Default',
		name: 'primaryTextAreaBorderColorActiveDesignDefault',
		defaultValue: '<fontColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._default._isActive._primary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Active',
		displayName: 'Secondary Text Area Border Color Active Design Default',
		name: 'secondaryTextAreaBorderColorActiveDesignDefault',
		defaultValue: '<fontColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._default._isActive._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Active',
		displayName: 'Tertiary Text Area Border Color Active Design Default',
		name: 'tertiaryTextAreaBorderColorActiveDesignDefault',
		defaultValue: '<fontColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._default._isActive._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Active',
		displayName: 'Quaternary Text Area Border Color Active Design Default',
		name: 'quaternaryTextAreaBorderColorActiveDesignDefault',
		defaultValue: '<fontColorNine>',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._default._isActive._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Active',
		displayName: 'Quinary Text Area Border Color Active Design Default',
		name: 'quinaryTextAreaBorderColorActiveDesignDefault',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._default._isActive._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Border Color Active',
		displayName: 'Primary Text Area Border Color Active Design Filled',
		name: 'primaryTextAreaBorderColorActiveDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._filled._isActive._primary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Active',
		displayName: 'Secondary Text Area Border Color Active Design Filled',
		name: 'secondaryTextAreaBorderColorActiveDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._filled._isActive._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Active',
		displayName: 'Tertiary Text Area Border Color Active Design Filled',
		name: 'tertiaryTextAreaBorderColorActiveDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._filled._isActive._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Active',
		displayName: 'Quaternary Text Area Border Color Active Design Filled',
		name: 'quaternaryTextAreaBorderColorActiveDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._filled._isActive._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Border Color Active',
		displayName: 'Quinary Text Area Border Color Active Design Filled',
		name: 'quinaryTextAreaBorderColorActiveDesignFilled',
		cssProperty: 'border-color',
		selector: '.comp.compTextArea._filled._isActive._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Background Default',
		displayName: 'Primary Text Area Background Default Design Default',
		name: 'primaryTextAreaBackgroundDefaultDesignDefault',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compTextArea._default._primary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Default',
		displayName: 'Secondary Text Area Background Default Design Default',
		name: 'secondaryTextAreaBackgroundDefaultDesignDefault',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compTextArea._default._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Default',
		displayName: 'Tertiary Text Area Background Default Design Default',
		name: 'tertiaryTextAreaBackgroundDefaultDesignDefault',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compTextArea._default._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Default',
		displayName: 'Quaternary Text Area Background Default Design Default',
		name: 'quaternaryTextAreaBackgroundDefaultDesignDefault',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compTextArea._default._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Default',
		displayName: 'Quinary Text Area Background Default Design Default',
		name: 'quinaryTextAreaBackgroundDefaultDesignDefault',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compTextArea._default._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Background Default',
		displayName: 'Primary Text Area Background Default Design Filled',
		name: 'primaryTextAreaBackgroundDefaultDesignFilled',
		defaultValue: '<backgroundColorNine>',
		cssProperty: 'background',
		selector: '.comp.compTextArea._filled._primary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Default',
		displayName: 'Secondary Text Area Background Default Design Filled',
		name: 'secondaryTextAreaBackgroundDefaultDesignFilled',
		defaultValue: '<backgroundColorNine>',
		cssProperty: 'background',
		selector: '.comp.compTextArea._filled._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Default',
		displayName: 'Tertiary Text Area Background Default Design Filled',
		name: 'tertiaryTextAreaBackgroundDefaultDesignFilled',
		defaultValue: '<backgroundColorNine>',
		cssProperty: 'background',
		selector: '.comp.compTextArea._filled._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Default',
		displayName: 'Quaternary Text Area Background Default Design Filled',
		name: 'quaternaryTextAreaBackgroundDefaultDesignFilled',
		defaultValue: '<backgroundColorNine>',
		cssProperty: 'background',
		selector: '.comp.compTextArea._filled._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Default',
		displayName: 'Quinary Text Area Background Default Design Filled',
		name: 'quinaryTextAreaBackgroundDefaultDesignFilled',
		defaultValue: '<backgroundColorNine>',
		cssProperty: 'background',
		selector: '.comp.compTextArea._filled._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Background Active',
		displayName: 'Primary Text Area Background Active Design Default',
		name: 'primaryTextAreaBackgroundActiveDesignDefault',
		cssProperty: 'background',
		selector: '.comp.compTextArea._default._isActive._primary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Active',
		displayName: 'Secondary Text Area Background Active Design Default',
		name: 'secondaryTextAreaBackgroundActiveDesignDefault',
		cssProperty: 'background',
		selector: '.comp.compTextArea._default._isActive._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Active',
		displayName: 'Tertiary Text Area Background Active Design Default',
		name: 'tertiaryTextAreaBackgroundActiveDesignDefault',
		cssProperty: 'background',
		selector: '.comp.compTextArea._default._isActive._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Active',
		displayName: 'Quaternary Text Area Background Active Design Default',
		name: 'quaternaryTextAreaBackgroundActiveDesignDefault',
		cssProperty: 'background',
		selector: '.comp.compTextArea._default._isActive._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Active',
		displayName: 'Quinary Text Area Background Active Design Default',
		name: 'quinaryTextAreaBackgroundActiveDesignDefault',
		cssProperty: 'background',
		selector: '.comp.compTextArea._default._isActive._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Background Active',
		displayName: 'Primary Text Area Background Active Design Filled',
		name: 'primaryTextAreaBackgroundActiveDesignFilled',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compTextArea._filled._isActive._primary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Active',
		displayName: 'Secondary Text Area Background Active Design Filled',
		name: 'secondaryTextAreaBackgroundActiveDesignFilled',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compTextArea._filled._isActive._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Active',
		displayName: 'Tertiary Text Area Background Active Design Filled',
		name: 'tertiaryTextAreaBackgroundActiveDesignFilled',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compTextArea._filled._isActive._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Active',
		displayName: 'Quaternary Text Area Background Active Design Filled',
		name: 'quaternaryTextAreaBackgroundActiveDesignFilled',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compTextArea._filled._isActive._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Background Active',
		displayName: 'Quinary Text Area Background Active Design Filled',
		name: 'quinaryTextAreaBackgroundActiveDesignFilled',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compTextArea._filled._isActive._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Label Font',
		displayName: 'Text Area Label Font Design Default',
		name: 'textAreaLabelFontDesignDefault',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compTextArea._default ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Font',
		displayName: 'Text Area Label Font Design Filled',
		name: 'textAreaLabelFontDesignFilled',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compTextArea._filled ._label',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Label Color Default',
		displayName: 'Primary Text Area Label Color Default Design Default',
		name: 'primaryTextAreaLabelColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._primary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Default',
		displayName: 'Secondary Text Area Label Color Default Design Default',
		name: 'secondaryTextAreaLabelColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._secondary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Default',
		displayName: 'Tertiary Text Area Label Color Default Design Default',
		name: 'tertiaryTextAreaLabelColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._tertiary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Default',
		displayName: 'Quaternary Text Area Label Color Default Design Default',
		name: 'quaternaryTextAreaLabelColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._quaternary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Default',
		displayName: 'Quinary Text Area Label Color Default Design Default',
		name: 'quinaryTextAreaLabelColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._quinary ._label',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Label Color Default',
		displayName: 'Primary Text Area Label Color Default Design Filled',
		name: 'primaryTextAreaLabelColorDefaultDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._primary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Default',
		displayName: 'Secondary Text Area Label Color Default Design Filled',
		name: 'secondaryTextAreaLabelColorDefaultDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._secondary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Default',
		displayName: 'Tertiary Text Area Label Color Default Design Filled',
		name: 'tertiaryTextAreaLabelColorDefaultDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._tertiary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Default',
		displayName: 'Quaternary Text Area Label Color Default Design Filled',
		name: 'quaternaryTextAreaLabelColorDefaultDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._quaternary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Default',
		displayName: 'Quinary Text Area Label Color Default Design Filled',
		name: 'quinaryTextAreaLabelColorDefaultDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._quinary ._label',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Label Color Active',
		displayName: 'Primary Text Area Label Color Active Design Default',
		name: 'primaryTextAreaLabelColorActiveDesignDefault',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._primary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Active',
		displayName: 'Secondary Text Area Label Color Active Design Default',
		name: 'secondaryTextAreaLabelColorActiveDesignDefault',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._secondary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Active',
		displayName: 'Tertiary Text Area Label Color Active Design Default',
		name: 'tertiaryTextAreaLabelColorActiveDesignDefault',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._tertiary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Active',
		displayName: 'Quaternary Text Area Label Color Active Design Default',
		name: 'quaternaryTextAreaLabelColorActiveDesignDefault',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._quaternary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Active',
		displayName: 'Quinary Text Area Label Color Active Design Default',
		name: 'quinaryTextAreaLabelColorActiveDesignDefault',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._quinary ._label',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Label Color Active',
		displayName: 'Primary Text Area Label Color Active Design Filled',
		name: 'primaryTextAreaLabelColorActiveDesignFilled',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._primary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Active',
		displayName: 'Secondary Text Area Label Color Active Design Filled',
		name: 'secondaryTextAreaLabelColorActiveDesignFilled',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._secondary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Active',
		displayName: 'Tertiary Text Area Label Color Active Design Filled',
		name: 'tertiaryTextAreaLabelColorActiveDesignFilled',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._tertiary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Active',
		displayName: 'Quaternary Text Area Label Color Active Design Filled',
		name: 'quaternaryTextAreaLabelColorActiveDesignFilled',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._quaternary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Label Color Active',
		displayName: 'Quinary Text Area Label Color Active Design Filled',
		name: 'quinaryTextAreaLabelColorActiveDesignFilled',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._quinary ._label',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Support Text Font',
		displayName: 'Text Area Support Text Font Design Default',
		name: 'textAreaSupportTextFontDesignDefault',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compTextArea._default ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Font',
		displayName: 'Text Area Support Text Font Design Filled',
		name: 'textAreaSupportTextFontDesignFilled',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compTextArea._filled ._supportText',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Support Text Color Default',
		displayName: 'Primary Text Area Support Text Color Default Design Default',
		name: 'primaryTextAreaSupportTextColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._primary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Default',
		displayName: 'Secondary Text Area Support Text Color Default Design Default',
		name: 'secondaryTextAreaSupportTextColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._secondary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Default',
		displayName: 'Tertiary Text Area Support Text Color Default Design Default',
		name: 'tertiaryTextAreaSupportTextColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._tertiary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Default',
		displayName: 'Quaternary Text Area Support Text Color Default Design Default',
		name: 'quaternaryTextAreaSupportTextColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._quaternary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Default',
		displayName: 'Quinary Text Area Support Text Color Default Design Default',
		name: 'quinaryTextAreaSupportTextColorDefaultDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._quinary ._supportText',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Support Text Color Default',
		displayName: 'Primary Text Area Support Text Color Default Design Filled',
		name: 'primaryTextAreaSupportTextColorDefaultDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._primary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Default',
		displayName: 'Secondary Text Area Support Text Color Default Design Filled',
		name: 'secondaryTextAreaSupportTextColorDefaultDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._secondary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Default',
		displayName: 'Tertiary Text Area Support Text Color Default Design Filled',
		name: 'tertiaryTextAreaSupportTextColorDefaultDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._tertiary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Default',
		displayName: 'Quaternary Text Area Support Text Color Default Design Filled',
		name: 'quaternaryTextAreaSupportTextColorDefaultDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._quaternary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Default',
		displayName: 'Quinary Text Area Support Text Color Default Design Filled',
		name: 'quinaryTextAreaSupportTextColorDefaultDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._quinary ._supportText',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Support Text Color Active',
		displayName: 'Primary Text Area Support Text Color Active Design Default',
		name: 'primaryTextAreaSupportTextColorActiveDesignDefault',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._primary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Active',
		displayName: 'Secondary Text Area Support Text Color Active Design Default',
		name: 'secondaryTextAreaSupportTextColorActiveDesignDefault',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._secondary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Active',
		displayName: 'Tertiary Text Area Support Text Color Active Design Default',
		name: 'tertiaryTextAreaSupportTextColorActiveDesignDefault',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._tertiary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Active',
		displayName: 'Quaternary Text Area Support Text Color Active Design Default',
		name: 'quaternaryTextAreaSupportTextColorActiveDesignDefault',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._quaternary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Active',
		displayName: 'Quinary Text Area Support Text Color Active Design Default',
		name: 'quinaryTextAreaSupportTextColorActiveDesignDefault',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._quinary ._supportText',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Support Text Color Active',
		displayName: 'Primary Text Area Support Text Color Active Design Filled',
		name: 'primaryTextAreaSupportTextColorActiveDesignFilled',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._primary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Active',
		displayName: 'Secondary Text Area Support Text Color Active Design Filled',
		name: 'secondaryTextAreaSupportTextColorActiveDesignFilled',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._secondary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Active',
		displayName: 'Tertiary Text Area Support Text Color Active Design Filled',
		name: 'tertiaryTextAreaSupportTextColorActiveDesignFilled',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._tertiary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Active',
		displayName: 'Quaternary Text Area Support Text Color Active Design Filled',
		name: 'quaternaryTextAreaSupportTextColorActiveDesignFilled',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._quaternary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Support Text Color Active',
		displayName: 'Quinary Text Area Support Text Color Active Design Filled',
		name: 'quinaryTextAreaSupportTextColorActiveDesignFilled',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._quinary ._supportText',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Left Icon Padding',
		displayName: 'Text Area Left Icon Padding Design Default',
		name: 'textAreaLeftIconPaddingDesignDefault',
		defaultValue: '0px 8px',
		cssProperty: 'padding',
		selector: '.comp.compTextArea._default ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Padding',
		displayName: 'Text Area Left Icon Padding Design Filled',
		name: 'textAreaLeftIconPaddingDesignFilled',
		defaultValue: '0px 8px',
		cssProperty: 'padding',
		selector: '.comp.compTextArea._filled ._leftIcon',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Rigth Icon Padding',
		displayName: 'Text Area Rigth Icon Padding Design Default',
		name: 'textAreaRigthIconPaddingDesignDefault',
		defaultValue: '0px 8px',
		cssProperty: 'padding',
		selector: '.comp.compTextArea._default ._rightIcon ',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Rigth Icon Padding',
		displayName: 'Text Area Rigth Icon Padding Design Filled',
		name: 'textAreaRigthIconPaddingDesignFilled',
		defaultValue: '0px 8px',
		cssProperty: 'padding',
		selector: '.comp.compTextArea._filled ._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Left Icon Color Default',
		displayName: 'Primary Text Area Left Icon Color Default Design Default',
		name: 'primaryTextAreaLeftIconColorDefaultDesignDefault',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._primary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Default',
		displayName: 'Secondary Text Area Left Icon Color Default Design Default',
		name: 'secondaryTextAreaLeftIconColorDefaultDesignDefault',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._secondary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Default',
		displayName: 'Tertiary Text Area Left Icon Color Default Design Default',
		name: 'tertiaryTextAreaLeftIconColorDefaultDesignDefault',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._tertiary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Default',
		displayName: 'Quaternary Text Area Left Icon Color Default Design Default',
		name: 'quaternaryTextAreaLeftIconColorDefaultDesignDefault',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._quaternary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Default',
		displayName: 'Quinary Text Area Left Icon Color Default Design Default',
		name: 'quinaryTextAreaLeftIconColorDefaultDesignDefault',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._quinary ._leftIcon',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Left Icon Color Default',
		displayName: 'Primary Text Area Left Icon Color Default Design Filled',
		name: 'primaryTextAreaLeftIconColorDefaultDesignFilled',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._primary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Default',
		displayName: 'Secondary Text Area Left Icon Color Default Design Filled',
		name: 'secondaryTextAreaLeftIconColorDefaultDesignFilled',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._secondary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Default',
		displayName: 'Tertiary Text Area Left Icon Color Default Design Filled',
		name: 'tertiaryTextAreaLeftIconColorDefaultDesignFilled',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._tertiary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Default',
		displayName: 'Quaternary Text Area Left Icon Color Default Design Filled',
		name: 'quaternaryTextAreaLeftIconColorDefaultDesignFilled',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._quaternary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Default',
		displayName: 'Quinary Text Area Left Icon Color Default Design Filled',
		name: 'quinaryTextAreaLeftIconColorDefaultDesignFilled',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._quinary ._leftIcon',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Left Icon Color Active',
		displayName: 'Primary Text Area Left Icon Color Active Design Default',
		name: 'primaryTextAreaLeftIconColorActiveDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._primary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Active',
		displayName: 'Secondary Text Area Left Icon Color Active Design Default',
		name: 'secondaryTextAreaLeftIconColorActiveDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._secondary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Active',
		displayName: 'Tertiary Text Area Left Icon Color Active Design Default',
		name: 'tertiaryTextAreaLeftIconColorActiveDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._tertiary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Active',
		displayName: 'Quaternary Text Area Left Icon Color Active Design Default',
		name: 'quaternaryTextAreaLeftIconColorActiveDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._quaternary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Active',
		displayName: 'Quinary Text Area Left Icon Color Active Design Default',
		name: 'quinaryTextAreaLeftIconColorActiveDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._quinary ._leftIcon',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Left Icon Color Active',
		displayName: 'Primary Text Area Left Icon Color Active Design Filled',
		name: 'primaryTextAreaLeftIconColorActiveDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._primary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Active',
		displayName: 'Secondary Text Area Left Icon Color Active Design Filled',
		name: 'secondaryTextAreaLeftIconColorActiveDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._secondary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Active',
		displayName: 'Tertiary Text Area Left Icon Color Active Design Filled',
		name: 'tertiaryTextAreaLeftIconColorActiveDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._tertiary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Active',
		displayName: 'Quaternary Text Area Left Icon Color Active Design Filled',
		name: 'quaternaryTextAreaLeftIconColorActiveDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._quaternary ._leftIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Left Icon Color Active',
		displayName: 'Quinary Text Area Left Icon Color Active Design Filled',
		name: 'quinaryTextAreaLeftIconColorActiveDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._quinary ._leftIcon',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Right Icon Color Default',
		displayName: 'Primary Text Area Right Icon Color Default Design Default',
		name: 'primaryTextAreaRightIconColorDefaultDesignDefault',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._primary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Default',
		displayName: 'Secondary Text Area Right Icon Color Default Design Default',
		name: 'secondaryTextAreaRightIconColorDefaultDesignDefault',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._secondary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Default',
		displayName: 'Tertiary Text Area Right Icon Color Default Design Default',
		name: 'tertiaryTextAreaRightIconColorDefaultDesignDefault',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._tertiary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Default',
		displayName: 'Quaternary Text Area Right Icon Color Default Design Default',
		name: 'quaternaryTextAreaRightIconColorDefaultDesignDefault',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._quaternary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Default',
		displayName: 'Quinary Text Area Right Icon Color Default Design Default',
		name: 'quinaryTextAreaRightIconColorDefaultDesignDefault',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._quinary ._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Right Icon Color Default',
		displayName: 'Primary Text Area Right Icon Color Default Design Filled',
		name: 'primaryTextAreaRightIconColorDefaultDesignFilled',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._primary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Default',
		displayName: 'Secondary Text Area Right Icon Color Default Design Filled',
		name: 'secondaryTextAreaRightIconColorDefaultDesignFilled',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._secondary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Default',
		displayName: 'Tertiary Text Area Right Icon Color Default Design Filled',
		name: 'tertiaryTextAreaRightIconColorDefaultDesignFilled',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._tertiary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Default',
		displayName: 'Quaternary Text Area Right Icon Color Default Design Filled',
		name: 'quaternaryTextAreaRightIconColorDefaultDesignFilled',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._quaternary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Default',
		displayName: 'Quinary Text Area Right Icon Color Default Design Filled',
		name: 'quinaryTextAreaRightIconColorDefaultDesignFilled',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._quinary ._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Right Icon Color Active',
		displayName: 'Primary Text Area Right Icon Color Active Design Default',
		name: 'primaryTextAreaRightIconColorActiveDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._primary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Active',
		displayName: 'Secondary Text Area Right Icon Color Active Design Default',
		name: 'secondaryTextAreaRightIconColorActiveDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._secondary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Active',
		displayName: 'Tertiary Text Area Right Icon Color Active Design Default',
		name: 'tertiaryTextAreaRightIconColorActiveDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._tertiary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Active',
		displayName: 'Quaternary Text Area Right Icon Color Active Design Default',
		name: 'quaternaryTextAreaRightIconColorActiveDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._quaternary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Active',
		displayName: 'Quinary Text Area Right Icon Color Active Design Default',
		name: 'quinaryTextAreaRightIconColorActiveDesignDefault',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._default._isActive._quinary ._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Right Icon Color Active',
		displayName: 'Primary Text Area Right Icon Color Active Design Filled',
		name: 'primaryTextAreaRightIconColorActiveDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._primary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Active',
		displayName: 'Secondary Text Area Right Icon Color Active Design Filled',
		name: 'secondaryTextAreaRightIconColorActiveDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._secondary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Active',
		displayName: 'Tertiary Text Area Right Icon Color Active Design Filled',
		name: 'tertiaryTextAreaRightIconColorActiveDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._tertiary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Active',
		displayName: 'Quaternary Text Area Right Icon Color Active Design Filled',
		name: 'quaternaryTextAreaRightIconColorActiveDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._quaternary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Right Icon Color Active',
		displayName: 'Quinary Text Area Right Icon Color Active Design Filled',
		name: 'quinaryTextAreaRightIconColorActiveDesignFilled',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compTextArea._filled._isActive._quinary ._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Success Icon Color',
		displayName: 'Text Area Success Icon Color Design Default',
		name: 'textAreaSuccessIconColorDesignDefault',
		defaultValue: '<successColor>',
		cssProperty: 'color',
		selector:
			'.comp.compTextArea._default ._successIcon._rightIcon, .comp.compTextArea._default._isActive ._successIcon._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Success Icon Color',
		displayName: 'Text Area Success Icon Color Design Filled',
		name: 'textAreaSuccessIconColorDesignFilled',
		defaultValue: '<successColor>',
		cssProperty: 'color',
		selector:
			'.comp.compTextArea._filled ._successIcon._rightIcon, .comp.compTextArea._filled._isActive ._successIcon._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Error Icon Color',
		displayName: 'Text Area Error Icon Color Design Default',
		name: 'textAreaErrorIconColorDesignDefault',
		defaultValue: '<errorColor>',
		cssProperty: 'color',
		selector:
			'.comp.compTextArea._default ._errorIcon._rightIcon, .comp.compTextArea._default._isActive ._errorIcon._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Error Icon Color',
		displayName: 'Text Area Error Icon Color Design Filled',
		name: 'textAreaErrorIconColorDesignFilled',
		defaultValue: '<errorColor>',
		cssProperty: 'color',
		selector:
			'.comp.compTextArea._filled ._errorIcon._rightIcon, .comp.compTextArea._filled._isActive ._errorIcon._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Error Border Color',
		displayName: 'Text Area Error Border Color Design Default',
		name: 'textAreaErrorBorderColorDesignDefault',
		defaultValue: '<errorColor>',
		cssProperty: 'border-color',
		selector:
			'.comp.compTextArea._default._hasError, .comp.compTextArea._default._isActive._hasError',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Error Border Color',
		displayName: 'Text Area Error Border Color Design Filled',
		name: 'textAreaErrorBorderColorDesignFilled',
		cssProperty: 'border-color',
		selector:
			'.comp.compTextArea._filled._hasError, .comp.compTextArea._filled._isActive._hasError',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Error Background',
		displayName: 'Text Area Error Background Design Default',
		name: 'textAreaErrorBackgroundDesignDefault',
		cssProperty: 'background',
		selector:
			'.comp.compTextArea._default._hasError, .comp.compTextArea._default._isActive._hasError',
		noPrefix: true,
	},
	{
		groupName: 'Text Area Error Background',
		displayName: 'Text Area Error Background Design Filled',
		name: 'textAreaErrorBackgroundDesignFilled',
		defaultValue: '<errorColor>',
		cssProperty: 'background',
		selector:
			'.comp.compTextArea._filled._hasError, .comp.compTextArea._filled._isActive._hasError',
		noPrefix: true,
	},

	{
		groupName: 'Text Area Error Color',
		displayName: 'Text Area Error Color Design Filled',
		name: 'textAreaErrorColorDesignFilled',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compTextArea._filled._hasError, .comp.compTextArea._filled._hasError ._leftIcon, .comp.compTextArea._filled._hasError ._rightIcon, .comp.compTextArea._filled._isActive._hasError, .comp.compTextArea._filled._isActive._hasError ._leftIcon, .comp.compTextArea._filled._isActive._hasError ._rightIcon',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
