import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{ displayName: 'Dropdown Font', name: 'dropdownFont', defaultValue: '<primaryFont>' },

	{
		groupName: 'Default',
		displayName: 'Default Dropdown Font',
		name: 'defaultDropdownFont',
		defaultValue: '<dropdownFont>',
		cssProperty: 'font',
		selector: '.comp.compDropdown._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Font',
		name: 'outlineDropdownFont',
		defaultValue: '<dropdownFont>',
		cssProperty: 'font',
		selector: '.comp.compDropdown._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Font',
		name: 'filledDropdownFont',
		defaultValue: '<dropdownFont>',
		cssProperty: 'font',
		selector: '.comp.compDropdown._filled',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Font',
		name: 'bigdesign1DropdownFont',
		defaultValue: '<dropdownFont>',
		cssProperty: 'font',
		selector: '.comp.compDropdown._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Dropdown Font Color',
		name: 'defaultDropdownFontColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compDropdown._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Font Color',
		name: 'outlineDropdownFontColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compDropdown._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Font Color',
		name: 'filledDropdownFontColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compDropdown._filled',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Font Color',
		name: 'bigdesign1DropdownFontColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector: '.comp.compDropdown._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Dropdown Label Font',
		name: 'defaultDropdownLabelFont',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compDropdown._default ._label',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Label Font',
		name: 'outlineDropdownLabelFont',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compDropdown._outlined ._label',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Label Font',
		name: 'filledDropdownLabelFont',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compDropdown._filled ._label',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Label Font',
		name: 'bigdesign1DropdownLabelFont',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compDropdown._bigDesign1 ._label',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Dropdown Label Color',
		name: 'defaultDropdownLabelColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compDropdown._default ._label',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Label Color',
		name: 'outlineDropdownLabelColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compDropdown._outlined ._label',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Label Color',
		name: 'filledDropdownLabelColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compDropdown._filled ._label',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Label Color',
		name: 'bigdesign1DropdownLabelColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compDropdown._bigDesign1 ._label',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Text  Box Height',
		name: 'defaultDropdownHeight',
		defaultValue: '32px',
		cssProperty: 'height',
		selector: '.comp.compDropdown._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Height',
		name: 'outlineDropdownHeight',
		defaultValue: '32px',
		cssProperty: 'height',
		selector: '.comp.compDropdown._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Height',
		name: 'filledDropdownHeight',
		defaultValue: '32px',
		cssProperty: 'height',
		selector: '.comp.compDropdown._filled',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Height',
		name: 'bigDesign1DropdownHeight',
		defaultValue: '60px',
		cssProperty: 'height',
		selector: '.comp.compDropdown._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Dropdown Border Radius',
		name: 'defaultDropdownBorderRadius',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compDropdown._default, .comp.compDropdown._default ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Border Radius',
		name: 'outlineDropdownBorderRadius',
		defaultValue: '16px',
		cssProperty: 'border-radius',
		selector: '.comp.compDropdown._outlined, .comp.compDropdown._outlined._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Border Radius',
		name: 'filledDropdownBorderRadius',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compDropdown._filled, .comp.compDropdown._filled ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Border Radius',
		name: 'bigdesign1DropdownBorderRadius',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector:
			'.comp.compDropdown._bigDesign1, .comp.compDropdown._bigDesign1 ._dropdownContainer',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Dropdown Border',
		name: 'defaultDropdownBorder',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compDropdown._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Border',
		name: 'outlineDropdownBorder',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compDropdown._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Border',
		name: 'filledDropdownBorder',
		cssProperty: 'border',
		selector: '.comp.compDropdown._filled',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Border',
		name: 'bigdesign1DropdownBorder',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compDropdown._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Dropdown Border Color',
		name: 'defaultDropdownBorderColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compDropdown._default, .comp.compDropdown._default ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Border Color',
		name: 'outlineDropdownBorderColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compDropdown._outlined, .comp.compDropdown._outlined._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Border Color',
		name: 'filledDropdownBorderColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector: '.comp.compDropdown._filled, .comp.compDropdown._filled ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Border Color',
		name: 'bigdesign1DropdownBorderColor',
		defaultValue: '<fontColorEight>22',
		cssProperty: 'border-color',
		selector:
			'.comp.compDropdown._bigDesign1, .comp.compDropdown._bigDesign1 ._dropdownContainer',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Dropdown Padding',
		name: 'defaultDropdownPadding',
		defaultValue: '0px 5px',
		cssProperty: 'padding',
		selector: '.comp.compDropdown._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Padding',
		name: 'outlineDropdownPadding',
		defaultValue: '0px 14px',
		cssProperty: 'padding',
		selector: '.comp.compDropdown._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Padding',
		name: 'filledDropdownPadding',
		defaultValue: '0px 5px',
		cssProperty: 'padding',
		selector: '.comp.compDropdown._filled',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Padding',
		name: 'bigdesign1DropdownPadding',
		defaultValue: '0px 5px',
		cssProperty: 'padding',
		selector: '.comp.compDropdown._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Dropdown Container Padding',
		name: 'defaultDropdownContainerPadding',
		defaultValue: '6px',
		cssProperty: 'padding',
		selector: '.comp.compDropdown._default ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Container Padding',
		name: 'outlineDropdownContainerPadding',
		defaultValue: '6px 14px',
		cssProperty: 'padding',
		selector: '.comp.compDropdown._outlined ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Container Padding',
		name: 'filledDropdownContainerPadding',
		defaultValue: '6px',
		cssProperty: 'padding',
		selector: '.comp.compDropdown._filled ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Container Padding',
		name: 'bigdesign1DropdownContainerPadding',
		defaultValue: '6px',
		cssProperty: 'padding',
		selector: '.comp.compDropdown._bigDesign1 ._dropdownContainer',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Dropdown Icon Padding',
		name: 'defaultIconDropdownPadding',
		defaultValue: '0px 8px',
		cssProperty: 'padding',
		selector:
			'.comp.compDropdown._default ._leftIcon, .comp.compDropdown._default ._rightIcon ',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Icon Padding',
		name: 'outlineIconDropdownPadding',
		defaultValue: '0px 8px',
		cssProperty: 'padding',
		selector:
			'.comp.compDropdown._outlined ._leftIcon, .comp.compDropdown._outlined ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Icon Padding',
		name: 'filledIconDropdownPadding',
		defaultValue: '0px 8px',
		cssProperty: 'padding',
		selector: '.comp.compDropdown._filled ._leftIcon, .comp.compDropdown._filled ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Right Icon Padding',
		name: 'bigdesign1LeftIconDropdownPadding',
		defaultValue: '0px 8px',
		cssProperty: 'padding',
		selector: '.comp.compDropdown._bigDesign1 ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Left Icon Padding',
		name: 'bigdesign1RightIconDropdownPadding',
		defaultValue: '0px 18px 0px 8px',
		cssProperty: 'padding',
		selector: '.comp.compDropdown._bigDesign1 ._leftIcon',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Dropdown Border When Active',
		name: 'defaultDropdownActiveBorder',
		defaultValue: '2px solid',
		cssProperty: 'border',
		selector:
			'.comp.compDropdown._default._isActive, .comp.compDropdown._default ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Border When Active',
		name: 'outlineDropdownActiveBorder',
		defaultValue: '2px solid',
		cssProperty: 'border',
		selector:
			'.comp.compDropdown._outlined._isActive, .comp.compDropdown._outlined ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Border When Active',
		name: 'filledDropdownActiveBorder',
		cssProperty: 'border',
		selector:
			'.comp.compDropdown._filled._isActive, .comp.compDropdown._filled ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Border When Active',
		name: 'bigdesign1DropdownActiveBorder',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector:
			'.comp.compDropdown._bigDesign1._isActive, .comp.compDropdown._bigDesign1 ._dropdownContainer',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Dropdown Background',
		name: 'defaultDropdownBackground',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compDropdown._default, .comp.compDropdown._default ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Background',
		name: 'outlineDropdownBackground',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compDropdown._outlined, .comp.compDropdown._outlined ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Background',
		name: 'filledDropdownBackground',
		defaultValue: '<backgroundColorNine>',
		cssProperty: 'background',
		selector: '.comp.compDropdown._filled',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Background',
		name: 'bigdesign1DropdownBackground',
		defaultValue: 'linear-gradient(90deg, #96A1B41A 0%, #33333300 64.33%), white',
		cssProperty: 'background',
		selector:
			'.comp.compDropdown._bigDesign1, .comp.compDropdown._bigDesign1 ._dropdownContainer',
		noPrefix: true,
	},

	{
		groupName: 'Active Label Color',
		displayName: 'Primary Dropdown Active Label Color',
		name: 'primaryDropdownActiveLabelColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._default._isActive._primary ._label, .comp.compDropdown._outlined._primary ._label, .comp.compDropdown._filled._isActive._primary ._label, .comp.compDropdown._bigDesign1._isActive._primary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Active Label Color',
		displayName: 'Secondary Dropdown Active  Label Color',
		name: 'secondaryDropdownActiveLabelColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._default._isActive._secondary ._label, .comp.compDropdown._outlined._secondary ._label, .comp.compDropdown._filled._isActive._secondary ._label, .comp.compDropdown._bigDesign1._isActive._secondary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Active Label Color',
		displayName: 'Tertiary Dropdown Active Label Color',
		name: 'tertiaryDropdownActiveLabelColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._default._isActive._tertiary ._label, .comp.compDropdown._outlined._tertiary ._label, .comp.compDropdown._filled._isActive._tertiary ._label, .comp.compDropdown._bigDesign1._isActive._tertiary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Active Label Color',
		displayName: 'Quaternary Dropdown Active Label Color',
		name: 'quaternaryDropdownActiveLabelColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._default._isActive._quaternary ._label, .comp.compDropdown._outlined._quaternary ._label, .comp.compDropdown._filled._isActive._quaternary ._label, .comp.compDropdown._bigDesign1._isActive._quaternary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Active Label Color',
		displayName: 'Quinary Dropdown Active Label Color',
		name: 'quinaryDropdownActiveLabelColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._default._isActive._quinary ._label, .comp.compDropdown._outlined._quinary ._label, .comp.compDropdown._filled._isActive._quinary ._label, .comp.compDropdown._bigDesign1._isActive._quinary ._label',
		noPrefix: true,
	},

	{
		groupName: 'Active Background',
		displayName: 'Primary Filled Dropdown Active Background Color',
		name: 'primaryDropdownActiveBackgroundColor',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector:
			'.comp.compDropdown._filled._isActive._primary, .comp.compDropdown._filled._primary ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Active Background',
		displayName: 'Secondary Filled Dropdown Active  Background Color',
		name: 'secondaryDropdownActiveBackgroundColor',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector:
			'.comp.compDropdown._filled._isActive._secondary, .comp.compDropdown._filled._secondary ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Active Background',
		displayName: 'Tertiary Filled Dropdown Active Background Color',
		name: 'tertiaryDropdownActiveBackgroundColor',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector:
			'.comp.compDropdown._filled._isActive._tertiary, .comp.compDropdown._filled._tertiary ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Active Background',
		displayName: 'Quaternary Filled Dropdown Active Background Color',
		name: 'quaternaryDropdownActiveBackgroundColor',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector:
			'.comp.compDropdown._filled._isActive._quaternary, .comp.compDropdown._filled._quaternary ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Active Background',
		displayName: 'Quinary Filled Dropdown Active Background Color',
		name: 'quinaryDropdownActiveBackgroundColor',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector:
			'.comp.compDropdown._filled._isActive._quinary, .comp.compDropdown._filled._quinary ._dropdownContainer',
		noPrefix: true,
	},

	{
		groupName: 'Active Border Color',
		displayName: 'Primary Dropdown Active Border Color',
		name: 'primaryDropdownActiveBorderColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'border-color',
		selector:
			'.comp.compDropdown._default._isActive._primary, .comp.compDropdown._outlined._primary, .comp.compDropdown._filled._isActive._primary, .comp.compDropdown._bigDesign1._isActive._primary, .comp.compDropdown._primary ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Active Border Color',
		displayName: 'Secondary Dropdown Active  Border Color',
		name: 'secondaryDropdownActiveBorderColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'border-color',
		selector:
			'.comp.compDropdown._default._isActive._secondary, .comp.compDropdown._outlined._secondary, .comp.compDropdown._filled._isActive._secondary, .comp.compDropdown._bigDesign1._isActive._secondary, .comp.compDropdown._secondary ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Active Border Color',
		displayName: 'Tertiary Dropdown Active Border Color',
		name: 'tertiaryDropdownActiveBorderColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'border-color',
		selector:
			'.comp.compDropdown._default._isActive._tertiary, .comp.compDropdown._outlined._tertiary, .comp.compDropdown._filled._isActive._tertiary, .comp.compDropdown._bigDesign1._isActive._tertiary, .comp.compDropdown._tertiary ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Active Border Color',
		displayName: 'Quaternary Dropdown Active Border Color',
		name: 'quaternaryDropdownActiveBorderColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'border-color',
		selector:
			'.comp.compDropdown._default._isActive._quaternary, .comp.compDropdown._outlined._quaternary, .comp.compDropdown._filled._isActive._quaternary, .comp.compDropdown._bigDesign1._isActive._quaternary, .comp.compDropdown._quaternary ._dropdownContainer',
		noPrefix: true,
	},
	{
		groupName: 'Active Border Color',
		displayName: 'Quinary Dropdown Active Border Color',
		name: 'quinaryDropdownActiveBorderColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'border-color',
		selector:
			'.comp.compDropdown._default._isActive._quinary, .comp.compDropdown._outlined._quinary, .comp.compDropdown._filled._isActive._quinary, .comp.compDropdown._bigDesign1._isActive._quinary, .comp.compDropdown._quinary ._dropdownContainer',
		noPrefix: true,
	},

	{
		groupName: 'Active Filled Font Color',
		displayName: 'Dropdown Filled Active  Font Color',
		name: 'textBoxFilledActiveFontColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._filled._isActive._secondary, .comp.compDropdown._filled._isActive._quaternary',
		noPrefix: true,
	},

	{
		groupName: 'IconColor',
		displayName: 'Primary Icon Color',
		name: 'primaryDropdownIconColor',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compDropdown._primary ._leftIcon, .comp.compDropdown._primary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'IconColor',
		displayName: 'Secondary Icon Color',
		name: 'secondaryDropdownIconColor',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._secondary ._leftIcon, .comp.compDropdown._secondary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'IconColor',
		displayName: 'Tertiary Icon Color',
		name: 'tertiaryDropdownIconColor',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._tertiary ._leftIcon, .comp.compDropdown._tertiary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'IconColor',
		displayName: 'Quaternary Icon Color',
		name: 'quaternaryDropdownIconColor',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._quaternary ._leftIcon, .comp.compDropdown._quaternary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'IconColor',
		displayName: 'Quinary Icon Color',
		name: 'quinaryDropdownIconColor',
		defaultValue: '<fontColorSix>',
		cssProperty: 'color',
		selector: '.comp.compDropdown._quinary ._leftIcon, .comp.compDropdown._quinary ._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Active IconColor',
		displayName: 'Primary Active Icon Color',
		name: 'primaryActiveDropdownIconColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._isActive._primary ._leftIcon, .comp.compDropdown._isActive._primary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Active IconColor',
		displayName: 'Secondary Active Icon Color',
		name: 'secondaryActiveDropdownIconColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._isActive._secondary ._leftIcon, .comp.compDropdown._isActive._secondary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Active IconColor',
		displayName: 'Tertiary Active Icon Color',
		name: 'tertiaryActiveDropdownIconColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._isActive._tertiary ._leftIcon, .comp.compDropdown._isActive._tertiary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Active IconColor',
		displayName: 'Quaternary Active Icon Color',
		name: 'quaternaryActiveDropdownIconColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._isActive._quaternary ._leftIcon, .comp.compDropdown._isActive._quaternary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Active IconColor',
		displayName: 'Quinary Active Icon Color',
		name: 'quinaryActiveDropdownIconColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._isActive._quinary ._leftIcon, .comp.compDropdown._isActive._quinary ._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Active Filled Icon Color',
		displayName: 'Dropdown Filled Active  Font Color',
		name: 'textBoxFilledActiveFontColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._filled._isActive._secondary ._leftIcon, .comp.compDropdown._filled._isActive._quaternary ._leftIcon, .comp.compDropdown._filled._isActive._secondary ._rightIcon, .comp.compDropdown._filled._isActive._quaternary ._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Active Big Design 1 Background',
		displayName: 'Primary Dropdown Active Background Color For Big Design 1',
		name: 'primaryDropdownActiveBackgroundColorBigDesign1',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorOne>19 0%, <backgroundColorSix>00 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compDropdown._bigDesign1._isActive._primary',
		noPrefix: true,
	},
	{
		groupName: 'Active Big Design 1 Background',
		displayName: 'Secondary Dropdown Active  Background Color For Big Design 1',
		name: 'secondaryDropdownActiveBackgroundColorBigDesign1',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorTwo>19 0%, <backgroundColorSix>00 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compDropdown._bigDesign1._isActive._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Active Big Design 1 Background',
		displayName: 'Tertiary Dropdown Active Background Color For Big Design 1',
		name: 'tertiaryDropdownActiveBackgroundColorBigDesign1',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorThree>19 0%, <backgroundColorSix>00 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compDropdown._bigDesign1._isActive._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Active Big Design 1 Background',
		displayName: 'Quaternary Dropdown Active Background Color For Big Design 1',
		name: 'quaternaryDropdownActiveBackgroundColorBigDesign1',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorFour>19 0%, <backgroundColorSix>00 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compDropdown._bigDesign1._isActive._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Active Big Design 1 Background',
		displayName: 'Quinary Dropdown Active Background Color For Big Design 1',
		name: 'quinaryDropdownActiveBackgroundColorBigDesign1',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorFive>19 0%, <backgroundColorSix>00 64.33%), white',
		cssProperty: 'background',
		selector: '.comp.compDropdown._bigDesign1._isActive._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Success Icon Color',
		displayName: 'Success Icon Color',
		name: 'successDropdownIconColor',
		defaultValue: '<successColor>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown ._successIcon._rightIcon, .comp.compDropdown._isActive ._successIcon._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Error Icon Color',
		displayName: 'Error Icon Color',
		name: 'errorDropdownIconColor',
		defaultValue: '<errorColor>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown ._errorIcon._rightIcon, .comp.compDropdown._isActive ._errorIcon._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Error Border Color',
		displayName: 'Error Active Border Color',
		name: 'errorDropdownBorderColor',
		defaultValue: '<errorColor>',
		cssProperty: 'border-color',
		selector:
			'.comp.compDropdown._default._hasError, .comp.compDropdown._outlined._hasError, .comp.compDropdown._filled._hasError, .comp.compDropdown._bigDesign1._hasError, .comp.compDropdown._default._isActive._hasError, .comp.compDropdown._filled._isActive._hasError, .comp.compDropdown._bigDesign1._isActive._hasError',
		noPrefix: true,
	},

	{
		groupName: 'Error Big Design 1Background',
		displayName: 'Error Big Design 1Dropdown Background',
		name: 'errorDropdownBackgroundColorForBigDesign1',
		defaultValue: 'linear-gradient(90deg, <errorColor>19 0%, <backgroundColorSix>00 64.33%)',
		cssProperty: 'background',
		selector:
			'.comp.compDropdown._bigDesign1._isActive._hasError, .comp.compDropdown._bigDesign1._hasError',
		noPrefix: true,
	},

	{
		groupName: 'Error Filled',
		displayName: 'Error Filled Dropdown Background',
		name: 'errorDropdownBackgroundColorForFilledDesign',
		defaultValue: '<errorColor>',
		cssProperty: 'background',
		selector:
			'.comp.compDropdown._filled._isActive._hasError, .comp.compDropdown._filled._hasError',
		noPrefix: true,
	},

	{
		groupName: 'Error Filled',
		displayName: 'Error Filled Dropdown Font Color',
		name: 'errorDropdownFontColorForFilledDesign',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._filled._isActive._hasError, .comp.compDropdown._filled._hasError, .comp.compDropdown._filled._isActive._hasError ._leftIcon, .comp.compDropdown._filled._hasError ._leftIcon, .comp.compDropdown._filled._isActive._hasError ._rightIcon, .comp.compDropdown._filled._hasError ._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Dropdown Support Text Font',
		name: 'defaultDropdownSupportTextFont',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compDropdown._default ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Support Text Font',
		name: 'outlineDropdownSupportTextFont',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compDropdown._outlined ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Support Text Font',
		name: 'filledDropdownSupportTextFont',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compDropdown._filled ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Support Text Font',
		name: 'bigdesign1DropdownSupportTextFont',
		defaultValue: '<quaternaryFont>',
		cssProperty: 'font',
		selector: '.comp.compDropdown._bigDesign1 ._supportText',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Dropdown Support Text Color',
		name: 'defaultDropdownSupportTextColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compDropdown._default ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Support Text Color',
		name: 'outlineDropdownSupportTextColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compDropdown._outlined ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Support Text Color',
		name: 'filledDropdownSupportTextColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compDropdown._filled ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Support Text Color',
		name: 'bigdesign1DropdownSupportTextColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compDropdown._bigDesign1 ._supportText',
		noPrefix: true,
	},

	{
		groupName: 'Active Support Text Color',
		displayName: 'Primary Dropdown Active Support Text Color',
		name: 'primaryDropdownActiveSupportTextColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._default._isActive._primary ._supportText, .comp.compDropdown._outlined._primary ._supportText, .comp.compDropdown._filled._isActive._primary ._supportText, .comp.compDropdown._bigDesign1._isActive._primary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Active Support Text Color',
		displayName: 'Secondary Dropdown Active  Support Text Color',
		name: 'secondaryDropdownActiveSupportTextColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._default._isActive._secondary ._supportText, .comp.compDropdown._outlined._secondary ._supportText, .comp.compDropdown._filled._isActive._secondary ._supportText, .comp.compDropdown._bigDesign1._isActive._secondary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Active Support Text Color',
		displayName: 'Tertiary Dropdown Active Support Text Color',
		name: 'tertiaryDropdownActiveSupportTextColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._default._isActive._tertiary ._supportText, .comp.compDropdown._outlined._tertiary ._supportText, .comp.compDropdown._filled._isActive._tertiary ._supportText, .comp.compDropdown._bigDesign1._isActive._tertiary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Active Support Text Color',
		displayName: 'Quaternary Dropdown Active Support Text Color',
		name: 'quaternaryDropdownActiveSupportTextColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._default._isActive._quaternary ._supportText, .comp.compDropdown._outlined._quaternary ._supportText, .comp.compDropdown._filled._isActive._quaternary ._supportText, .comp.compDropdown._bigDesign1._isActive._quaternary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Active Support Text Color',
		displayName: 'Quinary Dropdown Active Support Text Color',
		name: 'quinaryDropdownActiveSupportTextColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector:
			'.comp.compDropdown._default._isActive._quinary ._supportText, .comp.compDropdown._outlined._quinary ._supportText, .comp.compDropdown._filled._isActive._quinary ._supportText, .comp.compDropdown._bigDesign1._isActive._quinary ._supportText',
		noPrefix: true,
	},

	{
		groupName: 'Dropdown Item Tick',
		displayName: 'Primary Dropdown Item Tick',
		name: 'primaryDropdownItemTick',
		defaultValue: '2px solid <fontColorThree>',
		cssProperty: 'border',
		selector: '.comp.compDropdown._primary ._dropdownCheckIcon::before',
		noPrefix: true,
	},
	{
		groupName: 'Dropdown Item Tick',
		displayName: 'Secondary Dropdown Item Tick',
		name: 'secondaryDropdownItemTick',
		defaultValue: '2px solid <fontColorFour>',
		cssProperty: 'border',
		selector: '.comp.compDropdown._secondary ._dropdownCheckIcon::before',
		noPrefix: true,
	},
	{
		groupName: 'Dropdown Item Tick',
		displayName: 'Tertiary Dropdown Item Tick',
		name: 'tertiaryDropdownItemTick',
		defaultValue: '2px solid <fontColorFive>',
		cssProperty: 'border',
		selector: '.comp.compDropdown._tertiary._dropdownCheckIcon::before',
		noPrefix: true,
	},
	{
		groupName: 'Dropdown Item Tick',
		displayName: 'Quaternary Dropdown Item Tick',
		name: 'quaternaryDropdownItemTick',
		defaultValue: '2px solid <fontColorNine>',
		cssProperty: 'border',
		selector: '.comp.compDropdown._quaternary._dropdownCheckIcon::before',
		noPrefix: true,
	},
	{
		groupName: 'Dropdown Item Tick',
		displayName: 'Quinary Dropdown Item Tick',
		name: 'quinaryDropdownItemTick',
		defaultValue: '2px solid <fontColorSeven>',
		cssProperty: 'border',
		selector: '.comp.compDropdown._quinary._dropdownCheckIcon::before',
		noPrefix: true,
	},

	{
		groupName: 'Dropdown Item Tick',
		displayName: 'Dropdown Item Tick Height',
		name: 'dropdownItemTickHeight',
		defaultValue: '15px',
		cssProperty: 'height',
		selector: '._dropdownCheckIcon',
	},
	{
		groupName: 'Dropdown Item Tick',
		displayName: 'Dropdown Item Tick Width',
		name: 'dropdownItemTickWidth',
		defaultValue: '8px',
		cssProperty: 'width',
		selector: '._dropdownCheckIcon',
	},

	{
		groupName: 'Dropdown Item Tick',
		displayName: 'Margin Dropdown Item Tick',
		name: 'dropdownItemTickMargin',
		defaultValue: '0px 6px',
		cssProperty: 'margin',
		selector: '._dropdownCheckIcon',
	},

	{
		groupName: 'Dropdown Item',
		displayName: 'Dropdown Item Padding',
		name: 'dropdownItemPadding',
		defaultValue: '4px',
		cssProperty: 'padding',
		selector: '._dropdownItem',
	},
	{
		groupName: 'Dropdown Item',
		displayName: 'Dropdown Item Margin',
		name: 'dropdownItemMargin',
		defaultValue: '2px',
		cssProperty: 'margin',
		selector: '._dropdownItem',
	},
	{
		groupName: 'Dropdown Item',
		displayName: 'Dropdown Item Border Radius',
		name: 'dropdownItemBorderRadius',
		defaultValue: '3px',
		cssProperty: 'border-radius',
		selector: '._dropdownItem',
	},

	{
		groupName: 'Dropdown Item',
		displayName: 'Primary Filled Dropdown Item Hover Background Color',
		name: 'primaryDropdownItemHoverBackgroundColor',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'background',
		selector: '.comp.compDropdown._primary ._dropdownItem._hover',
		noPrefix: true,
	},
	{
		groupName: 'Dropdown Item',
		displayName: 'Secondary Filled Dropdown Item Hover  Background Color',
		name: 'secondaryDropdownItemHoverBackgroundColor',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compDropdown._secondary ._dropdownItem._hover',
		noPrefix: true,
	},
	{
		groupName: 'Dropdown Item',
		displayName: 'Tertiary Filled Dropdown Item Hover Background Color',
		name: 'tertiaryDropdownItemHoverBackgroundColor',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'background',
		selector: '.comp.compDropdown._tertiary ._dropdownItem._hover',
		noPrefix: true,
	},
	{
		groupName: 'Dropdown Item',
		displayName: 'Quaternary Filled Dropdown Item Hover Background Color',
		name: 'quaternaryDropdownItemHoverBackgroundColor',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'background',
		selector: '.comp.compDropdown._quaternary ._dropdownItem._hover',
		noPrefix: true,
	},
	{
		groupName: 'Dropdown Item',
		displayName: 'Quinary Filled Dropdown Item Hover Background Color',
		name: 'quinaryDropdownItemHoverBackgroundColor',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'background',
		selector: '.comp.compDropdown._quinary ._dropdownItem._hover',
		noPrefix: true,
	},

	{
		groupName: 'Dropdown Search',
		displayName: 'Search Input box Height',
		name: 'dropdownSearchBoxHeight',
		defaultValue: '20px',
		cssProperty: 'height',
		selector: '._dropdownSearchBox',
	},
	{
		groupName: 'Dropdown Search',
		displayName: 'Search Input box Font',
		name: 'dropdownSearchBoxWidth',
		defaultValue: '1',
		cssProperty: 'width',
		selector: '._dropdownSearchBox',
	},

	{
		groupName: 'Dropdown Search',
		displayName: 'Primary Dropdown Item Search Input Border',
		name: 'primaryDropdownSearchBoxBorder',
		defaultValue: '2px solid <fontColorThree>',
		cssProperty: 'border',
		selector: '.comp.compDropdown._primary ._dropdownSearchBox',
		noPrefix: true,
	},
	{
		groupName: 'Dropdown Search',
		displayName: 'Secondary  Dropdown Item Search Input Border',
		name: 'secondaryDropdownSearchBoxBorder',
		defaultValue: '2px solid <fontColorFour>',
		cssProperty: 'border',
		selector: '.comp.compDropdown._secondary ._dropdownSearchBox',
		noPrefix: true,
	},
	{
		groupName: 'Dropdown Search',
		displayName: 'Tertiary Dropdown Item Search Input Border',
		name: 'tertiaryDropdownSearchBoxBorder',
		defaultValue: '2px solid <fontColorFive>',
		cssProperty: 'border',
		selector: '.comp.compDropdown._tertiary ._dropdownSearchBox',
		noPrefix: true,
	},
	{
		groupName: 'Dropdown Search',
		displayName: 'Quaternary Dropdown Item Search Input Border',
		name: 'quaternaryDropdownSearchBoxBorder',
		defaultValue: '2px solid <fontColorNine>',
		cssProperty: 'border',
		selector: '.comp.compDropdown._quaternary ._dropdownSearchBox',
		noPrefix: true,
	},
	{
		groupName: 'Dropdown Search',
		displayName: 'Quinary Dropdown Item Search Input Border',
		name: 'quinaryDropdownSearchBoxBorder',
		defaultValue: '2px solid <fontColorSeven>',
		cssProperty: 'border',
		selector: '.comp.compDropdown._quinary ._dropdownSearchBox',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Dropdown Item Search Input Box Border Radius',
		name: 'defaultDropdownItemSearchInputBoxBorderRadius',
		defaultValue: '2px',
		cssProperty: 'border-radius',
		selector: '.comp.compDropdown._default ._dropdownSearchBox',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Dropdown Item Search Input Box Border Radius',
		name: 'outlineDropdownItemSearchInputBoxBorderRadius',
		defaultValue: '2px',
		cssProperty: 'border-radius',
		selector: '.comp.compDropdown._outlined ._dropdownSearchBox',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Dropdown Item Search Input Box Border Radius',
		name: 'filledDropdownItemSearchInputBoxBorderRadius',
		defaultValue: '2px',
		cssProperty: 'border-radius',
		selector: '.comp.compDropdown._filled ._dropdownSearchBox',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Dropdown Item Search Input Box Border Radius',
		name: 'bigdesign1DropdownItemSearchInputBoxBorderRadius',
		defaultValue: '2px',
		cssProperty: 'border-radius',
		selector: '.comp.compDropdown._bigDesign1 ._dropdownSearchBox',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
