import { StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		name: 'marginLeft',
		cssProperty: 'margin-left',
		displayName: 'margin left',
		description: 'This property specifies the left margin of the component',
		defaultValue: '20px',
	},

	{
		name: 'marginRight',
		cssProperty: 'margin-right',
		displayName: 'margin right',
		description: 'This property specifies the right margin of the component',
		defaultValue: '20px',
	},
	{
		name: 'padding',
		cssProperty: 'padding',
		displayName: 'padding',
		description: 'This property specifies the padding of the tab buttons',
		defaultValue: '10px 0 4px 0px',
		selector: '.tabsButtons',
	},
	{
		name: 'backgroundColorButton',
		cssProperty: 'background-color',
		displayName: 'background color',
		description: 'This property specifies the background color of the tab buttons',
		defaultValue: '#ffffff',
		selector: '.tabsButtons',
	},
	{
		name: 'borderButton',
		cssProperty: 'border',
		displayName: 'border',
		description: 'This property specifies the border of the tab buttons',
		defaultValue: 'none',
		selector: '.tabsButtons',
	},
	{
		name: 'textAlignButton',
		cssProperty: 'text-align',
		displayName: 'text align',
		description: 'This property specifies the text alignment of the tab buttons',
		defaultValue: 'left',
		selector: '.tabsButtons',
	},
	{
		name: 'fontSizeButton',
		cssProperty: 'font-size',
		displayName: 'font size',
		description: 'This property specifies the font size of the tab buttons',
		defaultValue: '15px',
		selector: '.tabsButtons',
	},
	{
		name: 'fontFamilyButton',
		cssProperty: 'font-family',
		displayName: 'font family',
		description: 'This property specifies the font family of the tab buttons',
		defaultValue: 'Open Sans',
		selector: '.tabsButtons',
	},
	{
		name: 'cursor',
		cssProperty: 'cursor',
		displayName: 'cursor',
		description: 'This property specifies the cursor type of the tab buttons',
		defaultValue: 'pointer',
		selector: '.tabsButtons',
	},
	{
		name: 'colorButton',
		cssProperty: 'color',
		displayName: 'color',
		description: 'This property specifies the color of the tab buttons',
		defaultValue: '#6c7586',
		selector: '.tabsButtons',
	},
	{
		name: 'opacityButton',
		cssProperty: 'opacity',
		displayName: 'opacity',
		description: 'This property specifies the opacity of the tab buttons',
		defaultValue: '1',
		selector: '.tabsButtons',
	},
	{
		name: 'displayButton',
		cssProperty: 'display',
		displayName: 'display',
		description: 'This property specifies the display properties of the tab buttons',
		defaultValue: 'flex',
		selector: '.tabsButtons',
	},
	{
		name: 'gapButton',
		cssProperty: 'gap',
		displayName: 'gap',
		description: 'This property specifies the gap between the tab buttons',
		defaultValue: '3px',
		selector: '.tabsButtons',
	},
	{
		name: 'borderBottomButton',
		cssProperty: 'border-bottom',
		displayName: 'border bottom',
		description: 'This property specifies the border bottom of  buttons',
		defaultValue: '6px solid #ffffff',
		selector: '.tabsButtons',
	},
	{
		name: 'justifyContentButton',
		cssProperty: 'justify-content',
		displayName: 'justify content',
		description: 'This property specifies the row alignment  of buttons',
		defaultValue: 'center',
		selector: '.tabsButtons',
	},
	{
		name: 'alignItemsButton',
		cssProperty: 'align-items',
		displayName: 'align items',
		description: 'This property specifies the colum alignment  of buttons',
		defaultValue: 'center',
		selector: '.tabsButtons',
	},
	{
		name: 'activeButtonBorder',
		cssProperty: 'border-bottom',
		displayName: 'border bottom',
		description: 'This property specifies the Border style of active button buttons',
		defaultValue: '6px solid #1f3c3d',
		selector: '.tabsButtonActive',
	},

	{
		name: 'widthDiv',
		cssProperty: 'width',
		displayName: 'width',
		description: 'This property specifies the width of container',
		defaultValue: '100%',
		selector: '.tabButtonDiv',
	},
	{
		name: 'justifyContentDiv',
		cssProperty: 'justify-content',
		displayName: 'justify content',
		description: 'This property specifies the row justification  of container',
		defaultValue: 'space-between',
		selector: '.tabButtonDiv',
	},
	{
		name: 'paddingLeftDiv',
		cssProperty: 'padding-left',
		displayName: 'padding left',
		description: 'This property specifies the left padding of container',
		defaultValue: '20px',
		selector: '.tabButtonDiv',
	},
	{
		name: 'paddingRightDiv',
		cssProperty: 'padding-right',
		displayName: 'padding right',
		description: 'This property specifies the right padding of container',
		defaultValue: '20px',
		selector: '.tabButtonDiv',
	},
	{
		name: 'displayDiv',
		cssProperty: 'display',
		displayName: 'display',
		description: 'This property specifies the display properties of the tab container',
		defaultValue: 'flex',
		selector: '.tabButtonDiv',
	},
	{
		name: 'borderBottomDiv',
		cssProperty: 'border-bottom',
		displayName: 'border bottom',
		description: 'This property specifies the border bottom of container',
		defaultValue: '1px solid #cecece',
		selector: '.tabButtonDiv',
	},
];
export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
