import { StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		displayName: 'Checkbox Font',
		name: 'checkboxFont',
		defaultValue: '<primaryFont>',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Checkbox Font',
		name: 'defaultCheckboxFont',
		defaultValue: '<checkboxFont>',
		cssProperty: 'font',
		selector: '.comp.compCheckbox._default label',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Checkbox Font',
		name: 'outlineCheckboxFont',
		defaultValue: '<checkboxFont>',
		cssProperty: 'font',
		selector: '.comp.compCheckbox._outlined label',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Checkbox Font',
		name: 'filledCheckboxFont',
		defaultValue: '<checkboxFont>',
		cssProperty: 'font',
		selector: '.comp.compCheckbox._filled label',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Checkbox Border',
		name: 'defaultCheckboxBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compCheckbox._default .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Checkbox Border',
		name: 'outlineCheckboxBorder',
		defaultValue: '2px solid',
		cssProperty: 'border',
		selector: '.comp.compCheckbox._outlined .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Checkbox Border',
		name: 'filledCheckboxBorder',
		defaultValue: '2px solid',
		cssProperty: 'border',
		selector: '.comp.compCheckbox._filled .commonCheckbox',
		noPrefix: true,
	},

	{
		groupName: 'Border Color',
		displayName: 'Primary Outline Checkbox Border Color',
		name: 'primaryOutlineCheckboxBorderColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compCheckbox._outlined._primary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Secondary Outline Checkbox Border Color',
		name: 'secondaryOutlineCheckboxBorderColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compCheckbox._outlined._secondary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Tertiary Outline Checkbox Border Color',
		name: 'tertiaryOutlineCheckboxBorderColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compCheckbox._outlined._tertiary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Quaternary Outline Checkbox Border Color',
		name: 'quaternaryOutlineCheckboxBorderColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'border-color',
		selector: '.comp.compCheckbox._outlined._quaternary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Quinary Outline Checkbox Border Color',
		name: 'quinaryOutlineCheckboxBorderColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'border-color',
		selector: '.comp.compCheckbox._outlined._quinary .commonCheckbox',
		noPrefix: true,
	},

	{
		groupName: 'Border Color',
		displayName: 'Primary Filled Checkbox Border Color',
		name: 'primaryFilledCheckboxBorderColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compCheckbox._filled._primary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Secondary Filled Checkbox Border Color',
		name: 'secondaryFilledCheckboxBorderColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compCheckbox._filled._secondary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Tertiary Filled Checkbox Border Color',
		name: 'tertiaryFilledCheckboxBorderColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compCheckbox._filled._tertiary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Quaternary Filled Checkbox Border Color',
		name: 'quaternaryFilledCheckboxBorderColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'border-color',
		selector: '.comp.compCheckbox._filled._quaternary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Quinary Filled Checkbox Border Color',
		name: 'quinaryFilledCheckboxBorderColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'border-color',
		selector: '.comp.compCheckbox._filled._quinary .commonCheckbox',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Primary Default Checkbox Background',
		name: 'primaryDefaultCheckboxBackground',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._default._primary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Secondary Default Checkbox Background',
		name: 'secondaryDefaultCheckboxBackground',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._default._secondary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Tertiary Default Checkbox Background',
		name: 'tertiaryDefaultCheckboxBackground',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._default._tertiary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quaternary Default Checkbox Background',
		name: 'quaternaryDefaultCheckboxBackground',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._default._quaternary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quinary Default Checkbox Background',
		name: 'quinaryDefaultCheckboxBackground',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._default._quinary .commonCheckbox',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Outline Checkbox Background',
		name: 'outlineCheckboxBackground',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._outlined .commonCheckbox',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Primary Filled Checkbox Background',
		name: 'primaryFilledCheckboxBackground',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._filled._primary .commonCheckbox._checked',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Secondary Filled Checkbox Background',
		name: 'secondaryFilledCheckboxBackground',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._filled._secondary .commonCheckbox._checked',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Tertiary Filled Checkbox Background',
		name: 'tertiaryFilledCheckboxBackground',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._filled._tertiary .commonCheckbox._checked',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quaternary Filled Checkbox Background',
		name: 'quaternaryFilledCheckboxBackground',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._filled._quaternary .commonCheckbox._checked',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quinary Filled Checkbox Background',
		name: 'quinaryFilledCheckboxBackground',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._filled._quinary .commonCheckbox._checked',
		noPrefix: true,
	},

	{
		groupName: 'Tick Color',
		displayName: 'Checkbox Tick Color',
		name: 'checkboxTickColor',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._default .commonCheckbox::before',
		noPrefix: true,
	},

	{
		groupName: 'Tick Color',
		displayName: 'Filled Tick Color',
		name: 'filledTickColor',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._filled .commonCheckbox::before',
		noPrefix: true,
	},

	{
		groupName: 'Tick Color',
		displayName: 'Primary Outline Checkbox Tick Color',
		name: 'primaryOutlineCheckboxTickColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._outlined._primary .commonCheckbox::before',
		noPrefix: true,
	},
	{
		groupName: 'Tick Color',
		displayName: 'Secondary Outline Checkbox Tick Color',
		name: 'secondaryOutlineCheckboxTickColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._outlined._secondary .commonCheckbox::before',
		noPrefix: true,
	},
	{
		groupName: 'Tick Color',
		displayName: 'Tertiary Outline Checkbox Tick Color',
		name: 'tertiaryOutlineCheckboxTickColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._outlined._tertiary .commonCheckbox::before',
		noPrefix: true,
	},
	{
		groupName: 'Tick Color',
		displayName: 'Quaternary Outline Checkbox Tick Color',
		name: 'quaternaryOutlineCheckboxTickColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._outlined._quaternary .commonCheckbox::before',
		noPrefix: true,
	},
	{
		groupName: 'Tick Color',
		displayName: 'Quinary Outline Checkbox Tick Color',
		name: 'quinaryOutlineCheckboxTickColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compCheckbox._outlined._quinary .commonCheckbox::before',
		noPrefix: true,
	},

	{
		groupName: 'Border Color',
		displayName: 'Outline Disabled Checkbox Border Color',
		name: 'outlineDisabledCheckboxBorderColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector:
			'.comp.compCheckbox._outlined._primary .commonCheckbox:disabled,.comp.compCheckbox._outlined._secondary .commonCheckbox:disabled,.comp.compCheckbox._outlined._tertiary .commonCheckbox:disabled,.comp.compCheckbox._outlined._quaternary .commonCheckbox:disabled,.comp.compCheckbox._outlined._quinary .commonCheckbox:disabled',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Default Disabled Checkbox Background',
		name: 'defaultDisabledCheckboxBackground',
		defaultValue: '<backgroundColorEight>',
		cssProperty: 'background',
		selector:
			'.comp.compCheckbox._default._primary .commonCheckbox:disabled,.comp.compCheckbox._default._secondary .commonCheckbox:disabled,.comp.compCheckbox._default._tertiary .commonCheckbox:disabled,.comp.compCheckbox._default._quaternary .commonCheckbox:disabled,.comp.compCheckbox._default._quinary .commonCheckbox:disabled',
		noPrefix: true,
	},
	{
		groupName: 'Tick Color',
		displayName: ' Outline Disabled Checkbox Tick Color',
		name: ' OutlineDisabledCheckboxTickColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'background',
		selector:
			'.comp.compCheckbox._outlined._primary .commonCheckbox:disabled::before,.comp.compCheckbox._outlined._secondary .commonCheckbox:disabled::before,.comp.compCheckbox._outlined._tertiary .commonCheckbox:disabled::before,.comp.compCheckbox._outlined._quaternary .commonCheckbox:disabled::before,.comp.compCheckbox._outlined._quinary .commonCheckbox:disabled::before',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Outline Disabled Checkbox Font Color',
		name: 'outlineDisabledCheckboxFontColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compCheckbox._outlined label._disabled',
		noPrefix: true,
	},

	{
		groupName: 'Font Color',
		displayName: 'Primary Outline Checkbox Font Color',
		name: 'primaryOutlineCheckboxFontColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector: '.comp.compCheckbox._outlined._primary',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Secondary Outline Checkbox Font Color',
		name: 'secondaryOutlineCheckboxFontColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector: '.comp.compCheckbox._outlined._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Tertiary Outline Checkbox Font Color',
		name: 'tertiaryOutlineCheckboxFontColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector: '.comp.compCheckbox._outlined._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Quaternary Outline Checkbox Font Color',
		name: 'quaternaryOutlineCheckboxFontColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector: '.comp.compCheckbox._outlined._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Quinary Outline Checkbox Font Color',
		name: 'quinaryOutlineCheckboxFontColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector: '.comp.compCheckbox._outlined._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Font Color',
		displayName: 'Primary Filled Checkbox Font Color',
		name: 'primaryFilledCheckboxFontColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector: '.comp.compCheckbox._filled._primary',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Secondary Filled Checkbox Font Color',
		name: 'secondaryFilledCheckboxFontColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector: '.comp.compCheckbox._filled._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Tertiary Filled Checkbox Font Color',
		name: 'tertiaryFilledCheckboxFontColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector: '.comp.compCheckbox._filled._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Quaternary Filled Checkbox Font Color',
		name: 'quaternaryFilledCheckboxFontColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector: '.comp.compCheckbox._filled._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Quinary Filled Checkbox Font Color',
		name: 'quinaryFilledCheckboxFontColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector: '.comp.compCheckbox._filled._quinary',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
