import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		name: 'design1RowHeight',
		cssProperty: 'height',
		displayName: 'Design 1 Row Height',
		description: 'Design 1 Row Height',
		defaultValue: '60px',
	},
	{
		name: 'design2RowHeight',
		cssProperty: 'height',
		displayName: 'Design 2 Row Height',
		description: 'Design 2 Row Height',
		defaultValue: '30px',
	},
	{
		name: 'design3RowHeight',
		cssProperty: 'height',
		displayName: 'Design 3 Row Height',
		description: 'Design 3 Row Height',
		defaultValue: '60px',
	},
	{
		name: 'design4RowHeight',
		cssProperty: 'height',
		displayName: 'Design 4 Row Height',
		description: 'Design 4 Row Height',
		defaultValue: '30px',
	},
	{
		name: 'design5RowHeight',
		cssProperty: 'height',
		displayName: 'Design 5 Row Height',
		description: 'Design 5 Row Height',
		defaultValue: '60px',
	},
	{
		name: 'design6RowHeight',
		cssProperty: 'height',
		displayName: 'Design 6 Row Height',
		description: 'Design 6 Row Height',
		defaultValue: '30px',
	},
	{
		name: 'design7RowHeight',
		cssProperty: 'height',
		displayName: 'Design 7 Row Height',
		description: 'Design 7 Row Height',
		defaultValue: '60px',
	},
	{
		name: 'design8RowHeight',
		cssProperty: 'height',
		displayName: 'Design 8 Row Height',
		description: 'Design 8 Row Height',
		defaultValue: '30px',
	},
	{
		name: 'design9RowHeight',
		cssProperty: 'height',
		displayName: 'Design 9 Row Height',
		description: 'Design 9 Row Height',
		defaultValue: '60px',
	},
	{
		name: 'design10RowHeight',
		cssProperty: 'height',
		displayName: 'Design 10 Row Height',
		description: 'Design 10 Row Height',
		defaultValue: '30px',
	},
	{
		name: 'design1RowBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 1 Row Background Color',
		description: 'Design 1 Row Background Color',
		defaultValue: '#FFFFFF',
	},
	{
		name: 'design2RowBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 2 Row Background Color',
		description: 'Design 2 Row Background Color',
		defaultValue: '#FFFFFF',
	},
	{
		name: 'design3RowBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 3 Row Background Color',
		description: 'Design 3 Row Background Color',
		defaultValue: '#FFFFFF',
	},
	{
		name: 'design4RowBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 4 Row Background Color',
		description: 'Design 4 Row Background Color',
		defaultValue: '#FFFFFF',
	},
	{
		name: 'design5RowBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 5 Row Background Color',
		description: 'Design 5 Row Background Color',
		defaultValue: '#FFFFFF',
	},
	{
		name: 'design6RowBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 6 Row Background Color',
		description: 'Design 6 Row Background Color',
		defaultValue: '#FFFFFF',
	},
	{
		name: 'design7RowBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 7 Row Background Color',
		description: 'Design 7 Row Background Color',
		defaultValue: '#FFFFFF',
	},
	{
		name: 'design8RowBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 8 Row Background Color',
		description: 'Design 8 Row Background Color',
		defaultValue: '#FFFFFF',
	},
	{
		name: 'design9RowBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 9 Row Background Color',
		description: 'Design 9 Row Background Color',
		defaultValue: '#FFFFFF',
	},
	{
		name: 'design10RowBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 10 Row Background Color',
		description: 'Design 10 Row Background Color',
		defaultValue: '#FFFFFF',
	},
	{
		name: 'design1EvenRowBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 1 Even Row Background Color',
		description: 'Design 1 Even Row Background Color',
		defaultValue: '#F6F6F6',
	},
	{
		name: 'design5EvenBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 5 Even Row Background Color',
		description: 'Design 5 Even Row Background Color',
		defaultValue: '#F6F6F6',
	},
	{
		name: 'design9EvenBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 9 Even Row Background Color',
		description: 'Design 9 Even Row Background Color',
		defaultValue: '#F6F6F6',
	},

	{
		name: 'design3SecondBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 3 Second Row Background Color',
		description: 'Design 3 Second Row Background Color',
		defaultValue: '#F6F6F6',
	},
	{
		name: 'design7SecondBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 7 Second Row Background Color',
		description: 'Design 7 Second Row Background Color',
		defaultValue: '#F6F6F6',
	},
	{
		name: 'design3ThridBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 3 Third Row Background Color',
		description: 'Design 3 Thrid Row Background Color',
		defaultValue: '#F6F6F6',
	},
	{
		name: 'design7ThirdBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 7 Third Row Background Color',
		description: 'Design 7 Third Row Background Color',
		defaultValue: '#F6F6F6',
	},

	{
		name: 'design1RowHoverSelectedBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 1 Row Hover or Selected Background Color',
		description: 'Design 1 Row Hover or Selected Background Color',
		defaultValue: '#EEEEEE',
		noPrefix: true,
		selector:
			'.comp.compTable._design1 ._row._dataRow:hover, .comp.compTable._design1 ._row._dataRow._selected',
	},
	{
		name: 'design2RowHoverSelectedBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 2 Row Hover or Selected Background Color',
		description: 'Design 2 Row Hover or Selected Background Color',
		defaultValue: '#EEEEEE',
		noPrefix: true,
		selector:
			'.comp.compTable._design2 ._row._dataRow:hover, .comp.compTable._design2 ._row._dataRow._selected',
	},
	{
		name: 'design3RowHoverSelectedBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 3 Row Hover or Selected Background Color',
		description: 'Design 3 Row Hover or Selected Background Color',
		defaultValue: '#EEEEEE',
		noPrefix: true,
		selector:
			'.comp.compTable._design3 ._row._dataRow:hover, .comp.compTable._design3 ._row._dataRow._selected',
	},
	{
		name: 'design4RowHoverSelectedBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 4 Row Hover or Selected Background Color',
		description: 'Design 4 Row Hover or Selected Background Color',
		defaultValue: '#EEEEEE',
		noPrefix: true,
		selector:
			'.comp.compTable._design4 ._row._dataRow:hover, .comp.compTable._design4 ._row._dataRow._selected',
	},
	{
		name: 'design5RowHoverSelectedBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 5 Row Hover or Selected Background Color',
		description: 'Design 5 Row Hover or Selected Background Color',
		defaultValue: '#EEEEEE',
		noPrefix: true,
		selector:
			'.comp.compTable._design5 ._row._dataRow:hover, .comp.compTable._design5 ._row._dataRow._selected',
	},
	{
		name: 'design6RowHoverSelectedBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 6 Row Hover or Selected Background Color',
		description: 'Design 6 Row Hover or Selected Background Color',
		defaultValue: '#EEEEEE',
		noPrefix: true,
		selector:
			'.comp.compTable._design6 ._row._dataRow:hover, .comp.compTable._design6 ._row._dataRow._selected',
	},
	{
		name: 'design7RowHoverSelectedBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 7 Row Hover or Selected Background Color',
		description: 'Design 7 Row Hover or Selected Background Color',
		defaultValue: '#EEEEEE',
		noPrefix: true,
		selector:
			'.comp.compTable._design7 ._row._dataRow:hover, .comp.compTable._design7 ._row._dataRow._selected',
	},
	{
		name: 'design8RowHoverSelectedBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 8 Row Hover or Selected Background Color',
		description: 'Design 8 Row Hover or Selected Background Color',
		defaultValue: '#EEEEEE',
		noPrefix: true,
		selector:
			'.comp.compTable._design8 ._row._dataRow:hover, .comp.compTable._design8 ._row._dataRow._selected',
	},
	{
		name: 'design9RowHoverSelectedBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 9 Row Hover or Selected Background Color',
		description: 'Design 9 Row Hover or Selected Background Color',
		defaultValue: '#EEEEEE',
		noPrefix: true,
		selector:
			'.comp.compTable._design9 ._row._dataRow:hover, .comp.compTable._design9 ._row._dataRow._selected',
	},
	{
		name: 'design10RowHoverSelectedBackgroundColor',
		cssProperty: 'background-color',
		displayName: 'Design 10 Row Hover or Selected Background Color',
		description: 'Design 10 Row Hover or Selected Background Color',
		defaultValue: '#EEEEEE',
		noPrefix: true,
		selector:
			'.comp.compTable._design10 ._row._dataRow:hover, .comp.compTable._design10 ._row._dataRow._selected',
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
