import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'Row Height',
		displayName: 'Design 1 Row Height',
		name: 'design1RowHeight',
		defaultValue: '60px',
		description: 'Design 1 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 2 Row Height',
		name: 'design2RowHeight',
		defaultValue: '60px',
		description: 'Design 2 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 3 Row Height',
		name: 'design3RowHeight',
		defaultValue: '68px',
		description: 'Design 3 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 4 Row Height',
		name: 'design4RowHeight',
		defaultValue: '68px',
		description: 'Design 4 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 5 Row Height',
		name: 'design5RowHeight',
		defaultValue: '60px',
		description: 'Design 5 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 6 Row Height',
		name: 'design6RowHeight',
		defaultValue: '60px',
		description: 'Design 6 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 7 Row Height',
		name: 'design7RowHeight',
		defaultValue: '40px',
		description: 'Design 7 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 8 Row Height',
		name: 'design8RowHeight',
		defaultValue: '40px',
		description: 'Design 8 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 9 Row Height',
		name: 'design9RowHeight',
		defaultValue: '60px',
		description: 'Design 9 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 10 Row Height',
		name: 'design10RowHeight',
		defaultValue: '60px',
		description: 'Design 10 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},

	{
		groupName: 'Row Background Color',
		displayName: 'Design 1 Row Background Color',
		name: 'design1RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 1 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 2 Row Background Color',
		name: 'design2RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 2 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 3 Row Background Color',
		name: 'design3RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 3 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 4 Row Background Color',
		name: 'design4RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 4 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 5 Row Background Color',
		name: 'design5RowBackgroundColor',
		description: 'Design 5 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 6 Row Background Color',
		name: 'design6RowBackgroundColor',
		description: 'Design 6 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 7 Row Background Color',
		name: 'design7RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 7 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 8 Row Background Color',
		name: 'design8RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 8 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 9 Row Background Color',
		name: 'design9RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 9 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 10 Row Background Color',
		name: 'design10RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 10 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},

	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 1 Even Row Background Color',
		name: 'design1EvenRowBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 1 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 2 Even Row Background Color',
		name: 'design2EvenRowBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 2 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 3 Even Row Background Color',
		name: 'design3EvenRowBackgroundColor',
		description: 'Design 3 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 4 Even Row Background Color',
		name: 'design4EvenRowBackgroundColor',
		description: 'Design 4 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 5 Even Row Background Color',
		name: 'design5EvenRowBackgroundColor',
		description: 'Design 5 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 6 Even Row Background Color',
		name: 'design6EvenRowBackgroundColor',
		description: 'Design 6 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 7 Even Row Background Color',
		name: 'design7EvenRowBackgroundColor',
		description: 'Design 7 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 8 Even Row Background Color',
		name: 'design8EvenRowBackgroundColor',
		description: 'Design 8 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 9 Even Row Background Color',
		name: 'design9EvenRowBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 9 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 10 Even Row Background Color',
		name: 'design10EvenRowBackgroundColor',
		description: 'Design 10 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},

	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 1 Second Row Background Color',
		name: 'design1SecondRowBackgroundColor',
		description: 'Design 1 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 2 Second Row Background Color',
		name: 'design2SecondRowBackgroundColor',
		description: 'Design 2 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 3 Second Row Background Color',
		name: 'design3SecondRowBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 3 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 4 Second Row Background Color',
		name: 'design4SecondRowBackgroundColor',
		description: 'Design 4 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 5 Second Row Background Color',
		name: 'design5SecondRowBackgroundColor',
		description: 'Design 5 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 6 Second Row Background Color',
		name: 'design6SecondRowBackgroundColor',
		description: 'Design 6 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 7 Second Row Background Color',
		name: 'design7SecondRowBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 7 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 8 Second Row Background Color',
		name: 'design8SecondRowBackgroundColor',
		description: 'Design 8 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 9 Second Row Background Color',
		name: 'design9SecondRowBackgroundColor',
		description: 'Design 9 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 10 Second Row Background Color',
		name: 'design10SecondRowBackgroundColor',
		description: 'Design 10 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},

	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 1 Third Row Background Color',
		name: 'design1ThirdRowBackgroundColor',
		description: 'Design 1 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 2 Third Row Background Color',
		name: 'design2ThirdRowBackgroundColor',
		description: 'Design 2 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 3 Third Row Background Color',
		name: 'design3ThirdRowBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 3 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 4 Third Row Background Color',
		name: 'design4ThirdRowBackgroundColor',
		description: 'Design 4 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 5 Third Row Background Color',
		name: 'design5ThirdRowBackgroundColor',
		description: 'Design 5 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 6 Third Row Background Color',
		name: 'design6ThirdRowBackgroundColor',
		description: 'Design 6 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 7 Third Row Background Color',
		name: 'design7ThirdRowBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 7 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 8 Third Row Background Color',
		name: 'design8ThirdRowBackgroundColor',
		description: 'Design 8 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 9 Third Row Background Color',
		name: 'design9ThirdRowBackgroundColor',
		description: 'Design 9 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 10 Third Row Background Color',
		name: 'design10ThirdRowBackgroundColor',
		description: 'Design 10 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},

	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 1 Row Hover Background Color',
		name: 'design1RowHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 1 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design1 ._row._dataRow:hover, .comp.compTable._design1 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 2 Row Hover Background Color',
		name: 'design2RowHoverBackgroundColor',
		description: 'Design 2 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design2 ._row._dataRow:hover, .comp.compTable._design2 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 3 Row HoverBackground Color',
		name: 'design3RowHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 3 Row HoverBackground Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design3 ._row._dataRow:hover, .comp.compTable._design3 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 4 Row HoverBackground Color',
		name: 'design4RowHoverBackgroundColor',
		defaultValue: '#BABABA1A',
		description: 'Design 4 Row HoverBackground Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design4 ._row._dataRow:hover, .comp.compTable._design4 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 5 Row Hover Background Color',
		name: 'design5RowHoverBackgroundColor',
		description: 'Design 5 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design5 ._row._dataRow:hover, .comp.compTable._design5 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 6 Row Hover Background Color',
		name: 'design6RowHoverBackgroundColor',
		description: 'Design 6 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design6 ._row._dataRow:hover, .comp.compTable._design6 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 7 Row Hover Background Color',
		name: 'design7RowHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 7 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design7 ._row._dataRow:hover, .comp.compTable._design7 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 8 Row Hover Background Color',
		name: 'design8RowHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 8 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design8 ._row._dataRow:hover, .comp.compTable._design8 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 9 Row Hover Background Color',
		name: 'design9RowHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 9 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design9 ._row._dataRow:hover, .comp.compTable._design9 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 10 Row Hover Background Color',
		name: 'design10RowHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 10 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design10 ._row._dataRow:hover, .comp.compTable._design10 ._row._dataRow._selected',
		noPrefix: true,
	},

	{
		groupName: 'Row Border ',
		displayName: 'Design 1 Row Border ',
		name: 'design1RowBorder',
		description: 'Design 1 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design1 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 2 Row Border ',
		name: 'design2RowBorder',
		defaultValue: '1px solid #3333330D',
		description: 'Design 2 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design2 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 3 Row Border ',
		name: 'design3RowBorder',
		description: 'Design 3 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design3 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 4 Row Border ',
		name: 'design4RowBorder',
		defaultValue: '1px solid #3333330D',
		description: 'Design 4 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design4 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 5 Row Border ',
		name: 'design5RowBorder',
		defaultValue: '1px solid #3333330D',
		description: 'Design 5 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design5 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 6 Row Border ',
		name: 'design6RowBorder',
		defaultValue: '1px solid #3333330D',
		description: 'Design 6 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design6 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 7 Row Border ',
		name: 'design7RowBorder',
		description: 'Design 7 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design7 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 8 Row Border ',
		name: 'design8RowBorder',
		defaultValue: '1px solid #DBDBDB',
		description: 'Design 8 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design8 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 9 Row Border ',
		name: 'design9RowBorder',
		description: 'Design 9 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design9 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 10 Row Border ',
		name: 'design10RowBorder',
		description: 'Design 10 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design10 .comp.compTableColumns',
		noPrefix: true,
	},

	{
		groupName: 'Row Border Radius',
		displayName: 'Design 1 Row Hover Border Radius',
		name: 'design1RowHoverBorderRadius',
		description: 'Design 1 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design1 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 2 Row Hover Border Radius',
		name: 'design2RowHoverBorderRadius',
		defaultValue: '8px 8px 8px  8px',
		description: 'Design 2 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design2 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 3 Row Hover Border Radius',
		name: 'design3RowHoverBorderRadius',
		description: 'Design 3 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design3 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 4 Row Hover Border Radius',
		name: 'design4RowHoverBorderRadius',
		defaultValue: '8px 8px 8px  8px',
		description: 'Design 4 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design4 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 5 Row Hover Border Radius',
		name: 'design5RowHoverBorderRadius',
		defaultValue: '8px 8px 8px  8px',
		description: 'Design 5 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design5 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 6 Row Hover Border Radius',
		name: 'design6RowHoverBorderRadius',
		defaultValue: '8px 8px 8px  8px',
		description: 'Design 6 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design6 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 7 Row Hover Border Radius',
		name: 'design7RowHoverBorderRadius',
		description: 'Design 7 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design7 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 8 Row Hover Border Radius',
		name: 'design8RowHoverBorderRadius',
		defaultValue: '8px 8px 8px  8px',
		description: 'Design 8 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design8 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 9 Row Hover Border Radius',
		name: 'design9RowHoverBorderRadius',
		description: 'Design 9 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design9 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 10 Row Hover Border Radius',
		name: 'design10RowHoverBorderRadius',
		description: 'Design 10 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design10 .comp.compTableColumns',
		noPrefix: true,
	},

	{
		groupName: 'Row Overflow',
		displayName: 'Design 1 Row Overflow',
		name: 'design1RowOverflow',
		description: 'Design 1 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design1 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 2 Row Overflow',
		name: 'design2RowOverflow',
		defaultValue: 'hidden',
		description: 'Design 2 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design2 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 3 Row Overflow',
		name: 'design3RowOverflow',
		description: 'Design 3 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design3 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 4 Row Overflow',
		name: 'design4RowOverflow',
		defaultValue: 'hidden',
		description: 'Design 4 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design4 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 5 Row Overflow',
		name: 'design5RowOverflow',
		defaultValue: 'hidden',
		description: 'Design 5 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design5 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 6 Row Overflow',
		name: 'design6RowOverflow',
		defaultValue: 'hidden',
		description: 'Design 6 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design6 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 7 Row Overflow',
		name: 'design7RowOverflow',
		description: 'Design 7 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design7 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 8 Row Overflow',
		name: 'design8RowOverflow',
		defaultValue: 'hidden',
		description: 'Design 8 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design8 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 9 Row Overflow',
		name: 'design9RowOverflow',
		description: 'Design 9 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design9 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 10 Row Overflow',
		name: 'design10RowOverflow',
		description: 'Design 10 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design10 .comp.compTableColumns',
		noPrefix: true,
	},

	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 1 Row Selected Box Shadow',
		name: 'design1RowSelectedBoxShadow',
		description: 'Design 1 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design1 ._row._dataRow:hover, .comp.compTable._design1 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 2 Row Selected Box Shadow',
		name: 'design2RowSelectedBoxShadow',
		description: 'Design 2 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design2 ._row._dataRow:hover, .comp.compTable._design2 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 3 Row Selected Box Shadow',
		name: 'design3RowSelectedBoxShadow',
		description: 'Design 3 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design3 ._row._dataRow:hover, .comp.compTable._design3 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 4 Row Selected Box Shadow',
		name: 'design4RowSelectedBoxShadow',
		defaultValue: '0px 3px 10px 0px rgba(0, 0, 0, 0.07)',
		description: 'Design 4 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design4 ._row._dataRow:hover, .comp.compTable._design4 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 5 Row Selected Box Shadow',
		name: 'design5RowSelectedBoxShadow',
		description: 'Design 5 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design5 ._row._dataRow:hover, .comp.compTable._design5 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 6 Row Selected Box Shadow',
		name: 'design6RowSelectedBoxShadow',
		description: 'Design 6 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design6 ._row._dataRow:hover, .comp.compTable._design6 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 7 Row Selected Box Shadow',
		name: 'design7RowSelectedBoxShadow',
		description: 'Design 7 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design7 ._row._dataRow:hover, .comp.compTable._design7 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 8 Row Selected Box Shadow',
		name: 'design8RowSelectedBoxShadow',
		description: 'Design 8 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design8 ._row._dataRow:hover, .comp.compTable._design8 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 9 Row Selected Box Shadow',
		name: 'design9RowSelectedBoxShadow',
		description: 'Design 9 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design9 ._row._dataRow:hover, .comp.compTable._design9 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 10 Row Selected Box Shadow',
		name: 'design10RowSelectedBoxShadow',
		description: 'Design 10 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design10 ._row._dataRow:hover, .comp.compTable._design10 ._row._dataRow._selected',
		noPrefix: true,
	},

	{
		groupName: 'Row Hover Background Color',
		displayName: 'Row Hover Background Color Primary Design2',
		name: 'rowHoverBackgroundColorPrimaryDesign2',
		defaultValue: '<backgroundHoverColorOne>',
		description: 'Row Hover Background Color Primary Design2',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design2._primary ._row._dataRow:hover, .comp.compTable._design2._primary ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Row Hover Background Color SecondaryDesign2',
		name: 'rowHoverBackgroundColorSecondaryDesign2',
		defaultValue: '<backgroundHoverColorTwo>',
		description: 'Row Hover Background Color SecondaryDesign2',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design2._secondary ._row._dataRow:hover, .comp.compTable._design2._secondary ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Row Hover Background Color TertiaryDesign2',
		name: 'rowHoverBackgroundColorTertiaryDesign2',
		defaultValue: '<backgroundHoverColorThree>',
		description: 'Row Hover Background Color TertiaryDesign2',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design2._teritiary ._row._dataRow:hover, .comp.compTable._design2._teritiary ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Row Hover Background Color QuaternaryDesign2',
		name: 'rowHoverBackgroundColorQuaternaryDesign2',
		defaultValue: '<backgroundHoverColorFour>',
		description: 'Row Hover Background Color QuaternaryDesign2',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design2._quaternary ._row._dataRow:hover, .comp.compTable._design2._quaternary ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Row Hover Background Color QuinaryDesign2',
		name: 'rowHoverBackgroundColorQuinaryDesign2',
		defaultValue: '<backgroundHoverColorFive>',
		description: 'Row Hover Background Color QuinaryDesign2',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design2._quinary ._row._dataRow:hover, .comp.compTable._design2._quinary ._row._dataRow._selected',
		noPrefix: true,
	},

	{
		groupName: 'Column Background Color',
		displayName: 'Design 1 Column Background Color',
		name: 'design1ColumnBackgroundColor',
		description: 'Design 1 Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Column Background Color',
		displayName: 'Design 2 Column Background Color',
		name: 'design2ColumnBackgroundColor',
		description: 'Design 2 Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Column Background Color',
		displayName: 'Design 3 Column Background Color',
		name: 'design3ColumnBackgroundColor',
		description: 'Design 3 Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Column Background Color',
		displayName: 'Design 4 Column Background Color',
		name: 'design4ColumnBackgroundColor',
		description: 'Design 4 Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Column Background Color',
		displayName: 'Design 5 Column Background Color',
		name: 'design5ColumnBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 5 Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Column Background Color',
		displayName: 'Design 6 Column Background Color',
		name: 'design6ColumnBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 6 Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Column Background Color',
		displayName: 'Design 7 Column Background Color',
		name: 'design7ColumnBackgroundColor',
		description: 'Design 7 Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Column Background Color',
		displayName: 'Design 8 Column Background Color',
		name: 'design8ColumnBackgroundColor',
		description: 'Design 8 Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Column Background Color',
		displayName: 'Design 9 Column Background Color',
		name: 'design9ColumnBackgroundColor',
		description: 'Design 9 Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Column Background Color',
		displayName: 'Design 10 Column Background Color',
		defaultValue: '#FFFFFF',
		name: 'design10ColumnBackgroundColor',
		description: 'Design 10 Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},

	{
		groupName: 'Even Column Background Color',
		displayName: 'Design 1 Even Column Background Color',
		name: 'design1EvenColumnBackgroundColor',
		description: 'Design 1 Even Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Column Background Color',
		displayName: 'Design 2 Even Column Background Color',
		name: 'design2EvenColumnBackgroundColor',
		description: 'Design 2 Even Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Column Background Color',
		displayName: 'Design 3 Even Column Background Color',
		name: 'design3EvenColumnBackgroundColor',
		description: 'Design 3 Even Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Column Background Color',
		displayName: 'Design 4 Even Column Background Color',
		name: 'design4EvenColumnBackgroundColor',
		description: 'Design 4 Even Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Column Background Color',
		displayName: 'Design 5 Even Column Background Color',
		name: 'design5EvenColumnBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 5 Even Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Column Background Color',
		displayName: 'Design 6 Even Column Background Color',
		name: 'design6EvenColumnBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 6 Even Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Column Background Color',
		displayName: 'Design 7 Even Column Background Color',
		name: 'design7EvenColumnBackgroundColor',
		description: 'Design 7 Even Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Column Background Color',
		displayName: 'Design 8 Even Column Background Color',
		name: 'design8EvenColumnBackgroundColor',
		description: 'Design 8 Even Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Column Background Color',
		displayName: 'Design 9 Even Column Background Color',
		name: 'design9EvenColumnBackgroundColor',
		description: 'Design 9 Even Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Column Background Color',
		displayName: 'Design 10 Even Column Background Color',
		name: 'design10EvenColumnBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 10 Even Column Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},

	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 1 Column Hover Background Color',
		name: 'design1ColumnHoverBackgroundColor',
		description: 'Design 1 Column Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design1 ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design1 ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 2 Column Hover Background Color',
		name: 'design2ColumnHoverBackgroundColor',
		description: 'Design 2 Column Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design2 ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design2 ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 3 Column HoverBackground Color',
		name: 'design3ColumnHoverBackgroundColor',
		description: 'Design 3 Column HoverBackground Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design3 ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design3 ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 4 Column HoverBackground Color',
		name: 'design4ColumnHoverBackgroundColor',
		description: 'Design 4 Column HoverBackground Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design4 ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design4 ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 5 Column Hover Background Color',
		name: 'design5ColumnHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 5 Column Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design5 ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design5 ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 6 Column Hover Background Color',
		name: 'design6ColumnHoverBackgroundColor',
		description: 'Design 6 Column Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design6 ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design6 ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 7 Column Hover Background Color',
		name: 'design7ColumnHoverBackgroundColor',
		description: 'Design 7 Column Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design7 ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design7 ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 8 Column Hover Background Color',
		name: 'design8ColumnHoverBackgroundColor',
		description: 'Design 8 Column Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design8 ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design8 ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 9 Column Hover Background Color',
		name: 'design9ColumnHoverBackgroundColor',
		description: 'Design 9 Column Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design9 ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design9 ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 10 Column Hover Background Color',
		name: 'design10ColumnHoverBackgroundColor',
		description: 'Design 10 Column Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design10 ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design10 ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},

	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 6 Column Hover Background Color Primary',
		name: 'design6ColumnHoverBackgroundColorPrimary',
		defaultValue: '<backgroundHoverColorOne>',
		description: 'Design 6 Column Hover Background Color Primary',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design6._primary ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design6._primary ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 6 Column Hover Background Color Secondary',
		name: 'design6ColumnHoverBackgroundColorSecondary',
		defaultValue: '<backgroundHoverColorTwo>',
		description: 'Design 6 Column Hover Background Color Secondary',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design6._secondary ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design6._secondary ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 6 Column Hover Background Color Tertiary',
		name: 'design6ColumnHoverBackgroundColorTeritiary',
		defaultValue: '<backgroundHoverColorThree>',
		description: 'Design 6 Column Hover Background Color Tertiary',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design6._tertiary ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design6._tertiary ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 6 Column Hover Background Color Quaternary',
		name: 'design6ColumnHoverBackgroundColorQuaternary',
		defaultValue: '<backgroundHoverColorFour>',
		description: 'Design 6 Column Hover Background Color Quaternary',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design6._quaternary ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design6._quaternary  ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 6 Column Hover Background Color Quinary',
		name: 'design6ColumnHoverBackgroundColorQuinary',
		defaultValue: '<backgroundHoverColorFive>',
		description: 'Design 6 Column Hover Background Color Quinary',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design6._quinary ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design6._quinary ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},

	{
		groupName: 'Row Border-Right LastChild',
		displayName: 'Design 1 Row Border-Right LastChild',
		name: 'design1RowBorder-RightLastChild',
		description: 'Design 1 Row Border-Right LastChild',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design1 .comp.compTableColumn:last-child',
		noPrefix: true,
	},
	{
		groupName: 'Row Border-Right LastChild',
		displayName: 'Design 2 Row Border-Right LastChild',
		name: 'design2RowBorder-RightLastChild',
		description: 'Design 2 Row Border-Right LastChild',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design2 .comp.compTableColumn:last-child',
		noPrefix: true,
	},
	{
		groupName: 'Row Border-Right LastChild',
		displayName: 'Design 3 Row Border-Right LastChild',
		name: 'design3RowBorder-RightLastChild',
		description: 'Design 3 Row Border-Right LastChild',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design3 .comp.compTableColumn:last-child',
		noPrefix: true,
	},
	{
		groupName: 'Row Border-Right LastChild',
		displayName: 'Design 4 Row Border-Right LastChild',
		name: 'design4RowBorder-RightLastChild',
		description: 'Design 4 Row Border-Right LastChild',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design4 .comp.compTableColumn:last-child',
		noPrefix: true,
	},
	{
		groupName: 'Row Border-Right LastChild',
		displayName: 'Design 5 Row Border-Right LastChild',
		name: 'design5RowBorder-RightLastChild',
		description: 'Design 5 Row Border-Right LastChild',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design5 .comp.compTableColumn:last-child',
		noPrefix: true,
	},
	{
		groupName: 'Row Border-Right LastChild',
		displayName: 'Design 6 Row Border-Right LastChild',
		name: 'design6RowBorder-RightLastChild',
		description: 'Design 6 Row Border-Right LastChild',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design6 .comp.compTableColumn:last-child',
		noPrefix: true,
	},
	{
		groupName: 'Row Border-Right LastChild',
		displayName: 'Design 7 Row Border-Right LastChild',
		name: 'design7RowBorder-RightLastChild',
		defaultValue: 'none',
		description: 'Design 7 Row Border-Right LastChild',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design7 .comp.compTableColumn:last-child',
		noPrefix: true,
	},
	{
		groupName: 'Row Border-Right LastChild',
		displayName: 'Design 8 Row Border-Right LastChild',
		name: 'design8RowBorder-RightLastChild',
		defaultValue: 'none',
		description: 'Design 8 Row Border-Right LastChild',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design8 .comp.compTableColumn:last-child',
		noPrefix: true,
	},
	{
		groupName: 'Row Border-Right LastChild',
		displayName: 'Design 9 Row Border-Right LastChild',
		name: 'design9RowBorder-RightLastChild',
		description: 'Design 9 Row Border-Right LastChild',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design9 .comp.compTableColumn:last-child',
		noPrefix: true,
	},
	{
		groupName: 'Row Border-Right LastChild',
		displayName: 'Design 10 Row Border-Right LastChild',
		name: 'design10RowBorder-RightLastChild',
		description: 'Design 10 Row Border-Right LastChild',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design10 .comp.compTableColumn:last-child',
		noPrefix: true,
	},

	{
		groupName: 'Column Border Bottom Last Child',
		displayName: 'Design 1 Column Border Bottom Last Child',
		name: 'design1ColumnBorderBottomLastChild',
		description: 'Design 1 Column Border Bottom Last Child',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design1 ._row:last-child .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom Last Child',
		displayName: 'Design 2 Column Border Bottom Last Child',
		name: 'design2ColumnBorderBottomLastChild',
		description: 'Design 2 Column Border Bottom Last Child',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design2 ._row:last-child .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom Last Child',
		displayName: 'Design 3 Column Border Bottom Last Child',
		name: 'design3ColumnBorderBottomLastChild',
		description: 'Design 3 Column Border Bottom Last Child',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design3 ._row:last-child .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom Last Child',
		displayName: 'Design 4 Column Border Bottom Last Child',
		name: 'design4ColumnBorderBottomLastChild',
		description: 'Design 4 Column Border Bottom Last Child',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design4 ._row:last-child .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom Last Child',
		displayName: 'Design 5 Column Border Bottom Last Child',
		name: 'design5ColumnBorderBottomLastChild',
		description: 'Design 5 Column Border Bottom Last Child',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design5 ._row:last-child .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom Last Child',
		displayName: 'Design 6 Column Border Bottom Last Child',
		name: 'design6ColumnBorderBottomLastChild',
		description: 'Design 6 Column Border Bottom Last Child',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design6 ._row:last-child .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom Last Child',
		displayName: 'Design 7 Column Border Bottom Last Child',
		name: 'design7ColumnBorderBottomLastChild',
		defaultValue: 'none',
		description: 'Design 7 Column Border Bottom Last Child',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design7 ._row:last-child .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom Last Child',
		displayName: 'Design 8 Column Border Bottom Last Child',
		name: 'design8ColumnBorderBottomLastChild',
		defaultValue: 'none',
		description: 'Design 8 Column Border Bottom Last Child',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design8 ._row:last-child .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom Last Child',
		displayName: 'Design 9 Column Border Bottom Last Child',
		name: 'design9ColumnBorderBottomLastChild',
		description: 'Design 9 Column Border Bottom Last Child',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design9 ._row:last-child .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Border Bottom Last Child',
		displayName: 'Design 10 Column Border Bottom Last Child',
		name: 'design10ColumnBorderBottomLastChild',
		description: 'Design 10 Column Border Bottom Last Child',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design10 ._row:last-child .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Row Hover Background Color Primary Design8',
		name: 'rowHoverBackgroundColorPrimaryDesign8',
		defaultValue: '<backgroundHoverColorOne>',
		description: 'Row Hover Background Color Primary Design8',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design8._primary ._row._dataRow:hover, .comp.compTable._design8._primary ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Row Hover Background Color SecondaryDesign8',
		name: 'rowHoverBackgroundColorSecondaryDesign8',
		defaultValue: '<backgroundHoverColorTwo>',
		description: 'Row Hover Background Color SecondaryDesign8',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design8._secondary ._row._dataRow:hover, .comp.compTable._design8._secondary ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Row Hover Background Color TertiaryDesign8',
		name: 'rowHoverBackgroundColorTertiaryDesign8',
		defaultValue: '<backgroundHoverColorThree>',
		description: 'Row Hover Background Color TertiaryDesign8',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design8._tertiary ._row._dataRow:hover, .comp.compTable._design8._tertiary ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Row Hover Background Color QuaternaryDesign8',
		name: 'rowHoverBackgroundColorQuaternaryDesign8',
		defaultValue: '<backgroundHoverColorFour>',
		description: 'Row Hover Background Color QuaternaryDesign8',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design8._quaternary ._row._dataRow:hover, .comp.compTable._design8._quaternary ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Row Hover Background Color QuinaryDesign8',
		name: 'rowHoverBackgroundColorQuinaryDesign8',
		defaultValue: '<backgroundHoverColorFive>',
		description: 'Row Hover Background Color QuinaryDesign8',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design8._quinary ._row._dataRow:hover, .comp.compTable._design8._quinary ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 9 Even Row Background Color Primary',
		name: 'design9EvenRowBackgroundColorPrimary',
		defaultValue: '#A8DEC933',
		description: 'Design 9 Even Row Background Color Primary',
		cssProperty: 'background-color',
		selector: '.comp.compTable._design9._primary ._row:nth-child(odd)',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 9 Even Row Background Color Secondary',
		name: 'design9EvenRowBackgroundColorSecondary',
		defaultValue: '#81B7AB33',
		description: 'Design 9 Even Row Background Color Secondary',
		cssProperty: 'background-color',
		selector: '.comp.compTable._design9._secondary ._row:nth-child(odd)',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 9 Even Row Background Color Tertiary',
		name: 'design9EvenRowBackgroundColorTertiary',
		defaultValue: '#FFE19333',
		description: 'Design 9 Even Row Background Color Tertiary',
		cssProperty: 'background-color',
		selector: '.comp.compTable._design9._tertiary ._row:nth-child(odd)',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 9 Even Row Background Color Quaternary',
		name: 'design9EvenRowBackgroundColorQuaternary',
		defaultValue: '#F3B4AE33',
		description: 'Design 9 Even Row Background Color Quaternary',
		cssProperty: 'background-color',
		selector: '.comp.compTable._design9._quaternary ._row:nth-child(odd)',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 9 Even Row Background Color Quinary',
		name: 'design9EvenRowBackgroundColorQuinary',
		defaultValue: '#A5BDF633',
		description: 'Design 9 Even Row Background Color Quinary',
		cssProperty: 'background-color',
		selector: '.comp.compTable._design9._quinary ._row:nth-child(odd)',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Row Hover Background Color Primary Design9',
		name: 'rowHoverBackgroundColorPrimaryDesign9',
		defaultValue: '<backgroundHoverColorOne>',
		description: 'Row Hover Background Color Primary Design9',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design9._primary ._row._dataRow:hover, .comp.compTable._design9._primary ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Row Hover Background Color SecondaryDesign9',
		name: 'rowHoverBackgroundColorSecondaryDesign9',
		defaultValue: '<backgroundHoverColorTwo>',
		description: 'Row Hover Background Color SecondaryDesign9',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design9._secondary ._row._dataRow:hover, .comp.compTable._design9._secondary ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Row Hover Background Color TertiaryDesign9',
		name: 'rowHoverBackgroundColorTertiaryDesign9',
		defaultValue: '<backgroundHoverColorThree>',
		description: 'Row Hover Background Color TertiaryDesign9',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design9._tertiary ._row._dataRow:hover, .comp.compTable._design9._tertiary ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Row Hover Background Color QuaternaryDesign9',
		name: 'rowHoverBackgroundColorQuaternaryDesign9',
		defaultValue: '<backgroundHoverColorFour>',
		description: 'Row Hover Background Color QuaternaryDesign9',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design9._quaternary ._row._dataRow:hover, .comp.compTable._design9._quaternary ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Row Hover Background Color QuinaryDesign9',
		name: 'rowHoverBackgroundColorQuinaryDesign9',
		defaultValue: '<backgroundHoverColorFive>',
		description: 'Row Hover Background Color QuinaryDesign9',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design9._quinary ._row._dataRow:hover, .comp.compTable._design9._quinary ._row._dataRow._selected',
		noPrefix: true,
	},

	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 10 Column Hover Background Color Primary',
		name: 'design10ColumnHoverBackgroundColorPrimary',
		defaultValue: '<backgroundHoverColorOne>',
		description: 'Design 10 Column Hover Background Color Primary',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design10._primary ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design10._primary ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 10 Column Hover Background Color Secondary',
		name: 'design10ColumnHoverBackgroundColorSecondary',
		defaultValue: '<backgroundHoverColorTwo>',
		description: 'Design 10 Column Hover Background Color Secondary',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design10._secondary ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design10._secondary ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 10 Column Hover Background Color tertiary',
		name: 'design10ColumnHoverBackgroundColortertiary',
		defaultValue: '<backgroundHoverColorThree>',
		description: 'Design 10 Column Hover Background Color tertiary',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design10._tertiary ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design10._tertiary ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 10 Column Hover Background Color Quaternary',
		name: 'design10ColumnHoverBackgroundColorQuaternary',
		defaultValue: '<backgroundHoverColorFour>',
		description: 'Design 10 Column Hover Background Color Quaternary',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design10._quaternary ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design10._quaternary  ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Column Hover Background Color',
		displayName: 'Design 10 Column Hover Background Color Quinary',
		name: 'design10ColumnHoverBackgroundColorQuinary',
		defaultValue: '<backgroundHoverColorFive>',
		description: 'Design 10 Column Hover Background Color Quinary',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design10._quinary ._row._dataRow:hover .comp.compTableColumn, .comp.compTable._design10._quinary ._row._dataRow._selected .comp.compTableColumn',
		noPrefix: true,
	},
	{
		groupName: 'Odd Column Background Color',
		displayName: 'Design 9 Odd Column Background Color Primary',
		name: 'design9OddColumnBackgroundColorPrimary',
		defaultValue: '#A8DEC933',
		description: 'Design 9 Odd Column Background Color Primary',
		cssProperty: 'background-color',
		selector: '.comp.compTable._design10._primary .comp.compTableColumn:nth-child(odd)',
		noPrefix: true,
	},
	{
		groupName: 'Odd Column Background Color',
		displayName: 'Design 9 Odd Column Background Color Secondary',
		name: 'design9OddColumnBackgroundColorSecondary',
		defaultValue: '#81B7AB33',
		description: 'Design 9 Odd Column Background Color Secondary',
		cssProperty: 'background-color',
		selector: '.comp.compTable._design10._secondary .comp.compTableColumn:nth-child(odd)',
		noPrefix: true,
	},
	{
		groupName: 'Odd Column Background Color',
		displayName: 'Design 9 Odd Column Background Color Tertiary',
		name: 'design9OddColumnBackgroundColorTertiary',
		defaultValue: '#FFE19333',
		description: 'Design 9 Odd Column Background Color Tertiary',
		cssProperty: 'background-color',
		selector: '.comp.compTable._design10._tertiary .comp.compTableColumn:nth-child(odd)',
		noPrefix: true,
	},
	{
		groupName: 'Odd Column Background Color',
		displayName: 'Design 9 Odd Column Background Color Quaternary',
		name: 'design9OddColumnBackgroundColorQuaternary',
		defaultValue: '#F3B4AE33',
		description: 'Design 9 Odd Column Background Color Quaternary',
		cssProperty: 'background-color',
		selector: '.comp.compTable._design10._quaternary .comp.compTableColumn:nth-child(odd)',
		noPrefix: true,
	},
	{
		groupName: 'Odd Column Background Color',
		displayName: 'Design 9 Odd Column Background Color Quinary',
		name: 'design9OddColumnBackgroundColorQuinary',
		defaultValue: '#A5BDF633',
		description: 'Design 9 Odd Column Background Color Quinary',
		cssProperty: 'background-color',
		selector: '.comp.compTable._design10._quinary .comp.compTableColumn:nth-child(odd)',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
