import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'Row Height',
		displayName: 'Design 1 Row Height',
		name: 'design1RowHeight',
		defaultValue: '60px',
		description: 'Design 1 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 2 Row Height',
		name: 'design2RowHeight',
		defaultValue: '30px',
		description: 'Design 2 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 3 Row Height',
		name: 'design3RowHeight',
		defaultValue: '60px',
		description: 'Design 3 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 4 Row Height',
		name: 'design4RowHeight',
		defaultValue: '68px',
		description: 'Design 4 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 5 Row Height',
		name: 'design5RowHeight',
		defaultValue: '60px',
		description: 'Design 5 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 6 Row Height',
		name: 'design6RowHeight',
		defaultValue: '30px',
		description: 'Design 6 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 7 Row Height',
		name: 'design7RowHeight',
		defaultValue: '60px',
		description: 'Design 7 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 8 Row Height',
		name: 'design8RowHeight',
		defaultValue: '30px',
		description: 'Design 8 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 9 Row Height',
		name: 'design9RowHeight',
		defaultValue: '60px',
		description: 'Design 9 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},
	{
		groupName: 'Row Height',
		displayName: 'Design 10 Row Height',
		name: 'design10RowHeight',
		defaultValue: '30px',
		description: 'Design 10 Row Height',
		cssProperty: 'height',
		noPrefix: true,
	},

	{
		groupName: 'Row Background Color',
		displayName: 'Design 1 Row Background Color',
		name: 'design1RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 1 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 2 Row Background Color',
		name: 'design2RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 2 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 3 Row Background Color',
		name: 'design3RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 3 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 4 Row Background Color',
		name: 'design4RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 4 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 5 Row Background Color',
		name: 'design5RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 5 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 6 Row Background Color',
		name: 'design6RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 6 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 7 Row Background Color',
		name: 'design7RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 7 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 8 Row Background Color',
		name: 'design8RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 8 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 9 Row Background Color',
		name: 'design9RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 9 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Row Background Color',
		displayName: 'Design 10 Row Background Color',
		name: 'design10RowBackgroundColor',
		defaultValue: '#FFFFFF',
		description: 'Design 10 Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},

	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 1 Even Row Background Color',
		name: 'design1EvenRowBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 1 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 2 Even Row Background Color',
		name: 'design2EvenRowBackgroundColor',
		description: 'Design 2 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 3 Even Row Background Color',
		name: 'design3EvenRowBackgroundColor',
		description: 'Design 3 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 4 Even Row Background Color',
		name: 'design4EvenRowBackgroundColor',
		description: 'Design 4 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 5 Even Row Background Color',
		name: 'design5EvenRowBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 5 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 6 Even Row Background Color',
		name: 'design6EvenRowBackgroundColor',
		description: 'Design 6 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 7 Even Row Background Color',
		name: 'design7EvenRowBackgroundColor',
		description: 'Design 7 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 8 Even Row Background Color',
		name: 'design8EvenRowBackgroundColor',
		description: 'Design 8 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 9 Even Row Background Color',
		name: 'design9EvenRowBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 9 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Even Row Background Color',
		displayName: 'Design 10 Even Row Background Color',
		name: 'design10EvenRowBackgroundColor',
		description: 'Design 10 Even Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},

	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 1 Second Row Background Color',
		name: 'design1SecondRowBackgroundColor',
		description: 'Design 1 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 2 Second Row Background Color',
		name: 'design2SecondRowBackgroundColor',
		description: 'Design 2 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 3 Second Row Background Color',
		name: 'design3SecondRowBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 3 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 4 Second Row Background Color',
		name: 'design4SecondRowBackgroundColor',
		description: 'Design 4 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 5 Second Row Background Color',
		name: 'design5SecondRowBackgroundColor',
		description: 'Design 5 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 6 Second Row Background Color',
		name: 'design6SecondRowBackgroundColor',
		description: 'Design 6 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 7 Second Row Background Color',
		name: 'design7SecondRowBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 7 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 8 Second Row Background Color',
		name: 'design8SecondRowBackgroundColor',
		description: 'Design 8 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 9 Second Row Background Color',
		name: 'design9SecondRowBackgroundColor',
		description: 'Design 9 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Second Row Background Color',
		displayName: 'Design 10 Second Row Background Color',
		name: 'design10SecondRowBackgroundColor',
		description: 'Design 10 Second Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},

	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 1 Third Row Background Color',
		name: 'design1ThirdRowBackgroundColor',
		description: 'Design 1 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 2 Third Row Background Color',
		name: 'design2ThirdRowBackgroundColor',
		description: 'Design 2 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 3 Third Row Background Color',
		name: 'design3ThirdRowBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 3 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 4 Third Row Background Color',
		name: 'design4ThirdRowBackgroundColor',
		description: 'Design 4 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 5 Third Row Background Color',
		name: 'design5ThirdRowBackgroundColor',
		description: 'Design 5 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 6 Third Row Background Color',
		name: 'design6ThirdRowBackgroundColor',
		description: 'Design 6 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 7 Third Row Background Color',
		name: 'design7ThirdRowBackgroundColor',
		defaultValue: '#F6F6F6',
		description: 'Design 7 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 8 Third Row Background Color',
		name: 'design8ThirdRowBackgroundColor',
		description: 'Design 8 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 9 Third Row Background Color',
		name: 'design9ThirdRowBackgroundColor',
		description: 'Design 9 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},
	{
		groupName: 'Third Row Background Color',
		displayName: 'Design 10 Third Row Background Color',
		name: 'design10ThirdRowBackgroundColor',
		description: 'Design 10 Third Row Background Color',
		cssProperty: 'background-color',
		noPrefix: true,
	},

	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 1 Row Hover Background Color',
		name: 'design1RowHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 1 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design1 ._row._dataRow:hover, .comp.compTable._design1 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 2 Row Hover Background Color',
		name: 'design2RowHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 2 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design2 ._row._dataRow:hover, .comp.compTable._design2 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 3 Row HoverBackground Color',
		name: 'design3RowHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 3 Row HoverBackground Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design3 ._row._dataRow:hover, .comp.compTable._design3 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 4 Row HoverBackground Color',
		name: 'design4RowHoverBackgroundColor',
		defaultValue: '#BABABA1A',
		description: 'Design 4 Row HoverBackground Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design4 ._row._dataRow:hover, .comp.compTable._design4 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 5 Row Hover Background Color',
		name: 'design5RowHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 5 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design5 ._row._dataRow:hover, .comp.compTable._design5 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 6 Row Hover Background Color',
		name: 'design6RowHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 6 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design6 ._row._dataRow:hover, .comp.compTable._design6 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 7 Row Hover Background Color',
		name: 'design7RowHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 7 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design7 ._row._dataRow:hover, .comp.compTable._design7 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 8 Row Hover Background Color',
		name: 'design8RowHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 8 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design8 ._row._dataRow:hover, .comp.compTable._design8 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 9 Row Hover Background Color',
		name: 'design9RowHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 9 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design9 ._row._dataRow:hover, .comp.compTable._design9 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Hover Background Color',
		displayName: 'Design 10 Row Hover Background Color',
		name: 'design10RowHoverBackgroundColor',
		defaultValue: '#EEEEEE',
		description: 'Design 10 Row Hover Background Color',
		cssProperty: 'background-color',
		selector:
			'.comp.compTable._design10 ._row._dataRow:hover, .comp.compTable._design10 ._row._dataRow._selected',
		noPrefix: true,
	},

	{
		groupName: 'Row Border ',
		displayName: 'Design 1 Row Border ',
		name: 'design1RowBorder',
		description: 'Design 1 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design1 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 2 Row Border ',
		name: 'design2RowBorder',
		description: 'Design 2 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design2 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 3 Row Border ',
		name: 'design3RowBorder',
		description: 'Design 3 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design3 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 4 Row Border ',
		name: 'design4RowBorder',
		defaultValue: '1px solid #3333330D',
		description: 'Design 4 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design4 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 5 Row Border ',
		name: 'design5RowBorder',
		description: 'Design 5 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design5 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 6 Row Border ',
		name: 'design6RowBorder',
		description: 'Design 6 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design6 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 7 Row Border ',
		name: 'design7RowBorder',
		description: 'Design 7 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design7 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 8 Row Border ',
		name: 'design8RowBorder',
		description: 'Design 8 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design8 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 9 Row Border ',
		name: 'design9RowBorder',
		description: 'Design 9 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design9 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border ',
		displayName: 'Design 10 Row Border ',
		name: 'design10RowBorder',
		description: 'Design 10 Row Border ',
		cssProperty: 'border',
		selector: '.comp.compTable._design10 .comp.compTableColumns',
		noPrefix: true,
	},

	{
		groupName: 'Row Border Radius',
		displayName: 'Design 1 Row Hover Border Radius',
		name: 'design1RowHoverBorderRadius',
		description: 'Design 1 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design1 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 2 Row Hover Border Radius',
		name: 'design2RowHoverBorderRadius',
		description: 'Design 2 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design2 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 3 Row Hover Border Radius',
		name: 'design3RowHoverBorderRadius',
		description: 'Design 3 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design3 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 4 Row Hover Border Radius',
		name: 'design4RowHoverBorderRadius',
		defaultValue: '8px 8px 8px  8px',
		description: 'Design 4 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design4 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 5 Row Hover Border Radius',
		name: 'design5RowHoverBorderRadius',
		description: 'Design 5 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design5 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 6 Row Hover Border Radius',
		name: 'design6RowHoverBorderRadius',
		description: 'Design 6 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design6 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 7 Row Hover Border Radius',
		name: 'design7RowHoverBorderRadius',
		description: 'Design 7 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design7 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 8 Row Hover Border Radius',
		name: 'design8RowHoverBorderRadius',
		description: 'Design 8 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design8 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 9 Row Hover Border Radius',
		name: 'design9RowHoverBorderRadius',
		description: 'Design 9 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design9 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Border Radius',
		displayName: 'Design 10 Row Hover Border Radius',
		name: 'design10RowHoverBorderRadius',
		description: 'Design 10 Row Hover Border Radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTable._design10 .comp.compTableColumns',
		noPrefix: true,
	},

	{
		groupName: 'Row Overflow',
		displayName: 'Design 1 Row Overflow',
		name: 'design1RowOverflow',
		description: 'Design 1 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design1 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 2 Row Overflow',
		name: 'design2RowOverflow',
		description: 'Design 2 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design2 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 3 Row Overflow',
		name: 'design3RowOverflow',
		description: 'Design 3 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design3 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 4 Row Overflow',
		name: 'design4RowOverflow',
		defaultValue: 'hidden',
		description: 'Design 4 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design4 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 5 Row Overflow',
		name: 'design5RowOverflow',
		description: 'Design 5 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design5 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 6 Row Overflow',
		name: 'design6RowOverflow',
		description: 'Design 6 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design6 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 7 Row Overflow',
		name: 'design7RowOverflow',
		description: 'Design 7 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design7 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 8 Row Overflow',
		name: 'design8RowOverflow',
		description: 'Design 8 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design8 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 9 Row Overflow',
		name: 'design9RowOverflow',
		description: 'Design 9 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design9 .comp.compTableColumns',
		noPrefix: true,
	},
	{
		groupName: 'Row Overflow',
		displayName: 'Design 10 Row Overflow',
		name: 'design10RowOverflow',
		description: 'Design 10 Row Hover  Overflow',
		cssProperty: 'overflow',
		selector: '.comp.compTable._design10 .comp.compTableColumns',
		noPrefix: true,
	},

	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 1 Row Selected Box Shadow',
		name: 'design1RowSelectedBoxShadow',
		description: 'Design 1 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design1 ._row._dataRow:hover, .comp.compTable._design1 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 2 Row Selected Box Shadow',
		name: 'design2RowSelectedBoxShadow',
		description: 'Design 2 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design2 ._row._dataRow:hover, .comp.compTable._design2 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 3 Row Selected Box Shadow',
		name: 'design3RowSelectedBoxShadow',
		description: 'Design 3 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design3 ._row._dataRow:hover, .comp.compTable._design3 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 4 Row Selected Box Shadow',
		name: 'design4RowSelectedBoxShadow',
		defaultValue: '0px 3px 10px 0px rgba(0, 0, 0, 0.07)',
		description: 'Design 4 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design4 ._row._dataRow:hover, .comp.compTable._design4 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 5 Row Selected Box Shadow',
		name: 'design5RowSelectedBoxShadow',
		description: 'Design 5 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design5 ._row._dataRow:hover, .comp.compTable._design5 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 6 Row Selected Box Shadow',
		name: 'design6RowSelectedBoxShadow',
		description: 'Design 6 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design6 ._row._dataRow:hover, .comp.compTable._design6 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 7 Row Selected Box Shadow',
		name: 'design7RowSelectedBoxShadow',
		description: 'Design 7 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design7 ._row._dataRow:hover, .comp.compTable._design7 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 8 Row Selected Box Shadow',
		name: 'design8RowSelectedBoxShadow',
		description: 'Design 8 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design8 ._row._dataRow:hover, .comp.compTable._design8 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 9 Row Selected Box Shadow',
		name: 'design9RowSelectedBoxShadow',
		description: 'Design 9 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design9 ._row._dataRow:hover, .comp.compTable._design9 ._row._dataRow._selected',
		noPrefix: true,
	},
	{
		groupName: 'Row Selected Box Shadow',
		displayName: 'Design 10 Row Selected Box Shadow',
		name: 'design10RowSelectedBoxShadow',
		description: 'Design 10 Row Selected Box Shadow',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compTable._design10 ._row._dataRow:hover, .comp.compTable._design10 ._row._dataRow._selected',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
