import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: '',
		displayName: 'Text Box Font',
		name: 'textBoxFont',
		defaultValue: '<primaryFont>',
		description: 'Default font of the text box',
		cssProperty: '',
		selector: '',
		noPrefix: false,
	},

	{
		groupName: 'Default',
		displayName: 'Default Text Box Font',
		name: 'defaultTextBoxFont',
		defaultValue: '<textBoxFont>',
		description: 'Default design font',
		cssProperty: 'font',
		selector: '.comp.compTextBox._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Text Box Font',
		name: 'outlineTextBoxFont',
		defaultValue: '<textBoxFont>',
		description: 'Outline design font',
		cssProperty: 'font',
		selector: '.comp.compTextBox._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Text Box Font',
		name: 'filledTextBoxFont',
		defaultValue: '<textBoxFont>',
		description: 'Filled design font',
		cssProperty: 'font',
		selector: '.comp.compTextBox._filled',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Text Box Font',
		name: 'bigdesign1TextBoxFont',
		defaultValue: '<textBoxFont>',
		description: 'Big Design 1 design font',
		cssProperty: 'font',
		selector: '.comp.compTextBox._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Text Box Font Color',
		name: 'defaultTextBoxFontColor',
		defaultValue: '<fontColorOne>',
		description: 'Default design font color',
		cssProperty: 'color',
		selector: '.comp.compTextBox._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Text Box Font Color',
		name: 'outlineTextBoxFontColor',
		defaultValue: '<fontColorOne>',
		description: 'Outline design font color',
		cssProperty: 'color',
		selector: '.comp.compTextBox._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Text Box Font Color',
		name: 'filledTextBoxFontColor',
		defaultValue: '<fontColorOne>',
		description: 'Filled design font color',
		cssProperty: 'color',
		selector: '.comp.compTextBox._filled',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Text Box Font Color',
		name: 'bigdesign1TextBoxFontColor',
		defaultValue: '<fontColorOne>',
		description: 'Big Design 1 design font color',
		cssProperty: 'color',
		selector: '.comp.compTextBox._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Text Box Label Font',
		name: 'defaultTextBoxLabelFont',
		defaultValue: '<quaternaryFont>',
		description: 'Default design label font',
		cssProperty: 'font',
		selector: '.comp.compTextBox._default ._label',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Text Box Label Font',
		name: 'outlineTextBoxLabelFont',
		defaultValue: '<quaternaryFont>',
		description: 'Outline design label font',
		cssProperty: 'font',
		selector: '.comp.compTextBox._outlined ._label',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Text Box Label Font',
		name: 'filledTextBoxLabelFont',
		defaultValue: '<quaternaryFont>',
		description: 'Filled design label font',
		cssProperty: 'font',
		selector: '.comp.compTextBox._filled ._label',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Text Box Label Font',
		name: 'bigdesign1TextBoxLabelFont',
		defaultValue: '<quaternaryFont>',
		description: 'Big Design 1 design label font',
		cssProperty: 'font',
		selector: '.comp.compTextBox._bigDesign1 ._label',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Text Box Label Color',
		name: 'defaultTextBoxLabelColor',
		defaultValue: '<fontColorEight>',
		description: 'Default design label color',
		cssProperty: 'color',
		selector: '.comp.compTextBox._default ._label',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Text Box Label Color',
		name: 'outlineTextBoxLabelColor',
		defaultValue: '<fontColorEight>',
		description: 'Outline design label color',
		cssProperty: 'color',
		selector: '.comp.compTextBox._outlined ._label',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Text Box Label Color',
		name: 'filledTextBoxLabelColor',
		defaultValue: '<fontColorEight>',
		description: 'Filled design label color',
		cssProperty: 'color',
		selector: '.comp.compTextBox._filled ._label',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Text Box Label Color',
		name: 'bigdesign1TextBoxLabelColor',
		defaultValue: '<fontColorEight>',
		description: 'Big Design 1 design label color',
		cssProperty: 'color',
		selector: '.comp.compTextBox._bigDesign1 ._label',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Text  Box Height',
		name: 'defaultTextBoxHeight',
		defaultValue: '32px',
		description: 'Default design text box height',
		cssProperty: 'height',
		selector: '.comp.compTextBox._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Text Box Height',
		name: 'outlineTextBoxHeight',
		defaultValue: '32px',
		description: 'Outline design text box height',
		cssProperty: 'height',
		selector: '.comp.compTextBox._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Text Box Height',
		name: 'filledTextBoxHeight',
		defaultValue: '32px',
		description: 'Text design text box height',
		cssProperty: 'height',
		selector: '.comp.compTextBox._filled',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Text Box Height',
		name: 'bigDesign1TextBoxHeight',
		defaultValue: '60px',
		description: 'Big Design 1 text box height',
		cssProperty: 'height',
		selector: '.comp.compTextBox._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Text Box Border Radius',
		name: 'defaultTextBoxBorderRadius',
		defaultValue: '4px',
		description: 'Default design text box border radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTextBox._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Text Box Border Radius',
		name: 'outlineTextBoxBorderRadius',
		defaultValue: '16px',
		description: 'Outline design text box border radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTextBox._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Text Box Border Radius',
		name: 'filledTextBoxBorderRadius',
		defaultValue: '4px',
		description: 'Filled design text box border radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTextBox._filled',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Text Box Border Radius',
		name: 'bigdesign1TextBoxBorderRadius',
		defaultValue: '4px',
		description: 'Big Design 1 design text box border radius',
		cssProperty: 'border-radius',
		selector: '.comp.compTextBox._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Text Box Border',
		name: 'defaultTextBoxBorder',
		defaultValue: '1px solid',
		description: 'Default design text box border',
		cssProperty: 'border',
		selector: '.comp.compTextBox._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Text Box Border',
		name: 'outlineTextBoxBorder',
		defaultValue: '1px solid',
		description: 'Outline design text box border',
		cssProperty: 'border',
		selector: '.comp.compTextBox._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Text Box Border',
		name: 'filledTextBoxBorder',
		defaultValue: '',
		description: 'Filled design text box border',
		cssProperty: 'border',
		selector: '.comp.compTextBox._filled',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Text Box Border',
		name: 'bigdesign1TextBoxBorder',
		defaultValue: '1px solid',
		description: 'Big Design 1 design text box border',
		cssProperty: 'border',
		selector: '.comp.compTextBox._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Text Box Border Color',
		name: 'defaultTextBoxBorderColor',
		defaultValue: '<fontColorEight>',
		description: 'Default design text box border color',
		cssProperty: 'border-color',
		selector: '.comp.compTextBox._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Text Box Border Color',
		name: 'outlineTextBoxBorderColor',
		defaultValue: '<fontColorEight>',
		description: 'Outline design text box border color',
		cssProperty: 'border-color',
		selector: '.comp.compTextBox._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Text Box Border Color',
		name: 'filledTextBoxBorderColor',
		defaultValue: '<fontColorEight>',
		description: 'Filled design text box border color',
		cssProperty: 'border-color',
		selector: '.comp.compTextBox._filled',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Text Box Border Color',
		name: 'bigdesign1TextBoxBorderColor',
		defaultValue: '<fontColorEight>22',
		description: 'Big Design 1 design text box border color',
		cssProperty: 'border-color',
		selector: '.comp.compTextBox._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Text Box Padding',
		name: 'defaultTextBoxPadding',
		defaultValue: '0px 5px',
		description: 'Default design text box padding',
		cssProperty: 'padding',
		selector: '.comp.compTextBox._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Text Box Padding',
		name: 'outlineTextBoxPadding',
		defaultValue: '0px 14px',
		description: 'Outline design text box padding',
		cssProperty: 'padding',
		selector: '.comp.compTextBox._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Text Box Padding',
		name: 'filledTextBoxPadding',
		defaultValue: '0px 5px',
		description: 'Filled design text box padding',
		cssProperty: 'padding',
		selector: '.comp.compTextBox._filled',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Text Box Padding',
		name: 'bigdesign1TextBoxPadding',
		defaultValue: '0px 5px',
		description: 'Big Design 1 design text box padding',
		cssProperty: 'padding',
		selector: '.comp.compTextBox._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Text Box Icon Padding',
		name: 'defaultIconTextBoxPadding',
		defaultValue: '0px 8px',
		description: 'Default design text box Icon padding',
		cssProperty: 'padding',
		selector: '.comp.compTextBox._default ._leftIcon, .comp.compTextBox._default ._rightIcon ',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Text Box Icon Padding',
		name: 'outlineIconTextBoxPadding',
		defaultValue: '0px 8px',
		description: 'Outline design text box Icon padding',
		cssProperty: 'padding',
		selector: '.comp.compTextBox._outlined ._leftIcon, .comp.compTextBox._outlined ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Text Box Icon Padding',
		name: 'filledIconTextBoxPadding',
		defaultValue: '0px 8px',
		description: 'Filled design text box Icon padding',
		cssProperty: 'padding',
		selector: '.comp.compTextBox._filled ._leftIcon, .comp.compTextBox._filled ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Text Box Right Icon Padding',
		name: 'bigdesign1LeftIconTextBoxPadding',
		defaultValue: '0px 8px',
		description: 'Big Design 1 design text box Right Icon padding',
		cssProperty: 'padding',
		selector: '.comp.compTextBox._bigDesign1 ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Text Box Left Icon Padding',
		name: 'bigdesign1RightIconTextBoxPadding',
		defaultValue: '0px 18px 0px 8px',
		description: 'Big Design 1 design text box Left Icon padding',
		cssProperty: 'padding',
		selector: '.comp.compTextBox._bigDesign1 ._leftIcon',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Text Box Border When Active',
		name: 'defaultTextBoxActiveBorder',
		defaultValue: '2px solid',
		description: 'Default design text box active border',
		cssProperty: 'border',
		selector: '.comp.compTextBox._default._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Text Box Border When Active',
		name: 'outlineTextBoxActiveBorder',
		defaultValue: '2px solid',
		description: 'Outline design text box active border',
		cssProperty: 'border',
		selector: '.comp.compTextBox._outlined._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Text Box Border When Active',
		name: 'filledTextBoxActiveBorder',
		defaultValue: '',
		description: 'Filled design text box active border',
		cssProperty: 'border',
		selector: '.comp.compTextBox._filled._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Text Box Border When Active',
		name: 'bigdesign1TextBoxActiveBorder',
		defaultValue: '1px solid',
		description: 'Big Design 1 design text box active border',
		cssProperty: 'border',
		selector: '.comp.compTextBox._bigDesign1._isActive',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Text Box Background',
		name: 'defaultTextBoxBackground',
		defaultValue: '',
		description: 'Default design text box background',
		cssProperty: 'background',
		selector: '.comp.compTextBox._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Text Box Background',
		name: 'outlineTextBoxBackground',
		defaultValue: '',
		description: 'Outline design text box background',
		cssProperty: 'background',
		selector: '.comp.compTextBox._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Text Box Background',
		name: 'filledTextBoxBackground',
		defaultValue: '<backgroundColorNine>',
		description: 'Filled design text box background',
		cssProperty: 'background',
		selector: '.comp.compTextBox._filled',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Text Box Background',
		name: 'bigdesign1TextBoxBackground',
		defaultValue: 'linear-gradient(90deg, #96A1B41A 0%, #33333300 64.33%)',
		description: 'Big Design 1 design text box background',
		cssProperty: 'background',
		selector: '.comp.compTextBox._bigDesign1',
		noPrefix: true,
	},

	{
		groupName: 'Active Label Color',
		displayName: 'Primary Text Box Active Label Color',
		name: 'primaryTextBoxActiveLabelColor',
		defaultValue: '<fontColorThree>',
		description: 'Primary Text Box Active Label Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._default._isActive._primary ._label, .comp.compTextBox._outlined._primary ._label, .comp.compTextBox._filled._isActive._primary ._label, .comp.compTextBox._bigDesign1._isActive._primary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Active Label Color',
		displayName: 'Secondary Text Box Active  Label Color',
		name: 'secondaryTextBoxActiveLabelColor',
		defaultValue: '<fontColorFour>',
		description: 'Secondary Text Box Active Label Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._default._isActive._secondary ._label, .comp.compTextBox._outlined._secondary ._label, .comp.compTextBox._filled._isActive._secondary ._label, .comp.compTextBox._bigDesign1._isActive._secondary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Active Label Color',
		displayName: 'Tertiary Text Box Active Label Color',
		name: 'tertiaryTextBoxActiveLabelColor',
		defaultValue: '<fontColorFive>',
		description: 'Tertiary Text Box Active Label Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._default._isActive._tertiary ._label, .comp.compTextBox._outlined._tertiary ._label, .comp.compTextBox._filled._isActive._tertiary ._label, .comp.compTextBox._bigDesign1._isActive._tertiary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Active Label Color',
		displayName: 'Quaternary Text Box Active Label Color',
		name: 'quaternaryTextBoxActiveLabelColor',
		defaultValue: '<fontColorNine>',
		description: 'Quaternary Text Box Active Label Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._default._isActive._quaternary ._label, .comp.compTextBox._outlined._quaternary ._label, .comp.compTextBox._filled._isActive._quaternary ._label, .comp.compTextBox._bigDesign1._isActive._quaternary ._label',
		noPrefix: true,
	},
	{
		groupName: 'Active Label Color',
		displayName: 'Quinary Text Box Active Label Color',
		name: 'quinaryTextBoxActiveLabelColor',
		defaultValue: '<fontColorSeven>',
		description: 'Quinary Text Box Active Label Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._default._isActive._quinary ._label, .comp.compTextBox._outlined._quinary ._label, .comp.compTextBox._filled._isActive._quinary ._label, .comp.compTextBox._bigDesign1._isActive._quinary ._label',
		noPrefix: true,
	},

	{
		groupName: 'Active Background',
		displayName: 'Primary Text Box Active Background Color',
		name: 'primaryTextBoxActiveBackgroundColor',
		defaultValue: '<backgroundColorOne>',
		description: 'Primary Text Box Active Background Color',
		cssProperty: 'background',
		selector: '.comp.compTextBox._filled._isActive._primary',
		noPrefix: true,
	},
	{
		groupName: 'Active Background',
		displayName: 'Secondary Text Box Active  Background Color',
		name: 'secondaryTextBoxActiveBackgroundColor',
		defaultValue: '<backgroundColorTwo>',
		description: 'Secondary Text Box Active Background Color',
		cssProperty: 'background',
		selector: '.comp.compTextBox._filled._isActive._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Active Background',
		displayName: 'Tertiary Text Box Active Background Color',
		name: 'tertiaryTextBoxActiveBackgroundColor',
		defaultValue: '<backgroundColorThree>',
		description: 'Tertiary Text Box Active Background Color',
		cssProperty: 'background',
		selector: '.comp.compTextBox._filled._isActive._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Active Background',
		displayName: 'Quaternary Text Box Active Background Color',
		name: 'quaternaryTextBoxActiveBackgroundColor',
		defaultValue: '<backgroundColorFour>',
		description: 'Quaternary Text Box Active Background Color',
		cssProperty: 'background',
		selector: '.comp.compTextBox._filled._isActive._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Active Background',
		displayName: 'Quinary Text Box Active Background Color',
		name: 'quinaryTextBoxActiveBackgroundColor',
		defaultValue: '<backgroundColorFive>',
		description: 'Quinary Text Box Active Background Color',
		cssProperty: 'background',
		selector: '.comp.compTextBox._filled._isActive._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Active Border Color',
		displayName: 'Primary Text Box Active Border Color',
		name: 'primaryTextBoxActiveBorderColor',
		defaultValue: '<fontColorThree>',
		description: 'Primary Text Box Active Border Color',
		cssProperty: 'border-color',
		selector:
			'.comp.compTextBox._default._isActive._primary, .comp.compTextBox._outlined._primary, .comp.compTextBox._filled._isActive._primary, .comp.compTextBox._bigDesign1._isActive._primary',
		noPrefix: true,
	},
	{
		groupName: 'Active Border Color',
		displayName: 'Secondary Text Box Active  Border Color',
		name: 'secondaryTextBoxActiveBorderColor',
		defaultValue: '<fontColorFour>',
		description: 'Secondary Text Box Active Border Color',
		cssProperty: 'border-color',
		selector:
			'.comp.compTextBox._default._isActive._secondary, .comp.compTextBox._outlined._secondary, .comp.compTextBox._filled._isActive._secondary, .comp.compTextBox._bigDesign1._isActive._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Active Border Color',
		displayName: 'Tertiary Text Box Active Border Color',
		name: 'tertiaryTextBoxActiveBorderColor',
		defaultValue: '<fontColorFive>',
		description: 'Tertiary Text Box Active Border Color',
		cssProperty: 'border-color',
		selector:
			'.comp.compTextBox._default._isActive._tertiary, .comp.compTextBox._outlined._tertiary, .comp.compTextBox._filled._isActive._tertiary, .comp.compTextBox._bigDesign1._isActive._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Active Border Color',
		displayName: 'Quaternary Text Box Active Border Color',
		name: 'quaternaryTextBoxActiveBorderColor',
		defaultValue: '<fontColorNine>',
		description: 'Quaternary Text Box Active Border Color',
		cssProperty: 'border-color',
		selector:
			'.comp.compTextBox._default._isActive._quaternary, .comp.compTextBox._outlined._quaternary, .comp.compTextBox._filled._isActive._quaternary, .comp.compTextBox._bigDesign1._isActive._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Active Border Color',
		displayName: 'Quinary Text Box Active Border Color',
		name: 'quinaryTextBoxActiveBorderColor',
		defaultValue: '<fontColorSeven>',
		description: 'Quinary Text Box Active Border Color',
		cssProperty: 'border-color',
		selector:
			'.comp.compTextBox._default._isActive._quinary, .comp.compTextBox._outlined._quinary, .comp.compTextBox._filled._isActive._quinary, .comp.compTextBox._bigDesign1._isActive._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Active Filled Font Color',
		displayName: 'Text Box Filled Active  Font Color',
		name: 'textBoxFilledActiveFontColor',
		defaultValue: '<fontColorTwo>',
		description: 'Text Box Filled Active  Font Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._filled._isActive._secondary, .comp.compTextBox._filled._isActive._quaternary',
		noPrefix: true,
	},

	{
		groupName: 'IconColor',
		displayName: 'Primary Icon Color',
		name: 'primaryTextBoxIconColor',
		defaultValue: '<fontColorSix>',
		description: 'Primary Icon Color',
		cssProperty: 'color',
		selector: '.comp.compTextBox._primary ._leftIcon, .comp.compTextBox._primary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'IconColor',
		displayName: 'Secondary Icon Color',
		name: 'secondaryTextBoxIconColor',
		defaultValue: '<fontColorSix>',
		description: 'Secondary Icon Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._secondary ._leftIcon, .comp.compTextBox._secondary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'IconColor',
		displayName: 'Tertiary Icon Color',
		name: 'tertiaryTextBoxIconColor',
		defaultValue: '<fontColorSix>',
		description: 'Tertiary Icon Color',
		cssProperty: 'color',
		selector: '.comp.compTextBox._tertiary ._leftIcon, .comp.compTextBox._tertiary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'IconColor',
		displayName: 'Quaternary Icon Color',
		name: 'quaternaryTextBoxIconColor',
		defaultValue: '<fontColorSix>',
		description: 'Quaternary Icon Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._quaternary ._leftIcon, .comp.compTextBox._quaternary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'IconColor',
		displayName: 'Quinary Icon Color',
		name: 'quinaryTextBoxIconColor',
		defaultValue: '<fontColorSix>',
		description: 'Quinary Icon Color',
		cssProperty: 'color',
		selector: '.comp.compTextBox._quinary ._leftIcon, .comp.compTextBox._quinary ._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Active IconColor',
		displayName: 'Primary Active Icon Color',
		name: 'primaryActiveTextBoxIconColor',
		defaultValue: '<fontColorEight>',
		description: 'Primary Active Icon Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._isActive._primary ._leftIcon, .comp.compTextBox._isActive._primary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Active IconColor',
		displayName: 'Secondary Active Icon Color',
		name: 'secondaryActiveTextBoxIconColor',
		defaultValue: '<fontColorEight>',
		description: 'Secondary Active Icon Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._isActive._secondary ._leftIcon, .comp.compTextBox._isActive._secondary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Active IconColor',
		displayName: 'Tertiary Active Icon Color',
		name: 'tertiaryActiveTextBoxIconColor',
		defaultValue: '<fontColorEight>',
		description: 'Tertiary Active Icon Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._isActive._tertiary ._leftIcon, .comp.compTextBox._isActive._tertiary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Active IconColor',
		displayName: 'Quaternary Active Icon Color',
		name: 'quaternaryActiveTextBoxIconColor',
		defaultValue: '<fontColorEight>',
		description: 'Quaternary Active Icon Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._isActive._quaternary ._leftIcon, .comp.compTextBox._isActive._quaternary ._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Active IconColor',
		displayName: 'Quinary Active Icon Color',
		name: 'quinaryActiveTextBoxIconColor',
		defaultValue: '<fontColorEight>',
		description: 'Quinary Active Icon Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._isActive._quinary ._leftIcon, .comp.compTextBox._isActive._quinary ._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Active Filled Icon Color',
		displayName: 'Text Box Filled Active  Font Color',
		name: 'textBoxFilledActiveFontColor',
		defaultValue: '<fontColorTwo>',
		description: 'Text Box Filled Active  Font Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._filled._isActive._secondary ._leftIcon, .comp.compTextBox._filled._isActive._quaternary ._leftIcon, .comp.compTextBox._filled._isActive._secondary ._rightIcon, .comp.compTextBox._filled._isActive._quaternary ._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Active Big Design 1 Background',
		displayName: 'Primary Text Box Active Background Color For Big Design 1',
		name: 'primaryTextBoxActiveBackgroundColorBigDesign1',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorOne>19 0%, <backgroundColorSix>00 64.33%)',
		description: 'Primary Text Box Active Background Color For Big Design 1',
		cssProperty: 'background',
		selector: '.comp.compTextBox._bigDesign1._isActive._primary',
		noPrefix: true,
	},
	{
		groupName: 'Active Big Design 1 Background',
		displayName: 'Secondary Text Box Active  Background Color For Big Design 1',
		name: 'secondaryTextBoxActiveBackgroundColorBigDesign1',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorTwo>19 0%, <backgroundColorSix>00 64.33%)',
		description: 'Secondary Text Box Active Background Color For Big Design 1',
		cssProperty: 'background',
		selector: '.comp.compTextBox._bigDesign1._isActive._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Active Big Design 1 Background',
		displayName: 'Tertiary Text Box Active Background Color For Big Design 1',
		name: 'tertiaryTextBoxActiveBackgroundColorBigDesign1',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorThree>19 0%, <backgroundColorSix>00 64.33%)',
		description: 'Tertiary Text Box Active Background Color For Big Design 1',
		cssProperty: 'background',
		selector: '.comp.compTextBox._bigDesign1._isActive._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Active Big Design 1 Background',
		displayName: 'Quaternary Text Box Active Background Color For Big Design 1',
		name: 'quaternaryTextBoxActiveBackgroundColorBigDesign1',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorFour>19 0%, <backgroundColorSix>00 64.33%)',
		description: 'Quaternary Text Box Active Background Color For Big Design 1',
		cssProperty: 'background',
		selector: '.comp.compTextBox._bigDesign1._isActive._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Active Big Design 1 Background',
		displayName: 'Quinary Text Box Active Background Color For Big Design 1',
		name: 'quinaryTextBoxActiveBackgroundColorBigDesign1',
		defaultValue:
			'linear-gradient(90deg, <backgroundColorFive>19 0%, <backgroundColorSix>00 64.33%)',
		description: 'Quinary Text Box Active Background Color For Big Design 1',
		cssProperty: 'background',
		selector: '.comp.compTextBox._bigDesign1._isActive._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Success Icon Color',
		displayName: 'Success Icon Color',
		name: 'successTextBoxIconColor',
		defaultValue: '<successColor>',
		description: 'Success Icon Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox ._successIcon._rightIcon, .comp.compTextBox._isActive ._successIcon._rightIcon',
		noPrefix: true,
	},
	{
		groupName: 'Error Icon Color',
		displayName: 'Error Icon Color',
		name: 'errorTextBoxIconColor',
		defaultValue: '<errorColor>',
		description: 'Error Icon Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox ._errorIcon._rightIcon, .comp.compTextBox._isActive ._errorIcon._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Error Border Color',
		displayName: 'Error Active Border Color',
		name: 'errorTextBoxBorderColor',
		defaultValue: '<errorColor>',
		description: 'Error Active Border Color',
		cssProperty: 'border-color',
		selector:
			'.comp.compTextBox._default._hasError, .comp.compTextBox._outlined._hasError, .comp.compTextBox._filled._hasError, .comp.compTextBox._bigDesign1._hasError, .comp.compTextBox._default._isActive._hasError, .comp.compTextBox._filled._isActive._hasError, .comp.compTextBox._bigDesign1._isActive._hasError',
		noPrefix: true,
	},

	{
		groupName: 'Error Big Design 1Background',
		displayName: 'Error Big Design 1Text Box Background',
		name: 'errorTextBoxBackgroundColorForBigDesign1',
		defaultValue: 'linear-gradient(90deg, <errorColor>19 0%, <backgroundColorSix>00 64.33%)',
		description: 'Error Big Design 1Text Box Background',
		cssProperty: 'background',
		selector:
			'.comp.compTextBox._bigDesign1._isActive._hasError, .comp.compTextBox._bigDesign1._hasError',
		noPrefix: true,
	},

	{
		groupName: 'Error Filled',
		displayName: 'Error Filled Text Box Background',
		name: 'errorTextBoxBackgroundColorForFilledDesign',
		defaultValue: '<errorColor>',
		description: 'Error Filled Text Box Background',
		cssProperty: 'background',
		selector:
			'.comp.compTextBox._filled._isActive._hasError, .comp.compTextBox._filled._hasError',
		noPrefix: true,
	},

	{
		groupName: 'Error Filled',
		displayName: 'Error Filled Text Box Font Color',
		name: 'errorTextBoxFontColorForFilledDesign',
		defaultValue: '<fontColorTwo>',
		description: 'Error Filled Text Box Font Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._filled._isActive._hasError, .comp.compTextBox._filled._hasError, .comp.compTextBox._filled._isActive._hasError ._leftIcon, .comp.compTextBox._filled._hasError ._leftIcon, .comp.compTextBox._filled._isActive._hasError ._rightIcon, .comp.compTextBox._filled._hasError ._rightIcon',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Text Box Support Text Font',
		name: 'defaultTextBoxSupportTextFont',
		defaultValue: '<quaternaryFont>',
		description: 'Default design label font',
		cssProperty: 'font',
		selector: '.comp.compTextBox._default ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Text Box Support Text Font',
		name: 'outlineTextBoxSupportTextFont',
		defaultValue: '<quaternaryFont>',
		description: 'Outline design label font',
		cssProperty: 'font',
		selector: '.comp.compTextBox._outlined ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Text Box Support Text Font',
		name: 'filledTextBoxSupportTextFont',
		defaultValue: '<quaternaryFont>',
		description: 'Filled design label font',
		cssProperty: 'font',
		selector: '.comp.compTextBox._filled ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Text Box Support Text Font',
		name: 'bigdesign1TextBoxSupportTextFont',
		defaultValue: '<quaternaryFont>',
		description: 'Big Design 1 design label font',
		cssProperty: 'font',
		selector: '.comp.compTextBox._bigDesign1 ._supportText',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Text Box Support Text Color',
		name: 'defaultTextBoxSupportTextColor',
		defaultValue: '<fontColorEight>',
		description: 'Default design label color',
		cssProperty: 'color',
		selector: '.comp.compTextBox._default ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Text Box Support Text Color',
		name: 'outlineTextBoxSupportTextColor',
		defaultValue: '<fontColorEight>',
		description: 'Outline design label color',
		cssProperty: 'color',
		selector: '.comp.compTextBox._outlined ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Filled',
		displayName: 'Filled Text Box Support Text Color',
		name: 'filledTextBoxSupportTextColor',
		defaultValue: '<fontColorEight>',
		description: 'Filled design label color',
		cssProperty: 'color',
		selector: '.comp.compTextBox._filled ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Big Design 1',
		displayName: 'Big Design 1 Text Box Support Text Color',
		name: 'bigdesign1TextBoxSupportTextColor',
		defaultValue: '<fontColorEight>',
		description: 'Big Design 1 design label color',
		cssProperty: 'color',
		selector: '.comp.compTextBox._bigDesign1 ._supportText',
		noPrefix: true,
	},

	{
		groupName: 'Active Support Text Color',
		displayName: 'Primary Text Box Active Support Text Color',
		name: 'primaryTextBoxActiveSupportTextColor',
		defaultValue: '<fontColorThree>',
		description: 'Primary Text Box Active Support Text Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._default._isActive._primary ._supportText, .comp.compTextBox._outlined._primary ._supportText, .comp.compTextBox._filled._isActive._primary ._supportText, .comp.compTextBox._bigDesign1._isActive._primary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Active Support Text Color',
		displayName: 'Secondary Text Box Active  Support Text Color',
		name: 'secondaryTextBoxActiveSupportTextColor',
		defaultValue: '<fontColorFour>',
		description: 'Secondary Text Box Active Support Text Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._default._isActive._secondary ._supportText, .comp.compTextBox._outlined._secondary ._supportText, .comp.compTextBox._filled._isActive._secondary ._supportText, .comp.compTextBox._bigDesign1._isActive._secondary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Active Support Text Color',
		displayName: 'Tertiary Text Box Active Support Text Color',
		name: 'tertiaryTextBoxActiveSupportTextColor',
		defaultValue: '<fontColorFive>',
		description: 'Tertiary Text Box Active Support Text Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._default._isActive._tertiary ._supportText, .comp.compTextBox._outlined._tertiary ._supportText, .comp.compTextBox._filled._isActive._tertiary ._supportText, .comp.compTextBox._bigDesign1._isActive._tertiary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Active Support Text Color',
		displayName: 'Quaternary Text Box Active Support Text Color',
		name: 'quaternaryTextBoxActiveSupportTextColor',
		defaultValue: '<fontColorNine>',
		description: 'Quaternary Text Box Active Support Text Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._default._isActive._quaternary ._supportText, .comp.compTextBox._outlined._quaternary ._supportText, .comp.compTextBox._filled._isActive._quaternary ._supportText, .comp.compTextBox._bigDesign1._isActive._quaternary ._supportText',
		noPrefix: true,
	},
	{
		groupName: 'Active Support Text Color',
		displayName: 'Quinary Text Box Active Support Text Color',
		name: 'quinaryTextBoxActiveSupportTextColor',
		defaultValue: '<fontColorSeven>',
		description: 'Quinary Text Box Active Support Text Color',
		cssProperty: 'color',
		selector:
			'.comp.compTextBox._default._isActive._quinary ._supportText, .comp.compTextBox._outlined._quinary ._supportText, .comp.compTextBox._filled._isActive._quinary ._supportText, .comp.compTextBox._bigDesign1._isActive._quinary ._supportText',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
