import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		name: 'supportTextDisabledColor',
		cssProperty: 'color',
		displayName: 'Application/Site Disabled font color',
		description: "This color is used for disabled textbox's support text.",
		defaultValue: '<formInputTextColor-when-disabled>',
		noPrefix: true,
		selector: '.commonInputBox .supportText.disabled',
	},
	{
		name: 'supportTextFontSize',
		cssProperty: 'font-size',
		displayName: 'textbox support text font size',
		description: "This textbox's font size is used for textbox's support text.",
		defaultValue: '<mainFontSize>',
		noPrefix: true,
		selector: '.commonInputBox .supportText',
	},
	{
		name: 'supportTextFontColor',
		cssProperty: 'color',
		displayName: 'textbox support text font color',
		description: "This textbox's color is used for textbox's support text.",
		noPrefix: true,
		selector: '.commonInputBox .supportText',
	},
	{
		name: 'inputTextFontSize',
		cssProperty: 'font-size',
		displayName: 'textbox input text font size',
		description: "This textbox's font size is used for textbox's input text.",
		defaultValue: '<mainFontSize>',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .inputContainer .textbox',
	},
	{
		name: 'supportTextErrorColor',
		cssProperty: 'color',
		displayName: 'Application/Site Error font color',
		description: "This color is used for error textbox's support text.",
		defaultValue: '<mainErrorColor>',
		noPrefix: true,
		selector: '.commonInputBox .supportText.error',
	},
	{
		name: 'textBoxBorderColor',
		cssProperty: 'border',
		displayName: "textbox's border color",
		description: "This color is used for textbox's border color.",
		defaultValue: '1px solid <formInputBorderColor>',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv',
	},
	{
		name: 'textBoxWdith',
		cssProperty: 'width',
		displayName: "textbox's width",
		description: "This is for textbox's width",
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv',
	},
	{
		name: 'textBoxHeight',
		cssProperty: 'height',
		displayName: "textbox's height",
		description: "This is for textbox's height",
		defaultValue: '56px',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv',
	},
	{
		name: 'textBoxBorderRadius',
		cssProperty: 'border-radius',
		displayName: "textbox's border radius",
		description: "This is for textbox's border radius",
		defaultValue: '4px',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv',
	},
	{
		name: 'textBoxBorderErrorColor',
		cssProperty: 'border',
		displayName: "textbox's border color on error",
		description: "This color is used for textbox's error border color.",
		defaultValue: '1px solid <formInputBorderErrorColor>',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv.error',
	},
	{
		name: 'textBoxLeftIconSelfAlign',
		cssProperty: 'justify-self',
		displayName: "textbox's left icon self align",
		description: "This is for textbox's left icon self align",
		defaultValue: 'center',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .leftIcon',
	},
	{
		name: 'leftIconLeftMargin',
		cssProperty: 'margin-left',
		displayName: 'Left icon left margin',
		description: "Left icon's left margin.",
		defaultValue: '5px',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .leftIcon',
	},
	{
		name: 'textBoxLeftIconLeftPadding',
		cssProperty: 'padding-left',
		displayName: "textbox's left icon padding left",
		description: "This is for textbox's left icon left padding",
		defaultValue: '0',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .leftIcon',
	},
	{
		name: 'textBoxRightIconSelfAlign',
		cssProperty: 'justify-self',
		displayName: "textbox's right icon self align",
		description: "This is for textbox's right icon self align",
		defaultValue: 'center',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .rightIcon',
	},
	{
		name: 'textBoxRightIconRightPadding',
		cssProperty: 'padding-right',
		displayName: "textbox's right icon padding right",
		description: "This is for textbox's right icon right padding",
		defaultValue: '0',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .rightIcon',
	},
	{
		name: 'textBoxRightIconRightMargin',
		cssProperty: 'margin-right',
		displayName: "textbox's right icon margin right",
		description: "This is for textbox's right icon right margin",
		defaultValue: '5px',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .rightIcon',
	},
	{
		name: 'noFloatTextBoxLabelBottomMargin',
		cssProperty: 'margin-bottom',
		displayName: "textbox's label margin",
		description: "This is for textbox's space between label and input box",
		noPrefix: true,
		selector: '.commonInputBox .noFloatTextBoxLabel',
	},
	{
		name: 'textBoxBorderColorOnFocus',
		cssProperty: 'border',
		displayName: "textbox's border color on focus",
		description: "This color is used for textbox's focus border color.",
		defaultValue: '1px solid <formInputBorderColor-focussed>',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv.focussed',
	},
	{
		name: 'textBoxBorderColorWhenHasText',
		cssProperty: 'border',
		displayName: "textbox's border color with text",
		description: "This color is used for textbox's border color when it has text.",
		defaultValue: '1px solid <formInputBorderColor-with-text>',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv.hasText',
	},
	{
		name: 'textBoxBorderColorWhenDisabled',
		cssProperty: 'border',
		displayName: "textbox's border color when disabled",
		description: "This color is used for textbox's border color when it is disabled.",
		defaultValue: '1px solid <formInputBorderColor-when-disabled>',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv.disabled',
	},
	{
		name: 'textBoxLabelTextSize',
		cssProperty: 'font-size',
		displayName: "Textbox's label font size",
		description: "This font size is used for textbox's label.",
		defaultValue: '<mainFontSize>',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .inputContainer .textBoxLabel',
	},
	{
		name: 'textBoxLabelTextColor',
		cssProperty: 'color',
		displayName: "textbox's label color",
		description: "This color is used for textbox's label color.",
		defaultValue: '<formInputTextColor>',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .inputContainer .textBoxLabel',
	},
	{
		name: 'textBoxLabelTextCursorEvent',
		cssProperty: 'cursor',
		displayName: "textbox's label text cursor event",
		description: "This cursor is used for textbox's label text cursor event.",
		defaultValue: 'text',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .inputContainer .textBoxLabel',
	},
	{
		name: 'textBoxInputContainerHeight',
		cssProperty: 'height',
		displayName: "textbox's input container height",
		description: "This height is used for textbox's input container height.",
		defaultValue: '100%',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .inputContainer',
	},
	{
		name: 'textBoxInputContainerHeight',
		cssProperty: 'width',
		displayName: "textbox's input container width",
		description: "This width is used for textbox's input container height.",
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .inputContainer',
	},

	{
		name: 'textBoxTextColorWhenDisabled',
		cssProperty: 'color',
		displayName: "textbox's border color when disabled",
		description: "This color is used for textbox's border color when it is disabled.",
		defaultValue: '<formInputTextColor-when-disabled>',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .inputContainer .textBoxLabel.disabled',
	},
	{
		name: 'textBoxLabelTextPostionFromLeft',
		cssProperty: 'left',
		displayName: "textbox's label position from left when input",
		description: "This left is used for textbox's label position when it has any input.",
		defaultValue: '0px',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .inputContainer .textBoxLabel',
	},
	{
		name: 'textBoxLabelTextPaddingFromLeft',
		cssProperty: 'padding-left',
		displayName: "textbox's label padding from left when input",
		description: "This left is used for textbox's label padding when it has any input.",
		defaultValue: '5px',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .inputContainer .textBoxLabel',
	},
	{
		name: 'textBoxLabelTextTransformWhenContainsTextFromTop',
		cssProperty: 'top',
		displayName: "textbox's label text position from top when input",
		description:
			"This top is used for textbox's label text position from top when it has any input.",
		defaultValue: '0',
		noPrefix: true,
		selector:
			'.commonInputBox .textBoxDiv .inputContainer .textbox:focus + .textBoxLabel, .commonInputBox .textBoxDiv .inputContainer .textbox:not(:placeholder-shown) + .textBoxLabel',
	},
	{
		name: 'textBoxLabelTextTransformWhenContainsTextFromLeft',
		cssProperty: 'left',
		displayName: "textbox's label text position from left when input",
		description:
			"This left is used for textbox's label text position from top when it has any input.",
		defaultValue: '5px',
		noPrefix: true,
		selector:
			'.commonInputBox .textBoxDiv .inputContainer .textbox:focus + .textBoxLabel, .commonInputBox .textBoxDiv .inputContainer .textbox:not(:placeholder-shown) + .textBoxLabel',
	},
	{
		name: 'textBoxLabelTextTransformWhenContainsTextPaddingLeft',
		cssProperty: 'padding-left',
		displayName: "textbox's label text padding from left when input",
		description:
			"This left is used for textbox's label text padding left when it has any input.",
		defaultValue: '0',
		noPrefix: true,
		selector:
			'.commonInputBox .textBoxDiv .inputContainer .textbox:focus + .textBoxLabel, .commonInputBox .textBoxDiv .inputContainer .textbox:not(:placeholder-shown) + .textBoxLabel',
	},
	{
		name: 'textBoxLabelTextTransformWhenContainsTextBackgroundColor',
		cssProperty: 'background-color',
		displayName: "textbox's label text background color when input",
		description:
			"This background color is used for textbox's label text background color when it has any input.",
		defaultValue: '#fff',
		noPrefix: true,
		selector:
			'.commonInputBox .textBoxDiv .inputContainer .textbox:focus + .textBoxLabel, .commonInputBox .textBoxDiv .inputContainer .textbox:not(:placeholder-shown) + .textBoxLabel',
	},
	{
		name: 'textBoxLabelTextTransformWhenContainsTextFromTopWhenContainsIcon',
		cssProperty: 'top',
		displayName: "textbox's label text position from top when input When Contains Icon",
		description:
			"This top is used for textbox's label text position from top when it has any input when contains Icon.",
		defaultValue: '0',
		noPrefix: true,
		selector:
			'.commonInputBox .textBoxDiv .inputContainer .textbox:focus + .textBoxLabel, .commonInputBox .textBoxDiv .inputContainer .textbox:not(:placeholder-shown) + .textBoxLabel',
	},
	{
		name: 'textBoxLabelTextTransformWhenContainsTextPaddingLeftWhenContainsIcon',
		cssProperty: 'padding-left',
		displayName: "textbox's label text padding from left when input when contains icon",
		description:
			"This left is used for textbox's label text padding left when it has any input when contains icon.",
		defaultValue: '0',
		noPrefix: true,
		selector:
			'.commonInputBox .textBoxDiv .inputContainer .textbox:focus + .textBoxLabel, .commonInputBox .textBoxDiv .inputContainer .textbox:not(:placeholder-shown) + .textBoxLabel',
	},
	{
		name: 'textBoxLabelTextTransformWhenContainsTextBackgroundColorWhenContainsIcon',
		cssProperty: 'background-color',
		displayName: "textbox's label text background color when input when contains icon",
		description:
			"This background color is used for textbox's label text background color when it has any input when contains icon.",
		defaultValue: '#fff',
		noPrefix: true,
		selector:
			'.commonInputBox .textBoxDiv .inputContainer .textbox:focus + .textBoxLabel, .commonInputBox .textBoxDiv .inputContainer .textbox:not(:placeholder-shown) + .textBoxLabel',
	},
	{
		name: 'textBoxLabelTextOpacity',
		cssProperty: 'opacity',
		displayName: "textbox's label text opacity",
		description: "This opacity is used for textbox's label content opacity.",
		defaultValue: '0',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .inputContainer .textbox.float::placeholder',
	},
	{
		name: 'textBoxContainerContentAlign',
		cssProperty: 'align-items',
		displayName: "textbox's Container Content Align in the grid",
		description: "This align items is used for textbox's conatiner content align.",
		defaultValue: 'center',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv',
	},
	{
		name: 'textBoxContainerContentAlign',
		cssProperty: 'align-items',
		displayName: "textbox's Container Content Align in the grid",
		description:
			"This align items is used for textbox's conatiner content align when contains icons",
		defaultValue: 'center',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv',
	},
	{
		name: 'textBoxLabelTextColorWhenError',
		cssProperty: 'color',
		displayName: "textbox's label color when error",
		description: "This color is used for textbox's label color when it has error.",
		defaultValue: '<form-input-error-color>',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .inputContainer .textBoxLabel.error',
	},
	{
		name: 'noFloatTextBoxLabelTextColor',
		cssProperty: 'color',
		displayName: "No Float textbox's label color",
		description: "This color is used for textbox's label color.",
		defaultValue: '<formInputTextColor>',
		noPrefix: true,
		selector: '.commonInputBox .noFloatTextBoxLabel',
	},
	{
		name: 'noFloatTextBoxTextColorWhenDisabled',
		cssProperty: 'color',
		displayName: "No Float textbox's border color when disabled",
		description: "This color is used for textbox's border color when it is disabled.",
		defaultValue: '<formInputTextColor-when-disabled>',
		noPrefix: true,
		selector: '.commonInputBox .noFloatTextBoxLabel.disabled',
	},
	{
		name: 'noFloatTextBoxLabelTextColorWhenError',
		cssProperty: 'color',
		displayName: "No Float textbox's label color when error",
		description: "This color is used for textbox's label color when it has error.",
		defaultValue: '<form-input-error-color>',
		noPrefix: true,
		selector: '.commonInputBox .noFloatTextBoxLabel.error',
	},
	{
		name: 'textBoxTextMouseEventWhenDisabled',
		cssProperty: 'cursor',
		displayName: "textbox's mouse cursor when disabled",
		description: "This not allowed mouse event is used for textbox's when it is disabled.",
		defaultValue: '<formInputMouseEventWhenDisabled>',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .inputContainer .textbox:disabled',
	},
	{
		name: 'textBoxTextBackgroundColorWhenDisabled',
		cssProperty: 'background-color',
		displayName: "textbox's background color when disabled",
		description: "This background color is used for textbox's when it is disabled.",
		defaultValue: 'transparent',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .inputContainer .textbox:disabled',
	},
	{
		name: 'textBoxLabelBackgroundColorWhenDisabled',
		cssProperty: 'background-color',
		displayName: "textbox's label background color when disabled",
		description: "This background color is used for textbox's label when it is disabled.",
		defaultValue: 'transparent',
		noPrefix: true,
		selector: '.commonInputBox .textBoxLabel.disabled',
	},
	{
		name: 'textBoxClearTextIconPointerEvent',
		cssProperty: 'cursor',
		displayName: "textbox's clear text icon poiter event",
		description: "This cursor event is used for textbox's clear icon.",
		defaultValue: 'pointer',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .clearText',
	},
	{
		name: 'textBoxIconColorWhenError',
		cssProperty: 'color',
		displayName: "textbox's Error Icon color when error",
		description: "This color is used for textbox's error icon color when it has error",
		defaultValue: '<formInputTextColor-when-error>',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .errorIcon',
	},
	{
		name: 'textBoxTextColorWhenDisabled',
		cssProperty: 'color',
		displayName: "textbox's text color when disabled",
		description: "This color is used for textbox's text color when its disabled",
		defaultValue: '<formInputTextColor-when-disabled>',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .inputContainer .textbox:disabled',
	},
	{
		name: 'textBoxIconColorWhenTextPresent',
		cssProperty: 'color',
		displayName: "textbox's Error Icon Color",
		description:
			"This color is used for textbox's icon color when we input new data in textbox after error",
		defaultValue: '<fromInputErrorIconHastextColor>',
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .errorIcon.hasText',
	},
	{
		name: 'textBoxPasswordIconPadding',
		cssProperty: 'padding',
		displayName: "textbox's Password Icon Padding",
		description: "This color is used for textbox's password icon padding",
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .passwordIcon',
	},
	{
		name: 'textBoxPasswordIconPaddingLeft',
		cssProperty: 'padding-left',
		displayName: "textbox's Password Icon Padding left",
		description: "This color is used for textbox's password icon padding left",
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .passwordIcon',
	},
	{
		name: 'textBoxPasswordIconPaddingRight',
		cssProperty: 'padding-right',
		displayName: "textbox's Password Icon Padding right",
		description: "This color is used for textbox's password icon padding right",
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .passwordIcon',
	},
	{
		name: 'textBoxPasswordIconPaddingTop',
		cssProperty: 'padding-top',
		displayName: "textbox's Password Icon Padding Top",
		description: "This color is used for textbox's password icon padding top",
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .passwordIcon',
	},
	{
		name: 'textBoxPasswordIconPaddingBottom',
		cssProperty: 'padding-bottom',
		displayName: "textbox's Password Icon Padding bottom",
		description: "This color is used for textbox's password icon padding bottom",
		noPrefix: true,
		selector: '.commonInputBox .textBoxDiv .passwordIcon',
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
