import { StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		displayName: 'Radio Button Font',
		name: 'radioButtonFont',
		defaultValue: '<primaryFont>',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Radio Button Font',
		name: 'defaultRadioButtonFont',
		defaultValue: '<radioButtonFont>',
		cssProperty: 'font',
		selector: '.comp.compRadioButton._default label',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Radio Button Font',
		name: 'outlineRadioButtonFont',
		defaultValue: '<radioButtonFont>',
		cssProperty: 'font',
		selector: '.comp.compRadioButton._outlined label',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Default Radio Button Border',
		name: 'defaultRadioButtonBorder',
		defaultValue: 'none',
		cssProperty: 'border',
		selector: '.comp.compRadioButton._default .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Radio Button Border',
		name: 'outlineRadioButtonBorder',
		defaultValue: '2px solid',
		cssProperty: 'border',
		selector: '.comp.compRadioButton._outlined .commonCheckbox',
		noPrefix: true,
	},

	{
		groupName: 'Border Color',
		displayName: 'Primary Outline Radio Button Border Color',
		name: 'primaryOutlineRadioButtonBorderColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'border-color',
		selector: '.comp.compRadioButton._outlined._primary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Secondary Outline Radio Button Border Color',
		name: 'secondaryOutlineRadioButtonBorderColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'border-color',
		selector: '.comp.compRadioButton._outlined._secondary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Tertiary Outline Radio Button Border Color',
		name: 'tertiaryOutlineRadioButtonBorderColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'border-color',
		selector: '.comp.compRadioButton._outlined._tertiary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Quaternary Outline Radio Button Border Color',
		name: 'quaternaryOutlineRadioButtonBorderColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'border-color',
		selector: '.comp.compRadioButton._outlined._quaternary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Border Color',
		displayName: 'Quinary Outline Radio Button Border Color',
		name: 'quinaryOutlineRadioButtonBorderColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'border-color',
		selector: '.comp.compRadioButton._outlined._quinary .commonCheckbox',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Primary Default Radio Button Background',
		name: 'primaryDefaultRadioButtonBackground',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector: '.comp.compRadioButton._default._primary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Secondary Default Radio Button Background',
		name: 'secondaryDefaultRadioButtonBackground',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector: '.comp.compRadioButton._default._secondary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Tertiary Default Radio Button Background',
		name: 'tertiaryDefaultRadioButtonBackground',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector: '.comp.compRadioButton._default._tertiary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quaternary Default Radio Button Background',
		name: 'quaternaryDefaultRadioButtonBackground',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector: '.comp.compRadioButton._default._quaternary .commonCheckbox',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Quinary Default Radio Button Background',
		name: 'quinaryDefaultRadioButtonBackground',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector: '.comp.compRadioButton._default._quinary .commonCheckbox',
		noPrefix: true,
	},

	{
		groupName: 'Background Color',
		displayName: 'Outline Radio Button Background',
		name: 'outlineRadioButtonBackground',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compRadioButton._outlined .commonCheckbox',
		noPrefix: true,
	},

	{
		groupName: 'Tick Color',
		displayName: 'Radio Button Tick Color',
		name: 'radioButtonTickColor',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compRadioButton._default .commonCheckbox ._thumb',
		noPrefix: true,
	},

	{
		groupName: 'Tick Color',
		displayName: 'Primary Outline Radio Button Tick Color',
		name: 'primaryOutlineRadioButtonTickColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'background',
		selector: '.comp.compRadioButton._outlined._primary .commonCheckbox ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Tick Color',
		displayName: 'Secondary Outline Radio Button Tick Color',
		name: 'secondaryOutlineRadioButtonTickColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'background',
		selector: '.comp.compRadioButton._outlined._secondary .commonCheckbox ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Tick Color',
		displayName: 'Tertiary Outline Radio Button Tick Color',
		name: 'tertiaryOutlineRadioButtonTickColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'background',
		selector: '.comp.compRadioButton._outlined._tertiary .commonCheckbox ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Tick Color',
		displayName: 'Quaternary Outline Radio Button Tick Color',
		name: 'quaternaryOutlineRadioButtonTickColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'background',
		selector: '.comp.compRadioButton._outlined._quaternary .commonCheckbox ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Tick Color',
		displayName: 'Quinary Outline Radio Button Tick Color',
		name: 'quinaryOutlineRadioButtonTickColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compRadioButton._outlined._quinary .commonCheckbox ._thumb',
		noPrefix: true,
	},

	{
		groupName: 'Border Color',
		displayName: 'Outline Disabled Radio Button Border Color',
		name: 'outlineDisabledRadioButtonBorderColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'border-color',
		selector:
			'.comp.compRadioButton._outlined._primary .commonCheckbox._disabled,.comp.compRadioButton._outlined._secondary .commonCheckbox._disabled,.comp.compRadioButton._outlined._tertiary .commonCheckbox._disabled,.comp.compRadioButton._outlined._quaternary .commonCheckbox._disabled,.comp.compRadioButton._outlined._quinary .commonCheckbox._disabled',
		noPrefix: true,
	},
	{
		groupName: 'Background Color',
		displayName: 'Default Disabled Radio Button Background',
		name: 'defaultDisabledRadioButtonBackground',
		defaultValue: '<backgroundColorEight>',
		cssProperty: 'background',
		selector:
			'.comp.compRadioButton._default._primary .commonCheckbox._disabled,.comp.compRadioButton._default._secondary .commonCheckbox._disabled,.comp.compRadioButton._default._tertiary .commonCheckbox._disabled,.comp.compRadioButton._default._quaternary .commonCheckbox._disabled,.comp.compRadioButton._default._quinary .commonCheckbox._disabled',
		noPrefix: true,
	},
	{
		groupName: 'Tick Color',
		displayName: ' Outline Disabled Radio Button Tick Color',
		name: ' OutlineDisabledRadioButtonTickColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'background',
		selector:
			'.comp.compRadioButton._outlined._primary .commonCheckbox._disabled ._thumb,.comp.compRadioButton._outlined._secondary .commonCheckbox._disabled ._thumb,.comp.compRadioButton._outlined._tertiary .commonCheckbox._disabled ._thumb,.comp.compRadioButton._outlined._quaternary .commonCheckbox._disabled ._thumb,.comp.compRadioButton._outlined._quinary .commonCheckbox._disabled ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Outline Disabled Radio Button Font Color',
		name: 'outlineDisabledRadioButtonFontColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector: '.comp.compRadioButton._outlined label._disabled',
		noPrefix: true,
	},

	{
		groupName: 'Font Color',
		displayName: 'Primary Outline Radio Button Font Color',
		name: 'primaryOutlineRadioButtonFontColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector: '.comp.compRadioButton._outlined._primary',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Secondary Outline Radio Button Font Color',
		name: 'secondaryOutlineRadioButtonFontColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector: '.comp.compRadioButton._outlined._secondary',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Tertiary Outline Radio Button Font Color',
		name: 'tertiaryOutlineRadioButtonFontColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector: '.comp.compRadioButton._outlined._tertiary',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Quaternary Outline Radio Button Font Color',
		name: 'quaternaryOutlineRadioButtonFontColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector: '.comp.compRadioButton._outlined._quaternary',
		noPrefix: true,
	},
	{
		groupName: 'Font Color',
		displayName: 'Quinary Outline Radio Button Font Color',
		name: 'quinaryOutlineRadioButtonFontColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector: '.comp.compRadioButton._outlined._quinary',
		noPrefix: true,
	},

	{
		groupName: 'Gap',
		displayName: 'Radio Button Group Gap',
		name: 'radioButtonGroupGap',
		defaultValue: '5px',
		cssProperty: 'gap',
		selector: '.comp.compRadioButton',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
