import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		name: 'design1HeaderPadding',
		cssProperty: 'padding',
		displayName: 'Design 1 Header Padding',
		description: 'Design 1 Header Padding',
		defaultValue: '5px',
	},
	{
		name: 'design3HeaderPadding',
		cssProperty: 'padding',
		displayName: 'Design 3 Header Padding',
		description: 'Design 3 Header Padding',
		defaultValue: '5px',
	},
	{
		name: 'design5HeaderPadding',
		cssProperty: 'padding',
		displayName: 'Design 5 Header Padding',
		description: 'Design 5 Header Padding',
		defaultValue: '5px',
	},
	{
		name: 'design7HeaderPadding',
		cssProperty: 'padding',
		displayName: 'Design 7 Header Padding',
		description: 'Design 7 Header Padding',
		defaultValue: '5px',
	},
	{
		name: 'design9HeaderPadding',
		cssProperty: 'padding',
		displayName: 'Design 9 Header Padding',
		description: 'Design 9 Header Padding',
		defaultValue: '5px',
	},

	{
		name: 'design2HeaderPadding',
		cssProperty: 'padding',
		displayName: 'Design 2 Header Padding',
		description: 'Design 2 Header Padding',
		defaultValue: '7px',
	},
	{
		name: 'design4HeaderPadding',
		cssProperty: 'padding',
		displayName: 'Design 4 Header Padding',
		description: 'Design 4 Header Padding',
		defaultValue: '0px',
	},
	{
		name: 'design6HeaderPadding',
		cssProperty: 'padding',
		displayName: 'Design 6 Header Padding',
		description: 'Design 6 Header Padding',
		defaultValue: '0px',
	},
	{
		name: 'design8HeaderPadding',
		cssProperty: 'padding',
		displayName: 'Design 8 Header Padding',
		description: 'Design 8 Header Padding',
		defaultValue: '0px',
	},
	{
		name: 'design10HeaderPadding',
		cssProperty: 'padding',
		displayName: 'Design 10 Header Padding',
		description: 'Design 10 Header Padding',
		defaultValue: '0px',
	},

	{
		name: 'design1HeaderBorderBottom',
		cssProperty: 'border-bottom',
		displayName: 'Design 1 Header Border Bottom',
		description: 'Design 1 Header Border Bottom',
		noPrefix: true,
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
	},
	{
		name: 'design2HeaderBorderBottom',
		cssProperty: 'border-bottom',
		displayName: 'Design 2 Header Border Bottom',
		description: 'Design 2 Header Border Bottom',
		defaultValue: '1px solid #ddd',
		noPrefix: true,
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
	},
	{
		name: 'design3HeaderBorderBottom',
		cssProperty: 'border-bottom',
		displayName: 'Design 3 Header Border Bottom',
		description: 'Design 3 Header Border Bottom',
		noPrefix: true,
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
	},
	{
		name: 'design4HeaderBorderBottom',
		cssProperty: 'border-bottom',
		displayName: 'Design 4 Header Border Bottom',
		description: 'Design 4 Header Border Bottom',
		noPrefix: true,
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
	},
	{
		name: 'design5HeaderBorderBottom',
		cssProperty: 'border-bottom',
		displayName: 'Design 5 Header Border Bottom',
		description: 'Design 5 Header Border Bottom',
		noPrefix: true,
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
	},
	{
		name: 'design6HeaderBorderBottom',
		cssProperty: 'border-bottom',
		displayName: 'Design 6 Header Border Bottom',
		description: 'Design 6 Header Border Bottom',
		noPrefix: true,
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
	},
	{
		name: 'design7HeaderBorderBottom',
		cssProperty: 'border-bottom',
		displayName: 'Design 7 Header Border Bottom',
		description: 'Design 7 Header Border Bottom',
		noPrefix: true,
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
	},
	{
		name: 'design8HeaderBorderBottom',
		cssProperty: 'border-bottom',
		displayName: 'Design 8 Header Border Bottom',
		description: 'Design 8 Header Border Bottom',
		noPrefix: true,
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
	},
	{
		name: 'design9HeaderBorderBottom',
		cssProperty: 'border-bottom',
		displayName: 'Design 9 Header Border Bottom',
		description: 'Design 9 Header Border Bottom',
		noPrefix: true,
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
	},
	{
		name: 'design10HeaderBorderBottom',
		cssProperty: 'border-bottom',
		displayName: 'Design 10 Header Border Bottom',
		description: 'Design 10 Header Border Bottom',
		noPrefix: true,
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
	},

	{
		name: 'design1HeaderFontColor',
		cssProperty: 'color',
		displayName: 'Design 1 Header Font Color',
		description: 'Design 1 Header Font Color',
		noPrefix: true,
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
	},
	{
		name: 'design2HeaderFontColor',
		cssProperty: 'color',
		displayName: 'Design 2 Header Font Color',
		description: 'Design 2 Header Font Color',
		noPrefix: true,
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
	},
	{
		name: 'design3HeaderFontColor',
		cssProperty: 'color',
		displayName: 'Design 3 Header Font Color',
		description: 'Design 3 Header Font Color',
		noPrefix: true,
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
	},
	{
		name: 'design4HeaderFontColor',
		cssProperty: 'color',
		displayName: 'Design 4 Header Font Color',
		description: 'Design 4 Header Font Color',
		noPrefix: true,
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
	},
	{
		name: 'design5HeaderFontColor',
		cssProperty: 'color',
		displayName: 'Design 5 Header Font Color',
		description: 'Design 5 Header Font Color',
		noPrefix: true,
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
	},
	{
		name: 'design6HeaderFontColor',
		cssProperty: 'color',
		displayName: 'Design 6 Header Font Color',
		description: 'Design 6 Header Font Color',
		noPrefix: true,
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
	},
	{
		name: 'design7HeaderFontColor',
		cssProperty: 'color',
		displayName: 'Design 7 Header Font Color',
		description: 'Design 7 Header Font Color',
		noPrefix: true,
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
	},
	{
		name: 'design8HeaderFontColor',
		cssProperty: 'color',
		displayName: 'Design 8 Header Font Color',
		description: 'Design 8 Header Font Color',
		noPrefix: true,
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
	},
	{
		name: 'design9HeaderFontColor',
		cssProperty: 'color',
		displayName: 'Design 9 Header Font Color',
		description: 'Design 9 Header Font Color',
		noPrefix: true,
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
	},
	{
		name: 'design10HeaderFontColor',
		cssProperty: 'color',
		displayName: 'Design 10 Header Font Color',
		description: 'Design 10 Header Font Color',
		noPrefix: true,
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
	},

	{
		name: 'design1HeaderFontSize',
		cssProperty: 'font-size',
		displayName: 'Design 1 Header Font Size',
		description: 'Design 1 Header Font Size',
		noPrefix: true,
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
	},
	{
		name: 'design2HeaderFontSize',
		cssProperty: 'font-size',
		displayName: 'Design 2 Header Font Size',
		description: 'Design 2 Header Font Size',
		noPrefix: true,
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
	},
	{
		name: 'design3HeaderFontSize',
		cssProperty: 'font-size',
		displayName: 'Design 3 Header Font Size',
		description: 'Design 3 Header Font Size',
		noPrefix: true,
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
	},
	{
		name: 'design4HeaderFontSize',
		cssProperty: 'font-size',
		displayName: 'Design 4 Header Font Size',
		description: 'Design 4 Header Font Size',
		noPrefix: true,
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
	},
	{
		name: 'design5HeaderFontSize',
		cssProperty: 'font-size',
		displayName: 'Design 5 Header Font Size',
		description: 'Design 5 Header Font Size',
		noPrefix: true,
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
	},
	{
		name: 'design6HeaderFontSize',
		cssProperty: 'font-size',
		displayName: 'Design 6 Header Font Size',
		description: 'Design 6 Header Font Size',
		noPrefix: true,
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
	},
	{
		name: 'design7HeaderFontSize',
		cssProperty: 'font-size',
		displayName: 'Design 7 Header Font Size',
		description: 'Design 7 Header Font Size',
		noPrefix: true,
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
	},
	{
		name: 'design8HeaderFontSize',
		cssProperty: 'font-size',
		displayName: 'Design 8 Header Font Size',
		description: 'Design 8 Header Font Size',
		noPrefix: true,
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
	},
	{
		name: 'design9HeaderFontSize',
		cssProperty: 'font-size',
		displayName: 'Design 9 Header Font Size',
		description: 'Design 9 Header Font Size',
		noPrefix: true,
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
	},
	{
		name: 'design10HeaderFontSize',
		cssProperty: 'font-size',
		displayName: 'Design 10 Header Font Size',
		description: 'Design 10 Header Font Size',
		noPrefix: true,
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
	},

	{
		name: 'design1HeaderFontFamily',
		cssProperty: 'font-family',
		displayName: 'Design 1 Header Font Family',
		description: 'Design 1 Header Font Family',
		noPrefix: true,
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
	},
	{
		name: 'design2HeaderFontFamily',
		cssProperty: 'font-family',
		displayName: 'Design 2 Header Font Family',
		description: 'Design 2 Header Font Family',
		noPrefix: true,
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
	},
	{
		name: 'design3HeaderFontFamily',
		cssProperty: 'font-family',
		displayName: 'Design 3 Header Font Family',
		description: 'Design 3 Header Font Family',
		noPrefix: true,
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
	},
	{
		name: 'design4HeaderFontFamily',
		cssProperty: 'font-family',
		displayName: 'Design 4 Header Font Family',
		description: 'Design 4 Header Font Family',
		noPrefix: true,
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
	},
	{
		name: 'design5HeaderFontFamily',
		cssProperty: 'font-family',
		displayName: 'Design 5 Header Font Family',
		description: 'Design 5 Header Font Family',
		noPrefix: true,
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
	},
	{
		name: 'design6HeaderFontFamily',
		cssProperty: 'font-family',
		displayName: 'Design 6 Header Font Family',
		description: 'Design 6 Header Font Family',
		noPrefix: true,
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
	},
	{
		name: 'design7HeaderFontFamily',
		cssProperty: 'font-family',
		displayName: 'Design 7 Header Font Family',
		description: 'Design 7 Header Font Family',
		noPrefix: true,
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
	},
	{
		name: 'design8HeaderFontFamily',
		cssProperty: 'font-family',
		displayName: 'Design 8 Header Font Family',
		description: 'Design 8 Header Font Family',
		noPrefix: true,
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
	},
	{
		name: 'design9HeaderFontFamily',
		cssProperty: 'font-family',
		displayName: 'Design 9 Header Font Family',
		description: 'Design 9 Header Font Family',
		noPrefix: true,
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
	},
	{
		name: 'design10HeaderFontFamily',
		cssProperty: 'font-family',
		displayName: 'Design 10 Header Font Family',
		description: 'Design 10 Header Font Family',
		noPrefix: true,
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
	},

	{
		name: 'design1HeaderFontWeight',
		cssProperty: 'font-weight',
		displayName: 'Design 1 Header Font Weight',
		description: 'Design 1 Header Font Weight',
		defaultValue: 'bold',
		noPrefix: true,
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
	},
	{
		name: 'design2HeaderFontWeight',
		cssProperty: 'font-weight',
		displayName: 'Design 2 Header Font Weight',
		description: 'Design 2 Header Font Weight',
		noPrefix: true,
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
	},
	{
		name: 'design3HeaderFontWeight',
		cssProperty: 'font-weight',
		displayName: 'Design 3 Header Font Weight',
		description: 'Design 3 Header Font Weight',
		noPrefix: true,
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
	},
	{
		name: 'design4HeaderFontWeight',
		cssProperty: 'font-weight',
		displayName: 'Design 4 Header Font Weight',
		description: 'Design 4 Header Font Weight',
		noPrefix: true,
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
	},
	{
		name: 'design5HeaderFontWeight',
		cssProperty: 'font-weight',
		displayName: 'Design 5 Header Font Weight',
		description: 'Design 5 Header Font Weight',
		noPrefix: true,
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
	},
	{
		name: 'design6HeaderFontWeight',
		cssProperty: 'font-weight',
		displayName: 'Design 6 Header Font Weight',
		description: 'Design 6 Header Font Weight',
		noPrefix: true,
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
	},
	{
		name: 'design7HeaderFontWeight',
		cssProperty: 'font-weight',
		displayName: 'Design 7 Header Font Weight',
		description: 'Design 7 Header Font Weight',
		noPrefix: true,
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
	},
	{
		name: 'design8HeaderFontWeight',
		cssProperty: 'font-weight',
		displayName: 'Design 8 Header Font Weight',
		description: 'Design 8 Header Font Weight',
		noPrefix: true,
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
	},
	{
		name: 'design9HeaderFontWeight',
		cssProperty: 'font-weight',
		displayName: 'Design 9 Header Font Weight',
		description: 'Design 9 Header Font Weight',
		noPrefix: true,
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
	},
	{
		name: 'design10HeaderFontWeight',
		cssProperty: 'font-weight',
		displayName: 'Design 10 Header Font Weight',
		description: 'Design 10 Header Font Weight',
		noPrefix: true,
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
	},

	{
		name: 'design1HeaderBorderTop',
		cssProperty: 'border-bottom',
		displayName: 'Design 1 Header Border Top',
		description: 'Design 1 Header Border Top',
		noPrefix: true,
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
	},
	{
		name: 'design2HeaderBorderTop',
		cssProperty: 'border-bottom',
		displayName: 'Design 2 Header Border Top',
		description: 'Design 2 Header Border Top',
		noPrefix: true,
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
	},
	{
		name: 'design3HeaderBorderTop',
		cssProperty: 'border-bottom',
		displayName: 'Design 3 Header Border Top',
		description: 'Design 3 Header Border Top',
		noPrefix: true,
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
	},
	{
		name: 'design4HeaderBorderTop',
		cssProperty: 'border-bottom',
		displayName: 'Design 4 Header Border Top',
		description: 'Design 4 Header Border Top',
		noPrefix: true,
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
	},
	{
		name: 'design5HeaderBorderTop',
		cssProperty: 'border-bottom',
		displayName: 'Design 5 Header Border Top',
		description: 'Design 5 Header Border Top',
		noPrefix: true,
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
	},
	{
		name: 'design6HeaderBorderTop',
		cssProperty: 'border-bottom',
		displayName: 'Design 6 Header Border Top',
		description: 'Design 6 Header Border Top',
		noPrefix: true,
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
	},
	{
		name: 'design7HeaderBorderTop',
		cssProperty: 'border-bottom',
		displayName: 'Design 7 Header Border Top',
		description: 'Design 7 Header Border Top',
		noPrefix: true,
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
	},
	{
		name: 'design8HeaderBorderTop',
		cssProperty: 'border-bottom',
		displayName: 'Design 8 Header Border Top',
		description: 'Design 8 Header Border Top',
		noPrefix: true,
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
	},
	{
		name: 'design9HeaderBorderTop',
		cssProperty: 'border-bottom',
		displayName: 'Design 9 Header Border Top',
		description: 'Design 9 Header Border Top',
		noPrefix: true,
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
	},
	{
		name: 'design10HeaderBorderTop',
		cssProperty: 'border-bottom',
		displayName: 'Design 10 Header Border Top',
		description: 'Design 10 Header Border Top',
		noPrefix: true,
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
	},

	{
		name: 'design1HeaderBorderLeft',
		cssProperty: 'border-bottom',
		displayName: 'Design 1 Header Border Left',
		description: 'Design 1 Header Border Left',
		noPrefix: true,
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
	},
	{
		name: 'design2HeaderBorderLeft',
		cssProperty: 'border-bottom',
		displayName: 'Design 2 Header Border Left',
		description: 'Design 2 Header Border Left',
		noPrefix: true,
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
	},
	{
		name: 'design3HeaderBorderLeft',
		cssProperty: 'border-bottom',
		displayName: 'Design 3 Header Border Left',
		description: 'Design 3 Header Border Left',
		noPrefix: true,
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
	},
	{
		name: 'design4HeaderBorderLeft',
		cssProperty: 'border-bottom',
		displayName: 'Design 4 Header Border Left',
		description: 'Design 4 Header Border Left',
		noPrefix: true,
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
	},
	{
		name: 'design5HeaderBorderLeft',
		cssProperty: 'border-bottom',
		displayName: 'Design 5 Header Border Left',
		description: 'Design 5 Header Border Left',
		noPrefix: true,
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
	},
	{
		name: 'design6HeaderBorderLeft',
		cssProperty: 'border-bottom',
		displayName: 'Design 6 Header Border Left',
		description: 'Design 6 Header Border Left',
		noPrefix: true,
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
	},
	{
		name: 'design7HeaderBorderLeft',
		cssProperty: 'border-bottom',
		displayName: 'Design 7 Header Border Left',
		description: 'Design 7 Header Border Left',
		noPrefix: true,
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
	},
	{
		name: 'design8HeaderBorderLeft',
		cssProperty: 'border-bottom',
		displayName: 'Design 8 Header Border Left',
		description: 'Design 8 Header Border Left',
		noPrefix: true,
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
	},
	{
		name: 'design9HeaderBorderLeft',
		cssProperty: 'border-bottom',
		displayName: 'Design 9 Header Border Left',
		description: 'Design 9 Header Border Left',
		noPrefix: true,
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
	},
	{
		name: 'design10HeaderBorderLeft',
		cssProperty: 'border-bottom',
		displayName: 'Design 10 Header Border Left',
		description: 'Design 10 Header Border Left',
		noPrefix: true,
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
	},

	{
		name: 'design1HeaderBorderRight',
		cssProperty: 'border-bottom',
		displayName: 'Design 1 Header Border Right',
		description: 'Design 1 Header Border Right',
		noPrefix: true,
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
	},
	{
		name: 'design2HeaderBorderRight',
		cssProperty: 'border-bottom',
		displayName: 'Design 2 Header Border Right',
		description: 'Design 2 Header Border Right',
		noPrefix: true,
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
	},
	{
		name: 'design3HeaderBorderRight',
		cssProperty: 'border-bottom',
		displayName: 'Design 3 Header Border Right',
		description: 'Design 3 Header Border Right',
		noPrefix: true,
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
	},
	{
		name: 'design4HeaderBorderRight',
		cssProperty: 'border-bottom',
		displayName: 'Design 4 Header Border Right',
		description: 'Design 4 Header Border Right',
		noPrefix: true,
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
	},
	{
		name: 'design5HeaderBorderRight',
		cssProperty: 'border-bottom',
		displayName: 'Design 5 Header Border Right',
		description: 'Design 5 Header Border Right',
		noPrefix: true,
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
	},
	{
		name: 'design6HeaderBorderRight',
		cssProperty: 'border-bottom',
		displayName: 'Design 6 Header Border Right',
		description: 'Design 6 Header Border Right',
		noPrefix: true,
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
	},
	{
		name: 'design7HeaderBorderRight',
		cssProperty: 'border-bottom',
		displayName: 'Design 7 Header Border Right',
		description: 'Design 7 Header Border Right',
		noPrefix: true,
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
	},
	{
		name: 'design8HeaderBorderRight',
		cssProperty: 'border-bottom',
		displayName: 'Design 8 Header Border Right',
		description: 'Design 8 Header Border Right',
		noPrefix: true,
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
	},
	{
		name: 'design9HeaderBorderRight',
		cssProperty: 'border-bottom',
		displayName: 'Design 9 Header Border Right',
		description: 'Design 9 Header Border Right',
		noPrefix: true,
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
	},
	{
		name: 'design10HeaderBorderRight',
		cssProperty: 'border-bottom',
		displayName: 'Design 10 Header Border Right',
		description: 'Design 10 Header Border Right',
		noPrefix: true,
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
