import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'Header Padding',
		displayName: 'Design 1 Header Padding',
		name: 'design1HeaderPadding',
		defaultValue: '5px',
		description: 'Design 1 Header Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Header Padding',
		displayName: 'Design 2 Header Padding',
		name: 'design2HeaderPadding',
		defaultValue: '7px',
		description: 'Design 2 Header Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Header Padding',
		displayName: 'Design 3 Header Padding',
		name: 'design3HeaderPadding',
		defaultValue: '5px',
		description: 'Design 3 Header Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Header Padding',
		displayName: 'Design 4 Header Padding',
		name: 'design4HeaderPadding',
		defaultValue: '5px',
		description: 'Design 4 Header Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Header Padding',
		displayName: 'Design 5 Header Padding',
		name: 'design5HeaderPadding',
		defaultValue: '5px',
		description: 'Design 5 Header Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Header Padding',
		displayName: 'Design 6 Header Padding',
		name: 'design6HeaderPadding',
		defaultValue: '0px',
		description: 'Design 6 Header Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Header Padding',
		displayName: 'Design 7 Header Padding',
		name: 'design7HeaderPadding',
		defaultValue: '5px',
		description: 'Design 7 Header Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Header Padding',
		displayName: 'Design 8 Header Padding',
		name: 'design8HeaderPadding',
		defaultValue: '0px',
		description: 'Design 8 Header Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Header Padding',
		displayName: 'Design 9 Header Padding',
		name: 'design9HeaderPadding',
		defaultValue: '5px',
		description: 'Design 9 Header Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},
	{
		groupName: 'Header Padding',
		displayName: 'Design 10 Header Padding',
		name: 'design10HeaderPadding',
		defaultValue: '0px',
		description: 'Design 10 Header Padding',
		cssProperty: 'padding',
		noPrefix: true,
	},

	{
		groupName: 'Header Border Bottom',
		displayName: 'Design 1 Header Border Bottom',
		name: 'design1HeaderBorderBottom',
		description: 'Design 1 Header Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Bottom',
		displayName: 'Design 2 Header Border Bottom',
		name: 'design2HeaderBorderBottom',
		defaultValue: '1px solid #ddd',
		description: 'Design 2 Header Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Bottom',
		displayName: 'Design 3 Header Border Bottom',
		name: 'design3HeaderBorderBottom',
		description: 'Design 3 Header Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Bottom',
		displayName: 'Design 4 Header Border Bottom',
		name: 'design4HeaderBorderBottom',
		description: 'Design 4 Header Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Bottom',
		displayName: 'Design 5 Header Border Bottom',
		name: 'design5HeaderBorderBottom',
		description: 'Design 5 Header Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Bottom',
		displayName: 'Design 6 Header Border Bottom',
		name: 'design6HeaderBorderBottom',
		description: 'Design 6 Header Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Bottom',
		displayName: 'Design 7 Header Border Bottom',
		name: 'design7HeaderBorderBottom',
		description: 'Design 7 Header Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Bottom',
		displayName: 'Design 8 Header Border Bottom',
		name: 'design8HeaderBorderBottom',
		description: 'Design 8 Header Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Bottom',
		displayName: 'Design 9 Header Border Bottom',
		name: 'design9HeaderBorderBottom',
		description: 'Design 9 Header Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Bottom',
		displayName: 'Design 10 Header Border Bottom',
		name: 'design10HeaderBorderBottom',
		description: 'Design 10 Header Border Bottom',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
		noPrefix: true,
	},

	{
		groupName: 'Header Font Color',
		displayName: 'Design 1 Header Font Color',
		name: 'design1HeaderFontColor',
		description: 'Design 1 Header Font Color',
		cssProperty: 'color',
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Color',
		displayName: 'Design 2 Header Font Color',
		name: 'design2HeaderFontColor',
		description: 'Design 2 Header Font Color',
		cssProperty: 'color',
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Color',
		displayName: 'Design 3 Header Font Color',
		name: 'design3HeaderFontColor',
		description: 'Design 3 Header Font Color',
		cssProperty: 'color',
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Color',
		displayName: 'Design 4 Header Font Color',
		name: 'design4HeaderFontColor',
		defaultValue: '#FFFFFF',
		description: 'Design 4 Header Font Color',
		cssProperty: 'color',
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Color',
		displayName: 'Design 5 Header Font Color',
		name: 'design5HeaderFontColor',
		description: 'Design 5 Header Font Color',
		cssProperty: 'color',
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Color',
		displayName: 'Design 6 Header Font Color',
		name: 'design6HeaderFontColor',
		description: 'Design 6 Header Font Color',
		cssProperty: 'color',
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Color',
		displayName: 'Design 7 Header Font Color',
		name: 'design7HeaderFontColor',
		description: 'Design 7 Header Font Color',
		cssProperty: 'color',
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Color',
		displayName: 'Design 8 Header Font Color',
		name: 'design8HeaderFontColor',
		description: 'Design 8 Header Font Color',
		cssProperty: 'color',
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Color',
		displayName: 'Design 9 Header Font Color',
		name: 'design9HeaderFontColor',
		description: 'Design 9 Header Font Color',
		cssProperty: 'color',
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Color',
		displayName: 'Design 10 Header Font Color',
		name: 'design10HeaderFontColor',
		description: 'Design 10 Header Font Color',
		cssProperty: 'color',
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
		noPrefix: true,
	},

	{
		groupName: 'Header Font Size',
		displayName: 'Design 1 Header Font Size',
		name: 'design1HeaderFontSize',
		description: 'Design 1 Header Font Size',
		cssProperty: 'font-size',
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Size',
		displayName: 'Design 2 Header Font Size',
		name: 'design2HeaderFontSize',
		description: 'Design 2 Header Font Size',
		cssProperty: 'font-size',
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Size',
		displayName: 'Design 3 Header Font Size',
		name: 'design3HeaderFontSize',
		description: 'Design 3 Header Font Size',
		cssProperty: 'font-size',
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Size',
		displayName: 'Design 4 Header Font Size',
		name: 'design4HeaderFontSize',
		defaultValue: '16px',
		description: 'Design 4 Header Font Size',
		cssProperty: 'font-size',
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Size',
		displayName: 'Design 5 Header Font Size',
		name: 'design5HeaderFontSize',
		description: 'Design 5 Header Font Size',
		cssProperty: 'font-size',
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Size',
		displayName: 'Design 6 Header Font Size',
		name: 'design6HeaderFontSize',
		description: 'Design 6 Header Font Size',
		cssProperty: 'font-size',
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Size',
		displayName: 'Design 7 Header Font Size',
		name: 'design7HeaderFontSize',
		description: 'Design 7 Header Font Size',
		cssProperty: 'font-size',
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Size',
		displayName: 'Design 8 Header Font Size',
		name: 'design8HeaderFontSize',
		description: 'Design 8 Header Font Size',
		cssProperty: 'font-size',
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Size',
		displayName: 'Design 9 Header Font Size',
		name: 'design9HeaderFontSize',
		description: 'Design 9 Header Font Size',
		cssProperty: 'font-size',
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Size',
		displayName: 'Design 10 Header Font Size',
		name: 'design10HeaderFontSize',
		description: 'Design 10 Header Font Size',
		cssProperty: 'font-size',
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
		noPrefix: true,
	},

	{
		groupName: 'Header Font Family',
		displayName: 'Design 1 Header Font Family',
		name: 'design1HeaderFontFamily',
		description: 'Design 1 Header Font Family',
		cssProperty: 'font-family',
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Family',
		displayName: 'Design 2 Header Font Family',
		name: 'design2HeaderFontFamily',
		description: 'Design 2 Header Font Family',
		cssProperty: 'font-family',
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Family',
		displayName: 'Design 3 Header Font Family',
		name: 'design3HeaderFontFamily',
		description: 'Design 3 Header Font Family',
		cssProperty: 'font-family',
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Family',
		displayName: 'Design 4 Header Font Family',
		name: 'design4HeaderFontFamily',
		defaultValue: 'Inter',
		description: 'Design 4 Header Font Family',
		cssProperty: 'font-family',
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Family',
		displayName: 'Design 5 Header Font Family',
		name: 'design5HeaderFontFamily',
		description: 'Design 5 Header Font Family',
		cssProperty: 'font-family',
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Family',
		displayName: 'Design 6 Header Font Family',
		name: 'design6HeaderFontFamily',
		description: 'Design 6 Header Font Family',
		cssProperty: 'font-family',
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Family',
		displayName: 'Design 7 Header Font Family',
		name: 'design7HeaderFontFamily',
		description: 'Design 7 Header Font Family',
		cssProperty: 'font-family',
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Family',
		displayName: 'Design 8 Header Font Family',
		name: 'design8HeaderFontFamily',
		description: 'Design 8 Header Font Family',
		cssProperty: 'font-family',
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Family',
		displayName: 'Design 9 Header Font Family',
		name: 'design9HeaderFontFamily',
		description: 'Design 9 Header Font Family',
		cssProperty: 'font-family',
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Family',
		displayName: 'Design 10 Header Font Family',
		name: 'design10HeaderFontFamily',
		description: 'Design 10 Header Font Family',
		cssProperty: 'font-family',
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
		noPrefix: true,
	},

	{
		groupName: 'Header Font Weight',
		displayName: 'Design 1 Header Font Weight',
		name: 'design1HeaderFontWeight',
		description: 'Design 1 Header Font Weight',
		cssProperty: 'font-weight',
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Weight',
		displayName: 'Design 2 Header Font Weight',
		name: 'design2HeaderFontWeight',
		description: 'Design 2 Header Font Weight',
		cssProperty: 'font-weight',
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Weight',
		displayName: 'Design 3 Header Font Weight',
		name: 'design3HeaderFontWeight',
		description: 'Design 3 Header Font Weight',
		cssProperty: 'font-weight',
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Weight',
		displayName: 'Design 4 Header Font Weight',
		name: 'design4HeaderFontWeight',
		defaultValue: '700',
		description: 'Design 4 Header Font Weight',
		cssProperty: 'font-weight',
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Weight',
		displayName: 'Design 5 Header Font Weight',
		name: 'design5HeaderFontWeight',
		description: 'Design 5 Header Font Weight',
		cssProperty: 'font-weight',
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Weight',
		displayName: 'Design 6 Header Font Weight',
		name: 'design6HeaderFontWeight',
		description: 'Design 6 Header Font Weight',
		cssProperty: 'font-weight',
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Weight',
		displayName: 'Design 7 Header Font Weight',
		name: 'design7HeaderFontWeight',
		description: 'Design 7 Header Font Weight',
		cssProperty: 'font-weight',
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Weight',
		displayName: 'Design 8 Header Font Weight',
		name: 'design8HeaderFontWeight',
		description: 'Design 8 Header Font Weight',
		cssProperty: 'font-weight',
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Weight',
		displayName: 'Design 9 Header Font Weight',
		name: 'design9HeaderFontWeight',
		description: 'Design 9 Header Font Weight',
		cssProperty: 'font-weight',
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Font Weight',
		displayName: 'Design 10 Header Font Weight',
		name: 'design10HeaderFontWeight',
		description: 'Design 10 Header Font Weight',
		cssProperty: 'font-weight',
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
		noPrefix: true,
	},

	{
		groupName: 'Header Border Top',
		displayName: 'Design 1 Header Border Top',
		name: 'design1HeaderBorderTop',
		description: 'Design 1 Header Font Border Top',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Top',
		displayName: 'Design 2 Header Border Top',
		name: 'design2HeaderBorderTop',
		description: 'Design 2 Header Font Border Top',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Top',
		displayName: 'Design 3 Header Border Top',
		name: 'design3HeaderBorderTop',
		description: 'Design 3 Header Font Border Top',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Top',
		displayName: 'Design 4 Header Border Top',
		name: 'design4HeaderBorderTop',
		description: 'Design 4 Header Font Border Top',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Top',
		displayName: 'Design 5 Header Border Top',
		name: 'design5HeaderBorderTop',
		description: 'Design 5 Header Font Border Top',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Top',
		displayName: 'Design 6 Header Border Top',
		name: 'design6HeaderBorderTop',
		description: 'Design 6 Header Font Border Top',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Top',
		displayName: 'Design 7 Header Border Top',
		name: 'design7HeaderBorderTop',
		description: 'Design 7 Header Font Border Top',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Top',
		displayName: 'Design 8 Header Border Top',
		name: 'design8HeaderBorderTop',
		description: 'Design 8 Header Font Border Top',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Top',
		displayName: 'Design 9 Header Border Top',
		name: 'design9HeaderBorderTop',
		description: 'Design 9 Header Font Border Top',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Top',
		displayName: 'Design 10 Header Border Top',
		name: 'design10HeaderBorderTop',
		description: 'Design 10 Header Font Border Top',
		cssProperty: 'border-bottom',
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
		noPrefix: true,
	},

	{
		groupName: 'Header Border Right',
		displayName: 'Design 1 Header Border Right',
		name: 'design1HeaderBorderRight',
		description: 'Design 1 Header Font Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Right',
		displayName: 'Design 2 Header Border Right',
		name: 'design2HeaderBorderRight',
		description: 'Design 2 Header Font Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Right',
		displayName: 'Design 3 Header Border Right',
		name: 'design3HeaderBorderRight',
		description: 'Design 3 Header Font Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Right',
		displayName: 'Design 4 Header Border Right',
		name: 'design4HeaderBorderRight',
		description: 'Design 4 Header Font Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Right',
		displayName: 'Design 5 Header Border Right',
		name: 'design5HeaderBorderRight',
		description: 'Design 5 Header Font Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Right',
		displayName: 'Design 6 Header Border Right',
		name: 'design6HeaderBorderRight',
		description: 'Design 6 Header Font Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Right',
		displayName: 'Design 7 Header Border Right',
		name: 'design7HeaderBorderRight',
		description: 'Design 7 Header Font Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Right',
		displayName: 'Design 8 Header Border Right',
		name: 'design8HeaderBorderRight',
		description: 'Design 8 Header Font Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Right',
		displayName: 'Design 9 Header Border Right',
		name: 'design9HeaderBorderRight',
		description: 'Design 9 Header Font Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Right',
		displayName: 'Design 10 Header Border Right',
		name: 'design10HeaderBorderRight',
		description: 'Design 10 Header Font Border Right',
		cssProperty: 'border-right',
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
		noPrefix: true,
	},

	{
		groupName: 'Header Border Left',
		displayName: 'Design 1 Header Border Left',
		name: 'design1HeaderBorderLeft',
		description: 'Design 1 Header Font Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design1 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Left',
		displayName: 'Design 2 Header Border Left',
		name: 'design2HeaderBorderLeft',
		description: 'Design 2 Header Font Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design2 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Left',
		displayName: 'Design 3 Header Border Left',
		name: 'design3HeaderBorderLeft',
		description: 'Design 3 Header Font Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design3 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Left',
		displayName: 'Design 4 Header Border Left',
		name: 'design4HeaderBorderLeft',
		description: 'Design 4 Header Font Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design4 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Left',
		displayName: 'Design 5 Header Border Left',
		name: 'design5HeaderBorderLeft',
		description: 'Design 5 Header Font Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design5 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Left',
		displayName: 'Design 6 Header Border Left',
		name: 'design6HeaderBorderLeft',
		description: 'Design 6 Header Font Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design6 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Left',
		displayName: 'Design 7 Header Border Left',
		name: 'design7HeaderBorderLeft',
		description: 'Design 7 Header Font Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design7 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Left',
		displayName: 'Design 8 Header Border Left',
		name: 'design8HeaderBorderLeft',
		description: 'Design 8 Header Font Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design8 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Left',
		displayName: 'Design 9 Header Border Left',
		name: 'design9HeaderBorderLeft',
		description: 'Design 9 Header Font Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design9 .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Left',
		displayName: 'Design 10 Header Border Left',
		name: 'design10HeaderBorderLeft',
		description: 'Design 10 Header Font Border Left',
		cssProperty: 'border-left',
		selector: '.comp.compTable._design10 .comp.compTableHeaderColumn',
		noPrefix: true,
	},

	{
		groupName: 'Header Background Color',
		displayName: 'Header Background Color Primary Design4',
		name: 'headerBackgroundColorPrimaryDesign4',
		defaultValue: '<fontColorThree>',
		description: 'Header Background Color Primary Design4',
		cssProperty: 'background-color',
		selector: '.comp.compTable._design4._primary .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Background Color',
		displayName: 'Header Background Color SecondaryDesign4',
		name: 'headerBackgroundColorSecondaryDesign4',
		defaultValue: '<fontColorFour>',
		description: 'Header Background Color SecondaryDesign4',
		cssProperty: 'background-color',
		selector: '.comp.compTable._design4._secondary .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Background Color',
		displayName: 'Header Background Color TertiaryDesign4',
		name: 'headerBackgroundColorTertiaryDesign4',
		defaultValue: '<fontColorFive>',
		description: 'Header Background Color TertiaryDesign4',
		cssProperty: 'background-color',
		selector: '.comp.compTable._design4._tertiary .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Background Color',
		displayName: 'Header Background Color QuaternaryDesign4',
		name: 'headerBackgroundColorQuaternaryDesign4',
		defaultValue: '<fontColorNine>',
		description: 'Header Background Color QuaternaryDesign4',
		cssProperty: 'background-color',
		selector: '.comp.compTable._design4._quaternary .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Background Color',
		displayName: 'Header Background Color QuinaryDesign4',
		name: 'headerBackgroundColorQuinaryDesign4',
		defaultValue: '<fontColorSeven>',
		description: 'Header Background Color QuinaryDesign4',
		cssProperty: 'background-color',
		selector: '.comp.compTable._design4._quinary .comp.compTableHeaderColumn',
		noPrefix: true,
	},

	{
		groupName: 'Header Border Color',
		displayName: 'Header Border Color Primary ',
		name: 'headerBorderColorPrimary',
		defaultValue: '1px solid <fontColorThree>',
		description: 'Header Border Color Primary ',
		cssProperty: 'border',
		selector: '.comp.compTable._design4._primary .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Color',
		displayName: 'Header Border Color Secondary',
		name: 'headerBorderColorSecondary',
		defaultValue: '1px solid <fontColorFour>',
		description: 'Header Border Color Secondary',
		cssProperty: 'border',
		selector: '.comp.compTable._design4._secondary .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Color',
		displayName: 'Header Border Color Tertiary',
		name: 'headerBorderColorTertiary',
		defaultValue: '1px solid <fontColorFive>',
		description: 'Header Border Color Tertiary',
		cssProperty: 'border',
		selector: '.comp.compTable._design4._tertiary .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Color',
		displayName: 'Header Border Color Quaternary',
		name: 'headerBorderColorQuaternary',
		defaultValue: '1px solid <fontColorNine>',
		description: 'Header Border Color Quaternary',
		cssProperty: 'border',
		selector: '.comp.compTable._design4._quaternary .comp.compTableHeaderColumn',
		noPrefix: true,
	},
	{
		groupName: 'Header Border Color',
		displayName: 'Header Border Color Quinary',
		name: 'headerBorderColorQuinary',
		defaultValue: '1px solid <fontColorSeven>',
		description: 'Header Border Color Quinary',
		cssProperty: 'border',
		selector: '.comp.compTable._design4._quinary .comp.compTableHeaderColumn',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
