import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{ displayName: 'Font', name: 'rangeSliderFont', defaultValue: '<primaryFont>' },
	{ displayName: 'Label Font', name: 'labelRangeSliderFont', defaultValue: '<quaternaryFont>' },
	{
		displayName: 'Tooltip Font',
		name: 'tooltipRangeSliderFont',
		defaultValue: '<quaternaryFont>',
	},
	{
		displayName: 'Fixed Tooltip Font',
		name: 'fixedTooltipRangeSliderFont',
		defaultValue: '<senaryFont>',
	},

	{
		groupName: 'Track',
		displayName: 'Thin Track Height',
		name: 'thinTrackHeightRangeSlider',
		defaultValue: '2px',
		cssProperty: 'height',
		selector:
			'.comp.compRangeSlider._thinTrack ._track, .comp.compRangeSlider._thinTrack ._rangeTrack',
		noPrefix: true,
	},
	{
		groupName: 'Track',
		displayName: 'Thick Track Height',
		name: 'thickTrackHeightRangeSlider',
		defaultValue: '10px',
		cssProperty: 'height',
		selector:
			'.comp.compRangeSlider._thickTrack ._track, .comp.compRangeSlider._thickTrack ._rangeTrack',
		noPrefix: true,
	},
	{
		groupName: 'Track',
		displayName: 'Medium Track Height',
		name: 'mediumTrackHeightRangeSlider',
		defaultValue: '4px',
		cssProperty: 'height',
		selector:
			'.comp.compRangeSlider._mediumTrack ._track, .comp.compRangeSlider._mediumTrack ._rangeTrack',
		noPrefix: true,
	},

	{
		groupName: 'Track',
		displayName: 'Thin Track Border Radius',
		name: 'thinTrackBorderRadiusRangeSlider',
		cssProperty: 'border-radius',
		selector:
			'.comp.compRangeSlider._thinTrack ._track, .comp.compRangeSlider._thinTrack ._rangeTrack',
		noPrefix: true,
	},
	{
		groupName: 'Track',
		displayName: 'Thick Track BorderRaidus',
		name: 'thickTrackBorderRaidusRangeSlider',
		defaultValue: '5px',
		cssProperty: 'border-radius',
		selector:
			'.comp.compRangeSlider._thickTrack ._track, .comp.compRangeSlider._thickTrack ._rangeTrack',
		noPrefix: true,
	},
	{
		groupName: 'Track',
		displayName: 'Medium Track Border Radius',
		name: 'mediumTrackBorderRadiusRangeSlider',
		defaultValue: '2px',
		cssProperty: 'border-radius',
		selector:
			'.comp.compRangeSlider._mediumTrack ._track, .comp.compRangeSlider._mediumTrack ._rangeTrack',
		noPrefix: true,
	},

	{
		groupName: 'Track',
		displayName: 'Small Thumb Track Margin Top',
		name: 'smallThumbTrackMarginTopRangeSlider',
		defaultValue: '5px',
		cssProperty: 'margin-top',
		selector: '.comp.compRangeSlider._smallThumb ._track',
		noPrefix: true,
	},
	{
		groupName: 'Track',
		displayName: 'Medium Thumb Track Margin Top',
		name: 'mediumThumbTrackMarginTopRangeSlider',
		defaultValue: '10px',
		cssProperty: 'margin-top',
		selector: '.comp.compRangeSlider._mediumThumb ._track',
		noPrefix: true,
	},
	{
		groupName: 'Track',
		displayName: 'Large Thumb Track Margin Top',
		name: 'largeThumbTrackMarginTopRangeSlider',
		defaultValue: '15px',
		cssProperty: 'margin-top',
		selector: '.comp.compRangeSlider._largeThumb ._track',
		noPrefix: true,
	},

	{
		groupName: 'Track',
		displayName: 'Small Thumb Track Margin Bottom',
		name: 'smallThumbTrackMarginBottomRangeSlider',
		defaultValue: '5px',
		cssProperty: 'margin-bottom',
		selector: '.comp.compRangeSlider._smallThumb ._track',
		noPrefix: true,
	},
	{
		groupName: 'Track',
		displayName: 'Medium Thumb Track Margin Bottom',
		name: 'mediumThumbTrackMarginBottomRangeSlider',
		defaultValue: '10px',
		cssProperty: 'margin-bottom',
		selector: '.comp.compRangeSlider._mediumThumb ._track',
		noPrefix: true,
	},
	{
		groupName: 'Track',
		displayName: 'Large Thumb Track Margin Bottom',
		name: 'largeThumbTrackMarginBottomRangeSlider',
		defaultValue: '15px',
		cssProperty: 'margin-bottom',
		selector: '.comp.compRangeSlider._largeThumb ._track',
		noPrefix: true,
	},

	{
		groupName: 'Thumb',
		displayName: 'Small Thumb Width',
		name: 'smallThumbWidthRangeSlider',
		defaultValue: '14px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._smallThumb ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Thumb',
		displayName: 'Medium Thumb Width',
		name: 'mediumThumbWidthRangeSlider',
		defaultValue: '24px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._mediumThumb ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Thumb',
		displayName: 'Large Thumb Width',
		name: 'largeThumbWidthRangeSlider',
		defaultValue: '34px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._largeThumb ._thumb',
		noPrefix: true,
	},

	{
		groupName: 'Thumb',
		displayName: 'Small Thumb Height',
		name: 'smallThumbHeightRangeSlider',
		defaultValue: '14px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider._smallThumb ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Thumb',
		displayName: 'Medium Thumb Height',
		name: 'mediumThumbHeightRangeSlider',
		defaultValue: '24px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider._mediumThumb ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Thumb',
		displayName: 'Large Thumb Height',
		name: 'largeThumbHeightRangeSlider',
		defaultValue: '34px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider._largeThumb ._thumb',
		noPrefix: true,
	},

	{
		groupName: 'Mark Thumb',
		displayName: 'Small Mark Thumb Width',
		name: 'smallMarkThumbWidthRangeSlider',
		defaultValue: '10px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._smallThumb ._mark._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Mark Thumb',
		displayName: 'Medium Mark Thumb Width',
		name: 'mediumMarkThumbWidthRangeSlider',
		defaultValue: '20px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._mediumThumb ._mark._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Mark Thumb',
		displayName: 'Large Mark Thumb Width',
		name: 'largeMarkThumbWidthRangeSlider',
		defaultValue: '30px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._largeThumb ._mark._thumb',
		noPrefix: true,
	},

	{
		groupName: 'Mark Thumb',
		displayName: 'Small Mark Thumb Height',
		name: 'smallMarkThumbHeightRangeSlider',
		defaultValue: '10px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider._smallThumb ._mark._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Mark Thumb',
		displayName: 'Medium Mark Thumb Height',
		name: 'mediumMarkThumbHeightRangeSlider',
		defaultValue: '20px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider._mediumThumb ._mark._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Mark Thumb',
		displayName: 'Large Mark Thumb Height',
		name: 'largeMarkThumbHeightRangeSlider',
		defaultValue: '30px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider._largeThumb ._mark._thumb',
		noPrefix: true,
	},

	{
		groupName: 'Round Thumb',
		displayName: 'All Size Round Thumb Border Radius',
		name: 'allSizeRoundThumbBorderRadiusRangeSlider',
		defaultValue: '50%',
		cssProperty: 'border-radius',
		selector: '.comp.compRangeSlider._roundThumb ._thumb',
		noPrefix: true,
	},

	{
		groupName: 'Rounded Square Thumb',
		displayName: 'Small Rounded Square Thumb Border Radius',
		name: 'smallRoundedSquareThumbBorderRadiusRangeSlider',
		defaultValue: '2px',
		cssProperty: 'border-radius',
		selector: '.comp.compRangeSlider._roundedThumbSquare._smallThumb ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Square Thumb',
		displayName: 'Medium Rounded Square Thumb Border Radius',
		name: 'mediumRoundedSquareThumbBorderRadiusRangeSlider',
		defaultValue: '4px',
		cssProperty: 'border-radius',
		selector: '.comp.compRangeSlider._roundedThumbSquare._mediumThumb ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Square Thumb',
		displayName: 'Large Rounded Square Thumb Border Radius',
		name: 'largeRoundedSquareThumbBorderRadiusRangeSlider',
		defaultValue: '6px',
		cssProperty: 'border-radius',
		selector: '.comp.compRangeSlider._roundedThumbSquare._largeThumb ._thumb',
		noPrefix: true,
	},

	{
		groupName: 'Pill Thumb',
		displayName: 'Small Pill Thumb Border Radius',
		name: 'smallPillThumbBorderRadiusRangeSlider',
		defaultValue: '7px',
		cssProperty: 'border-radius',
		selector: '.comp.compRangeSlider._pillThumb._smallThumb ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Pill Thumb',
		displayName: 'Medium Pill Thumb Border Radius',
		name: 'mediumPillThumbBorderRadiusRangeSlider',
		defaultValue: '12px',
		cssProperty: 'border-radius',
		selector: '.comp.compRangeSlider._pillThumb._mediumThumb ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Pill Thumb',
		displayName: 'Large Pill Thumb Border Radius',
		name: 'largePillThumbBorderRadiusRangeSlider',
		defaultValue: '17px',
		cssProperty: 'border-radius',
		selector: '.comp.compRangeSlider._pillThumb._largeThumb ._thumb',
		noPrefix: true,
	},

	{
		groupName: 'Pill Thumb',
		displayName: 'Small Pill Thumb Width',
		name: 'smallPillThumbWidthRangeSlider',
		defaultValue: '24px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._pillThumb._smallThumb ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Pill Thumb',
		displayName: 'Medium Pill Thumb Width',
		name: 'mediumPillThumbWidthRangeSlider',
		defaultValue: '34px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._pillThumb._mediumThumb ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Pill Thumb',
		displayName: 'Large Pill Thumb Width',
		name: 'largePillThumbWidthRangeSlider',
		defaultValue: '44px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._pillThumb._largeThumb ._thumb',
		noPrefix: true,
	},

	{
		groupName: 'Pill Mark Thumb',
		displayName: 'Small Pill Mark Thumb Width',
		name: 'smallPillMarkThumbWidthRangeSlider',
		defaultValue: '20px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._pillThumb._smallThumb ._mark._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Pill Mark Thumb',
		displayName: 'Medium Pill Mark Thumb Width',
		name: 'mediumPillMarkThumbWidthRangeSlider',
		defaultValue: '30px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._pillThumb._mediumThumb ._mark._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Pill Mark Thumb',
		displayName: 'Large Pill Mark Thumb Width',
		name: 'largePillMarkThumbWidthRangeSlider',
		defaultValue: '40px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._pillThumb._largeThumb ._mark._thumb',
		noPrefix: true,
	},

	{
		groupName: 'Pill Thumb Pit',
		displayName: 'Small Pill Thumb Pit Width',
		name: 'smallPillThumbPitWidthRangeSlider',
		defaultValue: '20px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._pillThumb._smallThumb ._thumbPit',
		noPrefix: true,
	},
	{
		groupName: 'Pill Thumb Pit',
		displayName: 'Medium Pill Thumb Pit Width',
		name: 'mediumPillThumbPitWidthRangeSlider',
		defaultValue: '27px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._pillThumb._mediumThumb ._thumbPit',
		noPrefix: true,
	},
	{
		groupName: 'Pill Thumb Pit',
		displayName: 'Large Pill Thumb Pit Width',
		name: 'largePillThumbPitWidthRangeSlider',
		defaultValue: '34px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._pillThumb._largeThumb ._thumbPit',
		noPrefix: true,
	},

	{
		groupName: 'Pill Thumb Pit',
		displayName: 'Small Pill Thumb Pit Height',
		name: 'smallPillThumbPitHeightRangeSlider',
		defaultValue: '10px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider._pillThumb._smallThumb ._thumbPit',
		noPrefix: true,
	},
	{
		groupName: 'Pill Thumb Pit',
		displayName: 'Medium Pill Thumb Pit Height',
		name: 'mediumPillThumbPitHeightRangeSlider',
		defaultValue: '17px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider._pillThumb._mediumThumb ._thumbPit',
		noPrefix: true,
	},
	{
		groupName: 'Pill Thumb Pit',
		displayName: 'Large Pill Thumb Pit Height',
		name: 'largePillThumbPitHeightRangeSlider',
		defaultValue: '24px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider._pillThumb._largeThumb ._thumbPit',
		noPrefix: true,
	},

	{
		groupName: 'Pill Thumb Pit',
		displayName: 'Small Pill Thumb Pit Border Radius',
		name: 'smallPillThumbPitBorderRadiusRangeSlider',
		defaultValue: '5px',
		cssProperty: 'border-radius',
		selector: '.comp.compRangeSlider._pillThumb._smallThumb ._thumbPit',
		noPrefix: true,
	},
	{
		groupName: 'Pill Thumb Pit',
		displayName: 'Medium Pill Thumb Pit Border Radius',
		name: 'mediumPillThumbPitBorderRadiusRangeSlider',
		defaultValue: '10px',
		cssProperty: 'border-radius',
		selector: '.comp.compRangeSlider._pillThumb._mediumThumb ._thumbPit',
		noPrefix: true,
	},
	{
		groupName: 'Pill Thumb Pit',
		displayName: 'Large Pill Thumb Pit Border Radius',
		name: 'largePillThumbPitBorderRadiusRangeSlider',
		defaultValue: '15px',
		cssProperty: 'border-radius',
		selector: '.comp.compRangeSlider._pillThumb._largeThumb ._thumbPit',
		noPrefix: true,
	},

	{
		groupName: 'Pill Mark Thumb Pit',
		displayName: 'Small Pill Mark Thumb Pit Width',
		name: 'smallPillMarkThumbPitWidthRangeSlider',
		defaultValue: '16px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._pillThumb._smallThumb ._mark._thumb ._thumbPit',
		noPrefix: true,
	},
	{
		groupName: 'Pill Mark Thumb Pit',
		displayName: 'Medium Pill Mark Thumb Pit Width',
		name: 'mediumPillMarkThumbPitWidthRangeSlider',
		defaultValue: '22px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._pillThumb._mediumThumb ._mark._thumb ._thumbPit',
		noPrefix: true,
	},
	{
		groupName: 'Pill Mark Thumb Pit',
		displayName: 'Large Pill Mark Thumb Pit Width',
		name: 'largePillMarkThumbPitWidthRangeSlider',
		defaultValue: '30px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider._pillThumb._largeThumb ._mark._thumb ._thumbPit',
		noPrefix: true,
	},

	{
		groupName: 'Pill Mark Thumb Pit',
		displayName: 'Small Pill Mark Thumb Pit Height',
		name: 'smallPillMarkThumbPitHeightRangeSlider',
		defaultValue: '7px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider._pillThumb._smallThumb ._mark._thumb ._thumbPit',
		noPrefix: true,
	},
	{
		groupName: 'Pill Mark Thumb Pit',
		displayName: 'Medium Pill Mark Thumb Pit Height',
		name: 'mediumPillMarkThumbPitHeightRangeSlider',
		defaultValue: '14px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider._pillThumb._mediumThumb ._mark._thumb ._thumbPit',
		noPrefix: true,
	},
	{
		groupName: 'Pill Mark Thumb Pit',
		displayName: 'Large Pill Mark Thumb Pit Height',
		name: 'largePillMarkThumbPitHeightRangeSlider',
		defaultValue: '20px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider._pillThumb._largeThumb ._mark._thumb ._thumbPit',
		noPrefix: true,
	},

	{
		groupName: 'Content Margin',
		displayName: 'Content Small Thumb Margin Left',
		name: 'contentSmallThumbMarginLeftRangeSlider',
		defaultValue: '7px',
		cssProperty: 'margin-left',
		selector: '.comp.compRangeSlider._smallThumb ._contentMargin',
		noPrefix: true,
	},
	{
		groupName: 'Content Margin',
		displayName: 'Content Medium Thumb Margin Left',
		name: 'contentMediumThumbMarginLeftRangeSlider',
		defaultValue: '12px',
		cssProperty: 'margin-left',
		selector: '.comp.compRangeSlider._mediumThumb ._contentMargin',
		noPrefix: true,
	},
	{
		groupName: 'Content Margin',
		displayName: 'Content Large Thumb Margin Left',
		name: 'contentLargeThumbMarginLeftRangeSlider',
		defaultValue: '17px',
		cssProperty: 'margin-left',
		selector: '.comp.compRangeSlider._largeThumb ._contentMargin',
		noPrefix: true,
	},

	{
		groupName: 'Content Margin',
		displayName: 'Content Small Thumb Margin Right',
		name: 'contentSmallThumbMarginRightRangeSlider',
		defaultValue: '7px',
		cssProperty: 'margin-right',
		selector: '.comp.compRangeSlider._smallThumb ._contentMargin',
		noPrefix: true,
	},
	{
		groupName: 'Content Margin',
		displayName: 'Content Medium Thumb Margin Right',
		name: 'contentMediumThumbMarginRightRangeSlider',
		defaultValue: '12px',
		cssProperty: 'margin-right',
		selector: '.comp.compRangeSlider._mediumThumb ._contentMargin',
		noPrefix: true,
	},
	{
		groupName: 'Content Margin',
		displayName: 'Content Large Thumb Margin Right',
		name: 'contentLargeThumbMarginRightRangeSlider',
		defaultValue: '17px',
		cssProperty: 'margin-right',
		selector: '.comp.compRangeSlider._largeThumb ._contentMargin',
		noPrefix: true,
	},

	{
		groupName: 'Content Margin Pill Thumb',
		displayName: 'Content Small Pill Thumb Margin Left',
		name: 'contentSmallPillThumbMarginLeftRangeSlider',
		defaultValue: '12px',
		cssProperty: 'margin-left',
		selector: '.comp.compRangeSlider._smallThumb._pillThumb ._contentMargin',
		noPrefix: true,
	},
	{
		groupName: 'Content Margin Pill Thumb',
		displayName: 'Content Medium Pill Thumb Margin Left',
		name: 'contentMediumPillThumbMarginLeftRangeSlider',
		defaultValue: '17px',
		cssProperty: 'margin-left',
		selector: '.comp.compRangeSlider._mediumThumb._pillThumb ._contentMargin',
		noPrefix: true,
	},
	{
		groupName: 'Content Margin Pill Thumb',
		displayName: 'Content Large Pill Thumb Margin Left',
		name: 'contentLargePillThumbMarginLeftRangeSlider',
		defaultValue: '22px',
		cssProperty: 'margin-left',
		selector: '.comp.compRangeSlider._largeThumb._pillThumb ._contentMargin',
		noPrefix: true,
	},

	{
		groupName: 'Content Margin Pill Thumb',
		displayName: 'Content Small Pill Thumb Margin Right',
		name: 'contentSmallPillThumbMarginRightRangeSlider',
		defaultValue: '12px',
		cssProperty: 'margin-right',
		selector: '.comp.compRangeSlider._smallThumb._pillThumb ._contentMargin',
		noPrefix: true,
	},
	{
		groupName: 'Content Margin Pill Thumb',
		displayName: 'Content Medium Pill Thumb Margin Right',
		name: 'contentMediumPillThumbMarginRightRangeSlider',
		defaultValue: '17px',
		cssProperty: 'margin-right',
		selector: '.comp.compRangeSlider._mediumThumb._pillThumb ._contentMargin',
		noPrefix: true,
	},
	{
		groupName: 'Content Margin Pill Thumb',
		displayName: 'Content Large Pill Thumb Margin Right',
		name: 'contentLargePillThumbMarginRightRangeSlider',
		defaultValue: '22px',
		cssProperty: 'margin-right',
		selector: '.comp.compRangeSlider._largeThumb._pillThumb ._contentMargin',
		noPrefix: true,
	},

	{
		groupName: 'Label',
		displayName: 'Min Label Font',
		name: 'minLabelFontRangeSlider',
		defaultValue: '<labelRangeSliderFont>',
		cssProperty: 'font',
		selector: '.comp.compRangeSlider ._minLabel',
		noPrefix: true,
	},
	{
		groupName: 'Label',
		displayName: 'Max Label Font',
		name: 'maxLabelFontRangeSlider',
		defaultValue: '<labelRangeSliderFont>',
		cssProperty: 'font',
		selector: '.comp.compRangeSlider ._maxLabel',
		noPrefix: true,
	},
	{
		groupName: 'Label',
		displayName: 'Mark Label Font',
		name: 'markLabelFontRangeSlider',
		defaultValue: '<labelRangeSliderFont>',
		cssProperty: 'font',
		selector: '.comp.compRangeSlider ._markLabel',
		noPrefix: true,
	},
	{
		groupName: 'Label',
		displayName: 'Tick Label Font',
		name: 'tickLabelFontRangeSlider',
		defaultValue: '<labelRangeSliderFont>',
		cssProperty: 'font',
		selector: '.comp.compRangeSlider ._tickLabel',
		noPrefix: true,
	},

	{
		groupName: 'Label',
		displayName: 'Bottom Label Container Height',
		name: 'bottomLabelContainerHeightRangeSlider',
		defaultValue: '20px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider ._bottomLabelContainer',
		noPrefix: true,
	},
	{
		groupName: 'Label',
		displayName: 'Top Label Container Height',
		name: 'topLabelContainerHeightRangeSlider',
		defaultValue: '20px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider ._topLabelContainer',
		noPrefix: true,
	},

	{
		groupName: 'Tick Container',
		displayName: 'Tick Container Gap',
		name: 'tickContainerGapRangeSlider',
		defaultValue: '3px',
		cssProperty: 'gap',
		selector: '.comp.compRangeSlider ._tickContainer',
		noPrefix: true,
	},

	{
		groupName: 'Tick',
		displayName: 'Tick Width',
		name: 'tickWidthRangeSlider',
		defaultValue: '2px',
		cssProperty: 'width',
		selector: '.comp.compRangeSlider ._tick',
		noPrefix: true,
	},
	{
		groupName: 'Tick',
		displayName: 'Tick Height',
		name: 'tickHeightRangeSlider',
		defaultValue: '6px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider ._tick',
		noPrefix: true,
	},

	{
		groupName: 'Fixed Label Tooltip',
		displayName: 'Fixed Label Tooltip Height',
		name: 'fixedLabelTooltipHeightRangeSlider',
		defaultValue: '30px',
		cssProperty: 'height',
		selector: '.comp.compRangeSlider._fixedLabelTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Fixed Label Tooltip',
		displayName: 'Fixed Label Tooltip Line Height',
		name: 'fixedLabelTooltipLineHeightRangeSlider',
		defaultValue: '30px',
		cssProperty: 'line-height',
		selector: '.comp.compRangeSlider._fixedLabelTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Fixed Label Tooltip',
		displayName: 'Fixed Label Tooltip Margin Top',
		name: 'fixedLabelTooltipMarginTopRangeSlider',
		defaultValue: '5px',
		cssProperty: 'margin-top',
		selector: '.comp.compRangeSlider._fixedLabelTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Fixed Label Tooltip',
		displayName: 'Fixed Label Tooltip Margin Bottom',
		name: 'fixedLabelTooltipMarginBottomRangeSlider',
		defaultValue: '5px',
		cssProperty: 'margin-bottom',
		selector: '.comp.compRangeSlider._fixedLabelTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Fixed Label Tooltip',
		displayName: 'Fixed Label Tooltip Font',
		name: 'fixedLabelTooltipFontRangeSlider',
		defaultValue: '<fixedTooltipRangeSliderFont>',
		cssProperty: 'font',
		selector: '.comp.compRangeSlider._fixedLabelTT ._toolTip',
		noPrefix: true,
	},

	{
		groupName: 'Tooltip',
		displayName: 'Tooltip Font',
		name: 'tooltipFontRangeSlider',
		defaultValue: '<tooltipRangeSliderFont>',
		cssProperty: 'font',
		selector:
			'.comp.compRangeSlider._roundedTT ._toolTip, .comp.compRangeSlider._roundedRectangleTT ._toolTip, .comp.compRangeSlider._largeRoundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Tooltip',
		displayName: 'Rounded Tooltip Border Radius',
		name: 'roundedTooltipBorderRadiusRangeSlider',
		defaultValue: '15px',
		cssProperty: 'border-radius',
		selector: '.comp.compRangeSlider._roundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Tooltip',
		displayName: 'Rounded Rectangle Tooltip Border Radius',
		name: 'roundedRectangleTooltipBorderRadiusRangeSlider',
		defaultValue: '5px',
		cssProperty: 'border-radius',
		selector: '.comp.compRangeSlider._roundedRectangleTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Tooltip',
		displayName: 'Large Rounded Tooltip Border Radius',
		name: 'largeRoundedTooltipBorderRadiusRangeSlider',
		defaultValue: '15px',
		cssProperty: 'border-radius',
		selector: '.comp.compRangeSlider._largeRoundedTT ._toolTip',
		noPrefix: true,
	},

	{
		groupName: 'Tooltip',
		displayName: 'Rounded Tooltip Padding',
		name: 'roundedTooltipPaddingRangeSlider',
		defaultValue: '3px 7px',
		cssProperty: 'padding',
		selector: '.comp.compRangeSlider._roundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Tooltip',
		displayName: 'Rounded Rectangle Padding',
		name: 'roundedRectanglePaddingRangeSlider',
		defaultValue: '3px 7px',
		cssProperty: 'padding',
		selector: '.comp.compRangeSlider._roundedRectangleTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Tooltip',
		displayName: 'Large Rounded Tooltip Padding',
		name: 'largeRoundedTooltipPaddingRangeSlider',
		defaultValue: '7px 9px',
		cssProperty: 'padding',
		selector: '.comp.compRangeSlider._largeRoundedTT ._toolTip',
		noPrefix: true,
	},

	{
		groupName: 'Empty Track',
		displayName: 'Empty Track Color',
		name: 'emptyTrackColorRangeSlider',
		defaultValue: '<backgroundColorNine>',
		cssProperty: 'background',
		selector: '.comp.compRangeSlider._emptyTrack ._track',
		noPrefix: true,
	},

	{
		groupName: 'Thumb',
		displayName: 'Thumb Color',
		name: 'thumbColorRangeSlider',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compRangeSlider ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Thumb',
		displayName: 'Inverted Thumb Color',
		name: 'invertedThumbColorRangeSlider',
		defaultValue: '<backgroundColorSeven>',
		cssProperty: 'background',
		selector: '.comp.compRangeSlider._invertThumb ._thumbPit',
		noPrefix: true,
	},

	{
		groupName: 'Tick',
		displayName: 'Tick Color',
		name: 'tickColorRangeSlider',
		defaultValue: '<backgroundColorEight>',
		cssProperty: 'background',
		selector: '.comp.compRangeSlider ._tick',
		noPrefix: true,
	},
	{
		groupName: 'Tick',
		displayName: 'Tick Label Color',
		name: 'tickLabelColorRangeSlider',
		defaultValue: '<backgroundColorEight>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider ._tickLabel',
		noPrefix: true,
	},

	{
		groupName: 'Thumb',
		displayName: 'Thumb Box Shadow',
		name: 'thumbBoxShadowRangeSlider',
		defaultValue: '0px 2px 10px 0px  <colorNine>',
		cssProperty: 'box-shadow',
		selector: '.comp.compRangeSlider ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Tooltip',
		displayName: 'Tooltip Box Shadow',
		name: 'tooltipBoxShadowRangeSlider',
		defaultValue: '0px 2px 10px 0px <colorNine>',
		cssProperty: 'box-shadow',
		selector:
			'.comp.compRangeSlider._roundedTT ._toolTip, .comp.compRangeSlider._roundedRectangleTT ._toolTip, .comp.compRangeSlider._largeRoundedTT ._toolTip',
		noPrefix: true,
	},

	{
		groupName: 'Range Track',
		displayName: 'Primary  Design Range Track Background Range Slider',
		name: 'primaryDesignRangeTrackBackgroundRangeSlider',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._primary ._rangeTrack',
		noPrefix: true,
	},
	{
		groupName: 'Range Track',
		displayName: 'Secondary  Design Range Track Background Range Slider',
		name: 'secondaryDesignRangeTrackBackgroundRangeSlider',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._secondary ._rangeTrack',
		noPrefix: true,
	},
	{
		groupName: 'Range Track',
		displayName: 'Tertiary  Design Range Track Background Range Slider',
		name: 'tertiaryDesignRangeTrackBackgroundRangeSlider',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._tertiary ._rangeTrack',
		noPrefix: true,
	},
	{
		groupName: 'Range Track',
		displayName: 'Quaternary  Design Range Track Background Range Slider',
		name: 'quaternaryDesignRangeTrackBackgroundRangeSlider',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._quaternary ._rangeTrack',
		noPrefix: true,
	},
	{
		groupName: 'Range Track',
		displayName: 'Quinary  Design Range Track Background Range Slider',
		name: 'quinaryDesignRangeTrackBackgroundRangeSlider',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._quinary ._rangeTrack',
		noPrefix: true,
	},

	{
		groupName: 'Filled Track',
		displayName: 'Primary  Design Filled Track Background Range Slider',
		name: 'primaryDesignFilledTrackBackgroundRangeSlider',
		defaultValue: '<backgroundHoverColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._primary._filledTrack ._track',
		noPrefix: true,
	},
	{
		groupName: 'Filled Track',
		displayName: 'Secondary  Design Filled Track Background Range Slider',
		name: 'secondaryDesignFilledTrackBackgroundRangeSlider',
		defaultValue: '<backgroundHoverColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._secondary._filledTrack ._track',
		noPrefix: true,
	},
	{
		groupName: 'Filled Track',
		displayName: 'Tertiary  Design Filled Track Background Range Slider',
		name: 'tertiaryDesignFilledTrackBackgroundRangeSlider',
		defaultValue: '<backgroundHoverColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._tertiary._filledTrack ._track',
		noPrefix: true,
	},
	{
		groupName: 'Filled Track',
		displayName: 'Quaternary  Design Filled Track Background Range Slider',
		name: 'quaternaryDesignFilledTrackBackgroundRangeSlider',
		defaultValue: '<backgroundHoverColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._quaternary._filledTrack ._track',
		noPrefix: true,
	},
	{
		groupName: 'Filled Track',
		displayName: 'Quinary  Design Filled Track Background Range Slider',
		name: 'quinaryDesignFilledTrackBackgroundRangeSlider',
		defaultValue: '<backgroundHoverColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._quinary._filledTrack ._track',
		noPrefix: true,
	},

	{
		groupName: 'Thumb Pit',
		displayName: 'Primary  Design Thumb Pit Background Range Slider',
		name: 'primaryDesignThumbPitBackgroundRangeSlider',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._primary ._thumbPit',
		noPrefix: true,
	},
	{
		groupName: 'Thumb Pit',
		displayName: 'Secondary  Design Thumb Pit Background Range Slider',
		name: 'secondaryDesignThumbPitBackgroundRangeSlider',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._secondary ._thumbPit',
		noPrefix: true,
	},
	{
		groupName: 'Thumb Pit',
		displayName: 'Tertiary  Design Thumb Pit Background Range Slider',
		name: 'tertiaryDesignThumbPitBackgroundRangeSlider',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._tertiary ._thumbPit',
		noPrefix: true,
	},
	{
		groupName: 'Thumb Pit',
		displayName: 'Quaternary  Design Thumb Pit Background Range Slider',
		name: 'quaternaryDesignThumbPitBackgroundRangeSlider',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._quaternary ._thumbPit',
		noPrefix: true,
	},
	{
		groupName: 'Thumb Pit',
		displayName: 'Quinary  Design Thumb Pit Background Range Slider',
		name: 'quinaryDesignThumbPitBackgroundRangeSlider',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._quinary ._thumbPit',
		noPrefix: true,
	},

	{
		groupName: 'Inverted Thumb Pit',
		displayName: 'Primary  Design Inverted Thumb Pit Background Range Slider',
		name: 'primaryDesignInvertedThumbPitBackgroundRangeSlider',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._primary._invertThumb ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Inverted Thumb Pit',
		displayName: 'Secondary  Design Inverted Thumb Pit Background Range Slider',
		name: 'secondaryDesignInvertedThumbPitBackgroundRangeSlider',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._secondary._invertThumb ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Inverted Thumb Pit',
		displayName: 'Tertiary  Design Inverted Thumb Pit Background Range Slider',
		name: 'tertiaryDesignInvertedThumbPitBackgroundRangeSlider',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._tertiary._invertThumb ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Inverted Thumb Pit',
		displayName: 'Quaternary  Design Inverted Thumb Pit Background Range Slider',
		name: 'quaternaryDesignInvertedThumbPitBackgroundRangeSlider',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._quaternary._invertThumb ._thumb',
		noPrefix: true,
	},
	{
		groupName: 'Inverted Thumb Pit',
		displayName: 'Quinary  Design Inverted Thumb Pit Background Range Slider',
		name: 'quinaryDesignInvertedThumbPitBackgroundRangeSlider',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._quinary._invertThumb ._thumb',
		noPrefix: true,
	},

	{
		groupName: 'Rounded Tooltip',
		displayName: 'Primary  Design Rounded Tooltip Background Range Slider',
		name: 'primaryDesignRoundedTooltipBackgroundRangeSlider',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._primary._roundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Tooltip',
		displayName: 'Secondary  Design Rounded Tooltip Background Range Slider',
		name: 'secondaryDesignRoundedTooltipBackgroundRangeSlider',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._secondary._roundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Tooltip',
		displayName: 'Tertiary  Design Rounded Tooltip Background Range Slider',
		name: 'tertiaryDesignRoundedTooltipBackgroundRangeSlider',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._tertiary._roundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Tooltip',
		displayName: 'Quaternary  Design Rounded Tooltip Background Range Slider',
		name: 'quaternaryDesignRoundedTooltipBackgroundRangeSlider',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._quaternary._roundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Tooltip',
		displayName: 'Quinary  Design Rounded Tooltip Background Range Slider',
		name: 'quinaryDesignRoundedTooltipBackgroundRangeSlider',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._quinary._roundedTT ._toolTip',
		noPrefix: true,
	},

	{
		groupName: 'Large Rounded Tooltip',
		displayName: 'Primary  Design Large Rounded Tooltip Background Range Slider',
		name: 'primaryDesignLargeRoundedTooltipBackgroundRangeSlider',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._primary._largeRoundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Large Rounded Tooltip',
		displayName: 'Secondary  Design Large Rounded Tooltip Background Range Slider',
		name: 'secondaryDesignLargeRoundedTooltipBackgroundRangeSlider',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._secondary._largeRoundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Large Rounded Tooltip',
		displayName: 'Tertiary  Design Large Rounded Tooltip Background Range Slider',
		name: 'tertiaryDesignLargeRoundedTooltipBackgroundRangeSlider',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._tertiary._largeRoundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Large Rounded Tooltip',
		displayName: 'Quaternary  Design Large Rounded Tooltip Background Range Slider',
		name: 'quaternaryDesignLargeRoundedTooltipBackgroundRangeSlider',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._quaternary._largeRoundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Large Rounded Tooltip',
		displayName: 'Quinary  Design Large Rounded Tooltip Background Range Slider',
		name: 'quinaryDesignLargeRoundedTooltipBackgroundRangeSlider',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._quinary._largeRoundedTT ._toolTip',
		noPrefix: true,
	},

	{
		groupName: 'Rounded Rectangle Tooltip',
		displayName: 'Primary  Design Rounded Rectangle Tooltip Background Range Slider',
		name: 'primaryDesignRoundedRectangleTooltipBackgroundRangeSlider',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._primary._roundedRectangleTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Rectangle Tooltip',
		displayName: 'Secondary  Design Rounded Rectangle Tooltip Background Range Slider',
		name: 'secondaryDesignRoundedRectangleTooltipBackgroundRangeSlider',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._secondary._roundedRectangleTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Rectangle Tooltip',
		displayName: 'Tertiary  Design Rounded Rectangle Tooltip Background Range Slider',
		name: 'tertiaryDesignRoundedRectangleTooltipBackgroundRangeSlider',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._tertiary._roundedRectangleTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Rectangle Tooltip',
		displayName: 'Quaternary  Design Rounded Rectangle Tooltip Background Range Slider',
		name: 'quaternaryDesignRoundedRectangleTooltipBackgroundRangeSlider',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._quaternary._roundedRectangleTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Rectangle Tooltip',
		displayName: 'Quinary  Design Rounded Rectangle Tooltip Background Range Slider',
		name: 'quinaryDesignRoundedRectangleTooltipBackgroundRangeSlider',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background-color',
		selector: '.comp.compRangeSlider._quinary._roundedRectangleTT ._toolTip',
		noPrefix: true,
	},

	{
		groupName: 'Rounded Tooltip',
		displayName: 'Primary  Design Rounded Tooltip Font Color Range Slider',
		name: 'primaryDesignRoundedTooltipFontColorRangeSlider',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider._primary._roundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Tooltip',
		displayName: 'Secondary  Design Rounded Tooltip Font Color Range Slider',
		name: 'secondaryDesignRoundedTooltipFontColorRangeSlider',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider._secondary._roundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Tooltip',
		displayName: 'Tertiary  Design Rounded Tooltip Font Color Range Slider',
		name: 'tertiaryDesignRoundedTooltipFontColorRangeSlider',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider._tertiary._roundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Tooltip',
		displayName: 'Quaternary  Design Rounded Tooltip Font Color Range Slider',
		name: 'quaternaryDesignRoundedTooltipFontColorRangeSlider',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider._quaternary._roundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Tooltip',
		displayName: 'Quinary  Design Rounded Tooltip Font Color Range Slider',
		name: 'quinaryDesignRoundedTooltipFontColorRangeSlider',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider._quinary._roundedTT ._toolTip',
		noPrefix: true,
	},

	{
		groupName: 'Large Rounded Tooltip',
		displayName: 'Primary  Design Large Rounded Tooltip Font Color Range Slider',
		name: 'primaryDesignLargeRoundedTooltipFontColorRangeSlider',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider._primary._largeRoundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Large Rounded Tooltip',
		displayName: 'Secondary  Design Large Rounded Tooltip Font Color Range Slider',
		name: 'secondaryDesignLargeRoundedTooltipFontColorRangeSlider',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider._secondary._largeRoundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Large Rounded Tooltip',
		displayName: 'Tertiary  Design Large Rounded Tooltip Font Color Range Slider',
		name: 'tertiaryDesignLargeRoundedTooltipFontColorRangeSlider',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider._tertiary._largeRoundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Large Rounded Tooltip',
		displayName: 'Quaternary  Design Large Rounded Tooltip Font Color Range Slider',
		name: 'quaternaryDesignLargeRoundedTooltipFontColorRangeSlider',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider._quaternary._largeRoundedTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Large Rounded Tooltip',
		displayName: 'Quinary  Design Large Rounded Tooltip Font Color Range Slider',
		name: 'quinaryDesignLargeRoundedTooltipFontColorRangeSlider',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider._quinary._largeRoundedTT ._toolTip',
		noPrefix: true,
	},

	{
		groupName: 'Rounded Rectangle Tooltip',
		displayName: 'Primary  Design Rounded Rectangle Tooltip Font Color Range Slider',
		name: 'primaryDesignRoundedRectangleTooltipFontColorRangeSlider',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider._primary._roundedRectangleTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Rectangle Tooltip',
		displayName: 'Secondary  Design Rounded Rectangle Tooltip Font Color Range Slider',
		name: 'secondaryDesignRoundedRectangleTooltipFontColorRangeSlider',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider._secondary._roundedRectangleTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Rectangle Tooltip',
		displayName: 'Tertiary  Design Rounded Rectangle Tooltip Font Color Range Slider',
		name: 'tertiaryDesignRoundedRectangleTooltipFontColorRangeSlider',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider._tertiary._roundedRectangleTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Rectangle Tooltip',
		displayName: 'Quaternary  Design Rounded Rectangle Tooltip Font Color Range Slider',
		name: 'quaternaryDesignRoundedRectangleTooltipFontColorRangeSlider',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider._quaternary._roundedRectangleTT ._toolTip',
		noPrefix: true,
	},
	{
		groupName: 'Rounded Rectangle Tooltip',
		displayName: 'Quinary  Design Rounded Rectangle Tooltip Font Color Range Slider',
		name: 'quinaryDesignRoundedRectangleTooltipFontColorRangeSlider',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector: '.comp.compRangeSlider._quinary._roundedRectangleTT ._toolTip',
		noPrefix: true,
	},
];
export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
