import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: 'Menu Font',
		displayName: 'Menu Font',
		name: 'menuFont',
		defaultValue: '<primaryFont>',
		cssProperty: 'font',
	},

	{
		groupName: 'Default',
		displayName: 'Default Menu Font',
		name: 'defaultMenuDesignFont',
		defaultValue: '<menuFont>',
		cssProperty: 'font',
		selector: '.comp.compMenu._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Outline Menu Font',
		name: 'outlineMenuDesignFont',
		defaultValue: '<menuFont>',
		cssProperty: 'font',
		selector: '.comp.compMenu._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Text',
		displayName: 'Text Menu Font',
		name: 'textMenuDesignFont',
		defaultValue: '<menuFont>',
		cssProperty: 'font',
		selector: '.comp.compMenu._text',
		noPrefix: true,
	},
	{
		groupName: 'Sides',
		displayName: 'Sides Menu Font',
		name: 'sidesMenuDesignFont',
		defaultValue: '<menuFont>',
		cssProperty: 'font',
		selector: '.comp.compMenu._sides',
		noPrefix: true,
	},
	{
		groupName: 'Top Bottom',
		displayName: 'Top Bottom Menu Font',
		name: 'topbottomMenuDesignFont',
		defaultValue: '<menuFont>',
		cssProperty: 'font',
		selector: '.comp.compMenu._topbottom',
		noPrefix: true,
	},

	{
		groupName: 'Menu Color',
		displayName: 'Primary Menu Color',
		name: 'primaryMenuColor',
		defaultValue: '<fontColorThree>',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._outlined._primary, .comp.compMenu._outlined._primary:visited, .comp.compMenu._text._primary._isActive, .comp.compMenu._text._primary:hover, .comp.compMenu._sides._primary._isActive, .comp.compMenu._sides._primary:hover, .comp.compMenu._topbottom._primary._isActive, .comp.compMenu._topbottom._primary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Menu Color',
		displayName: 'Secondary Menu Color',
		name: 'secondaryMenuColor',
		defaultValue: '<fontColorFour>',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._outlined._secondary, .comp.compMenu._outlined._secondary:visited, .comp.compMenu._text._secondary._isActive, .comp.compMenu._text._secondary:hover, .comp.compMenu._sides._secondary._isActive, .comp.compMenu._sides._secondary:hover, .comp.compMenu._topbottom._secondary._isActive, .comp.compMenu._topbottom._secondary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Menu Color',
		displayName: 'Tertiary Menu Color',
		name: 'tertiaryMenuColor',
		defaultValue: '<fontColorFive>',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._outlined._tertiary, .comp.compMenu._outlined._tertiary:visited, .comp.compMenu._text._tertiary._isActive, .comp.compMenu._text._tertiary:hover, .comp.compMenu._sides._tertiary._isActive, .comp.compMenu._sides._tertiary:hover, .comp.compMenu._topbottom._tertiary._isActive, .comp.compMenu._topbottom._tertiary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Menu Color',
		displayName: 'Quaternary Menu Color',
		name: 'quaternaryMenuColor',
		defaultValue: '<fontColorNine>',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._outlined._quaternary, .comp.compMenu._outlined._quaternary:visited, .comp.compMenu._text._quaternary._isActive, .comp.compMenu._text._quaternary:hover, .comp.compMenu._sides._quaternary._isActive, .comp.compMenu._sides._quaternary:hover, .comp.compMenu._topbottom._quaternary._isActive, .comp.compMenu._topbottom._quaternary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Menu Color',
		displayName: 'Quinary Menu Color',
		name: 'quinaryMenuColor',
		defaultValue: '<fontColorSeven>',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._outlined._quinary, .comp.compMenu._outlined._quinary:visited, .comp.compMenu._text._quinary._isActive, .comp.compMenu._text._quinary:hover, .comp.compMenu._sides._quinary._isActive, .comp.compMenu._sides._quinary:hover, .comp.compMenu._topbottom._quinary._isActive, .comp.compMenu._topbottom._quinary:hover',
		noPrefix: true,
	},

	{
		groupName: 'Menu Background Color',
		displayName: 'Primary Menu Background Color',
		name: 'primaryMenuBGColor',
		defaultValue: '<backgroundColorOne>',
		cssProperty: 'background',
		selector:
			'.comp.compMenu._default._primary._isActive, .comp.compMenu._default._primary:hover, .comp.compMenu._outlined._primary._isActive, .comp.compMenu._outlined._primary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Menu Background Color',
		displayName: 'Secondary Menu Background Color',
		name: 'secondaryMenuBGColor',
		defaultValue: '<backgroundColorTwo>',
		cssProperty: 'background',
		selector:
			'.comp.compMenu._default._secondary._isActive, .comp.compMenu._default._secondary:hover, .comp.compMenu._outlined._secondary._isActive, .comp.compMenu._outlined._secondary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Menu Background Color',
		displayName: 'Tertiary Menu Background Color',
		name: 'tertiaryMenuBGColor',
		defaultValue: '<backgroundColorThree>',
		cssProperty: 'background',
		selector:
			'.comp.compMenu._default._tertiary._isActive, .comp.compMenu._default._tertiary:hover, .comp.compMenu._outlined._tertiary._isActive, .comp.compMenu._outlined._tertiary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Menu Background Color',
		displayName: 'Quaternary Menu Background Color',
		name: 'quaternaryMenuBGColor',
		defaultValue: '<backgroundColorFour>',
		cssProperty: 'background',
		selector:
			'.comp.compMenu._default._quaternary._isActive, .comp.compMenu._default._quaternary:hover, .comp.compMenu._outlined._quaternary._isActive, .comp.compMenu._outlined._quaternary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Menu Background Color',
		displayName: 'Quinary Menu Background Color',
		name: 'quinaryMenuBGColor',
		defaultValue: '<backgroundColorFive>',
		cssProperty: 'background',
		selector:
			'.comp.compMenu._default._quinary._isActive, .comp.compMenu._default._quinary:hover, .comp.compMenu._outlined._quinary._isActive, .comp.compMenu._outlined._quinary:hover',
		noPrefix: true,
	},

	{
		groupName: 'Menu Border Color',
		displayName: 'Primary Menu Border Color',
		name: 'primaryMenuBorderColor',
		defaultValue: '<primaryMenuColor>',
		cssProperty: 'border-color',
		selector: '.comp.compMenu._outlined._primary, .comp.compMenu._outlined._primary:visited',
		noPrefix: true,
	},
	{
		groupName: 'Menu Border Color',
		displayName: 'Secondary Menu Border Color',
		name: 'secondaryMenuBorderColor',
		defaultValue: '<secondaryMenuColor>',
		cssProperty: 'border-color',
		selector:
			'.comp.compMenu._outlined._secondary, .comp.compMenu._outlined._secondary:visited',
		noPrefix: true,
	},
	{
		groupName: 'Menu Border Color',
		displayName: 'Tertiary Menu Border Color',
		name: 'tertiaryMenuBorderColor',
		defaultValue: '<tertiaryMenuColor>',
		cssProperty: 'border-color',
		selector: '.comp.compMenu._outlined._tertiary, .comp.compMenu._outlined._tertiary:visited',
		noPrefix: true,
	},
	{
		groupName: 'Menu Border Color',
		displayName: 'Quaternary Menu Border Color',
		name: 'quaternaryMenuBorderColor',
		defaultValue: '<quaternaryMenuColor>',
		cssProperty: 'border-color',
		selector:
			'.comp.compMenu._outlined._quaternary, .comp.compMenu._outlined._quaternary:visited',
		noPrefix: true,
	},
	{
		groupName: 'Menu Border Color',
		displayName: 'Quinary Menu Border Color',
		name: 'quinaryMenuBorderColor',
		defaultValue: '<quinaryMenuColor>',
		cssProperty: 'border-color',
		selector: '.comp.compMenu._outlined._quinary, .comp.compMenu._outlined._quinary:visited',
		noPrefix: true,
	},

	{
		groupName: 'Menu Color',
		displayName: 'Menu Font Color',
		name: 'menuFontColor',
		defaultValue: '<fontColorEight>',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._default._primary, .comp.compMenu._default._primary:visited, .comp.compMenu._default._secondary, .comp.compMenu._default._secondary:visited, .comp.compMenu._default._tertiary, .comp.compMenu._default._tertiary:visited, .comp.compMenu._default._quaternary, .comp.compMenu._default._quaternary:visited, .comp.compMenu._default._quinary, .comp.compMenu._default._quinary:visited,.comp.compMenu._text._primary, .comp.compMenu._text._primary:visited, .comp.compMenu._text._secondary, .comp.compMenu._text._secondary:visited, .comp.compMenu._text._tertiary, .comp.compMenu._text._tertiary:visited, .comp.compMenu._text._quaternary, .comp.compMenu._text._quaternary:visited, .comp.compMenu._text._quinary, .comp.compMenu._text._quinary:visited, .comp.compMenu._sides._primary, .comp.compMenu._sides._primary:visited, .comp.compMenu._sides._secondary, .comp.compMenu._sides._secondary:visited, .comp.compMenu._sides._tertiary, .comp.compMenu._sides._tertiary:visited, .comp.compMenu._sides._quaternary, .comp.compMenu._sides._quaternary:visited, .comp.compMenu._sides._quinary, .comp.compMenu._sides._quinary:visited, .comp.compMenu._topbottom._primary, .comp.compMenu._topbottom._primary:visited, .comp.compMenu._topbottom._secondary, .comp.compMenu._topbottom._secondary:visited, .comp.compMenu._topbottom._tertiary, .comp.compMenu._topbottom._tertiary:visited, .comp.compMenu._topbottom._quaternary, .comp.compMenu._topbottom._quaternary:visited, .comp.compMenu._topbottom._quinary, .comp.compMenu._topbottom._quinary:visited',
		noPrefix: true,
	},
	{
		groupName: 'Menu Color',
		displayName: 'Menu Light Font Color',
		name: 'menuLightFontColor',
		defaultValue: '<fontColorTwo>',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._default._primary._isActive, .comp.compMenu._default._primary:hover, .comp.compMenu._default._secondary._isActive, .comp.compMenu._default._secondary:hover, .comp.compMenu._default._quaternary._isActive, .comp.compMenu._default._quaternary:hover, .comp.compMenu._default._quinary._isActive, .comp.compMenu._default._quinary:hover, .comp.compMenu._outlined._primary._isActive, .comp.compMenu._outlined._primary:hover, .comp.compMenu._outlined._secondary._isActive, .comp.compMenu._outlined._secondary:hover, .comp.compMenu._outlined._tertiary._isActive, .comp.compMenu._outlined._tertiary:hover, .comp.compMenu._outlined._quaternary._isActive, .comp.compMenu._outlined._quaternary:hover, .comp.compMenu._outlined._quinary._isActive, .comp.compMenu._outlined._quinary:hover',
		noPrefix: true,
	},
	{
		groupName: 'Menu Color',
		displayName: 'Menu Dark Font Color',
		name: 'menuDarkFontColor',
		defaultValue: '<fontColorOne>',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._default._tertiary._isActive, .comp.compMenu._default._tertiary:hover, .comp.compMenu._outlined._tertiary._isActive, .comp.compMenu._outlined._tertiary:hover',
		noPrefix: true,
	},

	{
		groupName: 'Menu Text Decoration',
		displayName: 'Menu Text Decoration',
		name: 'menuTextDecoration',
		defaultValue: 'underline',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Menu Default Design Padding',
		name: 'defaultMenuDesignPadding',
		defaultValue: '5px',
		cssProperty: 'padding',
		selector: '.comp.compMenu._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Menu Outline Design Padding',
		name: 'outlineMenuDesignPadding',
		defaultValue: '5px 9px',
		cssProperty: 'padding',
		selector: '.comp.compMenu._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Text',
		displayName: 'Menu Text Design Padding',
		name: 'textMenuDesignPadding',
		defaultValue: '0px',
		cssProperty: 'padding',
		selector: '.comp.compMenu._text',
		noPrefix: true,
	},
	{
		groupName: 'Sides',
		displayName: 'Menu Sides Design Padding',
		name: 'sidesMenuDesignPadding',
		defaultValue: '4px 8px',
		cssProperty: 'padding',
		selector: '.comp.compMenu._sides',
		noPrefix: true,
	},
	{
		groupName: 'Top Bottom',
		displayName: 'Menu Top Bottom Design Padding',
		name: 'topbottomMenuDesignPadding',
		defaultValue: '4px 8px',
		cssProperty: 'padding',
		selector: '.comp.compMenu._topbottom',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Menu Default Design Text Alignment',
		name: 'defaultMenuDesignTextAlign',
		cssProperty: 'text-align',
		selector: '.comp.compMenu._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Menu Outline Design Text Alignment',
		name: 'outlineMenuDesignTextAlign',
		cssProperty: 'text-align',
		selector: '.comp.compMenu._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Text',
		displayName: 'Menu Text Design Text Alignment',
		name: 'textMenuDesignTextAlign',
		cssProperty: 'text-align',
		selector: '.comp.compMenu._text',
		noPrefix: true,
	},
	{
		groupName: 'Sides',
		displayName: 'Menu Sides Design Text Alignment',
		name: 'sidesMenuDesignTextAlign',
		cssProperty: 'text-align',
		selector: '.comp.compMenu._sides',
		noPrefix: true,
	},
	{
		groupName: 'Top Bottom',
		displayName: 'Menu Top Bottom Design Text Alignment',
		name: 'topbottomMenuDesignTextAlign',
		cssProperty: 'text-align',
		selector: '.comp.compMenu._topbottom',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Menu Default Design Border Radius',
		name: 'defaultMenuDesignBorderRadius',
		defaultValue: '3px',
		cssProperty: 'border-radius',
		selector: '.comp.compMenu._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Menu Outline Design Border Radius',
		name: 'outlineMenuDesignBorderRadius',
		defaultValue: '50px',
		cssProperty: 'border-radius',
		selector: '.comp.compMenu._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Text',
		displayName: 'Menu Text Design Border Radius',
		name: 'textMenuDesignBorderRadius',
		cssProperty: 'border-radius',
		selector: '.comp.compMenu._text',
		noPrefix: true,
	},
	{
		groupName: 'Sides',
		displayName: 'Menu Sides Design Border Radius',
		name: 'sidesMenuDesignBorderRadius',
		cssProperty: 'border-radius',
		selector: '.comp.compMenu._sides',
		noPrefix: true,
	},
	{
		groupName: 'Top Bottom',
		displayName: 'Menu Top Bottom Design Border Radius',
		name: 'topbottomMenuDesignBorderRadius',
		cssProperty: 'border-radius',
		selector: '.comp.compMenu._topbottom',
		noPrefix: true,
	},

	{
		groupName: 'Menu Font',
		displayName: 'Menu Font Weight',
		name: 'menuFontWeight',
		defaultValue: '700',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._text._primary._isActive, .comp.compMenu._text._primary:hover, .comp.compMenu._text._secondary._isActive, .comp.compMenu._text._secondary:hover, .comp.compMenu._text._tertiary._isActive, .comp.compMenu._text._tertiary:hover, .comp.compMenu._text._quaternary._isActive, .comp.compMenu._text._quaternary:hover, .comp.compMenu._text._quinary._isActive, .comp.compMenu._text._quinary:hover',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Menu Default Design Active Border',
		name: 'defaultMenuDesignActiveBorder',
		cssProperty: 'border',
		selector: '.comp.compMenu._default._isActive, .comp.compMenu._default:hover',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Menu Outline Design Active Border',
		name: 'outlineMenuDesignActiveBorder',
		defaultValue: '1px solid transparent',
		cssProperty: 'border',
		selector: '.comp.compMenu._outlined._isActive, .comp.compMenu._outlined:hover',
		noPrefix: true,
	},
	{
		groupName: 'Text',
		displayName: 'Menu Text Design Active Border',
		name: 'textMenuDesignActiveBorder',
		cssProperty: 'border',
		selector: '.comp.compMenu._text._isActive, .comp.compMenu._text:hover',
		noPrefix: true,
	},
	{
		groupName: 'Sides',
		displayName: 'Menu Sides Design Active Border',
		name: 'sideMenuDesignActiveBorder',
		defaultValue: '1px solid transparent, 1px solid, 1px solid transparent, 1px solid',
		cssProperty: 'border',
		selector: '.comp.compMenu._sides._isActive, .comp.compMenu._sides:hover',
		noPrefix: true,
	},
	{
		groupName: 'Top Bottom',
		displayName: 'Menu Top Bottom Design Active Border',
		name: 'topbottomMenuDesignActiveBorder',
		defaultValue: '1px solid, 1px solid transparent, 1px solid, 1px solid transparent',
		cssProperty: 'border',
		selector: '.comp.compMenu._topbottom._isActive, .comp.compMenu._topbottom:hover',
		noPrefix: true,
	},

	{
		groupName: 'Default',
		displayName: 'Menu Default Design Border',
		name: 'defaultMenuDesignBorder',
		cssProperty: 'border',
		selector: '.comp.compMenu._default',
		noPrefix: true,
	},
	{
		groupName: 'Outline',
		displayName: 'Menu Outline Design Border',
		name: 'outlineMenuDesignBorder',
		defaultValue: '1px solid',
		cssProperty: 'border',
		selector: '.comp.compMenu._outlined',
		noPrefix: true,
	},
	{
		groupName: 'Text',
		displayName: 'Menu Text Design Border',
		name: 'textMenuDesignBorder',
		cssProperty: 'border',
		selector: '.comp.compMenu._text',
		noPrefix: true,
	},
	{
		groupName: 'Sides',
		displayName: 'Menu Sides Design Border',
		name: 'sidesMenuDesignBorder',
		defaultValue: '1px solid transparent',
		cssProperty: 'border',
		selector: '.comp.compMenu._sides',
		noPrefix: true,
	},
	{
		groupName: 'Top Bottom',
		displayName: 'Menu Top Bottom Design Border',
		name: 'topbottomMenuDesignBorder',
		defaultValue: '1px solid transparent',
		cssProperty: 'border',
		selector: '.comp.compMenu._topbottom',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
