import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		groupName: '',
		displayName: '',
		name: 'menuFont',
		defaultValue: '<primaryFont>',
		description: 'Default font of the Menu',
		cssProperty: '',
		selector: '',
		noPrefix: false,
	},

	{
		groupName: '',
		displayName: '',
		name: 'defaultDesignFont',
		defaultValue: '<menuFont>',
		description: 'Font in Default Design',
		cssProperty: 'font',
		selector: '.comp.compMenu._default',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'outlineDesignFont',
		defaultValue: '<menuFont>',
		description: 'Font in Outline Design',
		cssProperty: 'font',
		selector: '.comp.compMenu._outlined',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'textDesignFont',
		defaultValue: '<menuFont>',
		description: 'Font in Text Design',
		cssProperty: 'font',
		selector: '.comp.compMenu._text',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'sidesDesignFont',
		defaultValue: '<menuFont>',
		description: 'Font in Sides Design',
		cssProperty: 'font',
		selector: '.comp.compMenu._sides',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'topbottomDesignFont',
		defaultValue: '<menuFont>',
		description: 'Font in Top Bottom Design',
		cssProperty: 'font',
		selector: '.comp.compMenu._topbottom',
		noPrefix: true,
	},

	{
		groupName: '',
		displayName: '',
		name: 'primaryMenuColor',
		defaultValue: '<backgroundColorOne>',
		description: 'Background Color One used in application',
		cssProperty: '',
		selector: '',
		noPrefix: false,
	},
	{
		groupName: '',
		displayName: '',
		name: 'secondaryMenuColor',
		defaultValue: '<backgroundColorTwo>',
		description: 'Background Color Two used in application',
		cssProperty: '',
		selector: '',
		noPrefix: false,
	},
	{
		groupName: '',
		displayName: '',
		name: 'tertiaryMenuColor',
		defaultValue: '<backgroundColorThree>',
		description: 'Background Color Three used in application',
		cssProperty: '',
		selector: '',
		noPrefix: false,
	},
	{
		groupName: '',
		displayName: '',
		name: 'quaternaryMenuColor',
		defaultValue: '<backgroundColorFour>',
		description: 'Background Color Four used in application',
		cssProperty: '',
		selector: '',
		noPrefix: false,
	},
	{
		groupName: '',
		displayName: '',
		name: 'quinaryMenuColor',
		defaultValue: '<backgroundColorFive>',
		description: 'Background Color Five used in application',
		cssProperty: '',
		selector: '',
		noPrefix: false,
	},

	{
		groupName: '',
		displayName: '',
		name: 'menuFontColor',
		defaultValue: '<fontColorEight>',
		description: 'Menu Font Color',
		cssProperty: '',
		selector: '',
		noPrefix: false,
	},
	{
		groupName: '',
		displayName: '',
		name: 'menuLightFontColor',
		defaultValue: '<fontColorTwo>',
		description: 'Menu Light Font Color',
		cssProperty: '',
		selector: '',
		noPrefix: false,
	},
	{
		groupName: '',
		displayName: '',
		name: 'menuDarkFontColor',
		defaultValue: '<fontColorOne>',
		description: 'Menu Dark Font Color',
		cssProperty: '',
		selector: '',
		noPrefix: false,
	},

	{
		groupName: '',
		displayName: '',
		name: 'menuBorder',
		defaultValue: '1px solid',
		description: 'Menu Border Style',
		cssProperty: '',
		selector: '',
		noPrefix: false,
	},
	{
		groupName: '',
		displayName: '',
		name: 'menuTextDecoration',
		defaultValue: 'underline',
		description: 'Menu Text Decoration',
		cssProperty: '',
		selector: '',
		noPrefix: false,
	},

	{
		groupName: '',
		displayName: '',
		name: 'defaultDesignPadding',
		defaultValue: '5px',
		description: 'Padding in Default Design',
		cssProperty: 'padding',
		selector: '.comp.compMenu._default',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'outlineDesignPadding',
		defaultValue: '5px 9px',
		description: 'Padding in Outline Design',
		cssProperty: 'padding',
		selector: '.comp.compMenu._outlined',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'textDesignPadding',
		defaultValue: '0px',
		description: 'Padding in Text Design',
		cssProperty: 'padding',
		selector: '.comp.compMenu._text',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'sidesDesignPadding',
		defaultValue: '4px 8px',
		description: 'Padding in Sides Design',
		cssProperty: 'padding',
		selector: '.comp.compMenu._sides',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'topbottomDesignPadding',
		defaultValue: '4px 8px',
		description: 'Padding in Top Bottom Design',
		cssProperty: 'padding',
		selector: '.comp.compMenu._topbottom',
		noPrefix: true,
	},

	{
		groupName: '',
		displayName: '',
		name: 'defaultDesignTextAlign',
		defaultValue: '',
		description: 'TextAlign in Default Design',
		cssProperty: 'textAlign',
		selector: '.comp.compMenu._default',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'outlineDesignTextAlign',
		defaultValue: '',
		description: 'TextAlign in Outline Design',
		cssProperty: 'textAlign',
		selector: '.comp.compMenu._outlined',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'textDesignTextAlign',
		defaultValue: '',
		description: 'TextAlign in Text Design',
		cssProperty: 'textAlign',
		selector: '.comp.compMenu._text',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'sidesDesignTextAlign',
		defaultValue: '',
		description: 'TextAlign in Sides Design',
		cssProperty: 'textAlign',
		selector: '.comp.compMenu._sides',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'topbottomDesignTextAlign',
		defaultValue: '',
		description: 'TextAlign in Top Bottom Design',
		cssProperty: 'textAlign',
		selector: '.comp.compMenu._topbottom',
		noPrefix: true,
	},

	{
		groupName: '',
		displayName: '',
		name: 'defaultDesignBorderRadius',
		defaultValue: '3px',
		description: 'BorderRadius in Default Design',
		cssProperty: 'border-radius',
		selector: '.comp.compMenu._default',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'outlineDesignBorderRadius',
		defaultValue: '3px',
		description: 'BorderRadius in Outline Design',
		cssProperty: 'border-radius',
		selector: '.comp.compMenu._outlined',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'textDesignBorderRadius',
		defaultValue: '0.5',
		description: 'BorderRadius in Text Design',
		cssProperty: 'border-radius',
		selector: '.comp.compMenu._text',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'sidesDesignBorderRadius',
		defaultValue: '3px',
		description: 'BorderRadius in Sides Design',
		cssProperty: 'border-radius',
		selector: '.comp.compMenu._sides',
		noPrefix: true,
	},
	{
		groupName: '',
		displayName: '',
		name: 'topbottomDesignBorderRadius',
		defaultValue: '3px',
		description: 'BorderRadius in Top Bottom Design',
		cssProperty: 'border-radius',
		selector: '.comp.compMenu._topbottom',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
