import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		name: 'menuTextDecoration',
		cssProperty: 'text-decoration',
		displayName: 'Text Decoration',
		description: 'Text decroation of the menu',
		defaultValue: 'none',
		selector: ' ',
	},
	{
		groupName: 'Design1',
		displayName: 'Font of simple menu design one',
		name: 'simpleMenuDesignOneFont',
		defaultValue: '12px <mainFontFamily>',
		description: 'Font of the menu',
		cssProperty: 'font',
		selector: '.comp.compMenu._simpleMenuDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design1',
		displayName: 'Color',
		name: 'simpleMenuDesignOneColor',
		defaultValue: '#33333380',
		description: 'The color of the simple menu design one',
		cssProperty: 'color',
		selector: '.comp.compMenu._simpleMenuDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design1',
		displayName: 'font weight',
		name: 'simpleMenuDesignOnefontWeight',
		defaultValue: '400',
		description: 'The font weight of the simple menu design one font-weight',
		cssProperty: 'font-weight',
		selector: '.comp.compMenu._simpleMenuDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design1',
		displayName: 'line height',
		name: 'simpleMenuDesignOneLineHeight',
		defaultValue: '14px',
		description: 'The color of the simple menu design one line height',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._simpleMenuDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design1',
		displayName: 'Color',
		name: 'simpleMenuDesignOneColorHoverSelected',
		defaultValue: '#08705C',
		description: 'The hover and selected color of the simple menu design one',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._simpleMenuDesign1:hover, .comp.compMenu._simpleMenuDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design1',
		displayName: 'font weight of design one hover and active ',
		name: 'simpleMenuDesignOneFontWeightHoverSelected',
		defaultValue: '700',
		description: 'The hover and selected font weight of the simple menu design one',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._simpleMenuDesign1:hover, .comp.compMenu._simpleMenuDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design2',
		displayName: 'Font of simple menu design Two',
		name: 'simpleMenuDesignTwoFont',
		defaultValue: '<simpleMenuDesignOneFont>',
		description: 'Font of the menu',
		cssProperty: 'font',
		selector: '.comp.compMenu._simpleMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design2',
		displayName: 'Color',
		name: 'simpleMenuDesignTwoColor',
		defaultValue: '<simpleMenuDesignOneColor>',
		description: 'The color of the simple menu design Two',
		cssProperty: 'color',
		selector: '.comp.compMenu._simpleMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design2',
		displayName: 'font weight',
		name: 'simpleMenuDesignTwofontWeight',
		defaultValue: '<simpleMenuDesignOnefontWeight>',
		description: 'The font weight of the simple menu design Two ',
		cssProperty: 'font-weight',
		selector: '.comp.compMenu._simpleMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design2',
		displayName: 'line height',
		name: 'simpleMenuDesignTwoLineHeight',
		defaultValue: '<simpleMenuDesignOneLineHeight>',
		description: 'The color of the simple menu design Two ',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._simpleMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design2',
		displayName: 'padding left',
		name: 'simpleMenuDesignTwoPaddingLeft',
		defaultValue: '8px',
		description: 'The padding left of the simple menu design Two ',
		cssProperty: 'padding-left',
		selector: '.comp.compMenu._simpleMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design2',
		displayName: 'padding right',
		name: 'simpleMenuDesignTwoPaddingRight',
		defaultValue: '<simpleMenuDesignTwoPaddingLeft>',
		description: 'The padding right of the simple menu design Two ',
		cssProperty: 'padding-right',
		selector: '.comp.compMenu._simpleMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design2',
		displayName: 'Border left',
		name: 'simpleMenuDesignTwoBorderLeftInActive',
		defaultValue: '1px solid transparent',
		description: 'The Border left of the simple menu design Two ',
		cssProperty: 'border-left',
		selector: '.comp.compMenu._simpleMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design2',
		displayName: 'Border right',
		name: 'simpleMenuDesignTwoBorderRightInActive',
		defaultValue: '<simpleMenuDesignTwoBorderLeftInActive>',
		description: 'The Border right of the simple menu design Two ',
		cssProperty: 'border-right',
		selector: '.comp.compMenu._simpleMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design2',
		displayName: 'Border left',
		name: 'simpleMenuDesignTwoBorderLeft',
		defaultValue: '1px solid #52BD94',
		description: 'The Border left of the simple menu design Two ',
		cssProperty: 'border-left',
		selector:
			'.comp.compMenu._simpleMenuDesign2:hover, .comp.compMenu._simpleMenuDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design2',
		displayName: 'Border right',
		name: 'simpleMenuDesignTwoBorderRight',
		defaultValue: '<simpleMenuDesignTwoBorderLeft>',
		description: 'The Border right of the simple menu design Two line height',
		cssProperty: 'border-right',
		selector:
			'.comp.compMenu._simpleMenuDesign2:hover, .comp.compMenu._simpleMenuDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design2',
		displayName: 'Color',
		name: 'simpleMenuDesignTwoColorHoverSelected',
		defaultValue: '#52BD94',
		description: 'The hover and selected color of the simple menu design Two',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._simpleMenuDesign2:hover, .comp.compMenu._simpleMenuDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design2',
		displayName: 'font weight of design Two hover and active ',
		name: 'simpleMenuDesignTwoFontWeightHoverSelected',
		defaultValue: '<simpleMenuDesignOnefontWeight>',
		description: 'The hover and selected font weight of the simple menu design Two',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._simpleMenuDesign2:hover, .comp.compMenu._simpleMenuDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design3',
		displayName: 'Font of simple menu design Three',
		name: 'simpleMenuDesignThreeFont',
		defaultValue: '13px <mainFontFamily>',
		description: 'Font of the menu',
		cssProperty: 'font',
		selector: '.comp.compMenu._simpleMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design3',
		displayName: 'Color',
		name: 'simpleMenuDesignThreeColor',
		defaultValue: '<simpleMenuDesignOneColor>',
		description: 'The color of the simple menu design Three',
		cssProperty: 'color',
		selector: '.comp.compMenu._simpleMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design3',
		displayName: 'font weight',
		name: 'simpleMenuDesignThreefontWeight',
		defaultValue: '<simpleMenuDesignOnefontWeight>',
		description: 'The font weight of the simple menu design Three ',
		cssProperty: 'font-weight',
		selector: '.comp.compMenu._simpleMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design3',
		displayName: 'line height',
		name: 'simpleMenuDesignThreeLineHeight',
		defaultValue: '<simpleMenuDesignOneLineHeight>',
		description: 'The color of the simple menu design Three ',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._simpleMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design3',
		displayName: 'padding top',
		name: 'simpleMenuDesignThreePaddingLeft',
		defaultValue: '1px',
		description: 'The padding left of the simple menu design Three ',
		cssProperty: 'padding-top',
		selector: '.comp.compMenu._simpleMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design3',
		displayName: 'padding bottom',
		name: 'simpleMenuDesignThreePaddingRight',
		defaultValue: '<simpleMenuDesignThreePaddingLeft>',
		description: 'The padding right of the simple menu design Three ',
		cssProperty: 'padding-bottom',
		selector: '.comp.compMenu._simpleMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design3',
		displayName: 'Border top',
		name: 'simpleMenuDesignThreeBorderLeft',
		defaultValue: '1px solid #FFC728',
		description: 'The Border left of the simple menu design Three ',
		cssProperty: 'border-top',
		selector:
			'.comp.compMenu._simpleMenuDesign3:hover, .comp.compMenu._simpleMenuDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design3',
		displayName: 'Border bottom',
		name: 'simpleMenuDesignThreeBorderRight',
		defaultValue: '<simpleMenuDesignThreeBorderLeft>',
		description: 'The Border right of the simple menu design Three line height',
		cssProperty: 'border-bottom',
		selector:
			'.comp.compMenu._simpleMenuDesign3:hover, .comp.compMenu._simpleMenuDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design3',
		displayName: 'Color',
		name: 'simpleMenuDesignThreeColorHoverSelected',
		defaultValue: '#FFC728',
		description: 'The hover and selected color of the simple menu design Three',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._simpleMenuDesign3:hover, .comp.compMenu._simpleMenuDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design3',
		displayName: 'font weight of design Three hover and active ',
		name: 'simpleMenuDesignThreeFontWeightHoverSelected',
		defaultValue: '<simpleMenuDesignOnefontWeight>',
		description: 'The hover and selected font weight of the simple menu design Three',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._simpleMenuDesign3:hover, .comp.compMenu._simpleMenuDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design4',
		displayName: 'Color',
		name: 'coloredMenuDesignOneColor',
		defaultValue: '<simpleMenuDesignOneColor>',
		description: 'The color of the coloured menu design One',
		cssProperty: 'color',
		selector: '.comp.compMenu._colouredMenuDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design4',
		displayName: 'Font ',
		name: 'coloredMenuDesignOneFont',
		defaultValue: '12px <mainFontFamily>',
		description: 'Font of the coloured menu design One',
		cssProperty: 'font',
		selector: '.comp.compMenu._colouredMenuDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design4',
		displayName: 'Font Weight',
		name: 'coloredMenuDesignOneFontWeight',
		defaultValue: '<simpleMenuDesignOnefontWeight>',
		description: 'The font weight of the coloured menu design  One',
		cssProperty: 'font-weight',
		selector: '.comp.compMenu._colouredMenuDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design4',
		displayName: 'Line Height',
		name: 'coloredMenuDesignOneLineHeight',
		defaultValue: '<simpleMenuDesignOneLineHeight>',
		description: 'The color of the coloured menu design  One',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._colouredMenuDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design4',
		displayName: 'Padding ',
		name: 'coloredMenuDesignOnePadding',
		defaultValue: '5px ',
		description: 'The padding  of the coloured menu design  One',
		cssProperty: 'padding',
		selector: '.comp.compMenu._colouredMenuDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design4',
		displayName: 'Color on Hover',
		name: 'coloredMenuDesignOneHoverAndActiveColor',
		defaultValue: '#ffffff',
		description: 'The hover and selected color of the coloured menu design  One',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._colouredMenuDesign1:hover, .comp.compMenu._colouredMenuDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design4',
		displayName: 'Font Weight On Hover and Active',
		name: 'coloredMenuDesignOneHoverAndActiveFontWeight',
		defaultValue: '500',
		description: 'The hover and selected font weight of the coloured menu design  One',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._colouredMenuDesign1:hover, .comp.compMenu._colouredMenuDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design4',
		displayName: 'Background Color',
		name: 'coloredMenuDesignOneBackgroundColorOnHover',
		defaultValue: '#EC6B5F',
		description: 'The background of the coloured menu design  One',
		cssProperty: 'background-color',
		selector:
			'.comp.compMenu._colouredMenuDesign1:hover, .comp.compMenu._colouredMenuDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design4',
		displayName: 'Border ',
		name: 'coloredMenuDesignOneBorderHover',
		defaultValue: '',
		description: 'The Border left of the coloured menu design  One',
		cssProperty: 'border',
		selector:
			'.comp.compMenu._colouredMenuDesign1:hover, .comp.compMenu._colouredMenuDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design4',
		displayName: 'Border Radius ',
		name: 'coloredMenuDesignOneBorderRadius',
		defaultValue: '2px',
		description: 'The Border Bottom Right Radius of the coloured menu design  One',
		cssProperty: 'border-radius',
		selector:
			'.comp.compMenu._colouredMenuDesign1:hover, .comp.compMenu._colouredMenuDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design5',
		displayName: 'Color',
		name: 'coloredMenuDesignTwoColor',
		defaultValue: '<coloredMenuDesignOneColor>',
		description: 'The color of the coloured menu design Two',
		cssProperty: 'color',
		selector: '.comp.compMenu._colouredMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design5',
		displayName: 'Font ',
		name: 'coloredMenuDesignTwoFont',
		defaultValue: '<coloredMenuDesignOneFont>',
		description: 'Font of the coloured menu design Two',
		cssProperty: 'font',
		selector: '.comp.compMenu._colouredMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design5',
		displayName: 'Font Weight',
		name: 'coloredMenuDesignTwoFontWeight',
		defaultValue: '<coloredMenuDesignOneFontWeight>',
		description: 'The font weight of the coloured menu design  Two',
		cssProperty: 'font-weight',
		selector: '.comp.compMenu._colouredMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design5',
		displayName: 'Line Height',
		name: 'coloredMenuDesignTwoLineHeight',
		defaultValue: '<coloredMenuDesignOneLineHeight>',
		description: 'The color of the coloured menu design  Two',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._colouredMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design5',
		displayName: 'Padding ',
		name: 'coloredMenuDesignTwoPadding',
		defaultValue: '5px 9px 5px 9px',
		description: 'The padding  of the coloured menu design  Two',
		cssProperty: 'padding',
		selector: '.comp.compMenu._colouredMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design5',
		displayName: 'Color on Hover',
		name: 'coloredMenuDesignTwoHoverAndActiveColor',
		defaultValue: '<coloredMenuDesignOneHoverAndActiveColor>',
		description: 'The hover and selected color of the coloured menu design  Two',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._colouredMenuDesign2:hover, .comp.compMenu._colouredMenuDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design5',
		displayName: 'Font Weight On Hover and Active',
		name: 'coloredMenuDesignTwoHoverAndActiveFontWeight',
		defaultValue: '<coloredMenuDesignOneHoverAndActiveFontWeight>',
		description: 'The hover and selected font weight of the coloured menu design  Two',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._colouredMenuDesign2:hover, .comp.compMenu._colouredMenuDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design5',
		displayName: 'Background Color',
		name: 'coloredMenuDesignTwoBackgroundColorOnHover',
		defaultValue: '#08705C',
		description: 'The background of the coloured menu design  Two',
		cssProperty: 'background-color',
		selector:
			'.comp.compMenu._colouredMenuDesign2:hover, .comp.compMenu._colouredMenuDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design5',
		displayName: 'Border ',
		name: 'coloredMenuDesignTwoBorder',
		defaultValue: '',
		description: 'The Border left of the coloured menu design  Two',
		cssProperty: 'border',
		selector:
			'.comp.compMenu._colouredMenuDesign2:hover, .comp.compMenu._colouredMenuDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design5',
		displayName: 'Border Radius ',
		name: 'coloredMenuDesignTwoBorderRadius',
		defaultValue: '50px',
		description: 'The Border Bottom Right Radius of the coloured menu design  Two',
		cssProperty: 'border-radius',
		selector:
			'.comp.compMenu._colouredMenuDesign2:hover, .comp.compMenu._colouredMenuDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design6',
		displayName: 'Color',
		name: 'coloredMenuDesignThreeColor',
		defaultValue: '#4D7FEECC',
		description: 'The color of the coloured menu design Three',
		cssProperty: 'color',
		selector: '.comp.compMenu._colouredMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design6',
		displayName: 'Font ',
		name: 'coloredMenuDesignThreeFont',
		defaultValue: '<coloredMenuDesignOneFont>',
		description: 'Font of the coloured menu design Three',
		cssProperty: 'font',
		selector: '.comp.compMenu._colouredMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design6',
		displayName: 'Font Weight',
		name: 'coloredMenuDesignThreeFontWeight',
		defaultValue: '<simpleMenuDesignOnefontWeight>',
		description: 'The font weight of the coloured menu design  Three',
		cssProperty: 'font-weight',
		selector: '.comp.compMenu._colouredMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design6',
		displayName: 'Line Height',
		name: 'coloredMenuDesignThreeLineHeight',
		defaultValue: '<coloredMenuDesignOneLineHeight>',
		description: 'The color of the coloured menu design  Three',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._colouredMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design6',
		displayName: 'Padding ',
		name: 'coloredMenuDesignThreePadding',
		defaultValue: '5px 9px 5px 9px',
		description: 'The padding left of the coloured menu design  Three',
		cssProperty: 'padding',
		selector: '.comp.compMenu._colouredMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design6',
		displayName: 'Color on Hover',
		name: 'coloredMenuDesignThreeHoverAndActiveColor',
		defaultValue: '#4D7FEE',
		description: 'The hover and selected color of the coloured menu design  Three',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._colouredMenuDesign3:hover, .comp.compMenu._colouredMenuDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design6',
		displayName: 'Font Weight On Hover and Active',
		name: 'coloredMenuDesignThreeHoverAndActiveFontWeight',
		defaultValue: '<coloredMenuDesignOneHoverAndActiveFontWeight>',
		description: 'The hover and selected font weight of the coloured menu design  Three',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._colouredMenuDesign3:hover, .comp.compMenu._colouredMenuDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design6',
		displayName: 'Background Color',
		name: 'coloredMenuDesignThreeBackgroundColor',
		defaultValue: '',
		description: 'The background of the coloured menu design  Three',
		cssProperty: 'background-color',
		selector:
			'.comp.compMenu._colouredMenuDesign3:hover, .comp.compMenu._colouredMenuDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design6',
		displayName: 'Border ',
		name: 'coloredMenuDesignThreeBorder',
		defaultValue: '1px solid #4D7FEE',
		description: 'The Border  of the coloured menu design  Three',
		cssProperty: 'border',
		selector:
			'.comp.compMenu._colouredMenuDesign3:hover, .comp.compMenu._colouredMenuDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design6',
		displayName: 'Border Radius ',
		name: 'coloredMenuDesignThreeBorderRadius',
		defaultValue: '<coloredMenuDesignTwoBorderRadius>',
		description: 'The Border Bottom Right Radius of the coloured menu design  Three',
		cssProperty: 'border-radius',
		selector:
			'.comp.compMenu._colouredMenuDesign3:hover, .comp.compMenu._colouredMenuDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design7',
		displayName: 'Color',
		name: 'FilledMenuDesignOneColor',
		defaultValue: '<coloredMenuDesignOneHoverAndActiveColor>',
		description: 'The color of the Filled menu design One',
		cssProperty: 'color',
		selector: '.comp.compMenu._filledMenuDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design7',
		displayName: 'Font ',
		name: 'FilledMenuDesignOneFont',
		defaultValue: '<coloredMenuDesignOneFont>',
		description: 'Font of the Filled menu design One',
		cssProperty: 'font',
		selector: '.comp.compMenu._filledMenuDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design7',
		displayName: 'Font Weight',
		name: 'FilledMenuDesignOneFontWeight',
		defaultValue: '<coloredMenuDesignOneFontWeight>',
		description: 'The font weight of the Filled menu design  One',
		cssProperty: 'font-weight',
		selector: '.comp.compMenu._filledMenuDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design7',
		displayName: 'Line Height',
		name: 'FilledMenuDesignOneLineHeight',
		defaultValue: '<coloredMenuDesignOneLineHeight>',
		description: 'The color of the Filled menu design  One',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._filledMenuDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design7',
		displayName: 'Padding ',
		name: 'FilledMenuDesignOnePadding',
		defaultValue: '2px',
		description: 'The padding left of the Filled menu design  One',
		cssProperty: 'padding',
		selector: '.comp.compMenu._filledMenuDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design7',
		displayName: 'Color on Hover',
		name: 'FilledMenuDesignOneHoverAndActiveColor',
		defaultValue: '<coloredMenuDesignOneHoverAndActiveColor>',
		description: 'The hover and selected color of the Filled menu design  One',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._filledMenuDesign1:hover, .comp.compMenu._filledMenuDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design7',
		displayName: 'Font Weight On Hover and Active',
		name: 'FilledMenuDesignOneHoverAndActiveFontWeight',
		defaultValue: '<coloredMenuDesignOneHoverAndActiveFontWeight>',
		description: 'The hover and selected font weight of the Filled menu design  One',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._filledMenuDesign1:hover, .comp.compMenu._filledMenuDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design7',
		displayName: 'Background Color',
		name: 'FilledMenuDesignOneBackgroundColor',
		defaultValue: '',
		description: 'The background of the Filled menu design  One',
		cssProperty: 'background-color',
		selector:
			'.comp.compMenu._filledMenuDesign1:hover, .comp.compMenu._filledMenuDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design7',
		displayName: 'Border ',
		name: 'FilledMenuDesignOneBorder',
		defaultValue: '',
		description: 'The Border  of the Filled menu design  One',
		cssProperty: 'border',
		selector:
			'.comp.compMenu._filledMenuDesign1:hover, .comp.compMenu._filledMenuDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design7',
		displayName: 'Border Radius ',
		name: 'FilledMenuDesignOneBorderRadius',
		defaultValue: '',
		description: 'The Border Bottom Right Radius of the Filled menu design  One',
		cssProperty: 'border-top-left-radius',
		selector:
			'.comp.compMenu._filledMenuDesign1:hover, .comp.compMenu._filledMenuDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design7',
		displayName: 'Border Bottom',
		name: 'FilledMenuDesignOneBorderBottom',
		defaultValue: '1px solid #ffffff',
		description: 'The Border bottom  of the Filled menu design  One',
		cssProperty: 'border-bottom',
		selector:
			'.comp.compMenu._filledMenuDesign1:hover, .comp.compMenu._filledMenuDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design8',
		displayName: 'Color',
		name: 'FilledMenuDesignTwoColor',
		defaultValue: '#FFC728',
		description: 'The color of the Filled menu design Two',
		cssProperty: 'color',
		selector: '.comp.compMenu._filledMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design8',
		displayName: 'Font ',
		name: 'FilledMenuDesignTwoFont',
		defaultValue: '<coloredMenuDesignOneFont>',
		description: 'Font of the Filled menu design Two',
		cssProperty: 'font',
		selector: '.comp.compMenu._filledMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design8',
		displayName: 'Font Weight',
		name: 'FilledMenuDesignTwoFontWeight',
		defaultValue: '<coloredMenuDesignOneFontWeight>',
		description: 'The font weight of the Filled menu design  Two',
		cssProperty: 'font-weight',
		selector: '.comp.compMenu._filledMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design8',
		displayName: 'Line Height',
		name: 'FilledMenuDesignTwoLineHeight',
		defaultValue: '<coloredMenuDesignOneLineHeight>',
		description: 'The color of the Filled menu design  Two',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._filledMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design8',
		displayName: 'Padding ',
		name: 'FilledMenuDesignTwoPadding',
		defaultValue: '',
		description: 'The padding left of the Filled menu design  Two',
		cssProperty: 'padding',
		selector: '.comp.compMenu._filledMenuDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design8',
		displayName: 'Color on Hover',
		name: 'FilledMenuDesignTwoHoverAndActiveColor',
		defaultValue: '<FilledMenuDesignTwoColor>',
		description: 'The hover and selected color of the Filled menu design  Two',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._filledMenuDesign2:hover, .comp.compMenu._filledMenuDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design8',
		displayName: 'Font Weight On Hover and Active',
		name: 'FilledMenuDesignTwoHoverAndActiveFontWeight',
		defaultValue: '<simpleMenuDesignOneFontWeightHoverSelected>',
		description: 'The hover and selected font weight of the Filled menu design  Two',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._filledMenuDesign2:hover, .comp.compMenu._filledMenuDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design8',
		displayName: 'Background Color',
		name: 'FilledMenuDesignTwoBackgroundColor',
		defaultValue: '',
		description: 'The background of the Filled menu design  Two',
		cssProperty: 'background-color',
		selector:
			'.comp.compMenu._filledMenuDesign2:hover, .comp.compMenu._filledMenuDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design8',
		displayName: 'Border ',
		name: 'FilledMenuDesignTwoBorder',
		defaultValue: '',
		description: 'The Border  of the Filled menu design  Two',
		cssProperty: 'border',
		selector:
			'.comp.compMenu._filledMenuDesign2:hover, .comp.compMenu._filledMenuDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design8',
		displayName: 'Border Radius ',
		name: 'FilledMenuDesignTwoBorderRadius',
		defaultValue: '',
		description: 'The Border Bottom Right Radius of the Filled menu design  Two',
		cssProperty: 'border-top-left-radius',
		selector:
			'.comp.compMenu._filledMenuDesign2:hover, .comp.compMenu._filledMenuDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design8',
		displayName: 'Border Bottom',
		name: 'FilledMenuDesignTwoBorderBottom',
		defaultValue: '',
		description: 'The Border bottom  of the Filled menu design  Two',
		cssProperty: 'border-bottom',
		selector:
			'.comp.compMenu._filledMenuDesign2:hover, .comp.compMenu._filledMenuDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design9',
		displayName: 'Color',
		name: 'FilledMenuDesignThreeColor',
		defaultValue: '<simpleMenuDesignTwoColorHoverSelected>',
		description: 'The color of the Filled menu design Three',
		cssProperty: 'color',
		selector: '.comp.compMenu._filledMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design9',
		displayName: 'Font ',
		name: 'FilledMenuDesignThreeFont',
		defaultValue: '<coloredMenuDesignOneFont>',
		description: 'Font of the Filled menu design Three',
		cssProperty: 'font',
		selector: '.comp.compMenu._filledMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design9',
		displayName: 'Font Weight',
		name: 'FilledMenuDesignThreeFontWeight',
		defaultValue: '<coloredMenuDesignOneFontWeight>',
		description: 'The font weight of the Filled menu design  Three',
		cssProperty: 'font-weight',
		selector: '.comp.compMenu._filledMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design9',
		displayName: 'Line Height',
		name: 'FilledMenuDesignThreeLineHeight',
		defaultValue: '<coloredMenuDesignOneLineHeight>',
		description: 'The color of the Filled menu design  Three',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._filledMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design9',
		displayName: 'Padding ',
		name: 'FilledMenuDesignThreePadding',
		defaultValue: '9px 18px 9px 18px',
		description: 'The padding left of the Filled menu design  Three',
		cssProperty: 'padding',
		selector: '.comp.compMenu._filledMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design9',
		displayName: 'Color on Hover',
		name: 'FilledMenuDesignThreeHoverAndActiveColor',
		defaultValue: '<FilledMenuDesignOneColor>',
		description: 'The hover and selected color of the Filled menu design  Three',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._filledMenuDesign3:hover, .comp.compMenu._filledMenuDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design9',
		displayName: 'Font Weight On Hover and Active',
		name: 'FilledMenuDesignThreeHoverAndActiveFontWeight',
		defaultValue: '<coloredMenuDesignOneFontWeight>',
		description: 'The hover and selected font weight of the Filled menu design  Three',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._filledMenuDesign3:hover, .comp.compMenu._filledMenuDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design9',
		displayName: 'Background Color Hover',
		name: 'FilledMenuDesignThreeBackgroundColor Hover',
		defaultValue: '<simpleMenuDesignTwoColorHoverSelected>',
		description: 'The background of the Filled menu design  Three',
		cssProperty: 'background-color',
		selector:
			'.comp.compMenu._filledMenuDesign3:hover, .comp.compMenu._filledMenuDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design9',
		displayName: 'Border ',
		name: 'FilledMenuDesignThreeBorder',
		defaultValue: '',
		description: 'The Border  of the Filled menu design  Three',
		cssProperty: 'border',
		selector:
			'.comp.compMenu._filledMenuDesign3:hover, .comp.compMenu._filledMenuDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design9',
		displayName: 'Border Radius ',
		name: 'FilledMenuDesignThreeBorderRadius',
		defaultValue: '',
		description: 'The Border Bottom Right Radius of the Filled menu design  Three',
		cssProperty: 'border-top-left-radius',
		selector:
			'.comp.compMenu._filledMenuDesign3:hover, .comp.compMenu._filledMenuDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design9',
		displayName: 'Border Bottom',
		name: 'FilledMenuDesignThreeBorderBottom',
		defaultValue: '',
		description: 'The Border bottom  of the Filled menu design  Three',
		cssProperty: 'border-bottom',
		selector:
			'.comp.compMenu._filledMenuDesign3:hover, .comp.compMenu._filledMenuDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design9',
		displayName: 'Background Color',
		name: 'FilledMenuDesignThreeBackgroundColor',
		defaultValue: 'rgba(82, 189, 148, 0.2)',
		description: 'The background of the Filled menu design  Three',
		cssProperty: 'background-color',
		selector: '.comp.compMenu._filledMenuDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design10',
		displayName: 'Color',
		name: 'FilledMenuDesignFourColor',
		defaultValue: '#333333',
		description: 'The color of the Filled menu design Four',
		cssProperty: 'color',
		selector: '.comp.compMenu._filledMenuDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Design10',
		displayName: 'Font ',
		name: 'FilledMenuDesignFourFont',
		defaultValue: '<coloredMenuDesignOneFont>',
		description: 'Font of the Filled menu design Four',
		cssProperty: 'font',
		selector: '.comp.compMenu._filledMenuDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Design10',
		displayName: 'Font Weight',
		name: 'FilledMenuDesignFourFontWeight',
		defaultValue: '<coloredMenuDesignOneHoverAndActiveFontWeight>',
		description: 'The font weight of the Filled menu design  Four',
		cssProperty: 'font-weight',
		selector: '.comp.compMenu._filledMenuDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Design10',
		displayName: 'Line Height',
		name: 'FilledMenuDesignFourLineHeight',
		defaultValue: '<coloredMenuDesignOneLineHeight>',
		description: 'The color of the Filled menu design  Four',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._filledMenuDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Design10',
		displayName: 'Padding ',
		name: 'FilledMenuDesignFourPadding',
		defaultValue: '9px 18px 9px 18px',
		description: 'The padding left of the Filled menu design  Four',
		cssProperty: 'padding',
		selector: '.comp.compMenu._filledMenuDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Design10',
		displayName: 'Color on Hover',
		name: 'FilledMenuDesignFourHoverAndActiveColor',
		defaultValue: '<FilledMenuDesignFourColor>',
		description: 'The hover and selected color of the Filled menu design  Four',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._filledMenuDesign4:hover, .comp.compMenu._filledMenuDesign4._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design10',
		displayName: 'Font Weight On Hover and Active',
		name: 'FilledMenuDesignFourHoverAndActiveFontWeight',
		defaultValue: '<coloredMenuDesignOneFontWeight>',
		description: 'The hover and selected font weight of the Filled menu design  Four',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._filledMenuDesign4:hover, .comp.compMenu._filledMenuDesign4._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design10',
		displayName: 'Background Color Hover',
		name: 'FilledMenuDesignFourBackgroundColor Hover',
		defaultValue: '<FilledMenuDesignTwoColor>',
		description: 'The background of the Filled menu design  Four',
		cssProperty: 'background-color',
		selector:
			'.comp.compMenu._filledMenuDesign4:hover, .comp.compMenu._filledMenuDesign4._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design10',
		displayName: 'Border Hover',
		name: 'FilledMenuDesignFourBorderHover',
		defaultValue: '',
		description: 'The Border  of the Filled menu design  Four',
		cssProperty: 'border',
		selector:
			'.comp.compMenu._filledMenuDesign4:hover, .comp.compMenu._filledMenuDesign4._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design10',
		displayName: 'Border Radius Hover',
		name: 'FilledMenuDesignFourBorderRadiusHover',
		defaultValue: '<coloredMenuDesignTwoBorderRadius>',
		description: 'The Border Bottom Right Radius of the Filled menu design  Four',
		cssProperty: 'border-radius',
		selector:
			'.comp.compMenu._filledMenuDesign4:hover, .comp.compMenu._filledMenuDesign4._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design10',
		displayName: 'Border Bottom',
		name: 'FilledMenuDesignFourBorderBottom',
		defaultValue: '',
		description: 'The Border bottom  of the Filled menu design  Four',
		cssProperty: 'border-bottom',
		selector:
			'.comp.compMenu._filledMenuDesign4:hover, .comp.compMenu._filledMenuDesign4._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design10',
		displayName: 'Background Color',
		name: 'FilledMenuDesignFourBackgroundColor',
		defaultValue: '',
		description: 'The background of the Filled menu design  Four',
		cssProperty: 'background-color',
		selector: '.comp.compMenu._filledMenuDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Design10',
		displayName: 'Border ',
		name: 'FilledMenuDesignFourBorder',
		defaultValue: '1px solid #333333',
		description: 'The Border  of the Filled menu design  Four',
		cssProperty: 'border',
		selector: '.comp.compMenu._filledMenuDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Design10',
		displayName: 'Border Radius Hover',
		name: 'FilledMenuDesignFourBorderRadius',
		defaultValue: '<coloredMenuDesignTwoBorderRadius>',
		description: 'The Border Bottom Right Radius of the Filled menu design  Four',
		cssProperty: 'border-radius',
		selector: '.comp.compMenu._filledMenuDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Design11',
		displayName: 'Color',
		name: 'FilledMenuDesignFiveColor',
		defaultValue: '#61C554',
		description: 'The color of the Filled menu design Five',
		cssProperty: 'color',
		selector: '.comp.compMenu._filledMenuDesign5',
		noPrefix: true,
	},
	{
		groupName: 'Design11',
		displayName: 'Font ',
		name: 'FilledMenuDesignFiveFont',
		defaultValue: '<simpleMenuDesignOneFont>',
		description: 'Font of the Filled menu design Five',
		cssProperty: 'font',
		selector: '.comp.compMenu._filledMenuDesign5',
		noPrefix: true,
	},
	{
		groupName: 'Design11',
		displayName: 'Font Weight',
		name: 'FilledMenuDesignFiveFontWeight',
		defaultValue: '<coloredMenuDesignOneHoverAndActiveFontWeight>',
		description: 'The font weight of the Filled menu design  Five',
		cssProperty: 'font-weight',
		selector: '.comp.compMenu._filledMenuDesign5',
		noPrefix: true,
	},
	{
		groupName: 'Design11',
		displayName: 'Line Height',
		name: 'FilledMenuDesignFiveLineHeight',
		defaultValue: '<coloredMenuDesignOneLineHeight>',
		description: 'The color of the Filled menu design  Five',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._filledMenuDesign5',
		noPrefix: true,
	},
	{
		groupName: 'Design11',
		displayName: 'Padding ',
		name: 'FilledMenuDesignFivePadding',
		defaultValue: '7px 10px 7px 10px',
		description: 'The padding left of the Filled menu design  Five',
		cssProperty: 'padding',
		selector: '.comp.compMenu._filledMenuDesign5',
		noPrefix: true,
	},
	{
		groupName: 'Design11',
		displayName: 'Color on Hover',
		name: 'FilledMenuDesignFiveHoverAndActiveColor',
		defaultValue: '<coloredMenuDesignOneHoverAndActiveColor>',
		description: 'The hover and selected color of the Filled menu design  Five',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._filledMenuDesign5:hover, .comp.compMenu._filledMenuDesign5._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design11',
		displayName: 'Font Weight On Hover and Active',
		name: 'FilledMenuDesignFiveHoverAndActiveFontWeight',
		defaultValue: '<coloredMenuDesignOneFontWeight>',
		description: 'The hover and selected font weight of the Filled menu design  Five',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._filledMenuDesign5:hover, .comp.compMenu._filledMenuDesign5._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design11',
		displayName: 'Background Color Hover',
		name: 'FilledMenuDesignFiveBackgroundColor Hover',
		defaultValue: '<FilledMenuDesignFiveColor>',
		description: 'The background of the Filled menu design  Five',
		cssProperty: 'background-color',
		selector:
			'.comp.compMenu._filledMenuDesign5:hover, .comp.compMenu._filledMenuDesign5._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design11',
		displayName: 'Border Hover',
		name: 'FilledMenuDesignFiveBorderHover',
		defaultValue: 'none',
		description: 'The Border  of the Filled menu design  Five',
		cssProperty: 'border',
		selector:
			'.comp.compMenu._filledMenuDesign5:hover, .comp.compMenu._filledMenuDesign5._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design11',
		displayName: 'Border Radius Hover',
		name: 'FilledMenuDesignFiveBorderRadiusHover',
		defaultValue: '<coloredMenuDesignTwoBorderRadius>',
		description: 'The Border Bottom Right Radius of the Filled menu design  Five',
		cssProperty: 'border-radius',
		selector:
			'.comp.compMenu._filledMenuDesign5:hover, .comp.compMenu._filledMenuDesign5._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design11',
		displayName: 'Border Bottom',
		name: 'FilledMenuDesignFiveBorderBottom',
		defaultValue: '',
		description: 'The Border bottom  of the Filled menu design  Five',
		cssProperty: 'border-bottom',
		selector:
			'.comp.compMenu._filledMenuDesign5:hover, .comp.compMenu._filledMenuDesign5._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design11',
		displayName: 'Background Color',
		name: 'FilledMenuDesignFiveBackgroundColor',
		defaultValue: '#61C55433',
		description: 'The background of the Filled menu design  Five',
		cssProperty: 'background-color',
		selector: '.comp.compMenu._filledMenuDesign5',
		noPrefix: true,
	},
	{
		groupName: 'Design11',
		displayName: 'Border ',
		name: 'FilledMenuDesignFiveBorder',
		defaultValue: '',
		description: 'The Border  of the Filled menu design  Five',
		cssProperty: 'border',
		selector: '.comp.compMenu._filledMenuDesign5',
		noPrefix: true,
	},
	{
		groupName: 'Design11',
		displayName: 'Border Radius Hover',
		name: 'FilledMenuDesignFiveBorderRadius',
		defaultValue: '<coloredMenuDesignTwoBorderRadius>',
		description: 'The Border Bottom Right Radius of the Filled menu design  Five',
		cssProperty: 'border-radius',
		selector: '.comp.compMenu._filledMenuDesign5',
		noPrefix: true,
	},

	{
		groupName: 'Design12',
		displayName: 'Font of simple menu design one',
		name: 'simpleMenuDesignOneFontVertical',
		defaultValue: '<simpleMenuDesignOneFont>',
		description: 'Font of the menu vertical',
		cssProperty: 'font',
		selector: '.comp.compMenu._simpleMenuHorizontalDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design12',
		displayName: 'Color',
		name: 'simpleMenuDesignOneColorVertical',
		defaultValue: '<simpleMenuDesignOneColor>',
		description: 'The color of the simple menu design one Vertical',
		cssProperty: 'color',
		selector: '.comp.compMenu._simpleMenuHorizontalDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design12',
		displayName: 'font weight',
		name: 'simpleMenuDesignOnefontWeightVertical',
		defaultValue: '<simpleMenuDesignOnefontWeight>',
		description: 'The font weight of the simple menu design one Vertical font-weight ',
		cssProperty: 'font-weight',
		selector: '.comp.compMenu._simpleMenuHorizontalDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design12',
		displayName: 'line height',
		name: 'simpleMenuDesignOneLineHeightVertical',
		defaultValue: '<simpleMenuDesignOneLineHeight>',
		description: 'The color of the simple menu design one Vertical line height',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._simpleMenuHorizontalDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design13',
		displayName: 'Font ',
		name: 'simpleMenuDesignTwoFontHorizontal',
		defaultValue: '12px Averia Libre',
		description: 'Font of the menu design Two Horizontal',
		cssProperty: 'font',
		selector: '.comp.compMenu._simpleMenuHorizontalDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design13',
		displayName: 'Color',
		name: 'simpleMenuDesignTwoColorHorizontal',
		defaultValue: '<simpleMenuDesignOneColor>',
		description: 'The color of the simple menu design Two Horizontal',
		cssProperty: 'color',
		selector: '.comp.compMenu._simpleMenuHorizontalDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design13',
		displayName: 'font weight',
		name: 'simpleMenuDesignTwofontWeightHorizontal',
		defaultValue: '<simpleMenuDesignOneFontWeightHoverSelected>',
		description: 'The font weight of the simple menu design Two Horizontal font-weight ',
		cssProperty: 'font-weight',
		selector: '.comp.compMenu._simpleMenuHorizontalDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design13',
		displayName: 'line height',
		name: 'simpleMenuDesignTwoLineHeightHorizontal',
		defaultValue: '<simpleMenuDesignOneLineHeight>',
		description: 'The color of the simple menu design Two Horizontal line height',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._simpleMenuHorizontalDesign2',
		noPrefix: true,
	},
	{
		groupName: 'Design13',
		displayName: 'font weight of design one hover and active ',
		name: 'simpleMenuDesignTwoFontWeightHorizontalHoverSelected',
		defaultValue: '300',
		description: 'The hover and selected font weight of the simple menu design Two',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._simpleMenuHorizontalDesign2:hover, .comp.compMenu._simpleMenuHorizontalDesign2._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design14',
		displayName: 'Font of simple menu design two',
		name: 'simpleMenuDesignThreeFontHorizontal',
		defaultValue: '<simpleMenuDesignOneFont>',
		description: 'Font of the menu Horizontal Three',
		cssProperty: 'font',
		selector: '.comp.compMenu._simpleMenuHorizontalDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design14',
		displayName: 'Color',
		name: 'simpleMenuDesignThreeColorHorizontal',
		defaultValue: '<simpleMenuDesignOneColor>',
		description: 'The color of the simple menu design Three Horizontal',
		cssProperty: 'color',
		selector: '.comp.compMenu._simpleMenuHorizontalDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design14',
		displayName: 'font weight',
		name: 'simpleMenuDesignThreefontWeightHorizontal',
		defaultValue: '<coloredMenuDesignOneHoverAndActiveFontWeight>',
		description: 'The font weight of the simple menu design Three Horizontal font-weight ',
		cssProperty: 'font-weight',
		selector: '.comp.compMenu._simpleMenuHorizontalDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design14',
		displayName: 'line height',
		name: 'simpleMenuDesignThreeLineHeightHorizontal',
		defaultValue: '<simpleMenuDesignOneLineHeight>',
		description: 'The color of the simple menu design Three Horizontal line height',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._simpleMenuHorizontalDesign3',
		noPrefix: true,
	},
	{
		groupName: 'Design14',
		displayName: 'font weight of design one hover and active ',
		name: 'simpleMenuDesignThreeFontWeightHorizontalHoverSelected',
		defaultValue: '<simpleMenuDesignOneFontWeightHoverSelected> ',
		description: 'The hover and selected font weight of the simple menu design Three',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._simpleMenuHorizontalDesign3:hover, .comp.compMenu._simpleMenuHorizontalDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design14',
		displayName: 'ColorHover',
		name: 'simpleMenuDesignThreeColorHoverSelected',
		defaultValue: ' <FilledMenuDesignFourColor>',
		description: 'The hover and selected color of the simple menu design three',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._simpleMenuHorizontalDesign3:hover, .comp.compMenu._simpleMenuHorizontalDesign3._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design15',
		displayName: 'Font of simple menu design four',
		name: 'simpleMenuDesignFourFontHorizontal',
		defaultValue: '12px Avenir Next Condensed',
		description: 'Font of the menu Horizontal',
		cssProperty: 'font',
		selector: '.comp.compMenu._simpleMenuHorizontalDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Design15',
		displayName: 'Color',
		name: 'simpleMenuDesignFourColorHorizontal',
		defaultValue: '<simpleMenuDesignOneColor>',
		description: 'The color of the simple menu design Four Horizontal',
		cssProperty: 'color',
		selector: '.comp.compMenu._simpleMenuHorizontalDesign4',
		noPrefix: true,
	},

	{
		groupName: 'Design15',
		displayName: 'line height',
		name: 'simpleMenuDesignFourLineHeightHorizontal',
		defaultValue: '<simpleMenuDesignOneLineHeight>',
		description: 'The color of the simple menu design Four Horizontal line height',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._simpleMenuHorizontalDesign4',
		noPrefix: true,
	},
	{
		groupName: 'Design15',
		displayName: 'border bottom',
		name: 'simpleMenuDesignFourBorderBottomHorizontal',
		defaultValue: '1px solid #EC6B5F',
		description: 'The border bottom of simple menu design four horizontal',
		cssProperty: 'border-bottom',
		selector:
			'.comp.compMenu._simpleMenuHorizontalDesign4:hover, .comp.compMenu._simpleMenuHorizontalDesign4._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design15',
		displayName: 'font weight',
		name: 'simpleMenuDesignFourfontWeightHorizontal',
		defaultValue: '600',
		description: 'The font weight of the simple menu design Three Horizontal font-weight ',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._simpleMenuHorizontalDesign4:hover, .comp.compMenu._simpleMenuHorizontalDesign4._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design15',
		displayName: 'ColorHover',
		name: 'simpleMenuDesignFourColorHoverSelected',
		defaultValue: '<coloredMenuDesignOneBackgroundColorOnHover>',
		description: 'The hover and selected color of the simple menu design three',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._simpleMenuHorizontalDesign4:hover, .comp.compMenu._simpleMenuHorizontalDesign4._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design16',
		displayName: 'Color',
		name: 'FilledMenuDesignOneVerticalColor',
		defaultValue: '<simpleMenuDesignTwoColorHoverSelected>',
		description: 'The color of the Filled menu design OneHorizontal',
		cssProperty: 'color',
		selector: '.comp.compMenu._filledMenuHorizontalDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design16',
		displayName: 'Font ',
		name: 'FilledMenuDesignOneVerticalFont',
		defaultValue: '<coloredMenuDesignOneFont>',
		description: 'Font of the Filled menu design OneHorizontal',
		cssProperty: 'font',
		selector: '.comp.compMenu._filledMenuHorizontalDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design16',
		displayName: 'Font Weight',
		name: 'FilledMenuDesignOneVerticalFontWeight',
		defaultValue: '<coloredMenuDesignOneFontWeight>',
		description: 'The font weight of the Filled menu design  OneHorizontal',
		cssProperty: 'font-weight',
		selector: '.comp.compMenu._filledMenuHorizontalDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design16',
		displayName: 'Line Height',
		name: 'FilledMenuDesignOneVerticalLineHeight',
		defaultValue: '<coloredMenuDesignOneLineHeight>',
		description: 'The color of the Filled menu design  OneHorizontal',
		cssProperty: 'line-height',
		selector: '.comp.compMenu._filledMenuHorizontalDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design16',
		displayName: 'Padding ',
		name: 'FilledMenuDesignOneVerticalPadding',
		defaultValue: '6px 10px 6px 10px',
		description: 'The padding left of the Filled menu design  OneHorizontal',
		cssProperty: 'padding',
		selector: '.comp.compMenu._filledMenuHorizontalDesign1',
		noPrefix: true,
	},
	{
		groupName: 'Design16',
		displayName: 'Color on Hover',
		name: 'FilledMenuDesignOneVerticalHoverAndActiveColor',
		defaultValue: '<FilledMenuDesignOneColor>',
		description: 'The hover and selected color of the Filled menu design  OneHorizontal',
		cssProperty: 'color',
		selector:
			'.comp.compMenu._filledMenuHorizontalDesign1:hover, .comp.compMenu._filledMenuHorizontalDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design16',
		displayName: 'Font Weight On Hover and Active',
		name: 'FilledMenuDesignOneVerticalHoverAndActiveFontWeight',
		defaultValue: '<coloredMenuDesignOneFontWeight>',
		description: 'The hover and selected font weight of the Filled menu design  OneHorizontal',
		cssProperty: 'font-weight',
		selector:
			'.comp.compMenu._filledMenuHorizontalDesign1:hover, .comp.compMenu._filledMenuHorizontalDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design16',
		displayName: 'Background Color Hover',
		name: 'FilledMenuDesignOneVerticalBackgroundColor Hover',
		defaultValue: '<simpleMenuDesignTwoColorHoverSelected>',
		description: 'The background of the Filled menu design  OneHorizontal',
		cssProperty: 'background-color',
		selector:
			'.comp.compMenu._filledMenuHorizontalDesign1:hover, .comp.compMenu._filledMenuHorizontalDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design16',
		displayName: 'Border ',
		name: 'FilledMenuDesignOneVerticalBorder',
		defaultValue: '',
		description: 'The Border  of the Filled menu design  OneHorizontal',
		cssProperty: 'border',
		selector:
			'.comp.compMenu._filledMenuHorizontalDesign1:hover, .comp.compMenu._filledMenuHorizontalDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design16',
		displayName: 'Border Radius ',
		name: 'FilledMenuDesignOneVerticalBorderRadius',
		defaultValue: '50px',
		description: 'The Border Bottom Right Radius of the Filled menu design  OneHorizontal',
		cssProperty: 'border-radius',
		selector:
			'.comp.compMenu._filledMenuHorizontalDesign1:hover, .comp.compMenu._filledMenuHorizontalDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design16',
		displayName: 'Border Bottom',
		name: 'FilledMenuDesignOneVerticalBorderBottom',
		defaultValue: '',
		description: 'The Border bottom  of the Filled menu design  OneHorizontal',
		cssProperty: 'border-bottom',
		selector:
			'.comp.compMenu._filledMenuHorizontalDesign1:hover, .comp.compMenu._filledMenuHorizontalDesign1._isActive',
		noPrefix: true,
	},
	{
		groupName: 'Design16',
		displayName: 'Background Color',
		name: 'FilledMenuDesignOneVerticalBackgroundColor',
		defaultValue: '',
		description: 'The background of the Filled menu design  OneHorizontal',
		cssProperty: 'background-color',
		selector: '.comp.compMenu._filledMenuHorizontalDesign1',
		noPrefix: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.defaultValue)
		.map(({ name, defaultValue }) => [name, defaultValue!]),
);
